owid/owid-grapher

- db/model/Gdoc/htmlToEnriched.ts
Many of our entries and articles have notices at the beginning saying when they were first published and last updated. 
In our old articles, these sentences were lifted into the article header, but the wp migration was putting them unceremoniously into the article body.
This PR adds code which identifies these phrases and puts them in a callout.
> Entry Emulator - Edit Notice

- db/model/Gdoc/Gdoc.ts
Encountered an issue where a post that was scheduled for Monday was featured in the atom feed.
This PR as is will fix that from happening (but in general I don't think we should/can schedule posts currently)
If we want to do this properly, we'll need to tighten up the way we handle times with the datepicker. 
Currently our DB is in UTC, but the times that the antd DatePicker chooses seem to be kind of random. The hour varies depending on which day you pick. If we want to schedule posts we'd want to be able to specify this or standardize it with a clearly specified explanation in the UI.
> 🐛 Exclude gdocs with future `publishedAt` dates from baking and atom feed

- adminSiteClient/ChartList.tsx
- adminSiteClient/ChartRow.tsx
- adminSiteClient/DatasetEditPage.tsx
- adminSiteClient/DatasetList.tsx
- adminSiteClient/EditTags.tsx
- adminSiteClient/EditableTags.tsx
- adminSiteClient/GdocsIndexPage.tsx
- adminSiteClient/GdocsStore.tsx
- adminSiteClient/PostsIndexPage.tsx
- adminSiteClient/TagBadge.tsx
- adminSiteClient/TagEditPage.tsx
- adminSiteClient/TagsIndexPage.tsx
- adminSiteServer/apiRouter.ts
- baker/algolia/indexToAlgolia.tsx
- baker/formatWordpressPost.tsx
- db/migrateWpPostsToArchieMl.ts
- db/model/Chart.ts
- db/model/Gdoc/Gdoc.ts
- db/model/Gdoc/htmlToEnriched.ts
- db/model/Post.ts
- db/wpdb.ts
- packages/@ourworldindata/utils/src/index.ts
- packages/@ourworldindata/utils/src/owidTypes.ts
- site/gdocs/OwidGdoc.tsx
Migrating the all charts block from entries into the Gdocs flow.
If we're on an entry with related charts, we add the block to the archie content before the first heading (which we assume to be after any introductory paragraphs)
I needed to handle the pcrm blocks in order to do this, because otherwise it was putting the all-charts block before their h3's, which wasn't right.
There are some newline parsing issues in the `htmlToEnriched` code, but fixing them would require refactoring a bunch of code with unknown consequences so I figured it's best to leave it alone since we'll be able to fix it easily in the gdoc once it's migrated.
I also fixed a little bug where the Preview button on the `/admin/posts` page was navigating to `/admin/posts/gdocs/some_id/preview` instead of …
> Entry Emulator - All Charts

- db/model/Gdoc/htmlToEnriched.ts
Some images are saved in the WP html with dimension data appended to them.
e.g.
`causes-of-death-2048x1024.png`
Which was making its way into the archie, despite the fact that [we only uploaded the source images to WP](https://github.com/owid/owid-grapher/blob/a04b880d763d073fe21153ebc288932895785082/devTools/uploadWordpressImagesToObjStorage/upload-wordpress-images-to-obj-storage.ts#L97) when we backed them up to drive.
The fixes that.
> 🐛 remove size suffix from migrated WP image filenames

- db/migration/1697464705200-PostsGdocsLinksDisplayOrder.ts
Needed by https://github.com/owid/etl/pull/1797
> :sparkles: add displayOrder column to posts_gdocs_variables_faqs table

- db/model/Gdoc/exampleEnrichedBlocks.ts
- db/model/Gdoc/rawToEnriched.ts
- packages/@ourworldindata/utils/src/owidTypes.ts
- site/gdocs/ArticleBlock.tsx
- site/gdocs/Video.tsx
- site/gdocs/centered-article.scss
For short silent videos, [autoplay is okay](https://accessibleweb.com/question-answer/does-wcag-allow-autoplay-of-videos/) - which will improve the flow of our Grapher redesign article (though it will add to the page size unless we implement an intersection observer for preloading)
https://github.com/owid/owid-grapher/assets/11844404/8383b675-d5b6-488e-b72a-2e2791c2cf94
> Video autoplay

- Makefile
- baker/Deployer.ts
- baker/ProgressStream.ts
- baker/buildAndDeploySite.ts
In #2781 I was a little too ambitious and removed some code that's necessary to deploy changes to the admin, so here goes.
> chore: re-add code necessary for deploying admin changes

- adminSiteClient/GdocsIndexPage.scss
- adminSiteClient/GdocsIndexPage.tsx
This PR changes the search in the GDocs index pages to work like the one on charts and indicators. 
This means it only matches continuous word fragments, not fuzzy filename like search where the characters can come up in any part of a long string as long as they are in order. Also, -term style queries work that exclude term.
The PR also adds a button stlye link to the documentation next to the add button.
> Better search on GDocs index page

- devTools/docker/sync-s3-images.sh
- site/README.md
`s3cmd` is really slow. Syncing images takes more than 3 minutes now, which is considerable time for our staging servers. Switching to `awscli` reduces the time to about 15s. (I'm not sure why is it so much faster, parallel sync perhaps?)
Moreover, using `.aws/config` is more intuitive than `~/.s3cfg`
> :sparkles: speed up image sync by replacing s3cmd with awscli

- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- We had a report that the entity selector opened for no apparent reason when clicking on the year button in the timeline
- My guess is that the year button was close to a line label that opens the entity selector on click
- Since the chart area space and the label itself are so small on mobile, we decided to disable opening the entity selector from the line label
> enhance(grapher): disable action on line label click for mobile

- adminSiteClient/EditorBasicTab.tsx
- When changing chart types (or adding y-dimensions), a random sample of entities are selected
- Apparently, that's annoying for authors; they would prefer to have entities persisted if possible (see [Slack](https://owid.slack.com/archives/C0149NKLZAM/p1696419244456579))
- Only sample entities when none are selected
> enhance(admin): persist entities when changing the chart type

- packages/@ourworldindata/grapher/src/mapCharts/MapChart.tsx
- packages/@ourworldindata/grapher/src/mapCharts/MapTooltip.tsx
Fixes #2695.
The problem here is that, for the chart mentioned in #2695, we have `max = 1` by chance, and then that makes it so we use `customValueLabels[1]` as a max label.
However, instead we want to use the label for the bin for value 1...
> fix(map-tooltip): show min/max label for correct bin

- packages/@ourworldindata/grapher/src/lineLegend/LineLegend.tsx
I stumbled over this when working on something else.
I don't quite understand the comment that explain why it was necessary to take into account the "Add country" button, but I assume that it's not relevant anymore since we have rewritten Grapher controls from scratch.
> chore(line-legend): remove unnecessary code

- _routes.json
- baker/SiteBaker.tsx
- baker/redirects.ts
- functions/grapher/[slug].ts
Work around Cloudflare's 2000 static redirects limit by handling redirects directly in the worker.
This works by baking a `grapher/_grapherRedirects.json` file as part of the baking process, where all grapher redirects always go.
The original `_redirects` file will then only contain WP redirects, plus some hardcoded ones.
I checked and we're currently down to just 506 redirects in the file now, so quite some room to spare.
I tried out the following variations and they all work:
- `/grapher/life-expectancy` goes through
- `/grapher/life-EXPECTANCY` redirects to lowercase
- `/grapher/life-expectancy/` removes trailing slash
- `/grapher/life-expectancy-globally-since-1770` redirects
- ^ this one also works with uppercase and a trailing slash mixed in
- …
> feat(redirects): handle grapher redirects in grapher worker

- adminSiteClient/ChartEditorPage.tsx
- adminSiteClient/EditorTextTab.tsx
- adminSiteClient/Forms.tsx
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
With descriptionShort being used as a fallback for the subtitle in a chart we now have seen some unfortunate cases that made it necessary to be able to control if the fallback should be used or not.
The reason why this is necessary is that some old charts do not have a subtitle. If we now update the indicator to have a descriptionShort then all of a sudden this desriptionShort would be used as subtitle which is maybe not what we want.
To fix this, the PR adds a link button to the subtitle text field in the chart admin. If a custom text is set then the button shows as "unlinked". If you click it the button links and you get whatever default the fallback chain provides (i.e. descriptionShort or no subtitle). 
For cases where there is currently no subtitle and you want to makes sure it stays …
> :sparkles: Add link/unlink button for the subtitle in the chart admin

- packages/@ourworldindata/components/src/styles/util.scss
- site/BlogIndexPage.tsx
- site/FrontPage.tsx
- site/css/homepage.scss
- site/css/mixins.scss
- site/owid.scss
from [slack](https://owid.slack.com/archives/C04TUH5UJA1/p1697036254239379)
- rename "Featured work" -> "Featured" (http://staging-site-latest-posts-title)
- rename "Our latest work" -> "Latest" 
(http://staging-site-latest-posts-title/latest)
- add subtitle (~~pending [decision on spacing](https://owid.slack.com/archives/C04TUH5UJA1/p1697955514767439?thread_ts=1697036254.239379&cid=C04TUH5UJA1)~~)
- accessibility improvements
- fixes https://github.com/owid/owid-grapher/issues/1971
> "Latest" title improvements

- adminSiteClient/EditorFeatures.tsx
- packages/@ourworldindata/grapher/src/barCharts/DiscreteBarChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedDiscreteBarChart.tsx
- The transforms functions that apply the missing data strategy to DiscreteBar charts and StackedDiscreteBar charts are buggy
- Luckily, none of our DiscreteBar/StackedDiscreteBar charts in the live db currently use the missing data strategy option (maybe a sign?!)
- As a hot fix, I simply remove the data missing strategy option for these chart types
- We might add them back in the future (or maybe not, cause apparently no-one has used these options for months)
- But we might want to make Grapher a bit smarter when it comes to missing data (I'll elaborate elsewhere)
> hotfix(grapher): remove missing data strategy for (stacked) discrete bar charts

- packages/@ourworldindata/grapher/src/modal/Modal.tsx
- In the chart revision tool, authors look at two charts side by side
- If one chart has a modal open, then clicking on the second chart closes the modal of the first one
- This makes it impossible to have both modals open at the same time
- This happens because any outside click is registered and dismisses the modal
- As a fix, I put in an additional check that checks whether the target that is clicked on is interactive
- If it is interactive, we assume the user didn't intend to dismiss the modal, so we keep it open
Is this a sensible solution?
<details>
<summary>Video of the bug:</summary>
https://github.com/owid/owid-grapher/assets/12461810/547a1ae8-4edc-4291-b6a6-36f5d33d5607
</details>
> fix(modal): don't dismiss when clicking on an interactive element

- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/modal/SourcesModal.stories.tsx
- packages/@ourworldindata/grapher/src/modal/SourcesModal.tsx
This PR introduces two different ways to iterate over the sources of a chart - a `columnsWithSourcesExtensive` and `columnsWithSourcesCondensed`. When rendering the sources at the bottom of the chart we want to only show the most relevant ones (i.e. hide stuff like population used for sizing a scatter) - for this we use the `Condensed` version. When showing the sources tab we use the Extensive so that all our sources are rendered there.
> Show only important sources in summaries

- site/DataPageV2Content.tsx
This mini PR fixes a few issues of when and how certain heading texts were displayed
> Fix datapage headings

- site/DataPageV2Content.tsx
This Pr is a stop gap measure until we have the proper redesigns of the "indicator flashcard" section below the chart that better deals with missing texts. What happens here is that the descriptionShort is always shown if present, the descriptionKey is shown as a list and a bug with the "go to FAQ" button is fixed
> Better key info block

- datapage/Datapage.ts
- site/DataPageV2Content.tsx
This PR improves the rendering of some dates and time ranges, updates the processing level (minor/major) text and fixes some minor wording issues.
> Better date displays - processing level display

- site/DataPageV2Content.tsx
At the right top of topic pages we show tags if they are given in the ETL. The tags are rendered as little pills and should link to the topic page that we have for this tag. Unfortunately, at this point we don't have the "authoritative links" stored with the tags and no association between tags and their topic pages so we slugify the text and 🤞. 
This PR improves the slugify function for this particular use case. It's not bullet proof but it makes sure that the system works for a few more of the important tags. Some remain broken until we store the links properly.
> Better automatic links to topic pages

- baker/GrapherBaker.tsx
- datapage/Datapage.ts
- db/migrateWpPostsToArchieMl.ts
- db/model/Post.ts
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/utils/src/Util.ts
- packages/@ourworldindata/utils/src/index.ts
- packages/@ourworldindata/utils/src/owidTypes.ts
- site/DataPageV2.tsx
- site/DataPageV2Content.tsx
- site/ExpandableToggle.scss
- site/gdocs/OwidGdoc.tsx
- site/gdocs/utils.tsx
This PR overhauls how we do citations on datapages. Max and Joe came up with a new way for how to cite data pages themselves (the last thing in the citation section) that needs the citation information of the related topic page. 
There are also various minor improvements to the display of sources/origins.
> Data pages: improve citations

- packages/@ourworldindata/components/src/IndicatorProcessing/IndicatorProcessing.tsx
- packages/@ourworldindata/components/src/index.ts
- site/DataPageV2Content.tsx
This PR extracts the processing information block into a separate component in the components repo
> Data pages: extract shared component IndicatorProcessing

- baker/BuildkiteTrigger.ts
- baker/DeployUtils.ts
Skipped builds (that happen when there's more than one build in the queue) were in an infinite loop, which eventually led to connection timeouts for those old builds. This PR adds all build states and handles them appropriately.
Additionally:
* await buildkite builds
* put back local bake when not baking on buildkite (enables baking on staging servers and local)
> :bug: don't leave buildkite handing for skipped builds

- db/migrateWpPostsToArchieMl.ts
- db/model/Gdoc/archieToEnriched.ts
- db/model/Gdoc/archieToGdoc.ts
- packages/@ourworldindata/utils/src/owidTypes.ts
- site/gdocs/OwidGdoc.tsx
Is it a hack if you use the code as was intended? 😁 
This adds an empty array to the gdoc content object's `sticky-nav` property, which causes the sticky nav to not render.
It was either this, or some sort of flag to hide the sticky nav. This seemed like the less intrusive way to handle it.
> Entry Emulator - hide sticky nav on linear topic pages

- adminSiteClient/Admin.tsx
- adminSiteClient/GdocsPreviewPage.tsx
- adminSiteClient/GdocsStore.tsx
- adminSiteClient/gdocsDeploy.ts
- adminSiteServer/apiRouter.ts
- site/hooks.ts
Autoupdating was causing lots of headaches when multiple clients were previewing the same document. The effort in fixing that class of issue seems to outweigh the marginal benefit of autoupdating, so I'm removing the autoupdating functionality altogether.
I also noticed that lightning updates hadn't been working properly for ages, so I've updated that code to fix the thing that was breaking it (Date comparisons) and made the declaration of light props more explicit and tied to our type validation so that it'll be harder to miss in the future.
> Remove Gdoc Preview autoupdating, fix lightning publishing

- datapage/Datapage.ts
- packages/@ourworldindata/grapher/src/modal/SourcesModal.tsx
This implements better fallback chains for the title of an indciator on both data pages and in the sources tab:
1. sources tab to: `display.name > indicator.title`
1. data page title to: `presentation.title_public > presentation.grapher_config.title > display.name > indicator.title`
> :sparkles: improve data page fallback chains

- packages/@ourworldindata/grapher/src/axis/Axis.ts
- packages/@ourworldindata/grapher/src/axis/AxisViews.tsx
Fixes #2850.
The issue here is that `bounds` are the bounds of the whole charting area, but the vertical axis has some extra bottom padding and the horizontal axis has some extra left padding:
```
V         |
e         |
r         |
t         |
i         |
c         |
a         |
l         |
|
a         |
x         |
i         |
s         |
|
-------------------------------------------------------------
PADDING   |                   Horizontal axis
```
By relying on `axis.range`, and in particular on the new `axis.rangeCenter` property, we can circumvent this issue.
> fix(axis): center axis labels

- functions/grapher/[slug].ts
The hot code path being the one where the user requests the correct slug from the very start.
This makes it such that redirects make a tiny bit longer, but non-redirects will be a bit quicker. And that should improve the overall expected response time by a bit.
> feat(functions): optimize grapher worker for the hot code path

- packages/@ourworldindata/grapher/src/dataTable/DataTable.tsx
- fixes https://github.com/owid/owid-grapher/issues/2831
- there are two code paths: "range" mode and "point" mode
- in "range" mode, a start and end year are selected and we show four columns: Start year, end year, absolute change, relative change
- in "point" mode, a single year is selected and we show a single column for that year
- in "point" mode, all is good
- tolerance is appropriately applied and no hundreds-years-away data points are used to fill an empty cell
- the issue is with the "range" mode
- here, we take the range of available data points within the current selection, and then apply min/max to get the values for the start and end point, i.e. if the user-selected time range is [1000, 2000] but we only have data for [1990, 2000], then we'll end up showing the 1990 value for …
> fix(data-table): respect tolerance

- db/migration/1698087308654-AddIndicatorShortNameToCatalogPath.ts
Implementation of https://github.com/owid/etl/issues/1823
* Append `#indicator_short_name` to catalogPath
* Add unique index on `catalogPath`
> :sparkles: add indicator shortName to catalogPath in variables table

- packages/@ourworldindata/core-table/src/CoreColumnDef.ts
- packages/@ourworldindata/core-table/src/CoreTableColumns.ts
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/core/LegacyToOwidTable.ts
- packages/@ourworldindata/grapher/src/modal/DownloadModal.tsx
- packages/@ourworldindata/grapher/src/modal/SourcesModal.tsx
- site/GrapherFigureView.tsx
Mild refactor of metadata handling in Grapher.
- Cleans up `CoreColumnDef` to closer resemble the given metadata json hierarchy
- In particular, `source` and a `presentation` objects are preserved
Other changes:
- Enables keyboard shortcuts on data pages, and adds a shortcut for the sources modal (clicking `s`)
> Sources modal: simplify CoreColumnDef

- baker/postUpdatedHook.ts
- db/migrateWpPostsToArchieMl.ts
- db/migration/1685653967284-PostsFeaturedImage.ts
- db/syncPostsToGrapher.ts
- packages/@ourworldindata/utils/src/owidTypes.ts
We didn't have all the other plumbing for featured images set up when this migration script was written. I'm trying to add it in now.
> Include featured image in wpPost -> ArchieML migration

- adminSiteClient/gdocsDeploy.ts
- settings/clientSettings.ts
The DoD document requires we rebake dods.json and grapher embeds that reference them. 
So this PR disqualifies it from ever being a lightning update candidate.
> 🐛 Don't trigger lightning updates if dod document is updated

- baker/SiteBaker.tsx
- baker/algolia/indexToAlgolia.tsx
- baker/sitemap.ts
- db/db.ts
- db/wpdb.ts
- packages/@ourworldindata/utils/src/owidTypes.ts
Fixes https://github.com/owid/owid-grapher/issues/2726
Uses the `wbdb.getPosts()` method (and fixes up / simplifies some incorrect typing) which correctly filters out reusable blocks. There's a default filter for posts that end in `-country-profile` in this method, but AFAICT that's to filter out the templates, not the pages themselves - those still get added:
As well as default country pages:
Also uses the `Gdoc.getPublishedGdocs()` method which filters out fragments and unpublished documents.
On my local environment:
`sitemap.xml` length before: 6056
`sitemap.xml` length after: 6043
The filtered pages:
```
http://localhost:3030/co2-country-profile
http://localhost:3030/coronavirus-country-profile
http://localhost:3030/energy-country-profile …
```
> 🐛 filter non-editorial content out of sitemap

- packages/@ourworldindata/grapher/src/chart/ChartInterface.ts
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/dataTable/DataTable.tsx
- packages/@ourworldindata/grapher/src/scatterCharts/ScatterPlotChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/MarimekkoChart.tsx
fixes #2692
- In scatter plot charts, entities without data along the x- and y-axis ended up being displayed in the data table because they did have data for the size dimension (often, the size dimension is population)
This PR makes sure that only entities show up in the data table that are actually displayed in the chart:
- Entities in scatter plots that don't have data for the x- and y-dimension are removed from the table view
- Entities in scatter plots and Marimekko charts that were manually excluded by the author are also removed from the table view
- Grapher has a new computed property, `tableForDisplay`
- Each chart type optionally can have a `transformTableForDisplay` method that produces `tableForDisplay`
- `tableForDisplay` is passed to `<DataTable />`
> enhance(scatter): remove entities from the data table that are not displayed in the chart

- db/model/Gdoc/gdocToArchie.ts
- site/gdocs/ArticleBlock.tsx
Just two small improvements:
1. Renders explorers at 8 columns if `hideControls=true` is present in the query string.
2. Skips parsing native tables if we're not inside a `{.table}` block.
1. The alternative was turning `{.table-rows}` into its own component which was a lot of new code and would require a migration for any tables that had already been created.
> Smaller chromeless explorer embeds in articles & a fix for native tables crashing

- db/migrateWpPostsToArchieMl.ts
- site/gdocs/utils.tsx
Adds an anchor link to the all charts block for linear topic pages, and also updated the `LinkedA` component to not open in a new tab if it's an anchor link.
> Linear topic page all charts improvements

- .bundlewatch.config.json
- adminSiteClient/GdocsIndexPage.tsx
- baker/algolia/indexToAlgolia.tsx
- db/migrateWpPostsToArchieMl.ts
- db/model/Gdoc/htmlToEnriched.ts
- packages/@ourworldindata/utils/src/owidTypes.ts
- site/gdocs/OwidGdoc.tsx
- site/gdocs/OwidGdocHeader.tsx
- site/gdocs/topic-page.scss
Supersedes https://github.com/owid/owid-grapher/pull/2868
1. Adds a new type to the gdoc type enum that we can use to add custom behaviours for linear topic pages.
2. Increases the size of headings in linear topic pages to approximate the same hierarchy that they currently have with their super headings.
3. Adds logic to wrap headings that were originally h1's (i.e. the grey bar section headings) with horizontal rules.
> Adds new Gdoc type: `linear-topic-page`

- .bundlewatch.config.json
- package.json
- packages/@ourworldindata/components/src/IndicatorProcessing/IndicatorProcessing.tsx
- packages/@ourworldindata/components/src/IndicatorSources/IndicatorSources.tsx
- packages/@ourworldindata/components/src/SimpleMarkdownText.tsx
- yarn.lock
This PR adds the [react-remark](https://github.com/remarkjs/react-remark) library. This seems to be the best library for parsing markdown given the following requirements:
- We want parsing to be separate from rendering, with the ability to modify the AST in between
- We'd like extensions to be straightforward and ideally a nice ecosystem of plugins for things like mathematical formulas, tables etc
- We'd like to avoid `dangerouslySetInnerHTML` in React
This PR then replaces the rendering path of the SimpleMarkdownText component with the new parser. 
Bundle size increases by about 40KB minified + gzipped but I think this is an ok trade-off
> :sparkles: add react-remark library, test it in SimpleMarkdownText

- package.json
- packages/@ourworldindata/components/src/MarkdownTextWrap/MarkdownTextWrap.tsx
- packages/@ourworldindata/components/src/SimpleMarkdownText.tsx
- packages/@ourworldindata/components/src/markdown/mdast-util-find-and-replace.d.ts
- packages/@ourworldindata/components/src/markdown/remarkPlainLinks.ts
- yarn.lock
By default, plain link like https://domain.com are not shown as links in markdown (see [commonmark spec](https://spec.commonmark.org/0.30/#autolinks)) and instead have to be written in the `[text](https://domain.com)` style. 
This PR adds autolinking to plain links. This is done in two different way
- once for the SimpleMarkdown component that uses react-remark via a remark transformation plugin
- and once for the MarkdownTextWrap component by doing the translation as part of the mapping to IRNodes
In theory it should be possible to use the remark plugin in both cases, but navigating the set of interdependent libraries at the state two years ago is a pain and so I went for the two bespoke versions. When we upgrade our setup to be ESM everywhere we can upgrade to the latest versions of the …
> Markdown: turn plain URLs into links

- packages/@ourworldindata/grapher/src/core/Grapher.tsx
Fixes a bug where if there are more than 3 sources, grapher would sometimes say "undefined and other sources"
> 🐛 fix undefined in source display in grapher

- adminSiteClient/GdocsDiff.tsx
- adminSiteClient/gdocsDeploy.ts
- adminSiteServer/apiRouter.ts
- baker/DeployUtils.ts
- baker/SiteBaker.tsx
- baker/bakeGdocPost.ts
- baker/bakeGdocPosts.ts
- ops/buildkite/deploy-content
Fixes #2906.
❗ I didn't test this in any way yet!
The underlying issue here was that gdoc properties like `linkedDocuments` and `imageMetadata` didn't get populated in the lightning deploy code path (`bakeGDocPost`).
I instead extended `bakeGDocPosts` to optionally take an array of slugs that it should bake, and bake every published gdoc otherwise.
✅ In order to reenable lightning deploys, we will also have to revert https://github.com/owid/owid-grapher/commit/ab2b183b166d808f034d245ff8bb3061ed0aa583.
> fix(bake): lightning deploys populate gdoc metadata

- packages/@ourworldindata/components/src/TextWrap/TextWrap.test.ts
- packages/@ourworldindata/components/src/TextWrap/TextWrap.tsx
Before, we were producing invalid HTML/SVG in the footer (`origin URL | CC BY`) in some very rare cases, [like this one here](https://ourworldindata.org/grapher/thumbnail/co-emissions-per-capita?imWidth=1000&imHeight=1000).
> enhance: TextWrap opens and closes every HTML tag

- packages/@ourworldindata/grapher/src/footer/Footer.tsx
- packages/@ourworldindata/grapher/src/footer/FooterManager.ts
Clicking on "Learn more about this data" should scroll to the "Sources & Processing" Section on data pages, otherwise the sources modal should open.
There were a couple of problems here:
- We were relying on the the existence of the sources and processing section only, but that means that _any_ chart (including charts in the All Charts block) would scroll to the Sources & Processing Section
- We didn't handle the iframe case properly (should always open in a modal)
> fix(grapher): open sources modal when embedded

- devTools/svgTester/export-graphs.ts
- devTools/svgTester/utils.ts
So, I was curious about performance metrics of grapher, both loading time and memory usage.
To get an overview, I adapted the SVG Tester with some readouts for time taken and memory usage, and these will then be dumped into the `results.csv` file.
This is easy to do for time taken for rendering, but what's a bit more tricky is getting an accurate readout of the memory consumption (heap used).
To do this in a somewhat good way, I added a (kind of hacky) `--isolate` mode that will run all the exports sequentially, and runs each in a fresh process. This takes an awfully long time, but it is actually accurate.
If you're curious about the results we get out of this, the results on my machine I put into a Google Sheet here: https://docs.google.com/spreadsheets/d/1Wzz76EYyOT0vo6uqQVMvvAQh0tOJyxcy …
> enhance(svg-tester): capture performance data

- packages/@ourworldindata/grapher/src/slopeCharts/SlopeChart.tsx
To reproduce:
- Go to https://owid.cloud/admin/charts/2562/edit
- Change chart to slope chart
- Drag the start time handle to > 1950
The order of data points to be plotted was swapped for some data points. These should be ordered by time. If not, bad things happen (see screenshot).
> fix broken slope charts

- .eslintignore
- .vscode/launch.json
- Makefile
- baker/GrapherBaker.tsx
- baker/postUpdatedHook.ts
- db/migration/1692042923850-AddPostsLinks.ts
- db/model/PostLink.ts
- db/refreshPageviewsFromDatasette.ts
- db/syncPostsToGrapher.ts
- db/wpdb.ts
- package.json
- packages/@ourworldindata/utils/src/owidTypes.ts
- site/DataPageV2.tsx
- site/DataPageV2Content.tsx
- site/blocks/RelatedCharts.tsx
This PR implements #2379. It adds the missing link in our db from wordpress posts to charts that are used there. It then uses this new posts_links table together with the existing posts_gdocs_links table to find the related writing for a data page by going from indciator id -> charts using this indicator -> articles using this indicator.
The posts_links table was modelled on the posts_gdocs_links table as I thought that uniformity is more important than the optimal layout here. Extracting the links is a bit crudely done ATM in that it just uses regex's on the raw html tag instead of parsing the html and querying for a tags. The latter would give us the text content of the content that establishes the links which is probably often useful, but it would complicate and slow down the script. …
> :tada: Add related research and writing via content graph to data pages

- baker/GrapherBaker.tsx
During the bug bash for data pages we realized that just checking for single indicator charts with schemaVersion == 2 was a bit too lenient. The reason for this was that some datasets were converted to using Origin instead of Source which is enough to bump the schemaVersion, but no human had actually looked at these indicators.
This PR changes the criterium now so that single indicator charts are shown as data pages if the indicator is schemaVersion == 2 and at least one of the following fields is set:
- descriptionShort
- descriptionFromProducer
- descriptionKey
- descriptionProcessing
- presentation.titlePublic
> :hammer: restrict datapages to only charts with vars that have any description* set

- site/DataPageV2.tsx
- site/DataPageV2Content.tsx
basically re-applying 7eb70960b82411cdd23670adbe04139875cf4646 (#2466)
> fix(datapages): don't bind charts in the all charts block to the window

- ops/buildkite/build-code
Recently we had a production code deploy die - the lerna build reported no action needed and the cache to be used but then the typescript build complained about some things not existing in the lerna built packages. This PR disables lerna caching for production buildkite builds
> 🔨 disable nx cache for buildkite production builds

- packages/@ourworldindata/core-table/src/CoreTable.ts
❗ **Urgent, should be done by the 30th (Thursday)**
- fixes #2948
- Pablo A wants to publish a set of map charts on the 30th
- Some map charts are broken; the data is available in the Table and Chart tab, but not in the Map tab (see #2948)
- I traced it down to the tolerance computation in the MapChart's transformTable function, and then did a `git bisect` to find the bad commit
- The commit introducing this bug is a perf optimization: https://github.com/owid/owid-grapher/pull/2620/commits/d58bef8cbe24185d3a7284f4ca23586def996ee6
- Since it's marked as a perf optimization only, I'm inclined to remove it, which fixes the bug
@danyx23 since you were the one reviewing [Marcel's PR](https://github.com/owid/owid-grapher/pull/2620), do you think it's safe to do so?
> Revert perf optimization that breaks map charts

- packages/@ourworldindata/grapher/src/core/grapher.scss
- packages/@ourworldindata/grapher/src/modal/EmbedModal.scss
- packages/@ourworldindata/grapher/src/modal/EmbedModal.tsx
- packages/@ourworldindata/grapher/src/modal/SourcesModal.scss
Just getting rid of some code that used to be duplicated.
They look a bit different, but not by all that much. Left is what's currently live, right is the new one:
> refactor: use `<CodeSnippet>` in embed modal

- adminSiteServer/adminRouter.tsx
- adminSiteServer/mockSiteRouter.tsx
- baker/GrapherBaker.tsx
This PR changes how grapher configs are treated in data pages. Grapher configs coming from the ETL level grapher config are no longer taken into account on /grapher/ pages, only in pure datapage previews.
The PR also streamlines the code between previews and baking a bit.
Once our grapher admin can deal with defaults in a better way (i.e. show the user where defaults are used and given them an option to disable the default value) we should change this again.
> 🔨 Data pages: ignore indicator level grapher configs on /grapher/ pages for now

- packages/@ourworldindata/grapher/src/modal/SourcesKeyDataTable.scss
- packages/@ourworldindata/grapher/src/modal/SourcesModal.scss
- packages/@ourworldindata/grapher/src/modal/SourcesModal.tsx
- site/DataPageContent.scss
- site/DataPageV2Content.tsx
This PR renders descriptionShort as markdown and makes sure that DoD links are not underlined and instead retain the style they have site-wide.
I don't know if there is a better way to make sure that links that have the dod-span class are not underlined - @sophiamersmann if you would prefer another way of doing this in CSS then please let me know! 🙏
> 💄 render descriptionShort as markdown, fix DoD link display

- db/model/Gdoc/rawToEnriched.ts
I noticed that [quite a few of these](https://owid-datasette-y43qr.ondigitalocean.app/owid?sql=SELECT+COUNT%28slug%29+FROM+posts_gdocs+WHERE+content+LIKE+%22%25owid.cloud%25%22) have snuck into our google docs from the wp migration tool.
This PR adds a warning in the preview if one has persisted (I'm going to go through and fix them in any Gdocs I can find)
We could also add this block to `cheerioToSpan` if we wanted to prevent publishing any links to owid.cloud ever, but there might be valid cases where we want to do that, so I'm not sure.
```
if (url && url.includes("owid.cloud")) {
url = url.replace("owid.cloud", "ourworldindata.org")
}
```
> 🎉 add warning if linking to owid.cloud in gdocs

- site/DataPageContent.scss
- site/DataPageV2Content.tsx
The "About this data" Section should use the full width:
> :sparkles: (data-page) allow About this data section to use full width

- db/migration/1701280181658-FixPostLinksForeingKeyDeleteClause.ts
- db/syncPostsToGrapher.ts
This PR fixes the FK constraint from posts_gdocs to posts that was missing an ON DELETE CASCADE clause. 
It also adds reusable block tombstone comments - this is useful because we currently inline WP reusable blocks into the posts when we sync them from WP into the grapher DB. At the moment this does not leave any trace, but for planning some content migration work it would be useful to be able to query for these tombstones.
> :hammer: fix posts_links FK constraint, add reusable block tombstones

- adminSiteClient/TagEditPage.tsx
- adminSiteServer/apiRouter.ts
- baker/GrapherBaker.tsx
- baker/GrapherBakingUtils.ts
- baker/batchTagWithGpt.ts
- db/migration/1701450183524-TagTopicSlug.ts
- db/migration/1701459310622-RemoveIsTopic.ts
- db/model/Chart.ts
- db/model/Gdoc/GdocPost.ts
- packages/@ourworldindata/utils/src/owidTypes.ts
- site/DataPageV2.tsx
- site/DataPageV2Content.tsx
This PR replaces the `isTopic` boolean on Tags with a `slug` column and adds UI in the admin to set a Tag's slug.
This allows us to resolve datapage's `topicTagsLinks` ( `Tag["name"][]` ) into actual slugs instead of the good-enough heuristic we launched with. And it will allow us to do the same for data insights
I added some util functions that the site renderer uses to supply the correct mapping to datapages. There's a small & regrettable amount of prop drilling to get them in the right place so they can hydrate correctly.
> Topic tag slug resolver

- baker/siteRenderers.tsx
This random page that I didn't know existed had its query become ambiguous due to https://github.com/owid/owid-grapher/pull/2984
This PR fixes that
> 🐛 fix ambiguous slug reference in knex query

- adminSiteClient/PostsIndexPage.tsx
- adminSiteServer/apiRouter.ts
This PR replaces the search for posts. We used to have fuzzy search here like for filenames in sublime text but I think this is unsuited for finding posts. We now use the same search that we have for charts and gdocs posts. The fields to be searched are:
- title
- slug
- authors
- id
I also changed the behaviour a bit for how loading more works.
> Add better search for posts

- explorer/urlMigrations/LegacyCovidUrlMigration.ts
- explorerAdminServer/ExplorerRedirects.ts
The old COVID explorer redirect used to only take old legacy query params into account and discarded new query params - this PR fixes this
This only came into play if you went to the covid explorer via certain links, e.g. if you go to /coronavirus-data-explorer which then redirects to /explorers/coronavirus-data-explorer with a bunch of special logic. This logic needed updating as the old logic only took legacy query params into account.
> :hammer: update /coronavirus-data-explorer redirect

- db/wpdb.ts
One of the two queries did not correctly take the chart redirect into account to identify the correct slug to match on. This PR fixes the query and cleans the queries up a bit.
> 🔨 fix related research section in data pages when using chart redirects

- adminSiteClient/GdocsAdd.tsx
- adminSiteClient/GdocsIndexPage.tsx
- adminSiteClient/admin.scss
- adminSiteServer/apiRouter.ts
- packages/@ourworldindata/utils/src/GdocsConstants.ts
Changes:
- Stops the server from throwing an error if attempting to register an already-registered article*
- Allows searching by gdoc ID
- Fixes the validation for the gdoc URL input (which hadn't been working correctly for the last few months)
- Adds some hints if validation fails
https://github.com/owid/owid-grapher/assets/11844404/48ce7a8c-e897-4bbf-911b-e37bbbe88cd1
\* I was doing this semi-frequently on prod when debugging things and it seemed a bit overkill to get a notification in slack because of it
> Small gdocs index page enhancements

- adminSiteClient/TagEditPage.tsx
- db/migrateWpPostsToArchieMl.ts
- db/migration/1701803220442-GdocFrontMatterBooleans.ts
- db/model/Gdoc/GdocPost.ts
- db/model/Gdoc/archieToEnriched.ts
- packages/@ourworldindata/utils/src/owidTypes.ts
- site/DataPageContent.scss
- site/gdocs/ProminentLink.tsx
Fixes #2981 - preview: [after (many tags)](https://github.com/owid/owid-grapher/assets/11844404/2a8616a9-2df2-4128-be3f-6816fc12d76d) | [after (few tags)](https://github.com/owid/owid-grapher/assets/11844404/903ae1c0-779f-45f2-a095-93cd1443ad14) | [after (many tags mobile)](https://github.com/owid/owid-grapher/assets/11844404/0ff14ef5-6434-4da5-a265-cdabd3fd7e1c)
Changes gdocs to use proper booleans instead of `"true"` and `"false"` strings for front matter. This is obviously how it should have always been but I was a bit rushed 😇 The migration is overkill seeing as this only affects LTPs and none of them have `"sidebar-toc": "false"` (which would be [treated as truthy](https://github.com/owid/owid-grapher/blob/master/site/gdocs/OwidGdoc.tsx#L126) until the article was republished) but …
> Miscellaneous bug fixes for the site

- baker/algolia/configureAlgolia.ts
I am pretty sure this rejiggle can lead to some improvement in our search results.
See https://www.algolia.com/doc/guides/managing-results/relevance-overview/in-depth/ranking-criteria/ as a reference document.
Several notes:
- The default ranking in Algolia is `["typo","geo","words","filters","proximity","attribute","exact","custom"]`, and aligning our criteria closer to theirs is probably a good thing (they know what they are doing; we don't!)
- The distinction between [Attribute and proximity](https://www.algolia.com/doc/guides/managing-results/relevance-overview/in-depth/ranking-criteria/#attribute-and-proximity-combinations) is very interesting; and Algolia writes:
> This ordering is a subtle distinction. You should keep the default ranking [with proximity before attribute] since …
> chore(algolia): change sort ranking order

- packages/@ourworldindata/grapher/src/header/Header.tsx
- The title of interactive and static charts should be semibold
- But for some reason, if the title is semibold, sometimes the title text overflows with the logo (only for static charts, not for interactive one, which is quite weird)
- As a quick "fix" I had the set the font weight for static exports to Medium
Before this can be merged, I need to do another investigation of why the title sometimes overflow for static charts.
---
This happened only locally LOL
> Static Grapher exports: Make title semibold

- db/model/Gdoc/GdocBase.ts
- db/model/Gdoc/rawToEnriched.ts
- packages/@ourworldindata/components/src/styles/variables.scss
- packages/@ourworldindata/utils/src/image.ts
- packages/@ourworldindata/utils/src/index.ts
- packages/@ourworldindata/utils/src/owidTypes.ts
- site/Lightbox.tsx
- site/gdocs/ArticleBlock.tsx
- site/gdocs/Image.tsx
Adds an optional `smallFilename` property to the `{.image}` component in archie.
This small image is assumed to be smaller than the regular image, and will show when the `Image` component's `img` tag has a width that is less than or equal to the width of the small image.
e.g.
```
{.image}
filename: large.png
smallFilename: small.png
{}
```
This will generate two `<source>` elements for the Image's `<picture>` to consider. The first one will only be active when the viewport width is less than 768px, the second source will always be active.
When previewing, it only uses the Digital Ocean CDN to load the original versions of the images (i.e. a srcset with only one URL specified.)
When baking, it makes multiple resizes of each image and includes all of those in the srcset. …
> 🎉 Add support for small filename in gdocs images

- .vscode/settings.json
- adminSiteClient/DatasetEditPage.tsx
- adminSiteClient/OriginList.tsx
- adminSiteClient/SourceList.tsx
- adminSiteClient/VariableEditPage.tsx
- adminSiteServer/apiRouter.ts
- packages/@ourworldindata/utils/src/OwidVariable.ts
Implementation of https://github.com/owid/owid-grapher/issues/2523.
- Add all new fields, including `updatePeriodDays`
- Add a list of origins for an indicator (all fields except license)
- Add indicator source (there's always max 1)
- Add `origins` to `admin/api/datasets/X.json`
- Add `updatePeriodDays`
- Add a list of origins for all indicators from a dataset
- Add a list of dataset sources and **remove confusing fields** that use the first dataset source
- I initially wanted to put field help text from our ETL docs into `secondaryLabel`, but eventually decided to only include link to our docs as the help would get outdated soon
- There's still the old confusing **Source** on Dataset page. Perhaps we could remove it and add sources to indicator tab instead?
- None of the fields are …
> :sparkles: add data page metadata fields to admin

- adminSiteServer/mockSiteRouter.tsx
- baker/SiteBaker.tsx
- baker/siteRenderers.tsx
- db/model/Gdoc/GdocBase.ts
- db/model/Gdoc/GdocDataInsight.ts
- db/model/Gdoc/GdocFactory.ts
- db/model/Gdoc/GdocPost.ts
- db/model/Image.ts
- db/wpdb.ts
- packages/@ourworldindata/components/src/styles/mixins.scss
- packages/@ourworldindata/components/src/styles/typography.scss
- packages/@ourworldindata/utils/src/Util.ts
- packages/@ourworldindata/utils/src/index.ts
- packages/@ourworldindata/utils/src/owidTypes.ts
- site/DataInsightsIndexPage.tsx
- site/DataInsightsIndexPageContent.tsx
- site/gdocs/OwidGdoc.tsx
- site/gdocs/OwidGdocPage.tsx
- site/gdocs/components/centered-article.scss
- site/gdocs/pages/DataInsight.scss
- site/gdocs/pages/DataInsight.tsx
- site/gdocs/pages/GdocPost.tsx
- site/runSiteFooterScripts.ts
A feed page with some sense of pagination in the mock site router
Will implement the actual pagination tomorrow
> 🎉 Data insights index page

- .vscode/settings.json
- adminSiteClient/PostsIndexPage.tsx
- adminSiteClient/admin.scss
- adminSiteServer/apiRouter.ts
This PR shows in the posts admin index page a preview button for gdocs that have the same slug but were not created via the "Create GDoc" button (and don't have an entry in the gdocSuccessorId column).
I thought about Ike's suggestion of setting the gdocSuccessorId when the slug is the same and thus solve this at the database level. This would have a number of other advantages (e.g. you don't have to match posts and gdocs in two different ways, once via gdocSuccessorId and once via slug) but it is a bit more fragile - we would then introduce a stateful sync that would have to be run correctly in a number of different code paths (e.g. when you rename a slug, ...). For this reason I decided to do the lookup both ways.
When we add our semantic database layer we can simplify this code a bit. …
> Posts admin: shows slug successors

- baker/formatWordpressPost.tsx
- baker/formatting.test.ts
- baker/formatting.tsx
- baker/pageOverrides.test.ts
- baker/siteRenderers.tsx
- db/migration/1702473994107-PostsAddFormattingOptions.ts
- db/syncPostsToGrapher.ts
- packages/@ourworldindata/utils/src/index.ts
- packages/@ourworldindata/utils/src/owidTypes.ts
- packages/@ourworldindata/utils/src/wordpressUtils.ts
This PR adds formattingOptions as a json column on the posts table. This is useful e.g. for identifying modular topic pages ($.bodyClassName = 'topic-page') or for identifying admin pages ($.subnavId = 'about')
> ✨ add formatting options column to wp posts table

- baker/SiteBaker.tsx
- baker/siteRenderers.tsx
- db/syncPostsToGrapher.ts
- db/wpdb.ts
This is mostly to unify the behaviour of syncPostsToGrapher
and postUpdateHook
> 🔨 sync not just wp pages and posts but also wp_blocks

- baker/postUpdatedHook.ts
- db/syncPostsToGrapher.ts
The wordpress posts sync script (`syncPostsToGrapher.ts`) and the update hook (`postUpdatedHook.ts`) are supposed to do pretty much the same thing, the former in batch mode and the latter for a single post. 
The two got a bit our of sync though as of late. One issues was that the treatment of reusable blocks (`wp_block`) was different - the sync script ignored them but they still came in via the hook. These can be useful (e.g. to migrate the reuseable blocks that store the content below explorers). 
Another issue was that the formattingOptions were not yet extracted in the update hook.
> Align post update hook and sync script

- adminSiteClient/PostsIndexPage.tsx
- adminSiteServer/adminRouter.tsx
- adminSiteServer/apiRouter.ts
- baker/GrapherBaker.tsx
- baker/postUpdatedHook.ts
- baker/siteRenderers.tsx
- db/migrateWpPostsToArchieMl.ts
- db/model/Post.ts
- db/syncPostsToGrapher.ts
- db/wpdb.ts
- packages/@ourworldindata/utils/src/dbTypes/Posts.ts
- packages/@ourworldindata/utils/src/dbTypes/PostsUtilities.ts
- packages/@ourworldindata/utils/src/index.ts
- packages/@ourworldindata/utils/src/owidTypes.ts
- site/EntriesByYearPage.tsx
- site/GrapherPage.jsdom.test.tsx
- site/GrapherPage.tsx
This PR does two things:
- it changes the `authors` field in the `posts` table to contain simply an ordered list of authors (instead of an unordered list of json objects with `{author: string, order: number}` type)
- it splits the `PostRow` type that represents a result for of the posts table into two, one `PostRowRaw` where authors and formattingOptions are still string fields and one `PostRowEnriched` where the json fields are parsed and the typed accordingly.
> Simplify authors fields in posts table, introduce better DB interaction for Posts

- baker/GrapherBaker.tsx
- datapage/Datapage.ts
- packages/@ourworldindata/core-table/src/CoreTableColumns.ts
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/dataTable/DataTable.scss
- packages/@ourworldindata/grapher/src/dataTable/DataTable.tsx
- packages/@ourworldindata/grapher/src/modal/SourcesModal.scss
- packages/@ourworldindata/grapher/src/modal/SourcesModal.tsx
- packages/@ourworldindata/utils/src/OwidVariable.ts
- packages/@ourworldindata/utils/src/index.ts
- packages/@ourworldindata/utils/src/owidTypes.ts
- site/DataPageV2.tsx
- site/DataPageV2Content.tsx
This PR changes the fallback chain for title-ish strings according to #3017
> 🔨 change fallback chain for display.name and titlePublic

- adminSiteClient/AdminLayout.tsx
- adminSiteClient/DatasetEditPage.tsx
- adminSiteClient/SourceEditPage.tsx
- adminSiteClient/VariableList.tsx
- adminSiteClient/VariablesIndexPage.tsx
- adminSiteServer/apiRouter.ts
- db/model/Variable.ts
Improve search through our indicators in the admin with more expansive search and search verbs, Google style.
- `(no prefix)` searches name or path (regex)
- `name:` search the name only (regex)
- `path:` search the catalog path only (regex)
- Search part of the catalog path (like)
- `namespace:`
- `version:`
- `dataset:`
- `table:`
- `short:`
- Search in time with `before:` and `after:`
- Negate a search term with `-` before it
- Search for private or public with `is:private` and `is:public`
> :tada: Vastly improved search over variables in the variable admin

- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/core/GrapherInterface.ts
- All state should be reflected in Grapher's URL but the "Show no data area" toggle was missing
> :sparkles: (grapher) reflect "Show no data area" toggle in the URL

- db/migrateWpPostsToArchieMl.ts
- db/model/Gdoc/htmlToEnriched.ts
This PR normalizes the heading levels so that the relative distance between headings is kept as before but the biggest heading used is h1 for entries/linear topic pages and h2 for others.
> GDoc migration: normalize headings

- packages/@ourworldindata/components/src/DataCitation/DataCitation.tsx
- packages/@ourworldindata/components/src/IndicatorProcessing/IndicatorProcessing.scss
- packages/@ourworldindata/components/src/index.ts
- packages/@ourworldindata/grapher/src/modal/SourcesModal.scss
- packages/@ourworldindata/grapher/src/modal/SourcesModal.tsx
- packages/@ourworldindata/utils/src/index.ts
- packages/@ourworldindata/utils/src/metadataHelpers.ts
- site/DataPageV2Content.tsx
This PR:
- adds citations to the sources overlay in Grapher
- tweaks the styling of data citations
- moves data page citations above data citations
- fixes an unrelated style issue with numbered lists
> 🎉 Tweak citations, add them to the sources overlay

- db/migration/1703777475319-FixGdocPostsWithoutType.ts
With the introduction of data-insights, the `type` field of the content json blob became more important to the point where the admin refuses to show the content of a gdoc that does not have this field set. Most gdocs had it set in the db already but some only had it in the gdoc document. The admin now breaks if the type is missing which leads to a bind since if the DB does not already have the type set, there is no way for the user to get it set.
This PR just assigns the type `article` to all (12 or so) posts_gdocs that do not have the type set. Even if the page is actually a topic page, the next time it is opened in the admin, the correct type will overwrite the field in the db. I checked that none of the 12 documents that will be influenced by this are currently published AND are …
> 🐛 fix missing type field in some posts_gdocs rows

- db/model/Gdoc/GdocPost.ts
This PR fixes this by guarding access to the tags property
> 🐛 GdocPost.tags is supposed to always exist but doesn't when accessing the featured content gdoc

- packages/@ourworldindata/components/src/IndicatorKeyData/IndicatorKeyData.tsx
- packages/@ourworldindata/components/src/IndicatorSources/IndicatorSources.tsx
- Links were sometimes interpreted as Markdown
- Example: https://ourworldindata.org/grapher/distribution-of-population-between-different-poverty-thresholds-historical
> Fix broken links in sources modal

- adminSiteClient/gdocsValidation.ts
Natasha and Charlie are working on migrating all our old articles to GDocs. For this, having to write an excerpt is a substantial effort (as it needs checking back with authors etc).
This PR makes excerpts optional. If things go well we should be able to make it mandatory at some point later in the year when authors had some time to go though the content but excpert is not strictly speaking necessary today anyway.
> ✨ allow publishing without excerpt

- packages/@ourworldindata/grapher/src/modal/SourcesModal.tsx
- packages/@ourworldindata/utils/src/metadataHelpers.ts
Fixes https://github.com/owid/owid-grapher/issues/3052
NOTE: I am not very familiar with this code and have not looked deeply into it, so there may be cases I haven't considered.
This PR:
* Shows `description` next to the indicator's title, when `descriptionShort` does not exist but `description` does exist.
* Removes indicator's `description` from the sources.
> Fix misplaced indicator's `description` field

- packages/@ourworldindata/core-table/src/CoreTableColumns.ts
- packages/@ourworldindata/core-table/src/OwidTable.ts
- packages/@ourworldindata/core-table/src/OwidTableConstants.ts
- packages/@ourworldindata/core-table/src/OwidTableUtil.ts
- packages/@ourworldindata/grapher/src/stackedCharts/AbstractStackedChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedAreaChart.test.ts
- packages/@ourworldindata/grapher/src/stackedCharts/StackedBarChart.test.ts
- packages/@ourworldindata/grapher/src/stackedCharts/StackedConstants.ts
- packages/@ourworldindata/grapher/src/stackedCharts/StackedUtils.ts
- fixes #2866
- StackedArea charts show interpolated (i.e. made-up) values in the tooltip
- I don't have a live example, but Pablo created a [buggy chart](http://staging-site-fix-tooltip-interpolated-values/grapher/energy-consumption-by-source-and-country?country=~BLR) for me on staging
- You won't be able to see the bug since it's fixed on this branch now, but still:
- Select Belarus and hover over any data point between 2000 and 2019
- Now it shows "No data" for Nuclear (which is correct), but we used to show interpolated values here (I should have screenshotted it before pushing a fix 🤦‍♀️)
- The fix is not trivial because linear interpolation overwrites the original column. We thus lose information on which values are real and which have been interpolated
- To keep track of this, the …
> StackedArea: Don't show interpolated values in tooltips

- ops/buildkite/deploy-content
- package.json
- packages/@ourworldindata/grapher/package.json
- yarn.lock
Running `npx wrangler` installs wrangler globally in the cache and could have unintended consequences (changing versions, etc.). Install it as dev dependency.
Related PR in ops https://github.com/owid/ops/pull/122
This should help with https://github.com/owid/owid-grapher/pull/3055#pullrequestreview-1801966719
> :hammer: add wrangler to package.json

- packages/@ourworldindata/grapher/src/header/Header.tsx
Revert #2970 
PNGs didn't pick up the right font (I think), and displayed the title as `bold` which was too overpowering
> :honeybee: (grapher) revert title font weight: semibold -> medium

- adminSiteClient/EditorBasicTab.tsx
- devTools/schemaProcessor/columns.json
- packages/@ourworldindata/grapher/src/controls/ChartIcons.tsx
- packages/@ourworldindata/grapher/src/core/GrapherConstants.ts
- packages/@ourworldindata/grapher/src/schema/grapher-schema.003.yaml
- `WorldMap` is removed from the admin's chart type list but continues to be used as chart type internally
- None of our charts are of type `WorldMap` currently, so no migration necessary
- Technically, this is a breaking change for our schema, but I don't think there is a need to increase the schema version etc since there is no code change
> :honeybee: (admin) remove WorldMap from chart type list

- baker/SiteBaker.tsx
`getPrefetchedGdocAttachments` is a function that queries the DB a couple of times to get all possible attachment data and caches it, so that we can pick the attachments from memory instead of querying the DB for each gdoc bake.
There was a bug in my implementation where linked documents' featured images weren't getting picked, because `linkedDocuments` is a dependency of `linkedImageFilenames`, but both are undefined when we call the function.
This PR fixes the bug by appending the featured images of any linked documents to the list of linkedImageFilenames when we're doing the picking.
**Before:**
**After:**
> 🐛 Fix missing featured images

- .bundlewatch.config.json
- adminSiteClient/ChartEditor.ts
- adminSiteClient/ChartEditorPage.tsx
- adminSiteClient/EditorExportTab.tsx
- adminSiteClient/admin.scss
- functions/_common/grapherRenderer.ts
- packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.tsx
- packages/@ourworldindata/grapher/src/captionedChart/StaticChartRasterizer.tsx
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/core/GrapherConstants.ts
- packages/@ourworldindata/grapher/src/core/grapher.scss
- packages/@ourworldindata/grapher/src/footer/Footer.tsx
- packages/@ourworldindata/grapher/src/footer/FooterManager.ts
- packages/@ourworldindata/grapher/src/header/Header.tsx
- packages/@ourworldindata/grapher/src/header/HeaderManager.ts
- packages/@ourworldindata/grapher/src/index.ts
- packages/@ourworldindata/grapher/src/modal/DownloadModal.test.tsx
- packages/@ourworldindata/grapher/src/modal/DownloadModal.tsx
<details>
<summary><b>Christian's sketch</b></summary>
</details>
Adds an Export tab to the chart admin with the following features:
- Static previews in the browser (desktop & mobile)
- Show/hide individual elements (e.g. subtitle, note)
- Data source and license can't be hidden
- Optionally include details at the bottom
- Export desktop/mobile PNG/SVG static charts with or without details included at the bottom
**Not implemented**
- Mobile Image Size Section
- No need for a preset dropdown since, if possible, I'd like to have a single size preset for mobile images that works for data insights and Instagram
- For now, we don't want authors to customise width/height individually
- Data Insights Section
- Would be nice, but it’s not essential, and I’m pressed for time
- Export settings are …
> 🎉 (static charts) add Export tab to the chart admin

- packages/@ourworldindata/grapher/src/axis/Axis.ts
- packages/@ourworldindata/grapher/src/barCharts/DiscreteBarChart.tsx
- packages/@ourworldindata/grapher/src/core/GrapherConstants.ts
- packages/@ourworldindata/grapher/src/horizontalColorLegend/HorizontalColorLegends.tsx
- packages/@ourworldindata/grapher/src/lineLegend/LineLegend.tsx
- packages/@ourworldindata/grapher/src/scatterCharts/ScatterPlotChartConstants.ts
- packages/@ourworldindata/grapher/src/scatterCharts/ScatterSizeLegend.tsx
- packages/@ourworldindata/grapher/src/slopeCharts/SlopeChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/MarimekkoChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedBarChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedDiscreteBarChart.tsx
- packages/@ourworldindata/grapher/src/verticalColorLegend/VerticalColorLegend.tsx
Refactor, no behaviour change.
Use a shared set of font sizes, getting rid of magic values.
The SVG tester complains about all slope charts because their labels are slightly bigger now (used to be 10.4px, now 10.5px).
> :hammer: (static charts) use a shared set of font sizes

- packages/@ourworldindata/grapher/src/core/Grapher.tsx
Adds a reaction to each Grapher so that when `isReady` is set to true, a `"grapherLoaded"` event is emitted. This enables us to do things once we know the Graphers on the page have fully loaded.
This isn't working correctly for datapages, however, because for some reason data page Graphers are mounting 3 times (so three separate events are getting emitted)
Here's a demo of me creating an event listener for the event, which I attach to the document immediately after refreshing the page so that it fires when the Grapher on the page finishes loading. Navigating around the grapher doesn't cause the event to fire again.
https://github.com/owid/owid-grapher/assets/11844404/04adab9e-6b7a-4e8d-aa92-4a97cb2329a2
> 🎉 add `grapherLoaded` event

- site/stripe/DonateForm.tsx
Updating reCAPTCHA on the donor form presents no ideal solutions so far: 
- (current) [react-recaptcha](https://www.npmjs.com/package/react-recaptcha): last update was 5 years ago
- [react-google-recaptcha](https://www.npmjs.com/package/react-google-recaptcha): quite a few issues on GH, current migration attempts are bumpy
- [react-hook-recaptcha](https://github.com/tomliangg/react-hook-recaptcha): would require migrating the whole form from a class to a functional component
In this context, the benefit of switching recaptcha libraries is unclear.
Instead, I suggest keeping the current working solution in place and making errors more prominent. This will help us react quicker to a possible failure of reCAPTCHA and act accordingly.
Given the high threshold for errors to be sent to slack …
> 🥅 (donate) notify front-end errors to bugsnag

- Makefile
- devTools/docker/banner.sh
- package.json
This PR adds local development support for Cloudflare Pages functions.
It integrates the wrangler dev server to the `make up.full` command.
> Local env for cloudflare functions with makefile

- functions/README.md
- ops/buildkite/deploy-content-preview
- package.json
This adds a script to manually deploy to Cloudflare previews, a production-like environment where we can deploy a copy of the baked site for testing.
This is particularly useful for testing CF Pages functions and increase confidence, in addition to the local/staging testing done with `wrangler`.
This requires quite a few manual steps to set up, which is fine for now since the scope of these functions is still pretty limited. As usage ramps up, we can consider a more automated approach to deploying these functions to CF, parallel to the current staging deploys.
For testing the donation flow:
- https://donate.owid.pages.dev
- temporarily disable CF Access rule, see https://github.com/owid/owid-grapher/blob/74c74736a6ccb5863c4693762a69a1726fe50563/functions/README.md?plain=1#L156-L160
> Deploy staging to Cloudflare previews

- .dev.vars.example
- functions/README.md
- functions/donation/donate.ts
- functions/donation/thank-you.ts
Add instructions to log into the Stripe CLI with the same `STRIPE_API_KEY` env variable defined in .dev.vars. This allows testers without access to the stripe dashboard to register a local webhook and test the donation/thank-you route.
Clouflare env variables (production and preview) updated accordingly.
Preview on https://donate.owid.pages.dev updated.
> 📝(donate) document Stripe CLI login

- packages/@ourworldindata/grapher/src/lineCharts/LineChart.tsx
- packages/@ourworldindata/grapher/src/mapCharts/MapTooltip.scss
- packages/@ourworldindata/grapher/src/mapCharts/MapTooltip.tsx
- fixes https://github.com/owid/owid-grapher/issues/2960
- Sparkline uses Grapher's LineChart to render
- The horizontal min and max lines and their labels are defined outside of the LineChart
- At some point, the LineChart added some more top and bottom padding to its bounds, but the sparkline chart wasn't updated accordingly
- To make sure the code doesn't go out of sync again, the LineChart's axis object is used to figure out the position of the extra lines and labels that live outside of the line chart
> :bug: (sparkline) fix visual glitch

- adminSiteClient/DimensionCard.tsx
- packages/@ourworldindata/grapher/src/dataTable/DataTable.tsx
- fixes #2787 
- Our config defines a `tableDisplay` field on the `display` property of a dimension
- `tableDisplay`  holds two properties, `hideAbsoluteChange` and `hideRelativeChange`, that hide change columns in the data table if set to true
- But these fields are currently ignored by Grapher (I don't know why)
- Both fields can be edited via the admin, but the UI is currently only exposed if `tableDisplay` already exists in the config
- This PR makes it so that `hideAbsoluteChange` and `hideRelativeChange` are respected
- Toggles to edit both fields are always exposed in the admin
- We don't have any indicators that set one of the fields to true ([Datasette](https://datasette-public.owid.io/owid?sql=select%0D%0A++id,%0D%0A++name,%0D%0A++display%0D%0Afrom%0D%0A++variables%0D%0Awhere%0D% …
> :tada: (data-table) allow to hide change columns

- adminSiteClient/DeployStatusPage.tsx
Automatically refresh /admin/deploys ~~every 30 seconds.~~ when tab becomes active again (e.g. after visiting another tab)
Context: [slack](https://owid.slack.com/archives/C0149NKLZAM/p1703091958890729)
> ✨automatically refresh deploy status page

- baker/SiteBaker.tsx
- db/model/Gdoc/GdocBase.ts
- db/model/Gdoc/GdocDataInsight.ts
- db/model/Gdoc/GdocPost.ts
- db/model/Gdoc/gdocUtils.ts
- packages/@ourworldindata/types/src/gdocTypes/Gdoc.ts
- packages/@ourworldindata/types/src/index.ts
- site/DataInsightsIndexPageContent.tsx
- site/gdocs/OwidGdoc.tsx
- site/gdocs/components/ProminentLink.tsx
- site/gdocs/components/Recirc.tsx
- site/gdocs/components/ResearchAndWriting.tsx
- site/gdocs/components/TopicPageIntro.tsx
- site/gdocs/utils.tsx
Currently if you link to another gdoc, we attach the entire gdoc as an attachment to the JSON that we send to the front-end
This is very inefficient seeing as we, at most, only use a couple of properties in the front-matter from the gdoc (title, subtitle, featured-image, etc)
This PR introduces a `OwidGdocMinimalPostInterface` type and uses that to pass to the FE instead.
On topic pages that link to a lot of other gdocs, e.g. [Energy](https://ourworldindata.org/energy) this offers huge savings.
Before: 1.2MB of linkedDocuments
After: 182.1kB
Here's a demo, with one of the minimal models highlighted in the console.
> 🔨 use a minimal representation of gdocs to link to

- packages/@ourworldindata/grapher/src/color/ColorScale.ts
- packages/@ourworldindata/types/package.json
- packages/@ourworldindata/types/src/grapherTypes/GrapherTypes.ts
- yarn.lock
This PR reverts one change that was done in the types extraction PR a week ago. The interface `ColorScaleConfigInterface` used to be defined as a type alias to a class (unlike what the name suggests). I changed this and with it also the way the ColorScale.config field was implemented but this then broke the color scale dropdowns.
I'd like to revert this PR at some point and figure out why this breaks the drop downs but I don't have the time rn to investigate this in detail.
> :bug: fix broken color scheme selection by reverting interface change

- devTools/docker/mysql-init-docker/Dockerfile
- docker-compose.dbtests.yml
- docker-compose.devcontainer.yml
- docker-compose.full.yml
- docker-compose.grapher.yml
This should hopefully git rid of the issues we lately sometimes had with microdnf
> 🔨 switch mysql docker images to debian to work around microdnf issues

- devTools/docker/mysql-init-docker/Dockerfile
- docker-compose.dbtests.yml
- docker-compose.devcontainer.yml
- docker-compose.full.yml
- docker-compose.grapher.yml
This reverts commit 9d5e7310e0dfaf57e6b30b583530bbefe194c149.
The reason for the revert is that the debian based mysql image is not available for M1/M2 based Macs :(
> Revert "🔨 switch mysql docker images to debian to work around microdnf issues"

- devTools/docker/mysql-init-docker/Dockerfile
> :honeybee: install missing GPG keys for mysql in dbtest

- explorer/Explorer.tsx
- The entity selection of this [explorer embedded in a topic page](https://ourworldindata.org/war-and-peace#explore-data-on-armed-conflict-and-war) is empty, although a global Explorer selection is given and respected on the [explorer page](https://ourworldindata.org/explorers/countries-in-conflict-data?facet=none&Measure=Deaths&Conflict+type=All+armed+conflicts&Conflict+sub-type=all)
- Explorers handle these two cases differently:
- If the entity selection passed to the Explorer is undefined, then the Explorer's global selection is used
- If the entity selection passed to the Explorer is defined but empty, then the chart's selected entities are used (unexpected!)
- The bug:
- If no global entity selector exists on the page, the MultiEmbedder passes an empty entity selection array to the …
> :bug: (explorer) respect global selection when embedded

- Makefile
The grapher repo cannot build explorers without `owid-content`, so make sure it's there.
> :bug: clone owid-content during "make up" if missing

- adminSiteServer/apiRouter.ts
- db/migrateWpPostsToArchieMl.ts
Given the following (subselection o) archieML JSON in the posts table:
```
"body": [
{
"type": "text",
"value": [
{
"text": "I am some text with an ampersand &",
"spanType": "span-simple-text"
}
],
"parseErrors": []
},
{
"url": "https://ourworldindata.org/grapher/annual-deforestation?stackMode=absolute&region=World",
"type": "chart",
"parseErrors": []
}
]
```
Here's how it was getting inserted into Gdocs:
Before:
After:
I opted to make the fix inline just before the gdoc creation, because an arbitrary HTML code escape done earlier in the pipeline would then cascade into a bunch of other places that we'd need to make sure was handled correctly.
> 🐛 Fix mistaken HTML character encoding grapher urls

- packages/@ourworldindata/grapher/src/barCharts/DiscreteBarChart.tsx
- fixes #3069 
- there are two ways of fixing this:
- setting the series strategy to `column` instead of `entity` such that – for a single country – both y-variables are plotted (they don't show up at the same time because they have no time overlap)
- setting the facetting strategy to facet by metric (with series strategy `entity`). that way, we would get two distinct bar charts – one for each y-column, i.e. one for historical and one for future data – where both bar charts display a single entity
The first solution produces the better result I think.
Example: [live](https://ourworldindata.org/grapher/number-of-deaths-per-year?time=latest) / [staging](http://staging-site-fix-broken-bar-chart-with-projected-data/grapher/number-of-deaths-per-year?time=latest)
> :bug: (discrete-bar) fix charts with projected data

- packages/@ourworldindata/grapher/src/barCharts/DiscreteBarChart.tsx
- Adds a striped pattern to bars in discrete bar charts when they show projected data
- I had to recreate Christian's `repeating-linear-gradient` CSS code as SVG pattern, so it might not be _excactly_ the same
Examples:
- http://staging-site-discrete-bar-striped-pattern/grapher/number-of-deaths-per-year?time=latest
- http://staging-site-discrete-bar-striped-pattern/grapher/median-age?time=2094&facet=entity&country=LBY~LBR
- http://staging-site-discrete-bar-striped-pattern/grapher/comparison-of-world-population-projections?time=2099&country=~AND
Screenshots:
> :sparkles: (discrete-bar) add striped pattern for projected data

- packages/@ourworldindata/grapher/src/dataTable/DataTable.jsdom.test.tsx
- packages/@ourworldindata/grapher/src/dataTable/DataTable.sample.ts
- packages/@ourworldindata/grapher/src/dataTable/DataTable.stories.tsx
- packages/@ourworldindata/grapher/src/testData/OwidTestData.sample.ts
- packages/@ourworldindata/grapher/src/testData/OwidTestData.ts
- If the table filter toggle is missing, we filter the table by default in some instances
- This adds two tests to make sure the table is not filtered...
- if the current selection is empty
- if we have a map tab
- I also refactored the code a bit to make it easier to define test data in the future
> :white_check_mark: (data table filter) add tests

- .github/workflows/sync-master.yml
Every foundation server needs its master server as a template to create new staging servers. Copying `staging-site-master` across hosts is too slow (>45min and it stops `staging-site-master` container), so we rather create `staging-site-master-1` that will be kept in sync with `master` and automatically updated by Buildkite.
> :hammer: sync master-1 with master on every push to master

- db/migration/1706317870929-DatasetsFieldNameMandatory.ts
- packages/@ourworldindata/types/src/dbTypes/Datasets.ts
This PR changes the `datasets` table so that the `name` column is no longer nullable. Null values were never used in this column and it's nicer if the column types match the content exactly.
> 🔨 make name on datasets mandatory

- .github/workflows/svg-compare-all-views.yml
- .github/workflows/svg-compare.yml
- Adds a GitHub action to test all possible views of a subset of charts
- The action works exactly like the other action works
- To review, it's probably easiest to look at the diff between `svg-compare.yml` and `svg-compare-all-views.yml`
- Both actions commit to the same branch in `owid-grapher-svgs`
- Having all SVGs for one change on the same branch is convenient since I often pull from the repo to look at the SVG differences locally (if there are many differences, GitHub often fails too to load the page) 
- Accidental content overwrites are impossible because both actions operate in different directories
- The verify step:
- The verify script reads chart IDs to process from the `most-viewed-charts.txt` file in `owid-grapher-svgs`
- The reference SVGs for all chart views are stored in …
> 🐝 (svg tester) add GitHub action to test all possible chart views

- devTools/docker/sync-s3-images.sh
Previously, our dev tool used the default s3 credentials when syncing to DigitalOcean Spaces. This is a little problematic, since we are now using multiple object stores.
This change suggests setting up a profile for OWID and explicitly using that. In this way, it's compatible with using multiple object stores, and in fact having multiple sets of S3 credentials on your machine.
`aws configure --profile=owid-spaces`
> :honeybee: set the dev tools to use a profile for s3 credentials

- baker/GDriveImagesBaker.tsx
404s from DigitalOcean Spaces don't raise an error, but still return false `response.ok`. This prevented retry logic from taking place.
> :bug: retry 404 errors from GDrive images

- adminSiteClient/ChartEditorPage.tsx
Since moving the DB further from the admin geographically, this call has had very bad performance impacts, and the results from it are not used.
Aims to improve: https://github.com/owid/owid-grapher/issues/3198
> :bug: disable topic fetching in the chart admin

- adminSiteClient/AdminSidebar.tsx
- settings/clientSettings.ts
> :sparkles: replace Fast-track tab by Wizard

- Makefile
- devTools/docker/my.cnf
- docker-compose.full.yml
- docker-compose.grapher.yml
Sometimes it's helpful to understand what queries are actually hitting the database as you work.
This change mounts the .gitignored `logs/` folder into the Docker MySQL container, and writes queries to `logs/queries.log` as they happen. This means you can `tail -f logs/queries.log` in your local environment and see queries happen live.
> :honeybee: Dev tooling: log all MySQL queries in dev

- adminSiteClient/GdocsIndexPage.tsx
- adminSiteClient/GdocsPreviewPage.tsx
- adminSiteClient/GdocsSettingsContentField.tsx
- adminSiteClient/GdocsSettingsForms.tsx
- adminSiteClient/gdocsDeploy.ts
- baker/siteRenderers.tsx
- db/model/Gdoc/GdocBase.ts
- db/model/Gdoc/GdocFactory.ts
- db/model/Gdoc/GdocHomepage.ts
- db/model/Gdoc/enrichedToMarkdown.ts
- db/model/Gdoc/enrichedToRaw.ts
- db/model/Gdoc/exampleEnrichedBlocks.ts
- db/model/Gdoc/rawToArchie.ts
- db/model/Gdoc/rawToEnriched.ts
- packages/@ourworldindata/types/src/gdocTypes/ArchieMlComponents.ts
- packages/@ourworldindata/types/src/gdocTypes/Gdoc.ts
- packages/@ourworldindata/types/src/index.ts
- packages/@ourworldindata/utils/src/Util.ts
- packages/@ourworldindata/utils/src/image.ts
- site/gdocs/OwidGdoc.tsx
- site/gdocs/OwidGdocPage.tsx
- site/gdocs/components/ArticleBlock.tsx
- site/gdocs/components/PillRow.tsx
- site/gdocs/components/centered-article.scss
- site/gdocs/pages/Homepage.tsx
- site/search/SearchPage.tsx
A new page type so that we can preview changes to the homepage in the admin before publishing (avoiding issues where featured posts aren't rendered correctly, etc)
It's basically a port of `Frontpage.tsx` and some extra boilerplate around the gdocs admin side of things.
Also adds a `pill-row` component
```
title: Test homepage with pill-row
excerpt: ignore me
type: homepage
authors: You
[+body]
{.pill-row}
title: Popular pages
[.pills]
text: Hello
url: https://en.wikipedia.org/
text: World
url: https://fr.wikipedia.org/
text:
url: https://docs.google.com/document/d/1Lo3CtGGESA3iQVrlhlQZbtG15ecUNt1Qfk2X3iBlwIk/edit
[]
{}
[]
```
The linting and comments are fixed in subsequent branches.
> 🎉 Homepage Gdoc type

- adminSiteClient/EditorBasicTab.tsx
- When creating a new chart, we want to sample a random set of entities
- But when editing a chart, we usually want to persist entities (unless it doesn't make sense)
- For stacked charts (StackedBar, StackedArea, StackedDiscreteBar), we were throwing away entities more often than necessary
- This PR implements two improvements:
- Stacked charts persist a single entity and only sample new entities when the current selection is empty
- StackedDiscreteBar charts are treated like other stacked charts – see above
> ✨ (admin) persist entities for stacked charts more often

- baker/GrapherBaker.tsx
- db/model/Variable.ts
Retry didn't apply to 500 errors, and these errors failed right away. Move `resp.ok` check to `retryPromise` to trigger retry.
Possible fix for https://github.com/owid/owid-grapher/issues/3212.
> :bug: retry 500 errors when fetching data / metadata

- adminSiteClient/ChartEditor.ts
- adminSiteServer/apiRouter.ts
- db/model/Post.ts
- packages/@ourworldindata/types/src/domainTypes/ContentGraph.ts
- site/RelatedArticles/RelatedArticles.tsx
This PR merges the content graph queries used in grapher pages (see #3176) and the references queries used in the chart admin to indicate where a chart is being used.
If fixes two issues on the tab page:
- Overridden Wordpress posts now ignored
- Remove duplicate posts
Reusable blocks are no longer surfaced. This is ok since reusable blocks are now dereferenced in the embedding article, which means a chart within a reusable block would show in the parent article. One exception is explorer content blocks, which are still standalone. A quick manual check on all explorers reveals that only one explorer references a chart: https://ourworldindata.org/explorers/plastic-pollution. Given these blocks' scope and limited lifetime, this caveat is acceptable.
_A future PR should use these references …
> Merge content graph and chart references

- baker/redirects.ts
- baker/syncRedirectsToGrapher.ts
- db/migration/1707467006420-AddRedirectsTable.ts
- db/model/Redirect.ts
- db/syncRedirectsToGrapher.ts
- db/wpdb.ts
- packages/@ourworldindata/types/src/dbTypes/Redirects.ts
- packages/@ourworldindata/types/src/index.ts
- packages/@ourworldindata/utils/src/urls/Url.test.ts
- packages/@ourworldindata/utils/src/urls/Url.ts
This PR adds a new `redirects` table to hold redirects currently stored in the Wordpress database.
It also adds a migration script to import Wordpress redirects: `syncRedirectsToGrapher`:
```
[...]
Skipping, a redirect already exists for "/what-makes-a-disease-eradicable"
Skipping, a redirect already exists for "/sources-for-eradication-of-diseases"
Skipping, a redirect already exists for "/can-the-world-eradicate-another-disease"
Adding redirect: /full-stack-engineer-q4-2023 -> /jobs
```
The number of enabled redirected in the Wordpress table is identical to the number of redirects in the new table after running the migration script.
> Add redirects table and migration script

- baker/redirects.ts
- baker/syncRedirectsToGrapher.ts
- refactor: bake redirects from db
- refactor: resolve internal redirects from db
The internal resolver is currently only used for prominent links. The following query reveals some examples of where it might be used:
```
select
*
from
posts_links pl
join posts p on pl.sourceId = p.id
where
pl.linkType = 'grapher'
and componentType = 'prominent-link'
and p.status = 'publish'
and p.gdocSuccessorId is NULL
and pl.target in (
select
slug
from
chart_slug_redirects csr
)
```
For instance, in https://ourworldindata.org/ukraine-war 
This PR also simplifies the formatWpUrl function since none of the paths in redirects contain the "__" string:
```
SELECT url, action_data, action_code FROM wp_redirection_items WHERE (url like "%\_\_%" OR action_data like "%\_\_%")  and status = "enabled"
```
--> 0 …
> refactor: bake redirects from db

- adminSiteClient/GdocsIndexPage.tsx
- adminSiteClient/GdocsPreviewPage.tsx
- adminSiteClient/gdocsDeploy.ts
- baker/algolia/indexToAlgolia.tsx
- db/model/Gdoc/GdocFactory.ts
- db/model/Gdoc/GdocPost.ts
- db/model/Post.ts
- packages/@ourworldindata/types/src/gdocTypes/Gdoc.ts
- packages/@ourworldindata/utils/src/Util.ts
- packages/@ourworldindata/utils/src/image.ts
- site/gdocs/OwidGdoc.tsx
- site/gdocs/OwidGdocPage.tsx
- site/gdocs/components/OwidGdocHeader.tsx
- site/gdocs/pages/GdocPost.tsx
- Example gdoc: https://docs.google.com/document/d/1gdVS23tMmqH1ABXp0hlvy7L-VPUv_CtowGvyujNXtg4/edit
- Preview: http://staging-site-about-page-tpl/admin/gdocs/1gdVS23tMmqH1ABXp0hlvy7L-VPUv_CtowGvyujNXtg4/preview
- Baked: http://staging-site-about-page-tpl/test-about-page
This PR adds a new template for about pages:
- these pages are visually similar to linear topic pages (headers are identical), although citations are discouraged.
- about pages are excluded from content graph queries as the charts they contain are usually used as examples and not for their semantic value (e.g. https://ourworldindata.org/owid-grapher)
- indexed by Algolia, but with a low importance
- create a new gdoc
- use the `template: about-page` frontmatter property to set the template
> feat: add about page template

- adminSiteServer/adminRouter.tsx
- adminSiteServer/apiRouter.ts
- adminSiteServer/mockSiteRouter.tsx
- baker/DeployUtils.ts
- baker/ExplorerBaker.tsx
- baker/GrapherBaker.tsx
- baker/SiteBaker.tsx
- baker/algolia/indexChartsToAlgolia.ts
- baker/algolia/indexToAlgolia.tsx
- baker/buildLocalBake.ts
- baker/formatWordpressPost.tsx
- baker/redirects.test.ts
- baker/redirects.ts
- baker/runBakeGraphers.ts
- baker/siteRenderers.test.ts
- baker/siteRenderers.tsx
- baker/sitemap.ts
- baker/startDeployQueueServer.ts
- baker/syncRedirectsToGrapher.ts
- db/model/Chart.ts
- db/model/Post.ts
- db/model/Redirect.ts
- db/wpdb.ts
- packages/@ourworldindata/types/src/dbTypes/Redirects.ts
- packages/@ourworldindata/types/src/index.ts
- pass knex as a parameter to downstream functions
- wrap top API calls in a transaction
- replace knex.raw() with knexRaw()
- this PR doesn't add [{readOnly: true}](https://www.notion.so/owid/Database-access-in-Grapher-d9db343c2bfb4ae0b14b3dec72f686c6?pvs=4#fdb6c225d4134e47a78fe3436a19f72c).
@danyx23 [as you know](https://github.com/owid/owid-grapher/pull/3145), these refactors tend to start with a small surface area but end up requiring extensive surgery across the codebase.
This is partly why I hadn't dived into it as part of this project, and continued using the `db.knexInstance().raw()` paradigm in downstream functions. (Another reason had to do with the value of doing this refactor on partly obsolete code).
So in case this ends up needing more work and blocks the delivery of the …
> refactor: pass knex as parameter

- baker/SiteBaker.tsx
- db/model/Gdoc/GdocBase.ts
- packages/@ourworldindata/utils/src/metadataHelpers.ts
- In the key indicator block, the key indicator title (pulled from the metadata) didn't always match the datapage title
- The datapage title uses a chain of metadata properties to resolve the correct title
- The key indicator block should use the same chain, but I forgot to include the chart config title
Example:
> 🐛 (key-indicator) make sure title matches the datapage title

- site/gdocs/components/ExplorerTiles.scss
- site/gdocs/components/ExplorerTiles.tsx
- site/gdocs/components/centered-article.scss
Make sure these assets load correctly on owid.cloud when the dev server is disabled.
> 🐛 use absolute URLs for image assets in homepage components

- .github/workflows/svg-compare-all-views.yml
- .github/workflows/svg-compare.yml
- Both SVG tester actions commit to the same branch, but force-push their changes, which means that they overwrite changes on remote
- As a result, the last action that pushes wins and overwrites the commit of the other action
- We could attempt to fix this, but I never felt strongly about having both actions commit to the same branch
- It's easier and less error-prone to just have both actions commit to different branches
- If on branch `<my-branch>`, then the first action now commits to a branch of the same name, and the other action commits to `<my-branch>__all-views`
[The follow-up PR](https://github.com/owid/owid-grapher/pull/3215) makes the SVG tester actions fail on purpose. Note that both actions commit to different branches:
SVG tester:
SVG tester (all views):
> 🐛 commit svg tester diffs to different branches

- packages/@ourworldindata/grapher/src/axis/AxisViews.tsx
- packages/@ourworldindata/grapher/src/barCharts/DiscreteBarChart.tsx
- I noticed that one of our DiscreteBar charts didn't draw bars correctly (see screenshot below, top row, second chart)
- There was a small issue in how we calculated the available space. Too much space was subtracted on the left
| <img width="733" alt="Screenshot 2024-02-26 at 14 51 17" src="https://github.com/owid/owid-grapher/assets/12461810/a0445aa4-4b6a-455c-9e73-2d8f99459007">  | <img width="733" alt="Screenshot 2024-02-26 at 14 51 32" src="https://github.com/owid/owid-grapher/assets/12461810/132dbe0d-da86-4309-8003-690f9cc48dff"> |
> 🐛 (discrete bar) fix broken layout

- db/refreshPageviewsFromDatasette.ts
- The script that runs on `make refresh.pageviews` currently doesn't work. It incorrectly filters out all rows, and then inserts 0 rows into the database.
- This statement threw out all entries (maybe because additional columns were recently added to the Datsette table?): https://github.com/owid/owid-grapher/blob/8fbf4ab92c74a79542aa88e04fca59338beec740/db/refreshPageviewsFromDatasette.ts#L30-L32
- To make this a bit more robust, I grab all valid pageview fields from each row of the downloaded data. A row is then declared "valid" if it has a day and a URL
- Note that we're also removing rows where the URL contains an emoji since MySQL couldn't insert those. We currently have one single entry where the URL contains an emoji ([Datasette](http://datasette-private/owid?sql=select%0D%0A++*%0D%0 …
> 🐛 fix script that refreshes pageviews

- .github/workflows/svg-compare-all-views.yml
- The all-views SVG tester pushes its changes to a branch named `<my-branch>__all-views`
- If run from the master branch, we want to push to the `owid-grapher-svgs` repo's master branch, but the action pushes to `master__all-views`. It also fails with differences on master, because we have some `branch-name = 'master'` checks (which don't work if the current branch name is `master__all-views`)
- This is fixed by using the `master` branch if on master, i.e.:
- If on master, keep the branch name `master`
- If not on master, use `<my-branch>__all-views`
Note that the SVG tester fails because one of my recent merges into master was supposed to update the owid-grapher-svgs repo but didn't (because the action failed early)
> 🐛 (svg tester) fix all-views action for the master branch

- adminSiteServer/adminRouter.tsx
- adminSiteServer/apiRouter.ts
- adminSiteServer/exportGitData.ts
- adminSiteServer/gitDataExport.ts
- db/model/Dataset.ts
- db/model/Source.ts
- Makes the `Dataset` and `Source` TypeORM classes obsolete by switching db access to knex
- This PR does not do any clean-up, e.g. SQL queries in the router files are not moved, although they ultimately should live in the `db` folder
- I added two helper functions that can be used as drop-in replacements for `queryMysql` and `mysqlFirst` that are often used in our codebase, `knexRaw` and `knexRawFirst` (both live in `db.ts`)
- Routes that I could easily test are tested, but not all of the code is!
@danyx23 let me know if this is how you imagined it, or if I should do anything differently.
@coderabbitai ignore
> :hammer: (db) migrate Dataset and Source to knex

- adminSiteServer/apiRouter.ts
- baker/algolia/indexChartsToAlgolia.ts
- baker/algolia/indexExplorersToAlgolia.ts
- baker/algolia/indexToAlgolia.tsx
- db/model/Pageview.ts
- Makes the `Pageview` TypeORM class obsolete by switching db access to knex
- This PR does not do any clean-up, e.g. SQL queries in the router files are not moved, although they ultimately should live in the `db` folder
@coderabbitai ignore
> :hammer: (db) migrate Pageview to knex

- packages/@ourworldindata/grapher/src/barCharts/DiscreteBarChart.tsx
- Sometimes, there was a bit too much padding on top of a discrete bar chart (see screenshot below)
- The reason is that Grapher incorrectly thinks that we need space for a legend
| <img width="733" alt="Screenshot 2024-02-26 at 15 02 37" src="https://github.com/owid/owid-grapher/assets/12461810/b83b5342-2793-460b-a6ba-01854655f7b5">  | <img width="733" alt="Screenshot 2024-02-26 at 15 02 23" src="https://github.com/owid/owid-grapher/assets/12461810/59318376-fd39-4652-966f-e40bf920c284"> |
> 🐛 (discrete bar) remove extra space on top

- packages/@ourworldindata/grapher/src/modal/SourcesModal.scss
- site/DataPageContent.scss
- Fixes a number of CSS issues for datapages and Grapher's sources modal (see screenshots below)
- Examples:
- https://ourworldindata.org/grapher/same-sex-sexual-acts-illegal
- https://ourworldindata.org/grapher/median-income-after-tax-lis
| <img width="677" alt="Screenshot 2024-02-27 at 17 20 58" src="https://github.com/owid/owid-grapher/assets/12461810/63583c8e-14f7-4bb6-bb5d-61a72cd0416e"> | <img width="677" alt="Screenshot 2024-02-27 at 17 20 35" src="https://github.com/owid/owid-grapher/assets/12461810/540662b8-8301-4bd7-89db-e19cf4c44532"> |
| <img width="677" alt="Screenshot 2024-02-27 at 17 12 47" src="https://github.com/owid/owid-grapher/assets/12461810/40124fb6-dfd7-4171-98e0-87c0c95a3774"> | <img width="677" alt="Screenshot 2024-02-27 …
> 🐛 (sources) fix css for lists and headings

- adminSiteServer/adminRouter.tsx
- adminSiteServer/apiRouter.ts
- adminSiteServer/mockSiteRouter.tsx
- baker/GrapherBaker.tsx
- baker/algolia/indexToAlgolia.tsx
- baker/countryProfiles.tsx
- baker/formatWordpressPost.tsx
- baker/runBakeGraphers.ts
- db/Variable.test.ts
- db/model/Dataset.ts
- db/model/User.ts
- db/model/Variable.ts
- db/tests/basic.test.ts
Adds knex based DB access code for tables users and variables
> Convert users and variables types to knex

- baker/GDriveImagesBaker.tsx
- db/model/Image.ts
- packages/@ourworldindata/utils/src/image.ts
- packages/@ourworldindata/utils/src/index.ts
- site/gdocs/components/Image.tsx
>  _Lossless WebP images are typically 26% smaller than the same images in PNG format._ 
\- [MDN](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types#webp_image)
Unfortunately, WebP is not as well-supported as PNG in most operating systems and programs, which Max and Este feel is more important when it comes to people using our graphics in their documents. 😢
Resolves https://github.com/owid/owid-grapher/issues/3238
Resolves https://github.com/owid/owid-grapher/issues/3220
> 🔨 bake gdoc images as PNG instead of WebP

- site/gdocs/components/HomepageIntro.tsx
Fixes 
which was occurring due to a nonsensical usage of the nullish coalescing operator
> 🐛 fix undefined URLs in homepage featured posts

- db/model/Gdoc/GdocBase.ts
Remove duplicate call to `loadLinkedCharts()` in `GdocBase.loadState()`.
> refactor: remove duplicate loadLinkedCharts

- site/gdocs/components/HomepageSearch.tsx
- site/gdocs/components/centered-article.scss
- Fixes the content jump from the search bar loading in
- Makes the all-topics link unclickable on mobile, because we hide the all topics section on mobile
https://github.com/owid/owid-grapher/assets/11844404/af9f6c4d-0772-4b1f-a836-f6e6ea5e8bd3
> ✨ homepage CSS fixes

- packages/@ourworldindata/grapher/src/axis/Axis.ts
- packages/@ourworldindata/utils/src/Util.ts
- packages/@ourworldindata/utils/src/index.ts
- Fixes https://github.com/owid/owid-grapher/issues/3007
- On smaller screens, Grapher sometimes displays a single tick label due to space constraints, which makes it impossible to read the chart
- Example: https://ourworldindata.org/grapher/death-rate-by-cause-who-mdb?facet=metric (on a smaller screen)
- Given a number of base ticks, we want to find a subset of ticks whose labels are not overlapping:
- The original strategy figured out which tick labels to hide so that we don't end up with overlapping tick labels
- The updated strategy does the same but retries if we end up with a single visible tick label:
1. Hide overlapping ticks, allowing for some padding (3px) between tick labels (this is the original strategy)
2. If we end up with a single tick label, try again but reduce the …
> 🐛 (grapher) show a minimum of two tick labels if possible

- packages/@ourworldindata/grapher/src/header/Header.tsx
> [!IMPORTANT]
> Wait for https://github.com/owid/owid-grapher/pull/3211 to be merged.
- When exporting to static charts, we adjust the font size to fit the chart title into a single line if possible
- The font size is decreased by not more than 20% using 0.5px steps
- But we don't currently do this on the web
- We re-introduce this technique for charts rendered in an interactive environment (we had removed this for interactive charts in the redesign)
- I think reducing the font size by 20% is quite a lot, so I opted for 15% instead (the old grapher also used 85% of the original font size as a threshold)
- With 85%, the font size gets at most reduced to...
- for narrow charts: 18px * 0.85 = 15.3px (subtitle font size = 12px)
- for medium charts: 20px * 0.85 = 17px (subtitle font size = …
> ✨ (title) try to fit chart title into a single line

- packages/@ourworldindata/components/src/Button/Button.scss
- packages/@ourworldindata/components/src/Button/Button.tsx
- packages/@ourworldindata/components/src/index.ts
- site/gdocs/components/ExplorerTiles.scss
- site/gdocs/components/ExplorerTiles.tsx
- site/gdocs/components/HomepageIntro.scss
- site/gdocs/components/HomepageIntro.tsx
- site/gdocs/components/KeyIndicator.scss
- site/gdocs/components/KeyIndicator.tsx
- site/gdocs/components/KeyIndicatorCollection.scss
- site/gdocs/components/KeyIndicatorCollection.tsx
- site/gdocs/components/LatestDataInsights.scss
- site/gdocs/components/LatestDataInsights.tsx
- site/owid.scss
Makes a new component for the `~~Button~~` that we're using everywhere
Contemplated hiding the icon when `onClick` is defined but decided to cross that bridge when we come to it.
[red-button-mobile](https://github.com/owid/owid-grapher/assets/11844404/8a8b7e15-3910-488d-bc39-3f8e5b0165e3)
[master-mobile](https://github.com/owid/owid-grapher/assets/11844404/0fa75c75-bde9-40f4-905d-0e00fe460375)
[master-desktop](https://github.com/owid/owid-grapher/assets/11844404/5ea8cfb8-cd6e-4c79-8e60-dfab12b4fd02)
[red-button-desktop](https://github.com/owid/owid-grapher/assets/11844404/104f3933-12f2-4b93-b6fa-897c1fe73fc2)
> 🎉 add reusable Button component

- site/Footnote.tsx
Adds a [debounce](https://atomiks.github.io/tippyjs/v6/all-props/#interactivedebounce) to our gdoc tooltips
Before:
https://github.com/owid/owid-grapher/assets/11844404/2bc89aab-10b6-436d-8c0b-f05aeced0889
After:
https://github.com/owid/owid-grapher/assets/11844404/9e09e930-fc33-4df8-a7e9-f64e401bc10b
> 🎉 add debounce to tooltip

- explorer/Explorer.tsx
- explorer/ExplorerConstants.ts
- packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.scss
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/core/grapher.scss
- site/gdocs/components/ArticleBlock.tsx
- site/gdocs/components/Chart.scss
- site/gdocs/components/Chart.tsx
- site/gdocs/components/KeyIndicator.tsx
- site/gdocs/components/KeyInsights.tsx
- site/multiembedder/MultiEmbedder.tsx
- On small screens, we want embedded Graphers to use the full screen width and bleed onto the edges horizontally (see screenshots below)
- This used to be implemented via a Grapher property `shouldOptimizeForHorizontalSpace`, which was awfully complicated and also led to the following bug: #3010 
- This PR removes the `shouldOptimizeForHorizontalSpace` property and simply sets negative margins on embedded charts
- It's not guaranteed that the chart title aligns with the text. It just so happens that both the grid-gap and Grapher's frame padding are set to 16px
- As Grapher's frame padding and the grid-gap are not likely to be updated frequently, I think it's okay to rely on that for now
| Not using the full width  | Using the full width  |
| <img width="296" …
> 🔨 (grapher) refactor mobile full width mode for embedded graphers

- packages/@ourworldindata/grapher/src/axis/Axis.ts
Baking fails for chart `sources-population-dataset` with the following error message:
```
TypeError: Cannot read properties of undefined (reading 'toFixed')
_HorizontalAxis.place (/home/owid/owid-grapher/packages/@ourworldindata/grapher/src/axis/Axis.ts:387:46)
<anonymous> (/home/owid/owid-grapher/packages/@ourworldindata/grapher/src/barCharts/DiscreteBarChart.tsx:471:33)
Array.map (<anonymous>)
DiscreteBarChart.render (/home/owid/owid-grapher/packages/@ourworldindata/grapher/src/barCharts/DiscreteBarChart.tsx:462:25)
Object.allowStateChanges [as _allowStateChanges] (/home/owid/owid-grapher/node_modules/mobx/lib/mobx.js:991:15)
/home/owid/owid-grapher/node_modules/mobx-react/index.js:851:28
trackDerivedFunction (/home/owid/owid-grapher/node_modules/mobx/lib/mobx.js:776:24)
Reaction.track …
```
> 🐛 (grapher) guard against undefined

- packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.tsx
Fixes #3283 at the source, and aligns `StaticCaptionedChart` and `CaptionedChart` a bit here.
> fix(static-chart): don't render chart on table tab

- adminSiteServer/mockSiteRouter.tsx
- baker/GrapherBaker.tsx
Remove WP API and DB checks. 
These checks are now unnecessary following the previous refactors whereby the underlying features were migrated to using the grapher DB.
When we disable the WP API and DB, these checks will disable  those same features that we actually want to keep.
> refactor(wp): remove unnecessary checks

- adminSiteServer/mockSiteRouter.tsx
- baker/SiteBaker.tsx
- baker/sitemap.ts
- db/db.ts
- db/model/Gdoc/GdocDataInsight.ts
- db/model/Gdoc/GdocHomepage.ts
- db/model/Gdoc/gdocUtils.ts
- packages/@ourworldindata/types/src/gdocTypes/Gdoc.ts
- site/SiteResources.tsx
This PR adds data insights to the sitemap and nav, and half-heartedly updates some data insight DB code to use Knex, before stopping arbitrarily to avoid spilling out into having to refactor the entire Gdocs codebase.
**Local sitemap with `DATA_INSIGHTS_INDEX_PAGE_SIZE` temporarily set to `2`:**
**The site nav Resources menu:**
> Data insights in sitemap and site nav

- packages/@ourworldindata/components/src/GdocsUtils.ts
- packages/@ourworldindata/components/src/index.ts
- site/gdocs/OwidGdocPage.tsx
Fixes prod's homepage's canonical URL being https://ourworldindata.org/owid-homepage at the moment.
I think `ts-pattern` saves us from overlooking lots of things and that in general we should use it for most Gdoc attributes so that we don't miss anything whenever we add additional gdoc templates.
> 🎉 use ts-pattern for OwidGdocPage attributes

- site/owid.scss
I went through `owid.scss` a bit and removed some rules that are obviously not in use anymore.
For all of these, I ran ripgrep through `live-data/bakedSite` to see that they are actually not in use anymore.
The removed styles are certainly not an exhaustive list of the unused css rules, but it's a start.
- `.owid-data` used to be an "All our articles" block on the old homepage, circa 2018
<details>
<summary>Details</summary>
</details>
- [Fancybox](http://fancybox.net/) used to be a jQuery-based image viewing tool that we certainly don't use any more.
- The `.social` component was this old one here, circa 2018
<details>
<summary>Details</summary>
</details>
- `#un-button` I couldn't really find anywhere.
- `.citation-note` is the `[cite]` in the screenshot below, and `.citation-guideline` …
> cleanup: remove old, unused css

- adminSiteClient/VisionDeficiencies.tsx
Spurred by a [Slack discussion](https://owid.slack.com/archives/C04LNF8LBA8/p1709729771436589): As Lars suggested that the Deuteranopia experience doesn't match his eyesight, I've updated these matrices with those that are used in [Chromium](https://github.com/chromium/chromium/blob/a08db9fd8a986495c18226f9fb2f1e836bb87e62/third_party/blink/renderer/core/css/vision_deficiency.cc#L41-L82).
These are also used in the DevTools, under `Rendering > Emulate vision deficiency`.
And: With these, green and red look pretty much indistinguishable here:
I've also removed the "reduced vision" modes in favour of actual color blindnesses, as Chrome did too.
> enhance: update vision deficiencies with matrices from Chromium source

- _routes.json
- adminSiteServer/mockSiteRouter.tsx
- adminSiteServer/testPageRouter.tsx
- baker/SiteBaker.tsx
See [Slack](https://owid.slack.com/archives/CQQUA2C2U/p1709027956213309) for context.
> refactor: move `embedCharts.js` to the `/assets` route

- baker/SiteBaker.tsx
- packages/@ourworldindata/components/src/GdocsUtils.ts
- packages/@ourworldindata/components/src/index.ts
This is in preparation of baking author pages under `/team`.
This PR reuses the `getCanonicalUrl` logic to build a bake path for all gdocs.
- test article: http://staging-site-generic-bake-dir/launching-data-insights
- test data insight: http://staging-site-generic-bake-dir/data-insights/extreme-poverty-in-china-has-been-almost-eliminated-first-in-rural-then-in-urban-regions
> refactor(baker): allow bake dirs for all gdoc types

- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/slopeCharts/SlopeChart.tsx
- packages/@ourworldindata/utils/src/PointVector.ts
Improves hover interaction on slope charts.
- Improves the "algorithm" to figure out which slope is currently closest to the mouse (see below for an explanation)
- Adds support for clicking anywhere inside the Grapher frame to dismiss the current selection
- Uses the "default" cursor for value and entity labels since they're clickable (default is the text selection cursor)
<details><summary>How do we figure out which slope is currently closest to the mouse?</summary>
<p>
| ![Screenshot 2024-03-07 at 10 27 26](https://github.com/owid/owid-grapher/assets/12461810/f17d8117-804c-49a3-b1d6-2bed5e7f1ffe) | ![Screenshot 2024-03-07 at 10 27 34](https://github.com/owid/owid-grapher/assets/12461810/dd221a34-7396-4503-98d2-743b1b2adca3) |
| We used to …
> ✨ (slope) improve hover interaction

- adminSiteClient/VariableEditPage.tsx
Browser doesn't allow fetching from **http**://etl.owid.io/api/v1 to make edits to metadata. It has to be `https` to make it work.
We need to put ETL API behind Cloudflare auth and make it available on `https`. A weird thing is that switching to a bar chart triggers a form save. Only Enter or Update button should trigger that (maybe we should only allow the button).
This PR disables metadata editing.
> :hammer: disable metadata edits

- site/gdocs/components/ExplorerTiles.tsx
- site/gdocs/components/HomepageIntro.tsx
Just two small fixes for the new homepage that I encountered:
- URI-encode the tag name for the explorer tag icon. Currently, we're using `<img src="https://ourworldindata.org/images/tag-icons/Population and Demographic Change.svg">`, which works but is not technically valid.
- Lazy-load images, especially these explorer tags since they're pretty far down the page
- Add an alt tag while we're at it
> fix(homepage): url-encode tag name for icon

- packages/@ourworldindata/grapher/src/stackedCharts/StackedBarChart.tsx
- Came up on [Slack](https://owid.slack.com/archives/C46U9LXRR/p1710173527593069)
- `StackedBar` y-axis labels are currently overlapping with other charts in faceted mode
- We should only show the y-axis labels for charts in the left row, and hide labels for all other charts
> 🐛 (stacked bar) hide y-axis labels when shared

- packages/@ourworldindata/grapher/src/footer/Footer.tsx
Resolves #3295 
I decided to remove link underlines for all static charts, including SVGs.
- Clicking on links within a static chart SVG on our website is not possible since we usually include the SVG via an `<img />` tag (aside, we also often wrap the static chart image itself in a link, which means the whole image is clickable)
- Thus, link underlines for static charts used on our website are never relevant
- They're only relevant when someone downloads the SVG version of a chart and then looks at it in their browser
- But if they do anything else with the chart, e.g. include it in a doc or presentation slides, share it on social media, etc., again, the link underlines would be misleading since they're not clickable in most environments
All in all, I don't think it's worth the …
> ✨ (static chart) remove link underlines

- adminSiteClient/TestIndexPage.tsx
- adminSiteServer/testPageRouter.tsx
- It would be great if we had some testing in place for explorers
- In recent months, two explorer bugs happened that we should have caught before they went live:
1. The source line disappeared for charts in an explorer 
2. The entity selector disappeared for an explorer 
- Both of these bugs weren't a result of work that was done on explorers, they were the result of code changes that were made far away from explorers
- Additionally, these bugs only surfaced for one (or few) explorers, not all of them
- (What I'm trying to say is that, without any testing in place, it is quite difficult at the moment to catch these bugs before shipping because, in theory, we would need to manually check all explorers for every grapher code change...)
- In the long term, I'd love for the site …
> 🎉 (test page) add explorer test pages

- adminSiteServer/testPageRouter.tsx
- Charts on the admin's test pages are currently much smaller than on the rest of our site
- I updated the chart height to use the same height that we use across our site
> ✨ (test page) make chart size more realistic

- baker/GrapherBakingUtils.ts
- baker/GrapherImageBaker.tsx
- devTools/svgTester/chart-configurations.ts
- devTools/svgTester/dump-chart-ids.ts
- devTools/svgTester/utils.ts
- use a `?` in the filename to separate the slug from the query params. it makes it easier to copy/paste a filename into the browser url bar
- add linear/log y-scales for slope charts
- reduce the number of charts per type to 25
> 🐝 (svg tester) minor improvements

- .github/workflows/svg-compare-all-views.yml
- .github/workflows/svg-compare.yml
- Both actions commit and force-push changes to master
- As a result, the last push wins and overwrites the commit of the sibling action
- Rather than directly committing to master, the actions create a temporary branch called `master__<unix timestamp>` and force-push to that branch
- If there are differences, we want to merge the temporary branch into master
- To do so, we switch to master, pull its current version from remote, merge the temporary branch, and force-push the result
- If we do get a merge conflict, it's automatically resolved by keeping `their` version, i.e. the version of the temporary branch the contains the differences
> 🐛 (svg tester) fix actions when running in parallel

- adminSiteClient/ChartList.tsx
- adminSiteServer/apiRouter.ts
- db/migration/1709913303952-RemoveIsExplorableColumnFromCharts.ts
- db/model/Chart.ts
- db/tests/basic.test.ts
- packages/@ourworldindata/grapher/src/schema/grapher-schema.003.yaml
- packages/@ourworldindata/types/src/dbTypes/Charts.ts
> [!WARNING]  
> Db tests are failing.
Just a little bit of cleanup. Removes the `isExplorable` property from Grapher's config and the `isExplorable` column from the `charts` table.
The config schema states that the `isExplorable` property is not in use and should be removed. I then noticed that the `charts` table has a column called `isExplorable` that also isn't in use, so I decided to remove it too.
Technically, this is a breaking schema change, but there is no real code change, so I guess it's okay not to increase the schema version etc.
> 💄 (grapher) remove isExplorable option

- baker/countryProfiles.tsx
I noticed that right now, on e.g. https://ourworldindata.org/country/germany, we are including some charts that are not currently published, e.g. `acute-care-beds-per-1000`.
The reason for this is that `publishedAt` (because the chart used to be published) is set, but `config.isPublished` is missing.
> fix(country-profiles): only include published charts

- .github/workflows/svg-compare-all-views.yml
- .github/workflows/svg-compare.yml
Don't run SVG tester actions on the `master-1` branch, see [Slack](https://owid.slack.com/archives/CQQUA2C2U/p1710404523492219)
> 🐝 (svg tester) skip actions on master-1

- packages/@ourworldindata/grapher/src/stackedCharts/StackedDiscreteBarChart.test.ts
- packages/@ourworldindata/grapher/src/stackedCharts/StackedDiscreteBarChart.tsx
Related: #2629 
We should also do this for DiscreteBar charts, but I don't have time now. I added a note to the issue above 👆🏻 
|  <img width="867" alt="Screenshot 2024-03-13 at 20 42 53" src="https://github.com/owid/owid-grapher/assets/12461810/e225ae4e-ae39-478b-8e1c-5d3df3c0fb65"> | <img width="867" alt="Screenshot 2024-03-13 at 20 42 41" src="https://github.com/owid/owid-grapher/assets/12461810/ec38035d-8936-49c7-90f8-425d9c436d5c"> |
| <img width="391" alt="Screenshot 2024-03-13 at 20 42 07" src="https://github.com/owid/owid-grapher/assets/12461810/dc9b8d54-b3c2-41bf-a0ad-ff7154e29ec1"> | <img width="391" alt="Screenshot 2024-03-13 at 20 42 22" src="https://github.com/owid/owid-grapher/assets/12461810/a0f56d0d-2dd1-4bff-96a8-cc375ff2e643"> |
> 🐛 (stacked discrete bar) wrap long labels

- adminSiteClient/GdocsIndexPage.tsx
- adminSiteClient/GdocsPreviewPage.tsx
- adminSiteClient/GdocsSettingsContentField.tsx
- adminSiteClient/GdocsSettingsForms.tsx
- adminSiteClient/gdocsDeploy.ts
- adminSiteClient/gdocsValidation.ts
- db/model/Gdoc/GdocAuthor.ts
- db/model/Gdoc/GdocBase.ts
- db/model/Gdoc/GdocFactory.ts
- db/model/Gdoc/enrichedToMarkdown.ts
- db/model/Gdoc/enrichedToRaw.ts
- db/model/Gdoc/exampleEnrichedBlocks.ts
- db/model/Gdoc/rawToArchie.ts
- db/model/Gdoc/rawToEnriched.ts
- packages/@ourworldindata/components/src/GdocsUtils.ts
- packages/@ourworldindata/components/src/styles/colors.scss
- packages/@ourworldindata/types/src/gdocTypes/ArchieMlComponents.ts
- packages/@ourworldindata/types/src/gdocTypes/Gdoc.ts
- packages/@ourworldindata/types/src/index.ts
- packages/@ourworldindata/utils/src/Util.ts
- packages/@ourworldindata/utils/src/image.ts
- packages/@ourworldindata/utils/src/index.ts
- site/gdocs/OwidGdoc.tsx
- site/gdocs/OwidGdocPage.tsx
- site/gdocs/components/ArticleBlock.tsx
- site/gdocs/components/Image.tsx
- site/gdocs/components/Socials.tsx
- site/gdocs/pages/Author.scss
- site/gdocs/pages/Author.tsx
- site/owid.scss
This PR adds a new "Author" OwidGdocType and associated template.
👉 See [this comment](https://github.com/owid/owid-grapher/pull/3256#discussion_r1506571552) for some of the more structural decisions I made.
[staging preview](http://staging-site-author-header/admin/gdocs/1VDcqVRkbi7dYI0xI9m3AQmp14xCEy9UukJoD6n3rHtE/preview), [gdoc](https://docs.google.com/document/d/1VDcqVRkbi7dYI0xI9m3AQmp14xCEy9UukJoD6n3rHtE/edit)
Only consider the "🌑 Dark launch" scope from the [tracking issue](https://github.com/owid/owid-grapher/issues/3224)
> Add author header

- baker/SiteBaker.tsx
- baker/algolia/indexToAlgolia.tsx
- baker/sitemap.ts
- db/model/Gdoc/GdocAuthor.ts
- db/model/Gdoc/GdocPost.ts
- db/model/Post.ts
- Add baking of author pages ([example on staging](http://staging-site-author-bake/team/hannah-ritchie))
- minor refactor of `getPublishedGdocs()` to `getPublishedGdocPosts()` for clarity
Bake on staging with: 
```yarn buildLocalBake http://staging-site-author-bake /home/owid/live-data/bakedSite --steps authors```
> feat(author): bake author gdocs

- .env.example-full
- Makefile
- baker/algolia/configureAlgolia.ts
- baker/algolia/indexChartsToAlgolia.ts
- baker/algolia/indexExplorersToAlgolia.ts
- baker/algolia/indexToAlgolia.tsx
- settings/clientSettings.ts
- site/search/Autocomplete.tsx
- site/search/SearchPanel.tsx
- site/search/searchClient.ts
This PR introduces two changes to make it easier to experiment with changes to Algolia.
The `ALGOLIA_INDEX_PREFIX` setting prepends a prefix to all index names.
E.g. `ALGOLIA_INDEX_PREFIX=dev-lars` will cause `dev-lars-pages`, `dev-lars-charts` and `dev-lars-explorers` to be used
Refreshes Algolia search indexes, creating them if they're missing, including updating any index settings that have changed.
Requires `ALGOLIA_ID` and `ALGOLIA_SECRET_KEY`, plus `ALGOLIA_INDEXING=true`.
See: https://github.com/owid/ops/issues/158
> :honeybee: Add the ability to prefix algolia index names

- site/search/Autocomplete.tsx
- site/search/SearchPanel.tsx
Fixes URLs like `/search?q=1%` from ever happening, and valid URLs like `/search?q=1%25` from breaking the site.
[See Slack](https://owid.slack.com/archives/C46U9LXRR/p1710329501091559).
> fix(search-bar): properly escape and unescape URLs

- adminSiteServer/mockSiteRouter.tsx
- baker/buildLocalBake.ts
- site/SiteConstants.ts
Serves images from the default local bake folder (`localBake`) on local dev environments.
At the very least, it avoids trying to load pages for image routes and fails straightaway.
`yarn buildLocalBake (--steps gdriveImages)` should have run at least once for image to resolve locally.
> fix(dev): serve gdoc images on local dev

- packages/@ourworldindata/components/src/styles/variables.scss
- site/search/Search.scss
- site/search/SearchPanel.tsx
Currently, we have loads of layout jumps in the search UI while the chart previews load.
This is not much of an issue on fast networks, but is very noticeable on slow networks.
In the future, when we want to use dynamic thumbnails sometimes, we need to also think about
- that these take longer to load, and
- that they can also fail to load in rare cases.
That's why I've worked on a jump-less placeholder UI, and also a small error tile that we can show instead.
<table>
<tr>
<th>Before
<th>After
<tr>
<td>
<td>
<tr>
<td>Many layout jumps during loading
<td>No layout jumps; error tile for when errors occur
</table>
For testing this:
- It's best to use DevTools' network throttling, for example "Fast 3G".
- To test the error behavior, manually clear out the `src` field of an `img` element in …
> enhance(search): show placeholder panels for chart thumbnails

- packages/@ourworldindata/grapher/src/controls/ActionButtons.tsx
- packages/@ourworldindata/grapher/src/controls/ContentSwitchers.tsx
- packages/@ourworldindata/grapher/src/controls/EntitySelectionToggle.tsx
- packages/@ourworldindata/grapher/src/controls/SettingsMenu.tsx
- packages/@ourworldindata/grapher/src/timeline/TimelineComponent.tsx
When inside the Variable Edit form, the `type="submit"` default behaviour of the HTML `<button>` element was messing things up. Explicitly setting all Grapher buttons to `type="button"` to fix this and any potential future issues like this.
> 🐛 add type="button" to all Grapher buttons

- db/migration/1710499585939-RemoveIsExplorableFromGrapherConfigs.ts
Follow up for #3323. Removes `isExplorable` from chart configs
> 🐝 remove isExplorable from Grapher configs

- packages/@ourworldindata/grapher/src/slopeCharts/SlopeChart.tsx
Fixes a bug in slope charts where the current selection was incorrectly dismissed when you drag the slider but then release the drag outside of the timeline
> 🐛 (slope) incorrectly dimissed selection

- .bundlewatch.config.json
- packages/@ourworldindata/grapher/src/horizontalColorLegend/HorizontalColorLegends.tsx
- packages/@ourworldindata/grapher/src/slopeCharts/SlopeChart.tsx
- packages/@ourworldindata/grapher/src/slopeCharts/SlopeChartConstants.ts
Moves the colour legend to the top on mobile. In other words, renders a vertical colour legend on larger screens and a horizontal colour legend on smaller screens.
| <img width="367" alt="Screenshot 2024-03-08 at 14 42 21" src="https://github.com/owid/owid-grapher/assets/12461810/e7d3496f-6e38-4225-8898-5cbc89503205"> | <img width="367" alt="Screenshot 2024-03-08 at 14 42 11" src="https://github.com/owid/owid-grapher/assets/12461810/ccad7e3b-0ff9-4c65-ba52-d6306babb1b6"> |
- It looks like we're not making use of the full width, but we need the space on the left to be reserved for entity labels in case the user select a slope
> ✨ (slope) move legend to the top on mobile

- adminSiteClient/EditorBasicTab.tsx
- db/migration/1709735276047-RemoveSizeDimensionFromSlopeCharts.ts
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/slopeCharts/SlopeChart.tsx
- packages/@ourworldindata/grapher/src/slopeCharts/SlopeChartConstants.ts
Removes the size dimension for slope charts.
- The size dimension currently maps to the stroke width of the slopes (we don't communicate that to the user though)
- We realised that it doesn't add to the understanding of the chart:
- In the case of slope charts with many slopes, slope thickness is hardly visible since slopes are overlapping ([example](https://ourworldindata.org/grapher/children-per-woman))
- In the case of slope charts with few slopes, different slope widths add noise since it isn't clear why some slopes are thicker than others ([example](https://ourworldindata.org/grapher/participation-time-in-personal-care-per-day))
> ✨ (slope) remove size dimension

- packages/@ourworldindata/grapher/src/slopeCharts/SlopeChart.tsx
- fixes #2878 
- Example chart: [Live](https://ourworldindata.org/grapher/child-mortality-1960-vs-latest-slope?country=~DEU) / [Staging](http://staging-site-slope-empty-focus-group/grapher/child-mortality-1960-vs-latest-slope?country=~DEU) (note that Germany is selected in both)
- Screenshots:
| <img width="844" alt="Screenshot 2024-03-08 at 13 54 37" src="https://github.com/owid/owid-grapher/assets/12461810/db941bdf-249a-411c-a682-024c31843508"> | <img width="844" alt="Screenshot 2024-03-08 at 13 54 20" src="https://github.com/owid/owid-grapher/assets/12461810/14e7f610-217a-41d0-a339-9687256962e4"> |
| Note that the slope chart is in a weird state (all legend items are grayed out while slopes are displayed as usual) | If an entity is selected …
> 🐛 (slope) fix chart state if entity without data is selected

- packages/@ourworldindata/grapher/src/stackedCharts/StackedBarChart.tsx
In #3288, Sophia gets rid of the `<Text>` component uses in slope charts.
The only other remaining use is in stacked bar charts, but there it is only used in one (simple) place: The tick labels as seen below.
We can instead just use `dy` to achieve (almost) the same effect.
> cleanup: remove <Text> component and use dominant-baseline instead

- .github/actions/setup-node-yarn-deps/action.yml
- .github/workflows/auto-author-assign.yml
- .github/workflows/auto-deploy-gh-pages.yml
- .github/workflows/buildkite.yml
- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/prettify.yml
- .github/workflows/stale.yml
- .github/workflows/svg-compare-all-views.yml
- .github/workflows/svg-compare.yml
(almost) all of them should now be using node20, which gets rid of a deprecation warning; see https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
> chore(ci): update github actions

- site/search/SearchPanel.tsx
Resolves #2932
It was a simple hardcoded value that was causing the hit clicks not to be tracked.
Before, all events were being sent as:
```json
{
"events": [
{
"eventType": "click",
"index": "charts",
"queryID": "blah",
"objectIDs": ["global-food-2"],
"positions": [1],
"eventName": "click",
"userToken": "blah",
},
],
}
```
which meant Algolia wasn't able to resolve them to any actual results in the index.
I'm waiting for the analytics data to update in our owid-staging application to confirm this has fixed it and then we should be good to go.
> 🐛 fix explorer and r&w algolia hit clicks not being tracked correctly

- baker/SiteBaker.tsx
- baker/siteRenderers.tsx
Resolves #2936
@marcelgerber you suggested adding a redirect but this should also work, right?
Or is it still preferable to keep it at index.html for server best practice reasons? (My only reason for doing it this way instead is that it seems simpler)
> 🐛 change entries-by-year baked filepath to fix ERR_TOO_MANY_REDIRECTS

- adminSiteClient/Admin.tsx
- adminSiteClient/AdminLayout.tsx
- adminSiteClient/DatasetEditPage.tsx
- adminSiteClient/OriginList.tsx
- adminSiteClient/SourceList.tsx
- adminSiteClient/VariableEditPage.tsx
ETL API now runs on HTTPS behind Cloudflare Access (e.g. https://etl.owid.io/api/v1/health). Hence, the browser doesn't complain anymore about making requests to http, and we can enable metadata editing again.
We have to call ETL API with `credentials: "include"` to pass CF cookies needed for auth. I've also turned on "loading indicator" in case the update takes longer (it should take a couple of seconds max).
Go to [dummy indicator](http://staging-site-enable-metadata-edits/admin/variables/553199) and edit its name or any other editable field. Then click on `Update indicator` and wait for loading to complete. You should see your change after refresh. (In prod, it would also make a commit to ETL)
> :hammer: enable metadata edits, add loading

- baker/postUpdatedHook.ts
- db/model/PostLink.ts
- db/syncPostsToGrapher.ts
Migrates the access to the post_links table from TypeORM to knex
> 🔨 migrate PostLink to knex

- adminSiteServer/exportGitData.ts
- baker/algolia/indexChartsToAlgolia.ts
- baker/algolia/indexExplorersToAlgolia.ts
- baker/algolia/indexToAlgolia.tsx
- baker/bakeGdocPost.ts
- baker/bakeGdocPosts.ts
- baker/batchTagWithGpt.ts
- baker/buildLocalBake.ts
- baker/postUpdatedHook.ts
- baker/recalcLatestCountryData.ts
- baker/runBakeGraphers.ts
- baker/startDeployQueueServer.ts
- baker/syncRedirectsToGrapher.ts
- db/analyzeWpPosts.ts
- db/db.ts
- db/migrateWpPostsToArchieMl.ts
- db/model/Gdoc/GdocBase.ts
- db/refreshPageviewsFromDatasette.ts
- db/syncPostsToGrapher.ts
- db/tests/basic.test.ts
- devTools/markdownTest/markdown.ts
- devTools/svgTester/dump-chart-ids.ts
- devTools/svgTester/dump-data.ts
This PR adds a new parameter for the transaction creation functions that closes the database connection. This is useful for scripts which usually want to run stuff in one transaction and would then like to have the DB connection closes. For the api router the option is not used of course as it is a long running process.
> ✨ unify transaction creation and close db connection in same call for scripts

- adminSiteServer/adminRouter.tsx
- adminSiteServer/app.tsx
- adminSiteServer/mockSiteRouter.tsx
- baker/DatapageHelpers.ts
- baker/DeployUtils.ts
- baker/GrapherBaker.tsx
- baker/SiteBaker.tsx
- baker/algolia/indexToAlgolia.tsx
- baker/bakeGdocPost.ts
- baker/bakeGdocPosts.ts
- baker/buildLocalBake.ts
- baker/runBakeGraphers.ts
- baker/siteRenderers.tsx
- baker/sitemap.ts
- baker/startDeployQueueServer.ts
- db/model/Gdoc/GdocAuthor.ts
- db/model/Gdoc/GdocBase.ts
- db/model/Gdoc/GdocDataInsight.ts
- db/model/Gdoc/GdocFactory.ts
- db/model/Gdoc/GdocPost.ts
- db/model/Image.ts
- db/model/Post.ts
- devTools/markdownTest/markdown.ts
This is not a nice PR - the images code was wrongly tagged as needing only a read-only transaction but it can actually update the DB when a sync occurs. This then bubbled up to a lot of places unfortunately.
> 🔨 images need a RW transaction in case they need to update the db 😢 - bubble this up

- adminSiteServer/adminRouter.tsx
- adminSiteServer/testPageRouter.tsx
- baker/postUpdatedHook.ts
- db/syncPostsToGrapher.ts
This PR fixes various issues that have accumulated during the DB refactor
> Fix remaining refactor issues

- adminSiteServer/mockSiteRouter.tsx
- baker/SiteBaker.tsx
- baker/siteRenderers.tsx
- db/db.ts
- packages/@ourworldindata/types/src/gdocTypes/Gdoc.ts
- site/DataInsightsIndexPage.tsx
- site/Head.tsx
- site/SiteFooter.tsx
- site/gdocs/OwidGdocPage.tsx
- site/gdocs/pages/Homepage.tsx
- site/gdocs/utils.tsx
Resolves https://github.com/owid/owid-grapher/issues/3365
Changes:
- Adds a new data insight feed page at `/atom-data-insights.xml`
- Adds logic to link to this page in the `<head>` if on `/data-insights` or a child thereof
- Updates UI to link to the new atom feed
To test:
1. Have some data insights published
2. Go to http://localhost:3030/atom-data-insights.xml and confirm it looks good
3. Check for regressions in http://localhost:3030/atom.xml
4. View source on http://localhost:3030/data-insights and http://localhost:3030/data-insights/your-data-insight-slug and check that the atom feed link is updated
5. Check for regressions on 2 other pages
6. Run `node itsJustJavascript/baker/buildLocalBake.js --steps rss` and confirm the output looks good
> Data insights RSS feed

- db/db.ts
The knexRaw function returns an array of objects. For insert statemements the first row then contains information like the insertId. The insert helper function forgot to reach into the array and return the first result but the type signature made it look like that is what happened.
> 🐛 fix insert statement array return value

- adminSiteServer/apiRouter.ts
This fixes #2430 - we may still want to add a trigger to ensure this always happens (even if the chart is created through different means) but for now this will do.
> 🐛 fix chart config not containing id after insert bug

- Makefile
- baker/updateAvailableEntities.ts
- baker/updateChartEntities.ts
- db/migration/1711549786507-CreateChartEntitiesTable.ts
- db/model/Entity.ts
- packages/@ourworldindata/types/src/dbTypes/ChartsXEntities.ts
- packages/@ourworldindata/types/src/index.ts
Implements #3401.
Currently, this is just a batch script that will update _all_ charts.
But it is written in such a way that it will be easy to hook into it in the future, and we could call `obtainAvailableEntitiesForGrapherConfig` in a server-side `onSave` handler, and update `charts_x_entities` for that chart only.
Ready for review already, but some TODOs still:
---
On my local machine, running the script takes 7.5 minutes.
The resulting table has 625,676 rows.
> feat: index chart entities into `charts_x_entities` table

- site/DataInsightsIndexPage.tsx
- site/DataInsightsIndexPageContent.tsx
- site/gdocs/OwidGdocPage.tsx
Fixes an issue with the local preview for data insights, and adds a more informative `og:description`
> Data insight `og:description`

- Makefile
Our yarn buildTsc script does an incremental build that doesn not delete old files. When we run yarn runDbMigrations, this can lead to problems.
This PR makes sure that we delete the itsJustJavascript directory when we run the make migrate command
> 🥽 make sure that "make migrate" deletes itsJustJavascript for safety

- db/model/Post.ts
A recent change to exclude data-insights from related posts on grapher page had a spurrious comma in the end which is not allowed in sql
> Fix comma in sql bug

- db/model/Gdoc/GdocFactory.ts
GDoc documents of type Fragment were accidentally included in queries for published gdocs. This made them appear in the sitemap and algolia results.
> 🐛 Exclude fragments from normal baking and showing up in algolia

- db/migration/1710255240486-AddTypeAndSortToVariables.ts
- packages/@ourworldindata/core-table/src/CoreTableColumns.ts
- packages/@ourworldindata/grapher/src/core/LegacyToOwidTable.ts
- packages/@ourworldindata/types/src/OwidVariable.ts
- packages/@ourworldindata/types/src/dbTypes/Variables.ts
- packages/@ourworldindata/types/src/domainTypes/CoreTableTypes.ts
- packages/@ourworldindata/types/src/index.ts
Grapher part of adding indicator `type` to MySQL and adding ordinal type. Here's [ETL pull request](https://github.com/owid/etl/pull/2423).
Fixes https://github.com/owid/owid-grapher/issues/1690
> :sparkles: add type and sort columns to variables table

- Makefile
- db/tests/run-db-tests.sh
- docs/devcontainer-setup.md
We used to still use the old `docker-compose` in a few places and it seems that this was deprecated now on the GA runner image. This PR switches to the modern `docker compose` invocation everywhere.
> Switch to `docker compose` invocation

- db/db.ts
The live grapher database's charset is `utf8mb4`, but the default connection charset for knex is `utf8mb3` (utf8, multibyte 3) which is [deprecated](https://dev.mysql.com/blog-archive/mysql-8-0-when-to-use-utf8mb3-over-utf8mb4/) and was causing the emoji in our dods to render as `?` characters.
This PR fixes that.
Further reading: [a great blog post on unicode](https://tonsky.me/blog/unicode/)
> 🐛 use `utf8mb4` for knex connections

- baker/algolia/indexChartsToAlgolia.ts
Review hints: Please have a look at the query :)
Especially make sure that there's not gonna be duplicate entries in the `tags` and `entityNames` arrays.
> feat(algolia): use `charts_x_entities` table for Algolia indexing

- adminSiteClient/ChartEditor.ts
- adminSiteClient/GrapherConfigGridEditor.tsx
- db/migration/1711580214803-RemoveAvailableEntitiesFromChartConfigs.ts
- devTools/schemaProcessor/columns.json
- packages/@ourworldindata/grapher/src/core/GrapherConstants.ts
- packages/@ourworldindata/grapher/src/schema/grapher-schema.004.yaml
Follow-up work to #3418.
Drops the `$.data` property from all our configs. It was only used for `$.data.availableEntities`, which we won't need any longer.
> chore: remove `$.data.availableEntities` from configs and schema

- adminSiteClient/ChartEditor.ts
- adminSiteClient/EditorHistoryTab.tsx
- adminSiteServer/apiRouter.ts
Just a tiny thing I was working on, and which is gonna be super useful:
> feat(admin): ability to diff chart revisions

- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- site/Head.tsx
- site/detailsOnDemand.tsx
- Fixes #3439
- We recently started validating DoDs in Grapher
- We need validation when we automatically check for DoDs with a specific prefix, like `grapher_indicator_my-indicator-title` (we never shipped automatic DoD checking though)
- `window.details` must be populated before Grapher loads for validation to work (if it's not there, Grapher can't validate and assumes all given details are invalid)
- Since we never shipped automatic DoD checking, we also don't currently need validation and can just remove the code around it
- Let's just do so for now and figure out how to do bug-free details validation in Grapher when we really need it
- This is "tested" by refreshing a Grapher page a number of times and verifying that the DoD checkbox in the Download modal is present
> 🐛 (grapher) don't validate dods

- .eslintrc.cjs
Pycharm otherwise raises error about ESLint being unable to read the referenced file.
> Fix ESLint config when using Pycharm

- site/LongFormPage.tsx
- site/SiteFooter.tsx
These are the only places I found that referenced that old page(s?).
Fixes #2013.
> Fix outdated "how to use" links

- Makefile
- baker/algolia/configureAlgolia.ts
- baker/algolia/indexExplorerViewsToAlgolia.ts
- baker/algolia/indexExplorersToAlgolia.ts
- explorer/ExplorerDecisionMatrix.ts
- site/search/searchTypes.ts
Resolves #3332.
This PR doesn't have its own Algolia staging environment, but instead you can look at the ones for the upstack PR #3429: `search-explorer-indexing-algolia`
Ranking criteria being used:
- 7-day pageviews of the _whole_ explorer
- Number of explorer settings that differ from the default
- Length of title
These are then combined into the rather-arbitrary-but-seemingly-working-quite well
```
score = explorerPageviews * 10 - numNonDefaultSettings * 50 - titleLength
```
Note that `explorerPageviews` doesn't change between different views of the same explorers; so it's only used to discriminate results from different explorers.
- `distinct: 4` by `explorerSlug`
- order by `viewTitleIndexWithinExplorer`
- _maybe_ set [`removeWordsIfNoResults`](https://www.algolia.com/doc/api-refere …
> feat(algolia): index explorer views to Algolia

- db/migration/1712742455229-UnpublishWPRedirectedArticles.ts
This migration unpublishes [all (currently 36) articles](http://datasette-private/owid?sql=SELECT+p.id+AS+postId%2C+p.title%2C+p.updated_at_in_wordpress%2C+r.source%2C+r.target%2C+r.createdAt%0D%0AFROM+redirects+r%0D%0AJOIN+posts+p+ON+r.source+%3D+%22%2F%22+%7C%7C+p.slug%0D%0AWHERE+p.status+%3D+%22publish%22%0D%0AAND+p.content+%21%3D+%22%22%0D%0AORDER+BY+p.updated_at_in_wordpress) which are being redirected.
The main benefit is that they will no longer appear as search results, [see discussion here](https://owid.slack.com/archives/C06JNSC90UE/p1712739957398759).
Is there anything we need to keep in mind when unpublishing? At least for WP, it should be enough to just mark them as private, right?
> migrate: Unpublish WP articles which are redirected

- site/search/SearchPanel.tsx
Joe was suggesting this; because otherwise the R&W results are pretty much useless when a country name is present in the query (which we are gonna be promoting now).
Overall, we were also talking about how useless fulltext queries usually are. There are only some rare cases where they provide any value currently; and if we end up in a situation where we also index headings, key insights, SDG targets etc., then we could stop doing fulltext search entirely.
Tip: Review with whitespace changes hidden :)
> feat(search): disable fulltext `pages` search if we detect a country name in query

- site/SiteAnalytics.ts
- site/search/Autocomplete.scss
- site/search/Autocomplete.tsx
- site/search/Search.scss
- site/search/SearchPanel.tsx
- site/search/searchClient.ts
- site/search/searchTypes.ts
> feat(search): surface explorer views in search results

- baker/algolia/configureAlgolia.ts
- site/search/SearchPanel.tsx
Once we detect a country/region name in the search query string, we now add it as a query param to the explorer link.
We do this *even though we don't know for sure that data for this country will be available in the explorer*. This is an accepted tradeoff, since we believe that it'll be worth it for the 80-90% of cases where this just works (most of our explorers have countries as entities, and most of them include a lot of different entities).
And then, if no data is available for that entity, then the user will be presented with an empty explorer - which is not great, but also not the end of the world.
> feat(search): pre-select explorer entities if they appear in search query

- packages/@ourworldindata/core-table/src/OwidTable.ts
- packages/@ourworldindata/grapher/src/lineCharts/LineChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/AbstractStackedChart.tsx
I noticed some performance problems with the `tableForSelection` call, and specifically the `transformTableForSelection` method in chart instances, while reviewing #3447.
So, I got at it and could quite improve these 🚀 
- For https://ourworldindata.org/grapher/excess-deaths-cumulative-economist-single-entity, we're now down from 3 seconds per call to 100ms
- Similar for https://ourworldindata.org/grapher/daily-new-estimated-covid-19-infections-icl-model
---
What I did to check that this is correct:
I just loaded up 10-or-so different charts with `missingDataStrategy = 'hide'`, ran `grapher.tableForSelection.dump()`, and compared stats like `numRows`, `numValidCells`, and `numErrorValues` across live and localhost.
They are all the same everywhere.
> perf(table): optimize `tableForSelection` calls

- adminSiteClient/gdocsValidation.ts
- baker/GrapherBaker.tsx
- db/model/Gdoc/GdocBase.ts
- db/model/Gdoc/archieToEnriched.ts
- db/model/Gdoc/gdocUtils.ts
- packages/@ourworldindata/types/src/gdocTypes/Datapage.ts
- packages/@ourworldindata/utils/src/Util.test.ts
- packages/@ourworldindata/utils/src/Util.ts
- packages/@ourworldindata/utils/src/image.ts
- packages/@ourworldindata/utils/src/index.ts
- site/DataPageV2.tsx
- site/DataPageV2Content.tsx
Fixes https://github.com/owid/owid-grapher/issues/3301
I remember taking a road trip that passed through a town with an odd bend in the highway as you exited. Apparently they'd started constructing the road from both ends, and only realized that they weren't aligned by the time they were in sight of each other.
This part of the datapage code feels a bit like that, except the two bits of road aren't even connected 😄 (All due respect to Daniel, who was under an enormous time crunch to get data pages implemented across the entire stack)
Changes:
- Removes the exhaustive `imageMetadataDicitionary` and other unused properties from FAQ documents that were being attached to the datapage's embedded JSON
- Attaches image metadata for the related research & writing's featured images (which are the …
> Fix data pages embedding all image metadata

- adminSiteClient/AdminApp.tsx
- adminSiteClient/AdminSidebar.tsx
- adminSiteClient/RedirectsIndexPage.tsx
- adminSiteClient/SiteRedirectsIndexPage.tsx
- adminSiteClient/admin.scss
- adminSiteServer/apiRouter.ts
- db/migration/1713447826006-UniqueRedirectSource.ts
- db/model/Redirect.ts
- package.json
- packages/@ourworldindata/types/src/dbTypes/Redirects.ts
- yarn.lock
I got heavily inspired by `RedirectsIndexPage.tsx`. I used `react-hook-form` since I had good experience with it before, and it makes the form handling nice.
Server validation error leads to a generic error popup on the frontend, which is bad UX, but it seems this is what we do also elsewhere. Let me know if there is a good way to avoid that.
> Add admin page for site redirects

- adminSiteServer/apiRouter.ts
- baker/SiteBaker.tsx
- baker/algolia/algoliaUtils.tsx
- baker/algolia/indexToAlgolia.tsx
- baker/sitemap.ts
- db/db.ts
- db/model/Gdoc/GdocAuthor.ts
- db/model/Gdoc/GdocBase.ts
- db/model/Gdoc/GdocFactory.ts
- db/model/Gdoc/GdocPost.ts
- db/model/Image.ts
- devTools/updateImageHeights/update-image-heights.ts
- packages/@ourworldindata/types/src/dbTypes/PostsGdocs.ts
- packages/@ourworldindata/types/src/dbTypes/Tags.ts
- packages/@ourworldindata/types/src/gdocTypes/Gdoc.ts
- packages/@ourworldindata/types/src/gdocTypes/Image.ts
- packages/@ourworldindata/types/src/index.ts
- site/gdocs/pages/DataInsight.tsx
https://github.com/owid/owid-grapher/pull/3496 was reverted because I forgot to select tags in the new version of `getPublishedGdocPosts`. This broke topic pages' all-charts blocks, data pages related research & writing sections, and algolia indexing of tags.
This PR is a re-application of that PR, plus a new function called `getPublishedGdocPostsWithTags` which selects published posts plus `{ tags: MinimalTag[] }`
`MinimalTag` follows the `Minimal-` suffix that I've used elsewhere to designate subtypes of our DB rows with only the attributes that we need for rendering on the frontend.
`getPublishedGdocPostsWithTags` is now correctly called in the SiteBaker, and in the Algolia indexing script.
I also added some additional logging to the SiteBaker for prefetching attachments, related to …
> Don't fetch image metadata during Algolia sync (with tags)

- db/model/Gdoc/GdocFactory.ts
- packages/@ourworldindata/types/src/dbTypes/PostsGdocs.ts
`gdocFromJSON` gets called in a few different places that have already correctly parsed the JSON tags object.
This PR moves the JSON tags parsing for `DBRawPostGdocWithTags->DBEnrichedPostGdocWithTags` to the correct place so that there's no type error from calling `JSON.parse([ { id: 1, name: "some-tag" } ])`
> 🐛 parse gdoc JSON tags in the correct place

- db/db.ts
- db/model/Gdoc/GdocHomepage.ts
- packages/@ourworldindata/utils/src/Util.ts
- packages/@ourworldindata/utils/src/index.ts
- site/SiteNavigation.tsx
- site/gdocs/components/HomepageIntro.scss
- site/gdocs/components/HomepageIntro.tsx
- site/gdocs/components/KeyIndicatorCollection.tsx
- site/search/Autocomplete.scss
- site/search/searchClient.ts
Resolves (most of) [#3290](https://github.com/owid/owid-grapher/issues/3290)
> Homepage updates

- adminSiteClient/TagEditPage.tsx
- adminSiteServer/apiRouter.ts
- db/migration/1713987607342-RemoveTagsBulkImport.ts
- packages/@ourworldindata/types/src/dbTypes/Tags.ts
It turned out that these tags - 1286 in total - were never used anywhere, were not surfaced to the authors, and hence we certainly don't need these ones any longer.
They can also be deleted cleanly despite the `tags` table having many foreign keys pointing to it, indicating that these tags really weren't used anywhere.
> migrate(tags): delete tags with `isBulkImport` & delete column

- .github/workflows/svg-compare-all-views.yml
- .github/workflows/svg-compare.yml
- devTools/svgTester/utils.ts
Small tweaks to prepare the SVG tester for move to foundation. In particular,
- the base URL is hard-coded to point to prod (this used to depend on the environment, i.e. was `localhost` for reference charts since they're usually exported locally and `staging-site-x` on staging, which then made every chart fail)
- keep the SVG tester GitHub actions for now since it's convenient that they're setup to fail when differences were detected (the Buildkite jobs currently don't give any indication of success/failure) but remove the steps that commit/push to `owid-grapher-svgs` (in the future we want the Buildkite job to post a comment on a PR with a summary; if we have that, we can drop the GitHub actions)
> 🐝 (svg tester) prepare for move to foundation

- baker/GrapherBaker.tsx
- db/db.ts
- db/migration/1712842552502-AddPostsSlugIndex.ts
- db/migration/1712843782834-AddVirtualGdocsTypeColumn.ts
- db/model/Gdoc/GdocBase.ts
- db/model/Gdoc/GdocFactory.ts
- db/model/Gdoc/GdocHomepage.ts
- db/model/Post.ts
- site/GrapherPage.jsdom.test.tsx
- site/GrapherPage.tsx
Various attempts to improve https://github.com/owid/owid-grapher/issues/3462
> Grapher baking performance enhancements

- baker/GrapherBaker.tsx
Addresses #3462.
This doubles the baking speed of the `bakeAllChangedGrapherPagesVariablesPngSvgAndDeleteRemovedGraphers` step.
There are probably also other baking steps that we want to use a similar pattern for - especially those using a read-only transaction (screw you, images!), and those that are currently using `pMap` or `Promise.all`.
> fix(baking): bake graphers in parallel, using multiple db transactions

- adminSiteServer/testPageRouter.tsx
> fix(admin): fix test pages paging

- explorer/Explorer.tsx
Fixes a bug where embedded explorers (with hidden controls) scrolled to the "About this data" section instead of opening the sources modal when the "Learn about this data" link was clicked. This happened because Grapher was not aware that it was embedded since the explorer didn't pass that information on.
> 🐛 (explorer) pass isEmbeddedInAnOwidPage to Grapher

- packages/@ourworldindata/grapher/src/closeButton/CloseButton.scss
- packages/@ourworldindata/grapher/src/closeButton/CloseButton.tsx
- packages/@ourworldindata/grapher/src/controls/EntitySelectionToggle.tsx
- packages/@ourworldindata/grapher/src/controls/SettingsMenu.scss
- packages/@ourworldindata/grapher/src/controls/SettingsMenu.tsx
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/core/grapher.scss
- packages/@ourworldindata/grapher/src/modal/Modal.scss
- packages/@ourworldindata/grapher/src/modal/Modal.tsx
- packages/@ourworldindata/grapher/src/modal/SourcesModal.tsx
- packages/@ourworldindata/grapher/src/slideInDrawer/SlideInDrawer.scss
- packages/@ourworldindata/grapher/src/slideInDrawer/SlideInDrawer.tsx
[Cycle 2024.2: Entity selector](https://github.com/owid/owid-grapher/issues/3349) (prep work) | [Designs](https://www.figma.com/file/X5mOEX8zULS6qyHocUYdmh/Grapher-UI?type=design&node-id=2523%3A6266&mode=design&t=7edFp79OOjz6RENz-1)
Adds a reusable `<CloseButton />` component that is used in a number of places:
- In modals
- In the settings popup
- In the slide-in drawer
> 🔨 (grapher) add CloseButton component

- explorer/Explorer.tsx
- packages/@ourworldindata/components/src/DataCitation/DataCitation.tsx
- packages/@ourworldindata/grapher/src/controls/SettingsMenu.scss
- packages/@ourworldindata/grapher/src/controls/SettingsMenu.tsx
- packages/@ourworldindata/grapher/src/core/grapher.scss
- packages/@ourworldindata/grapher/src/core/typography.scss
- packages/@ourworldindata/grapher/src/entitySelector/EntitySelector.scss
- packages/@ourworldindata/grapher/src/modal/DownloadModal.scss
- packages/@ourworldindata/grapher/src/modal/DownloadModal.tsx
- packages/@ourworldindata/grapher/src/modal/EmbedModal.scss
- packages/@ourworldindata/grapher/src/modal/EmbedModal.tsx
- packages/@ourworldindata/grapher/src/modal/Modal.scss
- packages/@ourworldindata/grapher/src/modal/Modal.tsx
- packages/@ourworldindata/grapher/src/modal/SourcesModal.scss
- packages/@ourworldindata/grapher/src/modal/SourcesModal.tsx
- packages/@ourworldindata/grapher/src/sidePanel/SidePanel.scss
- packages/@ourworldindata/grapher/src/sidePanel/SidePanel.tsx
- packages/@ourworldindata/grapher/src/slideInDrawer/SlideInDrawer.scss
- packages/@ourworldindata/grapher/src/slideInDrawer/SlideInDrawer.tsx
[Cycle 2024.2: Entity selector](https://github.com/owid/owid-grapher/issues/3349) (prep work) | [Designs](https://www.figma.com/file/X5mOEX8zULS6qyHocUYdmh/Grapher-UI?type=design&node-id=2523%3A6266&mode=design&t=7edFp79OOjz6RENz-1)
Refactors Grapher's modals by introducing typography utility classes that map to the Grapher Library defined in [Figma](https://www.figma.com/file/NUWQ31ikHIc3BQnIJw53NK/%5BGrapher%5D-Library?node-id=5%3A197&mode=dev).
This PR...
- gets rid of the `em` unit in modals (i.e. modals are now independent of Grapher's `baseFontSize`)
- adds a scss file called `typography.scss` that defines a set of utility classes for typography (similar to how it's done for the site)
- refactors Grapher's modal such that the scrollbar is on the very right (used to be padded)
- …
> 🔨 (grapher) refactor modals

- packages/@ourworldindata/components/src/Checkbox.scss
- packages/@ourworldindata/core-table/src/CoreTableColumns.ts
- packages/@ourworldindata/grapher/src/controls/Dropdown.scss
- packages/@ourworldindata/grapher/src/controls/Dropdown.tsx
- packages/@ourworldindata/grapher/src/controls/MapProjectionMenu.scss
- packages/@ourworldindata/grapher/src/controls/MapProjectionMenu.tsx
- packages/@ourworldindata/grapher/src/core/grapher.scss
- packages/@ourworldindata/grapher/src/core/typography.scss
- packages/@ourworldindata/grapher/src/entitySelector/EntitySelector.scss
- packages/@ourworldindata/grapher/src/entitySelector/EntitySelector.tsx
- packages/@ourworldindata/grapher/src/modal/ModalHeader.scss
- packages/@ourworldindata/grapher/src/modal/ModalHeader.tsx
- packages/@ourworldindata/utils/src/Util.ts
- packages/@ourworldindata/utils/src/index.ts
[Cycle 2024.2: Entity selector](https://github.com/owid/owid-grapher/issues/3349) | [Designs](https://www.figma.com/file/X5mOEX8zULS6qyHocUYdmh/Grapher-UI?type=design&node-id=2523%3A6266&mode=design&t=7edFp79OOjz6RENz-1)
Adds a dropdown menu to sort by name or indicator, as well as a button to toggle the sort order. Draws a simple bar chart when sorted by an indicator.
- Indicators considered for sorting are all indicators of the chart that can be formatted numerically (includes `NumberOrStringColumn`) and that are not projections
- Names are sorted asc by default, while numerical values are sorted desc by default
- If sorted by an indicator, then values without data are listed at the end (and are marked with a "No data" label)
- The (display) name of a column that is used as dropdown …
> 🎉 (entity selector) sort by name or value

- .bundlewatch.config.json
- packages/@ourworldindata/grapher/src/controls/LabeledSwitch.tsx
- packages/@ourworldindata/grapher/src/controls/SettingsMenu.scss
- packages/@ourworldindata/grapher/src/core/grapher.scss
- packages/@ourworldindata/grapher/src/entitySelector/EntitySelector.scss
- packages/@ourworldindata/grapher/src/entitySelector/EntitySelector.tsx
[Cycle 2024.2: Entity selector](https://github.com/owid/owid-grapher/issues/3349) | [Designs](https://www.figma.com/file/X5mOEX8zULS6qyHocUYdmh/Grapher-UI?type=design&node-id=2523%3A6266&mode=design&t=7edFp79OOjz6RENz-1)
Detects the user's location and displays it at the top of the list. Also shows a little icon next to the user's country/region with a tooltip rendered on hover.
- The user's location is displayed at the top if it's not currently selected (if it's already selected, then I don't think there is a need to move it to the top)
The SVG tester fails due to the changes in #3373
> 🎉 (entity selector) highlight user location

- packages/@ourworldindata/grapher/src/controls/SettingsMenu.scss
- packages/@ourworldindata/grapher/src/controls/SettingsMenu.tsx
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/core/GrapherConstants.ts
- packages/@ourworldindata/grapher/src/core/OverlayHeader.scss
- packages/@ourworldindata/grapher/src/core/OverlayHeader.tsx
- packages/@ourworldindata/grapher/src/core/grapher.scss
- packages/@ourworldindata/grapher/src/entitySelector/EntitySelector.scss
- packages/@ourworldindata/grapher/src/entitySelector/EntitySelector.tsx
- packages/@ourworldindata/grapher/src/modal/DownloadModal.scss
- packages/@ourworldindata/grapher/src/modal/DownloadModal.tsx
- packages/@ourworldindata/grapher/src/modal/EmbedModal.scss
- packages/@ourworldindata/grapher/src/modal/EmbedModal.tsx
- packages/@ourworldindata/grapher/src/modal/EntitySelectorModal.tsx
- packages/@ourworldindata/grapher/src/modal/Modal.scss
- packages/@ourworldindata/grapher/src/modal/Modal.tsx
- packages/@ourworldindata/grapher/src/modal/SourcesModal.scss
- packages/@ourworldindata/grapher/src/modal/SourcesModal.tsx
- packages/@ourworldindata/grapher/src/sidePanel/SidePanel.scss
- packages/@ourworldindata/grapher/src/sidePanel/SidePanel.tsx
- packages/@ourworldindata/grapher/src/slideInDrawer/SlideInDrawer.scss
- packages/@ourworldindata/grapher/src/slideInDrawer/SlideInDrawer.tsx
- packages/@ourworldindata/grapher/src/slopeCharts/SlopeChart.tsx
[Cycle 2024.2: Entity selector](https://github.com/owid/owid-grapher/issues/3349) | [Designs](https://www.figma.com/file/X5mOEX8zULS6qyHocUYdmh/Grapher-UI?type=design&node-id=2523%3A6266&mode=design&t=7edFp79OOjz6RENz-1)
- Modals used to come with a sticky header with a title and a close button, making the content area scrollable by default.
- This was convenient when our modals were relatively simple but started breaking down first for the Sources modal (where we need a sticky header on smaller screens only) and then for the entity selector (where we have some more sticky content on the top and bottom)
- For the entity selector in particular, making the entity selector work with the current `<Modal />` implementation led to a number of bugs that were difficult to get rid of (1px of text …
> 🔨 (grapher) refactor modals and entity selector

- packages/@ourworldindata/components/src/Checkbox.scss
- packages/@ourworldindata/grapher/src/closeButton/CloseButton.scss
- packages/@ourworldindata/grapher/src/controls/Dropdown.scss
- packages/@ourworldindata/grapher/src/controls/Dropdown.tsx
- packages/@ourworldindata/grapher/src/controls/RadioButton.scss
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/core/OverlayHeader.scss
- packages/@ourworldindata/grapher/src/core/OverlayHeader.tsx
- packages/@ourworldindata/grapher/src/core/typography.scss
- packages/@ourworldindata/grapher/src/dataTable/DataTable.scss
- packages/@ourworldindata/grapher/src/entitySelector/EntitySelector.scss
- packages/@ourworldindata/grapher/src/entitySelector/EntitySelector.tsx
- packages/@ourworldindata/grapher/src/modal/DownloadModal.scss
- packages/@ourworldindata/grapher/src/modal/SourcesDescriptions.scss
- packages/@ourworldindata/grapher/src/modal/SourcesKeyDataTable.scss
- packages/@ourworldindata/grapher/src/modal/SourcesModal.scss
- packages/@ourworldindata/grapher/src/modal/SourcesModal.tsx
- packages/@ourworldindata/grapher/src/slideInDrawer/SlideInDrawer.scss
- packages/@ourworldindata/grapher/src/tabs/Tabs.scss
Small bug fixes and improvements coming out of design review:
(What Marwa said is in quotes)
- The only "fix" that I'm aware of is setting the font size to 16px which looks bad, so I guess we'll have to live with this one...
Not clear how to address:
- We can't really slow down the item that travels to the top because then it would take forever to get there... but I did try to slow down the items around the selected one, so that it's hopefully a bit more obvious that we just moved it to the top
- I tried to make it so that, upon selecting, the previously selected item doesn't get animated and just disappears from the top and reappears in its original position, but that was even weirder than swapping..
----
To do before merging:
- ~Show "World" on top with a [globe …
> ✨ (entity selector) feedback

- packages/@ourworldindata/grapher/src/controls/ActionButtons.tsx
- packages/@ourworldindata/grapher/src/controls/ShareMenu.tsx
- packages/@ourworldindata/utils/src/BrowserUtils.ts
- packages/@ourworldindata/utils/src/index.ts
Resolves #3446.
Demo page: https://mobile-share-api.owid-staging.pages.dev/grapher/child-mortality-rate-ihme
The below video shows the behavior on: iOS -> Android -> macOS.
Also notice how the icon used is different on iOS.
Sadly, this will not work out of the box on staging servers, since the Web Share API is only available on https connections.
https://github.com/owid/owid-grapher/assets/2641501/076812d1-a301-43fb-bbe2-f905df41d5c9
> feat(share): on mobile OSs, show system share sheet immediately

- baker/siteRenderers.tsx
Sends a report to Bugsnag when indicators that are referenced in an explorer do not exist. We bake the explorer in any case, though (some chart views not loading is better than a broken link, in my opinion).
Not really a complete solution for #2937 but a bit better than what we have now :)
> 🐝 (baking) report explorers with missing variable IDs

- baker/algolia/configureAlgolia.ts
- The `proximity` ranking criterion was causing subpar search results, _especially_ when multiple country names are contained in the query.
- I always believed that removing it as a criterion would make many queries much worse, but at first sight, this is not the case.
Certainly improves queries like:
- gdp per capita india china
- share extreme poverty
- co2 per capita
- ghg emissions
Triggered by this [Slack discussion](https://owid.slack.com/archives/C06UA61V85U/p1714762934458109).
> enhance(algolia): demote `proximity` ranking for charts index

- packages/@ourworldindata/grapher/src/modal/EmbedModal.tsx
This explicitly requests the [`web-share`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy/web-share) and [`clipboard-write`](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API#security_considerations:~:text=The%20HTTP%20Permissions%2DPolicy%20permissions) permissions in our default iframe snippet.
If they are not set, two of our most-used Share menu interactions ("Share via OS share sheet" and "Copy URL to clipboard") will not work when in an iframe context.
Or, well, the `clipboard-write` permission is currently only required in Chromium browsers, but that's still a vast majority of users.
---
If these permissions are not granted, we now do a pretty nice feature & permission detection, and will not display the Share menu items which are not …
> enhance(embed): explicitly `allow` share features in iframe snippet

- db/model/Gdoc/archieToEnriched.ts
`posts_gdocs.content->>"$.grapher-url"` was being saved as `<a href="https://ourworldindata.org/grapher/some-slug">https://ourworldindata.org/grapher/some-slug</a>` due to Google's automatic linkifying.
It's not rendered anywhere, and we were extracting it correctly for the`gdocs_posts_links` table, hence us not catching it till now.
So, this PR's of arguable utility, but it feels like it ought to be correct.
> 🐛 correctly parse URLs in gdoc front matter

- db/tests/README.md
- db/tests/basic.test.ts
- db/tests/sql-fixtures.d.ts
- package.json
- yarn.lock
The `sql-fixtures` library has some nice features, but is quite outdated and brings knex@0.20 into our transitive dependencies, which brings with it a lot of crap, outdated dependencies (as indicated by the 1100 line lockfile diff here).
Since we don't really use its features, I think it's okay to get rid of it.
> chore(deps): remove`sql-fixtures` dependency

- packages/@ourworldindata/grapher/src/stackedCharts/MarimekkoChart.tsx
Filtered the label candidates which are a full list of nations using the `items` value provided by the chart code to reduce that set to just valid candidates, before performing label code; therefore, no candidate can get in just because it's in the list, it also has to a value that makes it valid, logic which is performed to create the chart `items` property.
This is a [more detailed description of my working out](https://github.com/owid/owid-grapher/issues/3456#issuecomment-2049376383) if you're interested.
Fixes: #3456
On the way I made something a constant and this seemed like gardening, so I left that in.
~1. I stuck with `for(const candidate ...` in the loop in order to keep your style consistent, but would br curious to know whether `let candidate` once, then re-used by both loops …
> (marimekko) fix 3456 missing labels

- packages/@ourworldindata/grapher/src/slopeCharts/SlopeChart.tsx
Format x-axis labels for slope charts.
> 🐛 (slope) format x-axis labels

- packages/@ourworldindata/grapher/src/facetChart/FacetChart.tsx
Fixes https://github.com/owid/owid-grapher/issues/2594
Hides single-item legends for facetted charts (ok since the entity name is mentioned in the title).
> 🐛 (facet) hide legends with a single bin

- baker/startDeployQueueServer.ts
Fixes #3519.
There were two kinds of calls to `deployIfQueueIsNotEmpty` - one had the knex transaction properly passed to it; the other didn't.
> fix(deploy-queue): pass transaction into deploy queue

- packages/@ourworldindata/components/src/styles/variables.scss
- site/TableOfContents.tsx
- site/css/page.scss
- site/css/sidebar.scss
- site/gdocs/components/topic-page.scss
As stated in my comment I have brought this up once the style is applied. A few images to look at.
Some further requirements to come as issue discussions raised three pages and states they should all function with the same style and behaviour: 
http://localhost:3030/age-structure
http://localhost:3030/charts
http://localhost:3030/entries-by-year
https://github.com/owid/owid-grapher/issues/3234
* ensure article header is still visible on article pages using a new z-index variable
* that z-index is calced from the site-header value
* this ensures the search box overlay still works as it does currently, covering the artcile header
* overlay is on ToC click and tested as click-away in both contexts: with and without an article header
* the "open on load" ToC at larger screen sizes logic is …
> fix 3234 add overlay to menu

- packages/@ourworldindata/grapher/src/stackedCharts/MarimekkoChart.tsx
Hides single-item legends for Marimekko charts (ok since the entity name is mentioned in the title).
> 🐛 (marimekko) do not show lone legend item

- Makefile
`node_modules` is an existing target, that depends on changes to `package.json`,  `yarn.lock` and `yarn.config.cjs` to run `yarn install`.
> Install packages only when relevant files change

- site/gdocs/components/ResearchAndWriting.tsx
The research and writing block had an incorrectly implemented fallback for when linked documents were invalid. 
If there's an error and we're previewing, we show a red warning block. If we're not previewing (i.e. baking), we should return null.
This was noticed because an unpublished gdoc that was being linked to in the [CO₂ topic page](https://ourworldindata.org/co2-and-greenhouse-gas-emissions#research-writing) was showing up as an empty tile.
> 🐛 fix research-and-writing links still rendering on bake even when content is invalid

- db/model/Gdoc/GdocAuthor.ts
- db/model/Gdoc/GdocBase.ts
- db/model/Gdoc/GdocDataInsight.ts
- db/model/Gdoc/GdocFactory.ts
- db/model/Gdoc/GdocHomepage.ts
*alternate solution to #3578, which had to be reverted because [this.content in GdocPost](https://github.com/owid/owid-grapher/blob/3691a52abfa41b34d7853df84df3329d80a9a187/db/model/Gdoc/GdocPost.ts#L34-L36) would  be honored by _.defaults as a property not to override, but would result in the `content` property not respecting `OwidGdocContent` at run time.*
This PR promotes GdocBase instance-level functions (e.g. `_enrichSubclassContent` as class methods.
GdocAuthor (but also GdocPost, GdocHomepage and Gdoc DataInsight) are created from a GdocBase instance (only when inserting a new Gdoc) using `Object.assign(gdocAuthor, gdocBase)`. This call lists all enumerable properties on GdocBase, including instance-level functions such as `_enrichSubclassContent`, and overrides the subclass …
> fix(author): fail on create due to functions as enumerable properties overridden in Object.assign

- packages/@ourworldindata/grapher/src/controls/RadioButton.scss
We were getting a warning from Vite build.
Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0. See:
https://sass-lang.com/d/slash-div
> Fix deprecation warning in SCSS for /

- adminSiteServer/apiRouter.ts
- db/model/Gdoc/rawToEnriched.ts
- packages/@ourworldindata/types/src/gdocTypes/ArchieMlComponents.ts
- packages/@ourworldindata/utils/src/image.ts
Added a route to get an ArchieML output of all work produced by an author from both gdoc articles and wordpress pages.
- Example route: http://staging-site-author-page-alt/admin/api/all-work?author=Esteban%20Ortiz-Ospina 
- Example page: http://staging-site-author-page-alt/admin/gdocs/1pU8nVBchpI_LYZmNOo4Dag9lHvQkzG-r8JD_57_-1rw/preview
To provide a way to manually populate the secondary section of research and writing blocks on author pages with topics rather than articles. This is relevant for a handful of authors who mostly work on topic pages, as well as data managers.
> Author page alternate template (topics-focused)

- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- fixes #3174 
- Stacked area and bar charts as well as line charts show multiple years at once (since time is plotted on the x-axis)
- If the timeline is hidden, the chart thus shows the whole range of data points (all values from start time to end time), but the table only shows data points for the start and end time exclusively
- This PR makes it so that the timeline is always shown on the table tab for stacked bar/area and line charts
- Datasette: [Stacked area/bar and line charts where the timeline is hidden](https://datasette-public.owid.io/owid?sql=select%0D%0A++id,%0D%0A++slug,%0D%0A++type%0D%0Afrom%0D%0A++charts%0D%0Awhere%0D%0A++json_extract(config,+%22$.hideTimeline%22)+is+true%0D%0A++and+(%0D%0A++++type+%3D+'StackedBar'%0D%0A++++or+type+%3D+'StackedArea'%0D%0A++++or+type+%3D+'L …
> 🐛 (grapher) show timeline on table tab if necessary

- packages/@ourworldindata/grapher/src/timeline/TimelineComponent.tsx
- packages/@ourworldindata/grapher/src/timeline/TimelineController.ts
- Fixes an issue where the current start or end point wasn't in sync with the timeline handle
- To reproduce:
- Go to https://ourworldindata.org/grapher/life-expectancy-at-different-ages
- Go to the table tab and move the start timeline handle a bit to the right
- Go back to the chart tab and hover over the timeline's start handle
- Note that the current time displayed in the tooltip isn't the actual time that is used for plotting (see screenshot)
> 🐛 (timeline) show current time point correctly

- packages/@ourworldindata/grapher/src/controls/EntitySelectionToggle.tsx
- packages/@ourworldindata/grapher/src/core/grapher.scss
Fixes a small issue where narrative charts had too much space on the bottom:
> 🐛 (grapher) remove extra space on bottom

- db/model/Gdoc/GdocBase.ts
Joe suggested not requiring `alt` on featured images at all, but not sure if: 
* it's worth the added complexity
* they are always only presentational
Long term, we might switch to auto-generating the description as you suggested before, but that is a much bigger project we didn't scope out, yet.
Fixes #3201
> Make image description optional

- packages/@ourworldindata/grapher/src/facetChart/FacetChart.tsx
- packages/@ourworldindata/grapher/src/facetChart/FacetChartUtils.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedAreaChart.tsx
Makes row and column padding of facet grids tighter. This gives more room to charts, esp. on mobile. Desktop grids are tighter too. I think that's okay but we could fine-tune by doing special sizing for different breakpoints.
Example chart: https://ourworldindata.org/grapher/deaths-caused-by-vaccine-preventable-diseases-over-time
| <img width="381" alt="Screenshot 2024-05-22 at 14 40 47" src="https://github.com/owid/owid-grapher/assets/12461810/d5819435-6b11-4876-922e-429fd0f50801"> | <img width="381" alt="Screenshot 2024-05-22 at 14 44 01" src="https://github.com/owid/owid-grapher/assets/12461810/a362c0a1-2b6b-46fc-82cf-f1902a03caac"> |
> ✨ (facets) reduce grid padding

- packages/@ourworldindata/grapher/src/facetChart/FacetChart.tsx
The external facet legend is the only one that is center-aligned. Left-align for consistency.
> ✨ (grapher) left-align external facet legend

- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/core/grapher.scss
- packages/@ourworldindata/grapher/src/slideInDrawer/SlideInDrawer.tsx
To make the slide-in drawer's animation work, `overflow-x: clip` was added to the grapher component. Since the drawer slides in and out, clipping content is needed to make sure that the entity selector isn't visible outside of the Grapher frame. But `overflow-x: clip` messes with the design in various places 👇🏻 
The "Enter full-screen" label is clipped:
Weird visual effect when in full-screen mode and a modal is open:
The tooltip's border is cut-off:
> 🐛 (grapher) fix cut-off action label

- packages/@ourworldindata/grapher/src/controls/ActionButtons.tsx
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
Resolves #2887 
Hides the full-screen button if you'd end up with a smaller grapher frame in full-screen mode (this is the case for landscape mode on mobile, for example)
> 🐛 (grapher) don't show full-screen button when not useful

- packages/@ourworldindata/components/src/TextWrap/TextWrap.tsx
- packages/@ourworldindata/grapher/src/horizontalColorLegend/HorizontalColorLegends.tsx
- packages/@ourworldindata/grapher/src/verticalColorLegend/VerticalColorLegend.tsx
Two small legend improvements:
- For horizontal legends: Improves hover interaction such that the hover is not lost when moving from one item to the next.
- For vertical legends: The color indicator and the text label are aligned at the top. This makes it easier to read when labels are long and broken into multiple lines.
| <img width="326" alt="Screenshot 2024-05-24 at 11 55 13" src="https://github.com/owid/owid-grapher/assets/12461810/8703a3fb-56ba-4f7f-abf2-71037a1a2daa">  | <img width="326" alt="Screenshot 2024-05-24 at 11 55 01" src="https://github.com/owid/owid-grapher/assets/12461810/22223fdd-e980-4b42-8416-ddf7c0e355a3"> |
> ✨ (legend) small visual & hover improvements

- .gitignore
- packages/@ourworldindata/components/src/MarkdownTextWrap/MarkdownTextWrap.tsx
- packages/@ourworldindata/components/src/TextWrap/TextWrap.tsx
- packages/@ourworldindata/grapher/src/axis/AxisViews.tsx
- packages/@ourworldindata/grapher/src/barCharts/DiscreteBarChart.tsx
- packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.tsx
- packages/@ourworldindata/grapher/src/captionedChart/Logos.tsx
- packages/@ourworldindata/grapher/src/footer/Footer.tsx
- packages/@ourworldindata/grapher/src/header/Header.tsx
- packages/@ourworldindata/grapher/src/horizontalColorLegend/HorizontalColorLegends.tsx
- packages/@ourworldindata/grapher/src/lineCharts/LineChart.tsx
- packages/@ourworldindata/grapher/src/lineLegend/LineLegend.tsx
- packages/@ourworldindata/grapher/src/scatterCharts/ComparisonLine.tsx
- packages/@ourworldindata/grapher/src/scatterCharts/ConnectedScatterLegend.tsx
- packages/@ourworldindata/grapher/src/scatterCharts/MultiColorPolyline.tsx
- packages/@ourworldindata/grapher/src/scatterCharts/ScatterPoints.tsx
- packages/@ourworldindata/grapher/src/scatterCharts/ScatterPointsWithLabels.tsx
- packages/@ourworldindata/grapher/src/scatterCharts/ScatterSizeLegend.tsx
- packages/@ourworldindata/grapher/src/slopeCharts/SlopeChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/MarimekkoChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedAreaChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedBarChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedDiscreteBarChart.tsx
- packages/@ourworldindata/grapher/src/verticalColorLegend/VerticalColorLegend.tsx
- packages/@ourworldindata/utils/src/Util.ts
- packages/@ourworldindata/utils/src/index.ts
Resolves #3607 
Adds labels to SVG groups and elements for more intuitive manual inspection and manipulation.
Figma displays an element's ID as its title. I researched if there is a way to customize this and show something else as an element's title, e.g. a `data-name` attribute or so, but I couldn't find anything. Since it's a bit odd to assign IDs to elements like that, I added a `makeIdForHumanConsumption` function that communicates that these IDs are for human inspection only and are not used in code, thus can be safely deleted.
I also made an effort to groups elements together, e.g. a tick's line and label is rendered into one group element.
PS: I also fixed this annoyance 👇🏻 
<details><summary>Figma screenshot</summary>
</details>
> ✨ (grapher) improve SVG output for manual manipulation

- .eslintrc.cjs
- adminSiteClient/GrapherConfigGridEditorTypesAndUtils.tsx
- adminSiteClient/SuggestedChartRevisionApproverPage.tsx
- packages/@ourworldindata/grapher/src/controls/ShareMenu.tsx
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- settings/clientSettings.ts
- settings/serverSettings.ts
Adds a `no-constant-binary-expression` lint rule. I sometimes run [Oxlint](https://oxc-project.github.io/docs/guide/usage/linter.html) on our project where this is enabled by default, and I think it makes sense to have it enabled in general.
This PR also fixes a couple of other things that Oxlint complains about, without adding more rules to eslint.
> 🐝 add no-constant-binary-expression eslint rule

- site/DataPageContent.scss
- site/DataPageV2Content.tsx
The data page layout is padded on both sides. I removed the padding in favour of a full-width grid layout (similar to how it's done on topic pages). As a result, the margins on the side are 16px on smaller devices (not 24px), which is more consistent with the designs and also allows me to make mobile charts full-width in a second step :)
| Topic page  | Data page  |
|  <img width="507" alt="Screenshot 2024-05-21 at 14 51 49" src="https://github.com/owid/owid-grapher/assets/12461810/a6a1f320-e67f-4de8-a495-bcb4cadf9e41"> | <img width="507" alt="Screenshot 2024-05-21 at 14 51 30" src="https://github.com/owid/owid-grapher/assets/12461810/787b4459-388a-4b81-b1aa-870bdb8c78b6"> |
> 🔨 (data page) use full-width grid

- site/DataPageContent.scss
- site/GrapherWithFallback.tsx
On smaller devices, use the full width for the main chart on a data page.
> ✨ (data page) use full width for chart on mobile

- packages/@ourworldindata/grapher/src/barCharts/DiscreteBarChart.tsx
- packages/@ourworldindata/grapher/src/barCharts/DiscreteBarChartConstants.ts
- packages/@ourworldindata/grapher/src/stackedCharts/StackedDiscreteBarChart.tsx
Wrap long labels in stacked bar charts. Gives more room to bars, esp. on mobile.
| <img width="326" alt="Screenshot 2024-05-28 at 10 02 30" src="https://github.com/owid/owid-grapher/assets/12461810/ab102a91-a219-461f-b650-e661359eac3a">  | <img width="326" alt="Screenshot 2024-05-28 at 10 02 42" src="https://github.com/owid/owid-grapher/assets/12461810/cb379ce5-9b7b-4ab5-b180-efa7d179ce8b"> |
> ✨ (stacked bar) wrap long labels / TAS-504

- packages/@ourworldindata/grapher/src/lineCharts/LineChart.tsx
- packages/@ourworldindata/grapher/src/scatterCharts/ComparisonLine.tsx
- packages/@ourworldindata/grapher/src/scatterCharts/ScatterPlotChart.tsx
Small improvements for scatter plots on smaller screens:
- Smaller gap between axis and axis label
- Smaller font size of comparison line label
- Smaller in-place label font sizes
- Smaller dots
Doesn't make a big difference to be honest but looks a bit more proportional at least.
| <img width="326" alt="Screenshot 2024-05-27 at 18 32 58" src="https://github.com/owid/owid-grapher/assets/12461810/6459f986-29d1-441a-8c30-9f8419b719b7">  | <img width="326" alt="Screenshot 2024-05-27 at 18 32 47" src="https://github.com/owid/owid-grapher/assets/12461810/b24cc616-8557-412a-9ba0-ab466a933d78"> |
> ✨ (scatter) space savings on mobile

- packages/@ourworldindata/grapher/src/slopeCharts/SlopeChart.tsx
If a slope chart has a selection by default, then don't dismiss the default selection when the user clicks anywhere in the grapher frame. Only allow dismissing the current selection after the user has interacted with the chart.
Example: https://ourworldindata.org/change-in-female-height-slope
> 🐛 (slope) only enable dismiss by click after interaction / TAS-508

- site/GrapherImage.tsx
- site/multiembedder/MultiEmbedder.tsx
A temporary fix for a flawed change we made to grapher behaviour on mobile, to be followed-up by https://github.com/owid/owid-grapher/issues/3661
> 🐛 don't fallback to static export views of charts by default on mobile

- packages/@ourworldindata/grapher/src/axis/AxisViews.tsx
Center-align axis labels (looks nicer on mobile where axis labels are often wrapped into multiple lines)
> ✨ (axis) center-align axis labels / TAS-512

- packages/@ourworldindata/grapher/src/chart/ChartManager.ts
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/scatterCharts/NoDataSection.tsx
- packages/@ourworldindata/grapher/src/scatterCharts/ScatterPlotChart.tsx
- packages/@ourworldindata/grapher/src/scatterCharts/ScatterPointsWithLabels.tsx
- packages/@ourworldindata/grapher/src/slopeCharts/SlopeChart.tsx
Fixes https://github.com/owid/owid-grapher/issues/3506
> 🐛 (scatter) feedback for selected entities without data / TAS-510

- site/gdocs/components/KeyIndicatorCollection.tsx
I dropped the ball on the accordion's accessibility, so here I am making amends 😇
This PR makes the `key-indicator-collection` component more accessible to keyboard and screen reader users.
In particular,
- Hidden content (i.e. closed accordion items) is removed from the tab sequence and the accessibility tree (uses the [inert attribute](https://web.dev/articles/inert) to do so)
- Fixes a bug where "clicking" on an accordion item by tabbing to it and then pressing Enter made the focus jump back to the first focusable element on the screen (the OWID logo in the header)
> 🐛 make key indicator collection more accessible

- site/gdocs/components/centered-article.scss
Different browsers render (slightly) differently but I think it's passable
Firefox:
Chrome:
Safari:
> 🎉 add commas between sibling ref superscripts

- site/gdocs/pages/Author.scss
see [slack](https://owid.slack.com/archives/C5BDCB2R3/p1717144683552119)
> fix(socials): harmonize logos widths

- ops/buildkite/deploy-content-preview
- update `yarn deployContentPreview` docs
- revert to using preview deploys on the `owid` (production) app (see [slack](https://owid.slack.com/archives/CQQUA2C2U/p1716985481093269))
- add failsafe in case script in run on the `master` branch by mistake
> docs(fn): update deploy-content-preview

- site/gdocs/utils.tsx
the `innerText` separating these two footnote spans wasn't interrupting the sibling selector that I added in https://github.com/owid/owid-grapher/pull/3670
This PR puts all `span-simple-text` spans inside actual span elements to interrupt the CSS sibling selector.
I've checked Chrome, Firefox, and Safari, as well as Grapher and Grapher exports because they also use this renderer in the dod footnotes.
> 🐛 fix ref commas appearing in gdoc articles when paragraph text is between them

- packages/@ourworldindata/grapher/src/header/Header.tsx
Reduces the title-logo padding on smaller screens.
Examples:
- http://staging-site-mobile-title/grapher/deaths-by-age-group-stacked
- http://staging-site-mobile-title/grapher/deaths-from-natural-disasters-by-type
> ✨ (grapher) make title wider on smaller screens / TAS-517

- packages/@ourworldindata/grapher/src/header/Header.tsx
- packages/@ourworldindata/grapher/src/header/HeaderManager.ts
Use the full width for the subtitle on smaller screens. This saves space on mobile if the title is short and the subtitle is long.
Alternatively, we could make it so that the subtitle wraps under the OWID logo. I'm sure there is a way to do it, but it would be more complex than the current solution, and I think the current solution is good enough.
Example chart: https://ourworldindata.org/grapher/fishing-pressure-by-taxa
| <img width="319" alt="Screenshot 2024-05-23 at 10 15 50" src="https://github.com/owid/owid-grapher/assets/12461810/3d776ffa-e5b0-4a7d-a202-fc34ad12d559"> | <img width="319" alt="Screenshot 2024-05-23 at 10 15 55" src="https://github.com/owid/owid-grapher/assets/12461810/f14495e0-3896-4f11-8cc8-d3ea83dafda1"> |
> ✨ (grapher) use full width for the subtitle

- packages/@ourworldindata/grapher/src/modal/SourcesDescriptions.tsx
- site/DataPageV2Content.tsx
As discussed in [this thread](https://owid.slack.com/archives/C03NV9Z3YSV/p1717585232801289), the current message "How does the producer of this data describe this data?" is a bit redundant. This PR rephrases it, to make it less repetitive.
> Improve message 'How does the producer...'

- packages/@ourworldindata/components/src/SimpleMarkdownText.tsx
I looked into moving markdown rendering to the server, but dropped it because it would increase the scope too much.
Fixes #2992
> Fix SimpleMarkdownText with SSR

- site/gdocs/pages/Author.tsx
Adds an extra column's width to the featured image column on our medium breakpoint to prevent the social media links from wrapping
I saw the comment about keeping the two headers in sync but I'm pretty sure it doesn't apply in this case?
https://github.com/owid/owid-grapher/assets/11844404/73dc839b-09d1-4cd7-a8bd-2a75bad883e5
> ✨ widen author featured image column at medium breakpoint

- packages/@ourworldindata/grapher/src/barCharts/DiscreteBarChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedDiscreteBarChart.tsx
fixes https://github.com/owid/owid-grapher/issues/3691
> 🐛 (grapher) prevent infinite loop

- packages/@ourworldindata/grapher/src/stackedCharts/MarimekkoChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/MarimekkoChartConstants.ts
- packages/@ourworldindata/utils/src/index.ts
- packages/@ourworldindata/utils/src/regions.ts
Improves #3683 
Uses a country's short name for Marimekko labels if the entity name is long. For now, we only have a single short name, `DR Congo`, but it's a good one.
We could also use the regions.json `variantNames`, but these are meant to be used as search aliases, so I don't think we should use them as label variants. But I hope that we add more short names in the future :)
> ✨ (marimekko) use country short names as labels / TAS-523

- packages/@ourworldindata/grapher/src/barCharts/DiscreteBarChart.tsx
- packages/@ourworldindata/grapher/src/chart/ChartManager.ts
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/facetChart/FacetChart.test.ts
- packages/@ourworldindata/grapher/src/facetChart/FacetChart.tsx
- packages/@ourworldindata/grapher/src/lineCharts/LineChart.test.ts
- packages/@ourworldindata/grapher/src/lineCharts/LineChart.tsx
- packages/@ourworldindata/grapher/src/mapCharts/MapTooltip.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/AbstractStackedChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedAreaChart.test.ts
- packages/@ourworldindata/grapher/src/stackedCharts/StackedAreaChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedBarChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedDiscreteBarChart.test.ts
- packages/@ourworldindata/grapher/src/stackedCharts/StackedDiscreteBarChart.tsx
Hide single-item legends for stacked bar charts. This is space-saving for mobile especially.
For stacked area charts with a "Change entity" button, the currently selected entity is shown in the title.
|https://ourworldindata.org/grapher/ace-north-atlantic-hurricanes|http://staging-site-stacked-bar-hide-legend/grapher/ace-north-atlantic-hurricanes|
| <img width="379" alt="Screenshot 2024-05-21 at 16 37 08" src="https://github.com/owid/owid-grapher/assets/12461810/2a77d007-b5f5-4bf6-a6b3-84b84fadcf0f">  | <img width="379" alt="Screenshot 2024-05-21 at 16 36 57" src="https://github.com/owid/owid-grapher/assets/12461810/05cad141-88d3-429a-9d0f-6c9cf9cb1d73"> |
|https://ourworldindata.org/grapher/tsunami-deaths|http://staging-site-stacked-bar-hide-legen …
> ✨ (stacked bar) hide single-item legends

- packages/@ourworldindata/components/src/TextWrap/TextWrap.tsx
- packages/@ourworldindata/components/src/TextWrap/TextWrapUtils.test.ts
- packages/@ourworldindata/components/src/TextWrap/TextWrapUtils.ts
- packages/@ourworldindata/grapher/src/slopeCharts/SlopeChart.tsx
Adds the ability to break after hyphens (`-`) to `TextWrap`. This is then used for slope labels to reduce the space we need for the labels on both sides.
I considered making this the default but decided against it because many labels looked worse / less balanced with additional line breaks after hyphens.
Some charts come back with a difference, but they're visually the same. The new code trims whitespace from each side:
```
Svg was different for 2649. The difference starts at character 15152.
Reference: 5" y="465.895">home) </tspan></text></g>
Current  : 5" y="465.895">home)</tspan></text></g><
```
```
Svg was different for 3552. The difference starts at character 11307.
Reference: "4.995000000000001"> Lower respiratory i
Current  : "4.995000000000001">Lower respiratory in
```
```
Svg was …
```
> ✨ (grapher) allow line breaks after hyphens / TAS-524

- packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.tsx
- packages/@ourworldindata/grapher/src/controls/ContentSwitchers.scss
- packages/@ourworldindata/grapher/src/controls/ContentSwitchers.tsx
- packages/@ourworldindata/grapher/src/controls/LabeledSwitch.scss
- packages/@ourworldindata/grapher/src/controls/MapProjectionMenu.scss
- packages/@ourworldindata/grapher/src/controls/MapProjectionMenu.tsx
- packages/@ourworldindata/grapher/src/controls/SettingsMenu.tsx
- packages/@ourworldindata/grapher/src/controls/controlsRow/ControlsRow.tsx
- packages/@ourworldindata/grapher/src/controls/settings/TableFilterToggle.tsx
Keeps controls from overflowing on smaller screens. See screenshots 👇🏻 
The "Show selection only" toggle on the table tab is moved into the settings drawer. The rest are just CSS touchups.
We compute the widths of the content switchers and the toggle to determine if there is enough space for the table toggle. I could have implemented this in a simpler way using breakpoints, but I wanted to make sure that we only hide the table toggle if absolutely necessary.
| <img width="319" alt="Screenshot 2024-05-23 at 18 36 23" src="https://github.com/owid/owid-grapher/assets/12461810/7b4904bb-726b-4a4d-afe4-164b3d3bce81">  | <img width="319" alt="Screenshot 2024-05-23 at 18 36 02" src="https://github.com/owid/owid-grapher/assets/12461810/a9a94e2e-a154-4538-87 …
> ✨ (grapher) prevent controls from overflowing

- site/gdocs/components/HomepageIntro.tsx
- site/gdocs/components/Image.tsx
Fixes #3698
All `HomepageIntro` thumbnails were using images with `containerType: "thumbnail"` which sets the source `sizes` attribute to 350px, which was inaccurate for the primary tile.
This PR fixes that by setting the containerType for the primary tile to be `span6`, which will correctly calculate the width of the image and load a sufficiently hi-res image for any given screen width/DPI
https://github.com/owid/owid-grapher/assets/11844404/6af81c2a-8225-4b02-90b0-9f38dc122994
> 🐛 increase the resolution of homepage intro primary thumbnails

- packages/@ourworldindata/grapher/src/lineCharts/LineChart.tsx
- packages/@ourworldindata/grapher/src/lineLegend/LineLegend.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedAreaChart.tsx
Increases the height of the line legend to both sides. The line legend used to be as tall as the y-axis. Now the line legend uses the full extent of the chart. On smaller screens, a larger height can give us an additional label, see below 👇🏻 
| <img width="317" alt="334457762-5f2cf38c-1419-47af-a4b8-085e39c718e6" src="https://github.com/owid/owid-grapher/assets/12461810/e9d1a047-992f-4865-be2c-10f4b69db8c4">  | <img width="317" alt="Screenshot 2024-05-28 at 16 15 55" src="https://github.com/owid/owid-grapher/assets/12461810/51f06dbb-8724-40e4-9386-b9aa93c7db09"> |
> ✨ (line labels) increase height of the line legend / TAS-507

- packages/@ourworldindata/grapher/src/core/EntityUrlBuilder.test.ts
- packages/@ourworldindata/grapher/src/core/EntityUrlBuilder.ts
> fix: only update legacy entity-dimension pair if entity contains non-numeric character

- packages/@ourworldindata/grapher/src/tooltip/TooltipContents.tsx
Fixes an issue where the tooltip doesn't show a variable's display name because it contains a new line character at the end (which throws off the regex)
Chart: https://ourworldindata.org/grapher/people-living-in-democracies-autocracies-simplified-lexical?stackMode=relative
> 🐛 (tooltip) fix missing display names

- site/SiteNavigation.tsx
On Monday, we'll launch a new topic page on Neglected Tropical Diseases, and recently, we launched another topic page on Wildfires. Both need to be added to our menu. 
@ikesau We shouldn't merge before Monday, but can you please confirm this is the right way to do this?
(cc @paarriagadap @pabloarosado @veronikasamborska1994 @spoonerf @lucasrodes — we should remember to do this now!)
> 🎉 Add NTDs & Wildfires topic pages to the menu

- adminSiteServer/apiRouter.ts
- baker/SiteBaker.tsx
- baker/redirects.ts
- db/migration/1718295383278-AddRedirectsTtl.ts
- db/model/Redirect.ts
- packages/@ourworldindata/types/src/dbTypes/Redirects.ts
When we delete a post it no longer gets baked and is thus not present in the next CF Pages deployment. However, assets can stay in the CF Pages cache for up to a week and we want them to be inaccessible right away, e.g. for job postings.
I verified that this works both locally and on staging, including deployment to staging Pages.
Fixes #2896
> Fix deleted assets staying in Cloudflare cache

- db/migration/1718371124648-AddGdocsPostsSlugIndex.ts
Noticed that we don't have an index for that column yet, and it seems super sensible to have one 👀
> db: add index on `posts_gdocs.slug` column

- baker/formatWordpressPost.tsx
- package.json
- site/owid.scss
- yarn.lock
So, I sneakily replaced our remaining three uses of the `[latex]` formatting declarator with [MathML](https://developer.mozilla.org/en-US/docs/Web/MathML) instead (which has universal browser support now, just not super-consistent rendering across browsers - looking at you, Safari):
- https://ourworldindata.org/excess-mortality-covid
- https://ourworldindata.org/history-of-poverty-data-appendix
- https://ourworldindata.org/mortality-risk-covid
This means that we can now get rid of the code for formatting these blocks :)
> chore(wp): get rid of mathjax-based `[latex]` formatting

- adminSiteClient/GdocsDateline.tsx
- adminSiteClient/GdocsPreviewPage.tsx
- baker/GrapherBaker.tsx
- db/db.ts
- db/model/Gdoc/GdocFactory.ts
- settings/clientSettings.ts
We want to schedule publishing of posts into the future, see #3714.
Lots of existing code already takes into account that `publishedAt` might be in the future. Main problem seems to be [Algolia indexing](https://github.com/owid/owid-grapher/blob/5e19bdb2e2b82517b2d19ee9a24ac2eaf06f3494/adminSiteServer/apiRouter.ts#L2407). Could we index posts in the same cron job that will bake them? We don't have to solve it now, since the current need is about data insights, which aren't indexed in search.
> Add time to publishedAt date picker

- site/search/SearchPanel.tsx
- site/search/SearchUtils.tsx
So, earlier today when we were talking about search, I assured Lars that "yes, we can now match all kinds of entities in search queries". I realized shortly thereafter that this wasn't the case.
The problem is that for countries like "Trinidad **_and_** Tobago" or "Saint Vincent **_and the_** Grenadines", Algolia would remove stop words from the highlighted results, and then the matching based on highlighted results wouldn't include them.
I now fixed this by _also_ running the "dumber" `extractRegionNamesFromSearchQuery`, for a first pass of matching country/region names that's purely based on the search query.
Only after that will it run the other matching logic (in order to also catch non-region matches, like `Salmon (farmed)` or also `Africa (UN)`).
This now means that non-country …
> fix(search): fix search highlighting of entities containing stop words

- db/migration/1719334981843-chart-diff-conflicts.ts
- db/migration/1719338980266-AddChartDiffConflictsTable.ts
In our new workflow, we need some way to track chart conflicts* between PROD and staging servers.
Currently, we define a conflict if the `updatedAt` field of a chart is greater in PROD than in STAGING.
If we take a look at the diagram below, we observe that the current method only captures scenario 1.
To capture scenario 2, we need to be smarter. I've been thinking of a logical expression, but I believe there is none. Therefore, the idea now is to track in a table if a conflict was resolved. A conflict will be identified by the chart ID and timestamp of edit in PROD.
*A chart conflict happens when one user edits a chart in PROD and another in STAGING, after branching out. Similar to git-conflict.
Related: https://github.com/owid/owid-grapher/pull/3584
> 🔨 add migration to add chart_diff_conflicts table

- site/SiteNavigation.tsx
The 'Corruption' topic is missing from the “Browse by topic” and “All our topics” on the landing page - [full Slack message here](https://owid.slack.com/archives/C03NV9Z3YSV/p1719504484565099).
> :bug: Adding Corruption to topic lists on homepage

- adminSiteClient/GdocsDateline.tsx
- adminSiteClient/GdocsPreviewPage.tsx
I find the language of timezones difficult to write, but hopefully this very long comment explains what's going on here.
And if not, then this video can speak for itself 😁 
https://github.com/owid/owid-grapher/assets/11844404/dd073b3d-3dc9-4e7e-8d5a-2df93b32f3cf
> ✨ use UTC in the gdocs datepicker

- db/model/Gdoc/GdocHomepage.ts
- packages/@ourworldindata/grapher/src/color/ColorBrewerSchemes.ts
- packages/@ourworldindata/grapher/src/color/ColorSchemes.ts
- packages/@ourworldindata/grapher/src/color/CustomSchemes.ts
- packages/@ourworldindata/grapher/src/controls/globalEntitySelector/GlobalEntitySelector.tsx
- packages/@ourworldindata/grapher/src/core/EntityCodes.ts
- packages/@ourworldindata/grapher/src/mapCharts/MapChart.tsx
- packages/@ourworldindata/grapher/src/mapCharts/WorldRegionsToProjection.ts
- packages/@ourworldindata/utils/src/Util.ts
- packages/@ourworldindata/utils/src/index.ts
- packages/@ourworldindata/utils/src/regions.ts
- site/SiteNavigation.tsx
- site/search/SearchUtils.tsx
I noticed a bunch of module-scope function calls; these get executed every time the corresponding module (and thereby `owid.mjs`) is loaded.
Many of these values are not needed at all, and some are only needed in "rare" cases.
There are probably more such things, I didn't do a full-on search of everything. A _rough_ regex to find those is `^(export )?(const|let) [\w_.]+ = [^(]*\w\(` (although that won't find multiline ones like `entities [newline] .filter(...)`).
I also discovered that the result of some of these, especially the ones in `CustomSchemes`, are never accessed at all.
By marking them with `@__NO_SIDE_EFFECTS__`, Rollup can eliminate (i.e. tree-shake) the call entirely from the bundle.
---
I think there is no way to do "proper" lazy properties, i.e. ones that are not a function …
> chore: initialize some module-scope variables lazily

- packages/@ourworldindata/grapher/src/chart/ChartInterface.ts
- packages/@ourworldindata/grapher/src/chart/ChartManager.ts
- packages/@ourworldindata/grapher/src/facetChart/FacetChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/AbstractStackedChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedBarChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedConstants.ts
- packages/@ourworldindata/grapher/src/stackedCharts/StackedUtils.ts
Automatically colours positive and negative values differently (if a single series is plotted)
Implemented as part of an effort to create a set of climate charts, see draft charts on [this staging site](http://staging-site-stacked-bar/admin/charts)
- Positive and negative values are coloured differently if a single series is currently plotted and that series actually has positive and negative values
- If one faceted chart uses pos/neg colouring, then we switch them all over for consistency
- The colours for positive and negative values are currently hard-coded, I don't want to add config for this; let's see how far we get with hard-coded values first
Example on staging: http://staging-site-stacked-bar-colors/admin/charts/7905/edit
> 🎉 (stacked bar) add neg/pos color encoding / TAS-547

- packages/@ourworldindata/grapher/src/axis/Axis.ts
- packages/@ourworldindata/grapher/src/axis/AxisConfig.ts
- packages/@ourworldindata/grapher/src/facetChart/FacetChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/AbstractStackedChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedAreaChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedBarChart.tsx
- packages/@ourworldindata/types/src/grapherTypes/GrapherTypes.ts
Aligns x-axes of faceted StackedBar charts, resolves #2160
Implemented as part of an effort to create a set of climate charts, see draft charts on [this staging site](http://staging-site-stacked-bar/admin/charts)
- Replaces the StackedBar chart's custom x-axis implementation with `DualAxisComponent`
- This works by passing a list of `domainValues` to the axis – it's then the axis' job (i) to figure out how much space is available for a single domain value (called the `bandWidth`) and (ii) to adjust the scale in such a way that we have sufficient padding on both sides for the outer bars to fit
- We also pass custom x-ticks to the axis, based on the actual x-values in the chart
- The `domainValues` and the `ticks` are shared across all facets, so that we end up with the same x-axis for all …
> ✨ (stacked bar) align x-axis of facets / TAS-548

- packages/@ourworldindata/grapher/src/axis/Axis.ts
- packages/@ourworldindata/grapher/src/axis/AxisConfig.ts
- packages/@ourworldindata/grapher/src/axis/AxisViews.tsx
- packages/@ourworldindata/grapher/src/facetChart/FacetChart.tsx
- packages/@ourworldindata/grapher/src/facetChart/FacetChartUtils.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedBarChart.tsx
- packages/@ourworldindata/types/src/domainTypes/Layout.ts
- packages/@ourworldindata/types/src/grapherTypes/GrapherTypes.ts
- packages/@ourworldindata/utils/src/Bounds.test.ts
- packages/@ourworldindata/utils/src/Bounds.ts
- packages/@ourworldindata/utils/src/Util.ts
Shares the x-axis across faceted StackedBar charts
Implemented as part of an effort to create a set of climate charts, see draft charts on [this staging site](http://staging-site-stacked-bar/admin/charts)
- Hiding axis labels of inner facets declutters the chart if there are many facets
- For charts with many facets, the x-axes are relatively close to each other, so it's easy to parse, even if there is only one axis on the bottom
- For charts with few facets, the x-axes are relatively far from each other. If then some axis labels are missing, it can be difficult to figure out the x-axis value of a bar
- I ended up with a threshold of 12 facets (partly because we want this for the climate charts that we're working on and they have 12 facets) 
- We might want to enable this for line charts …
> 🎉 (stacked bar) share x-axis across facets / TAS-549

- db/migration/1720038601815-RemoveEntitiesDisplayName.ts
Fixes #3169 
By dropping the column, any data is lost and won't be retrieved by the `down` side of the migration. If the column was truly never used then fair enough, but users find ways of doing usefuly stuff with what they find so I wanted to check that before merging
I have checked this table locally and it's not got anything in it, **and now it's gone**
Bit of a "gotcha" having to run `yarn runDbMigrations` - I'm sure you all know, but it doesn't hurt to remind
> garden: remove unneeded DB column

- Makefile
- baker/algolia/deleteAlgoliaIndex.tsx
Command for deleting all Algolia indexes (implements https://github.com/owid/owid-grapher/issues/3563). Ops part https://github.com/owid/ops/pull/201.
> :hammer: add command for deleting Algolia index

- adminSiteServer/mockSiteRouter.tsx
- baker/siteRenderers.tsx
- site/gdocs/components/AtomArticleBlocks.tsx
This also increases the number of DIs in the feed to 20, which is pretty standard AFAICT.
Fixes #3759
> Add content to data insights atom feed

- baker/algolia/indexChartsToAlgolia.ts
- baker/countryProfiles.tsx
- baker/siteRenderers.tsx
- db/migration/1720173993285-RenameIsIndexableColumn.ts
- db/model/Chart.ts
- db/tests/basic.test.ts
- packages/@ourworldindata/types/src/dbTypes/Charts.ts
Rename `charts.is_indexable` to `isIndexable` in the database (https://github.com/owid/etl/pull/2938 does the same in the ETL)
Should the ETL-PR of this PR be merged first?
> 🐝 (db) rename charts.is_indexable -> isIndexable

- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/core/GrapherConstants.ts
- packages/@ourworldindata/grapher/src/entitySelector/EntitySelector.tsx
This PR changes how we recognize our population indicators in Grapher. This identification is mainly done so that we can hide population in the short citation note that is visible in grapher when it is only used to size bubbles in scatter plots or similar.
> ✨ switch population variable identification from variable id to version agnostic ETL path

- adminSiteServer/app.test.tsx
- adminSiteServer/appClass.tsx
When we changed a React component in dev, the HMR kicked in for the client code, but then the page would fail to load and we had to refresh it manually. Adding the Vite middleware fixes it.
> Fix HMR with SSR in dev

- site/gdocs/components/KeyIndicatorCollection.tsx
#3527 attempted to fix a bug where - after opening an accordion item using the keyboard - the focus unexpectedly jumped to the top of the page. This was fixed by programmatically focusing the content area after opening an accordion. Unfortunately, this breaks the scroll-into-view animation. To avoid interrupting the scroll-into-view animation, we wait a few hundred ms to focus the content area. But we don't really know how much time the animation needs, so the timeout time is set through experimentation. If you're extremely quick to continue navigating, you'll still jump to the top page and then back. This only happens in Safari though – I can't repro the original bug in Chrome or Firefox. 
Not really happy with this fix, but can't think of another way...
> 🐛 (key indicator) fix broken animation / TAS-535

- packages/@ourworldindata/grapher/src/core/GrapherConstants.ts
I recently changed the ETL path of the historical OMM.
This has affected the indicator-detection by regex. As a consequence, scatterplots using population historical are showing the complete population source, as reported by Pablo [here](https://owid.slack.com/archives/C46U9LXRR/p1721899309662919).
Work on this was previously done in https://github.com/owid/owid-grapher/pull/3794/ and discussed in [slack](ttps://owid.slack.com/archives/CQQUA2C2U/p1721825347861559?thread_ts=1721123937.512529&cid=CQQUA2C2U)
(Asked for two revisions, but just aiming at one revision (first one). Thanks!)
> correct population historical path

- baker/algolia/indexChartsToAlgolia.ts
- db/db.ts
Part of https://github.com/owid/owid-grapher/issues/3781
Adds a new function that finds all ancestors of a given tag and includes them in a chart's record when we index to Algolia.
**Examples**
- A chart record that used to have a `tag` value of `["Cardiovascular Diseases"]` will now have `["Cardiovascular Diseases", "Health"]` 
- A chart record that used to have a `tag` value of `["Indoor Air Pollution", "CO2 & Greenhouse Gas Emissions"]` will now have `["Indoor Air Pollution", "CO2 & Greenhouse Gas Emissions", "Air Pollution", "Health", "Energy and Environment"]`
[Example output of `getParentTagsByChildName`](https://github.com/user-attachments/files/16199640/tagGraphByChildren.json)
> Include charts' parent tags in the algolia index

- site/gdocs/components/OwidGdocHeader.tsx
> ✨ increase width of topic page title on mobile

- baker/SiteBaker.tsx
- db/model/Gdoc/GdocBase.ts
- db/model/Gdoc/GdocDataInsight.ts
- db/model/Gdoc/GdocFactory.ts
- db/model/Gdoc/GdocHomepage.ts
- packages/@ourworldindata/types/src/gdocTypes/Gdoc.ts
- packages/@ourworldindata/types/src/index.ts
- site/gdocs/OwidGdoc.tsx
- site/gdocs/components/LatestDataInsights.tsx
- site/gdocs/pages/DataInsight.tsx
We could optimize the feed more, but I'm not sure if it's worth it. I haven't touched that part with the new features, i.e. after this fix, the feed page size is back to where it was before the new DI redesign.
> Optimize latest data insights data

- packages/@ourworldindata/components/src/MarkdownTextWrap/MarkdownTextWrap.tsx
- packages/@ourworldindata/components/src/SimpleMarkdownText.tsx
- packages/@ourworldindata/components/src/styles/mixins.scss
- packages/@ourworldindata/grapher/src/core/grapher.scss
- packages/@ourworldindata/grapher/src/footer/Footer.scss
- packages/@ourworldindata/grapher/src/modal/SourcesKeyDataTable.scss
- packages/@ourworldindata/grapher/src/modal/SourcesModal.scss
- site/KeyDataTable.scss
- site/detailsOnDemand.scss
- site/gdocs/utils.tsx
They don't link to anything and should not be rendered as links in HTML for cases like an Atom feed. See [Slack discussion](https://owid.slack.com/archives/CQQUA2C2U/p1721898655529639).
> Change DoDs to be spans instead of links

- adminSiteServer/mockSiteRouter.tsx
- site/gdocs/components/LinkedAuthor.tsx
https://github.com/user-attachments/assets/c3df8307-a5b8-4168-96d9-ef4c55c6081f
> ✨ article byline `/team` page fallback if no author present

- site/gdocs/components/LatestDataInsights.scss
Not all images used for data insights have the same aspect ratio, which I didn't know when I initially implemented it. Now the ratio should be preserved.
Before:
After:
> Maintain latest data insights image ratio

- packages/@ourworldindata/utils/src/image.ts
- site/gdocs/components/Image.tsx
This reverts commit 267045989055623a58977f263e02b864c4ea1b2e.
> Revert "Fix too many files generated for CF pages (#3818)"

- baker/GrapherBaker.tsx
I'm pretty sure this is good to go now, now that there are no more WP-based topic pages.
Would be great if someone can actually confirm this :)
> refactor(bake): remove WP topic page handling from data page baking

- Makefile
Fixes #3840
Modify the `Makefile` to check for an existing tmux session named `grapher` and kill it if it exists, during `make up` or `make up.full`.
> Fix tmux session handling in Makefile

- baker/sitemap.ts
- db/model/Gdoc/GdocAuthor.ts
- db/model/Gdoc/GdocBase.ts
- packages/@ourworldindata/types/src/gdocTypes/Gdoc.ts
Fixes #3775
Include author pages in the sitemap.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/owid/owid-grapher/issues/3775?shareId=40cd30c1-26cd-4d29-982d-5d54377d693e).
> Add author pages to sitemap

- adminSiteServer/apiRouter.ts
Ensures we don't create redirects or trigger rebuilds for drafts, and that we never create redirects if the gdoc's full slug is `/`
> 🐛 fix redirects from draft gdoc deletion

- packages/@ourworldindata/grapher/src/core/Grapher.tsx
Fixes https://github.com/owid/owid-grapher/issues/2674
> 🔨 more specific check for `Grapher.useAdminAPI`

- packages/@ourworldindata/components/src/Checkbox.scss
- packages/@ourworldindata/components/src/LabeledSwitch/LabeledSwitch.scss
- packages/@ourworldindata/components/src/RadioButton.scss
- packages/@ourworldindata/components/src/closeButton/CloseButton.scss
- packages/@ourworldindata/components/src/styles/colors.scss
- packages/@ourworldindata/components/src/styles/mixins.scss
- packages/@ourworldindata/grapher/src/controls/ActionButtons.scss
- packages/@ourworldindata/grapher/src/controls/ContentSwitchers.scss
- packages/@ourworldindata/grapher/src/controls/Controls.scss
- packages/@ourworldindata/grapher/src/controls/Dropdown.scss
- packages/@ourworldindata/grapher/src/controls/SettingsMenu.scss
- packages/@ourworldindata/grapher/src/controls/ShareMenu.scss
- packages/@ourworldindata/grapher/src/core/grapher.scss
- packages/@ourworldindata/grapher/src/dataTable/DataTable.scss
- packages/@ourworldindata/grapher/src/entitySelector/EntitySelector.scss
- packages/@ourworldindata/grapher/src/mapCharts/MapTooltip.scss
- packages/@ourworldindata/grapher/src/modal/DownloadModal.scss
- packages/@ourworldindata/grapher/src/modal/SourcesModal.scss
- packages/@ourworldindata/grapher/src/tabs/ExpandableTabs.scss
- packages/@ourworldindata/grapher/src/timeline/TimelineComponent.scss
- packages/@ourworldindata/grapher/src/tooltip/Tooltip.scss
- site/GrapherImage.scss
- site/css/content.scss
- site/gdocs/components/LatestDataInsights.scss
- site/gdocs/components/centered-article.scss
- site/owid.scss
Soo, when I just went to add more gray background colors, I noticed that we've been using the wrong `gray-10` color all this time (marwa-raging) 🤯 
It's a slight difference, but it's a difference.
> enhance: add more background gray colors

- adminSiteClient/ChartIndexPage.tsx
Fixes #3803
Persist search queries in the admin across browser navigation.
* Update `onSearchInput` method to update the URL parameters with the search input state.
* Update `componentDidMount` method to initialize the search input state from the URL parameters.
> Persist search query in URL parameters

- adminSiteClient/TestIndexPage.tsx
- adminSiteServer/testPageRouter.tsx
This will mostly be helpful for #3637, I think, so will merge it right away.
> feat(admin): add test page for color schemes

- .gitpod.yml
- docker-compose.dbtests.yml
- docker-compose.devcontainer.yml
- docker-compose.grapher.yml
- docs/local-database-setup.md
The MySQL 9 client, which came out last week, [removes the deprecated `mysql_native_password` auth mode](https://dev.mysql.com/doc/refman/9.0/en/mysql-nutshell.html#mysql-nutshell-removals).
This means that you can't log into the server if the server uses that mode as its auth mode, which for us was the case.
Or, more specifically, the `Waiting for MySQL to come up...` check will never succeed.
This PR makes it so we are using the default auth mode (`caching_sha2_password`).
The actual change will only take place once the database is rebuilt, or you manually run an `ALTER USER` command.
I tested it out, and existing databases will remain in full working order even if these command line args are not present - they'll just continue using `mysql_native_password` as the auth mode.
To …
> chore(mysql): change mysql auth mode to new default (`caching_sha2_password`)

- site/gdocs/components/KeyIndicatorCollection.tsx
Fixes #3863 by omitting the explicit `height: 0px` during server-side rendering.
This makes it so the first section of the collection is open by default, without a height animation.
> fix: don't animate initially-open key indicator height

- adminSiteClient/EditorFeatures.tsx
- packages/@ourworldindata/core-table/src/OwidTable.ts
- packages/@ourworldindata/grapher/src/stackedCharts/StackedDiscreteBarChart.test.ts
- packages/@ourworldindata/grapher/src/stackedCharts/StackedDiscreteBarChart.tsx
[Slack discussion](https://owid.slack.com/archives/C04LNF8LBA8/p1722269332128619?thread_ts=1722256968.554819&cid=C04LNF8LBA8)
Currently having it as `auto` (default) will hide missing data.
I'll check with the SVG tester if that seems like a good default.
<table>
<tr><th>With `MissingDataStrategy.auto` <th> With `MissingDataStrategy.hide`
<tr>
<td> 
<td>
</table>
> feat: implement `MissingDataStrategy` for `StackedDiscreteBar` chart

- devTools/svgTester/update-configs.sh
Adds a helper script to update configs & data of the SVG tester for convenience.
> 🐝 (svg tester) add helper script to update SVGs

- baker/GrapherBaker.tsx
- baker/GrapherImageBaker.tsx
- packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.tsx
Fixes #3881.
I also renamed that method, so that it now actually says what it does.
> fix: use correct, absolute URL for grapher exports

- packages/@ourworldindata/utils/src/image.ts
- packages/@ourworldindata/utils/src/index.ts
- site/gdocs/components/AtomArticleBlocks.tsx
Currently we're linking to the source image which is sometimes 10000px wide 😬
> ✨ use resized images in the data insights atom feed

- packages/@ourworldindata/grapher/src/barCharts/DiscreteBarChart.tsx
I stumbled over this chart that had inconsistent spacing across facets:
| <img width="1077" alt="Screenshot 2024-08-20 at 15 04 35" src="https://github.com/user-attachments/assets/d1ec8075-7da2-4359-80f7-212372c7b6ee">| <img width="1077" alt="Screenshot 2024-08-20 at 15 04 15" src="https://github.com/user-attachments/assets/2e9c4ab4-e5f1-46f1-bdb7-ce8ab2271ae6"> |
> ✨ (discrete bar) fix inconsistent spacing

- packages/@ourworldindata/core-table/src/CoreTableColumns.ts
- packages/@ourworldindata/grapher/src/dataTable/DataTable.tsx
Two minor improvements to Grapher's data table:
In cases where the unit was an empty string, the data table showed an unnecessary separator:
Now that we have better type information I think it makes sense to hide the change columns if we're dealing with non-numerical data:
> 🐛 (data table) small improvements

- site/blocks/RelatedCharts.tsx
- site/blocks/related-charts.scss
The navigation buttons in the related charts block jump to the top while the new chart is loading:
https://github.com/user-attachments/assets/b609bdac-516b-4449-9022-831a353adf7a
> ✨ (related charts) prevent layout shifts when navigating

- packages/@ourworldindata/grapher/src/core/LegacyToOwidTable.ts
Fixes [this issue brought up on Slack](https://owid.slack.com/archives/C0193RW5E2J/p1724158333414259).
Don't quite know why it works, but it does?
<table>
<tr><th>Before <th>After
<tr>
<td>
<td>
> fix: propagate display.color as var display color

- packages/@ourworldindata/core-table/src/CoreTableColumns.ts
- packages/@ourworldindata/core-table/src/CoreTableUtils.test.ts
- packages/@ourworldindata/core-table/src/CoreTableUtils.ts
- packages/@ourworldindata/core-table/src/OwidTable.ts
- packages/@ourworldindata/grapher/src/core/LegacyToOwidTable.ts
These are some easy changes that don't change Table method behaviour in any way, but for some of our most complex charts (read: covid scatters) these can shave off close to a second of processing time.
> perf: simple Grapher & CoreTable perf improvements

- packages/@ourworldindata/components/src/styles/mixins.scss
- packages/@ourworldindata/grapher/src/core/grapher.scss
- site/detailsOnDemand.scss
DoDs in Grapher got their styling from the site, which isn't present in the admin. Move the styles to a mixin that is used both on the site and in Grapher.
> Fix details on demand container styling in admin

- packages/@ourworldindata/grapher/src/stackedCharts/MarimekkoChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedDiscreteBarChart.tsx
I noticed that some of the tooltip footers didn't have a proper explanation text for tolerance.
| <img width="1078" alt="Screenshot 2024-09-02 at 13 08 44" src="https://github.com/user-attachments/assets/3ffb40b1-7224-4f08-80c9-8816ce8910de">  | <img width="1078" alt="Screenshot 2024-09-02 at 13 09 18" src="https://github.com/user-attachments/assets/5af390bd-c1f2-4ed7-aba0-77a66a5f1abd"> |
> 🐛 (tooltip): add explanation test for tolerance notice

- adminSiteServer/apiRouter.ts
- adminSiteServer/testPageRouter.tsx
- baker/GrapherBaker.tsx
- baker/GrapherBakingUtils.ts
- baker/GrapherImageBaker.tsx
- baker/SiteBaker.tsx
- baker/algolia/indexChartsToAlgolia.ts
- baker/countryProfiles.tsx
- baker/redirects.ts
- baker/siteRenderers.tsx
- baker/sitemap.ts
- baker/updateChartEntities.ts
- db/db.ts
- db/migration/1719842654592-AddChartConfigsTable.ts
- db/model/Chart.ts
- db/model/Gdoc/GdocPost.ts
- db/model/Post.ts
- db/tests/basic.test.ts
- package.json
- packages/@ourworldindata/types/src/dbTypes/ChartConfigs.ts
- packages/@ourworldindata/types/src/dbTypes/ChartRevisions.ts
- packages/@ourworldindata/types/src/dbTypes/Charts.ts
- packages/@ourworldindata/types/src/index.ts
- yarn.lock
Adds a `chart_configs` table to the database, adds a `configId` column to the `charts` table that points to a `chart_configs` row, and removes the `config` column.
Shouldn't result in any functionality change.
- All configs are copied from the `charts` table to the `chart_configs` table (for now, `patch config = full config` since inheritance hasn't been implemented yet)
- Configs have a UUID, but it's not yet used (the id of the chart is still the sequential primary key of the charts table) 
Site:
Admin:
Mojmir opened a PR for changes to the ETL: https://github.com/owid/etl/pull/2957
> 🔨 (db) add chart_configs table / TAS-563

- packages/@ourworldindata/grapher/src/core/Grapher.tsx
I feel like this is a good enhancement, and there's basically no downside to it.
These measurements will show up in a Performance recording, like so:
In Chrome 128+, it will also show details in the "Summary" tab, which are especially useful if a page loads multiple graphers.
These measurements can also be accessed using `performance.getEntriesByType("measure")`.
> enhance(grapher): record PerformanceMeasurements

- packages/@ourworldindata/grapher/src/tooltip/Tooltip.scss
* Fixes: https://github.com/owid/owid-grapher/issues/2714 long line length - note that I think these will still wrap as the only change is the date nowrap addition.
* This will be why I opted for `vw` unit to minimise the long line outcome.
* The same line fixes the problem Lucas was having in https://github.com/owid/owid-grapher/issues/3817: wrapping dates.
[OUT OF DATE]
> 2714 & 3817: Fix tooltip layout with long lines

- db/migration/1725540224795-CleanUpChartConfigStackMode.ts
- devTools/schemaProcessor/columns.json
In #3793, I removed `null` as an option from the Grapher schema. I thought I checked that we didn't have any nulls in the database, but apparently, I was wrong (see [the validation error in Slack](https://owid.slack.com/archives/C5JJW19PS/p1725531937760169)). This PR writes a migration to remove nulls from the database. I'm only doing this for chart configs since none of our indicator charts has the `stackMode` set to null.
I don't think null values currently have a way to get into the database. But if it happens, the validator will warn us again, and we can act then.
> 🐛 (grapher) delete stackMode=null from chart configs

- site/gdocs/components/AtomArticleBlocks.tsx
Today, a data insight was published using JPEGs instead of PNGs which exposed a buggy assumption we were making when rendering the data insight atom feed.
This PR fixes that assumption by making sure we only assume the extension is a PNG when we're rendering a resized version of the image. (See this [resize code for context](https://github.com/owid/owid-grapher/blob/20f9ea4b6522b6c74f605180d51023617e7174ea/baker/GDriveImagesBaker.tsx#L109))
In a followup PR we should make sure authors only use PNGs for data insights because JPEGs aren't the best format for data viz graphics, and converting them to PNG in the resize process adds artifacts
From [this image](https://ourworldindata.org/images/published/di-annual-reported-passenger-kilometers-mobile2_1350.png)
> 🐛 fix PNG assumption in AtomArticleBlocks

- adminSiteClient/gdocsValidation.ts
A follow-up to https://github.com/owid/owid-grapher/pull/3932 to ensure authors don't mistakenly upload images in the wrong file format.
Made non-PNGs a warning because there's still a plausible case where JPEG is better for a custom graphic... maybe 🙊
> 🎉 add admin image validation for data insights

- functions/_common/grapherRenderer.ts
- functions/grapher/[slug].ts
Cloudflare has support for redirects but only up to a limited number (I think 2000?). We have a lot of chart redirects in the chart_redirects table (about 1600 or so). Because everything under the /grapher/ route on our website has to run through a CF function anyways (to update the thumbnail image to include the correct query string), we decided to bake these redirects into a json file and do custom redirects handling in the CF function. 
We did this for html pages already but not for thumbnails, but now that we also have `.config.json` requests to worry about and would like to have consistent redirects handling that doesn't overly complicate the logic of our handlers.
This PR makes it so that both requests for the html pages at `/grapher/[slug]` and requests for …
> ✨ Adds consistent redirects handling for cf workers.

- functions/_common/grapherRenderer.ts
- functions/grapher/[slug].ts
- functions/grapher/by-uuid/[uuid].ts
This PR adds fetching of grapher configs from R2 via a CF function by using grapher config UUIDs instead of slugs. Because we have UUIDs for all chart configs (e.g. the ones defined in the ETL grapher config layer) we can get them for charts other than standalone charts that are published (which are the only ones that have valid, unique urls)
> ✨ add fetching grapher configs by UUID

- .env.example-full
- functions/_common/grapherRenderer.ts
- functions/_common/reusableHandlers.ts
- functions/grapher/[slug].ts
- functions/grapher/by-uuid/[uuid].ts
- functions/grapher/thumbnail/[slug].ts
- settings/clientSettings.ts
- site/search/SearchPanel.tsx
This PR duplicates the thumbnail rendering logic into the top level so that we can render pngs at `/grapher/SLUG.png` and svgs at `/grapher/SLUG.svg`. It also adds thumbnail rendering at `/grapher/by-uuid/UUID.png` and `.svg`. 
The HTML rewriting (of og images) is changed to point to the new `/grapher/SLUG.png` route. 
The old thumbnail rendering at `/grapher/thumbnail/SLUG` is kept for now so that existing fetches will still work until the various cached versions of the HTML have expired.
> ✨ Render thumbnails for graphers by uuid

- adminSiteServer/mockSiteRouter.tsx
- settings/clientSettings.ts
- site/multiembedder/MultiEmbedder.tsx
This PR switches the multi-embedder from using the chart config in the HTML file to the explicit grapher API. 
The current (draft) version just uses the same url as the request came in on but that means that for local dev you need to have baked pages to use port :8788. It's probably nicer to have an explicit "grapher api url" setting that defaults to the same as the main page for prod but can be set differently for local dev or staging
> ✨ Use grapher config from API instead of from HTML in multiembedder

- baker/algolia/indexExplorerViewsToAlgolia.ts
We've been indexing explorer views with no titles, which is resulting in crashes on prod where we try to call a string method on the null value.
https://github.com/owid/owid-grapher/blob/1644711a245882ab45559a04c6c03ffda573fac7/site/search/SearchPanel.tsx#L343
This PR adds logging to Bugsnag in the indexing script, and omits such records from the index until we can fix their data.
> 🔨 add bugsnag logging to explorer-views indexing script

- baker/MultiDimBaker.tsx
- db/model/Variable.ts
- packages/@ourworldindata/types/src/siteTypes/MultiDimDataPage.ts
- site/multiDim/MultiDimDataPageContent.tsx
This is currently quite painful to test -- sorry!
During the bake, a `variableIdToGrapherConfigMap` is written into the HTML.
It maps primary variable IDs to their respective `grapherConfigIdAdmin ?? grapherConfigIdETL ?? null`.
If such a UUID is present, then the config is fetched at runtime.
It is currently a bit hard to make grapher wait for this grapher config to arrive - it displays an empty screen during the loading, rather than a loading indicator of some sort.
We can tweak this later on, but we don't want grapher to render _before_ the config override has been fetched, otherwise we're flash-rendering twice with different FAUST.
> mdd: fetch variable-level config by uuid

- explorer/Explorer.tsx
A naive potential fix for https://github.com/owid/owid-grapher/issues/3943
I don't understand the Explorer data model well enough to know why `explorerProgram.grapherConfig` has the `yVariableIds`that it does - but it seems this line of code that inserts extra variables into the grapher config to get it to load the indicator data and metadata was assuming there'd be no duplicates.
There's almost certainly a better upstream fix for this, but this can fix the issue in the meantime until someone who understands explorers better can work things out.
> 🐛 fix duplicate indicators in indicator-based explorers

- packages/@ourworldindata/grapher/src/footer/Footer.tsx
- site/LongFormPage.tsx
- site/gdocs/pages/GdocPost.tsx
We've decided to change the URL's capitalization in our chart footers from `OurWorldInData.org` to `OurWorldinData.org` to make them easier to read.
> Change URLs from OurWorldInData to OurWorldinData in chart footers

- functions/grapher/[slug].ts
This reverts commit be9c4e31d1be2b44e1326eec94605d28adf4b16e.
Fixes #3958
After bisecting, we found that the commit reverted here broke redirects between Grapher charts, although site redirects were intact.
> Fix broken grapher redirects by reverting change

- adminSiteClient/ChartEditor.ts
Fixes #3954
When saving a chart as a new copy, delete the `slug`.
> :bug: Fix chart copy slug issue

- baker/algolia/indexExplorerViewsToAlgolia.ts
Fixes https://owid.slack.com/archives/C5JJW19PS/p1726254980391989
A query tried to access `charts.config` in the indexing step. I haven't tested this locally (I didn't know how), but the CI built the search index successfully in the baking step. There is another error about missing grapher IDs for one explorer that I think is unrelated.
> 🐛 fix query pointing to charts.config / TAS-614

- baker/siteRenderers.tsx
- explorer/Explorer.tsx
Fixes #3943
In #3793, we added a `dimensions` field to all existing ETL-authored indicator configs, but explorers don't expect partial grapher configs to come with dimensions.
Explorers specify their own dimensions, which led to the indicator of the partial grapher config being added twice. What made this worse is that the `dimensions` array of the partial grapher config got mutated every time a different view was selected, which led to dimensions being added multiple times to the same Grapher.
> 🐛 (explorer) remove duplicate columns / TAS-613

- packages/@ourworldindata/grapher/src/core/Grapher.tsx
Fixes #3931 
The global entity selector manages the selection of a chart from outside by passing in its own `selection` object, which should take precedence over the config's `selectedEntityNames`.  
In #3793, Grapher's `updateFromObject` method was updated to also change the current selection if `selectedEntityNames` is given. That's sensible (and is needed in the admin), but `updateFromObject` is also called in the constructor. If `selectedEntityNames` and `selection` both are given then `selectedEntityNames` always won, which broke the global entity selector (since it relies on `selection` being respected).
I think it's sensible to apply the passed-in selection only if it's non-empty, but this leads to funny behaviour of the global entity selector if the selection happens to be empty …
> 🐛 fix global entity selector

- functions/_common/env.ts
- functions/_common/grapherRenderer.ts
- functions/grapher/[slug].ts
- functions/grapher/by-uuid/[uuid].ts
This is an alternative fix for the one reverted in 24f6288.
> Fix grapher 404 page

- site/search/Autocomplete.tsx
Anywhere the `<Autocomplete>` component is mounted, you can press `/` to focus it.
`/` is also used by GitHub and YouTube. Unlike YouTube, Mousetrap ensures this also works on a German keyboard.
Mousetrap takes care that this _doesn't_ happen when some textfield is currently focused.
This will save me _seconds_!
> enhance(search): add global `/` shortcut to focus search bar

- gitCms/GitCmsConstants.ts
Load `GIT_CMS_DEFAULT_BRANCH` from env if available. This will be useful for explorers on staging servers.
> :sparkles: Enable explorers on staging servers

- packages/@ourworldindata/grapher/src/slideInDrawer/SlideInDrawer.scss
I noticed that the entity selector is outside of the Grapher frame. It shouldn't be. There is an obvious fix, but I don't understand what changed or why the code as-is ever worked.
> 🐛 slide-in drawer should open within the Grapher frame

- packages/@ourworldindata/grapher/src/axis/AxisViews.tsx
- packages/@ourworldindata/grapher/src/barCharts/DiscreteBarChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedDiscreteBarChart.tsx
The vertical zero line in the discrete bar and stacked discrete bar charts overlap with the bars, thereby obscuring the data.
Example: http://staging-site-discrete-bar-zero-line/grapher/number-electoral-democracies-age
> 🐛 (discrete bar) zero line obscured part of the data bars

- adminSiteClient/EditorCustomizeTab.tsx
- adminSiteClient/EditorTextTab.tsx
- adminSiteClient/Forms.tsx
- adminSiteClient/admin.scss
- db/migration/1726819761333-AddExplicitAutoValuesToChartConfigs.ts
- devTools/schemaProcessor/columns.json
- packages/@ourworldindata/grapher/src/axis/AxisConfig.test.ts
- packages/@ourworldindata/grapher/src/axis/AxisConfig.ts
- packages/@ourworldindata/grapher/src/core/Grapher.jsdom.test.ts
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/schema/defaultGrapherConfig.ts
- packages/@ourworldindata/grapher/src/schema/grapher-schema.005.yaml
- packages/@ourworldindata/types/src/grapherTypes/GrapherTypes.ts
- packages/@ourworldindata/types/src/index.ts
Grapher sometimes assigns meaning to config values being `undefined`. For example, if `timelineMaxTime` is undefined, Grapher uses the latest year in the data. This is problematic in an inheritance model since `undefined` can't be used to overwrite values. As a result, it's currently not possible to overwrite custom parent values with the automatic-default option for the following properties:
- `timelineMinTime` and `timelineMaxTime`
- `yAxis.min`, `yAxis.max`, `xAxis.min`, `xAxis.max`
- `baseColorScheme`
- `yAxis.label` and `xAxis.label`
- `map.columnSlug`
Instead of relying on `undefined` to have a value derived from the data, this PR adds a new value, like `"auto"` or `"latest"`, to make the behaviour explicit.
This is done for:
- `timelineMinTime` and `timelineMaxTime` (`"earliest"` …
> ✨ (admin) allow to overwrite parent values with automatic defaults / TAS-624

- db/model/Gdoc/GdocFactory.ts
- db/model/Post.ts
20 gdocs in the DB had `updatedAt` as the start of the UNIX epoch, i.e. `new Date(null)`.
Any other ideas what might have caused it?
> Fix potential source of gdoc.publishedAt being incorrect

- packages/@ourworldindata/grapher/src/core/Grapher.tsx
Resolves #3965
Show facets when multiple entities are selected in single-entity mode.
> ✨ (grapher) show facets when multiple entities are selected in single-entity mode

- explorer/GrapherGrammar.ts
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/scatterCharts/ScatterPlotChart.stories.tsx
- packages/@ourworldindata/grapher/src/scatterCharts/ScatterPlotChart.tsx
- packages/@ourworldindata/grapher/src/scatterCharts/ScatterPlotChartConstants.ts
Scatter plots respect a `backgroundSeriesLimit` that limits the number of background series plotted. It's not used by any of our charts and only comes up once for an [unpublished test explorer](https://github.com/search?q=repo:owid/owid-content%20backgroundSeriesLimit&type=code).
The SVG tester differences are spurious.
> 🧹(grapher) remove backgroundSeriesLimit from scatters

- db/refreshPageviewsFromDatasette.ts
Without the _stream=on param the rows were truncated at 4000 entries.
> Fix truncated rows in refreshPageviewsFromDatasette

- packages/@ourworldindata/grapher/src/core/Grapher.tsx
The StackedBar's entity selector should say "Add/remove entities", not "Select entities".
> 🐛 (stacked bar) say 'add' entities instead of 'select'

- functions/_common/grapherRenderer.ts
- functions/_common/readmeTools.ts
- functions/package.json
- yarn.lock
Enhancements on top of #3613, see the commit messages for details.
The biggest change is replacing `jszip` with [`littlezipper`](https://www.npmjs.com/package/littlezipper), which (mostly) uses the browser-inbuilt (and Workers-inbuilt!) `CompressionStream` API for zip generation, which gives us fast, native compression.
It's also a good option if we ever should want to create a zip file directly in the browser - it uses `CompressionStream` if available ( = most modern browsers), or otherwise creates an uncompressed zip file as a fallback.
> Marcel's enhancements to server-side csv generation

- packages/@ourworldindata/grapher/src/axis/AxisViews.tsx
- packages/@ourworldindata/grapher/src/core/grapher.scss
- packages/@ourworldindata/grapher/src/lineCharts/LineChart.tsx
- packages/@ourworldindata/grapher/src/lineCharts/LineChartConstants.ts
- packages/@ourworldindata/grapher/src/lineLegend/LineLegend.tsx
- packages/@ourworldindata/utils/src/Util.ts
Makes line charts a bit nicer to work with in Figma. In particular:
- Simplifies/flattens the hierarchy
- Removes groups and elements that are unnecessary for a static export
- Groups elements by type more often
I find grouping elements by type a bit un-elegant in code tbh. But if it helps our authors edit charts in Figma, it's a small price to pay, I guess :)
| <img width="333" alt="Screenshot 2024-10-07 at 13 52 38" src="https://github.com/user-attachments/assets/ed85d96b-c00d-4e06-bbd5-d20f60998c1c">  | <img width="333" alt="Screenshot 2024-10-07 at 13 52 52" src="https://github.com/user-attachments/assets/27684c02-c67a-40fe-92e5-525ef337c20b"> |
> ✨ (line chart) improve static version for Figma / TAS-628

- adminSiteServer/authentication.tsx
- functions/_common/reusableHandlers.ts
- functions/grapher/[slug].ts
- functions/grapher/by-uuid/[uuid].ts
- functions/grapher/thumbnail/[slug].ts
- public/_headers
A small follow-up to our call.
* `no-cache` is equivalent to `max-age=0, must-revalidate` and recommended being used instead, see
https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching#force_revalidation
* Authenticated responses should use private cache only
> Update cache control

- packages/@ourworldindata/types/src/siteTypes/MultiDimDataPage.ts
- site/multiDim/MultiDimDataPageContent.tsx
Another place where we show the metadata is in the sources modal, triggered by clicking on "Learn more about this data" when embedded. This should only scroll to the metadata section on the mdim page, except we currently set `isEmbeddedInAnOwidPage: true`, so it opens the modal even there.
We display a list of indicators and their sources there, even for the "all" view of the poverty mdim, which contains all the indicators. I think it means we don't have a place to show the global override for metadata there, but we should still override the per indicator metadata. Is that correct?
> Add overrides for indicator metadata

- baker/SiteBaker.tsx
- serverUtils/errorLog.ts
Bugsnag is currently grouping _all_ errors occurring during baking as of https://github.com/owid/owid-grapher/pull/4005 being merged.
https://app.bugsnag.com/our-world-in-data/grapher-admin/errors/66d0c35a0ab81c7871ff95d5?filters[event.since]=30d&filters[error.status]=ignored
This PR allows us to set a custom `groupingHash` which overrides Bugsnag's default grouping heuristic. I've set it for gdocs baking on the specific error message so that all instances of e.g. `Author "Our World in Data team" does not exist or is not published` get grouped and can be ignored permanently, but `Author "Mxa Rsero" does not exist or is not published` would still get logged.
> 🐛 disaggregate site-baker bugsnag errors

- explorer/Explorer.tsx
- packages/@ourworldindata/components/src/IndicatorKeyData/IndicatorKeyData.tsx
- packages/@ourworldindata/components/src/IndicatorProcessing/IndicatorProcessing.tsx
- packages/@ourworldindata/components/src/MarkdownTextWrap/MarkdownTextWrap.tsx
- packages/@ourworldindata/grapher/src/controls/ShareMenu.tsx
- packages/@ourworldindata/grapher/src/header/Header.tsx
- site/Feedback.tsx
- site/LongFormPage.tsx
- site/MetadataSection.tsx
- site/SiteFooter.tsx
- site/gdocs/components/ProminentLink.tsx
- site/gdocs/components/ResearchAndWriting.tsx
- site/gdocs/components/Socials.tsx
- site/gdocs/components/TopicPageIntro.tsx
- site/gdocs/pages/GdocPost.tsx
- site/gdocs/pages/Homepage.tsx
- site/gdocs/utils.tsx
We've had an unspoken convention here to omit referrer information from our links in many places throughout the codebase.
Specifically in gdocs pages, it's worked 3 ways:
1. gdoc links (linking to another article via its gdoc URL): **referrer information included**
2. grapher/explorer links (linking via a grapher/explorer url): **referrer information included**
3. url links (when we write out the complete URL): **referrer information omitted**
When linking to an OWID resource that isn't a grapher/explorer/gdoc page, we have to use url links, e.g https://ourworldindata.org/data and so this unspoken convention has hurt our ability to understand how users are navigating our site.
This PR removes the `noreferrer` attribute from url links in gdoc articles (see: the `LinkedA` component, and the …
> ✨ remove `rel="noreferrer"` from site `<a>` tags

- packages/@ourworldindata/grapher/src/core/Grapher.tsx
When everything hasn't loaded yet, `defaultTitle` may contain variable IDs.
I tried changing how `defaultTitle` works to avoid it ever returning a title with variable IDs, which would be possible if we made `titlePublicOrDisplayName` return an empty string instead of variable ID, which we could do if we changed `AbstractCoreColumn.name` to return an empty string instead of a slug (which is the variableId), but that breaks assumptions in other places where `titlePublicOrDisplayName` is used.
> Stop showing variable ID as a grapher title

- adminSiteClient/EditorExportTab.tsx
- packages/@ourworldindata/grapher/src/barCharts/DiscreteBarChart.tsx
- packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.tsx
- packages/@ourworldindata/grapher/src/chart/ChartManager.ts
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/core/GrapherConstants.ts
- packages/@ourworldindata/grapher/src/facetChart/FacetChart.tsx
- packages/@ourworldindata/grapher/src/halo/Halo.tsx
- packages/@ourworldindata/grapher/src/lineCharts/LineChart.tsx
- packages/@ourworldindata/grapher/src/lineCharts/LineChartConstants.ts
- packages/@ourworldindata/grapher/src/modal/DownloadModal.tsx
- packages/@ourworldindata/grapher/src/scatterCharts/ComparisonLine.tsx
- packages/@ourworldindata/grapher/src/scatterCharts/ScatterPlotChart.tsx
- packages/@ourworldindata/grapher/src/scatterCharts/ScatterPlotChartConstants.ts
- packages/@ourworldindata/grapher/src/scatterCharts/ScatterPointsWithLabels.tsx
- packages/@ourworldindata/grapher/src/scatterCharts/ScatterSizeLegend.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedDiscreteBarChart.tsx
Adds a flag to download a static chart optimised for social media / Instagram. The option is accessible from Grapher's download menu and is only available for staff members who are logged in.
This is how the social media export is currently different from the ordinary export:
1. Background is beige (+ line outlines etc are also beige)
2. Background `<rect />` not needed in Figma is removed
3. Dash pattern of grid lines is set to `7 7` (Lucas prefers this)
To be honest, I'm not sure if adding a flag for this special behaviour is worth it. Alternatively, we could allow to customize Grapher's background colour. Maybe that's nicer? We could also do none of these things and that would be fine as well! Curious what you think, @danyx23 
SVG tester changes come from the previous PR
> 🎉 (static charts) add output channel for social media / TAS-639

- packages/@ourworldindata/grapher/src/axis/AxisViews.tsx
- packages/@ourworldindata/grapher/src/barCharts/DiscreteBarChart.tsx
- packages/@ourworldindata/grapher/src/barCharts/DiscreteBarChartConstants.ts
- packages/@ourworldindata/grapher/src/horizontalColorLegend/HorizontalColorLegends.tsx
- packages/@ourworldindata/grapher/src/mapCharts/MapChart.tsx
- packages/@ourworldindata/grapher/src/slopeCharts/SlopeChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/MarimekkoChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedDiscreteBarChart.tsx
- packages/@ourworldindata/grapher/src/verticalColorLegend/VerticalColorLegend.tsx
Makes the static export of a discrete bar chart a bit nicer to work with in Figma:
- Removes unnecessary groups and elements
- Group elements by type (e.g. group all line labels together) 
The changes happen to make animation on iOS smoother ([example](http://staging-site-figma-discrete-bar/grapher/female-population-by-age-group?time=1976))
> ✨ (discrete bar) optimise static version for Figma / TAS-644

- site/DataCatalog/DataCatalog.tsx
Implements https://github.com/owid/owid-grapher/issues/3982
Avoids the issue of having to recreate the google.com behaviour on the homepage search by disabling the dropdown panel until there the user has typed something.
> ✨ add autofocus to homepage search and data catalog

- packages/@ourworldindata/grapher/src/verticalColorLegend/VerticalColorLegend.tsx
Items in the vertical colour legend are sometimes incorrectly positioned. This is a result of an oversight when I refactored the legend. 
I'm not fully back until tomorrow. @marcelgerber, if this looks ok to you, can you merge it in? Also feel free to commit to this branch if you want to change something. 
Example: https://ourworldindata.org/grapher/cardiovascular-death-rate-vs-gdp-per-capita
> 🐛 (legend) fix vertical positioning

- packages/@ourworldindata/utils/src/Util.ts
Figma shows element IDs as labels. We used to make those IDs "CSS safe," which sometimes led to ugly, difficult-to-read IDs. That's why, in a recent PR, I just assigned names as is to element IDs (including CSS unsafe stuff like spaces and %, etc). I didn't notice anything weird at the time, so I thought Figma would be ok with this. Now we're dealing with a weird Figma issue where lines show up but are not coloured. We can't repro the bug, so not sure this fix helps, but it's our best guess atm.
> 🐛 replace spaces in element IDs for Figma

- packages/@ourworldindata/grapher/src/entitySelector/EntitySelector.scss
- packages/@ourworldindata/grapher/src/entitySelector/EntitySelector.tsx
Resolves #3920
Keeps selected and unselected entities both in the list of entities to choose from.
I didn't remove the animation library because the animations make it look a bit smoother when the list of selected entities is in view.
Browsers like Chrome and Firefox are smart enough not to do a layout shift when a new entity is selected while the list of selected entities is not currently in view. But in other browsers like Safari, selecting a new entity always leads to a layout shift. The animation also helps here to make the layout shift a bit less jarring. 
Marcel's point below is addressed :)
> ✨ (entity selector) keep selected entities in options list

- packages/@ourworldindata/grapher/src/chart/ChartManager.ts
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/dataTable/DataTable.tsx
- packages/@ourworldindata/grapher/src/scatterCharts/ScatterPlotChart.tsx
- packages/@ourworldindata/grapher/src/timeline/TimelineComponent.stories.tsx
- packages/@ourworldindata/grapher/src/timeline/TimelineComponent.tsx
- packages/@ourworldindata/grapher/src/timeline/TimelineController.ts
Animates a scatter as a cloud of moving dots and keeps the axes fixed. The axes are fixed for the particular time range that is animated. 
At the animation's beginning and end, the view "jumps" to the new axis domains. The same happens when an animation is paused and the user starts dragging one of the sliders.
The animation in relative mode is unchanged. Getting the right axis domain doesn't seem trivial to me unless I'm missing something, so it's not worth doing at this point IMO.
In a follow-up PR, I'll also look into fixing the size domain.
> ✨ (scatter) don't animate as a time scatter

- packages/@ourworldindata/grapher/src/chart/ChartManager.ts
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/scatterCharts/ScatterPlotChart.tsx
- packages/@ourworldindata/grapher/src/scatterCharts/ScatterPlotChartConstants.ts
- packages/@ourworldindata/grapher/src/timeline/TimelineController.ts
It usually makes more sense to animate a scatter plot as a cloud of moving dots. However, if a chart is a time scatter by default or a user is currently viewing a time-scatter version of the chart, then animating a time scatter is sensible.
Examples:
- http://staging-site-scatter-animation-time/grapher/annual-hours-of-work-and-income-18702016
- http://staging-site-scatter-animation-time/grapher/measles-coverage-vs-cases-worldwide
- http://staging-site-scatter-animation-time/grapher/life-expectancy-vs-gdp-per-capita?time=1903..2021&country=~ITA
> ✨ (scatter) animate time scatters as time scatters

- packages/@ourworldindata/grapher/src/entitySelector/EntitySelector.tsx
Resolves #3669
Automatically closes the entity selector after an entity has been selected (in single entity selection mode).
Automatically closing the entity selector used to interrupt the animation which looked broken. Since we removed the animation, that's no problem anymore.
The entity selector is closed with a short delay (200ms), so that the selected entity is highlighted for a moment before the modal or drawer is closed.
Example: http://staging-site-close-entity-selector/grapher/life-expectancy-at-different-ages
> ✨ (grapher) automatically close entity selector in single selection mode

- packages/@ourworldindata/grapher/src/entitySelector/EntitySelector.tsx
Implements two unrelated changes for the entity selector:
- Hides the "Available entities" section if all entities are currently selected and there are only few entities to select in the first place
- Changes the label of the "Available entities" section to "All countries and regions" (instead of just "Countries and regions")
> ✨ (entity selector) hide available entities when all are selected

- adminSiteServer/appClass.tsx
- adminSiteServer/authentication.tsx
- settings/serverSettings.ts
We log in as admin user on staging servers. This is a bit annoying because for [data managers](https://github.com/owid/etl/issues/2578) because:
- Each time we land on a new staging server, we have to log in with admin (only once per staging server) and then we see a warning about "compromised passwords" on Chrome
- Chart edits on staging server are all made by "ETL" user (this is problematic since a lot of chart edits come from staging servers via chart-sync)
Add middleware that compares user IP to IPs from `tailscale status --json`. If we find a match, we'll look up Tailscale display name (which is actually a **Github name**) and use it to look up that user in MySQL. This assumes that Github names match MySQL full names (which is true for most people, and exceptions can change it).
Once …
> :sparkles: Log in Tailscale users automatically on staging servers

- explorer/Explorer.tsx
- explorer/ExplorerProgram.ts
- explorer/GrapherGrammar.ts
- gridLang/GridLangConstants.ts
Allow explorer configs to pass `auto` to `yAxisMin`.
This hasn't been necessary because the default behaviour used to be `auto`, but we'll soon be switching line charts to use 0 as the default value, and then we'll need a way to overwrite that in explorers.
> ✨ (explorer) allow to pass "auto" as yAxisMin

- adminSiteServer/apiRouter.ts
- adminSiteServer/chartConfigR2Helpers.ts
- adminSiteServer/migrateMultiDimConfigs.ts
- adminSiteServer/multiDim.ts
- baker/MultiDimBaker.tsx
- db/migration/1729600015045-AddMultiDimIdConfigMd5SlugIndex.ts
- db/migration/1729684787090-CreateMultiDimXChartConfigs.ts
- db/model/MultiDimDataPage.ts
- db/model/MultiDimXChartConfigs.ts
- db/model/Variable.ts
- devTools/migrateMultiDimConfigs/migrateMultiDimConfigs.ts
- devTools/syncGraphersToR2/syncGraphersToR2.ts
- packages/@ourworldindata/types/src/dbTypes/ChartConfigs.ts
- packages/@ourworldindata/types/src/dbTypes/MultiDimDataPages.ts
- packages/@ourworldindata/types/src/dbTypes/MultiDimXChartConfigs.ts
- packages/@ourworldindata/types/src/domainTypes/Various.ts
- packages/@ourworldindata/types/src/index.ts
- packages/@ourworldindata/types/src/siteTypes/MultiDimDataPage.ts
- packages/@ourworldindata/utils/package.json
- packages/@ourworldindata/utils/src/MultiDimDataPageConfig.test.ts
- packages/@ourworldindata/utils/src/MultiDimDataPageConfig.ts
- serverUtils/serverUtil.tsx
- site/multiDim/MultiDimDataPageContent.tsx
- yarn.lock
* Add new HTTP API for upserting mdim configs
* Configs are normalized on creation
* Indicator paths are resolved to variable IDs - this was previously done when baking
* We create a full chart config for every view by merging config defined in the view with variable config already stored in the DB
* We add the chart config UUID for each config to the `view` in the multidim config
* For each view, we create a row in the newly added `multi_dim_x_chart_configs` table, to track the relationships between multidim views and chart configs  
* To migrate the existing configs, we have to run the `devTools/migrateMultiDimConfigs/migrateMultiDimConfigs.ts` script with:
```
yarn tsx --tsconfig tsconfig.tsx.json devTools/migrateMultiDimConfigs/migrateMultiDimConfigs.ts
```
The existing config must be …
> Migrate multi dimensional configs to new storage

- packages/@ourworldindata/components/src/CodeSnippet/code-snippet.scss
- packages/@ourworldindata/components/src/ExpandableToggle/ExpandableToggle.tsx
- packages/@ourworldindata/components/src/styles/typography.scss
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/core/typography.scss
- packages/@ourworldindata/grapher/src/modal/DownloadIcons.tsx
- packages/@ourworldindata/grapher/src/modal/DownloadModal.scss
- packages/@ourworldindata/grapher/src/modal/DownloadModal.test.tsx
- packages/@ourworldindata/grapher/src/modal/DownloadModal.tsx
- packages/@ourworldindata/grapher/src/modal/Modal.tsx
- packages/@ourworldindata/grapher/src/tabs/Tabs.scss
Implements #4015.
---
There's quite a large state space, which I want to illustrate here to some degree:
<table>
<tr><th>Description <th>Screenshot <th>Example URL
<tr><td>"Normal" vis tab <td>
<td>
http://staging-site-download-tab-redesign/grapher/life-expectancy
<tr>
<td>"Normal" data tab
<td>
<td>
http://staging-site-download-tab-redesign/grapher/life-expectancy
http://staging-site-download-tab-redesign/grapher/electricity-prod-source-stacked?country=~DEU
<tr>
<td>Short names not available (pre-ETL dataset or csv-based explorer)
<td>
<td>
http://staging-site-download-tab-redesign/grapher/mode-of-reporting-literacy-rates
http://staging-site-download-tab-redesign/explorers/migration-flows
<tr>
<td>Vis download not possible, because on table tab
<td>
<td> …
> Redesigned download modal, with enhanced data download options

- explorer/Explorer.tsx
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/modal/DownloadModal.tsx
When `downloadDataLink` was provided in an explorer, we used to download that file in the download modal rather than the normal, client-generated csv file.
This feature didn't work for some time now already, so let's just get rid of it.
> chore: remove "external csv" functionality

- package.json
- settings/clientSettings.ts
- site/DonateForm.tsx
- site/Feedback.tsx
- site/NewsletterSubscription.tsx
- site/gdocs/components/DataInsightsNewsletter.tsx
- site/owid.entry.ts
- yarn.lock
Collect session replays via Sentry for 1% of cookie-consenting user sessions. Closes owid/analytics#155.
[Implementation notes and privacy considerations](https://www.notion.so/owid/Collect-session-replays-11874b71f92e804bb617ebfe69e8d0f6?pvs=4).
Remaining todos before merging:
> :honeybee: collect session replays via Sentry

- packages/@ourworldindata/grapher/src/horizontalColorLegend/HorizontalColorLegends.tsx
- packages/@ourworldindata/grapher/src/mapCharts/MapChart.tsx
- packages/@ourworldindata/grapher/src/mapCharts/MapChartConstants.ts
Optimise maps for Figma, similar to how that has been done for other chart types.
| <img width="320" alt="Screenshot 2024-10-24 at 16 48 48" src="https://github.com/user-attachments/assets/f7fb3bc7-908d-4b3f-8d13-4d4740265c0b">  | <img width="320" alt="Screenshot 2024-10-24 at 16 49 05" src="https://github.com/user-attachments/assets/a4424249-9ee8-4b4b-896d-a0ad0223bef3"> |
> ✨ (map) optimise static version for Figma

- baker/siteRenderers.tsx
- explorer/Explorer.tsx
- explorer/ExplorerProgram.test.ts
- explorer/ExplorerProgram.ts
- explorer/GrapherGrammar.ts
- gridLang/GridLangConstants.ts
- packages/@ourworldindata/types/src/grapherTypes/GrapherTypes.ts
Explorers incorrectly merge (partial) Grapher configs with explorer-level Grapher settings.
We naively merge configs like this
```js
{
...partialGrapherConfig,
...explorerProgram.grapherConfigOnlyGrapherProps
}
```
where `partialGrapherConfig` is the indicator config (of type `GrapherInterface`), but `explorerProgram.grapherConfigOnlyGrapherProps` is of type `ExplorerGrapherInterface` that includes explorer-flavoured flat config fields, like `yAxisMin`. Overwriting the y-axis min of the partial Grapher config, which is given as `yAxis.min`, thus won't work.
I don't know of an example in the wild where this currently leads to a problem, but you can fabricate a bug locally by following these steps:
Set `yAxis.min` of an indicator that is used in the conflict explorer by running
```sql …
```
> 🐛 (explorer) merge configs correctly

- site/gdocs/pages/DataInsight.tsx
Track "copy link" clicks on data insights. Closes owid/analytics#206
> :hammer: track data insight "copy link" clicks

- adminSiteClient/EditorCustomizeTab.tsx
- db/migration/1729763649580-SetYAxisMinDefaultToZero.ts
- packages/@ourworldindata/grapher/src/axis/AxisConfig.test.ts
- packages/@ourworldindata/grapher/src/axis/AxisConfig.ts
- packages/@ourworldindata/grapher/src/lineCharts/LineChart.tsx
- packages/@ourworldindata/grapher/src/schema/defaultGrapherConfig.ts
- packages/@ourworldindata/grapher/src/schema/grapher-schema.005.yaml
Resolves #3797
Makes 0 the new default minimum value for the y-axis of line charts
- With these changes, the default of `yAxis.min` depends on the chart type (`0` for line charts, `auto` for others). As a result, `yAxis.min` can't be included in the default base layer (since there isn't a single default value that should apply to all configs)
- I removed the default value for both the x-axis and the y-axis because I want to keep using one definition for the axis. I haven't found a way to compose the JSON schema such that I can keep the axis definition in one place and change the default min value of y-axis only
- Since we changed the default grapher config, we have to re-compute the full configs of all charts
- The `auto` value parsed from the config used to be translated to `undefined` …
> ✨ (line chart) set y-axis min default to 0

- packages/@ourworldindata/grapher/src/chart/ChartManager.ts
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/lineCharts/LineChart.tsx
- packages/@ourworldindata/grapher/src/lineCharts/LineChartConstants.ts
- packages/@ourworldindata/grapher/src/mapCharts/MapTooltip.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedAreaChart.tsx
- packages/@ourworldindata/types/src/grapherTypes/GrapherTypes.ts
- packages/@ourworldindata/types/src/index.ts
- site/multiembedder/MultiEmbedder.tsx
Grapher has a prop `annotation` highlighting an entity for a particular year if given. This is currently used by sparklines in map tooltips, but nowhere else. I removed the feature from stacked area charts that also implemented this and renamed `annotation` to `entityYearHighlight` – hopefully, that's a bit more intuitive.
> 🔨 (grapher) remove entity-year highlight from stacked area charts

- functions/grapher/by-uuid/[uuid].ts
Fixes an error when we try to load grapher configs for multi-dim preview in admin in prod, which runs on a different domain (admin.owid.io) than the Cloudflare Pages function (ourworldindata.org).
> Allow fetching grapher configs from all origins

- devTools/docker/my.cnf
I noticed there are 20 GB of logs I never needed to look at on my machine. IMHO, we can enable logging when debugging something as needed instead of having it always on.
> Disable MySQL logging

- packages/@ourworldindata/grapher/src/lineCharts/LineChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedAreaChart.tsx
Fixes #4117.
Also, fixes that currently, a StackedArea tooltip is only visible when hovering over the actual areas.
This regression was introduced in https://github.com/owid/owid-grapher/pull/2610/commits/d830a0133e4f1007d9318c98130bac049cd0b833.
> fix: re-enable extended tooltip hover area

- adminSiteServer/authentication.tsx
- db/migration/1731317168994-AddGithubUsernameToUsers.ts
- Add column `users.githubUsername`
- Match detected Tailscale user on githubUsername rather than fullName
- Add people with GitHub names different from their full names
> :sparkles: add column githubUsername to users table

- packages/@ourworldindata/grapher/src/stackedCharts/MarimekkoChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedBarChart.tsx
- packages/@ourworldindata/types/src/grapherTypes/GrapherTypes.ts
- packages/@ourworldindata/types/src/index.ts
Reverts changes that broke the color scale controls for Marimekko charts in the admin.
> 🐛 (admin) color scale controls are unresponsive

- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- site/multiDim/MultiDimDataPageContent.tsx
Fixes the hack to make the internal edit link in the share menu of grapher work for Mdims (#3987)
> 🔨 fix the mdim edit hack

- packages/@ourworldindata/explorer/src/Explorer.tsx
This PR fixes the bug reported in #4033 where the edit button in the share menu of grapher does not point to the right location for explorers
> 🔨 Fix explorer edit button

- baker/algolia/utils/pages.ts
Fixes the issue reported by Ed:
> 🐛 fix algolia updatedAt bug

- site/search/Search.scss
- site/search/SearchPanel.tsx
Changes:
- Autofocus SearchBox on the search page
- Removes the gray background for the no results screen
- Approximately places the algolia logo in a slightly better spot on the no results screen for most resolutions
> ✨ autofocus SearchBox on search page

- packages/@ourworldindata/grapher/src/modal/SourcesModal.scss
Fixes #4180 by restoring the `span` to the default `display: inline`.
> fix: restore correct ellipsis word wrap for sources modal

- adminSiteClient/AbstractChartEditor.ts
- adminSiteClient/ChartEditor.ts
- adminSiteClient/IndicatorChartEditorPage.tsx
- adminSiteServer/apiRouter.ts
- adminSiteServer/app.test.tsx
- db/migration/1730455806132-RemoveDefaultConfigLayer.ts
- db/model/Chart.ts
- db/model/Variable.ts
- devTools/svgTester/dump-data.ts
- packages/@ourworldindata/explorer/src/ExplorerProgram.ts
- packages/@ourworldindata/grapher/src/core/Grapher.jsdom.test.ts
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/core/GrapherConstants.ts
- packages/@ourworldindata/grapher/src/index.ts
- packages/@ourworldindata/grapher/src/schema/README.md
- packages/@ourworldindata/utils/src/Util.ts
- site/DataPageV2.tsx
- site/ExplorerPage.tsx
- site/GrapherPage.tsx
Removes the default layer from the full config of charts.
This is the smaller version that removes the default layer from the full configs of all charts but keeps using it in the admin. If I find the time this week, I also want to remove the admin's dependence on the default config, but even if I don't find the time, I think this PR is okay to be merged as is since keeping the default config up-to-date is zero effort (we have a GitHub action that infers the default config from the schema and automatically commits it).
I tested this by comparing the previously baked Grapher configs with the now-baked Grapher configs. The diff was empty for most configs. There were a few that used to have `map.colorScale` set to an empty object (not sure why) that is missing now, but that makes no …
> 🔨 remove default layer from chart configs / TAS-675

- Makefile
- db/tests/run-db-tests.sh
- devTools/docker/refresh-grapher-data.sh
- devTools/docker/sync-s3-images.sh
I just noticed that we cannot run make targets (in this case, `make reindex`) on our prod servers - they'll fail with `Access denied for user 'live_grapher'@'[owid-admin-prod.tail6e23.ts.net](http://owid-admin-prod.tail6e23.ts.net/)' (using password: YES)` when accessing the DB.
I'm pretty sure I got some idea now of what is going on:
In prod, we have .env secrets like `GRAPHER_DB_PASS='abc'` - i.e. they are wrapped in single quotes.
When these are loaded in Node (via dotenv), it strips out the quote marks and just reads `abc`. On the other hand, when [this piece of code](https://github.com/owid/owid-grapher/blob/d8ba3a0b521df9091987df22205900c5f0b31f7f/Makefile#L14-L20) reads the same var in the makefile, it reads that same line as `'abc'`, i.e. including the quotation marks (the same …
> fix(make): don't read .env file as env variables

- site/gdocs/components/centered-article.scss
See e.g. the data download post (or the introducing data insights one)
> 💄 when citations are disabled, the license block needs a bit of margin at the top

- packages/@ourworldindata/grapher/src/modal/DownloadModal.tsx
As [requested on Twitter](https://x.com/leecrawfurd/status/1859545295681396972), and I feel like Stata is important enough among "important business people" that it warrants being included in that list.
Pablo A [has tested this snippet](https://owid.slack.com/archives/C022GUFG8AC/p1732188810562839).
Sadly, from some quick research it doesn't seem like there's an easy way to import JSON into Stata, so I'm not sure there's a good way to get metadata into Stata.
> enhance(download): add code example for Stata

- packages/@ourworldindata/grapher/src/color/CustomSchemes.ts
- packages/@ourworldindata/grapher/src/core/GrapherConstants.ts
- packages/@ourworldindata/grapher/src/core/LegacyToOwidTable.ts
- packages/@ourworldindata/grapher/src/scatterCharts/ScatterPlotChart.test.ts
This PR tackles the easy parts of #4176 - it uses the new indicator id instead of the old one for the OWID regions.
This PR also tweaks the colors a bit. The new regions datasets does not map any item to Antarctica so the order changed a bit. I used this opportunity to also change the mapping of continent colors (see [this slack thread](https://owid.slack.com/archives/C5BDCB2R3/p1731934875618319))
> ✨ switch to the new owid regions data and tweak colors for regions

- adminSiteServer/apiRouter.ts
- db/migration/1731589634295-CreateChartViewsTable.ts
- db/model/ChartView.ts
- packages/@ourworldindata/types/src/dbTypes/ChartViews.ts
- packages/@ourworldindata/types/src/index.ts
Part of #4128.
This PR creates the DB table needed for narrative views, and sets up some CRUD methods for these that handle generating patch configs, explicitly persisting some properties of the patch, storing them in the DB and R2, and so on.
> feat: API handlers for narrative views

- site/gdocs/components/ProminentLink.tsx
- site/gdocs/components/centered-article.scss
Per Marwa's request
```
{.prominent-link}
url: https://ourworldindata.org/child-mortality
title: Child Mortality
thumbnail: child-mortality-thumbnail.png
{}
{.prominent-link}
url: https://ourworldindata.org/child-mortality
title: Child Mortality
thumbnail: child-mortality-thumbnail.png
description: Child mortality is one of the world’s largest problems. Around 6 million children under 15 die per year. That’s around 16,000 deaths every day, or 11 every minute.
{}
```
> ✨ center prominent link content when no description is present

- packages/@ourworldindata/grapher/src/core/Grapher.tsx
It's a bit annoying that I can't rely on `window.grapher` referring to the "main" Grapher on the data page if there is a Related Charts section
> 🔨 stop exposing grapher for charts embedded on a data page

- docs/browser-support.md
- vite.config-common.mts
I think it's time :)
This is dropping support for Safari 12 in particular, and beginning our browser support at Safari 13.1.
This makes us support browsers going back to early 2020, roughly 4.5 years.
I've hand-checked the features that Vite enables with this change, and it's mainly:
- No longer transpiling [ES6 template literals](https://caniuse.com/template-literals) but keeping them in their ES6 syntax
- Including the [nullish coalescing operator (`??`)](https://caniuse.com/mdn-javascript_operators_nullish_coalescing) as-is in the output JS and not transpiling it
- In CSS, it's dropping some vendor prefixes, e.g. `-webkit-sticky, -webkit-text-decoration-color`.
I've tested this in Safari 12 and Chrome 78, both of which are properly falling back to our no-JS solution (because of syntax …
> chore: update minimum browser versions we support

- db/migration/1732698153785-RemoveHasChartTabFromFullConfigs.ts
An oversight in https://github.com/owid/owid-grapher/pull/4159
> 🐛 remove hasChartTab and type from full configs

- site/DataCatalog/DataCatalogPage.tsx
- site/DonateForm.tsx
- site/DonatePage.tsx
- site/SiteNavigation.scss
- site/SiteNavigation.tsx
- site/SiteTools.tsx
- site/css/site-tools.scss
> Donation campaign updates

- adminSiteServer/mockSiteRouter.tsx
- baker/SiteBaker.tsx
- baker/siteRenderers.tsx
- baker/sitemap.ts
- site/ExplorerIndexPage.scss
- site/ExplorerIndexPage.tsx
- site/gdocs/components/ExplorerTiles.tsx
- site/owid.scss
A very simple explorer index page that a few of us at OWID have been missing. It also gives the homepage "See all our Data Explorers" link somewhere useful to go to.
We'll possibly update these cards to look the same as the cards on the homepage once Marwa has some time to design the rest of the tag icons that we'd need.
> 🎉 Explorers index page

- packages/@ourworldindata/grapher/src/modal/SourcesModal.tsx
Clicking on a pencil in the sources tab will now take you to variable edit page (if the variable id exists). (Joe's request, check this [slack thread](https://owid.slack.com/archives/C0149NKLZAM/p1732568053164499))
> :sparkles: Take user to variable edit page instead of dataset when clicking on a pencil

- site/owid.entry.ts
Increases Sentry session replay sampling from 1% of cookie-consenting sessions to 10% of cookie-consenting sessions. 
We are now on a "sponsored" Sentry plan (https://sentry.io/for/good/), which increases our budget of session replays to 100k per month (for free).
> 🐝  analytics: increase Sentry session replay sampling to 10%

- packages/@ourworldindata/explorer/src/ExplorerProgram.ts
- packages/@ourworldindata/grapher/src/core/loadVariable.ts
- packages/@ourworldindata/utils/src/Util.ts
- packages/@ourworldindata/utils/src/index.ts
- site/detailsOnDemand.tsx
- site/multiDim/MultiDimDataPageContent.tsx
- site/multiembedder/MultiEmbedder.tsx
- site/search/evaluateSearch.ts
This PR adds automatic retry with exponential back-off to all client side fetches that grapher or our site do. This should make our site a bit more robust on bad connections.
> ✨ add automatic retry to client fetch requests

- packages/@ourworldindata/types/src/domainTypes/Various.ts
- site/ExplorerIndex.tsx
- site/ExplorerIndexPage.scss
- site/ExplorerIndexPage.tsx
- site/runSiteFooterScripts.ts
Annoyingly this took more effort than I thought it would because I had to add it to the hyrdation pipeline.
I could have written a script tag in the footer like this: 
```
<script>
document.querySelectorAll('.explorer-index-page__card img').forEach(img => {
img.onerror = function() {
const errorDiv = document.createElement('div');
errorDiv.innerHTML = '<svg /> <h2 />...';
errorDiv.className = 'explorer-index-page__card-error';
this.parentNode.replaceChild(errorDiv, this);
};
});
</script>
```
but idk, I feel like that's a dangerous path to start going down for the rest of my team's sanity 😅 
I tested this in Chrome and Safari too (because apparently things can go wrong even when you're just rendering rectangles)
> ✨ add fallback for explorer index page thumbnails

- packages/@ourworldindata/core-table/src/OwidTable.ts
- packages/@ourworldindata/grapher/src/modal/DownloadModal.tsx
Filter data downloads in grapher to only the actively used columns. Not doing this was a problem for csv based explorers that can have a huge number of columns.
> ✨ Filter for only active columsn in grapher data download

- site/multiembedder/MultiEmbedder.tsx
Migrates config on the fly if they're outdated in the Multiembedder
Don't have time for MDims, but created an issue: https://github.com/owid/owid-grapher/issues/4239
> 🐛 migrate configs on the fly when fetched from R2

- packages/@ourworldindata/components/src/Button/Button.tsx
- packages/@ourworldindata/components/src/styles/mixins.scss
- packages/@ourworldindata/grapher/src/footer/Footer.tsx
- packages/@ourworldindata/utils/src/Util.ts
- packages/@ourworldindata/utils/src/index.ts
- site/DataCatalog/DataCatalogPage.tsx
- site/Html.tsx
- site/SiteFooter.tsx
- site/blocks/AllChartsListItem.tsx
- site/blocks/ExpandableParagraph.tsx
- site/css/cookie-notice.scss
- site/css/footer.scss
- site/css/forms.scss
- site/gdocs/components/AllCharts.tsx
- site/gdocs/components/ArticleBlock.tsx
- site/gdocs/components/DataInsightsNewsletter.tsx
- site/gdocs/components/KeyInsights.scss
- site/gdocs/components/KeyInsights.tsx
- site/gdocs/components/LatestDataInsights.scss
- site/gdocs/components/LatestDataInsights.tsx
- site/gdocs/components/PillRow.scss
- site/gdocs/components/ResearchAndWriting.tsx
- site/gdocs/components/centered-article.scss
- site/gdocs/components/topic-page.scss
- site/owid.scss
Some QOL things I noticed + Lighthouse recommendations
A few +/-5% lightness adjustments here and there because the background colour isn't white, because that's easier than adding $blue-61
I showed the `*:focus-within` rule to Marwa and she's happy with it 👍
> ✨ Site accessibility improvements

- devTools/svgTester/chart-configurations.ts
- packages/@ourworldindata/grapher/src/core/EntityUrlBuilder.ts
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/core/GrapherUrl.test.ts
- packages/@ourworldindata/grapher/src/core/GrapherUrl.ts
- packages/@ourworldindata/grapher/src/index.ts
- packages/@ourworldindata/types/src/grapherTypes/GrapherTypes.ts
- packages/@ourworldindata/utils/src/Util.ts
- packages/@ourworldindata/utils/src/index.ts
- site/search/SearchUtils.tsx
The way we were handling grapher query params was subpar at best - including that some of the types were not an accurate reflection of the properties that can actually be set, and so on.
https://github.com/owid/owid-grapher/commit/d2da674f1599db3ee1a9016c6ae3df2a74d02006 's commit message explains the changes made to the `GrapherQueryParams` type, for example.
There were also some corners where we had less type-safety than we can have.
`grapherConfigToQueryParams` is not used yet, but I'll need it down the road for narrative views. It takes a (partial) chart config and converts it into the query params fitting to achieve this grapher state.
> refactor(grapher): better handling of query params

- adminSiteClient/ImagesIndexPage.tsx
- adminSiteClient/admin.scss
- adminSiteServer/apiRouter.ts
- adminSiteServer/imagesHelpers.ts
- db/db.ts
Changes:
- Functionality to upload a new version of an image
- Standardizes API route names (they're all `/images` now)
- Refactors API routes to extract common functions
- Refactors image upload button into `PostImageButton` and `PutImageButton` + utils
> 🎉 Cloudflare images image updating

- adminSiteServer/apiRouter.ts
This was an incorrect assumption that is now throwing a few errors in the admin as we clean out some old charts
> 🐛 fix unpublished chart delete

- adminSiteServer/apiRouter.ts
- baker/SiteBaker.tsx
- db/exportMetadata.ts
- db/migration/1733228214376-CreateDonors.ts
- db/model/Donor.ts
- db/model/Gdoc/GdocAbout.ts
- db/model/Gdoc/GdocBase.ts
- db/model/Gdoc/GdocFactory.ts
- db/model/Gdoc/enrichedToMarkdown.ts
- db/model/Gdoc/enrichedToRaw.ts
- db/model/Gdoc/exampleEnrichedBlocks.ts
- db/model/Gdoc/gdocUtils.ts
- db/model/Gdoc/rawToArchie.ts
- db/model/Gdoc/rawToEnriched.ts
- packages/@ourworldindata/types/src/dbTypes/Donors.ts
- packages/@ourworldindata/types/src/gdocTypes/ArchieMlComponents.ts
- packages/@ourworldindata/types/src/gdocTypes/Gdoc.ts
- packages/@ourworldindata/types/src/index.ts
- packages/@ourworldindata/utils/src/Util.ts
- site/gdocs/OwidGdoc.tsx
- site/gdocs/components/ArticleBlock.tsx
- site/gdocs/components/Donors.scss
- site/gdocs/components/Donors.tsx
- site/gdocs/components/People.scss
- site/gdocs/components/People.tsx
- site/gdocs/pages/AboutPage.scss
- site/gdocs/pages/AboutPage.tsx
- site/gdocs/utils.tsx
- site/owid.scss
I also fixed a few unrelated things.
> Add donors component

- adminSiteClient/ImagesIndexPage.tsx
- adminSiteClient/admin.scss
- adminSiteServer/apiRouter.ts
- adminSiteServer/imagesHelpers.ts
- db/migration/1731360326761-CloudflareImages.ts
- db/migration/1732994843041-CloudflareImagesAddUserId.ts
https://github.com/user-attachments/assets/5b081556-8b49-4eac-9d86-a1f141e762d7
Changes:
- New API route, admin UI, and helper function to generate alt text for an image from OpenAI
- Makes alt text nullable in the DB
- Fixes some other issues with the CF images migration
> 🎉 Automatic alt text for cloudflare images

- baker/algolia/utils/pages.ts
- site/search/SearchPanel.tsx
> 🐛 fix default gdoc thumbnails not rendering in gdocs

- packages/@ourworldindata/grapher/src/dataTable/DataTable.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/AbstractStackedChart.tsx
I noticed that, in the admin, several chart types failed when creating a new chart and switching chart types before selecting a y variable: StackedArea and DataTable would just fail, with no way to recover from it.
> fix(admin): fix chart type failures when y dimension is missing

- adminSiteServer/apiRouter.ts
- db/migration/1733151294656-ChartViewsAddQueryParam.ts
- packages/@ourworldindata/grapher/src/index.ts
- packages/@ourworldindata/types/src/dbTypes/ChartViews.ts
This is just persisting them, we're not currently doing anything with this info. That's yet to come.
Part of #4128.
> enhance: persist query params when saving narrative view

- db/migration/1731360326761-CloudflareImages.ts
- db/migration/1732994843041-CloudflareImagesAddUserId.ts
- devTools/cloudflareImagesSync/cloudflareImagesSync.ts
- devTools/cloudflareImagesSync/tsconfig.json
Just the DB changes from https://github.com/owid/owid-grapher/pull/4214 so that we can merge this first, make sure the DB data is correct, and then merge the code changes
> 🎉 cloudflare images DB setup

- adminSiteServer/mockSiteRouter.tsx
- ops/buildkite/deploy-content
- packages/@ourworldindata/types/src/gdocTypes/GdocConstants.ts
- site/search/searchTypes.ts
`rm dist/images/published/*.etag` no longer works as the directory no longer exists, causing builds to fail
> 🐛 remove invalid buildkite step

- db/migration/1733850063207-RemoveColorDimensionFromSlopeCharts.ts
- db/migration/1733850122191-MigrateSlopeCharts.ts
- packages/@ourworldindata/utils/src/grapherConfigUtils.ts
- packages/@ourworldindata/utils/src/index.ts
Slope chart migrations that go hand in hand with the new designs.
Will be shipped earlier so that configs in R2 are already updated once the new code is deployed.
> 🔨 migrate slope chart configs

- packages/@ourworldindata/core-table/src/CoreTableColumns.ts
- packages/@ourworldindata/core-table/src/OwidTable.test.ts
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/entitySelector/EntitySelector.tsx
- packages/@ourworldindata/grapher/src/mapCharts/MapChart.tsx
- packages/@ourworldindata/grapher/src/mapCharts/MapSparkline.tsx
- packages/@ourworldindata/grapher/src/mapCharts/MapTooltip.tsx
- packages/@ourworldindata/grapher/src/slopeCharts/SlopeChart.test.ts
- packages/@ourworldindata/grapher/src/slopeCharts/SlopeChart.tsx
- packages/@ourworldindata/grapher/src/slopeCharts/SlopeChartConstants.ts
- packages/@ourworldindata/grapher/src/stackedCharts/AbstractStackedChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/MarimekkoChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedDiscreteBarChart.tsx
- packages/@ourworldindata/grapher/src/tooltip/TooltipContents.tsx
- packages/@ourworldindata/types/src/domainTypes/CoreTableTypes.ts
Adds tolerance to slope charts.
If the original times of start and end value are too close together, then we don't show the slope. This is something that came out of discussion with Joe and Daniel, but now that I'm working on this, I don't think we need to be that strict? As long as the original start time < the original end time, we should be good? Curious what you think!
Example charts:
- http://staging-site-slope-tolerance-viz/grapher/ratio-of-female-to-male-labor-force-participation-rates-slopes?time=2000..latest&country=AGO~OWID_WRL
- With forced relative mode (doesn't make much sense here, just for testing): http://staging-site-slope-tolerance-viz/grapher/ratio-of-female-to-male-labor-force-participation-rates-slopes?time=2000..latest&country=AGO~OWID_WRL&stackMode=relative
> 🎉 (slope) add tolerance / TAS-719

- .gitignore
- packages/@ourworldindata/components/src/Halo/Halo.tsx
- packages/@ourworldindata/components/src/TextWrap/TextWrap.test.ts
- packages/@ourworldindata/components/src/TextWrap/TextWrap.tsx
- packages/@ourworldindata/components/src/TextWrap/TextWrapGroup.test.ts
- packages/@ourworldindata/components/src/TextWrap/TextWrapGroup.tsx
- packages/@ourworldindata/components/src/index.ts
- packages/@ourworldindata/grapher/src/chart/ChartUtils.tsx
- packages/@ourworldindata/grapher/src/controls/ChartIcons.tsx
- packages/@ourworldindata/grapher/src/controls/ContentSwitchers.scss
- packages/@ourworldindata/grapher/src/core/grapher.scss
- packages/@ourworldindata/grapher/src/halo/Halo.tsx
- packages/@ourworldindata/grapher/src/lineCharts/LineChart.tsx
- packages/@ourworldindata/grapher/src/lineLegend/LineLegend.test.tsx
- packages/@ourworldindata/grapher/src/lineLegend/LineLegend.tsx
- packages/@ourworldindata/grapher/src/noDataModal/NoDataModal.tsx
- packages/@ourworldindata/grapher/src/scatterCharts/ComparisonLine.tsx
- packages/@ourworldindata/grapher/src/scatterCharts/NoDataSection.scss
- packages/@ourworldindata/grapher/src/scatterCharts/NoDataSection.tsx
- packages/@ourworldindata/grapher/src/scatterCharts/ScatterPointsWithLabels.tsx
- packages/@ourworldindata/grapher/src/scatterCharts/ScatterSizeLegend.tsx
- packages/@ourworldindata/grapher/src/slopeCharts/SlopeChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedAreaChart.tsx
- packages/@ourworldindata/grapher/src/tooltip/Tooltip.scss
- packages/@ourworldindata/grapher/src/tooltip/Tooltip.tsx
- packages/@ourworldindata/grapher/src/tooltip/TooltipProps.ts
- Entity names are usually only shown only on the right side
- If it would be otherwise difficult to match a label on the left to the corresponding slope, then the entity name is repeated
- The heuristic here uses the number of levels used by the line legend, the actual threshold (4) is arbitrary of course
- We prefer to add labels on the left if they're also labelled on the right (this is only important if labels are dropped due to space constraints)
- Entity annotations are hidden on smaller screens
- Entity annotations are also shown in the tooltip (line charts show entity annotations in the tooltip as well) 
- Show hidden line legend labels on hover
- Toggling the No Data section is quite disruptive. Once we make changes to the entity selector that account for the No data problem, we …
> ✨ (slope) redesign / TAS-722

- packages/@ourworldindata/grapher/src/chart/ChartManager.ts
- packages/@ourworldindata/grapher/src/controls/SettingsMenu.tsx
- packages/@ourworldindata/grapher/src/facetChart/FacetChart.tsx
- packages/@ourworldindata/grapher/src/lineLegend/LineLegend.tsx
- packages/@ourworldindata/grapher/src/scatterCharts/ScatterPlotChart.tsx
- packages/@ourworldindata/grapher/src/slopeCharts/SlopeChart.tsx
- packages/@ourworldindata/utils/src/Util.ts
Adds facetting support for slope charts.
If there are many facets it could be nice to declutter them, but I don't have time for that now.
> 🎉 (slope) support facetting / TAS-734

- adminSiteServer/imagesHelpers.ts
A leftover from the switch back to using guid's, that I didn't notice because all the test files I used were called `test.png` and so didn't trip the CHAR(36) length maximum 🙃
> 🐛 Use guid for cloudflare image uploads

- adminSiteClient/ImagesIndexPage.tsx
- adminSiteClient/admin.scss
- adminSiteServer/apiRouter.ts
- db/db.ts
One more feature for the images admin! Last one! I promise! 😅 
https://github.com/user-attachments/assets/5eb5a864-32cc-47e0-b8e9-ba1dce490ec3
> ✨ Add button to see which posts images are used in

- packages/@ourworldindata/grapher/src/chart/ChartUtils.tsx
- packages/@ourworldindata/grapher/src/facetChart/FacetChart.tsx
- packages/@ourworldindata/grapher/src/horizontalColorLegend/HorizontalColorLegends.tsx
- packages/@ourworldindata/grapher/src/lineCharts/LineChart.tsx
- packages/@ourworldindata/grapher/src/slopeCharts/SlopeChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedAreaChart.tsx
Two very minor (categorical) facet legend improvements:
- If a facet legend is hovered, then non-hovered bins are muted by reducing their opacity
- If a facet legend bin is hovered that is not plotted by a particular facet, then all lines in that facets are muted
- for example, hover 'Japan' in this chart: [live](https://ourworldindata.org/grapher/fossil-fuel-price-index?facet=metric&country=Brent~Northwest+Europe~UK+NBP~COL~IDN~JPN~Dubai) / [staging](http://staging-site-improve-facet-legends/grapher/fossil-fuel-price-index?facet=metric&country=Brent~Northwest+Europe~UK+NBP~COL~IDN~JPN~Dubai)
> ✨ improve hover state of facet legends

- adminSiteServer/adminRouter.tsx
- baker/MultiDimBaker.tsx
- functions/grapher/[slug].ts
- functions/grapher/by-uuid/[uuid].ts
- functions/multi-dim/[slug].json.ts
- site/multiDim/MultiDimDataPage.tsx
- site/multiDim/MultiDimDataPageContent.tsx
This PR fixes an issue in the MDim workflow when working in the ETL with staging servers. This is the setup that a lot of data managers use.
Lucas reported that when he makes changes in the ETL on his machine and runs the ETL update targeting a staging server, MDim views would not get updated. 
It turns out that the reason this happens (and is different from the local workflow) is that on staging servers, /grapher/by-uuid/UUID.config.json is not handled by the mock site router but instead by CF functions (atm wrangler if I understand correctly, soon probably the CF preview deploy).
These CF functions have s-MaxAge set and so cache the results for a good while.
This PR enables the IsPreviewing flag that we use in the runSiteFooterScripts script and if it is set then reqeusts to the above …
> Fix ETL staging server MDim caching issues

- db/model/Gdoc/enrichedToMarkdown.ts
- db/model/Gdoc/enrichedToRaw.ts
- db/model/Gdoc/exampleEnrichedBlocks.ts
- db/model/Gdoc/rawToEnriched.ts
- packages/@ourworldindata/types/src/gdocTypes/ArchieMlComponents.ts
- site/gdocs/components/ArticleBlock.tsx
Text inside the code block should be show verbatim, i.e. it's gonna be simple strings, not `EnrichedBlockText`.
> Fix type of EnrichedBlockCode

- site/DataPageContent.scss
I think this very small min-height was set so that content below the fold is more often visible, but we went to far. The above given min-height (540px) is reasonable and should apply in all cases.
| <img width="513" alt="Screenshot 2024-12-13 at 16 40 05" src="https://github.com/user-attachments/assets/7400fc3e-cdde-4aae-8b56-f4b624f47c9b" /> | <img width="513" alt="Screenshot 2024-12-13 at 16 40 18" src="https://github.com/user-attachments/assets/1c58b18f-bd60-425c-85e4-40e59be2df30" /> |
> ✨ (data page) restrict Grapher to reasonable min height

- packages/@ourworldindata/grapher/src/stackedCharts/StackedAreaChart.tsx
> 🐛 (stacked area) prevent crash when adjusting timeline while tooltip is visible

- packages/@ourworldindata/components/src/IndicatorProcessing/IndicatorProcessing.scss
Fixes an issue where horizontally dragging moves the whole page.
This happened because one of the elements had overflow.
https://github.com/user-attachments/assets/7835e9db-a546-429c-a0ec-c9dfdfee32ac
> 🐛 (data page) avoid horizontal page overflow

- packages/@ourworldindata/grapher/src/core/Grapher.tsx
This fixes a problem on mobile where showing/hiding the browser chrome (which happens on scroll) toggled the full screen button visibility, which lead to a jumpy layout.
> 🐛 hide full screen button when not useful

- 1733503871571-AddPageviewsUrlIndex.ts
- adminSiteClient/ChartIndexPage.tsx
- adminSiteClient/ChartList.tsx
- adminSiteClient/ChartRow.tsx
- adminSiteClient/EditorReferencesTab.tsx
- adminSiteServer/apiRouter.ts
- db/model/Chart.ts
This was a small request by authors - surfacing pageviews more prominently is useful prioritizing work on charts.
This PR shows the average daily pageviews in the chart index page and allows users to sort by these pageviews.
An index on analytics_pageviews is added so that joins can be more performant
> ✨ show average daily pageviews in charts list and references tab

- README.md
- functions/_common/downloadFunctions.ts
- functions/_common/metadataTools.ts
- functions/_common/readmeTools.ts
- functions/_common/urlTools.ts
- functions/package.json
- packages/@ourworldindata/grapher/src/modal/DownloadModal.tsx
- yarn.lock
When using the download API, add information about active filters to the metadata and readme.
> ✨ Add filter information to readme and metadata

- adminSiteServer/apiRouter.ts
The pageviews join on charts should only match pageviews for published charts
> 🐛 fix chart pageviews sql query bug

- db/model/Gdoc/extractGdocComponentInfo.ts
This fixes a bug when gdoc components have optional properties that are enumerated by the gdoc component extraction code
> Fix gdoc component extraction

- packages/@ourworldindata/grapher/src/lineCharts/LineChart.tsx
> 🐛 (line) dismiss projection line on deselecting an entity

- packages/@ourworldindata/grapher/src/horizontalColorLegend/HorizontalColorLegends.tsx
- packages/@ourworldindata/grapher/src/mapCharts/MapChart.tsx
Resolves https://github.com/owid/owid-grapher/issues/3988 by left-aligning categorical map legends when they have more than one line.
Introduces a bit of a regression, where the left/right padding around legend is removed (see second screenshot below). The padding has to be zero when the legend is left-aligned, but I can't add a condition to the code to that effect since that would introduce a cyclic dependency (to know whether to left-align the legend, I need to know the number of lines, and to know the number of lines, I need to know the `maxLegendWidth`).
| <img width="552" alt="Screenshot 2024-12-17 at 12 55 11" src="https://github.com/user-attachments/assets/9ad656d6-f5ca-4742-984f-f99d5f411548" /> | <img width="552" alt="Screenshot 2024-12-17 …
> ✨ (map) left-align multi-line categorical legends

- packages/@ourworldindata/grapher/src/slopeCharts/SlopeChart.tsx
Improve the SVG output of slope charts for Figma.
> ✨ (slope) improve svg output for figma

- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/scatterCharts/ScatterPlotChart.test.ts
- packages/@ourworldindata/grapher/src/scatterCharts/ScatterPlotChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/MarimekkoChart.tsx
Fixes #4284 by applying color tolerance before the author's timeline filter is applied to the input table.
This is how the bug for gray scatter plots like [this one](https://ourworldindata.org/grapher/affected-by-disasters-vs-gdp) happened:
- The World regions dataset only has data for 2023
- The chart's `timelineMax` is set to 2021
- Grapher first filters the input table by `[timelineMin, timelineMax]`, thereby dropping years 2022 and 2023 including all color values
- Later, in the scatter plot's `transformTable` function, Grapher applies infinite tolerance to the color dimension, but since all colour values have been removed, the colour column remains empty
Fixed by running colour (and size) tolerance for scatter and marimekkos earlier.
> 🐛 (scatter/marimekko) apply color/size tolerance early

- adminSiteClient/ImagesIndexPage.tsx
- adminSiteServer/apiRouter.ts
- db/db.ts
- db/migration/1734369183234-CloudflareImagesReplacedBy.ts
- db/model/Gdoc/GdocBase.ts
- db/model/Gdoc/GdocFactory.ts
- db/model/Image.ts
- packages/@ourworldindata/types/src/dbTypes/Images.ts
Fixes https://github.com/owid/owid-grapher/issues/4313
- Adds a `replacedBy` column to the `images` table
- Adds a `version` column to the `images` table
- Removes the unique `filename` constraint on the `images` column
- Adds a unique constraint on `filename, version`
- Updates all places that select "all images" to only select images where `replacedBy` is null
- Updates images API functions to reflect these changes
- the PUT route now sets the `replacedBy` column, and triggers a build
- the DELETE route uses a CTE to find every image in the chain and deletes them all
- it's possible that a user unpublishes an article and immediately deletes its images before the rebake has occurred, thus temporarily breaking the article before it's removed, but that seems unlikely
1. Create three images …
> 🐛 fix cloudflare image version management

- packages/@ourworldindata/grapher/src/lineCharts/LineChart.tsx
- packages/@ourworldindata/grapher/src/lineLegend/LineLegend.test.tsx
- packages/@ourworldindata/grapher/src/lineLegend/LineLegend.tsx
- packages/@ourworldindata/grapher/src/slopeCharts/SlopeChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedAreaChart.tsx
Adds tests in preparation for a refactor of the code responsible for dropping labels when there is not enough space.
I also renamed some of the computed values in the line legend component for clarity.
The SVG tester comes back with a difference because there was a small issue about label padding that I fixed.
> 🧪 (line legend) add tests for dropping labels

- packages/@ourworldindata/grapher/src/lineLegend/LineLegend.test.tsx
- packages/@ourworldindata/grapher/src/lineLegend/LineLegend.tsx
- packages/@ourworldindata/grapher/src/lineLegend/LineLegendConstants.ts
- packages/@ourworldindata/grapher/src/lineLegend/LineLegendFilterAlgorithms.ts
- packages/@ourworldindata/grapher/src/lineLegend/LineLegendHelpers.ts
- packages/@ourworldindata/grapher/src/lineLegend/LineLegendTypes.ts
- packages/@ourworldindata/grapher/src/slopeCharts/SlopeChart.tsx
Refactors the code that is responsible for dropping labels if there is not enough space.
The SVG tester comes back with one additional difference. It's a slope charts where the 'Tanzania' and 'Mali' labels are swapped. Tanzania should be on top (its value is 1339) and 'Mali' should be below (its value is 1337), so the updated chart is correct.
> 🔨 (line legend) refactor label dropping algorithm

- site/owid.scss
This is the case when e.g. part of the heading is italicized.
> Fix padding of headings with multiple children

- site/SiteTools.tsx
The user is already on the page we are linking to and it's easy to mistake it for the form submit button.
> Hide floating donate button on the donation page

- adminSiteClient/ImagesIndexPage.tsx
- adminSiteServer/apiRouter.ts
https://github.com/user-attachments/assets/9ae0acfa-d97b-469a-a09e-174fbfc2237a
> ✨ persist alt text between image revisions

- packages/@ourworldindata/grapher/src/horizontalColorLegend/HorizontalColorLegends.tsx
If a non-focused series is hovered in the facet legend, then its colour should be used (not the un-focused gray)
> 🐛 (facet) show swatch colour on hovering

- packages/@ourworldindata/grapher/src/scatterCharts/NoDataSection.tsx
- packages/@ourworldindata/grapher/src/slopeCharts/SlopeChart.tsx
For scatters, the No Data section should be left-aligned.
> 🐛 (scatter) left-align no data section

- packages/@ourworldindata/explorer/src/Explorer.tsx
- packages/@ourworldindata/grapher/src/controls/entityPicker/EntityPicker.tsx
- packages/@ourworldindata/grapher/src/controls/entityPicker/EntityPickerConstants.ts
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/index.ts
Fixes https://github.com/owid/owid-grapher/issues/4357
If a focused entity is unselected, then it should be un-focused as well. We do this for charts, but I forgot to do this for explorers.
> 🐛 (explorer) dismiss focus state after unselecting an entity

- packages/@ourworldindata/grapher/src/core/Grapher.tsx
Focus should also be cleared when query params reset.
> 🐛 clear focus when clearing query params

- packages/@ourworldindata/grapher/src/stackedCharts/MarimekkoChart.jsdom.test.tsx
One test in the Marimekko test suite is flaky and (sometimes) fails. It seems to be a rounding issue. Instead of rounding the values ourselves, I use jest's `toBeCloseTo` that compares floating point values allowing for imprecision.
> 🧪 fix flaky test

- db/migration/1735896576517-RemoveRelativeModeFromDiscreteBarCharts.ts
- packages/@ourworldindata/grapher/src/barCharts/DiscreteBarChart.tsx
Drops axis grid lines and labels for all discrete bar charts. The axis is currently only shown for discrete bar charts in relative mode, but relative mode is not supported for discrete bar charts. 
---
- <kbd>&nbsp;2&nbsp;</kbd> #4372 
- <kbd>&nbsp;1&nbsp;</kbd> #4371 👈
> ✨ (discrete bar) hide horizontal axis

- packages/@ourworldindata/grapher/src/barCharts/DiscreteBarChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedDiscreteBarChart.tsx
Make the zero line of discrete bar charts and stacked discrete bar charts a bit thinner.
---
This is **part 2 of 2 in a stack** made with GitButler:
- <kbd>&nbsp;2&nbsp;</kbd> #4372 👈 
- <kbd>&nbsp;1&nbsp;</kbd> #4371
> ✨ (discrete bar) thin zero line

- adminSiteClient/DatasetEditPage.tsx
- adminSiteClient/VariableEditPage.tsx
- package.json
- yarn.lock
Minor edits to our Dataset Edit page:
- Add "Archive" label when we are in the edit page of an archived dataset. 
- Hide "Archive" button at the bottom whenever we are in an edit page of an archived dataset.
- Add a button linking users to the Wizard page "Dataset Preview" for that specific dataset.
- Nit: Add missing white space to the Variable Edit page.
> ✨ "Archive" label in dataset, link to Dataset preview in Wizard

- db/migration/1736177572560-HousekeepingSuggestedReviews.ts
[Tracking issue](https://github.com/owid/owid-issues/issues/1777)
In https://github.com/owid/etl/pull/3792 I'm working on a bot that will suggest a chart for revision daily. It'll be a public chart, that has few visits.
We want to avoid suggesting the same chart multiple times, so we need to track what has already been suggested. This PR adds a new table for that.
I had thought of a table named `suggested_reviews`, with columns `id`, `type`, `date`. Where `type` can be 'chart', 'dataset', etc.
> new table for chart (and possibly other objects) revisions

- db/migration/1736188395813-UpdateHousekeepingSuggestedReviews.ts
- db/migration/1736206740420-UpdateHousekeepingSuggestedReviews2.ts
Wrongly assigned the column `objectType` to be unique, which shouldn't be the case
> edit migration further

- db/migration/1736177572560-HousekeepingSuggestedReviews.ts
- db/migration/1736209759039-RemoveHousekeepingSuggestedReviews.ts
- db/migration/1736209905900-CreateHousekeeper.ts
I got a bit confused and ended up fixing various migrations due to two typos in the schema definition.
- initial commit (with typos): https://github.com/owid/owid-grapher/pull/4387
- First fix: https://github.com/owid/owid-grapher/pull/4388
- Second fix: https://github.com/owid/owid-grapher/pull/4389
Since it is not working, I think it's just better to drop the table (it was empty) and create the new one with the correct schema from scratch.
> housekeeper: this pr fixes all previous migrations

- site/SiteNavigation.tsx
- site/SiteTools.tsx
- Show Subscribe instead of Donate button again
- Remove call to action top banner
> Revert temporary giving season changes

- yarn.lock
```
> yarn dedupe --check
➤ YN0000: ┌ Deduplication step
➤ YN0000: │ @eslint-community/regexpp@npm:^4.10.0 can be deduped from @eslint-community/regexpp@npm:4.11.1 to @eslint-community/regexpp@npm:4.12.1
➤ YN0000: │ @types/estree@npm:* can be deduped from @types/estree@npm:1.0.5 to @types/estree@npm:1.0.6
➤ YN0000: │ acorn@npm:^8.1.0 can be deduped from acorn@npm:8.11.3 to acorn@npm:8.14.0
➤ YN0000: │ acorn@npm:^8.8.0 can be deduped from acorn@npm:8.11.3 to acorn@npm:8.14.0
➤ YN0000: │ acorn@npm:^8.8.1 can be deduped from acorn@npm:8.11.3 to acorn@npm:8.14.0
➤ YN0000: │ detect-libc@npm:^2.0.0 can be deduped from detect-libc@npm:2.0.2 to detect-libc@npm:2.0.3
➤ YN0000: │ es-define-property@npm:^1.0.0 can be deduped from es-define-property@npm:1.0.0 to es-define-property@npm:1.0.1
➤ YN0000: …
```
> chore(deps): dedupe dependencies

- packages/@ourworldindata/grapher/src/chart/ChartUtils.tsx
- packages/@ourworldindata/grapher/src/lineCharts/LineChart.tsx
- packages/@ourworldindata/grapher/src/lineLegend/LineLegend.tsx
- packages/@ourworldindata/grapher/src/lineLegend/LineLegendHelpers.ts
We have hacky charts where the same indicator is used multiple times to create breaks within line charts. The React key for those cases is not appropriated and thus lines don't get removed when they're unselected:
https://github.com/user-attachments/assets/742fe4a6-804c-488a-9c27-38352a918670
> 🐛 (line) unselected lines don't disappear

- adminSiteServer/apiRouter.ts
- db/migrateWpPostsToArchieMl.ts
- packages/@ourworldindata/utils/src/metadataHelpers.ts
- site/Byline.tsx
- site/CitationMeta.tsx
- site/LongFormPage.tsx
- site/clientFormatting.tsx
- site/formatting.test.ts
- site/formatting.tsx
- site/gdocs/OwidGdocPage.tsx
> Fix citation metadata

- site/DataCatalog/DataCatalog.tsx
- site/DataCatalog/DataCatalogPage.tsx
Number formatting was requested by Marwa and as I was changing it I noticed we set a wrong canonical URL for the data catalog, so I fixed that too.
> Add formatting for numbers in data catalog

- packages/@ourworldindata/grapher/src/lineCharts/LineChart.tsx
In rare cases, authors hack line charts to show breaks between line segments. They do so by using the same indicator multiple times. One side effect is that Grapher then shows a line legend label for each of these lines.
This PR makes this a bit better by de-duplicating line legend labels. I can't think of a use case where we'd want to show identical line labels.
| <img width="1219" alt="Screenshot 2025-01-09 at 13 04 44" src="https://github.com/user-attachments/assets/dabb6f27-8973-4981-81e3-14f070532198" /> | <img width="1219" alt="Screenshot 2025-01-09 at 13 04 59" src="https://github.com/user-attachments/assets/f6e57b3c-76e1-4941-8675-20430a039460" /> |
Link: https://ourworldindata.org/explorers/poverty-explorer?facet=none&country=BOL~DEU~ALB&Indi …
> ✨ (line) deduplicate line labels

- adminSiteClient/EditorExportTab.tsx
Add a button in the chart edit page (Export tab), linking the user to Wizard app "Chart animation" to animated that chart.
(added multiple reviewers, just with one review is fine)
> ✨ Add wizard link for chart animation

- .github/workflows/project-automations.yml
I know it's unconventional to have an action target my PRs only, but manually adding the 'staging-viz' label to all of my PRs is soo annoying.
The 'staging-viz' label makes it so that the SVG tester doesn't fail when there are differences. That's the better default for me since SVG changes are expected for most of my PRs.
---
- <kbd>&nbsp;2&nbsp;</kbd> #4429 
- <kbd>&nbsp;1&nbsp;</kbd> #4428 👈
> 🐝 automatically add 'staging-viz' label to my PRs

- devTools/docker/mysql-init-docker/Dockerfile
Building db-load-data through docker compose (and/or as part of `make up.full`) fails with the following error:
``` 
Error response from daemon: invalid argument
```
The dockerd logs return the same generic error
```
Jan 08 13:38:52 matthieu-pr dockerd[16067]: time="2025-01-08T13:38:52.522058822Z" level=error msg="Handler for POST /v1.47/containers/create returned error: invalid argument" spanID=fe7aeda7b6d9d9b0 traceID=1c9ac07f8dd5be064aa53533cf0aa86e
```
Clearing the microdnf cache: `microdnf clean all`
Considered along the way:
- ❌ checking the container logs: empty
- ❌ create a container on a base mysql image then drop into it, and run the commands manually: goes through
- ❌ using a different package manager: apt, yum not present on base mysql image
> fix: db-load-data error when restarting

- packages/@ourworldindata/grapher/src/color/CustomSchemes.ts
Resolves https://github.com/owid/owid-grapher/issues/4141
> 🐛 compare colors using lower case hex codes

- packages/@ourworldindata/grapher/src/horizontalColorLegend/HorizontalColorLegends.tsx
- packages/@ourworldindata/grapher/src/mapCharts/MapChart.tsx
Reverts owid/owid-grapher#4324
The regression introduced in the PR above means that the legend is often overlapping on smaller screens.
> Revert "✨ (map) left-align multi-line categorical legends" / TAS-804

- packages/@ourworldindata/grapher/src/axis/Axis.ts
- packages/@ourworldindata/grapher/src/axis/AxisConfig.ts
- packages/@ourworldindata/grapher/src/axis/AxisViews.tsx
- packages/@ourworldindata/grapher/src/scatterCharts/ScatterPlotChart.tsx
- packages/@ourworldindata/types/src/grapherTypes/GrapherTypes.ts
Resolves https://github.com/owid/owid-grapher/issues/3567
Rotates the y-axis labels for scatter plots to make them horizontal and easier to read.
It would be nice if we also rotated the y-axis label for Marimekko charts, but for Marimekko charts with an x-dimension, the x-axis labels are plotted above the chart area (see screenshot). It would be confusing if we showed both labels on the same line.
I also tried right-aligning x-axis labels, but it often looked unbalanced.
<details><summary>Example of a Marimekko chart with a x-dimension</summary>
<p>
</p>
</details>
---
This is **part 1 of 3 in a stack** made with GitButler:
- <kbd>&nbsp;3&nbsp;</kbd> #4403 
- <kbd>&nbsp;2&nbsp;</kbd> #4402 
- <kbd>&nbsp;1&nbsp;</kbd> #4331 👈
> ✨ (scatter) rotate y-axis label / TAS-801

- adminSiteClient/DimensionCard.tsx
- packages/@ourworldindata/grapher/src/lineCharts/LineChart.tsx
- packages/@ourworldindata/grapher/src/lineCharts/LineChartConstants.ts
- packages/@ourworldindata/grapher/src/schema/grapher-schema.006.yaml
- packages/@ourworldindata/types/src/OwidVariableDisplayConfigInterface.ts
- packages/@ourworldindata/utils/src/OwidVariable.ts
Resolves https://github.com/owid/owid-grapher/issues/2824
Allow line charts to plot indicators with markers only.
Example on staging: http://staging-site-disconnect-lines/admin/charts/8428/edit
- Adds a new flag to the `display` object of an indicator, `plotMarkersOnlyInLineChart`
- If the flag is enabled for an indicator, then the line chart only draws markers (and doesn't connect data points by a line)
- Marker-only mode for projections is not supported
I struggled to come up with a good name and in the end went with something explicit, `plotMarkersOnlyInLineChart`. I'm happy to rename if we come up with a better name.
I don't know why the default config action is failing, but I don't think it's related to the changes in this PR.
---
This is **part 1 of 3 in a stack** made with …
> 🎉 (line) allow to disconnect lines / TAS-775

- .github/workflows/check-default-grapher-config.yml
- .github/workflows/sync-grapher-schema-to-digital-ocean.yml
The GitHub workflows using Nushell started failing with the following error message:
> 🔨 update nu-shell

- packages/@ourworldindata/explorer/src/ColumnGrammar.ts
- packages/@ourworldindata/explorer/src/ExplorerProgram.ts
- packages/@ourworldindata/explorer/src/gridLang/GridLangConstants.ts
Add support for disconnected, markers-only lines in explorers.
---
This is **part 2 of 3 in a stack** made with GitButler:
- <kbd>&nbsp;3&nbsp;</kbd> #4406 
- <kbd>&nbsp;2&nbsp;</kbd> #4405 👈 
- <kbd>&nbsp;1&nbsp;</kbd> #4382
> 🎉 support disconnecting lines in explorers / TAS-797

- packages/@ourworldindata/explorer/src/ColumnGrammar.ts
Resolves https://github.com/owid/owid-grapher/issues/4394
Add support for projections in explorers.
---
This is **part 3 of 3 in a stack** made with GitButler:
- <kbd>&nbsp;3&nbsp;</kbd> #4406 👈 
- <kbd>&nbsp;2&nbsp;</kbd> #4405 
- <kbd>&nbsp;1&nbsp;</kbd> #4382
> 🎉  support projections in explorers / TAS-798

- adminSiteClient/EditorCustomizeTab.tsx
- adminSiteClient/EditorFeatures.tsx
- packages/@ourworldindata/grapher/src/barCharts/DiscreteBarChart.tsx
- packages/@ourworldindata/grapher/src/controls/SettingsMenu.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedDiscreteBarChart.tsx
Resolves https://github.com/owid/owid-grapher/issues/4364
Shows a discrete and stacked discrete bar chart with a linear scale always.
In particular:
- Hides the 'Enable log/linear toggle' in the admin for discrete bar charts
- Hides log/linear toggle in the settings menu for discrete bar charts
- Forces discrete bar charts to use a linear scale, even if the axis config says otherwise
> ✨ disallow log y-scale for discrete bar charts / TAS-802

- packages/@ourworldindata/grapher/src/modal/SourcesModal.tsx
This PR deduplicates the sources based on their label. 
In rare cases, authors hack line charts to show breaks between line segments. They do so by using the same indicator multiple times. One side effect is that Grapher then shows a source tab for every imported indicator – even when their identical. 
For scatter plots like [this one](https://ourworldindata.org/grapher/female-labor-force-participation-rates-latest-vs-1980) that use the same indicator twice with different target years, the sources also appear twice.
I can't think of a situation where the tab label would be exactly the same, but we'd still want to show both tabs. So I decided to deduplicate by label. It would be safer to deduplicate on all of the content, but that seems wasteful.
SVG testet differences come from a previous …
> ✨ deduplicate sources tab by label / TAS-793

- functions/_common/downloadFunctions.ts
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/dataTable/DataTable.sample.ts
- packages/@ourworldindata/grapher/src/dataTable/DataTable.tsx
- packages/@ourworldindata/grapher/src/modal/DownloadModal.tsx
Fixes #4432
If 'Show selection only' on the table tab is toggled, then 'Download displayed data' only downloads data for those entities that are displayed in the table.
If 'Show selection only' isn't toggled, then 'Download displayed data' downloads all data (since all data is displayed). Don't know if this could be confusing. I find it okay.
This PR makes non-trivial changes to the Grapher component. Let me know if you prefer to wait for your refactor before merging this PR.
👇🏻 See my comment about `grapher.inputTable` vs `grapher.table` below
---
- <kbd>&nbsp;2&nbsp;</kbd> #4447 
- <kbd>&nbsp;1&nbsp;</kbd> #4433 👈
> 🐛 take table filter toggle into account for data download / TAS-796

- adminSiteClient/GdocsManualBreadcrumbsInput.tsx
- adminSiteClient/GdocsPreviewPage.tsx
- adminSiteClient/GdocsSettingsForms.tsx
- adminSiteClient/gdocsDeploy.ts
- adminSiteClient/gdocsValidation.ts
- adminSiteServer/apiRoutes/gdocs.ts
- adminSiteServer/app.test.ts
- baker/SiteBaker.tsx
- baker/algolia/utils/charts.ts
- baker/algolia/utils/explorerViews.ts
- db/db.ts
- db/migrateWpPostsToArchieMl.ts
- db/migration/1736443943021-RemoveManualBreadcrumbsFromNonSDGArticles.ts
- db/migration/1736455365750-RenameBreadcrumbsColumn.ts
- db/migration/1736969067156-PostsGdocsUpdatedAt.ts
- db/model/Gdoc/GdocBase.ts
- db/model/Gdoc/GdocFactory.ts
- db/tests/testHelpers.ts
- packages/@ourworldindata/types/src/dbTypes/PostsGdocs.ts
- packages/@ourworldindata/types/src/dbTypes/TagsGraph.ts
- packages/@ourworldindata/types/src/domainTypes/ContentGraph.ts
- packages/@ourworldindata/types/src/gdocTypes/Gdoc.ts
- packages/@ourworldindata/types/src/index.ts
- packages/@ourworldindata/utils/src/Util.ts
- site/Breadcrumb/Breadcrumb.tsx
- site/gdocs/components/centered-article.scss
- site/gdocs/pages/GdocPost.tsx
Resolves https://github.com/owid/owid-grapher/issues/3406
- Adds programmatically generated breadcrumbs to our tagged gdocs articles, based on the tag graph
- Fixes erroneous parent tag logic to reflect the fact that a tag may have multiple paths to get to it
- This requires a somewhat verbose new structure called a `ParentTagArray` which is an array of tags. One child tag can have multiple `ParentTagArray`s e.g. "Nuclear Energy" can be a child of "Energy" and in a different part of the graph, a child of "CO2 Emissions"
- We want _all_ of these parent tags for Algolia indexing, so the code has been fixed to reflect this
1. For each tag, pick the root-to-leaf subgraph with the highest weighted top node (tiebreak alphabetically)
2. For each subgraph, filter out non-topic nodes
3. Pick the …
> 🎉 automatic breadcrumbs from the tag graph

- .github/workflows/sync-grapher-schema-to-digital-ocean.yml
Our schema update script stopped working after upgrading nushell in the github runner from 0.80 to 0.101. The reason was that `str replace` changed the default from regex mode to normal string replace and now you have to pass `-r` to do a regex replace.
> 🐝 fix schema update nuschell script (-r flag needed now)

- adminSiteServer/multiDim.ts
- baker/MultiDimBaker.tsx
- packages/@ourworldindata/types/src/index.ts
- packages/@ourworldindata/types/src/siteTypes/MultiDimDataPage.ts
- packages/@ourworldindata/utils/src/MultiDimDataPageConfig.test.ts
- packages/@ourworldindata/utils/src/MultiDimDataPageConfig.ts
- site/multiDim/MultiDimDataPageContent.tsx
We now normalize the indicators to a list of objects, which can have an optional `display` property. See `IndicatorConfig`.
Resolves #4040
> Allow overriding display settings of indicators in mdims

- functions/_common/reusableHandlers.ts
Fixes https://github.com/owid/owid-grapher/issues/4450
Our `cors` middleware mutates all requests, but cached requests are immutable (a quick perusal through Cloudflare Workers/Functions docs didn't state this anywhere, but a lot of other third-party sources did)
This PR clones the cached thumbnail requests so that `corsify` can mutate them.
These issues are still in the `grapher/thumbnail` router, but that route should be deprecated, anyway.
> 🐛 fix immutable header mutation in handleThumbnailRequest

- packages/@ourworldindata/components/src/MarkdownTextWrap/MarkdownTextWrap.tsx
- packages/@ourworldindata/core-table/src/CoreTableColumns.ts
- packages/@ourworldindata/grapher/src/axis/Axis.ts
- packages/@ourworldindata/grapher/src/tooltip/TooltipContents.tsx
Resolves #4362 
Appends the unit to axis labels in parens, like "**label** (unit)".
The next PR makes it so that for axis labels that have parens, like `Human Development Index (male)`, only the first part (Human Development Index) is made bold. It looks nicer.
---
This is **part 3 of 4 in a stack** made with GitButler:
- <kbd>&nbsp;4&nbsp;</kbd> #4443 
- <kbd>&nbsp;3&nbsp;</kbd> #4403 👈 
- <kbd>&nbsp;2&nbsp;</kbd> #4402 
- <kbd>&nbsp;1&nbsp;</kbd> #4331
> ✨ add unit to axis labels / TAS-784

- packages/@ourworldindata/core-table/src/CoreTableColumns.ts
- packages/@ourworldindata/grapher/src/axis/Axis.ts
- packages/@ourworldindata/grapher/src/chart/ChartUtils.tsx
- packages/@ourworldindata/grapher/src/tooltip/Tooltip.scss
- packages/@ourworldindata/grapher/src/tooltip/TooltipContents.tsx
Deemphasis text in parentheses. For example, in the screenshot below "male" and "female" are deemphasised.
---
This is **part 4 of 4 in a stack** made with GitButler:
- <kbd>&nbsp;4&nbsp;</kbd> #4443 👈 
- <kbd>&nbsp;3&nbsp;</kbd> #4403 
- <kbd>&nbsp;2&nbsp;</kbd> #4402 
- <kbd>&nbsp;1&nbsp;</kbd> #4331
> ✨ deduplicate unit in axis labels / TAS-810

- functions/_common/imageOptions.ts
Adds an `imType=square` option to Grapher SVGs that returns a square version of the SVG with a white background (`imType=social-media-square` downloads a square version with beige background).
I need this for the Figma Plugin I'm working on.
I can verify that these changes work locally, but on staging `imType=square` returns the square image with beige background. Not sure why.
> ✨ add 'square' option to grapher thumbnails

- site/gdocs/pages/Homepage.scss
- site/gdocs/pages/Homepage.tsx
Okay, I'll admit it, I spent way too much time to fix this small little annoyance 😬 But I learned a bit about grid layouts on the way, soo... :)
The video shows the two things that have changed:
https://github.com/user-attachments/assets/6ffede95-9d61-452c-8e99-91552f0c5624
> enhance(homepage): better socials block on homepage

- packages/@ourworldindata/grapher/src/axis/Axis.test.ts
- packages/@ourworldindata/grapher/src/axis/Axis.ts
- packages/@ourworldindata/grapher/src/facetChart/FacetChart.tsx
- packages/@ourworldindata/grapher/src/lineCharts/LineChart.tsx
- packages/@ourworldindata/grapher/src/slopeCharts/SlopeChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/AbstractStackedChart.tsx
Resolves https://github.com/owid/owid-grapher/issues/3978
See https://github.com/owid/owid-grapher/commit/3790bad420d85b8915dfb9ce3df41712f5daf768 😅
Relying on d3's nice implementation sometimes leads to suboptimal results because d3 adds grid lines too eagerly (some examples below). That's why I ended up writing a custom 'nice' function for Grapher. It only adds an additional grid line if any data value exceeds the highest grid line by more than 25%. 
<details><summary>Examples of d3.nice where grid lines are placed to eagerly</summary>
<p>
If any data value is _just above_ a grid line, then showing an additional grid line 'squishes' the rest of the chart.
</p>
</details>
> ✨ use 'nice' axis ticks for linear scales / TAS-795

- devTools/tsconfigs/tsconfig.base.json
- package.json
- yarn.lock
https://www.npmjs.com/package/@tsconfig/node22
We still have to override `module` and `moduleResolution` because `node16` causes issues with imports of external packages like `instantsearch.js`.
> Update base TSConfig to options supported by Node 22

- site/DataCatalog/DataCatalogUtils.ts
The data catalog area filters are not handling sub-areas, they only go one level deep.
We recently added sub-areas to the graph, so the real topics were "hidden" on level below.
This doesn't address:
- type error in getTopicsForRibbons
- other places areas might be considered a one-level deep tree structure
Note that ribbons continue to show all children (and now grandchildren tags), not just the topic tags (that is tags with a matching topic page)
> fix: recursively fetch all tags in topic area

- adminSiteClient/constants.ts
- db/model/Gdoc/GdocBase.ts
- db/model/Gdoc/enrichedToMarkdown.ts
- db/model/Gdoc/enrichedToRaw.ts
- db/model/Gdoc/exampleEnrichedBlocks.ts
- db/model/Gdoc/rawToArchie.ts
- db/model/Gdoc/rawToEnriched.ts
- packages/@ourworldindata/types/src/gdocTypes/ArchieMlComponents.ts
- site/gdocs/components/KeyInsights.tsx
Based on a feature request from Slack: https://owid.slack.com/archives/C0149NKLZAM/p1737397453015989
You can preview this feature on the staging server here: http://staging-site-key-insights-narrative-chart/admin/gdocs/15ofwDSH2K_SEjQ7aZsLd99r6aGczV9vEz-uQzcHH0nY/preview
I didn't implement `htmlToEnriched` for this, since I assume it's only been used for WP -> gdocs conversion. Am I right in that?
> feat(gdocs): enable narrative charts inside key insights

- db/migration/1737580227406-RetainMultiEntitySelectionForChartsSplitByMetric.ts
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
Allow single-entity selection for charts split by metric.
> 🐛 allow single-entity selection for charts split by metric / TAS-828

- adminSiteClient/admin.scss
- adminSiteServer/apiRoutes/gdocs.ts
- db/db.ts
- db/model/Gdoc/GdocFactory.ts
Resolves #4493
Compares via canonical URL in the event we want `/data-insights/some-slug` and `/some-slug`
Renamed `addImagesToContentGraph` to `setImagesToContentGraph` because I was confused when reading it to see that it also took care of deleting images from the content graph if unpublishing.
https://github.com/user-attachments/assets/496f66d0-b7a7-49d3-a2e2-8d24958d0ed4
> ✨ check there's no slug collision before publishing

- functions/_common/downloadFunctions.ts
- functions/_common/grapherRenderer.ts
- functions/_common/grapherTools.ts
- functions/_common/metadataTools.ts
- functions/_common/readmeTools.ts
- functions/_common/urlTools.ts
- site/multiDim/MultiDimDataPageContent.tsx
> Add data download handling for multi-dims

- baker/GrapherBaker.tsx
- baker/GrapherBakingUtils.ts
- baker/MultiDimBaker.tsx
- db/model/Chart.ts
- db/model/MultiDimDataPage.ts
- devTools/tsconfigs/tsconfig.base.json
* Don't delete mdims in GrapherBaker
* Delete old mdims in MultiDimBaker
* Improve the console output
* Document issue with TSConfig and getting ESNext types
> Fix multidimensional data pages baking logic

- site/gdocs/components/centered-article.scss
- site/owid.scss
Still pretty glitchy on non-chrome browsers - this is just a best-effort attempt, timeboxed to an hour of tinkering. Feel free to add patches to the branch if you get nerd-sniped, but I recommend approving and running away as fast as you can 😁 
https://github.com/user-attachments/assets/c9209dac-9cca-4bff-99b7-a57fd9827e2f
> 🎉 hide footer when printing, better article layout

- adminSiteServer/functionalRouterHelpers.ts
- adminSiteServer/publicApiRouter.ts
- db/model/ChartView.ts
Adding a new `/chartViewMap` route to the public admin router, as disucssed.
I can access it locally (http://localhost:3030/api/chartViewMap) but not on staging.
> 🔨 add chart view map to public admin router

- site/gdocs/components/HomepageIntro.tsx
- site/gdocs/components/LinkedA.tsx
- site/gdocs/components/Person.tsx
- site/gdocs/components/PillRow.tsx
- site/gdocs/components/ProminentLink.tsx
- site/gdocs/components/Recirc.tsx
- site/gdocs/components/ResearchAndWriting.tsx
- site/gdocs/components/TopicPageIntro.tsx
- site/gdocs/utils.ts
- When previewing, link to the baked site. This is necessary for previews to work correctly in admin in prod, where relative URL isn't sufficient, because admin is on a different domain then the main site.
- Don't add hash and query string to gdoc URLs. Gdocs can have params like `?tab=t.0` and similar internal hashes that we shouldn't add to our own URLs.
It seems the support for query strings and hashes was added on purpose but there are only a couple gdocs with link with seemingly custom query param `?usp=sharing`, so it seems fine to remove that support for now. When we'll need it, we should add a way to specify the query params separately from the URL (or filter out the known godcs query params, which seems too fragile).
> Fix prominent link URL

- adminSiteClient/ChartEditor.ts
- adminSiteClient/ChartEditorPage.tsx
- adminSiteClient/EditorBasicTab.tsx
- adminSiteServer/apiRouter.ts
- adminSiteServer/apiRoutes/charts.ts
- db/model/Chart.ts
> feat(admin): allow tagging on the chart basic tab

- baker/algolia/indexChartsToAlgolia.ts
- baker/algolia/indexExplorerViewsAndChartsToAlgolia.ts
- baker/algolia/indexExplorerViewsToAlgolia.ts
- baker/algolia/indexPagesToAlgolia.tsx
- baker/algolia/utils/explorerViews.ts
There's been an issue for a while with `indexExplorerViewsAndCharts` due to some missing metadata in the covid explorer that was crashing the indexing script, that wasn't getting caught due to the process terminating before the Sentry request could finish.
This PR fixes both issues.
> 🐛 Fix algolia indexing and error capturing

- db/migration/1738574434234-AlterVariablesIndexes.ts
The `variables` table uses two indexes that make our ETL process more difficult. One is a unique index on `short_name`, and the other is a unique index on `title`. Both are now redundant since all variables can be addressed by `catalogPath`.  
These indexes become problematic when a dataset contains two tables with the same title (rare but harmless). Additionally, we recently encountered a [consistency issue](https://github.com/owid/etl/pull/3918) caused by hacky workarounds related to these indexes.  
Can these indexes be safely removed, or do we rely on them somewhere in owid-grapher?
> :hammer: Alter indexes for variables table

- baker/algolia/utils/explorerViews.ts
Otherwise Sentry won't group the event correctly.
Follow up to #4511.
> Capture error instead of object in explorerViews

- adminSiteClient/ChartRow.tsx
- adminSiteClient/EditorTextTab.tsx
Adds copy to markdown buttons for a chart in two places:
- On the charts index page in the admin
- On the 'Text' tab in the chart editor
> 🎉 (admin) add copy to markdown button / TAS-866

- packages/@ourworldindata/grapher/src/chart/ChartDimension.ts
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/core/LegacyToOwidTable.test.ts
- packages/@ourworldindata/grapher/src/core/LegacyToOwidTable.ts
- packages/@ourworldindata/types/src/OwidVariableDisplayConfigInterface.ts
- packages/@ourworldindata/types/src/index.ts
Refactor the creation of inputtable in anticipation of extracting the loading functionality. This PR does the following things:
- legacyToOwidTable is changed to no longer require a full grapher config but only a dimensions array and the selected entity colors
- dimensions is no longer returned from legacyToOwidTableAndDimensions - instead the slug adjustements are made as a getter in ChartDimension
> Refactor input table

- packages/@ourworldindata/grapher/src/lineCharts/LineChart.tsx
Don't hide line chart markers for square format exports.
> ✨ show dots in line charts for mobile exports

- site/SiteFooter.tsx
- site/css/site-tools.scss
Fixes the issue where the `site-tools` container was obscuring content even when its contents was hidden.
If we're not okay with 94% browser support, I'll rewrite this with JS but it's slightly annoying as I'll have to use a ref and layout effect to apply the transformation to `SiteTools` parent (the div container)
https://github.com/user-attachments/assets/a8fb3079-3419-43a9-b020-51c9c5722e83
> ✨ prevent site-tools from obscuring content of page

- site/gdocs/components/KeyIndicator.tsx
We need to pass the unresolved URL to Chart, where we resolve it with useLinkedChart again. If we pass the already resolved URL for a chart that was redirected, it won't be found in the attachments.
See [Slack discussion](https://owid.slack.com/archives/C46U9LXRR/p1738749662622129).
> Fix KeyIndicator not showing grapher with a redirect

- adminSiteClient/EditorExportTab.tsx
- packages/@ourworldindata/grapher/src/footer/Footer.tsx
Hide origin URL for square format exports. 
---
This is **part 3 of 3 in a stack** made with GitButler:
- <kbd>&nbsp;3&nbsp;</kbd> #4529 👈 
- <kbd>&nbsp;2&nbsp;</kbd> #4522 
- <kbd>&nbsp;1&nbsp;</kbd> #4427
> ✨ hide origin url for square exports / TAS-876

- packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.tsx
Removes the background rect from grapher exports.
Notes from the [Slack conversation](https://owid.slack.com/archives/CQQUA2C2U/p1738779580648569) where Marcel shared his thoughts:
- The rect was introduced to aid Wikipedians, because Wikipedia back then didn't respect any other background properties we had and instead put the chart on a transparent background. see https://github.com/owid/owid-grapher/issues/1993 
- Not a blocker because our SVGs can currently not be uploaded to Wikimedia Commons because the <style> block for loading fonts is considered unsafe
> 🔨 remove background from grapher exports / TAS-875

- adminSiteClient/ChartIndexPage.tsx
- adminSiteClient/ChartList.tsx
- adminSiteClient/admin.scss
- adminSiteServer/apiRoutes/charts.ts
- adminSiteServer/apiRoutes/datasets.ts
- adminSiteServer/apiRoutes/tags.ts
- adminSiteServer/apiRoutes/variables.ts
Fixes #4521 by including `pageviewsPerDay` in the 3 relevant queries for dataset, variable, and tag pages.
Also improves the 3 uses of `ChartList` (in dataset, variable, and tag pages) insofar that one can now also search these lists.
The split between `ChartIndexPage` and `ChartList` is now as follows: ChartIndexPage only needs to take care of data loading, and then passes a complete, unfiltered list of charts to `<ChartList>`.
It then takes care of sorting, filtering, basic pagination (via "Show more charts"), and handling the `?chartSearch=` query param.
> feat(admin): bring feature parity to all uses of `ChartList` component

- packages/@ourworldindata/components/src/Halo/Halo.tsx
- packages/@ourworldindata/grapher/src/lineLegend/LineLegend.tsx
- packages/@ourworldindata/grapher/src/slopeCharts/SlopeChart.tsx
Improves the SVG structure of slope charts for use in Figma.
The line labels are messed up when imported into Figma because Figma doesn't display `<tspan />` elements correctly and `MarkdownTextWrap` relies on them for rendering. I filed a bug report with Figma and hope this gets fixed on their site.
Changes:
- Figma users prefer the slope to be made up individual elements (two dots and a line) because it's then easier to make changes to those elements, like resizing the dots or increasing the line thickness
- I also added more specific element names
---
This is **part 4 of 7 in a stack** made with GitButler:
- <kbd>&nbsp;7&nbsp;</kbd> #4539 
- <kbd>&nbsp;6&nbsp;</kbd> #4538 
- <kbd>&nbsp;5&nbsp;</kbd> #4537 
- <kbd>&nbsp;4&nbsp;</kbd> #4531 👈 
- <kbd>&nbsp;3&nbsp;</kbd> #4529 
- …
> ✨ (slope) improve svg structure for figma / TAS-878

- packages/@ourworldindata/grapher/src/facetChart/FacetChart.tsx
Passing `isStatic` to the chart instances makes it so that they render their static version when exported to a SVG.
---
This is **part 7 of 7 in a stack** made with GitButler:
- <kbd>&nbsp;7&nbsp;</kbd> #4539 👈 
- <kbd>&nbsp;6&nbsp;</kbd> #4538 
- <kbd>&nbsp;5&nbsp;</kbd> #4537 
- <kbd>&nbsp;4&nbsp;</kbd> #4531 
- <kbd>&nbsp;3&nbsp;</kbd> #4529 
- <kbd>&nbsp;2&nbsp;</kbd> #4522 
- <kbd>&nbsp;1&nbsp;</kbd> #4427
> ✨ (facets) improve svg structure for figma

- adminSiteServer/mockSiteRouter.ts
- baker/SiteBaker.tsx
- baker/siteRenderers.tsx
- site/DataInsightsIndexPageContent.tsx
- site/DataPageV2Content.tsx
- site/gdocs/AttachmentsContext.tsx
- site/gdocs/OwidGdoc.tsx
- site/gdocs/components/AllCharts.scss
- site/gdocs/components/AllCharts.tsx
- site/multiDim/MultiDimDataPageContent.tsx
Resolves https://github.com/owid/owid-grapher/issues/4426
- Adds a button to the data catalog on the all charts block
- Adds `tags` to the gdoc AttachmentsContext
- Uses a gdoc's first tag to automatically generate the heading of the all charts block
https://github.com/user-attachments/assets/a8d9e59e-8076-4c37-8bf0-13d40981a8df
> ✨ all-charts block updates

- baker/siteRenderers.tsx
Citation uses the same landing page for all three country profiles (meaning 2 are wrong):
- https://ourworldindata.org/coronavirus/country/united-states#citation
- https://ourworldindata.org/co2/country/united-states#citation
- https://ourworldindata.org/energy/country/united-states#citation
> By default, the first argument provided to the memoized function is coerced to a string and used as the cache key.
Passing the same `knex` connection as the first argument meant that the function would only be called once, and would return the same landing for all country profiles.
> fix: caching of country profile landing

- packages/@ourworldindata/grapher/src/slopeCharts/SlopeChart.tsx
The zero labels in relative mode are so trivial that we don't need to show them.
> ✨ (slope) hide zero label in relative mode

- site/DataCatalog/DataCatalog.tsx
Fixes https://github.com/owid/owid-grapher/issues/4316
The data catalog was logging searches to google analytics twice. You can see this on prod by going to https://ourworldindata.org/data, entering a query, and then opening the dev console and typing `dataLayer.at(-1)` and `dataLayer.at(-2)`
The data catalog ran all of its business logic through a single `useEffect`, which meant it called anytime any of its dependencies changed. Analytics was one of the last things I added and I didn't stop to think that this callback would fire anytime any of the dependencies updated, including updates to the cache or even no-op calls to update the state.
Extracts the analytics logic into an independent effect, which only runs when `stateAsUrl` changes (which always corresponds to a search running, even …
> 🐛 fix double-logging data catalog searches

- adminSiteClient/ChartIndexPage.tsx
- adminSiteClient/ChartList.tsx
Also fixes query params handling. See [Slack discussion](https://owid.slack.com/archives/C46U9LXRR/p1739468896959499).
> Fix scroll on pages with ChartList

- functions/explorers/[slug].ts
Explorer thumbnails (e.g. https://ourworldindata.org/explorers/co2.png) currently have a transparent background when they should be white.
This is due to https://github.com/owid/owid-grapher/pull/4527, which was done to make editing charts in Figma easier, and we didn't notice it quickly because Grapher thumbnails didn't have the issue.
I had added https://github.com/owid/owid-grapher/commit/10ff804fa7c538a1327625cfc4ad70954ff64f2f as a partial fix for this when I noticed it on the data catalog (and I see no harm in keeping 1 extra line of CSS just in case this breaks again, as unlikely as that seems)
Adding a backgroundColor argument to the `svgToPng` call in the explorer rendering CF function.
Run `make up.full` and visit http://localhost:8788/explorers/migration.png
Download the image …
> 🐛 fix transparent background for explorer thumbnail previews

- adminSiteServer/apiRoutes/misc.ts
Fixes https://github.com/owid/owid-grapher/security/advisories/GHSA-28j4-g4cq-9r32 - an SQL injection that can only be used when authenticated in the admin.
This is thus not super important to fix, but it's also super easy to fix, so let's just do it.
While working on this, I noticed that the whole WP codepath of this handler is not required any more - there are no published WP topic pages at this point. So I got rid of it and simplified the function quite a bit.
> fix(admin-api): fix authenticated SQL injection & remove unnecessary WP codepath

- adminSiteClient/VariablesIndexPage.tsx
We have a great semantic search over indicators in the ETL, but people may not be aware of it or have used it.
This change adds a link from the existing indicator search, making it easy to discover.
> 🎉 Link from admin indicator search to ETL semantic search

- adminSiteClient/GdocsMoreMenu.tsx
- adminSiteClient/GdocsPreviewPage.tsx
- adminSiteClient/admin.scss
Adds a mobile preview for GDocs.
I didn't want to clutter the interface, so I added it to the 'More' menu. I'm happy to move it elsewhere if you prefer.
The mobile preview width is 375px. The smallest size I usually check is 325 but that seems a little harsh – 375 is closer to the reality of today's phones, I think. 
<details><summary>Screenshot</summary>
<p>
</p>
</details>
> 🎉 (admin) add mobile preview to gdocs preview / TAS-837

- baker/redirects.ts
We take Grapher redirects into consideration only when a route returns 404 and Cloudflare caches assets up to a week in the CDN, so it's possible to still get the old page after a redirect is created for it.
Authors are confused why they don't see chart redirects working after they push changes. It also means different users can see different charts when clicking on the same link, depending on whether the CDN data center that handles their request had the old page cached. I tested this case with Pablo A.
We take a similar approach as for deleting articles and add redirects in the special `_redirects` file - that Cloudflare always takes into consideration - for Grapher redirects that are less than a week old.
> Add site redirects for recent chart redirects

- site/SiteMobileMenu.tsx
- site/SiteNavigationToggle.tsx
Adds an effect to scroll the 2 mobile expandable toggles into view when they expand below the viewport, per Marwa's request
https://github.com/user-attachments/assets/a9570561-8b61-45c2-9519-39791c139a49
> 🎉 add scrollTo when expanding SiteNavigationToggle on mobile

- adminSiteClient/DatasetEditPage.tsx
- adminSiteClient/EditorExportTab.tsx
- adminSiteClient/VariableEditPage.tsx
- devTools/cloudflareImagesSync/cloudflareImagesSync.ts
- packages/@ourworldindata/grapher/src/core/loadVariable.ts
- settings/clientSettings.ts
Fixes https://github.com/owid/ops/issues/267, https://github.com/owid/owid-grapher/issues/4480, https://github.com/owid/etl/issues/3889 and https://github.com/owid/ops/issues/266 (the lines of code to fixed issues ratio is unbelievable!).
Remove trailing slash from `DATA_API_URL` and `ETL_WIZARD_URL` to be consistent with the rest of variables and ETL envs. Replace string concat by `urljoin` to make sure it still works with old envs.
> :honeybee: Standardise trailing slashes of URL-like envs

- site/SiteNavigationToggle.tsx
We get warnings in the admin dev server.
It seems we don't really need `useLayoutEffect` and can use `useEffect` instead.
https://gist.github.com/gaearon/e7d97cdf38a2907924ea12e4ebdf3c85
> Fix useLayoutEffect warning when server rendering

- packages/@ourworldindata/types/src/gdocTypes/Gdoc.ts
- site/gdocs/pages/AboutPage.tsx
Adds 2 new features to our about pages
1. `hide-nav` in the front-matter, to hide the about page nav
2. `override-title` in the front matter, to support existing About pages, and also the upcoming Privacy Policy page (which needs an actual title)
It's hard to imagine a scenario where we'd want one without the other, but given that they were both trivial to add and we won't be making many of them, I figured it was better to be explicit.
Create a gdoc with the following front-matter:
```
title: My custom about page title
type: about-page
hide-nav: true
override-title: true
```
> ✨ Privacy Policy front-matter

- db/model/Post.ts
- site/ThankYouPage.tsx
Fixes #4543
I didn't find additional pages that should be excluded.
> Exclude thank-you page from indexing

- adminSiteClient/GdocsSettingsForms.tsx
- adminSiteClient/gdocsDeploy.ts
- adminSiteClient/gdocsValidation.ts
- db/model/Gdoc/GdocDataInsight.ts
- packages/@ourworldindata/types/src/gdocTypes/Gdoc.ts
Adds two new properties to the front matter of DIs.
- `narrative-chart` is the name of a narrative chart. It's useful to know which narrative chart a DI is based on, similar to how we track the `grapher-url` a DI is based on.
- `figma-url` is a link to a Figma page. Authors are encouraged to share a Figma link if they customised the chart, but currently paste the link into the comment section of the GDoc. We double-down on Figma as an important piece of infrastructure this cycle, so I think it's justified to track it properly. 
Both properties will be surfaced in a new Data Insights index page we have in mind.
---
This is **part 1 of 9 in a stack** made with GitButler:
- <kbd>&nbsp;9&nbsp;</kbd> #4571 
- <kbd>&nbsp;8&nbsp;</kbd> #4570 
- <kbd>&nbsp;7&nbsp;</kbd> #4558 
- …
> ✨ add narrative-chart and figma-url to DI frontmatter / TAS-850

- adminSiteClient/AdminApp.tsx
- adminSiteClient/AdminSidebar.tsx
- adminSiteClient/DataInsightIndexPage.tsx
- adminSiteClient/admin.scss
- adminSiteClient/gdocsValidation.ts
- adminSiteServer/apiRouter.ts
- adminSiteServer/apiRoutes/dataInsights.ts
- db/model/Gdoc/GdocFactory.ts
- packages/@ourworldindata/grapher/src/chart/ChartUtils.tsx
- packages/@ourworldindata/grapher/src/index.ts
- packages/@ourworldindata/types/src/gdocTypes/Gdoc.ts
- packages/@ourworldindata/types/src/index.ts
- packages/@ourworldindata/utils/src/Util.ts
- packages/@ourworldindata/utils/src/index.ts
Adds an index page for data insights in the admin.
- The /dataInsights endpoint returns all data insights, enriched with information that is surfaced on the index page (e.g. image, topic tags, chart type)
- The index page has a list and gallery layout (top right) and allows to filter by publication status.
- The data insights query assumes the image block comes first
- Because we're now surfacing the `grapher-url`, I added some validation for it. As far as I know, the `grapher-url` should be a valid grapher or explorer link, but maybe I'm forgetting something?
- Search includes the body text. I just grabbed the markdown column for that because it was easiest. What's a little weird about that is that the markdown contains image filenames (and maybe other stuff), which sometimes leads to …
> 🎉 (admin) data insight index page / TAS-845

- adminShared/AdminTypes.ts
- adminSiteClient/AbstractChartEditor.ts
- adminSiteClient/ChartViewEditor.ts
- adminSiteClient/ChartViewEditorPage.tsx
- adminSiteClient/DataInsightIndexPage.tsx
- adminSiteClient/EditorReferencesTab.tsx
- adminSiteClient/ImagesIndexPage.tsx
- adminSiteClient/ReuploadImageForDataInsightModal.tsx
- adminSiteClient/admin.scss
- adminSiteClient/imagesHelpers.ts
- adminSiteServer/apiRouter.ts
- adminSiteServer/apiRoutes/chartViews.ts
- adminSiteServer/apiRoutes/dataInsights.ts
- adminSiteServer/apiRoutes/figma.ts
- adminSiteServer/apiRoutes/images.ts
- package.json
- packages/@ourworldindata/types/src/gdocTypes/Gdoc.ts
- settings/serverSettings.ts
- yarn.lock
Adds affordances for automatically re-uploading data insight images for DIs linked to a narrative chart or to a Figma chart.
- Adds a 'Reupload image' button on the data insight index page
- If a `figma-url` is given, a PNG version of the chart is fetched from Figma and then uploaded
- If a `narrative-chart` name is given, the PNG version of that narrative chart is uploaded as a DI image
- Adds a new section to the Reference tab in the chart editor for narrative charts
- Lists the DIs that use this narrative chart (there should usually only be one)
- Adds an affordance to upload the PNG export of the narrative chart as the Di image
- The [DI index page on staging](http://staging-site-di-automatic-image-upload/admin/dataInsights) lists two test DIs, one with a narrative chart URL and one …
> 🎉 reupload DI images automatically / TAS-831

- adminSiteClient/EditorBasicTab.tsx
Adds an info box for narrative chart editors, including a copy button for the name of a narrative chart.
The copy action is useful for the Figma plugin that expects a narrative chart name as input.
---
This is **part 6 of 9 in a stack** made with GitButler:
- <kbd>&nbsp;9&nbsp;</kbd> #4571 
- <kbd>&nbsp;8&nbsp;</kbd> #4570 
- <kbd>&nbsp;7&nbsp;</kbd> #4558 
- <kbd>&nbsp;6&nbsp;</kbd> #4557 👈 
- <kbd>&nbsp;5&nbsp;</kbd> #4556 
- <kbd>&nbsp;4&nbsp;</kbd> #4547 
- <kbd>&nbsp;3&nbsp;</kbd> #4500 
- <kbd>&nbsp;2&nbsp;</kbd> #4490 
- <kbd>&nbsp;1&nbsp;</kbd> #4489
> 🎉 add info section to the narrative chart editor

- adminShared/AdminTypes.ts
- adminSiteClient/AbstractChartEditor.ts
- adminSiteClient/EditorReferencesTab.tsx
- adminSiteServer/apiRoutes/chartViews.ts
- adminSiteServer/apiRoutes/charts.ts
Adds a section to the Ref tab that lists all data insights that are based on the chart.
---
This is **part 7 of 9 in a stack** made with GitButler:
- <kbd>&nbsp;9&nbsp;</kbd> #4571 
- <kbd>&nbsp;8&nbsp;</kbd> #4570 
- <kbd>&nbsp;7&nbsp;</kbd> #4558 👈 
- <kbd>&nbsp;6&nbsp;</kbd> #4557 
- <kbd>&nbsp;5&nbsp;</kbd> #4556 
- <kbd>&nbsp;4&nbsp;</kbd> #4547 
- <kbd>&nbsp;3&nbsp;</kbd> #4500 
- <kbd>&nbsp;2&nbsp;</kbd> #4490 
- <kbd>&nbsp;1&nbsp;</kbd> #4489
> 🎉 add di section to the chart editor ref tab

- adminSiteClient/CreateDataInsightModal.tsx
I forgot about topic tags!
This PR adds support for tagging DIs on creation in the admin.
---
This is **part 8 of 9 in a stack** made with GitButler:
- <kbd>&nbsp;9&nbsp;</kbd> #4571 
- <kbd>&nbsp;8&nbsp;</kbd> #4570 👈 
- <kbd>&nbsp;7&nbsp;</kbd> #4558 
- <kbd>&nbsp;6&nbsp;</kbd> #4557 
- <kbd>&nbsp;5&nbsp;</kbd> #4556 
- <kbd>&nbsp;4&nbsp;</kbd> #4547 
- <kbd>&nbsp;3&nbsp;</kbd> #4500 
- <kbd>&nbsp;2&nbsp;</kbd> #4490 
- <kbd>&nbsp;1&nbsp;</kbd> #4489
> 🎉 add topic tags input to di creation dialog

- .env.example-full
- adminSiteClient/CreateDataInsightModal.tsx
- adminSiteClient/admin.scss
- adminSiteServer/apiRouter.ts
- adminSiteServer/apiRoutes/slack.ts
- settings/clientSettings.ts
Send a message to the `#data-insights-pitches` channel in Slack on DI creation.
The Slack message includes the title, an optional note and the image (see screenshot).
The idea of having a `#data-insights-pitches` channel is that there is a very early editorial review that decides whether it makes sense to flesh out a data insight.
For testing, set `SLACK_DI_PITCHES_CHANNEL_ID` to the ID of the `#data-insights-pitches` channel (I just added you to the channel). The secret key for `SLACK_BOT_OAUTH_TOKEN` is in 1password.
The env var isn't set on staging yet, so it's currently only testable locally. I'll figure this out tomorrow, but I wanted to open up for review anyway.
<details><summary>Screenshot</summary>
<p>
</p>
</details> 
---
This is **part 9 of 9 in a stack** made with GitButler:
- …
> 🎉 share newly created DIs in Slack

- adminSiteClient/AbstractChartEditor.ts
- adminSiteClient/EditorDataTab.tsx
- adminSiteClient/EditorMarimekkoTab.tsx
- adminSiteClient/EditorScatterTab.tsx
- adminSiteClient/admin.scss
- packages/@ourworldindata/core-table/src/OwidTable.ts
- packages/@ourworldindata/explorer/src/Explorer.tsx
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/scatterCharts/ScatterPlotChart.tsx
- packages/@ourworldindata/grapher/src/scatterCharts/ScatterPlotChartConstants.ts
- packages/@ourworldindata/grapher/src/selection/SelectionArray.ts
- packages/@ourworldindata/grapher/src/stackedCharts/MarimekkoChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/MarimekkoChartConstants.ts
Allows to exclude entities for all chart types (used to be supported for Scatter and Marimekko only).
Entity exclusion is similar to the author's timeline filter in the sense that it should seem like the excluded entities simply don't exist, so the entity exclusion runs as early as the author timeline filter.
> 🎉 support entity exclusion for all chart types

- adminSiteClient/AdminApp.tsx
- adminSiteClient/AdminSidebar.tsx
- adminSiteClient/ChartViewIndexPage.tsx
- adminSiteClient/ImagesIndexPage.tsx
- adminSiteClient/MultiDimIndexPage.tsx
- adminSiteServer/apiRouter.ts
- adminSiteServer/apiRoutes/charts.ts
- adminSiteServer/apiRoutes/mdims.ts
- adminSiteServer/chartConfigHelpers.ts
- adminSiteServer/multiDim.ts
- adminSiteServer/validation.ts
- db/model/Gdoc/GdocBase.ts
- db/model/MultiDimDataPage.ts
- db/model/MultiDimXChartConfigs.ts
- package.json
- packages/@ourworldindata/types/src/dbTypes/ChartConfigs.ts
- packages/@ourworldindata/types/src/domainTypes/Various.ts
- serverUtils/serverUtil.tsx
- yarn.lock
Resolves #4458
ETL path and a new/changed admin API will be in a follow-up PR.
> Add admin for multidimensional data pages

- adminSiteServer/apiRoutes/mdims.ts
- baker/SiteBaker.tsx
- settings/clientSettings.ts
It should be safe to remove the feature flag when this stack is merged. I want to make it easier for data managers to play with the feature on their staging servers.
In the next PR of the stack I'll introduce the `catalogPath` and a new API for ETL.
> Remove MultiDimDataPage feature flag

- adminSiteClient/MultiDimIndexPage.tsx
- adminSiteServer/adminRouter.tsx
- adminSiteServer/apiRouter.ts
- adminSiteServer/apiRoutes/mdims.ts
- adminSiteServer/app.test.ts
- adminSiteServer/multiDim.ts
- adminSiteServer/validation.ts
- baker/MultiDimBaker.tsx
- db/migration/1738919205864-AddCatalogPathToMultiDim.ts
- db/model/MultiDimDataPage.ts
- packages/@ourworldindata/types/src/dbTypes/MultiDimDataPages.ts
- packages/@ourworldindata/types/src/siteTypes/MultiDimDataPage.ts
- site/multiDim/MultiDimDataPage.tsx
- site/multiDim/MultiDimDataPageContent.tsx
* Catalog path will now be the main ID used by ETL
* It's temporarily allowed to be null; we'll disallow that once existing
data is migrated
* Slug is now allowed to be null, since it will be only set in admin at
some point
* For that reason we'll use the catalog path as a slug for previews of
mdims in the admin, i.e. `/admin/grapher/{catalogPath}`
> Add catalogPath to mdims

- packages/@ourworldindata/grapher/src/core/Grapher.tsx
the full screen button is sometimes hidden when going into full-screen doesn't make a big difference or even makes the experience worse
but we should only hide the full screen button on smaller screens. it's weird if it's missing on desktop
> 🐛 hide full-screen button on small screens only

- packages/@ourworldindata/grapher/src/lineCharts/LineChart.tsx
- packages/@ourworldindata/grapher/src/slopeCharts/SlopeChart.tsx
- packages/@ourworldindata/utils/src/Util.ts
Disables focus mode on touch devices since users can easily accidentally end up in a focus state not being able to reset since they don't know how (I've seen this happen in session replays)
> ✨ disable focus on touch devices

- adminSiteServer/apiRoutes/misc.ts
- db/db.ts
- db/migration/1739788202649-PostsGdocsIndexes.ts
- db/model/Gdoc/GdocBase.ts
- db/model/Gdoc/GdocFactory.ts
- db/model/Post.ts
- packages/@ourworldindata/types/src/dbTypes/PostsGdocs.ts
This PR does a few things to the `posts_gdocs` table:
- Add a composite index on `type, published, publishedAt`
- These sorts of queries are very common, e.g. `WHERE type = "data-insight" AND published = 1 AND publishedAt <= NOW()`
- Also, it can be used on queries that _just_ filter on `type`
- Add another composite index on `published, publishedAt`
- Again, filtering on `published` is very common
- Convert the computed column `type` from `VIRTUAL` to `STORED`
- Add a computed stored column on `content ->> "$.authors`"
- This allows us to filter on them [without running out of MySQL sort memory](https://github.com/owid/owid-grapher/pull/4545#discussion_r1955835992)
- Add a composite index on `posts_gdocs_links (linkType, componentType)`, to aid filtering for `linkType = 'grapher'`
I …
> enhance(mysql): add better indexes for `posts_gdocs` table

- adminSiteClient/EditorBasicTab.tsx
- adminSiteClient/EditorDataTab.tsx
- packages/@ourworldindata/explorer/src/Explorer.tsx
- packages/@ourworldindata/grapher/src/barCharts/DiscreteBarChart.test.ts
- packages/@ourworldindata/grapher/src/controls/entityPicker/EntityPicker.tsx
- packages/@ourworldindata/grapher/src/controls/entityPicker/EntityPickerConstants.ts
- packages/@ourworldindata/grapher/src/core/Grapher.jsdom.test.ts
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/selection/SelectionArray.test.ts
- packages/@ourworldindata/grapher/src/selection/SelectionArray.ts
- packages/@ourworldindata/grapher/src/slopeCharts/SlopeChart.test.ts
- packages/@ourworldindata/types/src/domainTypes/CoreTableTypes.ts
- packages/@ourworldindata/types/src/index.ts
I tripped over the `availableEntities` of Grapher's selection in the last PR and wondered if it makes sense for the SelectionArray to manage both, the selected and the available entities.
I don't have a strong opinion but I am in slight favour of removing the available entities from the SelectionArray. I don't see a compelling reason for them to be part of the SelectionArray interface, and the fact that the available entities need to be kept up-to-date is a potential foot gun.
I also wonder if we could unify SelectionArray and FocusArray now that both essentially do the same thing (manage a selection).
Feel free to stop me – again, no strong opinion from my side.
> 🔨 remove availableEntities from SelectionArray

- db/model/Post.ts
- site/dataPage.ts
I noticed that we have this very complex query hanging around, which isn't really delivering any insightful results at this point.
You can find all the results this can ever find [over here, in this slightly adapted query](http://analytics/private?sql=--+What+we+want+here+is+to+get+from+the+variable+to+the+charts%0D%0A++++++++++++--+to+the+posts+and+collect+different+pieces+of+information+along+the+way%0D%0A++++++++++++--+One+important+complication+is+that+the+slugs+that+are+used+in+posts+to%0D%0A++++++++++++--+embed+charts+can+either+be+the+current+slugs+or+old+slugs+that+are+redirected%0D%0A++++++++++++--+now.%0D%0A++++++++++++SELECT+DISTINCT%0D%0A++++++++++++++++pl.target+AS+linkTargetSlug%2C%0D%0A++++++++++++++++COALESCE%28csr.slug%2C+cc.slug%29+AS+chartSlug%2C%0D%0A++++++++++++++++p.t …
> cleanup: don't query WP for related research posts

- packages/@ourworldindata/grapher/src/entitySelector/EntitySelector.tsx
This one is super straightforwad, I just thought it would be way cleaner if these values didn't live directly on the `SearchableEntity` object but somewhere below it.
These sort values are used for the "Sort by" functionality in the entity selector. I've tested things and it continues to work well.
> refactor(entitySelector): move sort values to own object

- site/gdocs/components/KeyInsights.scss
- site/gdocs/components/KeyInsights.tsx
We were overriding h4 style in Grapher download modal.
Fixes #3872
> Fix style leak in KeyInsights

- devTools/regionsUpdater/update.ts
- packages/@ourworldindata/grapher/src/entitySelector/EntitySelector.tsx
- packages/@ourworldindata/utils/src/FuzzySearch.test.ts
- packages/@ourworldindata/utils/src/FuzzySearch.ts
- packages/@ourworldindata/utils/src/Util.ts
- packages/@ourworldindata/utils/src/index.ts
- packages/@ourworldindata/utils/src/regions.json
- packages/@ourworldindata/utils/src/regions.ts
Resolves #4256, supersedes #4352.
Note: review #4621 first.
This PR makes use of the [Intl.DisplayNames](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames) (caniuse: 95% support, all major modern browsers), which can have the browser provide translations to country names into all languages.
How this works:
- Using `navigator.languages`, we find out all *non-English* language codes that the user's browser is set to
- Example: for me, `navigator.languages` is `['en', 'de', 'de-DE', 'en-GB', 'en-US']`, and so the non-English ones are `de, de-DE`.
- We then use `Intl.DisplayNames` to generate alternative names for each entity, at least if it matches a region in `regions.json` and has a `shortCode` attached to it.
- These alternative names also …
> feat(entitySelector): allow searching for entities in multiple languages

- adminSiteServer/app.test.ts
- db/migration/1740690097502-CreatedAtNotNull.ts
- db/model/Gdoc/GdocFactory.ts
- packages/@ourworldindata/types/src/dbTypes/PostsGdocs.ts
_inspired by https://github.com/owid/owid-grapher/pull/4567_
Removed the possibility to manually update `createdAt` and `updatedAt` dates in `serializePostsGdocsRow()`. These dates should only be handled by the DB and not at the application level.
- `createdAt` is set on row creation (and never needs to be updated)
- `updatedAt` is updated on row update by the DB
Also removed nullability for `createdAt` in the DB, to properly reflect this assumption in the application code.
1. Create a new Gdoc and verify that `createdAt` is automatically set by the database
2. Update an existing Gdoc and confirm that `updatedAt` is automatically updated
(nothing has changed on that front, that was already the case)
> refactor: remove createdAt and updatedAt from insertable properties

- packages/@ourworldindata/grapher/src/lineCharts/LineChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedAreaChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedBarChart.tsx
if the x-axis is not time, then it's shown in the tooltip
> ✨ add x-axis label to tooltips

- db/model/Chart.ts
- package.json
- yarn.lock
OpenAI allows us to provide a Zod schema, to which it will adhere in its response ([Structured Outputs](https://platform.openai.com/docs/guides/structured-outputs)).
This allows us to get rid of quite some parsing and validation logic :)
I also updated the model used to `gpt-4o`, which is both [quite a bit cheaper](https://platform.openai.com/docs/pricing) and more capable (not that it really matters).
> enhance: use Structured Outputs for OpenAI topic suggestions

- settings/serverSettings.ts
It's never used anywhere, so I thought we could just get rid of it.
> cleanup: remove `CATALOG_PATH`

- site/gdocs/components/LatestDataInsights.tsx
Previously the whole text content of the card, including the description, was used as the label for the link in a screen reader.
> Fix accessibility of DataInsightCard

- adminSiteClient/EditorBasicTab.tsx
- adminSiteClient/EditorFeatures.tsx
- db/migration/1741164615077-DropMapTabForScatterPlots.ts
We have very few scatter plots that come with a map tab, but there is no indication of whether the x or y variable is plotted ([example](https://ourworldindata.org/grapher/energy-use-per-capita-vs-co2-emissions-per-capita?tab=map)). Fiona suggested to remove the map tab for all those scatters.
Below is the list of scatters that currently come with a map tab. I checked for references manually in the chart editor. The first four charts had references at all and for those I scrolled through all articles to make sure the map view is not embedded anywhere.
There are four more chart configs with this issue that seem to be used in mdims, so I left them as is for now and only dropped the map tab for stand-alone grapher charts.
[https://admin.owid.io/admin/charts/1699/edit](https://admin.owid.io/ad …
> 🔨 drop map tab for scatter plots / TAS-916

- baker/DeployUtils.ts
Memoize `getSlackMentionByEmail` to avoid rate limiting. If this keeps happening, we can also fetch email -> slack mapping from `users` table.
> :bug: Memoize email to user lookup from Slack

- package.json
- site/gdocs/components/ArticleBlock.tsx
- site/gdocs/components/BlockErrorBoundary.tsx
- yarn.lock
This way we get also the React component stack attached to the error in Sentry.
> Switch to ErrorBoundary from Sentry

- adminSiteClient/EditorBasicTab.tsx
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
Invalid dimensions lead to an infinite loop where variables are loaded again and again in the admin
~This appears to be fixed in the Grapher state refactor, so I'm closing this one down.~ Might still makes sense to fix this now since the refactor only ships in 6 to 8 weeks?
Example: [live](https://admin.owid.io/admin/charts/1250/edit) / [staging](http://staging-site-fix-admin-infinite-loading/admin/charts/1250/edit)
> 🐛 (admin) prevent infinite loop when loading variables / TAS-859

- Makefile
- adminSiteServer/multiDim.ts
- baker/MultiDimBaker.tsx
- baker/algolia/configureAlgolia.ts
- baker/algolia/indexExplorerViewsMdimViewsAndChartsToAlgolia.ts
- baker/algolia/utils/charts.ts
- baker/algolia/utils/explorerViews.ts
- baker/algolia/utils/mdimViews.ts
- db/model/MultiDimDataPage.ts
- packages/@ourworldindata/utils/src/index.ts
- packages/@ourworldindata/utils/src/multiDim.ts
- site/DataCatalog/DataCatalogUtils.ts
- site/search/ChartHit.tsx
- site/search/searchTypes.ts
> Add multi-dims to data catalog

- packages/@ourworldindata/grapher/src/core/Grapher.tsx
Resolves https://github.com/owid/owid-grapher/issues/4612
The 'About this data' tabs used to be sorted alphabetically, but we prefer the author-specified sort order. The same is true for the columns used for sorting in the entity selector.
<details><summary>Screenshots</summary>
<p>
</p>
</details>
> ✨ don't sort columns used in the About this data modal and the entity selector

- .github/actions/build-tsc/action.yml
- .github/actions/setup-node-yarn-deps/action.yml
- .github/workflows/check-default-grapher-config.yml
- .github/workflows/ci.yml
- .github/workflows/prettify.yml
- .github/workflows/sync-grapher-schema-to-digital-ocean.yml
- settings/clientSettings.ts
- site/viteConstants.ts
- site/viteUtils.tsx
- vite.config-admin.mts
- vite.config-common.mts
- vite.config-site.mts
Improves CI speed & accuracy by:
- Only running things like `buildLerna` and `buildTsc` when they're actually needed!
- splitting out typecheck, prettier, and test into three separate, parallel tasks
> chore(ci): split up & speed up CI tasks

- site/search/Autocomplete.tsx
- site/search/searchTypes.ts
Fixes a path that I overlooked in https://github.com/owid/owid-grapher/pull/4541
1. Check this code out locally, or on staging
2. Attempt the following searches on the homepage
1. `blueberries` - data insight
2. `sustainable` - SDG
3. `optimism` - article
4. `life expectancy` - chart
5. `mpox` - explorer view
6. `privacy` - WordPress "other" page
7. `vatican` - Country profile page
All results should load correctly (team pages don't need to be verified as they aren't indexed)
> 🐛 fix gdoc page subdirectories not prepended to Autocomplete results

- .env.archive
- serverUtils/instrument.ts
- settings/clientSettings.ts
- settings/loadDotenv.ts
- settings/serverSettings.ts
- site/viteUtils.tsx
This PR allows specifying, e.g., `PRIMARY_ENV_FILE=.env.archive yarn tsx ./baker/archival/archiveChangedGrapherPages.ts`.
`PRIMARY_ENV_FILE` loads the specified env file as the _primary_ file, but still always loads `.env` and uses it for anything that's not explicitly overridden in `PRIMARY_ENV_FILE`.
> refactor: allow loading multiple .env files

- settings/clientSettings.ts
- site/cookiePreferences.ts
- site/instrument.ts
- site/runSiteFooterScripts.tsx
- vite.config-common.mts
When the `ARCHIVE` env var is set, we disable initializing Sentry, and will likewise disable cookie-based GA4 and the cookie notice.
The Sentry code (or, at the very least, part of it) is completely stripped from the bundled JS.
> feat(archive): disable sentry & cookie-based tracking

- package.json
- yarn.lock
Updates wrangler, whose out-of-date warning was tripping up our buildkite script that checked for errors:
https://github.com/owid/ops/blob/62eadad331da553daf95b4ff327f56afb8610ec5/templates/common.sh#L449-L457
> 🔨 Update wrangler to ^4.0.0

- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/modal/DownloadModal.tsx
Forces a local data download for archived pages, rather than a server-based one.
Also, it does the same for Mdims for now: until #4656 is fixed.
> feat(archive): force local data download

- devTools/svgTester/utils.ts
When working with the SVG tester, it is sometimes not clear what changed from looking at the pictures. It can then be helpful to look at the text diff, but this is not straightforward since the SVGs are on a single line.
This PR prettifies SVGs before comparison. The SVG tester doesn't fail on this branch because it prettifies both, the original and the new one, and then compares them.
We should update the SVG tester anyway because of the `includedEntities` -> `includedEntityNames` change, so I'll do that after merging this PR.
---
⧓ Review in [Butler Review `#7TLklK152`](https://gitbutler.com/sophiamersmann/owid-grapher/reviews/7TLklK152)
**🐝 prettify SVG files**
1 commit series (version 1)
| Series | Commit Title | Status | Reviewers | 
| --- | --- | --- | --- |
| 1/1 | [🐝 prettify SVG …
> 🐝 (svg tester) prettify SVG files

- packages/@ourworldindata/grapher/src/mapCharts/MapSparkline.tsx
For map sparklines, the top grid line should always be the max value, not a 'nice' tick value
> 🐛 disable nice ticks for map sparklines

- adminSiteClient/MultiDimIndexPage.tsx
Slug can now be null after we introduced catalogPath as the main ID used in ETL. I forgot to handle that in admin when I made the change previously.
Fixes ADMIN-4J
> Handle mdim slug being null in admin

- packages/@ourworldindata/grapher/src/core/Grapher.jsdom.test.ts
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
This should fix the SVG diffs present in #4419, hopefully.
Reason being that `legacyConfigAsAuthored.minTime == undefined`, whereas `authorsVersion.minTime == -Infinity` (since it's explicitly set in the `GrapherState#constructor -> updateFromObject` call).
You _explicitly_ changed this in the PR - maybe to circumvent some sort of circular dependency that occurred at some point? Anyhow, it seems this is now safe to do.
Decided to add a test for it, too, for which I had to make the getter public.
> fix(grapher refactor): fix time param handling

- baker/algolia/utils/pages.ts
Fixes `indexIndividualGdocPost` indexing posts that were scheduled for the future, which was causing not-live posts to show up in search
> 🐛 fix indexing scheduled gdoc posts

- site/SiteFooter.tsx
- site/SiteResources.tsx
We've updated the title of the [/teaching page](https://ourworldindata.org/teaching) and need to update the site nav links to it also.
> ✨ update "Teaching Materials" -> "Teaching With OWID"

- adminSiteClient/admin.entry.ts
- devTools/project-dependencies.md
- eslint.config.mjs
I forgot `explorerAdminClient/ExplorerCreatePage.scss` in there which caused build error
```
error during build:
--
  | Could not resolve "../explorerAdminClient/ExplorerCreatePage.scss" from "adminSiteClient/admin.entry.ts"
  | file: /home/owid/owid-grapher/adminSiteClient/admin.entry.ts
  | at getRollupError (file:///home/owid/owid-grapher/node_modules/rollup/dist/es/shared/parseAst.js:397:41)
  | at error (file:///home/owid/owid-grapher/node_modules/rollup/dist/es/shared/parseAst.js:393:42)
  | at ModuleLoader.handleInvalidResolvedId (file:///home/owid/owid-grapher/node_modules/rollup/dist/es/shared/node-entry.js:21111:24)
  | at file:///home/owid/owid-grapher/node_modules/rollup/dist/es/shared/node-entry.js:21071:26
  | 🚨 Error: The command exited with status 1
```
> :bug: fix error with ExplorerCreatePage.scss

- adminSiteClient/DataInsightIndexPage.tsx
Fixes an [issue Saloni's been encountering](https://our-world-in-data.sentry.io/issues/34514650/?alert_rule_id=119552&alert_type=issue&environment=production&notification_uuid=4baf4420-b103-4fdf-9725-68756196d1d7&project=4508607592464464&referrer=slack) where a second attempt to update an image would fail, due to a DB collision.
**The broken flow:**
1. Image with ID 1 exists in the DB
2. Update image from Figma via a PUT to `/api/images/1`
3. DB adds new image data as image with ID 2
4. Client doesn't update the ID
5. Update image from Figma again, via a PUT to `/api/images/1`
6. DB throws error
**Fix**
Update the ID of the image in the client as well, so that the second update will PUT to `/api/images/2`
> 🐛 update data insight image ID in place after uploading a new version

- functions/donation/_utils/checkout.ts
When we don't specify `payment_method_types` Stripe will pick and order them dynamically for us based on the allowed payment methods configured in the dashboard, customer location, currency etc.
https://docs.stripe.com/payments/payment-methods/dynamic-payment-methods
You can test this with a local dev Stripe setup and a VPN.
> Switch Stripe to dynamic payment methods

- adminSiteClient/EditorBasicTab.tsx
- packages/@ourworldindata/core-table/src/CoreTableColumns.ts
- packages/@ourworldindata/grapher/src/controls/Dropdown.scss
- packages/@ourworldindata/grapher/src/controls/Dropdown.tsx
- packages/@ourworldindata/grapher/src/controls/MapProjectionMenu.scss
- packages/@ourworldindata/grapher/src/controls/globalEntitySelector/GlobalEntitySelector.tsx
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/core/GrapherConstants.ts
- packages/@ourworldindata/grapher/src/core/grapher.scss
- packages/@ourworldindata/grapher/src/core/typography.scss
- packages/@ourworldindata/grapher/src/entitySelector/EntitySelector.scss
- packages/@ourworldindata/grapher/src/entitySelector/EntitySelector.tsx
- packages/@ourworldindata/grapher/src/index.ts
- packages/@ourworldindata/utils/src/Util.ts
- packages/@ourworldindata/utils/src/index.ts
Sort entities in Grapher's entity selector by the values of the currently selected year, rather than by the latest data point available for an entity
I also refactored some bits around externally loaded sort columns.
- We need to interpolate with tolerance so that the chart data and the entity selector data is consistent
- We do so on demand, i.e. only when a column is selected. Alternatively, we could apply tolerance to all columns of the `tableForSelection` but that's potentially expensive since we would apply tolerance to all columns of an unfiltered table with all available entities. That's not really worth it since most users don't use the Sort by option in the entity selector
- Infinite tolerance is applied to the externally loaded indicators (population, GDP per capita) 
- …
> ✨ (entity selector) sort by current values / TAS-932

- adminSiteClient/EditorBasicTab.tsx
- adminSiteClient/EditorFeatures.tsx
Re-enabling to make it possible to remove a map tab when it's enabled for a scatter plot.
> ✨ re-enable map tab tickbox for scatters

- packages/@ourworldindata/components/src/Button/Button.scss
- packages/@ourworldindata/components/src/Button/Button.tsx
When we recently changed how icons in `Button` work, we introduced this additional margin when there is no icon.
> Fix margin of Button without icon

- site/DataPageContent.scss
- site/TopicTags.scss
- site/multiDim/MultiDimDataPageContent.scss
- site/multiDim/MultiDimDataPageContent.tsx
- site/multiDim/MultiDimDataPageSettingsPanel.scss
- site/multiDim/MultiDimDataPageSettingsPanel.tsx
As [requested by Marwa](https://owid.slack.com/archives/C03NV9Z3YSV/p1742999075475339).
* Implement original mobile design typography
* Fix spacing in multidimensional data page
Fixes #4232
> Tweak data page header

- Makefile
- adminSiteClient/DatasetEditPage.tsx
- adminSiteServer/adminRouter.tsx
- adminSiteServer/apiRoutes/datasets.ts
- db/exportMetadata.ts
- db/migration/1743576697066-RemoveDatasetFilesTable.ts
- packages/@ourworldindata/types/src/dbTypes/DatasetFiles.ts
- packages/@ourworldindata/types/src/index.ts
Table `dataset_files` was historically used for downloading a zipped version of a dataset. It hasn't been used for years and the table is empty in production.
I also smuggled in a safeguard to prevent `make refresh` from running when `ENV=production`.
> :broom: Remove dataset_files table

- packages/@ourworldindata/grapher/src/mapCharts/ChoroplethMap.tsx
Changes the way we calculate a country's stroke width depending on viewport scale.
According to the [transform matrix docs](https://developer.mozilla.org/en-US/docs/Web/SVG/Reference/Attribute/transform#matrix) (relevant in this formula: `a` and `d`), we're multiplying both x and y dimensions by `viewportScale`.
This, in turn, means that the right way to scale something in an area-preserving way is to use the square root of `viewportScale`.
All screenshots taken in Firefox. You can see a stark difference at 300% and 400%.
| Zoom level | Live | This PR |
|--------|--------|--------|
| 50% | ![CleanShot 2025-04-02 at 17 41 12](https://github.com/user-attachments/assets/ecd10b42-d5f9-4de2-9ed7-8e8aeed075b5) | ![CleanShot 2025-04-02 at 17 41 …
> enhance(maps): scale country outline stroke in an area-preserving way

- packages/@ourworldindata/utils/src/Util.ts
This way we avoid one redirect request, which was slowing down the loading of the donate form, where we recently started using country detection.
> Avoid a redirect when detecting user's country

- adminSiteServer/appClass.tsx
- baker/DeployUtils.ts
- settings/serverSettings.ts
A lot of staging servers were failing in `getEmailSlackMentionsMap`, causing their deploy queues to run indefinitely. This happened because we used `SLACK_BOT_OAUTH_TOKEN` to detect staging servers—but we recently added that token to staging servers as well.
Fortunately, our staging servers now finally use `ENV=staging`, so we can clean up these hacks for good. 🎉
(I’ve deleted all `.pending` files on staging servers to unstuck the queues.)
> :bug: Fix stuck deploy queue on staging servers

- baker/SiteBaker.tsx
- baker/countryProfiles.tsx
Buildkite uses special syntax where --- marks a start of the group in the output of a build. We were using it to mark an end of the group, making the rendered HTML collapsible sections confusing in the Builkite UI.
See the output of the Buildkite build for this PR.
> Fix Buildkite output groups

- Makefile
- baker/GrapherBaker.tsx
- baker/archival/ArchivalBaker.ts
- baker/archival/archivalChecksum.ts
- baker/archival/archivalUtils.ts
- package.json
- packages/@ourworldindata/components/src/Button/Button.scss
- packages/@ourworldindata/components/src/Button/Button.tsx
- site/DataPageV2.tsx
- site/GrapherPage.tsx
- site/SiteHeader.tsx
- site/SiteLogos.tsx
- site/archive/ArchiveSiteNavigation.scss
- site/archive/ArchiveSiteNavigation.tsx
- site/archive/archiveTypes.ts
- site/owid.scss
- site/viteConstants.ts
- vite.config-archive.mts
This introduces a banner & navigation bar to archived pages.
[Figma](https://www.figma.com/design/0bSkR5nTebL69w8O6upNWd/Archival-Embeds?node-id=1-35&t=scrct9M2QpRichKL-1)
See a live demo over at http://staging-site-archive-navigation-banner:3000/latest/grapher/life-expectancy.
You can also run an archive step locally by running `make archive`.
> feat(archive): archive banner & navigation links

- site/SiteMobileArea.tsx
- site/SiteMobileMenu.tsx
- site/SiteNavigationTopics.tsx
I noticed a bunch of warnings for null React keys.
IDs make for better keys than slugs do, anyhow :)
> fix(nav): use non-null react keys

- packages/@ourworldindata/components/src/styles/mixins.scss
Reported being too cramped by Marcel with Chrome on macOS with non-retina external display.
[Slack discussion](https://owid.slack.com/archives/C03NV9Z3YSV/p1744373674034099).
> Fix detail on demand underline offset

- baker/archival/ArchivalBaker.ts
- baker/archival/archiveChangedGrapherPages.ts
- db/model/Chart.ts
- ops/buildkite/deploy-archive
- package.json
This is the code to enable future archive deploys.
You can find the content that would be going up to the R2 bucket on http://staging-site-archive-deploy:3000, e.g. over at http://staging-site-archive-deploy:3000/latest/grapher/life-expectancy.
That archive dir over there was created using the `deploy-archive` script. I haven't tested the `rclone copy` command yet, because on the staging server the token doesn't have the right permissions. We can test it properly once we set up a Buildkite step on live for this, early next week.
> feat(archive): deploy archive script

- adminSiteClient/imagesHelpers.ts
- functions/package.json
- package.json
- yarn.lock
Basically reverts 1f6c0442f04ef6b8e787a5ae92b9ff24cb79fb31, which we don't need to be doing any longer.
> chore(deps): un-pin `@types/node`

- devTools/tsconfigs/tsconfig.base.json
We unpinned @types/node in 7cdfffd9cb879948018244780ca5aa4a74b80693, so we no longer need to use only ESNext.Collection.
> Remove outdated workaround in tsconfig.base.json

- baker/siteRenderers.tsx
- site/DataInsightsIndexPage.tsx
- site/DataInsightsIndexPageContent.tsx
- site/NewsletterSubscription.tsx
- site/SiteConstants.ts
- site/gdocs/components/DataInsightsNewsletter.tsx
- site/gdocs/components/LatestDataInsights.tsx
- site/gdocs/components/LatestDataInsightsBlock.tsx
- site/gdocs/pages/DataInsight.tsx
Starting next week, we'll send our data insights three times per week. I've adapted the copy throughout the site to remove the word "daily" and replace "every weekday" with "every few days".
I _think_ I've identified all instances, but it's probably worth double-checking whether I've missed some or maybe other relevant words/sentences.
> Fix copy for data insights

- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- site/gdocs/components/Chart.tsx
- site/multiDim/MultiDim.scss
- site/multiDim/MultiDim.tsx
- site/multiDim/MultiDimDataPageContent.scss
- site/multiDim/MultiDimDataPageContent.tsx
- site/multiDim/MultiDimDataPageSettingsPanel.tsx
- site/multiDim/api.ts
- site/multiembedder/MultiEmbedder.tsx
- site/owid.scss
We now embed a multi-dim chart with controls by default and hide the controls if the URL contains `hideControls=true` (same as for explorer).
This is a prototype to inform the design of the component. We currently don't have finalized designs to follow, so the implementation is minimal.
Resolves #4741
You can try the component in various ArchieML contexts (see [my testing doc](https://docs.google.com/document/d/1XFA35qElj_sV42sEk6s3fL9QfD23ZMsV2oYIrwPb_lE/edit?tab=t.0)), but since this is a prototype, thorough QA is not necessary.
> Add prototype for embedding multi-dim with controls

- packages/@ourworldindata/utils/src/urls/Url.test.ts
complements #4736
Added tests for the `areQueryParamsEqual` method in the `Url` class to ensure proper comparison of URL query parameters.
> test: add tests for areQueryParamsEqual

- adminSiteClient/FeaturedMetricsPage.tsx
- baker/algolia/configureAlgolia.ts
- baker/algolia/indexExplorerViewsMdimViewsAndChartsToAlgolia.ts
- baker/algolia/utils/charts.ts
- baker/algolia/utils/explorerViews.ts
- baker/algolia/utils/mdimViews.ts
- baker/algolia/utils/shared.ts
- baker/algolia/utils/types.ts
- db/db.ts
- packages/@ourworldindata/utils/src/regions.ts
- packages/@ourworldindata/utils/src/urls/Url.test.ts
- packages/@ourworldindata/utils/src/urls/Url.ts
- site/DataCatalog/DataCatalogUtils.ts
- site/search/ChartHit.tsx
- site/search/searchTypes.ts
Resolves https://github.com/owid/owid-grapher/issues/4677
- Improves validation and error messages in the Featured Metrics admin to ensure URLs with grapher-specific query strings aren't added
- Adds a `areQueryParamsEqual` method to the `Url` class to allow for smart comparisons of URLs
- e.g. `blah.com?a=a&b=b === blah.com?b=b&a=a // true`
- Adds an `id` property to all of the records that we index to `explorer-views-and-charts`
- This property is used in `attributeForDistinct`, so that only one record per `id` can be returned
- Adds an optional `originalAvailableEntities` property to these records
- Adds a `createFeaturedMetricRecords` function
- Takes the records about to be indexed
- For each featured metric, it finds the corresponding record
- Duplicates it
- Increases its score, …
> 🎉 Featured metric indexing

- adminSiteServer/apiRoutes/variables.ts
- baker/archival/ArchivalBaker.ts
- db/model/Variable.ts
- packages/@ourworldindata/grapher/src/core/loadVariable.ts
- site/DataPageV2.tsx
- site/GrapherPage.tsx
I ran into an issue where we'd freshly archive a variable, but end up with the previous version of the metadata file.
I hope this fixes it 🤞🏻
> fix(archive): skip variable cache when archiving them

- baker/archival/ArchivalBaker.ts
- baker/archival/archivalChecksum.ts
- baker/archival/archiveChangedGrapherPages.ts
- packages/@ourworldindata/types/src/domainTypes/Archive.ts
- packages/@ourworldindata/types/src/index.ts
- site/SiteHeader.tsx
- site/archive/ArchiveSiteNavigation.tsx
- site/runSiteFooterScripts.tsx
Enables going forward in time with the "Go to next version" button.
It is powered by a client-side fetch of the `/versions/charts/[chartId].json` file.
> feat(archive): allow navigating to next version

- adminSiteClient/AbstractChartEditor.ts
- adminSiteClient/EditorDataTab.tsx
- packages/@ourworldindata/core-table/src/OwidTable.ts
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/core/LegacyToOwidTable.test.ts
- packages/@ourworldindata/grapher/src/dataTable/DataTable.test.tsx
To my surprise, I found out that computing `OwidTable.availableEntities` takes 80ms on my machine for https://ourworldindata.org/grapher/covid-daily-vs-total-cases-per-million - when in reality we only ever need the entity name.
A next step would be to remove `entityCode` and possibly `entityId` entirely from OwidTable, since there's not much of a use to it at this point. `entityCode` could be useful in data downloads, though.
> cleanup(table): get rid of unnecessary `availableEntities`

- packages/@ourworldindata/components/src/markdown/remarkPlainLinks.test.ts
- packages/@ourworldindata/components/src/markdown/remarkPlainLinks.ts
Makes the URL regex a bit less restrictive, so it also allows detecting the following two types of URLs (e.g. in the citations section on a data page):
- http://staging-site-url-regex
- http://localhost:3030
I've also added a bunch of tests for the regex!
> enhance(markdown): detect more types of links

- packages/@ourworldindata/core-table/src/CoreTable.ts
- packages/@ourworldindata/core-table/src/CoreTableUtils.test.ts
- packages/@ourworldindata/core-table/src/CoreTableUtils.ts
- packages/@ourworldindata/core-table/src/OwidTable.ts
- packages/@ourworldindata/grapher/src/color/ColorScale.ts
- packages/@ourworldindata/grapher/src/scatterCharts/ScatterPlotChart.tsx
- packages/@ourworldindata/types/src/domainTypes/CoreTableTypes.ts
- packages/@ourworldindata/utils/src/Util.ts
I found a good bunch of optimizations that we can apply to make core table methods more performant, especially for the our worst offender charts.
| Method                               | URL                                                                                   | Before: longest single call | Before: overall time | After: longest single call | After: overall time |
|--------------------------------------|---------------------------------------------------------------------------------------|-----------------------------|----------------------|----------------------------|---------------------|
| rowIndex                             | [covid-19-cumulative-confirmed-cases-vs-confirmed-deaths](http://localhost:3030/grapher/covid-19-cumulative-confirmed-cases-vs-confirmed-deaths) | …
> perf(table): core table performance improvements

- packages/@ourworldindata/components/src/Checkbox.tsx
- packages/@ourworldindata/components/src/RadioButton.tsx
- packages/@ourworldindata/explorer/src/Explorer.tsx
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/core/relatedQuestion.ts
- packages/@ourworldindata/grapher/src/index.ts
- packages/@ourworldindata/grapher/src/modal/EmbedModal.scss
- packages/@ourworldindata/grapher/src/modal/EmbedModal.tsx
- site/multiDim/MultiDim.scss
- site/multiDim/MultiDim.tsx
- site/multiDim/MultiDimDataPage.tsx
- site/multiDim/MultiDimDataPageContent.tsx
- site/multiembedder/MultiEmbedder.tsx
- site/runSiteFooterScripts.tsx
This is a prototype of an external mdim embed. The final design might be different.
Resolves #4775.
`<iframe>` of the same mdim in a blank HTML page, with and without controls:
Test that the iframe behaves correctly. And since I also changed the mdim data page implementation, testing that would be appreciated too.
> Add support for external multi-dim embeds

- site/AboutThisData.scss
Currently the markdown on datapages has default styles applied to links:
https://ourworldindata.org/grapher/total-population-in-extreme-poverty?tab=chart&time=2010..latest&focus=&country=~OWID_WRL
> ✨ use correct link colour in datapage key info

- packages/@ourworldindata/grapher/src/controls/ShareMenu.tsx
- site/Head.tsx
Resolves #2924
Removes Facebook and X sharing options from the menu.
- Click stats for sharing to FB/X are very low
- We now show the phone’s built-in share menu on mobile
- Facebook sharing breaks every once in a while
> 🔨 remove FB/X sharing options

- adminSiteServer/imagesHelpers.ts
- db/migration/1745941683275-NoMarkdownInAltText.ts
GPT-4 was adding bold formatting to the alt text it was generating for us. This should fix it.
> 🎉 remove "**" from gpt-generated alt text

- site/multiDim/MultiDim.tsx
- site/multiDim/MultiDimDataPageContent.tsx
We were logging the event every time any search params changed in `MultiDimDataPageContent` because that created a new `searchParams` state that we depended on when calculating the `settings`.
It worked correctly in `MultiDim`, but making the analytics call in the event handler instead of `useEffect` is better in general.
> Fix grapher view analytics events in mdims

- adminSiteClient/GdocsPreviewPage.tsx
- db/model/Chart.ts
- db/model/ChartView.ts
- db/model/Gdoc/GdocBase.ts
Loading times for the preview page and related API calls seem to be highly variable, but my rudimentary comparison between the staging and prod admin shows around ~1 s improvement:
* https://admin.owid.io/admin/gdocs/19AlSstYCtGglhNNt9mbKGAEf_oZcQTKNjYJ-5BlXSts/preview
* http://staging-site-speed-up-gdoc-preview/admin/gdocs/19AlSstYCtGglhNNt9mbKGAEf_oZcQTKNjYJ-5BlXSts/preview
> Speed up gdoc preview page

- packages/@ourworldindata/grapher/src/chart/ChartUtils.test.ts
- packages/@ourworldindata/grapher/src/chart/ChartUtils.tsx
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
Resolves #4812
Example chart: [live](https://ourworldindata.org/grapher/child-mortality-igme?tab=chart) / [staging](http://staging-site-switch-to-slope-time/grapher/child-mortality-igme?tab=chart)
- For some of our charts, only very few entities stretch the whole length of the time range
- After switching from a line to a slope chart, most countries say 'No data', which isn't helpful
- This has prevented authors to enable line/slope chart type switching for charts like [Child mortality rate](https://ourworldindata.org/grapher/child-mortality)
- On switching to the slope chart tab, Grapher tries to find a time range for which most selected countries have data
- There are two concerns to balance:
- We want to honour the user's selection
- We want to show a meaningful slope chart
- The …
> ✨ switch to meaningful time range for slopes

- packages/@ourworldindata/grapher/src/chart/ChartUtils.tsx
- packages/@ourworldindata/grapher/src/core/Grapher.test.ts
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/core/GrapherUrl.ts
- packages/@ourworldindata/grapher/src/schema/grapher-schema.007.yaml
- packages/@ourworldindata/types/src/grapherTypes/GrapherConstants.ts
- packages/@ourworldindata/types/src/grapherTypes/GrapherTypes.ts
- packages/@ourworldindata/types/src/index.ts
- site/gdocs/components/KeyIndicatorCollection.tsx
Resolves #4573
Adds support for slope charts being the default in line/slope chart combinations.
More concretely, adds support for 'line' and 'slope' options to the `tab` config field, in addition to the currently available options, 'table', 'map' and 'chart'. If `tab` is 'chart' and there are more than one chart type in Grapher, the first chart type is shown by default.
- Tabs are handled on two levels in Grapher:
- `tab` is 'table', 'map' or 'chart' (these options map to the config's tab field)
- if `tab` is 'chart', then `chartTab` determines the currently active chart type
- `toObject()` serialises Grapher into a config object
- if the active tab is different from the first chart type, it's stored in the config
- `updateFromObject()` constructs Grapher from a config object
- if `tab` …
> 🎉 support slope as default for line+slope charts

- packages/@ourworldindata/explorer/src/GrapherGrammar.ts
Drive-by change for an issue I noticed.
`hideAnnotationFieldsInTitle` is currently parsed into
```javascript
{
hideAnnotationFieldsInTitle: {
entity: { entity: false, time: false, … },
time: { entity: false, time: false, … },
changeInPrefix: { … }
}
}
```
> 🐛 (explorer) fix hideAnnotationFieldsInTitle field

- baker/algolia/utils/shared.ts
- packages/@ourworldindata/grapher/src/core/GrapherConstants.ts
- packages/@ourworldindata/grapher/src/index.ts
`findMatchingRecordByPathnameAndQueryParams` was broken because I used the string `"explorer"` instead of the correct `"explorers"`
This PR fixes that by using the correct constant and creating one for Grapher as well, for consistency's sake. 
I'm holding off on using it everywhere because it competes with `BAKED_GRAPHER_URL`. I've added a point to next week's meeting's agenda to discuss.
> 🐛 fix explorer featured metric indexing

- packages/@ourworldindata/types/src/gdocTypes/Datapage.ts
- site/dataPage.ts
- site/multiDim/MultiDimDataPageContent.tsx
Regression introduced in 60127dc81. We construct the FAQs for mdims differently than for the classic data page, which was one difference between the duplicated `getDatapageDataV2` function, that I missed.
> Fix missing FAQs in multi-dim data page

- site/gdocs/components/Donors.scss
- site/gdocs/components/Donors.tsx
Add testimonials interspersed in the list of donors, as requested by Charlie and Hassan. For the first version, we hard-code the list of testimonials, since it's likely we won't need to change it often. If/when the need to change them more often arises, we should be able to add them to the `{.donors}` Archie component.
* [Slack](https://owid.slack.com/archives/C07RNNQQD9V/p1746119872683459?thread_ts=1744211984.890759&cid=C07RNNQQD9V)
* [Figma](https://www.figma.com/design/kgwh14s9hheiWp7ajWUolJ/About-Pages?node-id=403-6802&m=dev)
A quick visual check should be enough.
> Add testimonials to donor list

- site/gdocs/components/centered-article.scss
Add the [`text-wrap: balance`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-wrap#balance) to:
* Headings
* Image captions
* Pull quotes
Not adding it to blockquote, since we often use it to cite longer paragraphs of text, and `balance` only works for text spanning a limited number of lines, so it can easily lead to paragraphs of different length looking inconsistent next to each other.
[Slack discussion](https://owid.slack.com/archives/C03SK89695E/p1747028552252099).
Example of the difference it makes for headings:
| ![image](https://github.com/user-attachments/assets/9526add8-8d51-44d4-b268-555499324e82) | ![image](https://github.com/user-attachments/assets/200166ad-5c2d-443a-9c30-d19238fb1cc0) | 
I already tested all the components in …
> Add text-wrap: balance to short article elements

- baker/algolia/utils/pages.ts
- db/migration/1747337107717-FixMalformedGdocMarkdown.ts
- db/model/Gdoc/enrichedToMarkdown.ts
Resolves https://github.com/owid/owid-grapher/issues/4820
We were extracting plaintext from a rendered article to fill the `content` field in our algolia records. This included some useless content such as text from an unhydrated key charts block which was showing up in search results.
This PR fixes this issue by using each gdoc's markdown representation instead, which is already filtered down to only show semantically significant content. Some additional work was needed to format this in a way that's appropriate for Algolia search excerpts (i.e. removing our custom components from `enrichedToMarkdown` like `<Video />`)
I also added a migration that fixes ~150 documents with errors in them due to a few small oversights in the `enrichedToMarkdown` functions.
**Before**
**After**
Check out …
> Fix bad algolia excerpts

- devTools/schemaProcessor/columns.json
- packages/@ourworldindata/grapher/src/schema/grapher-schema.007.yaml
We had a bug where `baseColorScheme: default` made Grapher crash. I found two charts in total that used ‘default’ as base color scheme. Both have been fixed manually.
This PR improves the status quo in two ways:
- ‘default’ is removed as valid base color scheme option from the bulk editor
- The base color scheme’s type in the config schema is narrowed, so that we get notified the next time an invalid value is used
> 🔨 stricter schema type for the base color scheme

- packages/@ourworldindata/core-table/src/OwidTable.ts
While working on something else I noticed these loops that are off by one.
---
- <kbd>&nbsp;2&nbsp;</kbd> #4892 
- <kbd>&nbsp;1&nbsp;</kbd> #4889 👈
> 🐛 fix off-by-one errors

- packages/@ourworldindata/grapher/src/core/Grapher.tsx
Relates to https://github.com/owid/owid-grapher/issues/3492 but more work is needed to resolve the issue.
---
- <kbd>&nbsp;2&nbsp;</kbd> #4895 
- <kbd>&nbsp;1&nbsp;</kbd> #4892 👈
> 🐛 (marimekko) don't show entities without data in the entity selector

- adminSiteClient/AbstractChartEditor.ts
- adminSiteClient/EditorCustomizeTab.tsx
- adminSiteClient/EditorDataTab.tsx
- adminSiteClient/EditorMapTab.tsx
- adminSiteClient/EditorTextTab.tsx
- packages/@ourworldindata/grapher/src/mapCharts/MapConfig.ts
- packages/@ourworldindata/types/src/index.ts
Adds a button to the chart editor that resets all map fields to their inherited defaults.
If you enable inheritance for an existing chart, then the chart's map settings overwrite the parent's map settings and there is currently no way in the admin to reset the map settings to their inherited defaults. This has been noticed by [Pablo A](https://owid.slack.com/archives/C0149NKLZAM/p1747399230591589).
This applies to all types of chart editors:
1. Chart editors for stand-alone charts
2. Chart editors for admin-authored indicator charts
3. Chart editors for narrative charts
To test each type:
- Go to this [GDP per capita chart](http://localhost:3030/admin/charts/4659/edit) that has a parent indicator with map settings
- Enable inheritance in the Debug tab
- Go to the Map tab and check that …
> 🎉 (admin) add reset button for map settings

- db/model/Variable.ts
When fetching metadata fails, error message tries to re-read body with `await resp.text()` which fails. This PR removes the body from the error message, it's not that useful anyway.
> :bug: Fix error message when fetching metadata

- devTools/regionsUpdater/update.ts
- packages/@ourworldindata/grapher/src/controls/globalEntitySelector/GlobalEntitySelector.tsx
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/entitySelector/EntitySelector.scss
- packages/@ourworldindata/grapher/src/entitySelector/EntitySelector.test.ts
- packages/@ourworldindata/grapher/src/entitySelector/EntitySelector.tsx
- packages/@ourworldindata/utils/src/index.ts
- packages/@ourworldindata/utils/src/regions.json
- packages/@ourworldindata/utils/src/regions.ts
Resolves #3599 
Adds a 'Filter by type' dropdown to the entity selector.
- I initially thought I'd use the newly imported `definedBy` field of the regions file, but it turns out that non-owid regions aren't really standardised which is why I resorted to string matching '... (SOURCE)' instead
- In addition to `WB`, `UNSD` and `WHO` defined in the regions file, I also added support for more sources; those are hard-coded
---
This is **part 4 of 16 in a stack** made with GitButler:
- <kbd>&nbsp;16&nbsp;</kbd> #4914 
- <kbd>&nbsp;15&nbsp;</kbd> #4911 
- <kbd>&nbsp;14&nbsp;</kbd> #4907 
- <kbd>&nbsp;13&nbsp;</kbd> #4883 
- <kbd>&nbsp;12&nbsp;</kbd> #4877 
- <kbd>&nbsp;11&nbsp;</kbd> #4876 
- <kbd>&nbsp;10&nbsp;</kbd> #4875 
- <kbd>&nbsp;9&nbsp;</kbd> #4864 
- <kbd>&nbsp;8&nbsp;</kbd> #4809 
- …
> 🎉 (entity selector) filter entities by type / TAS-923

- packages/@ourworldindata/grapher/src/mapCharts/MapChart.tsx
- packages/@ourworldindata/grapher/src/mapCharts/MapTooltip.tsx
Just something I noticed, which sometimes also makes map tooltips quite sluggish because `sortedNumericValues` needs to be re-computed again and again and again.
> enhance: reuse ColorScale for map tooltip

- adminSiteServer/app.test.ts
- baker/algolia/utils/charts.ts
- baker/algolia/utils/explorerViews.ts
- baker/algolia/utils/mdimViews.ts
- db/db.ts
Resolves https://github.com/owid/owid-grapher/issues/4675
Allows us to filter out non-topic, non-area tags from the tag graph and does so for mdim, chart, and explorer indexing.
> ✨ add option to exclude sub-areas from parentTagArrays

- adminSiteClient/EditorColorScaleSection.tsx
- adminSiteClient/EditorCustomizeTab.tsx
- adminSiteClient/EditorMapTab.tsx
- adminSiteClient/GrapherConfigGridEditor.tsx
- db/migration/1748436369499-RemoveEqualSizeBins.ts
- devTools/schemaProcessor/columns.json
- packages/@ourworldindata/explorer/src/ColumnGrammar.ts
- packages/@ourworldindata/grapher/src/barCharts/DiscreteBarChart.tsx
- packages/@ourworldindata/grapher/src/color/ColorScale.test.ts
- packages/@ourworldindata/grapher/src/color/ColorScaleConfig.test.ts
- packages/@ourworldindata/grapher/src/color/ColorScaleConfig.ts
- packages/@ourworldindata/grapher/src/facetChart/FacetChart.tsx
- packages/@ourworldindata/grapher/src/horizontalColorLegend/HorizontalColorLegends.tsx
- packages/@ourworldindata/grapher/src/lineCharts/LineChart.test.ts
- packages/@ourworldindata/grapher/src/lineCharts/LineChart.tsx
- packages/@ourworldindata/grapher/src/mapCharts/MapChart.tsx
- packages/@ourworldindata/grapher/src/schema/defaultGrapherConfig.ts
- packages/@ourworldindata/grapher/src/schema/grapher-schema.007.yaml
- packages/@ourworldindata/types/src/domainTypes/CoreTableTypes.ts
- packages/@ourworldindata/types/src/grapherTypes/GrapherTypes.ts
This option is enabled in pretty much every single chart (there was only one or two exceptions, and it most likely weren't intentional).
SVG diff is here: https://github.com/owid/owid-grapher-svgs/commit/79b3e96ddc5dd06c94e44c3f98a0bd3fedfdc090
For reference, this is what `equalSizeBins: false` would do:
Our [map bracket guide explicitly recommends](https://www.notion.so/owid/How-to-pick-map-brackets-fca269b396c3470e8d54dd762390ce2a?pvs=4#ee27365c7b6d480abdf2300fcf057f63) against enabling visual scaling.
> cleanup: remove `equalSizeBins` from ColorScale

- adminSiteServer/apiRoutes/charts.ts
I'm literally so confused by our error handling in the admin api router. `admin.requestJSON` expects `error` to have a `message` and `status`, so I added those for the charts endpoints. Not sure if we need to do this elsewhere as well?
Try updating [this chart on staging](http://staging-site-show-errors-in-admin/admin/charts/349/edit) (unless Bastian has fixed the problem by now)
> 🐛 show error message in the admin

- packages/@ourworldindata/grapher/src/mapCharts/ChoroplethMap.tsx
A "dumb" fix for https://github.com/owid/owid-grapher/issues/4957
https://github.com/user-attachments/assets/7d9a9982-120c-4cc9-b52f-0f2e418860b0
You can use either the MacOS simulator app, or your browser's phone simulator and zoom in via the track pad.
> 🐛 fix grapher 3D zoom trap

- packages/@ourworldindata/grapher/src/core/Grapher.tsx
Respect the `tableSearch` param (I forgot to parse it from the url when adding this feature)
> 🐛 parse table search param from url

- db/model/Post.ts
Fixes scheduled posts from showing up on author pages
e.g. on [Saloni's page](https://ourworldindata.org/team/saloni-dattani):
> 🐛 fix unpublished articles in author pages

- db/model/Gdoc/rawToEnriched.ts
Part of https://github.com/owid/owid-grapher/issues/4851
It's much rarer that we _don't_ want outlines around our images, so Marwa has asked that we make this the new default.
Will check with her to see if we need to do an audit/update before merging.
> ✨ outline article images by default

- .clinerules
- .github/workflows/ci.yml
- CLAUDE.md
- devTools/svgTester/verify-against-master.sh
- docs/devcontainer-setup.md
- docs/local-typescript-setup.md
- ops/buildkite/deploy-content
- package.json
Since we switched to `tsx` to execute TS files directly, we no longer need to compile TS to JS explicitly before running any commands.
We now have the `typecheck` script, which currently does almost the same as the old `buildTsc` (without the verbose flag), but it is used only for checking the types, and thus we don't need to run it in so many places.
> Remove buildTsc script

- packages/@ourworldindata/core-table/src/CoreTableColumns.ts
- packages/@ourworldindata/grapher/src/chart/ChartUtils.tsx
- packages/@ourworldindata/grapher/src/entitySelector/EntitySelector.tsx
- packages/@ourworldindata/grapher/src/mapCharts/MapChart.tsx
> [!IMPORTANT]
> Check SVG tester after all parent PRs have been merged.  
Adds projection columns to the entity selector.
Similar to how it works for maps, projection columns and their historical counterparts are combined into one sort column. If we can’t find a historical counterpart for a projection column, we just add it as-is to the dropdown options.
The dropdown label automatically updates when you drag the timeline handle (should the historical and project columns have different names)
Usually, projection columns have a clear cut-off year, but we do sometimes have combined columns with historical and projected data for the same year ([example](http://staging-site-entity-selector-projections/admin/charts/7406/edit)). In such cases, we drop the projected data and only show the …
> 🎉 show projected data in the entity selector

- packages/@ourworldindata/grapher/src/core/FetchingGrapher.tsx
When clicking around in the all charts block, charts could get into pretty weird states as they didn't reset cleanly.
This PR adds a call to GrapherState.reset() that should fix this
See https://owid.slack.com/archives/C46U9LXRR/p1750333064504219
> 🐛 fix all-charts weirdness

- packages/@ourworldindata/grapher/src/core/Grapher.tsx
The bug was introduced by [this commit](https://github.com/owid/owid-grapher/commit/0845ee4b5d19292d9366f58ac5b70005c4780e08).
> 🐛 fix issue where configs with a map region specified weren't rotated to the region

- packages/@ourworldindata/grapher/src/dataTable/DataTable.tsx
It's currently possible for some columns to have years outside of the given timeline range, e.g. a Population column used as size dimension in a scatter plot.
I think this happens when timelineMinTime and timelineMaxTime are not set. In that case, `tableAfterAuthorTimelineAndEntityFilter` doesn't actually get filtered and auxiliary columns (like the color or size dimensions) end up with data for years outside of the x/y range.
> 🐛 fix overflowing sparklines in data tables

- packages/@ourworldindata/grapher/src/stackedCharts/StackedDiscreteBarChart.tsx
It looks a bit more balanced and it gives a bit more space to the chart area
> ✨ slightly decrease legend padding in stacked discrete bar charts 

- baker/GrapherBaker.tsx
- baker/SiteBaker.tsx
- db/model/Gdoc/GdocBase.ts
- db/model/Variable.ts
- packages/@ourworldindata/utils/src/index.ts
- packages/@ourworldindata/utils/src/metadataHelpers.ts
We can't move all call sites to fetch the metadata from the DB, because for data pages and Algolia indexing we need the dimension entities, which we currently don't have in the DB.
Unfortunately, it doesn't seem to make a noticeable change in bake times in staging, but presumably we hit the R2 less, which is good in itself, and the code is a bit simpler.
> Move some variable metadata queries to DB

- adminSiteClient/EditorColorScaleSection.tsx
- adminSiteClient/GrapherConfigGridEditor.tsx
- db/migration/1750251210487-RemoveColorScaleMinValue.ts
- devTools/schemaProcessor/columns.json
- packages/@ourworldindata/grapher/src/color/ColorScale.test.ts
- packages/@ourworldindata/grapher/src/color/ColorScale.ts
- packages/@ourworldindata/grapher/src/color/ColorScaleConfig.test.ts
- packages/@ourworldindata/grapher/src/color/ColorScaleConfig.ts
- packages/@ourworldindata/grapher/src/lineCharts/LineChart.test.ts
- packages/@ourworldindata/grapher/src/schema/defaultGrapherConfig.ts
- packages/@ourworldindata/grapher/src/schema/grapher-schema.008.yaml
- packages/@ourworldindata/grapher/src/schema/migrations/migrate.test.ts
- packages/@ourworldindata/grapher/src/schema/migrations/migrations.ts
- packages/@ourworldindata/types/src/grapherTypes/GrapherTypes.ts
This makes it so we go from
```ts
{
customNumericMinValue: 0,
customNumericValues: [1, 2, 3],
customNumericLabels: ["one", "two", "three"]
}
```
to
```ts
{
customNumericValues: [0, 1, 2, 3],
customNumericLabels: ["one", "two", "three"]
}
```
Both of these will result in the bins:
- 0-1, labelled one
- 1-2, labelled two
- 2-3, labelled three
That is, the two properties are merged into one.
For a color scale with `n` bins, we'll now have `customNumericValues.length === n + 1` and `customNumericLabels?.length === n` and `customNumericColors?.length === n`.
This makes it easier to support automatic brackets, because the map bracket thresholds don't have this weird split into two properties any more.
Explorers have a very high number of them using `colorScaleNumericMinValue` and we can't …
> refactor: merge ColorScale's `customNumericMinValue` and `customNumericValues` into one

- packages/@ourworldindata/grapher/src/entitySelector/EntitySelector.tsx
Throws a bug for entity names with whitespaces and/or special characters.
> 🐛 flip id should be safe for css use

- packages/@ourworldindata/grapher/src/tooltip/Tooltip.scss
It should be controllable from outside whether the unit is capitalized or not
> 🐛 don't capitalize unit in tooltip

- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/modal/DownloadModal.scss
- packages/@ourworldindata/grapher/src/modal/DownloadModal.tsx
As part of this, I also applied the new design to the other callouts we show in the download modal. I think it still fits:
> feat: in download modal, show tip about interactive embeds

- site/DataPageContent.scss
Resolves #4992
I confirmed with Joe and Marwa that we only want to hide the tags on a small screen for now.
> Hide data page tags on a small screen

- baker/GrapherBaker.tsx
- baker/MultiDimBaker.tsx
- baker/SiteBaker.tsx
- baker/archival/ArchivalBaker.ts
- baker/archival/archiveChangedPages.ts
- db/model/Chart.ts
- db/model/Gdoc/GdocBase.ts
- db/model/Gdoc/GdocPost.ts
- db/model/MultiDimDataPage.ts
- db/model/archival/archivalDb.ts
- db/tsconfig.json
- packages/@ourworldindata/types/src/domainTypes/Archive.ts
- packages/@ourworldindata/types/src/gdocTypes/Gdoc.ts
- packages/@ourworldindata/types/src/grapherTypes/GrapherTypes.ts
- packages/@ourworldindata/types/src/index.ts
- serverUtils/archivalFileUtils.ts
- serverUtils/archivalUtils.ts
- site/GrapherPage.test.tsx
- site/GrapherWithFallback.tsx
- site/blocks/RelatedCharts.test.tsx
- site/blocks/RelatedCharts.tsx
- site/gdocs/components/Chart.tsx
Resolves #5063.
Provides `archivedChartInfo` in the following blocks/places:
- For the `<Chart>` component, via `_OWID_GDOC_PROPS.linkedCharts`
- For the `<RelatedCharts>` component, via `OWID_GDOC_PROPS.relatedCharts`
- For the `<AllCharts>` component, via `_OWID_DATAPAGEV2_PROPS.datapageData.allCharts`
Putting it in the right places everywhere took a lot of work and moving code, frankly more than I expected, which isn't great. At the very least, the various commits are self-contained.
Also, while working on this, I noticed that gdocs' `prefetchedAttachments` don't quite work the way they should, and that each baked gdoc still runs all the various DB queries etc. no matter what. I didn't fix that, as it's out of scope for this issue.
- _Note that the life expectancy chart is pretty much …
> feat: provide `archivedChartInfo` for embedded charts

- packages/@ourworldindata/grapher/src/schema/migrations/migrate.test.ts
- packages/@ourworldindata/grapher/src/schema/migrations/migrate.ts
- packages/@ourworldindata/utils/src/grapherConfigUtils.test.ts
- packages/@ourworldindata/utils/src/grapherConfigUtils.ts
As discussed in the data viz meeting today, accepting the schema and hoping for the best is a better strategy than just outright rejecting it and throwing the towel.
I'm not sure what to do about `mergeGrapherConfigs`? https://github.com/owid/owid-grapher/blob/4ccb17228d8fa4e19417362130d096027fccdcf7/packages/%40ourworldindata/utils/src/grapherConfigUtils.ts#L41-L72
It is also throwing when it attempts to merge two different schema versions, but on the client it is only used for explorers.
Merging configs with different schema versions seems more tricky than just accepting them. What do you think, @sophiamersmann?
> fix: accept newer schema versions without throwing

- package.json
- packages/@ourworldindata/components/package.json
- packages/@ourworldindata/core-table/package.json
- packages/@ourworldindata/explorer/package.json
- packages/@ourworldindata/grapher/package.json
- packages/@ourworldindata/utils/package.json
- packages/@ourworldindata/utils/src/Util.ts
- yarn.lock
- Fixes https://github.com/remeda/remeda/issues/1128
- Fix type errors after the bump
- Add remeda as explicit dependency to packages which already use it
> Bump remeda to 2.23.3

- packages/@ourworldindata/grapher/src/core/FetchingGrapher.tsx
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- site/multiDim/MultiDim.tsx
- site/multiDim/MultiDimDataPageContent.tsx
Fixes #5062.
The refactor made it so the config is fetched inside `FetchingGrapher`, but Grapher is unaware of that.
On the other hand, it is somewhat important that a dimensionless Grapher continues to show the "No table loaded yet" warning in other places, for example in the admin.
For this reason, I opted to introduce the new `isConfigReady` state, which goes into grapher's `isReady`.
---
- <kbd>&nbsp;2&nbsp;</kbd> #5081 
- <kbd>&nbsp;1&nbsp;</kbd> #5080 👈
> fix: show loading indicator while config is being fetched

- packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.tsx
This is an optional addendum to #5080.
During loading, we currently show a bunch of controls - things like the tab bar, data source, settings menu, download button, etc.
While a few of these may make sense, many of these just don't make any sense and can just be removed.
What do you think?
Here are some before/after videos with the loading artificially slowed down:
https://github.com/user-attachments/assets/e9c12b07-99c6-4e04-a8a3-79e60041aa93
https://github.com/user-attachments/assets/15fb7e58-82cc-4854-921a-38397b2ed5af
https://github.com/user-attachments/assets/52f9c3bc-5a5e-471c-9096-2515f28a1a4b
---
This is **part 2 of 2 in a stack** made with GitButler:
- <kbd>&nbsp;2&nbsp;</kbd> #5081 👈 
- <kbd>&nbsp;1&nbsp;</kbd> #5080
> feat: show fewer controls during loading

- site/gdocs/components/OwidGdocHeader.tsx
A small oversight from the LTP restyle.
[Figma reference](https://www.figma.com/design/HcwsPwvmm3azqy2a7RL5QK/Topic-Page?node-id=116-882&p=f&t=EOgpWTISF6KihKIH-0)
> 🐛 fix topic page heading size

- adminSiteClient/GrapherConfigGridEditor.tsx
- package.json
- packages/@ourworldindata/components/package.json
- packages/@ourworldindata/explorer/package.json
- packages/@ourworldindata/grapher/package.json
- packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.tsx
- packages/@ourworldindata/grapher/src/footer/Footer.tsx
- packages/@ourworldindata/grapher/src/header/Header.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/AbstractStackedChart.tsx
- packages/@ourworldindata/utils/package.json
- yarn.lock
This is _not_ the big mobx update just yet.
This is just the latest mobx-react version that still supports mobx 5, so let's take this step now so we can do proper stepwise upgrades.
> chore(deps): update mobx-react to version 6

- functions/_common/imageOptions.ts
- packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.tsx
- packages/@ourworldindata/grapher/src/chart/CaptionedOrThumbnailChart.tsx
- packages/@ourworldindata/grapher/src/chart/ChartAreaContent.tsx
- packages/@ourworldindata/grapher/src/chart/ChartManager.ts
- packages/@ourworldindata/grapher/src/chart/ChartTypeMap.tsx
- packages/@ourworldindata/grapher/src/chart/ChartUtils.tsx
- packages/@ourworldindata/grapher/src/chart/StaticChartWrapper.tsx
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/mapCharts/MapChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/MarimekkoChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedDiscreteBarChart.tsx
- packages/@ourworldindata/types/src/grapherTypes/GrapherTypes.ts
- packages/@ourworldindata/types/src/index.ts
Grapher thumbnails in search render just the chart area, no header or footer.
This PR adds a `renderMode` to Grapher, which can be either 'captioned' (renders Grapher as usual with header and footer) or 'thumbnail' (renders only the chart area).
The chart area content has been extracted from `CaptionedChart` into its own component, `ChartAreaContent`. A new wrapper component, `CaptionedOrThumbnailChart`, chooses between rendering `CaptionedChart` or just `ChartAreaContent` based on the `renderMode`.
Also drops the `containerElement` prop from the chart component, since it didn’t appear to be used.
You can test by setting `imType=thumbnail` to static exports, e.g http://staging-site-grapher-thumbnail-setup/grapher/life-expectancy.svg?imType=thumbnail&nocache.
> 🔨 thumbnail rendering

- packages/@ourworldindata/grapher/src/core/Grapher.tsx
Explorers were passing in undefined `staticBounds`, which broke the download modal
> 🐛 fix download modal in explorers

- packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.tsx
- packages/@ourworldindata/grapher/src/controls/ContentSwitchers.scss
- packages/@ourworldindata/grapher/src/controls/ContentSwitchers.tsx
- packages/@ourworldindata/grapher/src/controls/Controls.scss
- packages/@ourworldindata/grapher/src/controls/SettingsMenu.scss
- packages/@ourworldindata/grapher/src/controls/SettingsMenu.tsx
- packages/@ourworldindata/grapher/src/controls/controlsRow/ControlsRow.tsx
- packages/@ourworldindata/grapher/src/core/grapher.scss
- packages/@ourworldindata/grapher/src/popover/Popover.scss
- packages/@ourworldindata/grapher/src/popover/Popover.tsx
- packages/@ourworldindata/grapher/src/tabs/Tabs.scss
- packages/@ourworldindata/grapher/src/tabs/Tabs.tsx
> [!NOTE]
> Check SVG tester before merging 
Adds a '+X' tab that opens a popup with more chart types if there are more than four tabs. 
The first commit extracts a Popover component out of the Settings menu, and the second commit uses that component for the chart type menu.
---
This is **part 5 of 7 in a stack** made with GitButler:
- <kbd>&nbsp;7&nbsp;</kbd> #5021 
- <kbd>&nbsp;6&nbsp;</kbd> #5020 
- <kbd>&nbsp;5&nbsp;</kbd> #5037 👈 
- <kbd>&nbsp;4&nbsp;</kbd> #5036 
- <kbd>&nbsp;3&nbsp;</kbd> #4990 
- <kbd>&nbsp;2&nbsp;</kbd> #4855 
- <kbd>&nbsp;1&nbsp;</kbd> #4854
> 🎉 add chart type menu to tab switcher

- packages/@ourworldindata/grapher/src/core/FetchingGrapher.tsx
I don’t think we should merge the default settings here, unless I’m missing something?
The Grapher component should be the source of truth for defaults. `defaultGrapherConfig` _should_ be in sync, but it’s safer not to depend on that.
> 🔨 rely on Grapher's defaults in FetchingGrapher

- db/model/Chart.ts
- functions/donation/donate.ts
- functions/package.json
- functions/tsconfig.json
- package.json
- packages/@ourworldindata/types/package.json
- packages/@ourworldindata/types/src/DonationTypes.ts
- packages/@ourworldindata/types/src/gdocTypes/Datapage.ts
- serverUtils/openAiUtils.ts
- yarn.lock
We were using both `zod` and `@sinclair/typebox` for type validation.
Let's make it just one again, and Zod seems like the better one at this point because it has a bunch more features, and supports [Standard Schema](https://standardschema.dev/).
Also, when using `zod/mini`, we end up with a slightly smaller bundle.
> chore: use zod for type validation, remove typebox

- site/gdocs/components/Table.tsx
Browser adds `<tbody>` implicitly when it's missing, which breaks the hydration, and React raises error in dev. It's possible React didn't do the validation in older versions.
> Fix hydration error in Table

- site/gdocs/components/centered-article.scss
https://github.com/owid/owid-grapher/pull/5149 removed a line of CSS that was doing work for when a video had a vertical aspect ratio. This fixes that.
| <img width="1165" height="815" alt="image" src="https://github.com/user-attachments/assets/57d76d43-cb65-422d-95ab-5d4ec3d80901" /> | <img width="1058" height="924" alt="image" src="https://github.com/user-attachments/assets/668d7d09-3cc5-4d9b-808b-42fd8ea43b5f" /> |
> 🐛 fix videos being uncentered

- baker/DeployUtils.ts
- baker/startDeployQueueServer.ts
Run `runDeployIfQueueIsNotEmpty` every 5 seconds instead of watching `.queue` file. This simplifies it a bit and avoids situations with empty `.queue` file, but non-empty `.pending` file.
> :bug: Make deploy queue polling sync

- packages/@ourworldindata/grapher/src/mapCharts/MapTooltip.tsx
- packages/@ourworldindata/grapher/src/slopeCharts/SlopeChart.tsx
- packages/@ourworldindata/grapher/src/tooltip/Tooltip.scss
- packages/@ourworldindata/grapher/src/tooltip/TooltipContents.tsx
- packages/@ourworldindata/grapher/src/tooltip/TooltipProps.ts
Hides the display name in slope tooltips.
> 🐛 hide variable name in slope tooltips

- adminSiteServer/apiRoutes/charts.ts
- db/model/Chart.ts
We want to start syncing charts with just tags changes in ETL's chart-diff. For that, it'd be very useful to know the time of an update. Can we bump `lastEditedAt` when we make edits to tags? It'd show up at the top of charts view in Admin. Are there any risks from doing this?
> :sparkles: Update lastEditedAt if tags are updated

- packages/@ourworldindata/utils/src/experiments/Experiment.ts
- packages/@ourworldindata/utils/src/experiments/config.ts
- site/CookiePreferencesManager.tsx
- site/DataPageContent.scss
- site/DataPageV2Content.tsx
- site/SentryUtils.ts
- site/instrument.ts
Enhances Sentry tracking in three ways:
(1) Sets the user to the GA4 client ID (when analytics consent provided), which allows us to filter by user id in the Sentry UI and also connect Sentry session replays to GA4 sessions. Duplicates #5274. Closes #5231.
(2) Sets tag(s) for all assigned experiments, which allows us to filter Sentry session replays by experiment name and arm assignment. Sentry tag keys have a max length of 32 characters and values have a max length of 200 characters, so this PR adds type checking to experiment ids and arm ids accordingly.
(3) Sets tag for `document.referrer` hostname, which allows us to filter Sentry session replays by referrer (e.g. "google.com", "ourworldindata.org"). Only stores the hostname to keep cardinality low. Closes #5221.
⚠️  NOTE: do NOT …
> Add sentry user, experiment tags, referrer tag

- adminSiteServer/multiDim.ts
Published status is set in the admin. If the multi-dim is already published, we must cascade the property to the view grapher configs when we assemble them.
I tested the fix by making manual requests against the admin API in local env.
> Fix update of existing published multi-dim

- baker/countryProfiles.tsx
Concurrent calls to update charts using Admin API endpoint `/charts/[chart_id]` sometimes fail with deadlock. Adding a MySQL lock prevents them.
(Note that `country_latest_data` is scheduled for deprecation anyway, so this should be low risk)
> :bug: Add MySQL lock when updating `country_latest_data` to avoid deadlocks

- site/multiDim/MultiDimDataPageContent.tsx
When the initial page load URL doesn't include multi-dim view query params (or they are incorrect), we compute them from config and display the default (closest correct) ones. In such case they were not correctly passed to Grapher and were missing from the embed URLs.
> Fix multi-dim embed URL query params on page load

- adminSiteClient/DataInsightIndexPage.tsx
- adminSiteClient/ImagesIndexPage.tsx
- adminSiteClient/imagesHelpers.ts
- adminSiteServer/imagesHelpers.ts
- db/migration/1758638800569-ImagesSetNonNull.ts
- packages/@ourworldindata/types/src/dbTypes/Images.ts
Updating these 4 columns to make them non-nullable.
Marking `originalWidth` as non-null also means that, for now, we don't support uploading SVGs. Not sure if there's any codepaths we should remove also.
> migrate: mark `images` columns as non-null

- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/modal/EmbedModal.tsx
- site/multiDim/MultiDim.scss
- site/multiDim/MultiDim.tsx
- Fix ArchiveContext not being passed down in some cases
- Fix iframe height
- Fix query params behaving differently for live and archival embeds
This was cherry-picked from my article archive stack (so you reviewed this once already) to get the fixes into prod earlier, since we are publishing more mdims and I don't want their archive to be broken.
> Fix archival multi-dims

- packages/@ourworldindata/grapher/src/entitySelector/EntitySelector.tsx
The `tableForSelection` doesn't necessarily contain all entities. Since interpolated columns are computed only once and then persisted, some entities incorrectly show 'No data', because they weren't contained in the table when the column was computed.
> 🐛 fix entities incorrectly showing 'No data' in the entity selector

- baker/ExplorerBaker.tsx
- baker/archival/ArchivalBaker.ts
- baker/archival/archiveChangedPages.ts
- baker/siteRenderers.tsx
- packages/@ourworldindata/explorer/src/Explorer.tsx
- site/ExplorerPage.tsx
- site/owid-archive.entry.ts
- site/runSiteFooterScripts.tsx
Part of #5366
Missing images is a known issue. This might be solved at the same time as when we implement archiving of images for articles.
- Migrate DB with `yarn runDbMigrations`
- Create archive for one grapher-based and one indicator-based explorer
```
yarn buildArchive --type explorers --explorerSlugs co2 air-pollution --latestDir
```
> Add baking of explorer archive

- baker/ExplorerBaker.tsx
- baker/GrapherBaker.tsx
- baker/MultiDimBaker.tsx
- baker/SiteBaker.tsx
- baker/siteRenderers.tsx
- db/model/Gdoc/GdocBase.ts
- db/model/Gdoc/GdocPost.ts
- packages/@ourworldindata/explorer/src/Explorer.tsx
- packages/@ourworldindata/grapher/src/core/FetchingGrapher.tsx
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/core/GrapherUseHelpers.tsx
- packages/@ourworldindata/grapher/src/core/loadGrapherTableHelpers.ts
- packages/@ourworldindata/grapher/src/core/loadVariable.ts
- packages/@ourworldindata/types/src/gdocTypes/Datapage.ts
- packages/@ourworldindata/types/src/gdocTypes/Gdoc.ts
- packages/@ourworldindata/types/src/grapherTypes/GrapherTypes.ts
- packages/@ourworldindata/types/src/siteTypes/MultiDimDataPage.ts
- site/DataPageV2.tsx
- site/DataPageV2Content.tsx
- site/ExplorerPage.tsx
- site/GrapherFigureView.tsx
- site/GrapherPage.tsx
- site/Head.tsx
- site/MetadataSection.tsx
- site/blocks/RelatedCharts.tsx
- site/gdocs/components/Chart.tsx
- site/multiDim/MultiDim.tsx
- site/multiDim/MultiDimDataPage.tsx
- site/multiDim/MultiDimDataPageContent.tsx
In the past, the type(s) got renamed without renaming all of their variables. Since we are going to start archiving articles, which will also use `ArchiveContext`, it makes even more sense now to stop using "chart" as part of variable names for `ArchiveContext` and clean up the naming.
This also fixes a few other instances that I found confusing.
This change should not affect the behavior in any way.
Check that everything still works as expected.
> Rename archive variables to better match types
