owid/owid-grapher

.gitignore

My `composer install` generated a new `vendor/compiled.php` file which should probably be in gitignore. (unless I'm doing the setup strangely somehow!)

Add composer-generated compiled.php to .gitignore

---

config/mail.php

This lets password resets work with mailtrap and other smtp hosts where
the username is not an email address.

Add a default sender address to config/mail.php

---

app/Http/routes.php

This lets you use any local domain for development rather than just localhost:8888

Don't 401 in auth.domain if APP_DEBUG=true

---

grapher_admin/views.py

A UnicodeError is appearing when saving some charts.

Remove print(dim) in savechart() function

---

js/charts/LineChart.tsx

Hannah mentioned the following issue with the label crossing over the graph:
This change fixes it by adding standard padding as used in other charts when the legend is hidden.

Line Chart - When legend is hidden, add some padding 

---

src/migration/1541082619105-AddForeignKeyConstraints.ts

Removes a duplicate foreign key constraint from `datasets.createdByUserId` and adds foreign key constraints to `dataset_files.datasetId` and `sources.datasetId`.

Add & deduplicate foreign key constraints

---

jest.config.js
package.json
src/ChartBaker.tsx
src/admin/serverUtil.tsx
src/gitDataExport.ts
src/migration/1536830436456-ChangeGitFormat.ts
src/scripts/exportChartData.ts
src/scripts/exportMetadata.ts
test/admin/serverUtil.test.js
yarn.lock

Fixes #100.
Creates promise-based `exec()` and `tryExec()` utility functions and removes `shelljs` as a dependency, which [does not yet support async commands](https://github.com/shelljs/shelljs/issues/2).
Things I'm unsure about: 
- I have created `tryExec()` anticipating that in some cases we don't want to throw an error if a command returns a non-zero exit code, but didn't end up using it anywhere. 
- I wrote unit tests but didn't test the other code I changed—it seems most of it deals with deploys and I don't think that would be set up on my machine?
- [Overengineering urge] we should maybe redirect stdout & stderr to the server process to easily see logs?
Also, do mention _any_ comments you might have!

Create a promise-based exec()

---

src/ChartBaker.tsx

Fixes #105. 
`git init` is supposed to be safe to run in an existing repo. Pretty small change, but since it deals with deploys my confidence levels are very low.

Ensure a git repo exists before attempting to deploy

---

src/admin/app.tsx
src/admin/server.tsx

Should fix #101, but I haven't tested.
@mispy I was actually wondering:
1. Is there any way to test this?
2. Why are some imports (including this one & cookie parser) still using `require()`?

Attach Slack error reporting before catch-all middleware

---

src/admin/serverUtil.tsx

The exec() call was reaching the maxBuffer limit on stdout in the chart baker (with a fresh setup). I think the default limit was 200KB.

Increase exec() maxBuffer to 10MB

---

src/scripts/exportChartDataNamespace.ts

This is basically how I reproduce the charts on a test server for a specific namespace. The dump will contain all variables that are used in charts that have **at least one** variable from the specified namespace. 
Thought it might be useful to have it in the repo.

Create a data export script for a namespace

---

src/admin/testPages.tsx

~~**Not ready to merge**~~ Now ready to be reviewed.
Allows specifying a `namespace` query parameter in the test pages, e.g. http://localhost:3030/admin/test/embeds?namespace=wdi
...so that we can show charts from live and test grapher side-by-side:
(Something funny happening with the unit here! We should probably discuss separately.)
The purpose is to make it easier to go through the chart differences and flag up things that don't look right. 
Since the import will run on the test grapher first, there will be no (easy) way to fix anything at this point, except flag things. Do you think it's a good idea to show the chart IDs and ask the reviewer to put them in e.g. a spreadsheet? (Or is there some easier way?) We would then run the import on the live grapher and fix all the flagged charts …

Namespace filter for test pages

---

package.json
src/admin/serverUtil.tsx
yarn.lock

When I removed it, I wondered why shelljs was creating files for stderr, stdout and parameters... I now figured out that it's the most robust way to handle lots of data without hitting the maxBuffer limit.
`netlifyctl` in particular is pretty noisy and easily reaches the maxBuffer limit, which also means all deploys will fail with the existing code, which I think is not good?
Anyway, the return value is now changed to be the exit code as a string (but we don't use it anywhere anyway).

Bring back shelljs

---

site/client/SiteHeaderMenus.tsx
site/client/css/footer.scss
site/client/owid.entry.ts
site/server/views/FrontPage.tsx
site/server/views/SiteFooter.tsx
site/server/views/SiteHeader.tsx

It makes navigation slower but gives us more data about what people click on. For every link, there is up to a 350ms delay before navigating away from a page, in order to have time to send an event to Amplitude.
Google Analytics can tell us which pages were visited next, but since we have duplicate links in the header, footer and across the homepage, without this we don't know which link they clicked on.

Link tracking for header, footer & homepage

---

charts/client/chart.scss
site/client/Grapher.ts
site/client/owid.scss
site/server/devServer.ts
site/server/formatting.tsx

Some things to note:
- The interactive charts will now load on any device whose screen is >680px wide (orientation independent) no matter whether it's mobile (e.g. tablet). They still won't load on mobile devices ≤680px.
- The `img` tags now have `width` and `height` attributes specified – I'm assuming these are always correct?

Add notice to open interactive charts on mobile

---

charts/ChartView.tsx
site/client/FullStory.ts

These custom events are pretty cool – we'd be able to find sessions looking at specific chart types, with add country enabled/disabled... here's a GIF:
Though I haven't tested whether this works yet. I think I might try it on the test server first. Leaving it here for next week...

Add FullStory 'Loaded chart' event

---

admin/client/CountryStandardizerPage.tsx
admin/client/DimensionCard.tsx
admin/client/EditorCustomizeTab.tsx
admin/client/EditorFAQ.tsx
admin/client/EditorMapTab.tsx
admin/client/EditorScatterTab.tsx
admin/client/Forms.tsx
admin/client/ImportPage.tsx
admin/client/admin.scss
charts/DataTab.tsx
charts/SourcesTab.tsx

Fixes https://github.com/owid/owid-grapher/issues/146
- Replace usage of `<i class="fa fa-name"/>` to `<FontAwesomeIcon icon={faName}/>`.
- Check most of the UI and make sure it renders and looks fine / similar to previous one (there are slight changes due to different Font Awesome versions).
- Fix a minor padding issue with the link / unlink icon next to text fields.
- Could not find `faRemove` thus replaced with `faMinus`.

Replace old font-awesome <i> elements in admin with <FontAwesomeIcon/>

---

utils/server/staticGen.tsx

Prevents past deploys' assets from being loaded from the production URL systematically

fix: remove host from assets URL

---

.travis.yml
bundlesize.config.json
package.json
yarn.lock

- Add a hard limit for bundle size in order to prevent another mistake like this: https://github.com/owid/owid-grapher/commit/dbdfd793ef2f3abc74414c735f8aa390af4ccc25 (that was my mistake btw)
- Compare PR/branch bundle size with master bundle size
Can be run locally with `yarn bundlesize`.
See the bundle limits in `bundlesize.config.json` – I've intentionally excluded the admin panel bundle.

Add bundle size CI check

---

.vscode/extensions.json
.vscode/settings.json

Without having an identical `defaultFormatter`, our editors might produce different formatting on save.

VSCode: enable `formatOnSave` and set default formatter

---

README.md
admin/client/Admin.tsx
admin/client/EditorBasicTab.tsx
admin/client/EditorFeatures.tsx
admin/server/AdminSPA.tsx
admin/server/api.ts
bin/deploy.sh
charts/ChartConfig.tsx
db/migration/1574953821471-AddExplorableCharts.ts
db/model/Chart.ts
features.ts
jest.config.js
knexfile.ts
package.json
settings.ts
site/server/SiteBaker.tsx
test/charts/ChartConfig.test.ts
utils/charts.ts

- Adds an `EXPLORER` flag in settings (need to set `EXPLORER=true` in your local `.env`)
- An `isExplorer` column on `charts` table
- An "Explorable chart" checkbox in the Grapher admin
- Logic to ensure map & chart tab are force enabled for explorable charts
- Logic to ensure only `LineChart` and `DiscreteBar` can be made explorable (arbitrarily chosen, can change)
Notion: https://www.notion.so/owid/Boolean-is_explorable-on-Chart-310eafedc0924ad78afb616a718c8200

isExplorable chart field

---

.travis.yml
bin/deploy.sh
package.json

- Moves prettier check into `yarn testcheck`, which is basically the command that runs _all_ pre-deploy checks
- Runs `yarn testcheck` on Travis CI

Add CI checks: prettier & typecheck

---

.travis.yml
package.json

Travis defaults to using .nvmrc's node version if not specified. 
Confirmation here: https://travis-ci.org/owid/owid-grapher/builds/623120043#L171
Also pinning in package.json's engines as I think we benefit more from predictable builds across environments (including dev) than a wider and more flexible node version range.

Node version pinning

---

charts/ChartConfig.tsx
charts/ChartUrl.ts
charts/ChartView.tsx
charts/Controls.tsx
charts/Header.tsx
charts/URLBinder.ts
charts/UrlBinding.ts
site/client/SearchPageMain.tsx
site/server/views/ChartPage.tsx
utils/client/url.ts

Ready for review.
For motivation/plan, see the notes on https://www.notion.so/owid/Chart-type-in-URL-params-4e7cd507297c48afabb6c0e66762e248. This is part 1, the refactor.
* Replace `URLBinder` with a `ChartUrl` object and a static utility, `UrlBinding`
* Move all manipulation of `window` and `document` into a method `bindToWindow` that is only ever invoked from top-level JavaScript
* Also move to the top level: grabbing the global window query string to configure the chart with
* Remove `isSinglePage` from ChartConfig
* Rename and refactor some methods for clarity, mostly in the URL utils

URL binding refactor

---

charts/ChartUrl.ts
charts/ExploreModel.ts
charts/ExploreUrl.ts
charts/ExploreView.tsx
charts/UrlBinding.ts
charts/__tests__/ExploreView.test.tsx
site/server/views/ExplorePage.tsx

Make URL binding work on the Explore page, including both the Chart params and the chart type managed by the Explore view itself.
* Refactor the UrlBinding utility to take an abstract ObservableUrl
* Add a simple ExploreModel that just wraps chartType for now
* Add an ExploreUrl that wraps ChartUrl and handles URL params
* Update ExploreView to use these to accomplish URL binding
Note that the chart types show up in the URL params with names like `StackedArea` and `WorldMap`. Not sure if that's what we want; we may want to rename them to simply `area`, `map`, etc.
I would like to do more refactoring on this. In particular, I'm not happy with the ExploreView taking the queryStr on its props and creating its model. The model itself should be passed in as a prop, similar to ChartView. Also, …

Explore URL binding

---

charts/ExploreModel.ts
charts/ExploreView.tsx
charts/UrlBinding.ts
charts/__tests__/ExploreModel.test.ts
charts/__tests__/ExploreView.test.tsx

Mostly move a bunch of model concerns out of the ExploreView, into the ExploreModel. Added tests for ExploreModel.
Note that the ExploreModel now takes a RootStore as a required param. I tend to think this is the way models should work.
If every view has a model, and every model has a store, then we don't need to create context providers to pass the store around. We can just pass the model down through the props (or if we don't want to do that, put the model itself in a context).
Also cleaned up the way the view was doing the chart type buttons.

Explore model/view refactor

---

admin/client/Colorpicker.tsx
charts/ChartData.ts
charts/ColorSchemes.ts
charts/Controls.tsx
charts/HTMLTimeline.tsx
charts/MapData.ts
charts/MapTab.tsx
charts/PointsWithLabels.tsx
charts/ScatterPlot.tsx
charts/ScatterTransform.ts
charts/Util.ts

Our utils didn't acknowledge that these can return undefined when the
array is empty. One downstream consequence of this was a bunch of
console warnings about trying to format an invalid year of undefined.
The one thing I left in a funky state is Timeline, because it makes too
many assumptions. Instead, I tried not to render it if the years array
is empty, and I put a warning on the constructor if this is ever missed.
So far, no warnings in tests or on the console in dev.

Fix typechecking on first() and last()

---

charts/Bounds.ts
charts/TextWrap.tsx
charts/Util.ts
charts/__tests__/TextWrap.test.ts
package.json
yarn.lock

I knew [this one](https://github.com/owid/owid-grapher/commit/5ef074a48380ff38a31af4d1630251cbefc0b635) was coming to bite me at some point.
I recently noticed that the license for the charts was aligned to the left and it used to be aligned to the right:
This happens because **the text bounds calculation was done including the HTML content, so the text width calculation treated the HTML tags as renderable text.**
**This PR strips HTML before calculating the width.**
Maybe a useful note while on this topic:
We use `pixelWidth()` to calculate the rendered space used by text – it's just a library that contains the rough dimension of letters and sums them up. This is not bulletproof and the charts would break if the used font is not available on the client, or if the text rendering of the OS …

Fix TextWrap bounds calculations for HTML

---

charts/MapTab.tsx

Was getting a console warning about a `<div>` being inside a `<p>`. This
changes the outer `<p>` to a `<div>`.

Change p to div to fix warning

---

charts/Bounds.ts
charts/ChartTab.tsx
charts/ChartView.tsx
charts/DiscreteBarChart.tsx
charts/LoadingChart.tsx
charts/MapTab.tsx
charts/__tests__/ExploreView.test.tsx
charts/client/chart.scss

It used to be the case that the chart view disappears (element is fully removed from the DOM tree) while the data is loading, e.g. when switching an indicator.
Changes:
- The ChartView is always shown, even while loading the data
- If available, the header and notes/sources of a chart are shown (indicator data)
- The chart plot is replaced with a loading indicator while the data is loading. This is the same loading indicator that appears

Fix disappearing chart while indicator is loading

---

charts/ChoroplethMap.tsx

For #268.
* The focussed countries now have a black border instead of a yellow one (the black tone is a little "blacker" than the one for non-focussed countries).
* Note, though, that the legend still has a yellow border. I wasn't sure whether that color should be changed as well.
* When countries are focussed by hovering the legend (as opposed to hovering over a country itself), all other countries now get a `fill-opacity` of `.4`, fading them out.
It now looks like this:

Fade out non-highlighted countries on map

---

charts/ChoroplethMap.tsx
charts/MapLegend.tsx

Fixes an issue where we could get into a state where a tooltip is shown on top of the Data or Sources tab:
This happens whenever a country expands right up to the edge. For example when you leave towards the lower left corner in https://ourworldindata.org/grapher/fatalities-from-terrorism?region=Asia.

Hide tooltip when the cursor leaves the map, even in literal "edge" cases

---

charts/ChoroplethMap.tsx

This is in addition to the recently-merged #301. It fades out countries without data, too.
I like it better this way, but this may be a matter of taste.
---

Fade out no-data countries as well

---

charts/Controls.tsx
charts/SlopeChartTransform.ts

Hello 👋
It has been a while :) I had some free time and decided to check back in on one of my favorite github projects.
This is a very simple PR to get interactive timeline for slope charts as requested here: https://github.com/owid/owid-grapher/issues/256
It works for the most part. Except playing a video starts with a view of no data which can definitely be improved. Let me know and I can make that improvement in this PR. 
Note that all current slope charts will start showing timeline control by default.
Example screenshot:

show timeline for slope charts

---

charts/ChoroplethMap.tsx
charts/MapLegend.tsx

Until now, Grapher showed Tooltips for countries outside the current projection:
This is very inconsistent, for multiple reasons:
* The country for which the tooltip is shown is not even highlighted with a thicker border (the cursor changes to `pointer`, though).
* Tooltips were only shown using the "close to center" logic (`onMouseMove`), not the "inside country" logic (`onMouseEnter`). Therefore, a tooltip is not shown for large countries even if your cursor is inside it (Brazil with "Africa" projection is a good example).
This PR changes it so a tooltip is never shown for countries outside the current projection.
cc @danielgavrilov

Map: Don't show Tooltip for countries outside the projection

---

charts/DiscreteBarTransform.ts

Solves #72, by de-duping the values and then creating a map value->color using the color scheme.
Note: I wasn't able to extensively test this locally because I only have a limited dataset on my machine. But it seems to work.

Discrete Bar: Use same color from ColorScheme for equal values

---

admin/client/CountryStandardizerPage.tsx

Turns out this was changed in Bootstrap 4.1 (https://github.com/twbs/bootstrap/commit/7b2427cc6b790b2b66dee32ba55b8fa694b789e2), and this upload button looked broken ever since.

Country Standardizer: Fix the layout of the "Choose CSV file" button

---

settings.ts
site/server/siteBaking.tsx

Currently, the last page https://ourworldindata.org/blog/page/11 is not baked, even though a eleventh page should exist. This happens because two different values of `postsPerPage` are being used, https://github.com/owid/owid-grapher/blob/fa47a6237cbdc252e50758723bd1980983b24317/site/server/SiteBaker.tsx#L318-L320 (using `BLOG_POSTS_PER_PAGE = 21`) and https://github.com/owid/owid-grapher/blob/fa47a6237cbdc252e50758723bd1980983b24317/site/server/siteBaking.tsx#L184-L185.
I have now changed it so both files use `BLOG_POSTS_PER_PAGE`, which is now set to a default value of 20.
This is not an issue when running `yarn dev` bc in that case, `renderBlogByPageNum` is called unconditionally.
I couldn't test this because I don't have a local `wpdb`, but I guess this will work.
This was broken in …

Fix broken blog post paging

---

admin/client/ColorSchemeDropdown.tsx
admin/client/EditorCustomizeTab.tsx
admin/client/EditorMapTab.tsx
package.json
yarn.lock

As suggested in #137, color schemes are now previewed right in the dropdown:
This is accomplished by making use of the `react-select` package that is being used elsewhere.
A custom `linear-gradient` is being created from each color scheme (it currently contains exactly 6 colors), which is displayed along with the color scheme name.

Ability to preview color schemes in the dropdown

---

charts/Controls.tsx
charts/DataTab.tsx
charts/DownloadTab.tsx
charts/HTMLTimeline.tsx
site/client/Analytics.ts
site/client/Feedback.tsx
site/client/owid.entry.ts

From the Notion issue, this adds tracking for the following:
I also added tracking to Feedback opens and Timeline plays. Once these are live I'll make a dashboard for chart events in Amplitude.
The existing code is simple enough and I just stuck with the patterns I found, though I guess there is room for marginal improvements. Most events currently have the type OWID_SITE_CLICK and then "note" is used for further bucketing, but some events use different types. At some point if someone is spending a lot of time in Amplitude it might be helpful to organize the analytics code a little better and standardize these event names. For now Amplitude has great querying capabilities so even with a few naming conventions it is easy to sort through the events.

Add analytics to Charts and additional site events

---

charts/__tests__/ChartConfig.test.ts
charts/__tests__/DataTable.test.tsx
charts/__tests__/ExploreModel.test.ts
charts/__tests__/ExploreView.test.tsx
charts/__tests__/Store.test.ts
charts/__tests__/TextWrap.test.ts
charts/__tests__/Util.test.ts
site/server/views/__tests__/ChartPage.test.tsx
site/server/views/__tests__/ExplorePage.test.tsx
test/admin/serverUtil.test.ts
test/fixtures/index.ts
test/search.test.ts

I forget where I learned this habit, but it is a minor dev UX pattern that I like: making each test file executable with a shebang so you can just open the command line and type "/foobar.test.tsx" to run that particular test file, or hit a keyboard shortcut in your editor to execute the file.
It does require running "yarn global add jest" once.
I know it seems trivial as you can currently do "jest filepath", but I've found I run tests so much that often a quick copy/paste of the filename or the editor keyboard shortcut can shave off a couple seconds on test runs and make testing a little more fun.
Posting this as a "Draft" Pull Request to see what you all think.

Executable test files

---

package.json

This is a very minor thing but I've found tmux to be helpful when you have to start multiple services to run a product.
The benefit of tmux versus "npm-run-all" is each process runs in it's own shell and logs stay separate, like in the screenshot below:
The downside is the tmux key bindings are a little obtuse. I also don't want to add two more dependencies, tmux and tmex (the latter is an npm package that provides a nice wrapper for launching tmux sessions). So I'm more posting this to share as tmux can be a handy tool to have on the toolbelt.
I think ideally it would be better to try and modularize the various packages and then you wouldn't need to start multiple services if you were only working on one at a time. In the cases where you did need to start multiple services you could just …

Nit: added small tmux alternative to npm-run-all

---

charts/Controls.tsx
charts/client/chart.scss

Working on the issue: "Display timeline slider on its own row for date-based charts"
After working with the code we currently have 8 different code paths:
(>700px?)*(inlineControls?)*(timelineControls?)
If we added (isDayBased?) we would have more to support.
Instead what if we just always present the chart as on the mobile device, with timelines and extra controls on their own lines?
I have another branch too where I try to cleanly implement all the existing paths with the addition of the new paths but thought I'd put this one for review first, since it removes a decent amount of complexity.

Always show footer timeline and additional controls on their own rows like on mobile

---

site/server/views/ChartPage.tsx
site/server/views/CovidPage.tsx
site/server/views/ExplorePage.tsx
site/server/views/SiteFooter.tsx

@MarcelGerber spotted the problem.

Don't include Javascript libs on Chart, Explore, or Covid pages since they are already included in Footer. #324

---

charts/Controls.tsx
charts/client/chart.scss

I think it's good to have this back actually. I forgot about this case:
(current on left, this PR on right)

Allow inline controls in chart tabs row

---

charts/ChartConfig.tsx
charts/PointsWithLabels.tsx
charts/ScatterPlot.tsx

Notion issue: https://www.notion.so/owid/Show-axis-value-instead-of-year-on-ScatterPlot-points-d8069816d451406ab267b2c116ebc679

ScatterPlot: Use date formatting when labels are days instead of years

---

admin/client/EditorScatterTab.tsx
charts/ChartConfig.tsx
charts/ScatterPlot.tsx

This adds a select option for admin users to specify a different source for the label values in the scatterplots.
Before:
After:

Add ability to use x or y values in point labels on ScatterPlots.

---

site/server/SiteBaker.tsx

On April 7th, 2020 Netlify will change the way they handle redirects. Currently, the default behaviour is to always assume redirects are forced – a path will be redirected even if the file exists.
This behaviour will change on April 7th, and we will need to explicitly mark our redirects with a trailing `!` in order to preserve the current behaviour.
More info: https://community.netlify.com/t/changed-behavior-in-redirects/10084

Netlify: add explicit ! to (implicit) forced redirects

---

charts/DimensionWithData.ts
charts/MapData.ts
charts/MapTab.tsx
charts/ScatterPlot.tsx
charts/ScatterTransform.ts
charts/SourcesTab.tsx

In some cases, we may use different time formatting on different dimensions, e.g. a scatter plot where X axis has a years variable, and Y axis has a days variable: https://owid.cloud/admin/charts/4041/edit (Slack discussion: https://owid.slack.com/archives/CUQSW9STU/p1584912362004000?thread_ts=1584907551.000900&cid=CUQSW9STU)
From an implementation point of view, this breaks the timespan logic (and probably more) and it isn't a good idea to combine variables with different time-bases. But authors are already creating these charts, and I imagine there will be more as we find interesting correlations between COVID-19 and various health/economics metrics.
Anyway, I thought we should try to use dimension-specific year formatting to address the problem as much as possible.
This PR fixes a …

Use dimension-specific formatYear where possible

---

site/server/views/ChartPage.tsx

Ex:
- http://localhost:3030/admin/charts/4060/edit
- http://localhost:3099/grapher/deaths-covid-19-vs-case-fatality-rate
"ourworldindata.org/malaria" in the `originUrl` field creates the following big blue button href:
- before: "ourworldindata.org/malaria", leading to "[HOST]/ourworldindata.org/malaria"
- after: "/malaria", leading to "[HOST]/malaria"

Add support for ourworldindata.org/x originUrl to "Here is all our research" link

---

site/client/Feedback.tsx
site/client/owid.scss

We currently don't clear the form after feedback is successfully sent.
This is a quick fix that shows an unavoidable message – hopefully it decreases the duplication of messages.

Give clear success message when feedback is successfully sent

---

settings.ts
site/server/SiteBaker.tsx
site/server/svgPngExport.tsx

This fixes broken hrefs mentioned in https://github.com/owid/owid-grapher/pull/370#issuecomment-607054294, and also introduces a new flag `OPTIMIZE_SVG_EXPORTS` in `settings.ts` (which can be overridden in `.env`) to quickly enable and disable the feature.

Fix broken hrefs in optimized svgs

---

charts/ChartView.tsx
site/client/css/pages/chart.scss

**⚠️ This will possibly have an effect on external embeds.** 
Fixes #358, in an alternative and more involved way than #359.
Implements:
- Less empty space around chart
- Ideal-ratio-sizing at smaller dimensions, so that `fitBounds` doesn't apply on normal laptop screens (see #358)
- The (huge) entry link is now moved lower and isn't fully visible, but I think visible enough – the space is prioritized for the chart instead
@MarcelGerber I've tagged you to review if you have time, but no worries if you can't. I just saw that you've dug into how the chart sizing works and can let me know if you see some ways this could fail, or could be improved. 
I've avoided this issue for a long time because of how it ties up CSS & JS sizing. It's probably better to keep all logic in one place; this is …

Improve chart sizing on ChartPage

---

package.json
webpack.config.js
yarn.lock

Working towards #367, this shaves 200KB off our `commons.js` bundle by removing all locales from moment. `en` is still available, even though we don't currently use it (but might do so in the future).

Don't include moment.js locales in build

---

admin/client/CountryStandardizerPage.tsx
admin/client/DatasetEditPage.tsx
admin/client/ImportPage.tsx
admin/server/adminViews.tsx
admin/server/app.tsx
charts/SourcesFooter.tsx
charts/Util.ts
db/db.ts
db/wpdb.ts
scripts/bakeSite.ts
scripts/configureAlgolia.ts
scripts/exportChartData.ts
scripts/exportMetadata.ts
scripts/exportStripeDonors.ts
scripts/indexChartsToAlgolia.ts
scripts/indexToAlgolia.ts
scripts/postUpdatedHook.ts
site/client/DonateForm.tsx
site/client/covid/CovidFetch.ts
site/client/runCookieNotice.tsx
site/server/bakeChartsToImages.tsx
site/server/devServer.tsx
site/server/grapherUtil.ts
site/server/svgPngExport.tsx
site/siteSearch.ts
test/enzymeSetup.ts
tsconfig.client.json
tsconfig.json
utils/csv.ts
utils/server/serverUtil.tsx

Working towards #367, I realized on the way that I need to enable the TypeScript option `esModuleInterop`.
The flag is explained here: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#support-for-import-d-from-cjs-from-commonjs-modules-with---esmoduleinterop
I just thought to open a separate PR for that, so the tree shaking one (currently at https://github.com/owid/owid-grapher/compare/tree-shaking-lodash) doesn't get too crowded. This here shouldn't be able to break anything.

TypeScript: Enable esModuleInterop

---

scripts/indexToAlgolia.ts
test/search.test.ts
utils/htmlToString.ts
utils/string.ts

This is again working towards #367.
I've moved `htmlToPlaintext`, which requires the [big html-to-text](https://bundlephobia.com/result?p=html-to-text@5.1.1) library and is only used in scripts and texts, to its own file.
This decreases the size of `commons.js` by .2 MB yet again.

Don't bundle html-to-text in production commons.js

---

charts/LineChartTransform.ts
charts/MapData.ts
charts/Util.ts
site/client/FullStory.ts
site/client/SiteHeaderMenus.tsx
site/client/covid/CovidTable.tsx
site/client/covid/CovidUtils.ts
site/client/runChartsIndexPage.ts
site/client/runCountryProfilePage.ts
utils/charts.ts
utils/search.ts

Working further towards #367, this makes sure we are only importing the lodash functions we need, and never `import * from lodash` (at least on the client side).
The savings are not huge: a mere 0.04MB less for `commons.js`. Well, I guess we're using quite a lot of lodash functions.
This would be easier with `lodash-es`, where the nicer destructuring imports are supported, but `ts-node` then complains about using ES6 modules directly, and I haven't really come up with a nice solution to that.
Note that admin code still uses `import *` imports, but we don't really care about its size. We could change those too, though.

Reduce lodash bundle size

---

admin/client/EditorDataTab.tsx
admin/client/VariableEditPage.tsx
charts/ChartConfig.tsx
charts/ChartData.ts
charts/DataKey.ts
charts/DataSelector.tsx
charts/DiscreteBarTransform.ts
charts/EntityDimensionKey.ts
charts/HeightedLegend.tsx
charts/LineChart.tsx
charts/LineChartTransform.ts
charts/Lines.tsx
charts/ScatterTransform.ts
charts/SlopeChartTransform.ts
charts/SourcesFooter.tsx
charts/StackedArea.tsx
charts/StackedAreaTransform.ts
charts/StackedBarTransform.ts
charts/TextWrap.tsx
charts/Variable.ts
charts/__tests__/TextWrap.test.ts

Before & After:
This hopefully improves styling of those charts and will let us use standard entity names and get the Map view working. It requires researchers to paste in an entity-annotation map at the variable level. The preferred way would be to have an annotation column and I tried to implement that but was not able to come up with a good approach yet. If we get our data warehouse model refactored hopefully that will be easy to move, if we want to keep this annotations feature around.
I also tried to clean up a few things as I went like adding more privates and renaming the vague "DataKey" to "EntityDimensionKey". Not that the latter rolls off the tongue but I think it's slightly better to have wordy but more informative names. These are all nits and would be happy to separate those …

Add Entity Annotations Feature to Line Charts

---

charts/Util.ts
site/client/covid/CovidFetch.ts

Further looking into how we can reduce the amount of resources loaded on https://ourworldindata.org/coronavirus, I noticed that `full_data.csv` is being loaded twice:
This stems from the fact that both the "deaths" and "cases" tables call `fetchECDCData` for themselves (and at roughly the same time, so the browser can't access a cached version quite yet).
While the file is only about 50KB gzipped, it's still an unnecessary request that we can prevent quite easily and nicely. And lodash's memoize seems to do a good job of saving the Promise. I'm open to other solutions, though.

Memoize the result of fetchECDCData

---

charts/HeightedLegend.tsx

---
There is a bit too much padding? This could go out as it is, but that wide gap is kind of a bit much. 
I thought this would be a 2min fix and I've spend much longer, so I'm leaving this here to merge or for anyone to extend and fix that padding.
I think the problem is that when legend items get offset, they have lines on the left, and this padding is reserved for those lines. But the padding is reserved in `HeightedLegend`, before we even know whether we need those lines. So when the lines are unnecessary, we end up with unused space.

Take annotation into account when computing legend width

---

charts/Controls.tsx
charts/client/chart.scss
charts/global.d.ts

Resolves #326.
As mentioned over there, the `navigator.share` API allows a website to interact with the operating systems' share functionality, especially on iOS and Android. It has good browser compatibility on mobile.
The additional menu entry ("Share via...", [akin to Twitter mobile](https://user-images.githubusercontent.com/2641501/77945355-d3beb700-72c0-11ea-965e-182db3e4d8a6.jpg)) is only shown if the API is supported, so you won't see any difference on a normal desktop browser.
This is what this looks like on Android 10:

Support navigator.share API in share menu

---

admin/client/EditorScatterTab.tsx
charts/AxisScale.ts
charts/Bounds.ts
charts/ChartConfig.tsx
charts/ChartData.ts
charts/Controls.tsx
charts/ScatterTransform.ts

This adds a toggle to zoom instead of the auto zoom behavior on selection change:
We could make the button pop more but it doesn't do much in certain situations so I found a more subtle placement in the controls area to be relatively straightforward. We could try this and iterate later.
There remain opportunities to clean up the scatter transform code to make this work better on some of the existing scatterplots. It works pretty well on connected scatters but in certain situations it has little effect (or no effect) due to various sorts of filters in the Scatter transform.

Add Zoom to selection toggle to scatterplots

---

charts/Marks.tsx

https://www.notion.so/Fix-skewed-arrow-on-scatter-plot-929b156ae4ea4fad841c9468af950000
Well, this one was easy 😄 
Looked like this before:
... now it doesn't anymore!

Fix skewed arrows

---

charts/Bounds.ts
charts/ComparisonLine.tsx
charts/Halos.tsx
charts/PointsWithLabels.tsx

Add Halos to text labels on scatterplots

---

charts/Lines.tsx
charts/StackedArea.tsx

Fixes #369.
I've changed it so the tooltip follows the finger, and is only visible while the finger is held down (on mobile).
The desktop behavior is still the same.

Better touch support for line & area charts

---

charts/StackedArea.tsx

Now there's a _little_ more space for the chart itself.
The bigger issue here is the big padding on the right of the legend, but that's way harder to fix (it comes from the markers/indicators that _may_ be to the left of the labels).

StackedArea: Reduce the legend width on mobile so there's more place for the chart itself

---

public/sandbox/bakeSandbox.ts
public/sandbox/index.html
public/sandbox/readme.md

This allows you to bake a current chart in the sandbox along with your local development version of Grapher charts to a self-contained folder in order to share interactive development prototypes with the rest of the team for feedback.
How to use:
1. Go to the admin for any chart on prod and copy/paste the debug version into sandbox/chart.js (paste it with `const sandboxChart =`—see chart.sample.js for a sample).
2. Run "ts-node bakeSandbox.ts /some/destionation/folder

Add sandbox to folder baking

---

charts/Util.ts
site/client/SiteHeaderMenus.tsx
site/client/css/header.scss

https://www.notion.so/Fill-up-mobile-menu-empty-space-with-entry-list-1f816b7560864ffa85b70bc2459a6154
These item previews will only be shown in the mobile menu, and only for categories that are not expanded. They are cutoff with "...".

In the mobile menu, preview entry list for each category

---

charts/LabelledSlopes.tsx

Correctly align right labels and values for slope charts

---

charts/ChartLayout.tsx
package.json
postcss.config.js
site/client/css/forms.scss
site/client/css/header.scss
site/client/css/mixins.scss
site/client/css/pages/homepage.scss
webpack.config.js
yarn.lock

As briefly discussed in Slack, currently the homepage looks quite broken in IE11. This PR makes the styles more compatible, thus especially the homepage looks quite good actually.
Of course any JS is still broken, but the site is still _usable_, just non-interactive.
(The blog images are only missing because I'm running locally)
Regarding the commits:
* e354386 has two very simple fixes for the "Articles by topic" dropdown and the newsletter "Subscribe" button. If you don't like the other changes, this one should be a no-brainer.
* 3037d89 adds a [PostCSS](https://postcss.org/) step to webpack which calls [Autoprefixer](https://autoprefixer.github.io/). Also, I replaced the [deprecated extract-text-webpack-plugin](https://github.com/webpack-contrib/extract-text-webpack-plugin) with the …

IE 11 styles

---

charts/Controls.tsx
package.json
yarn.lock

Fixes #258.
The share menu now looks like this:
As expected, the "Copy link" entry copies the full link to the clipboard. The text changes to "Copied!" afterwards.
I tested this in quite a few browsers, and all worked fine:
* Windows Chrome 83
* Windows Firefox 68
* iOS Safari 13.3 & 12.2
* macOS Safari 13 & 12
* Android Chrome 83
The library I'm using (`copy-to-clipboard`) will fallback to a `prompt()` window in case other methods don't work, but that shouldn't happen too often and has never happened in my testing.

ShareMenu: Allow copying link to chart

---

site/server/MathJax.ts

I just noticed that posts like `latex-maths` get a whole bunch of unnecessary updates (https://github.com/owid/owid-static/commits/master/latex-maths.html).
That's due to mathjax's font caching, which assigns ids in the order of rendering, which is not deterministic in our case. Disabling the font caching should resolve that without any side effects.

Disable mathjax font caching to prevent unnecessary page updates

---

admin/client/ColorSchemeDropdown.tsx
charts/Controls.tsx
charts/IndicatorDropdown.tsx
site/client/global-entity/GlobalEntityControl.tsx
utils/client/react-select.tsx

@danielgavrilov When looking at #420 I noticed you introduced the new `react-select` class, which is great.
I just find the new `isArray` function to be even more useful, since it allows us to get the values as an array every time without casting. Let me know what you think.

Introduce asArray to react-select.tsx and use it instead of casts

---

.rsync-ignore
bin/deploy.sh
package.json

Motivation: running tests locally is getting increasingly resource intensive.
This adds an "-r" option to the deploy command to run tests on the target server rather than locally. 
Given the size of the resulting node_modules folder, only one target test folder is created per staging server (as opposed to one per user). From preliminary tests, it looks like constantly overriding each other's changes in the target folder through rsync will be barely noticeable.
This PR also adds some more minor related improvements.

Add ability to run testcheck remotely

---

charts/MapTab.tsx

Currently, we show the hint "Click for change over time" for all countries on a map, even if there is no data available to show. That's confusing, since we encourage the user to click - and nothing happens.
One example of that would be Greenland here: https://ourworldindata.org/grapher/men-survival-to-age-65
This changes it so the hint is only shown if it's actually possible.

Only show "Click for change over time" hint if that's actually possible

---

package.json
site/server/formatting.tsx
site/server/views/FrontPage.tsx
site/server/views/SiteFooter.tsx
yarn.lock

We load a lot of images.
For example, upon visiting https://ourworldindata.org/coronavirus, a whopping 1MB of just svg graphics are loaded, many of which are either immediately replaced by an interactive chart or are simply never displayed because the user navigates away before she reaches them.
That's unnecessary traffic for us and unnecessary bandwidth towards the data caps of visitors.
That's why I suggest we lazy-load some of them, meaning they are only loaded once the user is _close_ to reaching them. This is now natively possible in [many browsers](https://caniuse.com/#feat=loading-lazy-attr) using the `<img loading="lazy">` attribute: https://web.dev/native-lazy-loading/
When exactly the image is loaded is a decision the browser makes, depending on the connection speed, whether …

Lazy-loading images

---

site/server/SiteBaker.tsx
site/server/bakeChartsToImages.tsx
site/server/formatting.tsx
site/server/grapherUtil.ts
site/server/siteBaking.tsx

This should potentially fix case 2 of https://www.notion.so/Bug-iframe-full-embeds-58f7693f518c42d7aebe95f306a1e65b.
I've also included some other, minimal somewhat-related fixes I've come across.

Trim iframe url when converting iframes to figures

---

charts/PointsWithLabels.tsx

Before:
After:
The current top perf hit in the Dashboard is a simple "cloneDeep". It looks like it was added in be1f0c6ce0dcd2bb473ceacbeb69cc1201d8e1ad to ensure we weren't repeatedly incrementing a memoized value on hover.
I looked at a large number of scatters and couldn't find one where we had `initialRenderData` not computed when `renderData` was called. So I think this is safe to not cloneDeep. In theory if there is a way to call `renderData` with a memoized `initialRenderData` and you hover/unhovered a series a number of times, maybe you would see a slight increase in the circle or line size, but couldn't repro that.

Perf: remove cloneDeep from PointsWithLabels

---

charts/AxisBox.tsx

Some of the "jumpiness" of the animations in log/linear switching happens when we go from a linear to a log scale and one of the domain mins is temporarily 0, which cascades until we get SVGs with lots of NaNs.
In LineCharts one of the intermediate renders looks like this:
In ScatterPlots:
This removes those invalid states and also removes some red in console.logs.
It's probably not worth it, but I wonder whether we could avoid the (logScale && domainContainsZero) runtime bugs by having an axis domain type to ensure there is code to handle zeroes in an axis domain.

fix(jumpiness): do not set min axis domain to 0 during scale animation.

---

admin/client/EditorMapTab.tsx
admin/client/admin.scss
charts/MapData.ts
charts/MapLegend.tsx

https://www.notion.so/Chart-editor-Make-Map-color-bins-more-clear-b2d7a990160e4b478243a5f8373a7676
This is for the discussion we had on Slack today about the confusing map legend bins.
I tried to make them a little clearer:
I'm not 100% sure if the operators are making the situation better or worse, so please feel free to chime in if they're confusing the hell out of you.

Chart editor: Make Map color bins more clear

---

admin/client/EditorMapTab.tsx
charts/MapConfig.ts
charts/MapData.ts

I think for charts like https://ourworldindata.org/grapher/covid-19-testing-policy, or really any chart on https://ourworldindata.org/policy-responses-covid, it makes way more sense to display the label of the bin (i.e. "No testing policy", "symptoms & key groups", ...) rather than the numeric value (i.e. 1, 2, 3).
Therefore this is now an option, and the new things are highlighted in red in the screenshot below:
I'm not 100% happy with the variable name & label for the toggle, so if you can come up with anything else feel free to suggest something else.

New option to show custom label instead of numeric value in map tooltip

---

site/server/grapherUtil.ts

This hopefully fixes case 4 of https://www.notion.so/Bug-iframe-full-embeds-58f7693f518c42d7aebe95f306a1e65b.
I don't think there's anything that can go wrong here, but it's probably still better to test this somewhere before deploying because this would be one that either breaks nothing or everything 🙃

Make lookup of iframe url case-insensitive

---

charts/Util.ts
charts/covidDataExplorer/CovidChartUrl.ts
charts/covidDataExplorer/CovidCountryPicker.tsx
charts/covidDataExplorer/CovidDataExplorer.tsx
charts/covidDataExplorer/CovidDataUtils.ts
site/client/css/pages/covidDataExplorer.scss

Notion issue: https://www.notion.so/owid/Ensure-country-colors-don-t-change-as-you-select-countries-a0a033f788aa415d844a657fc2b839ce
- Assigns a color to a country on select. Uses that color for any chart, until the country is unselected.
- Adds a small, colored rectangle in the country list.

Consistent country colors on COVID Data Explorer

---

site/client/Lightbox.tsx
site/server/formatting.tsx

Currently on mobile when you click the preview of a non-interactive chart, the interactive chart loads in a new tab _and_ the preview image shows up in the lightbox in the old tab.
This prevents the lightbox opening.
I went with the class `no-lightbox` to enable this, we could just as well go with a `data-` attribute if you want.

For non-interactive charts, don't open the preview in the lightbox

---

charts/DownloadTab.tsx
charts/LoadingChart.tsx
charts/client/chart.scss
site/client/Lightbox.tsx
site/client/LoadingIndicator.tsx
site/client/css/components/loading-indicator.scss
site/server/views/ChartPage.tsx

Currently, loading charts have "pulsating" loading indicator, while the lightbox and download tab use `fa-spinner`.
This changes `LoadingIndicator` to use the pulsating one and uses it for loading charts, the lightbox and the download tab.
This also makes it easier to re-use the element in the future.

Make LoadingIndicator more general and use it more consistently across owid

---

charts/covidDataExplorer/CovidDataExplorer.tsx
charts/covidDataExplorer/CovidRadioControl.tsx
site/client/css/pages/covidDataExplorer.scss

**Before:**
**After:**
https://www.notion.so/owid/Additional-label-for-align-outbreaks-checkbox-e8a6d6187df041ee8c244943464c29dc
https://www.notion.so/owid/Per-capita-label-displays-x-axis-label-a7ad27d4855146829c1e97b16ba40091

Covid data explorer label improvements

---

charts/ChartData.ts
charts/ChartUrl.ts
site/client/Analytics.ts

Before I deploy the `~` fix, I thought it might make sense to see how often we are seeing broken country links coming in. Then hopefully this will go down to zero when we switch to `~`.

Add tracking to determine how often broken entity names are happening

---

package.json
scripts/liveCommit.ts
yarn.lock

This is based off Daniels comment here (https://owid.slack.com/archives/CQQUA2C2U/p1590083865004800), but expanded to also cover staging servers and viewing commit information locally (`--tree` and `--show`).
This is the output of `yarn live-commit playfair --show --tree`, for example:
`yarn live-commit` just opens the deployed commit on the live server on github, just like Daniels snippet did.
As for why I'm using `opener` instead of a simple `open`, I'll leave it to [opener](https://www.npmjs.com/package/opener#why):
> Because Windows has `start`, Macs have `open`, and *nix has `xdg-open`. At least [according to some guy on StackOverflow](http://stackoverflow.com/q/1480971/3191). And I like things that work on all three. Like Node.js. And Opener.
I'm running on a Linux/Windows …

add `yarn live-commit` script to show information about deployed commits

---

charts/ChartData.ts
charts/ChartUrl.ts
charts/__tests__/ChartUrl.test.ts
charts/covidDataExplorer/CovidChartUrl.ts
site/client/Analytics.ts
site/client/SearchPageMain.tsx
site/client/SearchResults.tsx
site/client/global-entity/GlobalEntitySelectionUrl.ts
utils/client/url.ts

This addresses https://github.com/owid/owid-grapher/issues/397
It maintains backwards compatibility with the current URLs (called "v1"), while from here on out using a new schema ("v2"). v2 uses "|" as the delimiter, and concatenates the entities and then encodes the whole string. v2 always contain a "|", so if there is only 1 entity I append an extra "|" just to differentiate between v1 and v2.
The downside is the URLs are not as pretty, so very open to suggestions. Another potential tweak is to only use v2 style URLs for the Facebook share button (but then we'd have the problem if someone just copies/pastes the url into FB). Or we could use a different delimiter that doesn't have the Facebook problems (~ or _ perhaps).

Change delimiter in country query parameter to support Facebook URLs

---

charts/LineChartTransform.ts

fixes https://owid.slack.com/archives/C46U9LXRR/p1590491812001400.
Maybe we should also do the same for other chart types?

Don't show fractional ticks for y axis if it contains only integer values

---

charts/AxisScale.ts
charts/HorizontalAxis.tsx
charts/Util.ts
charts/VerticalAxis.tsx
charts/__tests__/Util.test.ts

As we [discussed with @MarcelGerber](https://owid.slack.com/archives/C46U9LXRR/p1590491812001400).
URL: https://ourworldindata.org/coronavirus-data-explorer?zoomToSelection=true&deathsMetric=true&dailyFreq=true&perCapita=true&smoothing=7&country=AGO~
URL: https://ourworldindata.org/coronavirus-data-explorer?yScale=log&zoomToSelection=true&time=2020-05-23&deathsMetric=true&dailyFreq=true&perCapita=true&smoothing=7&country=DEU~GBR~ITA~AUT~USA~MKD~FRA~AUS~CHE~IRL~BEL~NLD~IRN~DNK~ECU~CAN~SRB~CHN

Show necessary decimal places to differentiate axis ticks

---

site/client/Footnote.tsx
site/server/formatting.tsx

Currently, `React.hydrate()` duplicates every `<a>` element we have, since it can only hydrate _into_ a wrapper element, not replace one:
In fact I made the exact same mistake myself at some point, but didn't catch it when you @danielgavrilov pushed your changes.
The `onTrigger` and `onUntrigger` callbacks of Tippy together catch every `click` event on the link.

Don't duplicate <a> element when hydrating footnotes

---

admin/client/Forms.tsx
admin/client/admin.scss

As discussed in Slack (https://owid.slack.com/archives/C5BDCB2R3/p15906768430756009), since this was possible with the old one.

Map color picker can be reset to default color

---

charts/DiscreteBarChart.tsx

For the discussion here: https://owid.slack.com/archives/C46U9LXRR/p1590442732000300
When dragging the timeline there's _still_ some padding going on, but to a lesser extent:

DiscreteBar: only show padding for negative values when needed

---

charts/Controls.tsx

Goals:
- reduce unnecessary traffic
- get a slightly clearer picture of actual impressions on external sites (as opposed to charts loaded below the fold and never scrolled to)

Lazy load iframes

---

charts/ChartLayout.tsx
charts/ChartView.tsx
charts/Controls.tsx
charts/HeightedLegend.tsx
charts/HorizontalAxis.tsx
charts/LabelledSlopes.tsx
charts/VerticalAxis.tsx
charts/client/chart.scss

Very fiddly implementation! I hope I never have to touch this code again. 😄 
The immediate thing this fixes is support for `paddingBottom` in order to fix [Log/lin toggle covers x-axis footnote sometimes](https://www.notion.so/owid/Log-lin-toggle-covers-x-axis-footnote-sometimes-6893edce6a30450f84adc9bbff6c12a5).
@breck7 It would be great if you can look through and let me know if you notice anything weird or anything that should be explained.
I drew this diagram to try to understand what is going on, but sadly we live in an era where code is written in plaintext so I can't embed it:

ControlsOverlay: Support padding in any direction

---

.bundlewatch.config.json
.github/workflows/bundlewatch.yml
.travis.yml
package.json
yarn.lock

I hope this works.
I tried this in my own fork and it seemed to work there (https://github.com/MarcelGerber/owid-grapher/pull/4).
Todo:
Obviously we'll only see whether the PR status works once the token is in place.

Replace bundlesize with bundlewatch

---

admin/server/adminViews.tsx
settings.ts

This enables browser security features for our session token:
* HttpOnly ensures the cookie cannot be read using `document.cookie`, so nefarious code on the client side cannot obtain the token.
* SameSite=Strict will never send the cookie with cross-site requests, and provides protection against cross-site request forgery attacks.
* Secure means the token will only ever be sent over encrypted connections.
It is disabled in a development environment since most localhost connections are not running over https.
This is in line with the session cookie recommendations from OWASP: https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html#cookies

Session cookie hardening

---

yarn.lock

So, yarn duplicates some modules when installing.
For some this is necessary since their specified versions are not compatible with one another, but for others this is just something yarn does.
There's the [`yarn-deduplicate`](https://www.npmjs.com/package/yarn-deduplicate) package available to clean up the lock file and merge unneeded duplicates. The package also has a pretty good documentation with examples and stuff to explain what's going on.
So I ran `npx yarn-deduplicate`... and voila, our `node_modules` folder is 120MB smaller already 🎉
For reference, here is the log with the changed packages:
<details>
<summary>Log</summary>
```
Package "@babel/runtime" wants ^7.0.0 and could get 7.9.2, but got 7.4.5
Package "@babel/runtime" wants ^7.1.2 and could get 7.9.2, but got 7.4.5
Package …
```

Deduplicate yarn modules

---

admin/client/ChartEditorPage.tsx
admin/client/VisionDeficiencies.tsx

The effects work with SVG color filters, which are taken from here: https://github.com/hail2u/color-blindness-emulation/blob/master/filters.svg?short_path=5708e81
These filters can then be applied as CSS filters, using something like `filter: url(#deuteranopia)`.

Ability to emulate vision deficiencies in the grapher admin

---

charts/covidDataExplorer/CovidDataUtils.ts

As [Max pointed out](https://owid.slack.com/archives/C5BDCB2R3/p1592864662018900):
https://ourworldindata.org/coronavirus-data-explorer?zoomToSelection=true&positiveTestRate=true&dailyFreq=true&perCapita=true&smoothing=7&country=~MYS

CovidDataExplorer: Show 1 decimal place is metric is rate

---

admin/server/LoginPage.tsx
admin/server/RegisterPage.tsx

This is just something I came across when looking through the code.
It especially bugs me since the stylesheets this refers to are still from the Bootstrap 4 alpha, whereas we obviously are using a more recent version by now.

Don't use hardcoded bootstrap stylesheet for login & register pages

---

site/client/css/pages/chart.scss
site/server/views/ChartPage.tsx

This improves the styles for our fallbacks elements when JS is disabled (`<noscript>`) or fails.
| | |
| :--- | :--- |
| ![image](https://user-images.githubusercontent.com/2641501/85399664-7650a400-b557-11ea-9276-ede643e1b52c.png) | ![image](https://user-images.githubusercontent.com/2641501/85399884-d6dfe100-b557-11ea-8cd9-430f574b559d.png) |
| | |
| :--- | :--- |
| ![image](https://user-images.githubusercontent.com/2641501/85400016-0bec3380-b558-11ea-8818-8c47431fde88.png) | ![image](https://user-images.githubusercontent.com/2641501/85400053-1ad2e600-b558-11ea-8d82-7d8556ffbaef.png) |

Improve fallback styles

---

admin/client/CountryStandardizerPage.tsx

Charlie had problems using the Country Standardizer tool and I'm seeing these too, so these should hopefully fix these.
The issues are as following:
* Upon selecting an input format, the `<select>` jumps back to "Non-default country name"
* Same for the output format ("Our World in Data Name")
* For this reason, it's also not possible to change back to the default after a value was changed
* For some reason, the mobx `reaction` that fetched the country name mapping didn't trigger when `inputFormat` changed, only for `outputFormat`

Fix some problems with the Country Standardizer

---

charts/__tests__/CovidChartUrl.test.ts
charts/__tests__/CovidExplorerTable.test.ts
charts/covidDataExplorer/CovidChartUrl.ts
charts/covidDataExplorer/CovidDataExplorer.tsx
charts/covidDataExplorer/CovidExplorerTable.ts
charts/owidData/OwidTable.ts

This moves toward a new selection system and fixes a few issues.
On scatterplots, unselected groups (like World, EU, etc) are now filtered.
Before:
After:
Selection now also trumps filtering:
Viewing aligned and then selecting "World":
Hiding small countries then selecting "Iceland":

Selection issues fixes

---

site/client/css/components/lightbox.scss

Fixes the issue with the Germany Covid post, mentioned here: https://owid.slack.com/archives/C46U9LXRR/p1593820854047200

Use white background in lightbox

---

charts/ChartConfig.tsx
charts/ChartUrl.ts
charts/Util.ts
charts/__tests__/ChartUrl.test.ts
charts/covidDataExplorer/CovidChartUrl.ts
site/client/EmbedChart.tsx
site/client/Lightbox.tsx
site/client/SearchResults.tsx
site/client/blocks/ProminentLink/ProminentLink.tsx
site/client/blocks/index.ts
site/client/figures/ChartFigure.ts
site/client/figures/CovidExplorerFigure.ts
site/client/global-entity/GlobalEntitySelectionUrl.ts
site/server/formatting.tsx
utils/client/url.ts

This PR:
- syncs "Related Charts" links on pages with the floating country selector list of entities, adding to a link if the link already specifies entities on its own.
- renames `entitiesToQueryParams` to `entitiesToQueryParam` as the return value is a single query parameter
- creates a `splitURLintoPathAndQueryString` function
- makes Charts with disabled "Add country" buttons ignore entity query parameters
Check it out live at: https://nightingale-owid.netlify.app/covid-deaths
Note, we will eventually need to isolate out a `RelatedChartLink` component out of the `ProminentLink` component on the Wordpress, especially if the floating country selector expands to appear across the website.

"Related Charts" dynamic links

---

admin/client/ChartEditor.ts
admin/client/DimensionCard.tsx
charts/ChartDimension.ts
charts/DataTableTransform.ts
charts/covidDataExplorer/CovidDataExplorer.tsx
charts/covidDataExplorer/CovidExplorerTable.ts
charts/owidData/OwidVariable.ts

This PR allows one to select whether a chart's DataTable should show Absolute and/or Relative columns for individual dimensions. This behavior extends to the source charts for the Data Explorer.
The controls can be found on the Basic tab under the individual dimension dropdowns.

Editor option to control DataTable column selection

---

charts/ChartConfig.tsx
charts/ChartUrl.ts
charts/HTMLTimeline.tsx
charts/Util.ts
charts/__tests__/OwidTable.test.ts
charts/__tests__/Util.test.ts
charts/covidDataExplorer/CommandPalette.tsx
charts/covidDataExplorer/CovidChartUrl.ts
charts/covidDataExplorer/CovidDataExplorer.tsx
charts/covidDataExplorer/CovidExplorerTable.ts
charts/covidDataExplorer/CovidTypes.ts
charts/owidData/OwidTable.ts
site/client/Analytics.ts
site/client/css/pages/commandPalette.scss
site/client/owid.scss
stories/index.stories.tsx

This adds keyboard shortcuts and a clickable help menu (placeholder design for now).  Color schemes can be toggled and dimensions as well.
Shortcuts are not enabled on the baked pages.
I'm thinking of putting it behind some sort of feature flag and/or removing the dimension changing commands for now.

New: color options, keyboard shortcuts, more dimension options

---

charts/ChartConfig.tsx
charts/ChartDimensionWithOwidVariable.ts
charts/Controls.tsx
charts/DataTable.tsx
charts/DataTableTransform.ts
charts/HTMLTimeline.tsx
charts/Util.ts

With this PR, DataTables automatically select a start year where x>=50% of the entities have values. This is intended to reduce tables with an initial view of sparse data. This auto-selection will not trigger if the user has modified the timeline, the authors have specified a default timeline start year, or if the start year is set to the "latest" data.
Live on [Nightingale](https://nightingale-owid.netlify.app/).
~~Note: the Covid Data Explorer already has some lag when switching tabs that is now slightly exacerbated (when Table->Chart) by this code. I'm adding this as an issue [here](https://www.notion.so/owid/Lag-when-switching-tabs-in-CDE-491b7e8577104fd6bc722d163160e208) that I think we should address separately.~~ Fixed.
**Before:**
**After:**

Data Table Automatic Time Selection

---

admin/client/Admin.tsx
admin/client/AdminLayout.tsx
admin/client/VariableSelector.tsx
charts/ChartConfig.tsx
charts/ChartUrl.ts
charts/Controls.tsx
charts/DownloadTab.tsx
charts/ExploreModel.ts
charts/ExploreUrl.ts
charts/ExploreView.tsx
charts/__tests__/ExploreModel.test.ts
charts/__tests__/ExploreView.test.tsx
charts/covidDataExplorer/CovidDataExplorer.tsx

Often I hit runtime Mobx errors because observables are being changed by regular methods (or computeds). It seems it is recommended to enable the global 'enforceActions' (https://mobx.js.org/refguide/api.html#enforceactions) so an error is thrown if an observable is being updated not in a function with an `@action` decorator. My hope is that this will help make it easier to debug Mobx issues.
At first I tried the "always" setting, but that throws errors when default properties are initialized on object construction (https://github.com/mobxjs/mobx/issues/1702 if curious). So the "observed" setting makes more sense.

Turn on Mobx enforceActions flag

---

charts/DataTable.tsx
charts/SortIcon.tsx
charts/covidDataExplorer/CovidCountryPicker.tsx

This PR:
- changes the Explorer country picker icon to an alphanumeric icon when sorting by location, and sorts by largest quantities first
- sorts the DataTable columns by largest quantity first and improves icon selection
**Before:**
**After:**
**Before:**
**After:**

Sorting UI/UX improvements

---

charts/__tests__/CovidChartUrl.test.ts
charts/__tests__/CovidExplorerTable.test.ts
charts/covidDataExplorer/CovidChartUrl.ts
charts/covidDataExplorer/CovidConstants.ts
charts/covidDataExplorer/CovidDataExplorer.tsx
charts/covidDataExplorer/CovidExplorerControl.tsx
charts/covidDataExplorer/CovidExplorerTable.ts
charts/covidDataExplorer/CovidTypes.ts
charts/owidData/OwidTable.ts
site/client/Analytics.ts
site/client/css/pages/covidDataExplorer.scss
utils/client/react-select.tsx

This change adds 8 more chart views + 8 more map views to the Explorer.
It also changes the Interval control to a dropdown to accommodate the new options.
It changes the dailyFreq=true, totalFreq=true query param booleans to a single enum type instead.
New:

Add weekly, biweekly, and weekly/biweekly change options to Explorer

---

charts/ChartConfig.tsx
charts/ChartDimension.ts
charts/Controls.tsx
charts/DataTableTransform.ts
charts/HTMLTimeline.tsx
charts/Util.ts
charts/covidDataExplorer/CovidChartUrl.ts
charts/covidDataExplorer/CovidConstants.ts
charts/covidDataExplorer/CovidDataExplorer.tsx
charts/covidDataExplorer/CovidExplorerTable.ts

This PR creates a multimetric DataTable in the CDE. To enable this, add `&tableMetrics=` to the URL followed by a MetricKind a la `deaths`, `cases`, etc. This will force the DataTable for the explorer to show only the metrics you specify, according to the following format:
- `deaths`, `cases`, and `tests` will show both cumulative and daily numbers
- `case_fatality_rate`, `tests_per_case`, and `positive_test_rate` will show only cumulative numbers
The only control that should affect the view is the `per capita` option. Otherwise, clicking "align outbreaks" will add continents to the table, but I didn't consider that necessarily worth changing as only the authors should be interacting with the controls anyways.
**You can see it live on Nightingale …

Multimetric CDE DataTable

---

charts/ChartConfig.tsx

As reported by max (https://owid.slack.com/archives/C46U9LXRR/p1596443291092100)

fix(slope): show correct start/end year in chart title

---

charts/MapProjections.ts

Looking at the Heap snapshot, the MapProjectionsKlass had a huge retained size. It seems we use mobx computed on that class purely for cacheing. But then when a chart uses those computeds, that creates a reference inside the singleton instance to that chart, and so that chart will never be GC'd. At least that's my working theory, without knowing the exact details of how computeds are implemented. Does this make sense?
Just computing the values in MapProjections statically seems to fix the issue, and the GC continually gets mem usage back down to 50MB or so in my ad hoc test harness. I haven't looked at whether computing these values on every load is efficient. If not we could just do our own simple on demand cacheing.
Before:
After:

Dev: memory leak fix. Map projections was keeping a ref to all charts preventing GC

---

charts/ChartUrl.ts
charts/__tests__/ChartUrl.test.ts

See https://www.notion.so/owid/Time-param-should-not-end-in-3e114bad62ba4b6e95984e047fc306db
This is because services like Twitter don't recognize URLs ending in `..` correctly, so we now always generate URLs like `2000..latest`, `earliest..2015` or `earliest..latest`.
There are also some new test cases for these new and the old URLs, which continue to work.

fix(chart url): unbounded time params  include "earliest" or "latest", respectively

---

package.json
webpack.config.js
yarn.lock

This is a better fix for the issue where an error message like this would show up during a build:
<details>
```
ERROR in ./node_modules/@emotion/core/dist/core.browser.esm.js
Module not found: Error: Can't resolve '@emotion/serialize' in '/home/owid/tmp/live-breck-tmp/node_modules/@emotion/core/dist'
@ ./node_modules/@emotion/core/dist/core.browser.esm.js 4:0-53 53:19-34 167:23-38 175:19-34 335:23-38
@ ./node_modules/react-select/async/dist/react-select.browser.esm.js
@ ./charts/IndicatorDropdown.tsx
@ ./charts/ExploreView.tsx
@ ./site/client/owid.entry.ts
```
</details>
Turns out this is documented behavior in webpack, and happens due to the reasons described in https://github.com/owid/owid-grapher/commit/aba10dbca8ac0bac7544fd1abf64e7495ec05b8a#r41260036.
From the webpack docs …

fix(webpack): "can't resolve module" error

---

charts/AxisBox.tsx
charts/AxisScale.ts
charts/HorizontalAxis.tsx
charts/VerticalAxis.tsx

(https://www.notion.so/owid/Fix-how-grid-lines-are-created-c8fab78c8a184dcd87e40dc100786d47)
This improves the placement and number of grid lines and ticks, especially for log axes.
Some comparisons (old/new):
Same on mobile (here there's only `10^x` and `5 * 10^x` grid lines, and most `5...` ticks are missing because of a collision):
Sadly, I don't yet have my "own" staging server where I could push this for you to try it out.
The heuristic (when using log scale) roughly works as follows:
* generate many potential tick marks using `d3`, which seems to always generate _all_ the ticks of the form `y * 10^x` for `0 < y < 10`
* assign different priorities to these tick marks: highest priority to ones of the form `10^x`, then `5 * 10^x`, then `2 * 10^x`
* keep the other, in-between ticks as …

Place more grid lines / ticks when using log scale

---

site/server/siteBaking.tsx

Turns out we've been lying the whole time, and have included charts that are not published or not indexable in the number shown on the front page.
This now includes exactly those charts that are listed on the "All charts" page.
_Before_: 3708 charts across 297 topics
_After_: 2968 charts across 297 topics

show correct number of charts on the front page

---

scripts/exportMetadata.ts

When running `./refresh.sh` from a staging server:
```
$ ts-node --transpile-only -r tsconfig-paths/register -r dotenv/config scripts/exportMetadata.ts --with-passwords /tmp/owid_metadata_with_passwords.sql
Exporting database structure and metadata to /tmp/owid_metadata_with_passwords.sql...
mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces
mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces
```
Adding the `--no-tablespaces` flag to the `mysqldump` commands silences the error (as described in the release doc: 
https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-31.html), although I'm unclear about the …

Fix exportMetadata script following MySQL 5.7.31 update

---

admin/client/TestIndexPage.tsx
admin/server/testPages.tsx
charts/ComparisonLineGenerator.ts
charts/__tests__/ComparisonLineGenerator.test.ts
package.json
yarn.lock

(https://www.notion.so/owid/Comparison-line-log-linear-issues-10b4a258ee994b3eb3a4bd705b9692d7)
Comparison line generation was quite bad for charts with log x axes, because some lines just wouldn't display because not enough data points could be created.
I also incorporated some other changes here, like:
* Parsing the expression only once instead of every time it is evaluated
* Increasing the number of sample points from 100 to 500, which sometimes helps with the "line resolution"
* Not falling back to `y = x` in case of an evaluation error
* Adding a test page (http://localhost:3030/admin/test/embeds?comparisonLines=true) for all comparison line charts
(notice how the `0.02%` lines was absent before)

Improve comparison line generation for log axes

---

admin/client/EditorColorScaleSection.tsx
charts/BinningStrategies.ts
charts/ColorLegendView.tsx
charts/ColorScale.ts
charts/ColorScaleConfig.ts
charts/MapData.ts
charts/MapTooltip.tsx
charts/Util.ts
charts/__tests__/BinningStrategies.test.ts
charts/__tests__/Util.test.ts
charts/covidDataExplorer/CovidDataExplorer.tsx
db/migration/1597151871804-ColorScaleStrategies.ts
package.json
yarn.lock

Notion: https://www.notion.so/owid/Improve-the-automatic-binning-algorithm-for-legend-bins-d6090ee49df5461aa6fd4fddc44d34a6
- Migrates a bunch of the color scale props that weren't named consistently
- Migrates all old charts to the `equalInterval` binning strategy
- Implements `ckmeans` and `quantiles` binning strategies
- Sets `ckmeans` as the new default binning strategy
- Allows configuring how many automatically-generated bins should be created
- Allows using the automatically-generated bins as a starting point (in the past, the bin brackets were hidden if automatic classification was selected)

Add ckmeans & quantiles binning strategies for color scales

---

charts/covidDataExplorer/CovidExplorerTable.ts
charts/owidData/OwidTable.ts

[Link to bug.](https://www.notion.so/owid/CDE-with-Per-Million-and-Unaligned-Outbreaks-doesn-t-show-any-data-or-axes-ee0dc032294441aab024cd44d2d6a469)
Live at [Nightingale](https://nightingale-owid.netlify.app/coronavirus-data-explorer?yScale=log&zoomToSelection=true&casesMetric=true&interval=smoothed&perCapita=true&smoothing=7&country=USA~GBR~CAN~BRA~AUS~IND~DEU~MEX~ZAF~COL~KOR~NOR~UGA~NGA&pickerMetric=location&pickerSort=asc).
**Before:**
**After:**

CDE Fix: Transform per capita after computing rolling averages

---

charts/LineChart.tsx

Notion: https://www.notion.so/owid/Annotation-is-cut-off-on-mobile-0114f4d6568c4ce48e25513edf7a163e
It's still not perfect, mind you, but at least now the actual numbers are visible in the tooltip, which is arguably the most important information in the tooltip.
Dev note: In the future, we probably should rework that use of a HTML table and use CSS grid instead. But I didn't want to go there for this simple fix.

Break lines in line chart tooltip, so the annotation is not cut off on mobile

---

site/client/css/mixins.scss
site/client/css/pages/homepage.scss
site/client/owid.scss
site/server/views/BlogIndexPage.tsx

(https://www.notion.so/owid/Change-wordpress-post-thumbnail-size-to-match-twitter-preview-card-aspect-ratio-5dd98184fd074caa93009f4be444bd95)
This changes the aspect ratio of the "Latest publications" and "All posts" preview images, from roughly 1.42 : 1 to 1.91 : 1.
Why 1.91 : 1, you may ask? Because that's the same aspect ratio Twitter and Facebook use, and this will as such make preview cards there look nicer.
Live on https://tufte-owid.netlify.app/

Change post thumbnail aspect ratio to be more in line with Twitter/Facebook

---

charts/DiscreteBarChart.tsx

... as mentioned earlier in [Slack](https://owid.slack.com/archives/C46U9LXRR/p1597956936008200).
Turns out this was a race condition between the d3 width animation and React re-rendering the bar with an updated width.
I tried several methods, and this one seems to be the nicest that also keeps the animation. But since I'm still new to d3 there might be a better solution, so please do comment if you know of a nicer solution.
Live at [Tufte](https://tufte-owid.netlify.app/grapher/political-regime-updated2016?tab=chart&time=latest)

Fix race condition in bar chart when quickly dragging timeline

---

charts/areaCharts/StackedArea.tsx
charts/areaCharts/StackedAreaTransform.ts
charts/axis/HorizontalAxis.tsx
charts/axis/VerticalAxis.tsx
charts/barCharts/DiscreteBarChart.tsx
charts/barCharts/DiscreteBarTransform.ts
charts/core/ChartData.ts
charts/core/ChartDimension.ts
charts/core/ChartTransform.ts
charts/lineCharts/LineChart.tsx
charts/mapCharts/ChoroplethMap.tsx
charts/mapCharts/MapData.ts
charts/scatterCharts/PointsWithLabels.tsx
charts/scatterCharts/ScatterTransform.ts
charts/scatterCharts/TimeScatter.tsx
charts/slopeCharts/LabelledSlopes.tsx
charts/utils/Util.test.ts
charts/utils/Util.ts

I've had a look at the sorts we're doing, and noticed that in the Covid explorer, `_.sortBy` uses up a surprising amount of time in the profiler.
Fixes included here (I tried to split them nicely into separate commits):
* Use `_.minBy` and `_.maxBy` where possible - many times we were sorting an array just to get the smallest or biggest value, which can obviously be done more efficiently (`O(n)` vs `O(n log n)`).
As an added bonus, it is also more expressive and its return type includes `undefined` for the case when the array is empty.
* In one case, use `sort(uniq(years))` instead of `sortedUniq(sort(years))` - turns out we have on the order of 25000 years there, and uniq-first is just way faster
* Introduce a custom, fast `sortNumeric` function that uses `arr.sort()`
In comparison to …

Performance improvements

---

charts/controls/Timeline.tsx
charts/core/chart.scss

**Live on [Nightingale.](https://nightingale-owid.netlify.app/grapher/number-without-clean-cooking-fuel?tab=chart)**
This PR:
- creates tooltips on the Timeline that show the currently selected date, and fade after 2 seconds.
- adds padding around the Timeline to make it easier to click.
- fixes a small Timeline bug where the Handle jumps on click.

Timeline Tooltips + Upgrades

---

db/wpdb.ts
explorer/admin/ExplorerBaker.tsx
explorer/admin/ExplorerContent.tsx
explorer/admin/ExplorerPage.tsx
explorer/client/ExplorerProgram.ts
explorer/client/explorer.scss
explorer/covidExplorer/covidExplorer.scss
site/server/formatting.tsx

Grabs the reusable block identified by `wpBlockId` in the switcher admin and displays it below the explorer (public view only).
Only for switcher explorers.

Add CMS content to the bottom of explorer pages

---

charts/axis/AxisBox.tsx
charts/axis/AxisScale.ts
charts/axis/AxisSpec.ts
charts/axis/HorizontalAxis.tsx
charts/barCharts/DiscreteBarChart.tsx
charts/barCharts/DiscreteBarTransform.ts
charts/controls/ScaleSelector.tsx
charts/core/ChartConstants.ts
charts/core/ChartUrl.ts
charts/lineCharts/LineChartTransform.ts
charts/scatterCharts/ComparisonLineGenerator.test.ts
charts/scatterCharts/ComparisonLineGenerator.ts
charts/scatterCharts/ScatterTransform.ts
charts/slopeCharts/LabelledSlopes.tsx
charts/utils/Util.test.ts
charts/utils/Util.ts
explorer/covidExplorer/CovidExplorer.tsx
explorer/covidExplorer/CovidParams.ts

Introduces a new enum `ScaleType` with values `log` and `linear`, and uses it throughout the code base.
This way it's easier to reason about where log axes are appearing, since we can just search for enum usages.

Make ScaleType an enum

---

charts/areaCharts/StackedArea.tsx
charts/barCharts/DiscreteBarChart.tsx
charts/barCharts/StackedBarChart.tsx
charts/controls/Controls.tsx
charts/core/ChartConfig.tsx
charts/core/ChartLayout.tsx
charts/core/ChartTab.tsx
charts/core/ChartView.tsx
charts/core/ChartViewContext.ts
charts/core/Footer.tsx
charts/core/NoDataOverlay.tsx
charts/core/Tooltip.tsx
charts/lineCharts/LineChart.stories.tsx
charts/lineCharts/LineChart.tsx
charts/lineCharts/LineChartTransform.ts
charts/lineCharts/LineLabels.tsx
charts/mapCharts/MapTooltip.tsx
charts/scatterCharts/TimeScatter.tsx

In order to add faceting, I think it's best to clean up all the chart code so the components of each chart can be tested independently. Then when we show many charts in one screen it will be a lot easier and more reliable.
This is a step in that direction. It ain't pretty yet, but it's slightly prettier than our current code.
The main things to be done are:
- remove globals like Context
- create interfaces with only the needed properties/methods instead of requiring chartConfig
- create stories and/or unit tests for each component so that we can sanity check the APIs
Before:
[No unit tests or stories]
After:

Dev: refactor LineChart so it is testable

---

charts/core/ChartUrl.jsdom.test.ts
charts/core/ChartUrl.ts
explorer/client/SwitcherExplorer.tsx

In the Switcher Explorer when you change charts, if the new chart has default params that match the user's current params, those will be dropped from the query string.
With this new flag that behavior can be turned off and user settings are preserved during chart switching.
Before:
After:

Dev: Energy Explorer params fix.

---

explorer/covidExplorer/CovidConstants.ts
explorer/covidExplorer/CovidExplorer.jsdom.test.tsx
explorer/covidExplorer/CovidExplorer.tsx
explorer/covidExplorer/CovidParams.ts

This PR allows the CDE "frequency" selector to change columns in the MultriMetric view.
If our explorers migrate into "chart-switchers", I hope to throw out all MultiMetric code and just build a chart with the desired view.
**[Live at Nightingale](https://nightingale-owid.netlify.app/coronavirus-data-explorer?tab=table&time=latest&country=&casesMetric=true&interval=weekly&smoothing=0&pickerMetric=location&pickerSort=asc&tableMetrics=cases~deaths~tests~tests_per_case~case_fatality_rate~positive_test_rate).**

CDE MultiMetric DataTable: Support Intervals

---

deploy/testcheck.sh
site/client/blocks/AdditionalInformation/additional-information.scss
site/client/css/content.scss
site/client/css/mixins.scss
site/client/css/page.scss
site/client/css/pages/countryPicker.scss
site/client/css/sidebar.scss
site/client/owid.scss

See http://localhost:3030/forests
Also applies to "All charts" blocks and explorer views.

More space for charts on mobile

---

droplet/live.crontab

At the moment, errors in cron tasks fail silently (from what I can see in the logs, postfix is not installed / configured properly, so no logs are sent).
This PR sends the output of non-zero exiting (failing) commands to our #errors channel.
(NB: the fix deploy-queue -> live-deploy-queue is already deployed).

Crontab reporting

---

adminSite/server/adminRouter.tsx
db/wpdb.ts
site/server/siteBaking.tsx

Unpublished posts were wrongly using the article template when being previewed.

Use post template when previewing unpublished posts

---

charts/utils/Util.ts

Returned "24undefined50" instead of "24.50"

"undefined" decimal separator with d3 formatting

---

adminSite/client/EditorBasicTab.tsx
explorer/covidExplorer/CovidExplorer.tsx
explorer/indicatorExplorer/ExplorableChartConfig.jsdom.test.ts
grapher/core/Grapher.tsx
grapher/core/GrapherConfig.ts
grapher/core/GrapherUrl.jsdom.test.ts
grapher/core/GrapherUrl.ts
grapher/core/GrapherView.stories.tsx
grapher/mapCharts/MapConfig.test.ts
grapher/mapCharts/MapConfig.ts
grapher/mapCharts/MapTransform.jsdom.test.tsx
grapher/mapCharts/MapTransform.ts
grapher/test/samples.ts
grapher/test/utils.ts
site/server/bakeChartsToImages.tsx
site/server/svgPngExport.tsx

Adds a few tests. Removes some code from the Grapher constructor.
Ditches the ugly 'useV2' for 'manuallyProvideData', which is a tiny bit more helpful.

Dev: start tests for MapConfig and MapTransform. Cleanup Grapher constructor

---

site/server/views/GrapherPage.tsx

Often I need to glance at the JSON config on a Grapher page. I think we should beautify it:
- Faster debuggability for us
- The size difference should be inconsequential over the wire after Gzipping
- Like the new trailing commas rule in Prettier, this might help when looking at diffs in owid-static
- In case other devs want to use our stuff later on, making it more visible in our source could be useful to them

Dev: beautify JSON output on Grapher page

---

adminSite/client/AdminApp.tsx
adminSite/client/AdminSidebar.tsx
adminSite/client/DeployStatusPage.tsx
adminSite/client/admin.scss
adminSite/server/apiRouter.ts
db/postUpdatedHook.ts
deploy/deploy.ts
deploy/queue.test.ts
deploy/queue.ts
deploy/types.ts
deploy/watch.ts
jest.config.js

As described on Notion issue: https://www.notion.so/owid/Create-deploy-status-page-in-Grapher-Admin-2e38fc965531418db65234297056c3d4
http://localhost:3030/admin/deploys
It helps have an easily accessible page for authors (and developers) to check whether their changes have been deployed. It's awkward to bug a colleague about this – authors would usually wait quite some time before reaching out to us.
This is just a first step – exposing the information that's already in the `.queue` and `.pending` files. Ideally, it would be **visible on the chart page itself** what the deploy status of the chart is – whether it's already published, pending or waiting.
We could also add more deploy info on this page, e.g. what commit is the admin server running currently, pull and parse commits from …

Deploy status page in Admin

---

grapher/mapCharts/MapTab.tsx

Related Slack discussion: https://owid.slack.com/archives/C46U9LXRR/p1599665841022600?thread_ts=1599557290.007100&cid=C46U9LXRR
@breck7 Do you perchance know why you changed it from `targetYear` to `targetYearProp` in [this commit](https://github.com/owid/owid-grapher/commit/a57bb35880586166f1183884e09e052a5895476b#diff-99f0978524a3e523eae3da0e5cba38eeR289)?
I just want to make sure this doesn't re-surface any other issues.
Basically the problem here was that `targetYearProp` can be `Infinity` (and is in this case), and `formatYear(Infinity)` is a very helpful (and verbose!) `undefined NaN, -0NaN`

Fix map tooltip date

---

grapher/axis/AxisViews.tsx
grapher/barCharts/DiscreteBarChart.tsx
grapher/chart/ChartLayout.tsx
grapher/chart/ChartTab.tsx
grapher/chart/ChartTransform.ts
grapher/controls/AddEntityButton.scss
grapher/controls/AddEntityButton.tsx
grapher/controls/CollapsibleList/CollapsibleList.jsdom.test.tsx
grapher/controls/CollapsibleList/CollapsibleList.scss
grapher/controls/CollapsibleList/CollapsibleList.tsx
grapher/controls/Controls.scss
grapher/controls/Controls.tsx
grapher/controls/ControlsRow.scss
grapher/controls/ControlsRow.tsx
grapher/controls/ScaleSelector.scss
grapher/controls/ScaleSelector.tsx
grapher/core/Grapher.tsx
grapher/core/GrapherView.tsx
grapher/core/grapher.scss
grapher/lineCharts/LineLabels.tsx
grapher/slopeCharts/LabelledSlopes.tsx
site/client/css/sidebar.scss
site/client/css/variables.scss

This PR moves inline controls and the vertical axis log/lin selector into a responsive `ControlsRow`.
In my next PR, I will move `ControlsRow` out of `ChartLayout` and into `LineChart`, etc.
**Live on [Nightingale](https://nightingale-owid.netlify.app/grapher/stunting-vs-level-of-prosperity-over-time).**

Condense Controls

---

db/model/Chart.ts
site/server/bakeChartsToImages.tsx
site/server/grapherUtil.ts
svgTester/SVGTester.tsx

Fixes the issue reported here: https://owid.slack.com/archives/C46U9LXRR/p1600640963003100
I checked and `getChartsBySlug` is only called in `bakeChartsToImages` and `SVGTester`, so this change should be safe.
For a more permanent solution we should really consider making chart slugs unique, though, so bugs like this don't happen again and again.

fix(baking): don't bake images of draft charts

---

grapher/chart/ChartTransform.ts
grapher/core/Grapher.tsx
grapher/dataTable/DataTable.jsdom.test.tsx
grapher/mapCharts/MapConfig.ts
grapher/mapCharts/MapTransform.ts

**This is a temporary fix.**
Notion issue: https://www.notion.so/owid/Map-shows-ranges-instead-of-single-date-d4b9ee92baf541faa9027966e609d359
- Corrected conversion from legacy interface: used to translate `map.year` → `map.time`, but the correct is `map.targetYear` → `map.time`
- There are existing code paths that pass different timeline brackets based on the tab, I just updated those to use the map config. It's better to implement the `TimeViz` interface, but I thought I'd keep this minimal to avoid conflicts.
cc @breck7

Use map config to generate timeline when tab = map

---

grapher/timeline/TimelineController.test.ts
grapher/timeline/TimelineController.ts

A few months ago we could [set an unbounded value (`"earliest"` or `"latest"`) by dragging past the timeline brackets](https://owid.slack.com/archives/C011F008G6S/p1586599539086300):
It seems we lost this feature at some point – not sure if intentionally or not?
This PR adds back that feature, as long as we want it.

Set unbounded value when dragging beyond timeline start/end

---

adminSite/client/ChartEditor.ts
adminSite/client/VariableSelector.tsx
adminSite/client/admin.scss
adminSite/server/apiRouter.ts
db/migration/1601548270564-AddArchivedNamespaceColumn.ts

Just some easy improvements:
- Can filter the namespaces dropdown (using `react-select`)
- Visually distinguish archived namespaces

VariableSelector namespaces dropdown improvements

---

grapher/dataTable/DataTable.scss
grapher/dataTable/DataTable.tsx
grapher/downloadTab/DownloadTab.scss

This PR cleans up the DataTable a bit, fixes some layout bugs, and adds a line hover effect.
**Live at [Nightingale](https://nightingale-owid.netlify.app/coronavirus-data-explorer?tab=table&zoomToSelection=true&time=2020-03-15..latest&country=MEX~IND~USA~ITA~BRA~GBR~FRA~ESP~PER&region=World&casesMetric=true&interval=smoothed&perCapita=true&smoothing=7&pickerMetric=total_deaths&pickerSort=desc).**
**Before:**
**After:**

DataTable Spiffification

---

coreTable/LegacyToOwidTable.test.ts
coreTable/LegacyToOwidTable.ts

Fixes https://www.notion.so/owid/Discrete-Bar-Chart-Wrong-orders-of-magnitude-in-labels-656f228827db44458de525a0d4573888
Turns out we were applying `conversionFactor` two times, once for the factor saved at the (less specific) variable level and once for the (more specific) one saved at the dimension/chart level.
@breck7 I don't know exactly if you had any further plans to drop `ChartDimension` or similar, so feel free to solve this differently.

fix: only apply `conversionFactor` once

---

grapher/scatterCharts/ConnectedScatterLegend.tsx
grapher/scatterCharts/ScatterPlotChart.tsx

I'm not sure if using `sidebarWidth` is the right way to go, or if we should rather introduce a new field (e.g. `legendWidth`) that's made for exactly this purpose.

fix: scatter legend too wide

---

grapher/core/Grapher.jsdom.test.ts
grapher/core/Grapher.tsx

Often I want to go back to the original (mostly when testing) and currently I need to manually clear the params in the browser and refresh.

New: add keyboard shortcut to clear query params

---

grapher/core/Grapher.tsx
grapher/dataTable/DataTable.tsx
grapher/timeline/TimelineComponent.tsx

This fixes a couple of the recent regressions in DataTables:
- Timeline not working on DataTables
- "Closest year" notices not formatting properly
Noticing now that embeds have separate issues -- will fix in a separate hotfix.

DataTable Regression Fixes

---

grapher/mapCharts/MapChart.tsx
grapher/text/TextWrap.test.ts
grapher/text/TextWrap.tsx

Fixes https://www.notion.so/owid/Categorial-map-legend-contains-entries-for-every-country-fa7f01e8ff524cc3ac12943bdc6a5840 and https://www.notion.so/owid/Hovering-over-map-legend-doesn-t-highlight-respective-countries-545a42f7acb148ef81f88da9dbc5e606
I also decided to remove `mainLegendLabel` since we're currently not using it (it's always an empty string). If there's any reason why we would want to use it again in the future, let me know and I'll revert that change.
During that work I also realised that `new TextWrap("")` returns a height of `-1.1`, so I fixed that, too, and added a test.

Map legend fixes

---

coreTable/CoreTable.test.ts
coreTable/CoreTable.ts
coreTable/CoreTableColumns.ts
coreTable/CoreTableConstants.ts
coreTable/InvalidCells.ts
coreTable/OwidTable.test.ts
coreTable/OwidTable.ts
explorer/covidExplorer/CovidAnnotations.ts
explorer/covidExplorer/CovidConstants.ts
explorer/covidExplorer/CovidExplorer.jsdom.test.tsx
explorer/covidExplorer/CovidExplorer.stories.tsx
explorer/covidExplorer/CovidExplorer.tsx
explorer/covidExplorer/CovidExplorerTable.test.ts
explorer/covidExplorer/CovidExplorerTable.ts
explorer/covidExplorer/CovidExplorerUtils.ts
explorer/covidExplorer/MegaCsv.ts
grapher/facetChart/FacetChart.stories.tsx
grapher/facetChart/FacetChart.test.ts
grapher/facetChart/FacetChart.tsx

This adds a "StorageEngine" concept so you can make a CoreTable from rows or columns. The latter is faster for a number of ops. It's a little clunky but decently tested and we can sharpen the design over time.
This restores *some* perf to CovidExplorer. Tomorrow I will do vector transforms for generating new columns and then next CovidExplorer should be faster than prod.
This should be good to merge into Next if anyone wants to. It's a decent number of lines so probably good to merge it before doing other related work on next.
Otherwise I will merge in the morning.
Other minor thing:
- Adds `table.dump()` method, which just calls console.table. Very pretty table printing in dev tools and/or nodejs.

Add support for Vectorization

---

coreTable/CoreTable.ts
coreTable/CoreTableColumns.ts
coreTable/CoreTableUtils.test.ts
coreTable/CoreTableUtils.ts
coreTable/OwidTable.ts
explorer/covidExplorer/.gitignore
explorer/covidExplorer/CovidExplorerTable.ts
explorer/covidExplorer/perfTest.ts

This adds a dead simple decorator `@imemo` for memoizing compute-heavy getters that will never change. (I'm actually probably still using this too much, as some of these getters are not compute heavy). I'm not attached to the name just picked something unique.
I then replace mobx `@computeds`  with `@imemo`. CoreTables are immutable so once you call a getter the result will never change. No need then for any tracking overhead.
We still have some Mobx computed and actions in Tables for selection, but the selection concept should probably move to Grapher anyway.
3 perf runs:
Before:
1593ms csv to covid explorer table
6945ms csv to covid explorer table with every possible column
1637ms csv to covid explorer table
7136ms csv to covid explorer table with every possible column
1581ms csv to …

Switch from computes in CoreTable to simple memoization decorator

---

coreTable/CoreTable.test.ts
coreTable/CoreTable.ts
coreTable/CoreTableColumns.ts
coreTable/CoreTableConstants.ts
coreTable/CoreTableUtils.test.ts
coreTable/CoreTableUtils.ts
coreTable/LegacyToOwidTable.ts
coreTable/OwidTable.test.ts
coreTable/OwidTable.ts
explorer/client/SwitcherExplorer.tsx
explorer/covidExplorer/CovidConstants.ts
explorer/covidExplorer/CovidExplorerTable.test.ts
explorer/covidExplorer/CovidExplorerTable.ts
explorer/covidExplorer/CovidExplorerUtils.ts
explorer/covidExplorer/MegaCsv.ts
explorer/covidExplorer/perfTest.ts
grapher/chart/ChartDimension.test.ts
grapher/controls/countryPicker/CountryPicker.stories.tsx
grapher/controls/countryPicker/CountryPicker.tsx
grapher/core/Grapher.tsx
grapher/dataTable/DataTable.tsx
grapher/downloadTab/DownloadTab.tsx
grapher/utils/Util.test.ts
grapher/utils/Util.ts

Just simplifying CoreTable a bit:
- A `ColumnStore` is just basically:  { [columnSlug: string] : number|string[] } 
- Input data can be from CSV, Rows, or Columns `delimited: string | {}[] | ColumnStore`
- Any data passed into a table is immediately converted into a ColumnStore if not already one
- All operations are then performed on Columns
You can still use row methods and they behave as expected, but it is better to use column methods because they are noticeably faster when your data is in the 100K+ value range (like the MegaCSV set).

Migrate row operations to column operations

---

coreTable/LegacyToOwidTable.test.ts
coreTable/LegacyToOwidTable.ts

Quick fix for https://www.notion.so/owid/Chart-timeline-and-or-entities-may-be-truncated-02e0bf42622c431ba42ef77dbdfae826
The alternative, better way is to use the column store and new table joins, but this is quicker.

Fix: Ensure all column slugs are present in all rows in legacy conversion

---

coreTable/CoreTable.test.ts
coreTable/CoreTable.ts
coreTable/CoreTableColumns.ts
coreTable/CoreTableConstants.ts
coreTable/CoreTableUtils.ts
explorer/covidExplorer/CovidExplorer.stories.tsx
explorer/covidExplorer/CovidExplorer.tsx
explorer/covidExplorer/CovidExplorerTable.test.ts
explorer/covidExplorer/CovidExplorerUtils.ts
explorer/covidExplorer/MegaCsv.ts
explorer/covidExplorer/perfTest.ts

I am switching off perf for now to work on other issues but wanted to merge this in.
This adds general "groupBy" and "reduce" methods. The benefits of having these general GroupBy/Reduce methods, in addition to fixing this perf, will be that we may find them useful elsewhere for new functionality.
It also separates the (now) slowest part of loading the CE into an `addGroups` method in MegaCsv.ts. Next step would be to use the new methods for that method. My other branch does that but haven't optimized perf yet.
I also turned the plain `boolean[]` filter mask into a tiny class. There's some perf gains that can be had in filtering and just took a step in that direction.
I also turned the table.concat method from accepting a single table to an array of tables which makes more sense.
Finally, …

Dev: add group and reduce methods to CoreTable. Add perf test harness for CE

---

coreTable/OwidTableConstants.ts
explorer/covidExplorer/CovidExplorer.tsx
explorer/covidExplorer/CovidExplorerTable.ts
explorer/covidExplorer/CovidParams.ts
explorer/covidExplorer/MegaCsv.ts
grapher/dataTable/DataTable.tsx

Variety of fixes for the CovidExplorer DataTables.
This adds back titles, units, data, and source grapher data.
Still need to restore MultiMetric DataTables, but need to repair CovidExplorer query params first.

Restore CovidExplorer Datatables

---

explorer/covidExplorer/CovidExplorer.tsx

This PR fixes issues with the CovidExplorer URL:
- country param now reflects actual selection
- CovidExplorer URL now includes tab and year selection from the Grapher
- CovidExplorer now feeds its params to the Grapher
Unrelatedly, it also removes an unused `perCapitaTitle` function.

CovidExplorer Query Params Fixes

---

grapher/slopeCharts/SlopeChart.tsx

Courtesy of @danielgavrilov. I checked and it seems to work across all our Slope Charts.

Fix: SlopeChart legend contains countries instead of continents

---

grapher/mapCharts/MapChart.tsx
grapher/mapCharts/MapColorLegends.tsx

This fixes special snowflake charts like this one http://localhost:3030/grapher/yaws-status-and-case-numbers, which display both a categorical and a numeric legend.
This fix is very ugly, but somehow `legendY` needs to know whether the requesting legend is a numeric or categorical one. And it works.
Please let me know if you can think of a better way to solve this issue, I'm all ears.

fix: if a map displays two legends, don't overlay them over one another

---

grapher/core/Grapher.tsx
grapher/core/GrapherWithChartTypes.jsdom.test.tsx

Tiny change -- makes it so that the timelineHandles use the closest data point to the query string `time` param instead of the param itself.

Unskip Map Tests

---

coreTable/CoreTable.ts
coreTable/CoreTableColumns.ts
coreTable/OwidTable.ts
grapher/core/Grapher.tsx
grapher/mapCharts/MapChart.tsx
grapher/mapCharts/MapTooltip.tsx
grapher/scatterCharts/ScatterPlotChart.tsx
grapher/slopeCharts/SlopeChart.tsx

There are a bunch in the `CovidExplorer` that I didn't fix, let me know if I should.
Also, some of these checks may be redundant – I wasn't paying attention to that, just trying to get it to the previous state.
Also, no tests added, and it seems it might be a bit of an effort to design test cases for all?

Fix: Use isMissing instead of undefined column check

---

tsconfig.client.json
tsconfig.json

Having [recently bumped the es version in tsconfigs](https://github.com/owid/owid-grapher/commit/467c48765931c32f79bde6bc5161868a2d9522a8) (from es7 to es2020), I believe `esnext.asynciterable` is now redundant as it was made part of ES2018 (see https://developer.mozilla.org/en-US/docs/Archive/Web/JavaScript/ECMAScript_Next_support_in_Mozilla).

Remove redundant esnext.asynciterable in tsconfig

---

coreTable/CoreColumnDef.ts
coreTable/CoreTableColumns.ts
coreTable/OwidSource.ts
grapher/core/Grapher.tsx
grapher/sourcesTab/SourcesTab.tsx

Allows authors to directly put source info into an Explorer. It does not connect to Grapher backend so there would be some copy/pasting in the short-run. I think in the medium-run it makes sense to move all column definitions to Git.
I believe in Live we only have the ability to define a source for a dataset, and variables pull sources from the dataset they were uploaded with. So it's a little duplicative storing source info at the column level. But something we could do later.

New: authors can now define column source information in Explorers

---

coreTable/CoreTable.ts
coreTable/CoreTableConstants.ts
coreTable/OwidTable.ts

Turns out, [that change](https://github.com/owid/owid-grapher/commit/fb9a851a5d2cfadc29d07453760f23fed7d84365) broke [relative mode](https://tufte.owid.cloud/admin/test/embeds?ids=619) again.
As a quick stopgap, this introduces a new transform type `UpdateColumnDefsAndApply` (naming up for debate) that recomputes values, whereas the "standard" `UpdateColumnDefs` one doesn't.
Without this fix `toPercentageFromEachColumnForEachEntityAndTime` is broken.

fix: introduce new transform type `UpdateColumnDefsAndApply`

---

adminSite/client/EditorMapTab.tsx

For https://www.notion.so/owid/Admin-Manual-map-buckets-not-shown-b6151aa52365429ba4d77b590135c0d0
This seems very brittle, but also seems to work.
If there's a better way to do this please let me know, because this doesn't feel like it's the right way.

fix(admin): enable editing of buckets for map charts

---

adminSite/client/ChartList.tsx
adminSite/server/apiRouter.ts

This is not really a regression on `next` but is already to be seen on live: On the admin landing page, some line charts display a type of "Unknown" in the type column.
This happens because `Grapher.tsx` strips off all default values, and the default value for the chart type is `LineChart`. Therefore the `charts.json` response includes `type: null` for those charts.
If there's a better way to fix this please let me know :)

fix(admin): AdminIndexPage displays correct chart type for line charts

---

coreTable/CoreTableUtils.ts
coreTable/OwidTable.ts
coreTable/OwidTableUtil.ts
grapher/scatterCharts/ScatterPlotChart.test.ts
grapher/scatterCharts/ScatterPlotChart.tsx
grapher/selection/SelectionArray.ts
grapher/utils/Util.test.ts
grapher/utils/Util.ts

The tolerance used to be applied independently to X and Y column, which meant e.g. a constant Y value from a single year would be used as X changes over time, creating some "staircases":
Before:
Now:
Related discussion on Slack: https://owid.slack.com/archives/C01D295TM4K/p1605193993004700
To-do:
- ~~Drop any duplicate points? This needs to happen after the timeline filter. But it needs to minimize the difference between `timeValue` and `time.x`.~~ The `endPointsOnly` transform also gets more complex if we drop duplicates, so I decided to leave duplicates unless they cause problems. No problems spotted so far...

New ScatterPlot interpolation: a value can belong only to a single point

---

site/server/SiteBaker.tsx

This would hopefully prevent the daily deploy errors we get, while preserving a full log of deploys (even empty ones) in the git repo.
Notion issue: https://www.notion.so/owid/Empty-serverUtil-Error-from-empty-deploy-2b91b1b5fd964ce59d67890d5a7ccf54

Allow empty deploy commits

---

grapher/noDataModal/NoDataModal.scss
grapher/scatterCharts/ScatterPlotChart.tsx
grapher/scatterCharts/ScatterPlotChartConstants.ts

Show helpful message on single-year ScatterPlot avg annual change

---

coreTable/CoreTable.ts
coreTable/CoreTableUtils.ts
coreTable/OwidTableSynthesizers.ts
grapher/barCharts/DiscreteBarChart.test.ts
grapher/barCharts/DiscreteBarChart.tsx
grapher/lineCharts/LineChart.test.ts
grapher/lineCharts/LineChart.tsx
grapher/slopeCharts/SlopeChart.test.ts
grapher/slopeCharts/SlopeChart.tsx
grapher/stackedCharts/AbstractStackedChart.tsx
grapher/stackedCharts/StackedAreaChart.test.ts
grapher/stackedCharts/StackedBarChart.test.ts

Notion issue: https://www.notion.so/owid/StackedArea-LineChart-DiscreteBar-crash-when-data-contains-non-numeric-vaue-8b1b59ed3ae74d0fa40b004590c694cc

Fix: replace non-numeric cells with errors for charts that don't support them

---

adminSite/client/DatasetEditPage.tsx
baker/GrapherImageBaker.tsx
explorer/admin/ExplorerBaker.tsx
explorer/admin/ExplorerPage.tsx
explorer/client/Explorer.scss
explorer/client/Explorer.tsx
explorer/client/ExplorerConstants.ts
grapher/captionedChart/Logos.tsx
grapher/controls/Controls.tsx
grapher/controls/EntitySelectorModal.scss
grapher/controls/ShareMenu.scss
grapher/core/Grapher.stories.tsx
grapher/core/Grapher.tsx
grapher/core/GrapherConstants.ts
grapher/core/grapher.scss
grapher/footer/Footer.tsx
grapher/footer/FooterManager.ts
grapher/header/Header.tsx
grapher/header/HeaderManager.ts
grapher/sourcesTab/SourcesTab.scss
site/client/EmbedChart.tsx
site/client/css/pages/chart.scss
site/client/figures/MultiEmbedder.tsx
site/client/owid.entry.ts
site/client/runVariableCountryPage.tsx
site/server/views/EmbedDetector.tsx
site/server/views/GrapherPage.tsx
site/server/views/IframeDetector.tsx

Just trying to cleanup the "isEmbed" style properties a bit, and remove any general css classes like "chart" and "iframe". Ideally we can get our SCSS and TypeScript linking to the same identifiers at some point.

Embed cleanup

---

grapher/axis/AxisConfig.ts
grapher/axis/AxisViews.tsx
grapher/barCharts/DiscreteBarChart.tsx
grapher/captionedChart/CaptionedChart.stories.tsx
grapher/captionedChart/CaptionedChart.tsx
grapher/chart/ChartManager.ts
grapher/controls/ScaleSelector.scss
grapher/controls/ScaleSelector.stories.tsx
grapher/controls/ScaleSelector.tsx
grapher/core/Grapher.tsx
grapher/lineCharts/LineChart.tsx
grapher/scatterCharts/ScatterPlotChart.tsx
grapher/stackedCharts/StackedAreaChart.tsx

Some may say UX is better; some may say it's a slight regression; but 99% of our charts don't have and xScale toggle, and we can always iterate later if we want.
The current implementation was as simple as could be and yet still a decently complex 100 lines interweaved in a few classes (You have to do collision detection amongst other things). Other more important things for now :).
Before/after

Move xScale log lin toggle to controls row.

---

adminSite/client/ChartEditor.ts
adminSite/client/DimensionCard.tsx
coreTable/LegacyToOwidTable.ts
coreTable/LegacyVariableCode.ts
grapher/core/Grapher.tsx

Dimension-level colors can now be edited in the admin. Can't merge until I finish column re-ordering early tomorrow.

Fix: custom dimension colors in admin

---

adminSiteServer/adminRouter.tsx
adminSiteServer/apiRouter.ts
explorerAdmin/ExplorerCreatePage.tsx
explorerAdmin/ExplorersListPage.tsx
gitCms/GitCms.test.ts
gitCms/GitCmsClient.test.ts
gitCms/GitCmsClient.ts
gitCms/GitCmsConstants.ts
gitCms/GitCmsServer.test.ts
gitCms/GitCmsServer.ts

Now that GitCMS is in the hot path, it needed some love. I tried a few approaches and think it's best to actually create an express server, hit it from the client, write to disk, git commit, etc. But would love feedback on this, and where things could be improved.
Before:
After:

Add GitCMS integration tests

---

gitCms/GitCms.test.ts
gitCms/GitCmsServer.ts

It wasn't running correctly since git _always_ needs `user.name` and `user.email` set in some config somewhere, even if it's always passed as `--author=` arg for every command.
Thus, we now set it in the repo-local config.
See https://stackoverflow.com/q/29685337/10670163 for example, which is about just this issue.
cc @breck7

test: fix GitCms test on CI

---

site/server/views/LongFormPage.tsx

Manually matches https://ourworldindata.org/faqs#can-i-redistribute-your-data
Not pulling content out of a reusable block automatically as it might not be obvious down the line that updating the FAQ updates the citation note at the bottom of articles.

Update citation note

---

grapher/color/ColorScale.ts

This fixes a recurring issue that was [reported in Slack](https://owid.slack.com/archives/C46U9LXRR/p1608119235000600) multiple times in the last few days, where the color scale outlier detection would remove all values except for 0 and the authors couldn't assign map brackets etc.
I'm going to merge this in already so this can go live, but please take a quick look at it to see if this all makes sense.
Also, it looks like we don't currently have tests for `ColorScale` methods? This would really benefit from tests...
**Before:**
**After:**

fix(colorScale): don't remove outliers if that would mean we end up with only one distinct value

---

.gitignore
baker/GrapherBaker.tsx
baker/SiteBaker.tsx
baker/buildLocalBake.ts
baker/countryProfiles.tsx
package.json

Just split the body of "bakeAll" into 2 methods for baking Wordpress parts of site and the rest. that way you can dive in and debug the Grapher parts of the bake (which are slow and have a lot of room for improvement) without having to have the wordpress part running.

Decouple baking of Grapher and Wordpress

---

grapher/core/Grapher.tsx

Notion: https://www.notion.so/owid/Source-tab-is-empty-and-no-source-below-charts-edc8f4b52be1473ba3792aa4351aaed7
This also fixes the exclusion of the variables "Countries Continent" and "Total population (Gapminder, HYDE & UN)", which wasn't working on live. That's a slight behavior change in the sources line (marked in red), but I think that's for the better:
(same in the Sources tab, where these two entries are now also absent)

fix(sources): sources tab and text no longer empty

---

grapher/timeline/TimelineComponent.tsx
grapher/timeline/TimelineController.ts

I _think_ it was introduced when we had the timeline dragging freely without snapping. Now that it always snaps to available years, it's not necessary.
The fact that it snaps on `≤1` also causes this bug where you can't select a range that's only 1 time step apart: 
https://user-images.githubusercontent.com/1308115/103649389-48acd480-4f56-11eb-8095-91597c521afc.mov
Reported here: https://owid.slack.com/archives/C46U9LXRR/p1609849260000400

Remove Timeline#snapTimes()

---

explorer/Explorer.tsx
grapher/controls/ShareMenu.tsx
grapher/core/Grapher.tsx

Notion: https://www.notion.so/owid/Embed-code-missing-url-and-hideControls-param-d08ae86bd229421ba897afc9b2a944b9
This fixes 3 issues we had:
* the `hideControls=true` param (as part of the patch) works
* the embed dialog shows the correct URL, including the base URL
* the "Hide controls" toggle at the bottom of the embed dialog is restored (it's still not integrated in a super clean way, but I think it's better than before at least, and more extensible)

Embed dialog: correct URL, hideControls toggle, hideControls works

---

coreTable/CoreTableUtils.test.ts
coreTable/CoreTableUtils.ts
package.json
yarn.lock

In my search for performance issues in `next`, I noticed that `cartesianProduct` took a very long time.
It is called by `table.complete`, which in turn is called in our various tolerance methods.
I switched the cartesian product code over to use https://github.com/ehmicky/fast-cartesian instead, and the results speak for themselves:
When switching from "log" to "linear" in http://localhost:3030/grapher/GDP-vs-agriculture-employment, `cartesianProduct` takes:
* 936ms before (with our custom implementation)
* 24.5ms after (with https://github.com/ehmicky/fast-cartesian)
We still would want to look for further optimizations in the future to make things faster, but that's a great first step already and we may need a fast cartesian product in the future, too!

perf: way faster cartesian product using `fast-cartesian`

---

adminSiteServer/IndexPage.tsx
adminSiteServer/app.tsx
site/webpackUtils.tsx

Even with #784, the admin site is still not working since it is loading its assets from the wrong path.
In fact, back before `itsJustJavascript`, there were two different methods to determine where to load an asset from: https://github.com/owid/owid-grapher/blob/57bf84c10266421cbff9bd6aa5474c4345d1bc48/utils/server/staticGen.tsx and https://github.com/owid/owid-grapher/blob/57bf84c10266421cbff9bd6aa5474c4345d1bc48/adminSite/server/utils/webpack.ts. One was for the admin server, the other for the actual site.
In this PR, I'm changing the URL where admin assets are delivered from `/admin/build` to `/admin/assets`, and can then just use `baseUrl: "/admin"` to load the correct one. I notice this is certainly not the cleanest solution, but it works and that's what we need most at the moment. …

fix(admin): use correct asset path

---

explorer/Explorer.jsdom.test.tsx
explorer/Explorer.sample.tsx
explorer/Explorer.tsx

Should fix [After changing an explorer to log scale, url doesn't revert when you change it back to linear](url) by giving each grapher its own query parameters.

fix: each grapher gets its own query params

---

adminSiteServer/IndexPage.tsx
adminSiteServer/mockSiteRouter.tsx
baker/SiteBaker.tsx
site/Head.tsx
site/SiteFooter.tsx
site/webpackUtils.tsx

So, the "Test embeds" page wasn't working since the asset URL was relative to the wrong server. The same problem also happened to the "Preview post" and "Preview explorer" pages.
These should now all be fixed, since _almost_ all of them are now using absolute paths rather than relative ones.

fix(admin): test embeds page works again

---

explorer/Explorer.jsdom.test.tsx
explorer/Explorer.sample.tsx
explorer/Explorer.tsx

Notion issue: https://www.notion.so/owid/selection-param-not-correctly-decoded-by-Explorer-518f9a5fdf2e46d7a8ca20146eb06321
@shaahmad Does that the one-line change for `persistedParams` look reasonable? Not sure if it might break something else, it was a shot in the dark 🎯

Recover Explorer selection from URL params on load

---

adminSiteClient/EditorColorScaleSection.tsx
clientUtils/Util.ts
coreTable/CoreColumnDef.ts
devTools/graphersToGit/.gitignore
devTools/graphersToGit/tasks.ts
explorer/ColumnGrammar.ts
explorer/Explorer.tsx
explorer/ExplorerGrammar.ts
explorer/ExplorerProgram.ts
grapher/chart/ChartUtils.tsx
grapher/color/BinningStrategies.test.ts
grapher/color/BinningStrategies.ts
grapher/color/BinningStrategy.ts
grapher/color/ColorScale.test.ts
grapher/color/ColorScale.ts
grapher/color/ColorScaleBin.ts
grapher/color/ColorScaleConfig.test.ts
grapher/color/ColorScaleConfig.ts
grapher/mapCharts/MapChart.tsx
grapher/scatterCharts/ScatterPlotChart.tsx
grapher/verticalColorLegend/VerticalColorLegend.tsx
gridLang/GridProgram.test.ts
gridLang/GridProgram.ts

Some additions to the work on #715.
- New `colorScale` columns:
- Tests for color bins DSL
- `VerticalColorLegend` now infers its numeric bin labels – we no longer have to specify them all by hand. This was necessary to implement because color scales are defined on column level, so it's the same definition for both Map and ScatterPlot.
(It's not ideal with the `<` and `>` but maybe we can figure that out another time)
---
@breck7 I didn't merge the last commit in #715: https://github.com/owid/owid-grapher/pull/715/commits/f8bca6641a375a00f3beaef352c530673a171127
It had some conflicts I wasn't sure how to resolve and just left it for later. Do you think it should be merged? I can try to merge again, or we can leave it as a low priority task.

Color scales for grid explorers

---

coreTable/CoreTableUtils.test.ts
coreTable/CoreTableUtils.ts
coreTable/OwidTable.test.ts
coreTable/OwidTable.ts
grapher/stackedCharts/AbstractStackedChart.tsx
grapher/stackedCharts/StackedAreaChart.test.ts
grapher/stackedCharts/StackedAreaChart.tsx
grapher/stackedCharts/StackedUtils.ts

Notion: https://www.notion.so/owid/Don-t-extrapolate-StackedArea-charts-at-start-end-where-some-variables-are-missing-values-70131dff17494705a042bc92e9dd7eb1
Prevents misleading stacked area charts where a variable was extrapolated (by simply copying over the closest known value) when they were not defined.
The behavior is different depending on whether we have a column-based series or an entity-based one.
For entity-based series, it is still showing the "full" time range, but showing "No data" for entities that are not present:
On the other hand, for column-based series it is only showing the time range where all columns have values:
(Here, "Fossil fuels and cement" has data before 1850, but it is not shown since there's no earlier data available for "Land use change").

fix(stacked): don't do extrapolation of variables

---

coreTable/CoreTableColumns.test.ts
coreTable/CoreTableColumns.ts
coreTable/OwidTable.test.ts

Notion: https://www.notion.so/owid/CSV-download-includes-human-formatted-numbers-451fab4d3aea4870bbb746af99b3343c
I just hope we _never_ have to apply some formatting to CSV-downloaded numbers 🤞, and there's not some rogue column type that needs formatValue in some way?
I at least checked that the unit conversion factor is respected in the value contained in the csv.
For reference, this was probably broken in https://github.com/owid/owid-grapher/commit/30e7773b65b62d48538d07a2560a7ae4369473ee

fix(csv): csv download no longer contains pretty-printed numbers

---

db/wpdb.ts

Switched to _.memoize (probably less confusing in this instance).
Regression introduced: https://github.com/owid/owid-grapher/commit/2dd7f0661ba6fe7fdfb1ad2a59b9ef7ed7a2ad9f#diff-ab0604f7a26be8d1267ef4e5fcec2f3e4a321c61a83a763796ac0710b7cac81bL553

Fix slow blog index baking

---

explorer/client/ExplorerControls.tsx
explorer/client/ExplorerShell.tsx
explorer/client/SwitcherExplorer.tsx
explorer/covidExplorer/CovidExplorer.tsx

Note: This PR is against _master_
Notion: https://www.notion.so/owid/Dropdowns-in-explorer-controls-overlay-mobile-should-scroll-0ca3cf675adc4a81b41409534fb847a5
This is a quick fix for the problem that the Interval dropdown in the Covid explorer, as well as the dropdowns in the CO2, cannot be fully used on mobile, since not all of the dropdown options cannot be reached and the dropdowns don't scroll.
Since we're facing the same issue on `next` still, I will make sure that this fix also makes its way into `next`!
Live on **hans**.

fix(explorer): dropdowns are completely in view on mobile

---

explorer/covidExplorer/CovidExplorerTable.ts

The current CovidExplorer creates its own client-side generated aggregates. 
In `next`, we will use the CSV aggregates.
In order to enable us to launch the new aggregates-included CSV for the Next explorer, without duplicating aggregates on the current explorer, it seems easiest/best to drop them on the current CovidExplorer and continue generating them the old way.

Remove CovidExplorer MegaCSV aggregates before processing

---

README.md

NVM seems to be the preferred way to install Node, as opposed to Brew. e.g.
https://www.reddit.com/r/node/comments/a9mwti/should_node_be_installed_with_homebrew_or/
https://jamesauble.medium.com/install-nvm-on-mac-with-brew-adb921fb92cc

Update README to use NVM

---

baker/GrapherBakingUtils.test.ts
baker/GrapherBakingUtils.ts
baker/GrapherImageBaker.tsx
urls/Url.test.ts
urls/Url.ts

Notion: https://www.notion.so/owid/Embedded-charts-without-query-strings-are-iframe-full-when-they-should-be-iframe-less-8a61cf7045884363a6247ac64af7574f
What I changed:
* `Url` drops a trailing `?` if the query string is empty
* Both `GrapherBakingUtils` and `GrapherImageBaker` use this Url class
* Also, they now have two common methods for extracting slug & queryStr from an embed URL, and combining these to a export filename. This way, the implementations can hopefully stay in sync in the future.
* I also added unit tests for these two util methods.

Embedded charts without query string get iframe-less embeds

---

adminSite/server/utils/authentication.tsx
wordpress/web/app/plugins/owid/src/authentication.php

With no active session, attempting to access a protected page redirects the user to the login page.
This PR uses the `redirect_to` (wordpress) and `next` (grapher) query parameters to redirect the user to the previously requested page upon successful login.
See https://www.notion.so/80f7bd92d1dd40aab3a9dea9858a7dd6

Return to requested protected page before login

---

clientUtils/Util.test.ts
clientUtils/Util.ts
clientUtils/url.test.ts
clientUtils/url.ts
coreTable/CoreTable.ts
devTools/tsconfigs/tsconfig.base.json
explorer/Explorer.tsx
explorer/urlMigrations/CO2UrlMigration.ts
explorer/urlMigrations/EnergyUrlMigration.ts
explorer/urlMigrations/ExplorerUrlMigrationUtils.ts
explorer/urlMigrations/ExplorerUrlMigrations.test.ts
explorer/urlMigrations/LegacyCovidUrlMigration.ts
grapher/controls/Controls.tsx
grapher/core/EntityUrlBuilder.test.ts
grapher/core/EntityUrlBuilder.ts
grapher/core/Grapher.jsdom.test.ts
grapher/core/Grapher.tsx
grapher/core/GrapherUrlMigrations.test.ts
grapher/core/GrapherUrlMigrations.ts
grapher/selection/SelectionArray.ts
patch/Patch.test.ts
patch/Patch.ts
site/SearchPageMain.tsx
site/SearchResults.tsx
site/blocks/ProminentLink.tsx
site/multiembedder/MultiEmbedder.tsx
urls/Url.test.ts
urls/Url.ts

Notion: https://www.notion.so/owid/Legacy-URLs-containing-are-broken-db43850218dd4c539d9968a60861be18
This deploy is live on _tufte_.
---
This took some time, and even more nerves, but here it finally is.
This PR makes URL encoding and decoding more consistent, by:
* Handling URL decoding as early as `strToQueryParams` (in `url.ts`) (but it still also returns the non-decoded version; more on that below)
* Handling URL encoding _exclusively_ in `queryParamsToStr` (in `url.ts`)
To exemplify the changed behaviour, this is what these two methods now do:
```ts
strToQueryParams("?country=Asia%20(excl.%20China%20&%20India)") == {
_original: { country: "Asia%20(excl.%20China%20&%20India)" },
decoded: { country: "Asia (excl. China & India)" }
}
queryParamsToStr({ country: "Asia (excl. China & …
```

rework URL encoding decoding such that it's more consistent

---

site/GrapherFigureView.tsx

Notion: https://www.notion.so/owid/Site-search-doesn-t-update-preview-chart-efd05ff4249240c2abe6afdfe905d325
This is an easy fix for the site search not updating when the query changes, and I hope it is a nice one too.

fix: site search updates preview chart when query changes

---

clientUtils/Util.ts
explorer/Explorer.jsdom.test.tsx
explorer/Explorer.tsx
explorer/urlMigrations/ExplorerUrlMigrations.test.ts
grapher/controls/globalEntitySelector/GlobalEntitySelector.tsx
grapher/core/EntityCodes.ts
grapher/core/EntityUrlBuilder.test.ts
grapher/core/EntityUrlBuilder.ts
grapher/core/Grapher.jsdom.test.ts
grapher/core/Grapher.tsx
grapher/core/GrapherUrlMigrations.test.ts
grapher/core/GrapherUrlMigrations.ts
site/SearchResults.tsx
site/blocks/ProminentLink.tsx
site/multiembedder/MultiEmbedder.tsx

Notion issue: [Revert back to using entity codes instead of entity names](https://www.notion.so/Revert-back-to-using-country-instead-of-selection-8963b354600649d898fb941e7d58c872)
- Use codes instead of names (`selection=USA` instead of `selection=United+States`)
I just made the changes in the query param accessors (now renamed to `getSelectedEntityNamesParam` and `setSelectedEntityNamesParam`). 
Ideally, in the future we'd move the _codes → names_ transformations outside the codebase, so they can be updated by authors (maybe using the chart data entity map as before? maybe an API?), but for now this is enough to preserve the URLs on live.

Revert to using entity codes instead of entity names

---

grapher/controls/EntitySelectorModal.tsx

Notion: https://www.notion.so/owid/Sort-countries-by-name-in-selection-dialog-416a238ed8bc40809422e4e2585fa1c3
This is quick fix.
We should probably put up an `EntitySelectorModal` cleanup on the list of things to do after Operation Merge is finished, because the split between `EntitySelectorSingle` and `EntitySelectorMulti` really is not great.
The fact that single was already sorted and multi was not is probably just one artifact of that split.

fix: EntitySelectorMulti sorts entities

---

grapher/core/Grapher.tsx

Notion: https://www.notion.so/owid/Some-charts-are-missing-a-timeline-0cc1f7ec43a04762bb8a19558313a0f1
I _think_ this is the correct logic for the timeline.
For reference, [this is the old logic behind this.](https://github.com/owid/owid-grapher/blob/3ec3750084c76bf49b426f022cc7c86385692d6b/grapher/core/GrapherView.tsx#L472-L486)
I also tested this somewhat, and it seems to do the job.
And, if you can think of a way to make the method more expressive / easier to understand the nested logic, please go for it!

fix: show timeline on map tab even if chart is StackedArea, StackedBar or DiscreteBar

---

explorer/Explorer.jsdom.test.tsx
explorer/Explorer.tsx

Notion issue: [Include all choice params in Explorer URL](https://www.notion.so/Include-all-choice-params-in-Explorer-URL-87b675a53a01460899edcc61b149b99a).
> Is it a good idea to include all Explorer params (metric, interval, align outbreaks, etc) in the URL every time, regardless whether they are set to their default value?
> That way, if we change the default, which is highly likely, we won’t end up with unexpected views.
> This is the behaviour of the current (live) CovidExplorer.
> On the Next explorer, we omit params that are set to their defaults. This can be problematic if we change the default view (which we do every now and then).
> An example: I want to embed a cases, daily, per million chart.
> Because all these are defaults, they’re not in the URL. If we change the defaults, …

Serialize all choice params in Explorer URL

---

grapher/scatterCharts/ScatterPlotChart.test.ts
grapher/scatterCharts/ScatterPlotChart.tsx
grapher/scatterCharts/ScatterPlotChartConstants.ts
grapher/scatterCharts/ScatterPointsWithLabels.tsx
grapher/scatterCharts/ScatterUtils.ts

Notion issue: [Plot points for ScatterPlot when connecting lines are hidden](https://www.notion.so/Plot-points-for-ScatterPlot-when-connecting-lines-are-hidden-56b03ae1e9284a53b5c66c4b59b57f9b)
`TimeScatter` was used for this, but [now it's gone](https://staging.owid.cloud/admin/test/embeds?ids=4334) (left is _live_, right is _next_):
---
With this PR, ScatterPlots with hidden connecting lines (`hideConnectedScatterLines
`) do plot points:

Points-only (disconnected) ScatterPlot

---

explorer/ExplorerDecisionMatrix.ts
explorer/ExplorerProgram.test.ts

Notion issue: [ "Align outbreaks" setting is not remembered when switching away from a view where it is disabled](https://www.notion.so/Align-outbreaks-setting-is-not-remembered-when-switching-away-from-a-view-where-it-is-disabled-5d2e20a8e7d74cf386bc49168d260647)
⚠️ That test case I've added doesn't actually reproduce the issue, it passes before and after. I spent an hour trying to figure it out but didn't get anywhere, and this is a Low priority issue so didn't think it was worth continuing.
Meanwhile, the fix actually works if you try to reproduce it in the browser. There was a bug in `toConstrainedParams` – the choice params are built-up sequentially (e.g. for COVID that's metric, interval, population ...), and for each param this function ensures there's a valid state, or it changes …

fix: CovidExplorer spuriously selects Align outbreaks

---

explorer/urlMigrations/ExplorerUrlMigrations.test.ts
explorer/urlMigrations/LegacyCovidUrlMigration.ts

Notion: [All old Explorer URLs and embeds have perCapita enabled](https://www.notion.so/All-old-Explorer-URLs-and-embeds-have-perCapita-enabled-4926b84936634812b5682b585995c71e)

fix: set CovidExplorer boolean URL params to 'false' if omitted

---

explorer/Explorer.tsx
explorer/ExplorerGrammar.ts
explorer/ExplorerProgram.ts

Notion: [Change CSV download to point to GitHub CSV again](https://www.notion.so/Change-CSV-download-to-point-to-GitHub-CSV-again-6567d913fe624b11b9c792fead4ae5c5)
After this is deployed, we need to set a `downloadDataLink` in the Explorer config.

feat: allow setting a custom link to download CSV in explorers

---

grapher/core/Grapher.jsdom.test.ts
grapher/core/Grapher.tsx

Notion: [LineChart animations should be playing a line chart, not bar chart](https://www.notion.so/LineChart-animations-should-be-playing-a-line-chart-not-bar-chart-2c2cd73bf8bf4c249b3d82cc0739da4d)
Both line charts and scatter plots now always play in time-range mode, even if the chart starts out in single year mode (i.e. single-year discrete bar chart, or single-year scatter). This detection didn't quite work before.
In `TimelineController`, there's already a `rangeMode` that can later be used to switch between the two modes - single-year and multi-year playing.

fix(play): line chart plays as line chart, not discrete bar chart

---

package.json
yarn.lock

This is to streamline the DX when working on the site.
Two new commands:
- `yarn startSiteBack`: starts TS compiler + admin (on compilation success)
- `yarn startSiteFront`: starts webpack with live reload
I went the tsc-watch route rather than nodemon to limit the number of watchers.
One caveat: when webpack finishes compiling before the admin restarts, this results in a 404. When this happens, the browser usually retries and picks it up on the next round automatically.

Add admin restart and browser reload on change

---

coreTable/CoreTable.test.ts
coreTable/CoreTable.ts
explorer/Explorer.tsx
grapher/core/Grapher.jsdom.test.ts
grapher/core/Grapher.tsx

Notion: [Switching to Map view is slow](https://www.notion.so/Switching-to-Map-view-is-slow-71ed38f1a82d48d88d73cc6b55ef5cfa)
The main thing that makes switching to the map tab slow is that we need to apply 4 `FilterMask`s, and every one of them needs to be applied to ~80000 rows × ~100 columns for the Covid explorer.
To display any given chart, though, we don't need much more than 4 or 5 columns.
So what I'm doing in here is that I drop most columns as early on as possible, only keeping those that we need to display the current chart. This seems to work quite nicely.
This all is still a bit rough around the edges, though, and we (I) probably want to test it more, too.
TODOs:

Improve perf by dropping unnecessary columns before transforming the table further

---

grapher/mapCharts/MapChart.tsx
grapher/mapCharts/ProjectionChooser.tsx

The original fix of stretching the `foreignObject` to 100% height meant that the `ProjectionChooser` was invisibly obstructing Fiji and New Zealand which then wouldn't respond to mouse-over or click events:
I couldn't see any way to fix this by doing something else on Firefox, so this PR disables the pointer events on the obstructing parent and re-enables them on the child `div`, which gives the "intended" behaviour.
CAVEAT: I haven't been able to test this on iOS or Android with touch events, but (all macOS) Safari 11, Firefox 86 and Microsoft Edge 89 work as expected.

fix(map): ProjectChooser no longer obstructs map

---

clientUtils/PromiseCache.test.ts
clientUtils/PromiseCache.ts
clientUtils/PromiseSwitcher.test.ts
clientUtils/PromiseSwitcher.ts
clientUtils/Util.ts
coreTable/CoreTable.ts
coreTable/CoreTableColumns.ts
explorer/Explorer.tsx
explorer/ExplorerProgram.ts
grapher/controls/entityPicker/EntityPicker.tsx
grapher/controls/entityPicker/EntityPickerConstants.ts
grapher/core/Grapher.tsx
grapher/core/LegacyToOwidTable.ts
grapher/lineCharts/LineChart.test.ts

Work in progress, should be [live on playfair](http://playfair-owid.netlify.app/explorers/coronavirus-data-explorer-json?zoomToSelection=true&time=2020-03-01..latest&country=USA~GBR~CAN~DEU~ITA~IND&region=World&pickerMetric=location&pickerSort=asc&Metric=Confirmed+cases&Interval=7-day+rolling+average&Align+outbreaks=false&Relative+to+Population=true) at some point.

feat: JSON table support for Explorer (in columnStore format)

---

explorer/ExplorerControls.scss
explorer/ExplorerControls.tsx

This is a quick fix for one potential that Charlie brought up on Slack: [With the Covid explorer metric dropdown scrolling now, it can be easy to miss the lower options](https://owid.slack.com/archives/CV5RY8F1B/p1617121725009500?thread_ts=1617116752.008000&cid=CV5RY8F1B)

fix(explorer): dropdowns can be wider & higher to fit more options

---

grapher/core/Grapher.tsx

Notion: [ScatterPlot: Disable log/lin switch for "average annual change" chart](https://www.notion.so/ScatterPlot-Disable-log-lin-switch-for-average-annual-change-chart-a31ae16898654fde85c89e2881fb8c7e)
This one's easy.

fix: x-axis lin/log toggle hidden while "Average annual change" enabled

---

explorer/ExplorerDecisionMatrix.ts
explorer/ExplorerProgram.test.ts

Notion: [Explorer setting unreachable?](https://www.notion.so/Explorer-setting-unreachable-0e8d5d6565ee43f7bf779dedae523911)
In `constrainedOptions`, the logic checked left-to-right which options are available, but wasn't taking into account the choices we made in previous loop iterations already.
Also, I re-enabled the broken test case from #818. Turns out that the column names absolutely need to contain the choice type (Dropdown, Radio, Checkbox), otherwise they won't even get parsed.

fix(explorer): `toConstrainedOptions` logic improved

---

explorer/Explorer.jsdom.test.tsx
explorer/Explorer.sample.tsx
explorer/Explorer.stories.tsx
grapher/core/Grapher.tsx

Notion: [Infinite loading state in Covid explorer](https://www.notion.so/Infinite-loading-state-in-Covid-explorer-3190f56ec06542acbf5866d5b7f18c74)
When Explorer is switched from a row with `columnSlug` to one without, the `colorSlug` is not being cleared on the underlying Grapher. 
This is one (fragile) way to fix it. Still need to add a test.

fix: reset colorSlug and sizeSlug when switching Explorer views

---

grapher/core/Grapher.jsdom.test.ts
grapher/core/Grapher.tsx

Notion: [ScatterPlot allows selecting entities not plotted on the chart](https://www.notion.so/ScatterPlot-allows-selecting-entities-not-plotted-on-the-chart-dc862f57e6c549e3a7122db542ec6455)
Supersedes #850, and solves it in a simpler way.

fix: `tableForSelection` only contains entities that can be selected

---

grapher/barCharts/DiscreteBarChart.tsx
grapher/color/ColorScheme.ts

Notion: ["Invert colors" reverses the order of bars](https://www.notion.so/Invert-colors-reverses-the-order-of-bars-9cd6aee7477948a0a7762e22be3a1376)
The `.reverse()` call here modified `this.sortedRawSeries` in place, which meant that it was... sorted the other way round. When it was then accessed to assign the new colors after "Invert colors" has been toggled, its order was wrong.
I also found another occurence where we were inadvertently modifying a "static" array in-place in `ColorScheme.ts`, and fixed it even though it doesn't seem to be causing any trouble currently.

fix(admin): "Invert colors" for discrete bar charts doesn't invert the whole chart series

---

grapher/chart/ChartInterface.ts
grapher/lineCharts/LineChart.test.ts
grapher/lineCharts/LineChart.tsx

Notion: [LineChart: Overlay lines by order of variables (first should be on top)](https://www.notion.so/LineChart-Overlay-lines-by-order-of-variables-first-should-be-on-top-f865d1eb540b4a2da6aeb3fffb424252)
This is the ordering that was used in `pre-v3`. 
For now it's not possible to reorder in Admin, but at least this fixes the issue for past charts.

fix: plot line series in pre-v3 order (first column is on top)

---

baker/SiteBaker.tsx
devTools/droplet/setup-staging-environment.sh
explorer/urlMigrations/CovidUrlMigration.ts
explorer/urlMigrations/ExplorerUrlMigrationUtils.ts
explorer/urlMigrations/ExplorerUrlMigrations.test.ts
explorer/urlMigrations/ExplorerUrlMigrations.ts
package.json
yarn.lock

We need to synchronise the deploys between Explorer config and this PR.
Likely the process should be:
1. Disable auto-publishing on Netlify
2. Update COVID Explorer configuration with new metric names
3. Deploy this PR
4. Once at the baking step of the deploy (or afterwards), re-enable Netlify auto-publishing

Rename "Vaccinations" & "Tests per confirmed case" metrics

---

grapher/barCharts/DiscreteBarChart.tsx
grapher/barCharts/DiscreteBarChartConstants.ts

Notion: [Bar charts - all bars are blue](https://www.notion.so/Bar-charts-all-bars-are-blue-1fdd648e33764370a1a05c90833fefe8)
This PR is live on _tufte_.
In fixing this, I decided to (slightly) differentiate the of behaviour DiscreteBarCharts depending on whether they are a collapsed line chart or a "real" DiscreteBarChart.
A collapsed line chart turned bar chart now:
* uses OWID Distinct as its default color scheme (like LineCharts do)
* rationale: a line chart loaded with a single-year selection immediately has colored bars, rather than starting out with blue ones
* uses `colorScheme.assignColors()` to assign colors to entities, to keep colors consistent when it turns into a line chart again (and also when entities in the bar chart reorder)
* rationale:
* the colors stay the same when …

fix: DiscreteBarChart and LineChart colors consistent

---

coreTable/CoreTable.ts
coreTable/CoreTableColumns.ts
coreTable/OwidTable.test.ts
coreTable/OwidTable.ts
grapher/core/Grapher.tsx

Notion: [Fix ScatterPlot uses wrong time column](https://www.notion.so/Fix-ScatterPlot-using-wrong-time-column-190a88cd3cbf47e7aff2ea6622086f59). 
There were two problems:
- The `timeColumn` was inferred to be the first column of time type. This meant that an `originalTime` column could end up the inferred time column for the whole table.
- We started dropping `originalTime` columns in https://github.com/owid/owid-grapher/pull/830.

Fix ScatterPlot uses wrong time column 

---

package.json
settings/clientSettings.ts
settings/findBaseDir.ts
settings/serverSettings.ts
yarn.lock

This fixes the issue that [running the `exportMetadata` script resulted in an error message](https://owid.slack.com/archives/C01D295TM4K/p1616507884021000), and makes the config code more robust.
How this happened: When running `node itsJustJavascript/db/exportMetadata.ts`, dotenv was looking for a config file `itsJustJavascript/.env` - which doesn't exist.
This then meant that `ormconfig.js` simply used the default database settings (for Typeorm), and MySQL threw a not-very-helpful error message.
The fix now is that we're using `pkg-dir` to find our `package.json` file, and always use the `.env` file on that level. This makes it so that our settings code always uses the same config file, no matter whether it's run from `itsJustJavascript` or not.

fix(config): locate the correct `.env` file to use

---

adminSiteServer/testPageRouter.tsx
coreTable/CoreTable.ts
coreTable/OwidTable.ts
grapher/core/Grapher.jsdom.test.ts

- Adds a new `comparisonUrl` param to embed test pages, so for example you can compare _local_ vs _jefferson_, instead of always _local_ vs _live_. Example: http://localhost:3030/admin/test/embeds?ids=306&comparisonUrl=https://jefferson-owid.netlify.app
- Fixes `complete()` being a noop in certain cases. Added a ScatterPlot test case that was affected by this. 
- There was a map test case that I got wrong some time ago, now fixed
- Makes performance on charts that apply tolerance much worse

fix: CoreTable#complete() does not append missing rows

---

clientUtils/Util.ts
explorer/ExplorerControls.tsx
grapher/controls/Controls.tsx
grapher/core/GrapherAnalytics.ts
site/AmazonMenu.tsx
site/NewsletterSubscription.tsx
site/SiteHeaderMenus.tsx
site/blocks/CookiePreferences.tsx
site/owid.entry.ts

This fixes a couple of issues related to link tracking:
- [Tracking event sent twice when click on label of explorer controls (checkbox)](https://www.notion.so/Tracking-event-sent-twice-when-click-on-label-of-explorer-controls-checkbox-5c5862be61c24335b2951d239ec93c71)
- [Use `data-track-note` and not href as the event action](https://www.notion.so/Use-data-track-note-and-not-href-as-the-event-action-ca02c0042ae443b79296cff6a5f288e9)

Fix link tracking

---

grapher/core/Grapher.jsdom.test.ts
grapher/core/Grapher.tsx

Notion: [canonicalUrl of embedded chart is wrong, doesn't include selected entities](https://www.notion.so/canonicalUrl-of-embedded-chart-is-wrong-doesn-t-include-selected-entities-4f78411d424b4c64a73c1fa1ad409ee5)
This fixes the canonical URL of embedded charts being wrong, but ideally
we fix this in a nicer way at some point.
Let's put this on our list of pain points, maybe. I feel like `SelectionArray` should really be immutable, even though I somewhat understand why we want/need it to be mutable.

fix: `authorsVersion` selection doesn't reflect grapher selection

---

adminSiteClient/EditorFeatures.tsx
grapher/core/Grapher.tsx
grapher/stackedCharts/StackedDiscreteBarChart.stories.tsx
grapher/stackedCharts/StackedDiscreteBarChart.tsx

Notion: [Relative/100% stacked bar transform](https://www.notion.so/Relative-100-stacked-bar-transform-ca046c9723914361b092d32054768654)
Thankfully the table transform was already there, and then this was actually quite easy to do.
I decided to always order the bars by label (i.e. country name) when in relative mode, because otherwise it would be super jumpy. We can reconsider once we have some more clever ordering options.
I also fixed the bug [Max reported](https://owid.slack.com/archives/C46U9LXRR/p1620903248035500) where countries without data were showing up in the chart, even though they didn't have a bar. It's not totally related, but not totally unrelated either.

feat: stacked bars support relative mode

---

adminSiteServer/testPageRouter.tsx

When I was going to https://owid.cloud/admin/test/embeds?type=StackedDiscreteBar, I found that that page was lying to us 😢 
While there are at least 4 StackedDiscreteBar charts out there, it was showing none.
This is because the `hasChartTab` option gets stripped out from the configuration if it has the default config (`true`), and we didn't consider that in the SQL query we build.
I added a `COALESCE` to all of these, and now it works again!

fix(admin): test page shows charts that only have implicit `hasChartTab`

---

package.json
yarn.lock

I am almost certain that we don't need these two any more. They are certainly no longer being referenced anywhere.

chore(deps): remove `asciify-string` and `google-trends-api` dependencies

---

.env.example
.gitignore
Makefile
README.md
db/downloadAndCreateDatabase.sh
package.json
wordpress/.lando.yml
wordpress/.lando/scripts/refresh-dev.sh

Automate more of the development environment with `make`, heavily reusing existing `yarn` commands and `lando`. The idea is that the environment should come up cleanly right out of the box with minimal intervention.
- Run `make` for available commands
- `make start` brings up background services (nginx, mysql), does one-time db imports (grapher, wordpress), and runs foreground services in watch mode (admin, webpack)
- Reduces MySQL services from two to one in lando
- Unifies database settings to work out of the box with lando defaults
- Updates `.env.example` and copies `.env.example` to `.env` on first run

chore: Drive dev environment with `make`

---

grapher/controls/EntitySelectorModal.scss

Switch from flex box for entity selector to using ul columns with a media query.
This is because countries were spilling left-to-right before top-to-bottom, a highly unintuitive sort order for people to look through. A media query approach was taken because flexbox columns would only solve this if the container had fixed height.
See: https://www.notion.so/owid/List-countries-vertically-instead-of-by-rows-in-grapher-country-selector-ad9fbd8b86c04e61bf58b68dd5e1bade

fix: make country selection top-to-bottom, left-to-right

---

explorer/GrapherGrammar.ts

This is a "footnote" in the Grapher chart. (Hannah asked about this on [Slack](https://owid.slack.com/archives/C5BDCB2R3/p1621951911077100).)

feat: support setting Grapher `note` in Explorer config

---

site/SiteFooter.tsx
site/multiembedder/MultiEmbedder.tsx
site/webpackUtils.tsx

This PR is live on _tufte_.
Since we're already using `polyfill.io` anyway, we might as well be using to polyfill these two :)
This gives us basic compatibility (i.e. there might be other issues) with:
* Firefox >= 52 ([explorer embeds are not great in Firefox < 59, though](https://user-images.githubusercontent.com/2641501/119222982-4a3afb80-baf7-11eb-9d35-51c705293cd8.png))
* Chrome >= 58
* Safari >= 11.0

chore: polyfill IntersectionObserver & URLSearchParams

---

explorer/Explorer.scss

In a previous design, the title could take more space because there were more controls to the right of it. Now that there are fewer, there is blank space left.
This change reduces the title so as to remove the need for blank space in the panel to its right.
See: https://www.notion.so/owid/Condense-explorer-title-d5bbac463dd54470a60cac48c1c2dee2

enhance: Shrink explorer title to reduce wasted space

---

README.md
adminSiteServer/apiRouter.ts
adminSiteServer/app.tsx
adminSiteServer/mockSiteRouter.tsx
baker/GrapherBaker.tsx
db/wpdb.ts
settings/clientSettings.ts
settings/serverSettings.ts

Currently, grapher fails to render some pages (e.g. `/grapher/:slug`) if you do not have a wordpress database dump set up and if you do not have a working wordpress API url with credentials.
This PR makes it well defined how to disable these two Wordpress integrations by blanking out specific config keys (`WORDPRESS_DB_NAME` and `WORDPRESS_API_URL`). When they are disabled, the site runs without them and does not attempt operations that would have failed. This makes rendering local charts much much faster.
For example, the http://localhost:3030/admin/test/embeds page rapidly renders all local charts after this change, whereas before they blocked on API calls to a Wordpress instance and were slower than the production site.

chore: Make it well-defined how to run grapher without wordpress

---

grapher/stackedCharts/StackedAreaChart.tsx
grapher/stackedCharts/StackedBarChart.tsx
grapher/stackedCharts/StackedDiscreteBarChart.test.ts
grapher/stackedCharts/StackedDiscreteBarChart.tsx
grapher/stackedCharts/StackedUtils.test.ts
grapher/stackedCharts/StackedUtils.ts

Fixes the issues that [Hannah reported](https://owid.slack.com/archives/C46U9LXRR/p1622146853049900) for this chart: https://ourworldindata.org/grapher/per-capita-co2-by-fuel
In [`stackSeries`](https://github.com/owid/owid-grapher/blob/62d1a56ac0929a06fb92d161d30f61a0f41368bf/grapher/stackedCharts/StackedUtils.ts#L6-L19), we were assuming that all series had the same number of points (one for every entity we have), which wasn't the case if some variable had missing data for one entity.
I'm not in love with the whole `fake` point thing, and think we should introduce another `NoDataAvailableStackedPoint` or something instead. But that's something for another time.

fix: stacked discrete bar chart handles mising values for some columns

---

grapher/core/Grapher.jsdom.test.ts
grapher/core/Grapher.tsx

When you click on the Source or Download tabs of a chart, the timeline currently stays rendered, despite logic that is meant to hide it.
This is because the check is done on `this.tab`, but actually Source and Download are overlays on the tab; when you click on them, `this.tab` stays at wherever it was last.
This fix runs the same check, but on `this.currentTab` instead, which picks up any overlay (such as Source or Download) if they are available. This has the effect of correctly hiding the timeline when the user clicks on those tabs.
See: https://www.notion.so/owid/Hide-timeline-on-Sources-and-Download-tabs-8766e5c1c13f431b978b8d579b92ff65

fix: hide timeline for Source or Download tabs

---

grapher/persistable/Persistable.test.ts
grapher/persistable/Persistable.ts

Notion: [Cannot save chart with `minTime=Infinity` config](https://www.notion.so/Cannot-save-chart-with-minTime-Infinity-config-02c50abd4c6d45c488073442a2046ee9)
I tested this by logging the output of the old and new method, and made sure that the differences are restricted to `minTime` and `maxTime` in my testing. So this should fix the issue and shouldn't negatively impact anything else - fingers crossed!

fix(persistable): don't delete `Infinity` from object

---

grapher/stackedCharts/AbstractStackedChart.tsx
grapher/stackedCharts/StackedAreaChart.tsx

This fixes https://www.notion.so/owid/Do-not-plot-series-with-value-0-on-StackedArea-5b877f8c58854445a4631f9999b9b813 , in particular the vaccination chart by company

Fix(grapher): Hide time series that are all 0 in stacked area charts

---

grapher/chart/ChartUtils.tsx
grapher/lineCharts/LineChart.tsx
grapher/lineCharts/LineChartUtils.ts

This fixes the issue described in https://www.notion.so/owid/Broken-chart-ea6e5f3f9dcf49d4859b74dad585d6ca). The problem is that autoDetectSeriesStrategy checks if there is more than one variable involved and if so it sets the strategy to column. When there is a projection we have two variables but logically this is shown as one and entity is still the right strategy.
This is my first code commit so please let me know extensively what you think. It might also be that the entire approach is wrong, but this is what I came up with to resolve the issue :).

Fix line charts with projection

---

grapher/facetChart/FacetChart.test.ts
grapher/facetChart/FacetChart.tsx

Currently, facet charts totally ignore the timeline control. This is because they are generated from the `inputTable` before transformations, which include filtering the data to only the selected range.
This fix builds the facet charts instead from the `transformedData` that has been correctly filtered this way.

fix(grapher): Facet graphs controlled by the timeline

---

db/wpdb.ts

**Before**
**After**
postApi's dates (date, modified, date_gmt, modified_gmt) are e.g. 2021-06-03T13:30:23, with no timezone offset. Parsing them with new Date() is understood as UTC given TZ=utc is defined in .env. This passes the dates as GMT / UTC.
Not entirely sure how Mailchimp uses the post time in their RSS campaigns but it's probably best to have the correct one, especially given our preflight process which is time sensitive (see [Automate immediate newsletter updates](https://www.notion.so/Automate-immediate-newsletter-updates-04f02909c1bc4eaa9700c258a9f57cfc))

Fix time in Atom feed

---

grapher/horizontalColorLegend/HorizontalColorLegends.tsx
grapher/stackedCharts/StackedDiscreteBarChart.tsx

Notion: [HorizontalLegend become offset when converting SVG → PNG](https://www.notion.so/HorizontalLegend-become-offset-when-converting-SVG-PNG-2f7ef11b178141abbe035bee4f19f6c2)
Note that Lato and Playfair Display are installed on `owid-live`, but not on `owid-staging` - that's why the above image is rendered using the wrong fonts.
You may also notice that the bar labels, and other stuff, isn't aligned correctly in the above image. That's because, you guessed it, they also use `dominant-baseline`, which isn't supported by Sharp.

fix: legend label alignment in png exports

---

clientUtils/BrowserUtil.ts
grapher/stackedCharts/StackedDiscreteBarChart.tsx

Notion: [Animate reordering of bars](https://www.notion.so/Animate-reordering-of-bars-188ab2942abe43b48c9306e42b966f15)
Thankfully, this can be done pretty easily with `react-flip-toolkit`.
One caveat there is that we're only animating the order of bars, and not their respective width. Animating the bar width is a little more intricate (because we would also need to animate the axis, etc.)
This is also live on _tufte_. Try it out here:
* [COVID explorer](https://tufte-owid.netlify.app/explorers/coronavirus-data-explorer?Metric=People+vaccinated+%28by+dose%29&Interval=7-day+rolling+average&Relative+to+Population=true&Align+outbreaks=false&country=IND~USA~ITA~GBR~DEU~CAN)
* [Per capita electricity consumption by source](https://tufte-owid.netlify.app/grapher/per-capita-electricity-source-sta …

feat: StackedDiscreteBarChart bars animate

---

baker/formatWordpressPost.tsx
baker/formatting.test.ts
baker/formatting.tsx
site/DataToken.tsx
site/covid/LastUpdated.tsx
site/runDataTokens.tsx

Until now, only /coronavirus had a client-side refreshed "Last updated" tag ({{COVID_LAST_UPDATED}}).
This adds support for a more generic {{LastUpdated timestampUrl:https://...}} tag, where the timestamp url is provided as an attribute. 
List of currently available timestamps (COVID only): 
- public: https://github.com/owid/covid-19-data/tree/master/public/data/internal/timestamp
- internal: https://www.notion.so/owid/e4b94a243b834804aca76734917857a5?v=ec20b4bceaf44d31aa8e2e9c5f6bd3d2

Add support for more "last updated" tags

---

adminSiteClient/EditorCustomizeTab.tsx
explorer/Explorer.tsx
explorer/ExplorerProgram.test.ts
explorer/ExplorerProgram.ts
explorer/GrapherGrammar.ts
grapher/axis/AxisConfig.ts
grapher/captionedChart/CaptionedChart.tsx
grapher/chart/ChartManager.ts
grapher/controls/Controls.tsx
grapher/core/Grapher.tsx
grapher/core/GrapherConstants.ts
grapher/facetChart/FacetChart.stories.tsx
grapher/facetChart/FacetChart.test.ts
grapher/facetChart/FacetChart.tsx

Currently, many charts support facets by typing `f` when viewing. The y-axis of every facet has the same range, so that you can compare scale across entities.
This PR adds a "Uniform y-axis" toggle when in facet mode which allows you to switch to relative y-axis mode, good for comparing the shape across entities. The default mode can be set to relative by an author, set via the "Facets have uniform y-axis" checkbox in the "Customize" tab. This controls the `yAxis.facetAxisRange` grapher config key.
See: https://www.notion.so/owid/Adjusted-vs-uniform-y-axis-scale-b88534934da04681b753742627d24ced

enhance(grapher): add relative yaxis mode in facets

---

grapher/lineCharts/LineChart.tsx

Notion: [Single data points being hidden can be misleading in line charts](https://www.notion.so/Single-data-points-being-hidden-can-be-misleading-in-line-charts-7c4317eafefb4ba281c48d8f75801280)
This also changes it so that circles can be shown on hover over a line, when they weren't shown before. This can make it clearer how many observations we have, as you can see in the video below.
https://user-images.githubusercontent.com/2641501/122206994-ed3a2780-cea1-11eb-88be-d7b25561fa37.mp4

fix: always display marker for singular data point in line chart

---

adminSiteClient/DimensionCard.tsx

Quite a lot of charts support tolerance now.
The field in `DimensionCard` was hidden for some charts, this PR makes it always shown.

fix(admin): always show "Tolerance" input in DimensionCard

---

grapher/captionedChart/CaptionedChart.tsx
grapher/controls/Controls.scss
grapher/controls/Controls.tsx
grapher/core/Grapher.stories.tsx
grapher/core/Grapher.tsx
grapher/core/GrapherConstants.ts
grapher/facetChart/FacetChart.test.ts

Add a dropdown menu for faceting, which is enabled by pressing "f", allowing you to choose what faceting strategy to use, when there are multiple available.
See: https://www.notion.so/owid/Plot-entities-together-or-metrics-together-f47c2de5ca554294a78a540dc383597f
- Turn the dropdown into the full hovering design

enhance(grapher): Offer a dropdown menu for facet strategy

---

grapher/core/Grapher.tsx

This resolves two issues:
- Colors on "change entity" charts not being applied (reported by both [Lucas](https://owid.slack.com/archives/C46U9LXRR/p1624631755004300) and [Charlie](https://owid.slack.com/archives/C46U9LXRR/p1624813310013700))
- Add country button showing up when it shouldn't (reported by [Charlie](https://owid.slack.com/archives/C46U9LXRR/p1624813310013700))

fix: single entity charts shouldn't show "add country" button

---

grapher/core/Grapher.tsx

This reverts a part of https://github.com/owid/owid-grapher/commit/1581f9d2bdd39bb65d74d4a6973f4bddc6f6c32f.
It's a quick fix for a bug we have where `stackMode` is not being saved/recovered at all from config ([Slack report](https://owid.slack.com/archives/C46U9LXRR/p1624953280000400)). Since faceting is not surfaced to users, it seems harmless to revert.
The logic as it was written also wasn't quite right: charts can be stacked by either metric or entity, so that needs to be taken into account. But additionally, what gets stacked is determined by `seriesStrategy`, which doesn't have a consistent meaning from chart to chart.

fix(grapher): allow saving/recovering stackMode config property

---

grapher/stackedCharts/StackedDiscreteBarChart.tsx

Notion: [Show Total value in tooltip](https://www.notion.so/Show-Total-value-in-tooltip-865cde592fc04f5bbdeaebf08fb7aff2)
Live on _tufte_.
Looks a little something like this:

feat: show total value in stacked bar chart tooltip

---

grapher/controls/CollapsibleList/CollapsibleList.scss
grapher/controls/CollapsibleList/CollapsibleList.tsx

Notion: [Mobx reaches max update depth](https://www.notion.so/Mobx-reaches-max-update-depth-61049a64ac6d4443aeb1e859c50b1bb3)
While looking into this, I noticed that the code in `CollapsibleList` was entirely broken in some way:
In every call to `calculateItemWidths`, we were calculating the widths of all _visible_ elements and appended them to the end of the ever-growing `this.itemsWidths`.
To fix this and to also measure the width of items that are not visible, we now mount all dropdown items after the More button with `visibility: hidden` to have access to their `clientWidth`.
This results in `calculateItemWidths` always calculating the width of all children, i.e. `this.itemsWidths` is always up to date for all children.
Let me know if you know of a way of measuring the width without …

fix: collapsible list measures item widths correctly

---

grapher/stackedCharts/StackedDiscreteBarChart.tsx

After we observed issues in both Safari & Firefox, it doesn't really make sense to keep it for now.
This mostly reverts 8000a2909e30e6ca05d3777a3dcc2c6507ffedf3 (#929).
We can see how we can continue from here - maybe by using a different library for animation.

fix: disable stacked bar chart animation

---

grapher/stackedCharts/StackedDiscreteBarChart.tsx
package.json
yarn.lock

Notion: [Animate reordering of bars](https://www.notion.so/Animate-reordering-of-bars-188ab2942abe43b48c9306e42b966f15)
After the last attempt using `react-flip-toolkit` [failed due to browser issues](https://github.com/owid/owid-grapher/pull/955), I decided to reimplement it using `react-move`.
Live on _tufte_, e.g. here: https://tufte-owid.netlify.app/grapher/per-capita-energy-stacked

feat: animate stacked bar charts using `react-move`

---

wordpress/.lando/config/php.ini
wordpress/README.md
wordpress/config/application.php

Workaround for https://core.trac.wordpress.org/ticket/53607 (Loading or saving a post with enough (large) revisions exhausts available memory)
Issue: ["Updating failed" when saving ](https://www.notion.so/Updating-failed-when-saving-a8d3edae4ec4426fabcb73350f79e936)

Limit number of Wordpress revisions

---

grapher/core/Grapher.tsx
package.json
settings/clientSettings.ts
site/owid.entry.ts
webpack.config.ts
yarn.lock

For now only the main grapher is using the error boundary, the other ReactDOM.render instances still have to be wrapped

feat(bugsnag):  Attempt initial bugsnag setup

---

grapher/core/Grapher.tsx
site/covid/CovidTable.tsx
site/covid/CovidTableColumns.tsx
site/covid/CovidTableRow.tsx

Okay, so one thing that's contained in here is just a fix for one of the issues we detected using Bugsnag, namely that we use `Object.fromEntries` which doesn't have super-good browser support yet.
But in working on this I discovered a way bigger issue with our Bugsnag, namely that it reloaded the Grapher every time the window size changed 😧 
https://user-images.githubusercontent.com/2641501/127222317-69d9d94f-b60a-4407-88d6-199822c4af62.mp4
To make matters worse, in Android Chrome there's a window resize event happening for many scrolls, since the address bar is shown/hidden on scroll.
This probably happened because every call to `Bugsnag.getPlugin("react").createErrorBoundary(React)` returns a new reference to a Bugsnag error boundary, and `setBoundsFromContainerAndRender` is called on …

fix Bugsnag integration

---

grapher/color/ColorScale.test.ts
grapher/color/ColorScale.ts
grapher/mapCharts/MapChart.tsx

This fixes an issue that [Charlie reported on Slack](https://owid.slack.com/archives/C46U9LXRR/p1627505440001300):
Turns out that `tooltipUseCustomLabels` was assuming that all data values would just be `0, 1, 2, ...`, and it was completely disregarding the configured bins. That was dumb (and [I'm the one to blame](https://github.com/owid/owid-grapher/pull/439)).

fix(map): `tooltipUseCustomLabels` mode respects bins

---

grapher/core/schema.json

Remove fields that do not exist in our codebase and auto-annotate as deprecated fields that have not been used in the past year.
See Jupyter notebook for details of auto-annotation/marking for deletion: https://gist.github.com/larsyencken/9f157a3db5a4d5dcd26262d5e72a51c5

chore: Prune and annotate the JSON schema

---

grapher/axis/Axis.ts
grapher/barCharts/DiscreteBarChart.tsx
grapher/chart/ChartInterface.ts
grapher/facetChart/FacetChart.tsx
grapher/facetChart/FacetChartConstants.ts
grapher/lineCharts/LineChart.test.ts
grapher/lineCharts/LineChart.tsx
grapher/lineLegend/LineLegend.stories.tsx
grapher/lineLegend/LineLegend.test.tsx
grapher/lineLegend/LineLegend.tsx
grapher/scatterCharts/ScatterPlotChart.tsx
grapher/stackedCharts/AbstractStackedChart.tsx
grapher/stackedCharts/StackedAreaChart.test.ts
grapher/stackedCharts/StackedAreaChart.tsx
grapher/stackedCharts/StackedDiscreteBarChart.tsx

Notion: [Refactor chart transform flow to support facets](https://www.notion.so/Refactor-chart-transform-flow-to-support-facets-55a3a4183162465885a8bc2527f66ef4)
This also fixes:
- [yAxisMin explorer setting should be respected in facets](https://www.notion.so/yAxisMin-explorer-setting-should-be-respected-in-facets-f992da1cbd944de18301b3bd26915555)
...which is being worked on https://github.com/owid/owid-grapher/pull/946, this is an alternative way to fix it.
- [StackedArea axis is not uniform](https://owid.slack.com/archives/CQQUA2C2U/p1624358837039600)
This PR adds `xAxis` and `yAxis` to `ChartInterface`, and then also initializes chart classes (that aren't rendered) in the faceting logic, in order to determine the right axis props to pass. 
Effectively, it only fixes the "uniform Y …

enhance: determine facet properties from intermediate chart views

---

adminSiteClient/EditorCustomizeTab.tsx
explorer/ExplorerProgram.ts
explorer/GrapherGrammar.ts
grapher/captionedChart/CaptionedChart.stories.tsx
grapher/captionedChart/CaptionedChart.tsx
grapher/controls/Controls.scss
grapher/controls/Controls.tsx
grapher/core/Grapher.tsx
grapher/core/GrapherInterface.ts
grapher/core/schema.json

Convert the standard drop-down for selecting facets into a more visual and user friendly design. The expected behaviour is that:
- The "f" key enables the chart control, but only for charts that support faceting (e.g. not scatterplots)
- The control looks like a normal dropdown, but shows hovering options when you click on it
- You should have the option "All together" and either "Split by entity" or "Split by country", depending on the chart
Refactors the faceting variables in `Grapher.tsx` to make clear what the desired faceting strategy is vs the actual rendered strategy, which has to take into account what is actually possible given the data.
See: https://www.notion.so/owid/Plot-entities-together-or-metrics-together-f47c2de5ca554294a78a540dc383597f

enhance(grapher): Improve UI for facet selection

---

grapher/axis/AxisConfig.ts
grapher/controls/Controls.tsx
grapher/core/Grapher.tsx
grapher/core/GrapherConstants.ts
grapher/core/GrapherInterface.ts
grapher/core/schema.json
grapher/facetChart/FacetChart.stories.tsx
grapher/facetChart/FacetChart.test.ts
grapher/facetChart/FacetChart.tsx

Add two new URL parameters to preserve faceting settings. They are:
- `facet`: can be (`none`, `entity`, `metric`)
- `uniformYAxis`: can be (`1`, `0`)
Refactoring
- Renamed `FacetStrategy.column` to `FacetStrategy.metric`
- Make `yAxis.facetDomain` to `undefined` by default (but default it to `FacetAxisDomain.shared`)
Expected behaviour
- The URL parameters can override the default settings
- They get auto-added if you vary from the default settings, and auto-removed if you go back to any default setting
https://www.notion.so/owid/URL-parameter-support-for-facets-c7fb9b2a1e864f5e85137de71a736fca

enhance(grapher): Add URL parameters for faceting

---

explorer/Explorer.jsdom.test.tsx
explorer/Explorer.sample.tsx
explorer/Explorer.tsx

Notion: [Preserve tab when switching between choices on Explorers](https://www.notion.so/Preserve-tab-when-switching-between-choices-on-Explorers-9a06817286b24ba7990a8b105b77881e)
This fixes small issues:
* There were situations when switching the view also inadvertently changed the tab from chart to map tab
* ... and there were cases when the user was on the map tab and switched to a view that didn't have a map tab, but we showed a map anyway

fix(explorer): preserve tab when switching view

---

adminSiteClient/SuggestedChartRevisionApproverPage.tsx

Adds a "random" button to the `SuggestedChartRevisionApproverPage` so that admin users can explore suggested chart revisions more easily.
Demo: https://user-images.githubusercontent.com/11767602/128666873-99be1800-aa90-408c-bd9d-bd57f894e811.mov

enhance(chartApprovalTool): add random button

---

adminSiteClient/EditorCustomizeTab.tsx
adminSiteClient/EditorFeatures.tsx
explorer/GrapherGrammar.ts
grapher/core/Grapher.tsx
grapher/core/GrapherInterface.ts
grapher/stackedCharts/StackedDiscreteBarChart.tsx

Notion: [Show total value next to bars](https://www.notion.so/Show-total-value-next-to-bars-b3bc132511b04e9ba42264daf50176f8)
This PR is live on _tufte_. Check out https://tufte.owid.cloud/admin/test/embeds?type=StackedDiscreteBar for a nice comparison to _live_, or check the [Covid explorer](https://tufte-owid.netlify.app/explorers/coronavirus-data-explorer?Metric=People+vaccinated+%28by+dose%29&Interval=7-day+rolling+average&Relative+to+Population=true&Align+outbreaks=false&country=IND~USA~ITA~GBR~DEU~CAN).
I opted to not introduce another new option here, and to always display the total value if `!manager.isRelativeMode`. That is, for charts where the underlying data is already relative (i.e. the underlying data adds up to 100% for each entity), the authors can hide the total value by …

feat: display total values in StackedDiscreteBarChart

---

adminSiteClient/ChartEditor.ts

Notion: [Updating a newly created chart creates a duplicate of it](https://www.notion.so/Updating-a-newly-created-chart-creates-a-duplicate-of-it-87e732bd8fe54e41be19fc4e3f48bf9a)
This fixes the most prominent issue, and most importantly prevents duplicate slugs from appearing for now.

fix(admin): set grapher id of newly saved grapher

---

grapher/core/Grapher.tsx

Constrain the faceting experience so that we offer faceting only when it makes sense, and so that faceting interacts better with relative mode in the StackedDiscreteBar case.
Note that we change the relative mode state when switching to faceting. The ideal solution would not do this, just override it, but that would take a big refactor. So this is the compromise approach.
https://www.notion.so/owid/Ensure-all-possible-faceting-combinations-make-sense-for-v1-launch-5006ee5a119844c9bca5007b1e42e598

enhance: Improve faceting boundary cases

---

coreTable/OwidTable.ts
grapher/dataTable/DataTable.stories.tsx
grapher/dataTable/DataTable.tsx

Now gets `entityType` from manager, not from the `OwidTable`. 
This is a lapse from Project Next – the entity type isn't ever defined on the table, at least yet. It's messier right now to define it there, even though it _feels_ like it belongs there.
https://www.notion.so/owid/Grapher-table-view-labels-entity-as-Country-always-209c27d7a8aa45b593f0b754153db901

fix(DataTable): show correct entity type in table header

---

grapher/core/Grapher.tsx

Solves a minor problem where the Grapher is shortening source names on display when this behavior is not desired for a number of source names in the latest World Bank World Development Indicators dataset.
- e.g. the source name "World Bank and OECD" should not be shortened to "World Bank" by default.
- e.g. the source name "World Bank based on UN Population Division" should not be shortened to "World Bank" by default.
This fix alters the default source name shortening behavior to NOT shorten source names on display when the source name starts with a `majorSource` (e.g. "World Bank") followed by either " and" or " based on".

fix(grapher): add exception to default source name shortening

---

site/Feedback.tsx
site/owid.scss

This PR adds a general link to our FAQ in the feedback form and does a simple match on some of the most common keywords to highlight specific entries. The goal of this is to reduce feedback that is already answered in the FAQ. See the slack thread here for background: https://owid.slack.com/archives/C0149NKLZAM/p1629910262010300

Feedback links to faq

---

wordpress/composer.json
wordpress/composer.lock
wordpress/web/app/plugins/owid/src/authentication.php

Rewrite of JWT validation logic due to breaking API change in lcobucci/jwt library after upgrade to 4.x (https://lcobucci-jwt.readthedocs.io/en/latest/upgrading/#v3x-to-v4x). Most notable change is more explicit constraint validation:
- Lcobucci\JWT\Validation\Constraint\PermittedFor: verifies if the claim aud contains the expected value
- Lcobucci\JWT\Validation\Constraint\SignedWith: verifies if the token was signed with the expected signer and key
- Lcobucci\JWT\Validation\Constraint\StrictValidAt: verifies presence and validity of the claims iat, nbf, and exp (supports leeway configuration)

Upgrade lcobucci/jwt to 4.x (wordpress authentication)

---

site/SiteSubnavigation.tsx

before: https://ourworldindata.org/coronavirus-data-explorer
after: https://ourworldindata.org/explorers/coronavirus-data-explorer
@danielgavrilov there seems to be a client side redirect performed between the two URLs. Any reason not to have it performed server side? (pinging you as I saw you contributed related migration tests, but feel free to pass along)

Update COVID explorer path in subnavigation

---

.bundlewatch.config.json
adminSiteServer/IndexPage.tsx
site/SiteFooter.tsx
site/webpackUtils.tsx
webpack.config.ts

Supersedes #994.
This solves the "`commons.js` is too big" problem another way, namely by splitting `commons.js` into two parts, one containing the dependencies included in there (`vendors.js`) and the other containing the rest of the shared code (`commons.js`).
This approach has several advantages:
* The assets are always named the same, so finding which assets we need to include stays super easy
* We don't need to re-generate and re-upload >5000 files whenever our JS changes, which leads to long deploy times
* No need to worry about edge cases where assets might be deleted (through a deploy) at the exact time when they are requested

chore(webpack): factor out node_modules from comons.js into vendors.js

---

clientUtils/Util.ts
clientUtils/owidTypes.ts

Notion: [Tweak facet layout algorithm](https://www.notion.so/Tweak-facet-layout-algorithm-2b1a1959a0c14c4d9923ae1ac18b442f)
The [very quick fix](https://github.com/owid/owid-grapher/commit/7f288b0ca9b6d8c28be28245c83b1caa7f06bc1f) I deployed temporarily increased `IDEAL_PLOT_ASPECT_RATIO`, this changes it back.
I'd like to spend some time testing different cases before deploying (will be doing this next week).
I've added this tweak to the [Observable notebook](https://observablehq.com/@danielgavrilov/pack-rectangles-of-a-preferred-aspect-ratio) under "Round col, then derive row, remove extra columns".

enhance(facets): decrease columns in grid if all charts can fit in fewer columns

---

adminSiteClient/EditorFeatures.tsx
grapher/chart/ChartInterface.ts
grapher/chart/ChartManager.ts
grapher/facetChart/FacetChart.tsx
grapher/horizontalColorLegend/HorizontalColorLegends.tsx
grapher/lineCharts/LineChart.test.ts
grapher/lineCharts/LineChart.tsx
grapher/mapCharts/MapChart.tsx
grapher/stackedCharts/AbstractStackedChart.tsx
grapher/stackedCharts/StackedAreaChart.test.ts
grapher/stackedCharts/StackedAreaChart.tsx
grapher/stackedCharts/StackedBarChart.tsx
grapher/stackedCharts/StackedDiscreteBarChart.test.ts
grapher/stackedCharts/StackedDiscreteBarChart.tsx
grapher/verticalColorLegend/VerticalColorLegend.tsx

Notion: [Global legend for all facets](https://www.notion.so/Global-legend-for-all-facets-c579c294009b4e72a6f21b801a366c8f)
Ready to review. Not quite sure whether this is the right approach for combining legends across charts, but it could be good enough for v1. Wrote some thoughts below:
Not deployed on a staging server because my staging server is used for another PR. But here are screenshots:
**Is it reasonable to assume that a legend with 1 item should be automatically hidden?** 
This applies to the global facet legend, but also the stacked bar legend. There may be cases where it's a multi-metric chart, so the titles don't contain the full information and we need to rely on the legends, but maybe all except one metric happen to be missing for the selected countries. This behaviour …

enhance(facets): Add global legend for Line, StackedArea & StackedDiscreteBar

---

grapher/controls/entityPicker/EntityPicker.tsx

This fixes an issue that I noticed with the climate change explorer.
Since the explorer is based on `grapherId`s (aka switcher explorer), the unavailable entities weren't properly greyed out. Since entities are often non-overlapping in this specific explorer, this made things extra bad because one didn't even know what could be selected.
---
`SelectionArray`'s `availableEntities` array is monotonically non-decreasing over time, i.e. is always growing and never shrinking. Therefore, `this.selection.availableEntityNameSet` always returns every entity that is visible in the entity picker, and should only be used if `grapherTable` isn't available (don't know when that would be the case, actually?).
Otherwise, let's use `grapherTable`, which in the case of a switcher explorer contains only the …

fix(explorer): in a switcher explorer, correctly show available entities

---

grapher/controls/entityPicker/EntityPicker.tsx
grapher/timeline/TimelineComponent.tsx
site/hacks.ts
site/owid.entry.ts

Notion: [Charts often break when translated with Google Translate](https://www.notion.so/Charts-often-break-when-translated-with-Google-Translate-c46a844640714cc698ee14c13b5b504b)
This is live on _tufte_.
---
This problem with Google Translate (there's a video in Notion) is actually one of the most common issues we see in Bugsnag, indicating that this is indeed a problem for many of our users.
The patch is admittedly hacky since it modifies `Node.insertBefore` and `Node.removeChild` in such a way that they only fail silently (`console.error`) instead of throwing.
But the fix was proposed by Dan Abramov himself, which makes me trust it way more :)
---
Tracking issues:
* React issue, including the patch: https://github.com/facebook/react/issues/11538#issuecomment-417504600
* Another …

fix: introduce monkeypatch for Google Translate to work with React

---

grapher/controls/globalEntitySelector/GlobalEntitySelector.tsx
grapher/text/TextWrap.tsx

Live on _tufte_.
Followup for #1005.
I noticed a major issue with Google Translate where the chart title wouldn't update in an explorer:
https://user-images.githubusercontent.com/2641501/133777716-f285bb40-65d4-4121-be79-0e2591d03cec.mp4
This is not new behaviour, but has been the case before #1005 already.
Also note that `TextWrap.renderHtml` is only used for the chart header and footer (i.e. title, subtitle, source line, note).
---
We could also think about `renderHtml` just returning the text as is and it leaving the wrapping to the browser? This works quite nicely for chart title and subtitle, although it would of course introduce disparities between the interactive chart and the static version. It also results in way nicer translated versions.

fix: further Google Translate fixes

---

grapher/captionedChart/CaptionedChart.scss
grapher/captionedChart/CaptionedChart.tsx

Fixes #360.
This is live on _tufte_, complete with newly rebaked exports.
---
The process of deploying this and regenerating all existing SVGs should looks something like this:
```sh
pm2 stop live-deploy-queue
cd live/bakedSite
git rm -r grapher/exports
git rm -r exports
mkdir grapher/exports
mkdir exports
yarn buildAndDeploySite live
```
Note: The deploy will take about two hours to rebake all exports.

fix(svg): use `text-rendering: geometricPrecision` to fix text rendering issue on Android Chrome

---

grapher/facetChart/FacetChart.test.ts
grapher/facetChart/FacetChart.tsx
grapher/facetChart/FacetChartConstants.ts

Notion: [Ensure entity color in global legend is consistent with all facets](https://www.notion.so/Ensure-entity-color-in-global-legend-is-consistent-with-all-facets-68588d0d74264c92a01aba601d31ed66)
This is achieved by passing down a `seriesColorMap` to all child charts, which makes sure that entity colors are synchronized between the charts.
I intentionally didn't pass down the Grapher's map (`manager.seriesColorMap`) but rather a map local to FacetChart. That's because otherwise, the facet charts don't use the default blue line color _if_ a user is coming from a non-faceted view at first. I didn't like that behaviour, and so there's now essentially two distinct `seriesColorMap`s being used depending on whether the chart is faceted or not.
I checked this with LineCharts, …

fix(facet): ensure entity colors are consistent between facet charts and the global legend

---

grapher/facetChart/FacetChart.tsx
grapher/facetChart/FacetChartConstants.ts

Notion: [DiscreteBar y axis should not collapse when faceted](https://www.notion.so/DiscreteBar-y-axis-should-not-collapse-when-faceted-85cbc4790e2c4f97a9137195ff92afaa)
Example chart where this goes wrong: https://ourworldindata.org/grapher/per-capita-energy-stacked?facet=metric&country=USA~GBR~OWID_WRL~CHN~IND~FRA~DEU~SWE~ZAF~JPN~BRA

fix(facet): do not share Y axis on StackedDiscreteBar

---

grapher/core/Grapher.tsx
grapher/facetChart/FacetChart.tsx
grapher/facetChart/FacetChartConstants.ts

Notion issue: [Figure out better logic for when to hide/show legend](https://www.notion.so/Figure-out-better-logic-for-when-to-hide-show-legend-d1ec076ec8894dc79c62280106ca5dc5)
When a chart faceted by metric can have countries added/removed, and the user selects only one country, the legend used to collapse itself, example: https://ourworldindata.org/grapher/excess-mortality-p-scores-average-baseline-by-age?country=~GBR
The chart doesn't mention anywhere that the selected entity is United Kingdom. One workaround is to untick "Hide automatic time/entity" in order to show the entity name in the title, but this is not ideal, it leaves it to the author to anticipate that the chart can end up in a state without a legend. 
This PR makes it so that the facet legend is not collapsed if there is …

fix(facet): always show entities in legend if user can edit selection

---

explorer/ExplorerControls.tsx

As mentioned [by Charlie on Slack](https://owid.slack.com/archives/C46U9LXRR/p1632928460002300), the keyboard popping up makes this hard to use on a phone.
At the same time I also lowered the threshold to 10 (again, on desktop only), which is roughly where the dropdown starts to have so many options that it scrolls.

enhance(explorer): explorer dropdowns are never searchable on mobile

---

adminSiteServer/apiRouter.ts
adminSiteServer/app.tsx
baker/DeployUtils.ts
baker/Deployer.ts
baker/GrapherBakingUtils.ts
baker/SiteBaker.tsx
baker/algolia/configureAlgolia.ts
baker/algolia/indexChartsToAlgolia.ts
baker/algolia/indexToAlgolia.ts
baker/buildAndDeploySite.ts
baker/pageOverrides.tsx
baker/slackLog.ts
settings/serverSettings.ts

Notion issue: [Exceptions in baking should prevent deploy](https://www.notion.so/Exceptions-in-baking-should-prevent-deploy-161e34b212734dee944441bee742063a)
I haven't tested this at all, just sharing this because I spotted it yesterday during the call – seems like the exit code was being captured but no action taken. Now the deploy process should halt on a non-zero exit code.
Some things that could lead to this not working:
- A script exits with a non-zero code that we don't care about (e.g. failure to remove a file that isn't there)
- The errors thrown from the baker don't trigger a non-zero exit code
I won't be working on this, I just hope it's useful when/if @mlbrgl gets to look into it.

fix(baker): halt deploy on non-zero exit code

---

grapher/facetChart/FacetChart.tsx
grapher/text/TextWrap.test.ts
grapher/text/TextWrap.tsx

Notion: [Prevent chart titles from overlapping on FacetCharts](https://www.notion.so/Prevent-chart-titles-from-overlapping-on-FacetCharts-5c643f4fc67740afa555f8a875269a71)
Live on _tufte_. Try [this chart](https://tufte-owid.netlify.app/grapher/technology-and-infrastructure-diffusion-in-the-us?facet=metric&uniformYAxis=0&country=~USA) and make the window small.
---
This work has been living on my laptop for quite a while now, and I finally came around to polish & PR it 🙌 
What it does to shrink down labels is described pretty well in this comment:
```
/**
* In order to display a potentially long facet label in the potentially tight space, we
* shrink and shorten the label as follows to prevent overlap between neighbouring labels:
* - If the label already fits, we're happy :)
* - …
```

feat(facet): shrink and shorten facet labels if necessary

---

baker/countryProfiles.tsx
site/CountryProfilePage.tsx

The country profile numbers are poorly formatted, have too many decimal places, and no units. We would prefer not to show them at all. So this PR prunes them from the output.

enhance: Remove specific numbers from country profiles

---

explorer/ExplorerProgram.test.ts
explorer/ExplorerProgram.ts
gridLang/GridProgram.test.ts
gridLang/GridProgram.ts

Notion: [Investigate small-ish explorer improvements to reduce excessive repetition](https://www.notion.so/Investigate-small-ish-explorer-improvements-to-reduce-excessive-repetition-23ac1351285849d4ab964b06c0a82178)
This allows a single column def to be used by multiple tables, like this:
```
table	https://abc	apples
table	https://def	bananas
columns	apples	bananas
slug	type
entity_name	EntityName
```
This should make our life way easier with the Global Food Explorer, where we're probably using tens of tables with the same column definitions.

feat(explorer): one column def can be used for multiple tables

---

baker/formatWordpressPost.tsx
baker/formatting.tsx
baker/siteRenderers.test.ts
baker/siteRenderers.tsx
clientUtils/Util.ts
clientUtils/owidTypes.ts
clientUtils/urls/Url.test.ts
clientUtils/urls/Url.ts
db/wpdb.ts
settings/clientSettings.ts
site/LongFormPage.tsx
site/blocks/ProminentLink.tsx
site/blocks/index.ts
site/blocks/prominent-link.scss
site/owid.entry.ts
wordpress/web/app/plugins/owid/src/ProminentLink/prominent-link.php

sequel to https://github.com/owid/owid-grapher/pull/1030
Loosened error logging on /uploads standalone links, while content is being rewritten. See [notion issue](https://www.notion.so/owid/Automatic-prominent-links-1eafcce85953483d912b6e5f20b928ec#4c7b604dc6894217bf7ad361e49f58b2) for long-term fix.

feat: automatic prominent links (bis)

---

grapher/core/Grapher.tsx

[Slack context](https://owid.slack.com/archives/C46U9LXRR/p1637071765029300?thread_ts=1637064083.024900&cid=C46U9LXRR)
---
I believe this is better than what we have now but not quite sure?
It's just a quick-and-dirty fix anyway, and we really should [Split "Hide automatic time/entity" toggle into multiple ones](https://www.notion.so/Split-Hide-automatic-time-entity-toggle-into-multiple-ones-a3056259ca2248ad865a01a55af12807).
Also, let's wait and see what differences the svg checker comes up with :)

enhance: line chart in relative mode with toggle always shows "Change in"

---

clientUtils/Util.ts
grapher/downloadTab/DownloadTab.scss
grapher/downloadTab/DownloadTab.tsx

Notion issue: [Reorganise download tab options to make space for "not allowed to download" notice](https://www.notion.so/Reorganise-download-tab-options-to-make-space-for-not-allowed-to-download-notice-dfe622ff9ed342618dee2c4ed52786f4)
Deployed on `playfair`: [Explorer](https://playfair-owid.netlify.app/explorers/coronavirus-data-explorer?zoomToSelection=true&time=2020-03-01..latest&facet=none&pickerSort=asc&pickerMetric=location&Metric=Confirmed+cases&Interval=7-day+rolling+average&Relative+to+Population=true&Align+outbreaks=false&country=USA~GBR~CAN~DEU~ITA~IND) | [Grapher](https://playfair-owid.netlify.app/grapher/excess-mortality-raw-death-count)

enhance(grapher): redesign download tab

---

explorerAdminClient/ExplorerCreatePage.tsx
explorerAdminClient/ExplorersListPage.tsx
gitCms/GitCmsServer.ts
gitCms/tsconfig.json

Notion: [Explorer GitCMS should do a pull before pushing](https://www.notion.so/Explorer-GitCMS-should-do-a-pull-before-pushing-5ecb7cffd4cb47a1a2be29141bcd2d25)
turns out, there's a lot of smaller fixes that have come together in here now:
* most importantly, gitCms runs an automatic pull before every write and delete operation
* ... but only if the branch has an upstream branch set up
* if the pull fails, the whole operation fails and is communicated back to the user (through an `alert()`, _but still_)
* the failure is then also logged to slack
* the pull button on the ExplorerListPage is moved all the way to the top, since it might become a little more important now
* there was also an issue where gitCms would always set the git username and email in the `owid-content` repo - which …

feat(explorer): gitCms automatically pulls before committing changes

---

explorer/ExplorerDecisionMatrix.ts
explorer/ExplorerProgram.test.ts
explorer/GrapherGrammar.ts

Notion: [Ability to specify the default view of an explorer](https://www.notion.so/Ability-to-specify-the-default-view-of-an-explorer-459b8da60a5043038e84376d959b6383) - we're gonna need this for the food explorer.
This is deployed to _tufte_. Try it here: https://tufte.owid.cloud/admin/explorers/tunnels
It allows the default view of a explorer to be a different one than the first row of the spreadsheet.
The syntax to use is as follows:
```tsv
graphers							
Type Radio	type		defaultView
In Ground	DiscreteBar
Underwater	DiscreteBar
All types	LineChart	true
```
As you can see in the tests, we also fall back to the default config in the case where a non-existent choice is given, e.g. `?Type=Bridges` would fall back to `All types`.

feat(explorer): can specify the row to use as the default view

---

baker/DeployUtils.ts
baker/bakeSiteOnStagingServer.ts

Notion issue: [Exceptions in build&bake should prevent deploy](https://www.notion.so/Exceptions-in-build-bake-should-prevent-deploy-161e34b212734dee944441bee742063a). 
I was getting this error again while deploying `playfair`, so I tried to fix it.
Now it's getting caught:
```
/home/owid/playfair/bakedSite/atmospheric-concentrations.html
/home/owid/playfair/bakedSite/greenhouse-gas-emissions.html
/home/owid/playfair/bakedSite/emissions-by-sector.html
JsonError: Missing data for query variableId:176101 entityId:355 year:1950 | %year the world emitted 6 billion tonnes of CO<sub>2</sub>. Please check the tag for any missing or wrong argument.
at /home/owid/playfair/itsJustJavascript/baker/formatWordpressPost.js:151:19
at Generator.next (<anonymous>)
at fulfilled …
```

fix: halt deploy on baking error

---

grapher/captionedChart/CaptionedChart.tsx
grapher/core/Grapher.tsx

If they are not integers, there can be very slight increase in blurring/aliasing (or imbalanced border colors) in anything that has lots of horizontal/vertical lines, e.g. legends.
(the top border on "before" is more prominent than the bottom border, in "after" they are _perceptually_ even)

enhance(grapher): ensure width/height are integers

---

explorer/Explorer.tsx

This has been a long-standing issue, but noone really came around to fixing it.
Basically, what's happening here is that `this.isNarrow` specifies whether the `mobile-explorer` class is applied or not, and that class changes up the layout by a layout.
So if we ever change `isNarrow`, we have to wait for the browser to apply the new layout before we fetch the size of the grapher div.
https://user-images.githubusercontent.com/2641501/146197462-81ca4b86-b723-47d7-8090-6655e1c33517.mp4

fix(explorer): properly size the grapher component when explorer switches between wide and narrow mode

---

explorer/Explorer.tsx
grapher/controls/entityPicker/EntityPicker.tsx

Basically, since in the global food explorer we're abusing the notion of multiple tables a bit (since we have multiple tables that all have the same column names), we need to ensure that the entity picker reacts to a table change.
There's also a refactoring of how the different event listeners are disposed of.
https://user-images.githubusercontent.com/2641501/146196753-61438344-9327-49be-837a-331db8860cee.mp4

fix(explorer): EntityPicker reacts to current table changing

---

.bundlewatch.config.json
clientUtils/Util.ts
grapher/color/ColorScale.ts
grapher/color/ColorScaleBin.ts
grapher/horizontalColorLegend/HorizontalColorLegends.tsx
grapher/mapCharts/MapChart.tsx

Notion issue: [Open-ended map brackets](https://www.notion.so/Open-ended-map-brackets-1b46c058954042909716d0d71e2cbe74)
Deployed on playfair, see [**all affected charts**](https://playfair.owid.cloud/admin/test/embeds?ids=26,46,66,75,128,134,194,225,254,259,268,319,351,360,365,366,373,390,438,485,486,488,500,530,533,534,540,586,632,637,639,677,696,699,701,712,737,745,762,768,769,772,775,779,780,797,802,807,812,873,878,879,880,886,888,891,893,909,918,919,1017,1019,1022,1024,1025,1031,1032,1038,1039,1040,1042,1073,1090,1111,1125,1154,1165,1214,1229,1245,1249,1252,1264,1270,1312,1329,1331,1332,1341,1342,1377,1385,1403,1410,1419,1431,1433,1469,1470,1484,1523,1536,1572,1584,1590,1595,1598,1615,1619,1623,1624,1644,1645,1646,1669,1672,1703,1704,1706,1749,1773,1793,1797,1798,1800,1821,1822,1828,18 …

feat(map): open-ended brackets redesign

---

grapher/controls/Controls.scss
grapher/controls/Controls.tsx
grapher/core/Grapher.jsdom.test.ts
grapher/core/Grapher.tsx

Notion: [Title of svg/png export doesn't include date annotation, but interactive chart does](https://www.notion.so/Title-of-svg-png-export-doesn-t-include-date-annotation-but-interactive-chart-does-89bce5655f3a4ae5a66083e9aae88a6f)
Live on _tufte_. Try it here, for example: https://tufte-owid.netlify.app/grapher/co-emissions-per-capita
---
As outlined in the Notion issue, the problem here was that `hasTimeline` was always set to `false` when we are on an overlay tab (SourcesTab or DownloadTab). Since we are on the DownloadTab when downloading a chart (duh), this lead to the logic in `currentTitle` deciding that we should not include the year in the title, at least in the case where `hideTitleAnnotation=true`.
As a solution, I've split it into `hasTimeline` and `showTimeline`, where:
* …

fix(grapher): fix issue where some exports didn't include year in title

---

explorer/urlMigrations/CovidUrlMigration.ts
explorer/urlMigrations/ExplorerUrlMigrationUtils.ts

As [discussed on Slack](https://owid.slack.com/archives/C5BDCB2R3/p1641307912017200).
We are getting rid of `Align outbreaks` in favour of `Color by test positivity`.

Rename "Align outbreaks" checkbox in COVID Explorer

---

grapher/horizontalColorLegend/HorizontalColorLegends.tsx

The "Hide" checkbox otherwise has no effect:

fix(legends): omit hidden bins in numeric legend

---

grapher/scatterCharts/ScatterPlotChart.test.ts
grapher/scatterCharts/ScatterPlotChart.tsx

[Charlie needs a ScatterPlot with Time on the X axis](https://owid.slack.com/archives/C5BDCB2R3/p1641411409032800?thread_ts=1641405010.031600&cid=C5BDCB2R3).
Surprisingly, setting the default column (if none is specified) to be `time` _just works_:
And svgTester reports no differences.
What do you think about the approach?

feat(scatter): plot time on X axis by default if no columns specified

---

clientUtils/Util.test.ts
clientUtils/Util.ts
explorer/ExplorerProgram.ts
grapher/core/Grapher.tsx
site/EmbedChart.tsx
site/SiteHeaderMenus.tsx
site/covid/LastUpdated.tsx
site/stripe/DonateForm.tsx

We have a _lot_ of fetch errors on Bugsnag. I am guessing some good fraction of them are transient network errors (but haven't investigated much), so implementing retries (up to 3 times) would decrease the fetch error rate.
Deployed on [playfair](https://playfair-owid.netlify.app).
Note that `fetch()` doesn't throw when the server responds with an error code, (`404` or `500`):
> -   The Promise returned from `fetch()` **won't reject on HTTP error status** even if the response is an HTTP 404 or 500. Instead, as soon as the server responds with headers, the Promise will resolve normally (with the [`ok`](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok "ok") property of the response set to false if the response isn't in the range 200--299), and it will only reject on network …

enhance: retry fetch requests

---

explorer/Explorer.tsx
explorer/ExplorerProgram.ts
explorer/GrapherGrammar.ts
grapher/core/Grapher.tsx

Notion issue: [Add related link at the bottom of data explorer](https://www.notion.so/Add-related-link-at-the-bottom-of-data-explorer-a06d10a7389e4541b255475a096bc784)
This came up recently, [Max wanted a related question on an explorer](https://owid.slack.com/archives/CLDM2AWCD/p1641496014000100?thread_ts=1641294116.014600&cid=CLDM2AWCD).
In the Grapher config it's possible to add multiple questions, but in the Explorer only a single one. But there are no Graphers that have defined more than one, so I think this is fine.
<details>
<summary>SQL to check for <code>relatedQuestions</code> config:</summary>
<pre>
SELECT id, config->"$.relatedQuestions", JSON_LENGTH(config->"$.relatedQuestions")
FROM charts
WHERE config->"$.relatedQuestions" IS NOT NULL
</pre>
</details>

feat(explorers): allow configuring a related question

---

README.md
package.json
yarn.lock

Not sure if anyone uses this (we could remove it instead) but for now adding it in dev dependencies prevents the `/bin/sh: tmex: command not found` error that Pablo ran into while following the README instructions.
(`tmux` also needs to be installed btw, maybe should mention that in the README too?)

fix: install `tmex`

---

adminSiteClient/EditorScatterTab.tsx
grapher/captionedChart/CaptionedChart.stories.tsx
grapher/captionedChart/CaptionedChart.tsx
grapher/controls/Controls.tsx
grapher/core/Grapher.tsx
grapher/core/GrapherConstants.ts
grapher/core/GrapherInterface.ts

[As discussed here](https://owid.slack.com/archives/CQQUA2C2U/p1643054986036100)
we haven't used it in any chart since 2020, so let's get rid of the code behind it now

refactor: remove highlightToggle

---

baker/algolia/configureAlgolia.ts

This enables a bunch of the language-dependent features we have enabled, like `ignorePlurals`.
Related discussion: https://owid.slack.com/archives/CQQUA2C2U/p1643114057010100

chore(algolia): specify English as default search language

---

site/SiteHeaderMenus.tsx

There is some Safari bug on both macOS and iOS that leads to a `(0,m.fetchWithRetries) is not a function.` error. 
We could potentially see if #1060 fixes it, but until then we can just fetch the header menu without retries.
Slack discussion: https://owid.slack.com/archives/CQQUA2C2U/p1643017308010200
Error on Bugsnag: https://app.bugsnag.com/our-world-in-data/our-world-in-data-website/errors/61e8217018e327000758b9e3

fix: use `fetch` instead of `fetchWithRetries` in SiteHeaderMenus

---

adminSiteServer/adminRouter.tsx
adminSiteServer/mockSiteRouter.tsx
baker/ExplorerBaker.tsx
baker/SiteBaker.tsx
baker/siteRenderers.test.ts
baker/siteRenderers.tsx
explorerAdminServer/ExplorerAdminServer.test.ts
explorerAdminServer/ExplorerAdminServer.tsx

This comes as a side-effect of [Shift prominent link transformation to editor on copy / paste](https://www.notion.so/Shift-prominent-link-transformation-to-editor-on-copy-paste-6dc963e803f34363b48d6f2147e74428), which merges authored (aka manual) prominent links with automatic prominent links (whereby https://ourworldindata.org/xyz is transformed into a fully-fledged prominent links at bake time).
Authored prominent links will then inherit the capabilities of their automatic counterpart, which rely on requesting missing information (title and image) from the DB.
Previously, explorer pages were only rendering authored prominent links. With this merge, they now need to be able to render the full prominent links (with optional DB fallback). Pulling that content in can't (and shouldn't …

Refactor explorerAdminServer

---

baker/algolia/configureAlgolia.ts

I _believe_ that we also have to set the global `ignorePlurals` for that setting to work.
Additionally, I went through the list of common queries without results and added some more synonyms.

chore: fine-tune Algolia settings, introduce more synonyms

---

baker/algolia/configureAlgolia.ts
baker/algolia/indexChartsToAlgolia.ts

[As discussed here](https://owid.slack.com/archives/C014N17DHEC/p1643195645008300), this is one of the easiest ways for us to improve the charts that show up in chart results.
At first I was unsure how long "calculating" this information would take for all the charts that we have, but that's not an issue at all thankfully - on tufte index creation took just 6 seconds! (the graph DB is created once, and then only queried subsequently)
~Note, however, that this doesn't consider the new `numRelatedArticles` metric for search ranking yet - that we have to enable once we have played around with it a bit.~

feat(algolia): rank chart by number of references to a chart

---

.vscode/launch.json
adminSiteClient/ChartEditor.ts
adminSiteClient/ChartEditorPage.tsx
adminSiteClient/EditorTextTab.tsx
adminSiteClient/admin.scss
adminSiteServer/apiRouter.ts
baker/GrapherBaker.tsx
baker/algolia/configureAlgolia.ts
baker/algolia/indexContentGraphToAlgolia.test.ts
baker/algolia/indexContentGraphToAlgolia.ts
baker/formatWordpressPost.tsx
baker/formatting.tsx
baker/siteRenderers.test.ts
baker/siteRenderers.tsx
clientUtils/owidTypes.ts
db/contentGraph.test.ts
db/contentGraph.ts
db/wpdb.ts
grapher/core/Grapher.tsx
grapher/core/GrapherConstants.ts
grapher/core/GrapherInterface.ts
package.json
settings/clientSettings.ts
site/blocks/ProminentLink.tsx
site/formatting.tsx
wordpress/composer.json
wordpress/composer.lock
wordpress/web/app/plugins/owid/owid.php

This is a PoC to merge Wordpress and the admin tagging systems.
Categories and tags are dropped in favour of parent / child relationships: in Wordpress entries become topics that reference each other, while in the admin, charts reference those topics.
Background info, rationale and video demos: [One single taxonomy between grapher and wordpress](https://www.notion.so/One-single-taxonomy-between-grapher-and-wordpress-4992c4f2671248c8872e19073debb172)
Those relationships are baked into a bi-directional data structure (aka "content graph") powered by [Fortune.js](http://fortune.js.org/) (currently used for "All our related research and data" block on grapher pages, e.g. https://ourworldindata.org/grapher/population-density). This data structure is only available at bake and preview time, it …

Content graph, one taxonomy, entries as topics

---

clientUtils/Util.test.ts
clientUtils/Util.ts
explorer/ExplorerProgram.ts
grapher/core/Grapher.tsx
site/EmbedChart.tsx
site/covid/LastUpdated.tsx
site/stripe/DonateForm.tsx

Reverts #1066 because we had issues with it in loading `headerMenu.json`, and potentially Explorer table loading errors from it are not being logged in Bugsnag, because no error is being thrown, only `setError` called on Grapher: https://github.com/owid/owid-grapher/blob/36fb4246211d2a66c18bb9da52cfcbfcbc354778/explorer/Explorer.tsx#L297

Revert "enhance: retry fetch requests" #1066

---

grapher/chart/ChartManager.ts
grapher/facetChart/FacetChart.tsx
grapher/lineCharts/LineChartConstants.ts

Fixes #1098. 
@MarcelGerber was right that only `startHandleTimeBound` needs to be passed on for this to work. I made it a property of `ChartManager` to enable this.
---
Related: Now that we have faceted charts, all the specific chart managers (`LineChartManager`, `ScatterPlotManager`, etc) are basically getting merged into `ChartManager` in order to make it possible to pass props to individual facets. Or at least that's what I'm doing. The alternative is to keep them separate, and make `ChartManager` a union of all specific chart manager – maybe that's better?

fix(facets): relative line charts

---

.gitignore
.gitpod.yml

This PR adds a Gitpod configuration (`.gitpod.yml`), which allows opening up this code base in Gitpod with one click. It greatly simplifies contributing to projects by spinning up a dev environment with everything set up in the cloud.
You can start the Gitpod environment by simply prefixing a GitHub URL by `gitpod.io/#`. For example, [this link](https://gitpod.io/#https://github.com/owid/owid-grapher/pull/1117) opens this branch/PR in Gitpod. If you're not familiar with Gitpod, check out their [website](https://gitpod.io). It's similar to GitHub codespaces, but open-source and more user-friendly (in my mind).
One caveat with this setup is that I chose MySQL 8.0 (default for Ubuntu 20.04), not 5.7 as recommended in the readme. I can switch to 5.7, but this will complicate the setup a bit …

Add Gitpod

---

package.json
yarn.lock

When running `yarn`:
`warning " > mobx-utils@5.6.2" has incorrect peer dependency "mobx@^4.13.1 || ^5.13.1".`
(currently, we are on mobx@5.13.0)
When previewing the site, this manifests as:
This PR upgrades mobx to the latest 5.x.x

chore: fix mobx-utils peer-dep (mobx)

---

adminSiteClient/SuggestedChartRevision.ts
adminSiteClient/SuggestedChartRevisionApproverPage.tsx
adminSiteClient/SuggestedChartRevisionList.tsx
adminSiteServer/apiRouter.ts
baker/tsconfig.json
clientUtils/owidTypes.ts
db/model/SuggestedChartRevision.ts
db/tsconfig.json
devTools/project-dependencies.md

This is part 1 of ♾️ of the #1082 work.
I noticed that `db` had a dependency on `adminSiteClient`, which is a red flag really. Thankfully, the dependency only existed because of an enum import, and could be resolved by using this type to `owidTypes` in the bottom `clientUtils` module.
I also realized that TS project references are transitive (i.e. if A -> B and B -> C, then A can also import modules from C without explicitly listing C), so the `project-dependencies.md` graph doesn't even reflect all the various interdependencies that we have.

refactor: move SuggestedChartRevisionStatus enum to clientUtils

---

coreTable/CoreTable.ts
coreTable/CoreTableColumns.ts
coreTable/CoreTableUtils.ts
grapher/axis/Axis.test.ts
grapher/axis/Axis.ts
grapher/axis/AxisConfig.ts
grapher/axis/AxisConfigInterface.ts
grapher/barCharts/DiscreteBarChart.tsx
grapher/chart/ChartManager.ts
grapher/core/Grapher.tsx
grapher/lineCharts/LineChart.tsx
grapher/mapCharts/MapChart.tsx
grapher/scatterCharts/ScatterPlotChart.tsx
grapher/scatterCharts/ScatterPlotChartConstants.ts
grapher/scatterCharts/ScatterPointsWithLabels.tsx
grapher/slopeCharts/SlopeChart.tsx
grapher/stackedCharts/AbstractStackedChart.tsx
grapher/stackedCharts/MarimekkoChart.tsx
grapher/tooltip/Tooltip.tsx

This is prep work for implementing https://github.com/owid/owid-grapher/issues/1087.
- ⭐ **`ticks` is a config property allowing you to override the automatic tick generation and use manual ticks (it allows showing just the start & end ticks in sparklines). If a tick value is `-Infinity` or `Infinity`, it gets replaced with the minimum or maximum value in the data.**
- `hideGridlines` is now a config property instead of a mutable property of `Axis` (it made things cleaner)
- ⭐ **Time columns now have prepositions: `in` used for years & quarters, `on` for dates.** (the only place they will be used are sparklines, but we can add them in other places after this is merged)
- `replaceCells` used to be a utility function private to CoreTable, now it's a public method on CoreTable. I had used it …

Map sparklines #1: Prep work

---

clientUtils/Util.ts
coreTable/CoreTable.ts
coreTable/CoreTableColumns.ts
coreTable/CoreTableConstants.ts
coreTable/OwidTableConstants.ts
grapher/lineCharts/LineChart.tsx
grapher/mapCharts/MapChart.tsx
grapher/mapCharts/MapChartConstants.ts
grapher/mapCharts/MapTooltip.jsdom.test.tsx
grapher/mapCharts/MapTooltip.scss
grapher/mapCharts/MapTooltip.tsx

Fixes #1087, continuation of and based on top of #1159.
https://user-images.githubusercontent.com/1308115/154110274-e1a8fe4f-901a-4984-a399-182d7df1e131.mp4
- [Life expectancy map](https://playfair-owid.netlify.app/grapher/life-expectancy) (interesting because UK data starts at 1543 but others much later)
- [Energy embedded in traded goods map](https://playfair-owid.netlify.app/grapher/traded-energy-share-domestic) (diverging color scale, contains negative values)
- [COVID vaccine age map](https://playfair-owid.netlify.app/grapher/covid-vaccine-age) (numerical values are coded to text values)
- [COVID cases map](https://playfair-owid.netlify.app/explorers/coronavirus-data-explorer?tab=map&zoomToSelection=true&time=2021-08-20&facet=none&pickerSort=asc&pickerMetric=location&Interval=7-day+ro …

Map sparklines #2: Feature work

---

adminSiteServer/apiRouter.ts

Fixes #1209.
In the case where a new chart would immediately be published (without first creating a draft), the duplicate slug detection didn't quite work.
Since we didn't yet have an ID for that chart, the corresponding query would look like this:
```sql
SELECT *
FROM charts
WHERE id != NULL
AND JSON_EXTRACT(config, "$.isPublished") IS TRUE
AND JSON_EXTRACT(config, "$.slug") = '...'
```
However, since SQL is oh-so-awesome, `id != NULL` would never evaluate to true.

fix(admin): properly check for duplicate slugs

---

adminSiteClient/ImportPage.tsx

When importing data, there are client-side warnings that check if a value is a number. We have plenty of scientific notation numbers in our database and they are handled fine, so I'm allowing scientific notation in the regex that checks for numbers.
Problem reported by [Pablo on Slack](https://owid.slack.com/archives/C01GAN73R5W/p1645453849936399).

fix: do not show non-numeric warning for scientific notation

---

clientUtils/owidTypes.ts
site/formatting.test.ts
site/formatting.tsx

resolves #1112 
- legacy h6 caption + image combos are not considered standalone figures and are not moved to the left column
- 2n+1 charts are positioned as follows: 2n in a `side-by-side` split, and the remaining one in the left column of a `sticky-left` layout. Reason for not using a `side-by-side` layout for the remaining chart: added complexity not warranted given the low occurrence of that setup.
- add tests for automatic layout engine (`splitContentIntoSectionsAndColumns()`)
- refactor automatic layout engine using chain of responsibility pattern (baseline tests before refactoring added in #1219)

Moves standalone visualizations to left column

---

adminSiteClient/DimensionCard.tsx
adminSiteClient/EditorDataTab.tsx
grapher/core/Grapher.tsx
grapher/core/GrapherInterface.ts

Live on _tufte_.
---
Fixes #1145.
This is mostly using the existing fix from #846, but there was a `grapher.seriesColorMap.clear()` missing to make sure that the update is immediately visible in the preview.
---
There is one problem that still exists, which is `selectedData`. For charts where it is still present, it's not possible to clear the color that's set in `selectedData`.
You can see this in action at http://tufte.owid.cloud/admin/charts/216/edit, for example: Try to clear out the orange color for "Western Pacific", and you'll fail miserably.
However, I feel like this should be addressed separately, and the issue with `selectedData` is already tracked in #1111.

fix(admin): allow resetting dimension color using color picker

---

adminSiteClient/Admin.tsx
adminSiteClient/DeployStatusPage.tsx
adminSiteServer/apiRouter.ts

Live on _tufte_. [Try it here](https://tufte.owid.cloud/admin/deploys) (yes, feel free to hit that button).
Are you tired of modifying a random chart just to trigger an explorer bake? Or to kick off an awfully long-running rebake after a staging server DB update?
Here comes the solution - it's a button!
(And yes, I realize that this isn't the ideal solution for the explorer baking issue, but it might as well be good enough. And it can be used in other cases, too!)

feat(admin): add button to trigger manual deploy

---

baker/sitemap.ts
clientUtils/Util.ts
clientUtils/dayjs.ts
coreTable/CoreTableColumns.ts
devTools/cypress/integration/cookiePreferences.js
explorerAdminClient/ExplorersListPage.tsx
package.json
site/CitationMeta.tsx
site/CookiePreferencesManager.tsx
site/EntriesByYearPage.tsx
site/blocks/CookiePreferences.tsx
site/covid/CovidFetch.ts
site/covid/LastUpdated.tsx
webpack.config.ts
yarn.lock

Live on _tufte_.
MomentJS is old and creaky and bloated, dayjs is new and beautiful and, crucially, mostly a drop-in replacement for MomentJS.
So let's get rid of moment for good.

refactor: drop momentjs in favor of dayjs

---

adminSiteClient/BulkDownloadPage.tsx
adminSiteClient/ChartList.tsx
adminSiteServer/apiRouter.ts
adminSiteServer/mockSiteRouter.tsx
baker/redirects.ts
db/migration/1646815966637-RemoveStarredCharts.ts
db/model/Chart.ts

Starred charts were a way to feature one big chart on the homepage.
They were [last used in February 2019](https://web.archive.org/web/20190218172333/https://ourworldindata.org/).
So let's get rid of all the code related to them.

refactor: remove support for starred charts

---

devTools/docker/mysql-init-docker/Dockerfile
docker-compose.yml

The mysql-server:8.0 image only has amd64 as a flavour, meaning that the first init takes ~1h on M1 Macs. After the switch it takes more like ~10min.

enhance: use mysql-server:latest image for better arm64 support

---

devTools/docker/download-wordpress-mysql.sh
devTools/docker/download-wordpress-uploads.sh
wordpress/scripts/deploy.sh
wordpress/scripts/refresh-staging.sh

We currently assume that everyone has the same `.ssh/config` settings for our work, but that's mainly to hard-code IP addresses for our servers.
Instead, this change simply uses the friendly DNS for each step, avoiding the need for common settings.

chore: avoid the need for special ssh settings

---

devTools/docker/create-and-fill-wordpress-db.sh
devTools/docker/create-wordpress-admin-user.sh

Configure the dev environment by default so that it doesn't contain any password hashes from the live wordpress dump, but instead has a new user `admin@example.com` with password `admin` that you can use to log in with.

enhance(dev): add a wordpress admin user when building dev environment

---

adminSiteClient/DimensionCard.tsx
clientUtils/formatValue.ts
coreTable/CoreTableColumns.ts
db/migration/1646223315110-DropDisplayForSizeDimension.ts
grapher/scatterCharts/Halos.tsx
grapher/scatterCharts/ScatterPlotChart.test.ts
grapher/scatterCharts/ScatterPlotChart.tsx
grapher/scatterCharts/ScatterPlotChartConstants.ts
grapher/scatterCharts/ScatterPointsWithLabels.tsx
grapher/scatterCharts/ScatterUtils.ts
grapher/verticalColorLegend/VerticalColorLegend.stories.tsx
grapher/verticalColorLegend/VerticalColorLegend.tsx

Working on https://github.com/owid/owid-grapher/issues/1089.
In this PR:
- The Admin now allows specifying `dimension.display` for the size dimension on a Grapher (the dropdown used to be disabled)
- Consequently, **the `tolerance` for the `size` dimension is now considered**. It used to be ignored and always `Infinity`.
- Some older charts had `dimension.display` populated for the `size` dimension, even though it was ignored. **A migration now wipes `dimension.display` for the size dimension for all ScatterPlots.** I have gone through all affected charts, and they all seem good (there are 3 categories: [charts that use the default size variable](https://playfair.owid.cloud/admin/test/embeds?ids=51,53,84,85,150,161,172,177,178,185,212,213,214,245,250,251,275,290,294,306,335,340,354,355,356 …

Scatter size legend #1: Prep work

---

grapher/scatterCharts/ScatterPlotChart.test.ts
grapher/scatterCharts/ScatterPlotChart.tsx
grapher/scatterCharts/ScatterPlotChartConstants.ts
grapher/scatterCharts/ScatterPoints.tsx
grapher/scatterCharts/ScatterPointsWithLabels.tsx
grapher/scatterCharts/ScatterSizeLegend.tsx
grapher/scatterCharts/ScatterUtils.ts

Fixes #1089 | [Deployed on playfair](https://playfair.owid.cloud/admin/test/embeds?type=ScatterPlot) | [Slack #design discussion](https://owid.slack.com/archives/C5BDCB2R3/p1645630994255989)
This PR adds a ScatterPlot size legend:
https://user-images.githubusercontent.com/1308115/157084760-c7fb71ac-7b03-4707-9620-d1c9ad26bfd7.mp4
- The point radius scale has been changed to be more perceptually accurate – the area did not always correspond to magnitude in the past, [for example](https://playfair.owid.cloud/admin/test/embeds?ids=308&comparisonUrl=https%3A%2F%2Fourworldindata.org) (before/after):
(Luxembourg **~$106**, Poland **~$26**. Perceptually the scale was wrong in some cases in the past.)
- It was possible [to have zero-radius, invisible …

Scatter size legend #2: Feature work

---

.env.example-full
.env.example-grapher
Makefile

Add a Makefile flow for working with the full wordpress stack, including downloading the data you need.
- All data required will be downloaded, including uploads
- If your `.env` file is missing wordpress configuration, it will warn you and abort
- If you have no `.env` file, it will use `.env.example-full` instead

chore: Add "make up.full" and "make down.full" for wordpress

---

devTools/docker/wordpress-php-docker/Dockerfile

My Docker Wordpress was very slow.
[After a quick look around](https://serverfault.com/a/956661), I found out that opcache is not enabled by default, and enabling that speeds up PHP considerably.
And sure enough, after enabling opcache (and running `docker-compose -f docker-compose.full.yml --build`) Wordpress is now okay fast (not blazing fast sadly).
For review for @mlbrgl because he will know best what the repercussions are :)

feat(docker): enable php opcache

---

db/migration/1647866984314-LineChartYMaxZero.ts

Fixes https://github.com/owid/owid-issues/issues/140.
This is a **database migration only**, no implementation changes on the Grapher. It's a mass-fix for an authoring issue.
The `version` is not bumped intentionally, to avoid re-baking the data and exports for 2000+ charts. The chart config is updated on every bake anyway (unlike exports), so all interactive charts will be fixed without a version bump.

fix: edit some charts to make Y=0 line always visible

---

adminSiteClient/EditorCustomizeTab.tsx
clientUtils/owidTypes.ts
grapher/barCharts/DiscreteBarChart.tsx
grapher/stackedCharts/MarimekkoChart.tsx
grapher/stackedCharts/StackedDiscreteBarChart.test.ts
grapher/stackedCharts/StackedDiscreteBarChart.tsx

Fixes #1344.
We have some charts, like [Global crop production by farm size](https://ourworldindata.org/grapher/global-crop-production-by-farm-size) and [Death rates from smoking by age](https://ourworldindata.org/grapher/death-rates-smoking-age), where none of the existing sort orders make sense. We really want to display the entities in the same order as they are specified in the Admin.
Hence, I added a new option for "custom" order, which then does exactly that. See video below.
https://user-images.githubusercontent.com/2641501/159874897-d200c26b-5121-48e1-8a13-fa4bdd711f4e.mp4

feat: can specify custom sort order for StackedDiscreteBar

---

Makefile

When first bringing up the full stack, auto-add a `wordpress/.env` file if it is missing.

fix(Makefile): ensure we have a wordpress/.env file

---

Makefile
README.md
docs/docker-compose-mysql.md
docs/full-wordpress-setup.md
settings/serverSettings.ts
wordpress/.env.example
wordpress/config/application.php

Follow up to #1359.
I think we have to rename these ones too in order to be consistent, or is there a specific reason you left them out @ikesau?
basically, this means that in `wordpress/.env` too, everyone will have to rename `DB_NAME` -> `WORDPRESS_DB_NAME` etc.

Rename more env variables

---

grapher/barCharts/DiscreteBarChart.test.ts
grapher/barCharts/DiscreteBarChart.tsx

This PR closes #1347.
Improved readability and updated DiscreteBarChart.test to take changes into account
It now looks like this:

enhance(DiscreteBarChart): Improve readability of DiscreteBar value and year labels

---

site/DataToken.tsx
site/covid/FullWidthRawHtml.tsx
site/runDataTokens.tsx

Support dynamic **client-side** insertion of covid vaccination table in /covid-vaccinations.
Format: `{{FullWidthRawHtml url:https://[URL_HERE]}}`
- Short version: `{{FullWidthRawHtml}}` tags need to be inside a "Custom HTML" Wordpress block. 
- Longer version: this "need" is a conceptual constraint, to simplify the understanding of {{FullWidthRawHtml}} tags. By default, Gutenberg wraps every paragraph in a `<p>`, which would prevent the [FullWidthHandler](https://github.com/owid/owid-grapher/blob/3d41b1e33227c1312bb8b698bb8840f15fc7d741/site/formatting.tsx#L122) from kicking in (since it only matches top-level elements). Technically, this is not an issue since [empty `<p>` are cleaned up](https://github.com/owid/owid-grapher/blob/3d41b1e33227c1312bb8b698bb8840f15fc7d741/baker/formatWordpr …

Add {{FullWidthRawHtml}} data token

---

adminSiteClient/Forms.tsx

Fixes the source of #1092 
`onBlur` resolves before the submit handler, so the request payload is correctly trimmed.

improve(Forms.tsx): trim inputs on blur

---

adminSiteClient/GrapherConfigGridEditor.tsx
adminSiteClient/GrapherConfigGridEditorTypesAndUtils.tsx
clientUtils/schemaProcessing.ts

This PR is part of #1224 - it adds a new operator so that on time fields like maxTime you can query for entries "latest" or "earliest"

Bulk-fastt-enable-latest-earliest

---

grapher/axis/Axis.ts

This PR fixes #1267 
Now Axis tick labels include sufficient decimal places.
The chart now looks like this,
Often baseTicks added ticks with duplicate start and end values with different priorities. Since they had different priorities, they were not filtered by `uniq`.
https://github.com/owid/owid-grapher/blob/58fb266f3c105f8fef13741b86332f655df7452b/grapher/axis/Axis.ts#L463-L482
Due to this, `numDecimalPlaces` is always 1
https://github.com/owid/owid-grapher/blob/58fb266f3c105f8fef13741b86332f655df7452b/grapher/axis/Axis.ts#L323-L332

fix: Axis tick labels shows proper decimal places.

---

.gitpod.yml
grapher/core/grapher.scss
grapher/footer/Footer.tsx
grapher/sourcesTab/SourcesTab.scss
grapher/sourcesTab/SourcesTab.tsx

This PR closes #1151 and contains the following:
**Fix grapher footer source text selection**
Users couldn't select the source text, but this is useful to quickly copy and paste the source. I made the text selectable and removed the `onClick` action that would open the Source tab when clicking the source. I think it's a better user experience because a) selecting the source text in order to copy it would open the Source tab (annoying), b) clicking a non-link, non-button text is not expected to do something, and c) the Source tab is just below and well visible anyways.
I also did the following:
- Removed the class `noselect` as it was not being used (or at least I didn't find where)
- Removed `user-select` from `button`and `clickable` - I don't see what this really adds here?
**Improve …

Fix source text footer and improve source styling

---

grapher/barCharts/DiscreteBarChart.tsx

I'm still trying to fully understand the code but I had an initial idea for this fix. (Issue #1346)
I first thought of editing the `legendLabelStyle` function, but I couldn't figure out how to access `barHeight`, so I moved `fontSize` and `fontWeight` inside the `<text>` tags.
For now, this only takes into consideration `barHeight` with some approximate values for the heights and font sizes.
Please let me know if this approach is alright and I will do the same for `valueLabelStyle` as well.

Fix bar chart font size

---

devTools/docker/create-wordpress-admin-user.sh

Without this, the admin user cannot access all WP backend features, including rich text (block) editing, which makes local development difficult.

Give wordpress admin user administrator rights + rich editing

---

grapher/mapCharts/MapChart.tsx
grapher/mapCharts/MapTooltip.tsx

Fixes #1342 
Transformation of data into labels was already done for numeric values, so I included the condition for strings as well.
The same formatting is done to empty/undefined data, instead of returning a constant "No data" string.
I have tested this in the dev admin server and the graph mentioned in the issue, please let me know if any changes need to be made.

Show custom label for categorical datum in map tooltip

---

grapher/axis/Axis.test.ts
grapher/axis/Axis.ts

Fixes #1267, but in a different way to #1394.
I feel like this is the more sensible way to go about this problem.
The main difference here is this one here in the output of `HorizontalAxis.baseTicks`:
```diff
[
-   { value: 0, priority: 2 },
+   { value: 0, priority: 1 },
{ value: 0.00005, priority: 2 },
{ value: 0.0001, priority: 2 },
{ value: 0.00015, priority: 2 },
{ value: 0.0002, priority: 2 },
{ value: 0.00025, priority: 2 },
{ value: 0.0003, priority: 2 },
{ value: 0.00035, priority: 2 },
{ value: 0.0004, priority: 2 }
]
```
In addition, I added a test case (which passes for both the old & new fix, and fails without them) which we should get in either way :)

different fix: Axis tick labels shows proper decimal places

---

grapher/chart/ChartManager.ts
grapher/facetChart/FacetChart.tsx

[Slack context](https://owid.slack.com/archives/C46U9LXRR/p1652300758047539)
otherwise, DiscreteBarChart and StackedBarChart don't know whether a
value was tolerance-induced or not, and will always display the date of
the data point
In the above view, the `on Dec 30, 2021` shouldn't be there because every data point is from that date, _and_ the timeline is set to that date, too.

fix(facet): pass `endTime` to faceted chart

---

baker/countryProfiles.tsx
site/CountryProfilePage.tsx
site/runCountryProfilePage.ts

Spun off from #1320, this is an attempt to use the cleanup work from there at least:
* remove unused code that was used to format the latest data value
* properly handle undefined config fields like `config.type` and `config.hasChartType`, and use the defaults there (LineChart, true)
* always use the current year as the latest year, and a 10-year backwards time window around it
* display the variant name in grey and not as part of the link

refactor: clean up country profile code

---

clientUtils/Util.ts
clientUtils/patchHelper.ts
clientUtils/schemaProcessing.ts
grapher/chart/ChartManager.ts
grapher/core/Grapher.tsx
grapher/facetChart/FacetChart.tsx
grapher/footer/Footer.tsx
grapher/footer/FooterManager.ts
grapher/lineCharts/LineChart.tsx
grapher/lineCharts/LineChartConstants.ts
grapher/mapCharts/MapTooltip.stories.tsx
grapher/mapCharts/MapTooltip.tsx
grapher/stackedCharts/StackedAreaChart.tsx
grapher/stackedCharts/StackedBarChart.tsx
grapher/tooltip/Tooltip.tsx
grapher/tooltip/TooltipProps.ts

Partially resolves https://github.com/owid/owid-grapher/issues/1084
**The Tooltip module now stores tooltips in an `ObservableMap` instead of referencing a single instance.**
_This will allow for simultaneous synchronised tooltips on facet charts in the future_
**Connects  `FacetChart`'s managers to the parent `Grapher` `tooltips` instance**
_This allows the tooltip to be added to the tooltips map correctly and be rendered by Grapher._

improve(FacetChart.tsx): tooltips

---

baker/siteRenderers.tsx

This should be ok given the single usage of this function so far, which always happens after URLs have been resolved.

refactor(prom links): simplify renderGrapherImageByChartSlug

---

explorer/ExplorerProgram.test.ts
explorer/ExplorerProgram.ts
explorerAdminClient/ExplorerCreatePage.tsx
gridLang/GridLangConstants.ts

Fixes #1329.
There is now a valid way to enter subtitles with newlines, which doesn't screw up `TextWrap`.
They can be entered either by hand, or by pressing `Ctrl + Enter` in the Handsontable editor.
---
Potential caveat: For the sources tab, we already extensively use HTML formatting and `<br>`s. It might be confusing that the sources tab can use `<br>` just fine, but that authors need to use `\n` for subtitles and footnotes.
---
TODOs after merging:

Ability to enter newlines in explorer config

---

adminSiteClient/GrapherConfigGridEditor.tsx
devTools/schemaProcessor/columns.json
grapher/schema/grapher-schema.001.json
grapher/schema/grapher-schema.001.yaml

Fixes #1439, supersedes #1152.
Now we have a Cloudflare Worker in place for `files.ourworldindata.org`, so we can change all references.

fix: consistent grapher schema URLs

---

grapher/controls/Controls.tsx
grapher/core/GrapherConstants.ts
grapher/facetChart/FacetChart.tsx

`DiscreteBar` used to try to collapse the axis when "uniform Y axis" is checked, this fixes that ([chart](https://ourworldindata.org/grapher/share-who-currently-had-depression-by-age-and-gender)):
https://user-images.githubusercontent.com/1308115/168875112-277ddf4a-ac95-450f-bba8-a79c62d20f67.mp4

fix(facets): do not share Y axis on faceted DiscreteBar

---

clientUtils/Bounds.ts
grapher/text/TextWrap.test.ts
grapher/text/TextWrap.tsx

Issue: [Lucas reported this issue here on Slack](https://owid.slack.com/archives/C46U9LXRR/p1653160820675989)
In our svg and png exports, the first line after a newline had an unintentional indent:
This happened because `TextWrap.lines()` was not stripping out leading newlines, and they would be rendered as a space in the svg version of a chart (but not in the HTML version).
E.g. for the above chart, it would be `["- Flexitarian [...]", "\n- Pescetarian [...]"]`.
I also used the opportunity to add test cases for `.lines()`, which didn't have any test coverage beforehand.

fix: strip out newlines in TextWrap

---

clientUtils/owidTypes.ts
grapher/axis/Axis.test.ts
grapher/axis/Axis.ts
grapher/axis/AxisConfig.ts
grapher/axis/AxisConfigInterface.ts
grapher/barCharts/DiscreteBarChart.tsx
grapher/core/Grapher.jsdom.test.ts
grapher/core/Grapher.tsx
grapher/lineCharts/LineChart.tsx
grapher/stackedCharts/StackedAreaChart.tsx

Fixes #1191 | Fixes #1100 | Live on tufte: [Example](https://tufte-owid.netlify.app/grapher/distribution-of-population-between-different-poverty-thresholds-up-to-30-dollars?stackMode=relative&time=latest&country=~CHN)
Unbreaks StackedArea when a single year is selected (#1191) - it's basically a wide StackedBar chart then - and adds a timeline to StackedArea and StackedBar charts (#1100).
All in all, I feel like the timelines are a great benefit and are useful for pretty much all charts.
However, in looking at some of them side-by-side, there are some where `minTime`/`maxTime` is set but `timelineMinTime`/`timelineMaxTime` is not. I will go through and check with the authors if necessary. One example is [this chart on same-sex marriage](https://halley-owid.netlify.app/grapher/same-sex-hous …

Fix single-year StackedArea charts and enable timeline for them

---

grapher/horizontalColorLegend/HorizontalColorLegends.tsx
grapher/stackedCharts/MarimekkoChart.jsdom.test.tsx
grapher/stackedCharts/MarimekkoChart.test.tsx
grapher/stackedCharts/MarimekkoChart.tsx
grapher/stackedCharts/MarimekkoChartConstants.ts

This fixes a few issues that Charlie found and adds a few things I wanted to do for a while:
1. It is now possible to hide categories from the legend (Antarctica was a common request to hide)
2. The (wrong) interpolation hint in the on-hover panel for the x axis is now gone when the "x axis time override" is set. A proper solution will need proper join support between years and days. For now, all Marimekko charts that want to merge days and years (e.g. vaccincation data and population) use the x axis time override anyhow and so we can use this to hide the wrong time notice in the tooltip
3. I made it possible to use a marimekko chart without specifying an x axis. This turns it into a tightly stacked bar chart which can be useful for

Marimekko tweaks

---

grapher/axis/Axis.ts
grapher/core/Grapher.tsx
grapher/stackedCharts/MarimekkoChart.tsx

Additional tweaks based on authors feedback. This does the following:
* X axis and grid lines hidden if no x variable mapped
* improved sorting and label picking to make sure first and last items are picked of the range with values and the first (desc) or last (asc) label of the no/0 values range
* Ensured that sort order with same values is consistent (sort by name if value is equal)
* Bars are rendered at least one pixel high always so that they are visible as a thin line
* Hide controls that don't make sense without the x variable being mapped
I attempted to get Antarctica to hide automatically but that didn't work unfortunately.
This PR now has diffs against existing Marimekkos because I changed the labeling strategy somewhat, I think for the better.

Marimekko-tweaks-with-feedback

---

grapher/lineCharts/LineChart.tsx
grapher/lineCharts/LineChartConstants.ts
grapher/stackedCharts/StackedAreaChart.tsx

Fixes #1331.
Expands the mouse target zone around the first and last point in the chart by ~5% of the axis width each~ 44px (mobile) or 25px (otherwise). These numbers are of course arbitrary, but seem to work quite well on my phone and laptop.
https://user-images.githubusercontent.com/2641501/165938794-32033030-9e28-416f-9e31-66602099ad4e.mp4

feat: expand mouse target for LineChart/StackedArea tooltip

---

coreTable/CoreColumnDef.ts
coreTable/CoreTableColumns.test.ts
coreTable/CoreTableColumns.ts
grapher/core/LegacyToOwidTable.ts
grapher/mapCharts/MapChart.tsx

[As discussed on Slack](https://owid.slack.com/archives/CQQUA2C2U/p1654084452507939?thread_ts=1654073915.561489&cid=CQQUA2C2U) | Incidentally fixes #1273 
Our `CoreTableColumns` are all typed, but that is not a good fit for grapher variables. These can be either numeric, or have string values, or can even contain a mix of the two.
While `NumericColumn` can mostly handle string values fine, it cannot format them and will only output an empty string in this case.
So, in this PR I introduce a new column type, `NumberOrStringColumn`, that behaves mostly like `NumericColumn` but can also format string values.

refactor: introduce new column type `NumberOrStringColumn`

---

grapher/stackedCharts/StackedAreaChart.tsx

Just a tiny fix. Didn't check if other chart tooltips might be missing this...

enhance(StackedArea): do not trim trailing zeroes in tooltip

---

db/migration/1653584089031-DetailsOnDemand.ts

Resolves #1467
~Realized there was no point in having an `AUTO_INCREMENT` id if we can always just use the category and term to index.~
Update: added an `AUTO_INCREMENT` id 😊

feat(details on demand): add details table to grapher DB

---

.bundlewatch.config.json
adminSiteClient/GrapherConfigGridEditorTypesAndUtils.tsx
site/SiteTools.tsx

This shifts weight from the owid bundle to the vendors bundle (no overall size change).
Not entirely sure whether 
`import { FontAwesomeIcon } from "@fortawesome/react-fontawesome/index"`
is preferable to 
`import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"`
but this makes it consistent across imports.
see [#61f84b7](https://github.com/owid/owid-grapher/pull/1492/commits/61f84b757332cdbef46bb21cad41fa3569d953b8)

fix(import): import fontawesome /index

---

db/migration/1654553380446-AddSourceChecksum.ts

Adds a yet-unused `sourceChecksum` column to `datasets` table. See https://github.com/owid/etl/pull/208 for the logic to actually write this column.

Migration to add sourceChecksum column for datasets

---

adminSiteClient/ChartEditor.ts
adminSiteClient/ChartEditorPage.tsx
adminSiteClient/EditorTextTab.tsx
adminSiteClient/Forms.tsx
clientUtils/Util.ts
grapher/core/Grapher.tsx
grapher/core/GrapherConstants.ts
grapher/core/GrapherInterface.ts

Resolves #1482 
Adds support for the adding Details to our grapher configs.
How it works:
1. fetch all the Details from the DB
2. Watch the `subtitle` and `note` fields for changes, specifically for the inclusion of any text that matches the `hover::category::term` syntax
3. If there's a match, check to see if it corresponds with a Detail defined in the DB
4. Pass all corresponding Details through to Grapher as an object with the shape `Record<string, Record<string, Detail>>`
5. Track the Detail references that _don't_ match, and warn the user
https://user-images.githubusercontent.com/11844404/172952619-a3c59e2e-2fdf-4fc7-9701-2214d72d1b42.mov

Details on demand editor implementation

---

clientUtils/Util.ts
coreTable/CoreColumnDef.ts
grapher/core/LegacyToOwidTable.test.ts
grapher/core/LegacyToOwidTable.ts
grapher/dataTable/DataTable.jsdom.test.tsx
grapher/dataTable/DataTable.sample.ts
grapher/dataTable/DataTable.scss
grapher/dataTable/DataTable.tsx

Fixes #1274 | Live on tufte: [One](https://tufte-owid.netlify.app/grapher/smoking-death-rate-1990-2017?tab=table), [Two](https://tufte-owid.netlify.app/grapher/tests-of-covid-19-per-thousand-people-vs-gdp-per-capita?tab=table)
Data tables didn't show these values because they were assuming the `targetTimes` to be the same for every column, and didn't take into account that the `targetTime` can be overriden for some columns.
There's also a slight visual change in the table tab, which is that the `targetTime` is now displayed as part of the column header.
In some cases it is redundant, but it is crucial in many cases. It's always displayed when the timeline is set to a single year.
---
9b4ca4a0c9c1f5dfe5a66559c00dd537905d90ae is a refactoring of the `columnsWithValues` method, which was …

fix: Display data values in DataTable for columns with xOverrideYear

---

coreTable/CoreTable.ts
coreTable/CoreTableColumns.ts
grapher/barCharts/DiscreteBarChart.tsx
grapher/core/Grapher.tsx
grapher/dataTable/DataTable.tsx
grapher/lineCharts/LineChart.tsx
grapher/scatterCharts/ScatterPlotChart.tsx
grapher/scatterCharts/ScatterTooltip.tsx
grapher/sourcesTab/SourcesTab.tsx
grapher/stackedCharts/StackedAreaChart.tsx
grapher/stackedCharts/StackedBarChart.tsx

[As discussed on Slack](https://owid.slack.com/archives/CQQUA2C2U/p1655316054237859)
Different columns can have different time units, and so it makes sense to move the handling of time all the way to the column level.
There is still a `table.timeColumn`, which can be used to format axis labels, for example.

refactor: move `formatTime` method from table-level to column-level

---

adminSiteServer/apiRouter.ts
db/migration/1654553380446-AddSourceChecksum.ts
db/migration/1656580147849-CreateActiveDatasetsView.ts

Exclude archived datasets from `admin/datasets` and other lists (sources, variables, etc.). Instead of manually adding WHERE conditions we could have a `active_datasets` or `unarchived_datasets` view with the `not isArchived` filter.

enhance(admin): exclude archived datasets

---

explorer/Explorer.tsx
explorer/ExplorerProgram.ts

With the upcoming demography explorer (currently: 140 tables), switching the entity picker sort metric currently stalls the UI thread for >10 seconds.
With these two variables pulled out of the loop and shared between the calls, switching metrics happens in an instant instead.

perf(explorer): call heavy explorer getters only once

---

grapher/axis/Axis.ts
grapher/axis/AxisConfigInterface.ts
grapher/axis/AxisViews.tsx
grapher/mapCharts/MapTooltip.tsx

Fixes #1172.
No longer shows solid line for value=0 when the axis `formatColumn` is a date column.

enhance(axis): do not show solid 0 line for date columns

---

grapher/horizontalColorLegend/HorizontalColorLegends.tsx
grapher/mapCharts/MapChart.tsx

I implemented [automatic legend sizing](https://github.com/owid/owid-grapher/commit/6129ac3c26d8a0c6d716f1acbd0ed678daf1d747) several months ago, but didn't enable it on maps to avoid a large svgTester diff.
By enabling it, denser legends are now wider, and sparse legends narrower. Relatedly, [Max recently suggested legends on maps should be bigger](https://owid.slack.com/archives/C46U9LXRR/p1656510679657209), so this seems like a good time to make the change.

enhance(map): automatic legend width

---

adminSiteClient/ChartList.tsx
adminSiteClient/Forms.tsx
adminSiteClient/TagBadge.tsx
adminSiteClient/admin.scss
adminSiteServer/apiRouter.ts
clientUtils/owidTypes.ts
db/migration/1656406573545-KeyCharts.ts
db/model/Chart.ts

This handles marking topics as "key topics" on a per-chart basis:
- toggle key status and save on click on a tag
- status persisted as long as the tag is present in the list (per chart): deleting a tag will delete the key status
- new `isKey` column added to `chart_tags` table
_Note: tags (in non-edit mode) were previously links to the corresponding tag pages. This could be added back if it turns out to be a regularly used feature._
https://user-images.githubusercontent.com/13406362/176219672-001049a2-feeb-4fe6-bd2d-cd1f3df36c49.mp4
It comes in support of #1447, which requires charts to be marked as "key charts" on any given topic.

API / UI support for selecting key charts in admin

---

adminSiteServer/apiRouter.ts
baker/GrapherBaker.tsx
baker/SiteBaker.tsx
baker/countryProfiles.tsx
baker/postUpdatedHook.ts
baker/siteRenderers.tsx
baker/sitemap.ts
db/model/Dataset.ts
db/model/Post.ts
db/model/Variable.ts
db/syncPostsToGrapher.ts

Removes the last bit of TypeScript namespaces that were remaining in the codebase. In preparation for #1522.

Split grapher data #1: Remove TypeScript namespaces

---

db/migration/1657627850269-TargetYear.ts
grapher/schema/grapher-schema.001.json
grapher/schema/grapher-schema.001.yaml

As discussed [on Slack](https://owid.slack.com/archives/CQQUA2C2U/p1657621825175579).
There appear to be some charts that have `dimension.targetYear` set to 2000 (chart id <= 409) or to `null` (chart id <= 1686).
`targetYear` only makes sense for scatter plots and Marimekko charts, and it being present when it shouldn't be can throw up some DataTable code. Same goes for when it's `null` when it shouldn't be.

chore(db): add migration to remove bogus targetYear fields

---

grapher/text/MarkdownTextWrap.test.ts
grapher/text/MarkdownTextWrap.tsx

Fixes an issue in a PR: https://github.com/owid/owid-grapher/pull/1535#issuecomment-1176034159
> - There is a bug with newline nodes, they don't get lifted up to the top (they are supposed to). I can implement a fix for this, shouldn't take long – we just need to recursively call the splitting method.

fix(MarkdownTextWrap): always split text on newline

---

adminSiteServer/apiRouter.ts

[Reported on Slack](https://owid.slack.com/archives/C46U9LXRR/p1657710086586729).
This is the quickest fix: uncommenting the endpoint. 
Not sure if we want to maybe use `getVariableData()`, there are some differences between that and the query here: https://github.com/owid/owid-grapher/blob/38fdb485c18fe4de992d7f8fc560d4b6e6ca82aa/adminSiteServer/apiRouter.ts#L1594-L1604

fix(admin): bring back VariableEditPage endpoint

---

grapher/axis/Axis.ts
grapher/captionedChart/CaptionedChart.tsx
grapher/horizontalColorLegend/HorizontalColorLegends.tsx
grapher/lineLegend/LineLegend.tsx
grapher/scatterCharts/ConnectedScatterLegend.tsx
grapher/scatterCharts/ScatterSizeLegend.tsx
grapher/scatterCharts/ScatterTooltip.tsx
grapher/slopeCharts/SlopeChart.tsx
grapher/text/TextWrap.stories.tsx
grapher/text/TextWrap.test.ts
grapher/text/TextWrap.tsx
grapher/verticalColorLegend/VerticalColorLegend.tsx

In Details on Demand (#1552) we noticed that the height `TextWrap` returns is not correct – `lineHeight` is not multiplied by the `fontSize`.

fix(TextWrap): match SVG and HTML rendering

---

clientUtils/Util.ts
grapher/captionedChart/CaptionedChart.tsx
grapher/core/Grapher.tsx
grapher/detailsOnDemand/detailsOnDemand.scss
grapher/detailsOnDemand/detailsOnDemand.tsx
grapher/downloadTab/DownloadTab.tsx
grapher/footer/Footer.tsx
grapher/footer/FooterManager.ts
grapher/header/Header.tsx
grapher/header/HeaderManager.ts
grapher/text/MarkdownTextWrap.scss
grapher/text/MarkdownTextWrap.stories.tsx
grapher/text/MarkdownTextWrap.test.ts
grapher/text/MarkdownTextWrap.tsx
grapher/text/parser.ts

Implements Marwa's design feedback for static exports.
Business logic outline:
1. Scan through the subtitle and note text, find all DoD references and create a unique ordered list (because in the case where the same DoD is referenced twice, we don't want to increment the citation number)
2. Traverse the Markdown AST and whenever we find a DoD, append a IRSuperscript token into its children that uses the corresponding index from the unique ordered list
Rendering superscript in SVG has some quirks but it seems to work fairly well.
TODO:

DoD export style touchups

---

baker/GrapherImageBaker.tsx

I ran the local baker with configs that included DoDs before and after these changes: it's fixed!

Disable DoD footnotes on bake

---

db/migration/1659011791860-AddShortNameToVariables.ts
db/migration/1659011799966-AddShortNameAndVersionToDatasets.ts

We need `shortName` and `version` for better alignment of ETL and grapher metadata. See [accompanying PR](https://github.com/owid/etl/pull/359)

migration(variables,datasets): add shortName and version to variables and datasets tables

---

.github/workflows/sync-grapher-schema-to-digital-ocean.yml

See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-only-when-a-push-affects-specific-files

chore(actions): only run schema action when schema changes

---

site/LongFormPage.tsx
site/PostCard/PostCard.tsx

Fixes #1561 | [Live on tufte](https://tufte-owid.netlify.app/) | See [Facebook Sharing Debugger](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Ftufte-owid.netlify.app%2Fworld-population-update-2022)
Before this fix, we had thumbnail URLs like `https://ourworldindata.org/app/uploads/2022/07/Population-2022-768x402.png` under the `og:image` meta tag. Notice the `/app` in there.
In addition, there is a 301 redirect going from `/app/uploads/` to `/uploads/`:
https://github.com/owid/owid-grapher/blob/d9b38d588566ab0bdfc93feeba42dc3e2db13df2/baker/redirects.ts#L23-L26
It seems that Facebook didn't like this redirect, and threw up for that reason. With this fix in place, we're rewriting these URLs in the baking step already, and are thus not hitting the redirect any longer.
The …

fix: rewrite thumbnail URL from `/app/uploads` to `/uploads`

---

baker/formatWordpressPost.tsx
clientUtils/owidTypes.ts
devTools/docker/create-wordpress-admin-user.sh
site/LongFormPage.tsx
site/TableOfContents.tsx
site/blocks/StickyNav.tsx
site/blocks/index.ts
site/css/colors.scss
site/css/page.scss
wordpress/web/app/plugins/owid/owid.php
wordpress/web/app/plugins/owid/src/StickyNav/StickyNav.js
wordpress/web/app/plugins/owid/src/StickyNav/block.json
wordpress/web/app/plugins/owid/src/StickyNav/sticky-nav.php
wordpress/web/app/plugins/owid/src/blocks.js

[Staging demo](https://ptolemy.owid.cloud/admin/posts/preview/50414)
The first component for our new topic page front matter module.
We can't dynamically generate the nav because the names of the headings in the sticky nav are different from the header titles in the actual page. 
e.g. the sticky nav may say "Data Explorers" but the heading is "Explore our data on Poverty"
Ergo we need to manually specify the text content and the HTML IDs, and the custom link interface seemed as good a way to do this as any (per Matthieu's advice to not over-engineer these modules while the designs are still likely to change)
https://user-images.githubusercontent.com/11844404/182184587-212fad5c-39ab-4e32-916a-c30b84532d62.mov
TODO:

Sticky Nav

---

grapher/core/LegacyToOwidTable.test.ts
grapher/core/LegacyToOwidTable.ts

The new multi-table join algorithm has an ultimate fallback for day/year joins where it just tries to match by entity. This is what our old algorithm did always in these cases (unless specifically overridden but that only works in some cases). The issue in those cases is that trying to find any match for a given entity in a variable like Population is of course highly ambiguous - there are many years for any given entity. Our old and also the new version then defaulted to choosing the first row that matches. This has the downside of often being the first year that we have data for for a given entity which is often pretty weird (think of covid daily data for example where we try to merge in population for the size and we have daily data until yesterday but population only exists until two …

Multi-table-join: prefer matching the last row on ambiguous matches

---

.vscode/launch.json
clientUtils/Util.ts
grapher/core/LegacyToOwidTable.test.ts
grapher/core/LegacyToOwidTable.ts

This should allevieate performance issues with many variables as recently reported. In one test the time to do the full join went down from 4 seconds to 600 ms and the memory use from 250MB to 85MB
Slack discussion: https://owid.slack.com/archives/CQQUA2C2U/p1659005364871929
> The original motivation was performance improvements. Those were quite straightforward but then I kept running into breaking charts with the svg tester that led me to add several iterations of fixes (felt so close every time ). The end result is several improvements over the status quo and one open question:
> 
> **Benefits**
> 
> -   Performance - the chart initialization time for some heavy multi-variable charts improved from ~4000 ms join cpu time to ~600ms and a memory footprint reduction by about half. (e.g. …

Perf: adds a new implementation for full joining multiple tables

---

grapher/text/MarkdownTextWrap.scss
grapher/text/MarkdownTextWrap.tsx
site/LongFormPage.tsx
site/SiteFooter.tsx
site/webpackUtils.tsx

I'll go through these one by one:
* `ResizeObserver` is [well-supported](https://caniuse.com/resizeobserver), but we're still getting [some Bugsnag errors](https://app.bugsnag.com/our-world-in-data/our-world-in-data-website/errors/62f156e75adfd5000841ad32) from browsers not supporting it, especially iOS 12.
Our rough policy for supporting old browsers is "only fix it if it's very very easy to do", and in this case it thankfully is by adding `ResizeObserver` to what we request from polyfill.io.
* [Google Translate is doing some very weird shit that is not always React-compatible](https://github.com/facebook/react/issues/11538). We had issues with that before already. I noticed some of that is going on with MarkdownTextWrap, too, which [surfaced via …

fix: several small issues with MarkdownTextWrap and Sticky Nav

---

adminSiteClient/ChartList.tsx
adminSiteClient/Forms.tsx
adminSiteClient/TagBadge.tsx
adminSiteClient/admin.scss

Key chart tagging should only be available on the charts list. Some of the key chart tagging has leaked onto the posts list. This fixes it.
_The problem: key chart tagging leaking onto the posts list_

fix(key chart): leaking styles on post list

---

devTools/docker/wait-for-mysql.sh

Fixes #1591
The `wait-for-mysql.sh` script appears to be missing grapher variables from `.env`, so we source `.env` first.

fix: get the admin pane working on first load

---

.vscode/tasks.json
devTools/docker/create-and-fill-wordpress-db.sh
devTools/docker/create-wordpress-admin-user.sh
devTools/docker/download-grapher-chartdata-mysql.sh
devTools/docker/download-grapher-metadata-mysql.sh
devTools/docker/download-grapher-mysql.sh
devTools/docker/refresh-grapher-data.sh
devTools/docker/refresh-wordpress-data.sh

Resolves #1381.
This adds local refresh tasks for wordpress (db & uploads) and grapher (db).
The refresh tasks can be run through VSCode: 
- cmd + shift + p  >  "Tasks: Run Task"
- "refresh grapher" or "refresh wordpress".
In their default mode, the tasks download all assets (db dumps and wordpress uploads) and refresh all tables.
Check the comments in .vscode/tasks.json for additional usage scenarios.

Refresh local env with VSCode tasks

---

site/gdocs/article-block.tsx
site/gdocs/article-blocks.tsx
site/gdocs/fixed-graphic.tsx
site/gdocs/owid-article.tsx

This brings support for rich text (bold, italics, etc...) as well as the full range of custom `ArticleElement`s to the summary block.

feat(gdocs): add support for rich text in summary

---

baker/GrapherBaker.tsx

Our usual logic for using and releasing DB resources is to share a db connection within a process and to release them when the process is about to shut down. This works well for many cases but with the new workerpool implementation in baking we now have several workerthreads that get spawned which create their own connections but then the usual automatic cleanup fails.
The workerpool library complicates this picture and it is unclear what the best way for managing resources is there ATM. They have a onTerminateWorker callback but unhelpfully this is called on the main thread, not inside the worker thread.
This PR now does only the minimal thing which is to explicitly terminate the worker pool. In some preliminary tests this already released connections although TBH this is a bit …

fix: shut down workerpools

---

site/Breadcrumb/Breadcrumb.scss
site/blocks/expandable-paragraph.scss
site/blocks/front-matter.scss
site/css/colors.scss
site/css/content.scss
site/css/header.scss
site/css/mixins.scss
site/css/page.scss
site/owid.scss

[Staging demo](https://ptolemy-owid.netlify.app/world-population-growth)
Based on the [new link designs in figma](https://www.figma.com/file/cZrEfEgWkpAQTeLLQyukDw/%5BDesktop%5D-Library-1.0?node-id=162%3A357).
I updated the mixin and then manually searched for all `a` tag CSS that used that mixin or a blue similar to blue-90.

Update link colours

---

grapher/core/Grapher.tsx

In order to check whether entities changed between the original view and the current view, we were only using `legacyConfig.selectedData`, and we didn't dedupe it.
This lead to most charts appending a `?country=...` on load automatically.
An example chart is this one here: https://ourworldindata.org/grapher/age-standardized-death-rate-by-cause
---
It's not like the current behaviour was super bad, but it caused a lot of unnecessary `?country=` in https://github.com/owid/owid-grapher-svgs, which are being stripped out by an upcoming fix for #1388.
To get more clean SVG diffs, I'm merging this very easy fix beforehand.
This also means that this PR will lead to SVG diffs, but they are all of the quality:
```diff
- <a href="http://localhost:3030/grapher/sub-energy-fossil-renewables-nuclear?cou …
```

fix: use `selectedEntityIds` for original entity ids

---

grapher/mapCharts/MapChart.tsx
grapher/mapCharts/MapChartConstants.ts

The issue came up in the maps-with-annotations project. There we need to have a computed property that depended on chorplethData. All pieces of information were passed in directly as props, not through the manager pattern we normally use. The issue is that some parts of the prop were updated whenever the users hovered and this led to a recreation of the props and thus a regeneration of the (potentially expensive) computed properties in ChorplethMap.
This switch makes it possible to update choroplethData much less often by using the manager pattern we use in most other places.

ChoroplethMap: switch to manager pattern to avoid refresh issues

---

adminSiteClient/EditorBasicTab.tsx

Fixes #1354.
I stumbled upon this when working on related code, and it turns out the fix for #1354 is super super easy.
We might still want to get rid of auto-selection altogether, or at least rework how it works, but for now it at least won't screw up every StackedArea ever again.
I think this bug also lead to a considerable amount of buggy charts that we published and then noticed that something's wrong, so here's hoping that's no more.

fix(admin): don't auto-select multiple entities in multi-variable charts

---

grapher/core/grapher.scss

Changes to link styling mistakenly affected the tabs on graphers in articles. This overrides those changes.

Remove underline from Grapher tabs in .article-content

---

devTools/tsconfigs/tsconfig.base.json

Changing the build target means that some newer ES features no longer need to be transpiled.
This includes especially:
* async/await ([es2017](https://flaviocopes.com/es2017/))
* Rest/Spread syntax ([es2018](https://flaviocopes.com/es2018/))
* No new syntax-level features really from [es2019](https://flaviocopes.com/es2019/), but some nice standard library additions at least
Switching to a newer build target reduces the asset size, and can potentially also improve performance by a bit since we're now using the native implementation of these features.
---
I didn't go with es2020 just yet because its syntax features (nullish coalescing and optional chaining) [did "only" get support in iOS Safari 13.4](https://caniuse.com/mdn-javascript_operators_optional_chaining,mdn-javascript_operators_nul …

chore: change TS build target to es2019

---

adminSiteClient/DimensionCard.tsx
adminSiteClient/EditorBasicTab.tsx

Changing the color of a dimension no longer works ([reported on Slack](https://owid.slack.com/archives/C46U9LXRR/p1661944664407249)), likely we broke it in https://github.com/owid/owid-grapher/pull/1623.
> I am trying to change the colors in [this chart](https://owid.cloud/admin/charts/5906/edit) but am unable to do so. I neither can change the hex codes nor select a color from the palette.
This fix works, but I don't understand why.

fix(admin): make dimension color picker work

---

baker/sitemap.ts
explorer/Explorer.tsx
explorer/ExplorerGrammar.ts
explorer/ExplorerProgram.ts
site/ExplorerPage.tsx
site/Head.tsx

Resolves #1214 | Live on tufte: [Affected explorer](https://tufte-owid.netlify.app/explorers/natural-resources), [Unaffected explorer](https://tufte-owid.netlify.app/explorers/global-food), [Sitemap](https://tufte-owid.netlify.app/sitemap.xml)
Implements the `indexViewsSeparately` explorer keyword, as outlined in https://github.com/owid/owid-grapher/issues/1214#issuecomment-1242311179.
When enabled, it includes the URLs of all views in the sitemap, and uses the fully-specified view URL as a canonical URL.
As outlined in #1214, the plan is to enable this option on the `natural-resources` and `water-and-sanitation` explorers for now.

feat(explorer): ability to index explorers in Google Search

---

db/migration/1662646791543-VariableViews.ts
db/model/Variable.ts

Add columns `catalogPath` that points to the table in the catalog (aka variable view) and `dimensions` which contain information about dimensions in JSON format that we need to locate that variable in the table.
@danyx23 I hope there wouldn't be any side effects. There weren't any the last time we added column to `variables`.

migration(variables): add catalogPath and dimensions columns to variables

---

clientUtils/Util.ts
grapher/chart/ChartManager.ts
grapher/core/Grapher.tsx
grapher/scatterCharts/ScatterPlotChart.tsx

Old pre-next behaviour. Since we haven't restored it, I think we should get rid of it.

chore: remove unused `useTimelineDomains`

---

db/migration/1663061841304-ProperDatasetShortNames.ts

Migration needed for https://github.com/owid/etl/pull/464. Upserting datasets would raise an error without this migration because of constraint on `name`, so it's quite safe.

migrate(shortName): remove insitution and version from dataset short names

---

explorer/Explorer.tsx

Live on halley: [Affected explorer](https://halley-owid.netlify.app/explorers/natural-resources), [Unaffected explorer](https://halley-owid.netlify.app/explorers/global-food)
We have an open experiment where we can opt in explorers to be expanded in our sitemap (#1214). The purpose of this expansion is to allow people to arrive, through Google Search, at specific views of our data represented by specific explorer configurations.
A current problem is that our page titles are all too similar for explorer views, so Google omits them from search as being not helpful to the user.
This change modifies the page title each time the explorer view changes from the default setting, for opted-in explorers. The page title chosen is the grapher display title suffixed with "- Our World In Data".

enhance(explorer): improve dynamic page titles exposed to Google

---

grapher/color/CustomSchemes.ts
grapher/stackedCharts/StackedAreaChart.test.ts

This makes the old stackedAreaDefault color scheme synomymous with owid-distinct as per the new style guide.
Once we do the data migrations we can get rid of the stackedAreaDefault in favour of owid-distinct everywhere

enhance: switch existing stacked area default chart

---

baker/formatWordpressPost.tsx
site/blocks/additional-information.scss

#1657 and #1659 regressed Additional Information blocks.
**Before:**
https://user-images.githubusercontent.com/11844404/191357057-5b17467d-854f-4295-8400-0e8be1432ed2.mov
**After:**
https://user-images.githubusercontent.com/11844404/191357224-21070377-8eed-4312-baba-29e69dc4704d.mov

Additional Information CSS and hydration fixes

---

site/ChartsIndexPage.tsx
site/runChartsIndexPage.ts

Fixes #1680 
I noticed another bug where the sidebar isn't highlighting the correct heading that corresponds with the user's position on the page, but that's another issue.

Remove /charts searchbar autofocus and prevent URL hash from disappearing

---

grapher/controls/globalEntitySelector/GlobalEntitySelector.scss
site/TableOfContents.tsx
site/css/footer.scss
site/css/page.scss
site/css/sidebar.scss
site/css/variables.scss
site/owid.scss

A couple of ToC glitches that I wanted to fix.
[Staging demo](https://ptolemy.owid.cloud/admin/posts/preview/32527)
I have tested the changes on several COVID pages and articles (with and without y-overflow in the sidebar), and the All Charts page.
- Background is now `blue-10` all the time
- Remove the sticky tracking logic
- Fix `.section-heading` positioning on widescreens
- Fix top and bottom margin between the header and footer
https://user-images.githubusercontent.com/11844404/191842712-4cc13db3-3ae3-482d-8bc1-da17ac33bbc5.mov
https://user-images.githubusercontent.com/11844404/191842931-936ab76e-c19b-4d06-9880-e2cef549d525.mov

Table of Contents improvements

---

adminSiteClient/EditorBasicTab.tsx

The variable id for the population variable to be used by default when creating scatter plots is hardcoded. It used to be variable id 72 for a long time but recently we created a new updated population variable via the ETL and deleted variable 72. This commit updates to the new id.

fix: switch to new hardcoded population variable

---

Makefile
devTools/docker/refresh-grapher-data.sh

For some development workflows, it's not important to have the data values from grapher, only up-to-date metadata.
This PR adds `make refresh.meta` which does this, downloading and fetching only the grapher metadata.

chore: add "make refresh.meta" to only refresh grapher metadata

---

grapher/core/Grapher.tsx

Fixes an issue I spotted in the `food-footprints` explorer:
We have two different ways of specifying dimensions, one for `grapherId`-based explorer views and one for proper spreadsheet-powered explorer views.
For explorers using both of these, we fail to reset the `grapher.dimensions` when switching away from the `grapherId` chart, which can lead to edge-case behaviour.
In particular, when [navigating to this view](https://ourworldindata.org/explorers/food-footprints?uniformYAxis=0&country=Beef+%28beef+herd%29~Lamb+%26+Mutton~Beef+%28dairy+herd%29~Prawns+%28farmed%29~Cheese~Pig+Meat~Poultry+Meat~Eggs~Rice~Tofu+%28soybeans%29~Milk~Tomatoes~Maize~Wheat+%26+Rye~Peas~Bananas~Potatoes~Nuts~Almonds~Avocados~Beefburger~Cow%27s+milk~Dairy-free+ice+cream~Lentils~Vegan+pizza~Almond+milk~Bread~Meat+p …

fix: properly reset dimensions on explorer change

---

jest.config.js

This can currently break deploys if env variable CATALOG_PATH is set to something else (like in production).

fix(tests): fix failing parquet sets when env is set

---

db/model/Variable.ts

Setting `CATALOG_PATH=''` disables fetching parquet from catalog and fall backs to `data_values` table.

fix(Variable): use parquet if CATALOG_PATH is not empty

---

db/model/Variable.ts

We're still getting segfaults in production even though we're not using duckdb at all. It doesn't play nicely with `workerpool` from deploys and can result in non-deterministic segfaults.
I've been testing moving `require` inline (which never gets called) and it has been working on staging. It's non-deterministic though, so one can never be sure :(. If we still get errors after this we should just remove duckdb altogether.

fix(duckdb): move require(duckdb) from top to inline to prevent segfaults

---

site/blocks/AdditionalInformation.tsx
site/blocks/additional-information.scss
site/css/content.scss

Fixes some minor CSS scoping glitches with the Additional Information block
I tested how this would impact other h3's if they were in the additional information block and found that any child h3 gets lifted up to the "main heading" of the block, so presumably multiple h3's is a case we don't have to worry about.
The `&.grapherPreview img` change addresses the `img` rule which was also affecting all `img`'s within a Grapher inside `article-content`. I suspect it was written to only apply to the preview `img` before the embed is hydrated, so I made the rule only apply when `grapherPreview` is active.

additional-information h3 CSS fix

---

db/migration/1667317480367-FillMissingPublishedByBySourceName.ts
db/readme.md

If source doesn't have `dataPublishedBy` attribute, use its `source.name`. This migration cannot be rolled back, here's at least a list of 164 sources that will be updated.
```
"id","description->'$.dataPublishedBy'","name"
44,"null","Our World In Data"
189,"","Multiple sources compiled by Our World in Data (2019)"
302,"null","OECD: Education at a Glance 2012"
582,"null","Hypothetical global emissions - CDIAC (2014)"
588,"null","Renewable Investment as % of GDP - BNEP and World Bank"
669,"null","Number of people with and without access to improved water sources - World Bank and UN"
2218,"null","Cereal Yield Index - World Bank (2017) & OWID"
2219,"null","Land under cereal production index - World Bank (2017)"
2221,"null","Daily protein supply - FAO (2017)"
2804,"null","Dietary …
```

migration(sources): fill missing dataPublishedBy with source name

---

baker/siteRenderers.tsx
packages/@ourworldindata/grapher/src/core/GrapherInterface.ts
site/multiembedder/MultiEmbedder.tsx

Two things broke when we stopped baking the site URLs into Grapher's code directly:
- Explorers weren't injecting the URLs correctly into their Graphers
- These values weren't being exported by Graphers' `toObject` method
This fixes that.
[Staging preview](https://ptolemy-owid.netlify.app/explorers/co2)

Fix missing URLs in Explorer grapher configs

---

packages/@ourworldindata/grapher/src/lineCharts/LineChart.tsx

This fixes #1724 and re-introduces darkening of colors specifically for line charts that get their color from the values (as opposed to a single color for the variable/entity)

fix: line charts with colors from value could be too bright 

---

devTools/droplet/live.crontab

This is to address a problem on `live` where after upgrade to 20.04 calls to `node` no longer worked from `cron`.

fix: use -l in cron so that nvm env variables are there

---

packages/@ourworldindata/grapher/src/controls/EntitySelectorModal.scss
packages/@ourworldindata/grapher/src/controls/ShareMenu.scss
packages/@ourworldindata/grapher/src/core/grapher.scss
packages/@ourworldindata/grapher/src/sourcesTab/SourcesTab.scss
packages/@ourworldindata/grapher/src/text/MarkdownTextWrap.scss
site/gdocs/centered-article.scss

The Lerna branch changed the order in which some SCSS files had to be imported. 
This meant that in a few places, low-specificity Grapher rules were being trumped by the low-specificity site-wide rules because they were declared later.
e.g.
```css
// before
.article h2 {
margin-bottom: 32px
}
.grapher-header h2 {
margin-bottom:  0;
}
```
```css
// after
.grapher-header h2 {
margin-bottom:  0;
}
.article h2 {
margin-bottom: 32px
}
```
This PR nests all Grapher CSS in a top-level `.GrapherComponent` selector, which increases all rules' specificity to at least `0-2-1`, which seems to be sufficient to trump generic site rules. 
It also prevents any Grapher CSS rules from leaking out to the rest of the site.
[Staging preview](https://ptolemy-owid.netlify.app/grapher/global-pasture?country=~OWID …

Scope Grapher CSS

---

.vscode/launch.json
.vscode/tasks.json
devTools/droplet/refresh-staging-db.sh

This allows for development to happen remotely on staging, using VSCode remote extensions.
The initial staging server setup is slightly different (different UNIX user, doesn't add a pm2 app for the admin). 
The refresh script has also been slightly altered to cater for this different UNIX user and avoid permission issues on downloaded DB dumps in /tmp.

Remote dev

---

adminSiteClient/GdocsPreviewPage.tsx
package.json
site/gdocs/ArticleBlock.tsx
site/gdocs/BlockErrorBoundary.tsx
site/gdocs/DebugContext.tsx
yarn.lock

https://user-images.githubusercontent.com/13406362/198077498-8e247297-f146-4264-bee6-8b845d1d0528.mp4
Features:
- captures errors in individual components (only `<Chart>` for this PoC) so finding the misbehaving component is easier
- allows retries when source updated
Not done:
Supersedes #1726 (discussed with @danyx23)

Prevent WSOD in gdocs preview

---

Makefile
baker/Deployer.ts

This change aims to avoid accidental carry-over state from Lerna if you switched branch before deploy, by doing `yarn nx reset` before deploy or stage.
It also enhances the `make stage` command. Previously, you could only target the `staging` server, but now you can run `STAGING=myserver make stage` to target a different one.

chore: improve "make deploy" and "make stage" with nx reset

---

db/gdocToArchieml.ts
site/gdocs/ArticleBlock.tsx
site/gdocs/Footnotes.tsx
site/gdocs/List.tsx
site/gdocs/centered-article.scss

Fixes:
- Inline footnotes
- Bold in lists
- `.fixedSectionGraphic` height
[Staging preview](https://ptolemy.owid.cloud/admin/gdocs/1clAEly4t6MihroNdKxPFbYO5xhbO_UZFJhGmOf0xjsw/preview)

Google doc formatting fixes

---

db/gdocToArchieml.ts
packages/@ourworldindata/utils/src/owidTypes.ts
site/css/content.scss
site/gdocs/ArticleBlock.tsx
site/gdocs/ArticleBlocks.tsx
site/gdocs/OwidArticle.tsx
site/gdocs/SDGTableOfContents.scss
site/gdocs/SDGTableOfContents.tsx
site/gdocs/centered-article.scss
site/owid.scss

https://user-images.githubusercontent.com/13406362/198972317-3cd5589a-93c1-43d4-af88-f9559bb71f37.mp4
- dynamic generation based on document headings
- support supertitles by adding a line return (shift + enter) in the heading
- open / close animation
- ⚠️ responsive work pending grid refactor
- [demo gdoc](https://docs.google.com/document/d/1iLmMolntBXj1lhsApKI8FuLW7795DGB6t5e_iwdeeyk/edit)
closes #1733

1733-sdg-table-of-contents-index

---

packages/@ourworldindata/grapher/src/core/Grapher.tsx

Source name that gets displayed in the footer was automatically shortened from `World Bank*` to `World Bank`. Figuring that this is happening gave us a lot of headache. This shouldn't be implicit, but should be either given as an explicit footer or long source name should be moved to source description.
I've already manually updated footer of all affected charts (~60 charts).

refactor(grapher): remove automatic source name shortening

---

db/gdocToArchieml.ts
packages/@ourworldindata/utils/src/index.ts
packages/@ourworldindata/utils/src/owidTypes.ts
site/css/variables.scss
site/gdocs/ArticleBlock.tsx
site/gdocs/ArticleBlocks.tsx
site/gdocs/OwidArticle.tsx
site/gdocs/SDGTableOfContents.tsx
site/gdocs/centered-article.scss

closes #1761 
Relies on #1733's vertical tab character for separating the heading from its supertitle, without creating ArchieML overhead for authors.
Test document: https://docs.google.com/document/d/1iLmMolntBXj1lhsApKI8FuLW7795DGB6t5e_iwdeeyk/edit
Known issues:
- the first heading below the table of contents shouldn't show a separation line. This will be possible when #1729 is merged and removes wrapping `<div>s` and allowing for the use of `:first-of-type` selectors.
- the separation line above headings is only as wide as the content column for now. Will re-evaluate feasibility once #1729 is merged.

1761-sdg-heading-supertitle

---

adminSiteClient/gdocsDeploy.ts
packages/@ourworldindata/utils/src/owidTypes.ts
site/gdocs/OwidArticle.tsx
site/gdocs/centered-article.scss

closes #1760 
Similar to #1758's `cover-color`, the `supertitle` frontmatter property is not surfaced in the preview settings pane until it is elevated to the rank of a more generic feature used beyond SDG pages.

feat(gdocs): add support for page supertitle

---

site/css/grid.scss
site/gdocs/ArticleBlock.tsx
site/gdocs/SDGGrid.scss
site/gdocs/SDGGrid.tsx
site/gdocs/centered-article.scss

Test doc: https://docs.google.com/document/d/1UOhC3dU2Zc1DEt2Yzqblfc3l9K1ZS27fcNHQa7uwnxI/edit#heading=h.o4zdv2a800b3
- Now uses a `grey-section`.
- Moves the "The 17 goals" heading outside of the component, and into the authorable document.
closes #1782

feat(sdg grid): add responsive

---

baker/siteRenderers.tsx
packages/@ourworldindata/grapher/src/controls/VerticalScrollContainer.tsx
packages/@ourworldindata/grapher/src/controls/globalEntitySelector/GlobalEntitySelector.scss
packages/@ourworldindata/grapher/src/core/grapher.scss
packages/@ourworldindata/grapher/src/detailsOnDemand/detailsOnDemand.scss
site/blocks/KeyInsights.scss
site/blocks/research-and-writing.scss
site/css/sidebar.scss
site/css/variables.scss

Resolves https://github.com/owid/owid-grapher/issues/1765
And a couple of small fixes caught by Marwa and Daniel today.
https://user-images.githubusercontent.com/11844404/204660872-19604104-9b92-4ab7-bc90-ca8c829e800d.mov
https://user-images.githubusercontent.com/11844404/204864858-087d91de-4d6d-4c2c-a8fc-acd24dd8d20c.mov

CSS fixes for topic pages and details on demand

---

site/gdocs/OwidArticle.tsx
site/gdocs/centered-article.scss

closes #1784 
- fix style regression on citation and licence footer blocks
- remove separation on first header when directly following the table of contents

1784-fix-citation-and-licence-footer-blocks

---

site/gdocs/ArticleBlock.tsx
site/gdocs/centered-article.scss

closes #1796 
Also addresses some style regressions on the h3
Before (with regression)
After

1796-sdg-can-we-remove-the-line-in-the-text-blocks

---

site/FrontPage.tsx

Based on a discussion with Max, these updates align with our policy to use the terminology of "articles" and "topic pages" instead of "posts" and "entries". 
Note that I don't use "topic pages" explicitly here, but favor using clear language that is still in line with those terms. 
I've also changed the phrasing of "all our X" to "all of our X" because the "of" is needed for the phrase to be grammatical (because ['our' is a pronoun](https://proofed.com/writing-tips/word-choice-all-of/#:~:text=When%20deciding%20whether%20to%20write,that%20begins%20with%20a%20determiner.), weird rule.)

copyedits on homepage

---

site/blocks/GalleryArrow.scss
site/blocks/related-charts.scss

closes #1794 (iOS)
Also fixes issues on Android

fix: all charts navigation mobile

---

packages/@ourworldindata/core-table/src/CoreTableUtils.ts
packages/@ourworldindata/grapher/src/core/Grapher.tsx
site/multiembedder/MultiEmbedder.tsx

> [mobx.array] Attempt to read an array index (0) that is out of bounds (0). Please check length first. Out of bound indices will not be tracked by MobX
This might not fix every case we see this warning, but it definitely makes it less common for now.
The `relatedQuestion` one we saw on every chart that didn't feature a related question, for example.

fix: get rid of mobx "out of bounds" warning

---

.github/workflows/svg-compare.yml
devTools/svgTester/utils.ts
devTools/svgTester/verify-graphs.ts

Up until now, the svgTester was not failing (on master, at least) when there were errors occurring!
When not on master, it was also hard to notice these errors because they were only part of the log, not of the diff.
This now makes it such that:
- Errors are very apparent as the exit reason (even on master)
- When not on master, erroneous svg files will be deleted, such that they are visible in the GH diff

chore(ci): svgTester better communicates errors

---

db/wpdb.ts

Fixes #1811
Avoid a `DataSource is not set for this entity` error when querying the typeorm model for Google Docs by connecting before calling the method.

fix: ensure connection is ready before `getListedGdocs()`

---

packages/@ourworldindata/grapher/src/barCharts/DiscreteBarChart.tsx
packages/@ourworldindata/grapher/src/stackedCharts/MarimekkoChart.tsx
packages/@ourworldindata/grapher/src/stackedCharts/StackedDiscreteBarChart.tsx

Since the information _which_ columns lack data is rarely of use to the end user.
[As requested](https://owid.slack.com/archives/C46U9LXRR/p1670861719945009?thread_ts=1670861612.951139&cid=C46U9LXRR) by @JoeHasell

enhance: unify "No matching data" message between chart types

---

packages/@ourworldindata/grapher/src/core/Grapher.tsx

This change in resize logic did not play safely with the way explorers use graphers.
The explorer render path doesn't leverage `renderGrapherIntoContainer` , but `componentDidMount` still calls and something about the config was not persisting correctly causing the view to break when changing tabs.
This reverts the change.

Fix explorer crash on iOS

---

package.json
yarn.lock

`nx@15.3.3` has in issue which prevents us from executing the binary via yarn (although npx still works)
Till this is fixed we can lock the version to `15.3.0`

Pin nx to 15.3.0

---

packages/@ourworldindata/grapher/src/controls/ShareMenu.tsx
packages/@ourworldindata/utils/src/Util.ts
site/blocks/CodeSnippet.tsx

Demo available at https://zo6kbr.csb.app/, and currently live on _tufte_.
On live, in pretty much every iframe we were offering the option to `Copy link`, and were suggesting that copying worked fine, when in reality it was just failing. Now we check beforehand whether copying works.
---
Context: [a message from Jason a while back](https://owid.slack.com/archives/C46U9LXRR/p1662167698237319?thread_ts=1662072770.585419&cid=C46U9LXRR)

fix: check for clipboard permission before showing copy option

---

packages/@ourworldindata/grapher/src/core/Grapher.tsx

Resolves #1806
... if it's used as a size or marimekko x variable.
had to update the variable id to use.
[Slack context](https://owid.slack.com/archives/C46U9LXRR/p1670855145129159).

fix: exclude population variable from sources footer

---

site/FrontPage.tsx
site/SiteHeader.tsx
site/SiteHeaderMenus.tsx

Removing the most prominent link until we've launched the new SDG tracker. I've commented this out rather than remove it since we may add it back with the launch of the new page.

Remove link to SDG tracker

---

db/gdocToArchieml.ts

This solution supersedes the approach in #1824. After a discussion today we decided that simplicity trumps possible correctness at the extreme - i.e. that using regexp to solve the immediate problem in two lines is better than adding a lot of recursive tree walking logic to the same ultimate effect.

feat: fix the leading whitespace underlined issue in links in gdoc posts

---

adminSiteClient/AdminSidebar.tsx
settings/clientSettings.ts

Add a tab that redirects to fast-track running on our analytics server. To access it, users will need to **install Tailscale and login with Github**.  Lars said it's [reasonable ask](https://github.com/owid/engineering/issues/34#issuecomment-1323363904) to want this from authors (I guess we'll want to use it for other things in the future too). We could also set up nginx proxy from owid-analytics, but that sounds painful and I don't want to overcomplicate it (given that future of fast-track is unclear). On the other hand, isn't asking for Tailscale too much?
If we go with Tailscale, it's gonna be confusing for authors without Tailscale to land on a page that doesn't work... Not sure how to communicate that in the admin though.
(Fast-track is currently running only for staging at …

feature(admin): add tab with redirect to fast-track app

---

baker/algolia/indexChartsToAlgolia.ts

I almost can't believe it, but the calculation of `numRelatedArticles` in our Algolia `charts` index has been broken for almost one year, ever since #1070.
`numRelatedArticles` is our main means of ranking for the charts index.
#1070 changed `getRelatedArticles` from accepting a slug to an id, but since in this case `c` is untyped that did go unnoticed all this time.

fix(algolia): correctly compute number of related articles again

---

db/dataSource.ts

This is a pretty large footgun honestly, but with the addition of `db/model/Gdoc/htmlToEnriched.test.ts` in #1853, TypeORM tries to load that file and fails.
You'll see that failure when running `yarn startAdminServer`.
I'll merge this right away to un-break master, but we can discuss more if needed.
cc @danyx23 @mlbrgl

fix: exclude test files from TypeORM's source files

---

packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.tsx
packages/@ourworldindata/grapher/src/controls/Controls.tsx
packages/@ourworldindata/grapher/src/core/Grapher.tsx

This is an _optional_ follow-up PR after #1788.
It shows the faceting strategy dropdown in the following _new_ case:
* The current chart is auto-faceted, meaning that it cannot be shown unfaceted, _and_
* both faceting strategies are applicable: by metric and by entity.
E.g. in the below setting:
- [Discrete bar chart, auto-faceted because it uses both multiple dimensions and multiple entities](https://tufte-owid.netlify.app/grapher/daily-new-estimated-infections-of-covid-19?time=2021-01-10&country=DEU~FRA) --- [same chart on live](https://ourworldindata.org/grapher/daily-new-estimated-infections-of-covid-19?time=2021-01-10&country=DEU~FRA)
- [Stacked bar chart, auto-faceted because it shows multiple entities](https://tufte-owid.netlify.app/grapher/deaths-by-age-group-stacked?country=DEU~F …

feat(facet): show faceting strategy dropdown when forcing faceting

---

packages/@ourworldindata/grapher/src/stackedCharts/AbstractStackedChart.tsx
packages/@ourworldindata/grapher/src/stackedCharts/StackedAreaChart.stories.tsx
packages/@ourworldindata/grapher/src/stackedCharts/StackedBarChart.tsx

[As discussed on Slack](https://owid.slack.com/archives/C03NV9Z3YSV/p1674057135213079)
This kind of interpolation doesn't make sense for Stacked Bar charts, and as it turns out there's not a change for the worse in the SVG tester either.

Disable linear interpolation on StackedBar charts

---

packages/@ourworldindata/grapher/src/mapCharts/GeoPathRoundingContext.ts
packages/@ourworldindata/grapher/src/mapCharts/MapChart.tsx
packages/@ourworldindata/grapher/src/mapCharts/MapProjections.ts

Okay, well, I must admit I got sidetracked when working on map annotations ;)
I noticed the way we first generate a SVG path for a country, then tear it apart to round numbers to one decimal place, and then reconstructing the SVG path is not very performant.
It turns out that d3 allows passing a context to the projection functions. The context is normally used to render to, say, a canvas element, but it's also perfectly fine for our use case here.
And indeed, in my very unscientific testing, `geoPathsFor` takes:
* 30-40ms before this optimization
* 12-15ms now
The return value is totally unchanged, which the SVG tester will confirm.

perf(map): optimize `geoPathsFor` method

---

site/runSiteFooterScripts.ts

The de-structuring of debug causes recurring issues to a small but significant number of users. We don't really know how this comes to be but assume that some html pages must be still using a cached version that could lead to the value passed into runSiteFooterScripts to be undefined. Anyhow, this change guards against this and should fix this issue.

fix: fix debug destructuring bug

---

db/migrateWpPostsToArchieMl.ts
db/model/Gdoc/htmlToEnriched.test.ts
db/model/Gdoc/htmlToEnriched.ts
db/model/Gdoc/rawToArchie.ts

This PR collects the counts of tag types, both HTML and wp: comment component ones, of each post and stores these stats in the archieml_update_statistics column of the posts table. This information will be useful during the iterative process of backporting so that you can e.g. easily see the posts that have a <video> tag.

Collect html and wp:component tag statistics during backporting

---

db/tests/run-db-tests.sh
devTools/docker/create-test-db.sh
devTools/docker/mark-test-mysql-dirty.sh

When running "make dbtest", a new MySQL testing database is intialised with a base schema and users. It must be ready before tests can be run.
Currently, the command we use to wait may return before the database is in fact ready, which we workaround with "sleep 3", although on some machines 3s is not enough.
This change replaces this strategy with by adding a "tombstone" table called `_test_db_ready` which is added at the end of db init. The wait script waits for this table to be created, meaning there is no longer a race condition on first run.
To avoid a race condition on second run, we delete the tombstone after every test run, meaning that on subsequent runs we will wait until the db is re-initialised again.

fix: get rid of race condition on "make dbtests"

---

docs/devcontainer-setup.md

Quick fix for a few typos and words.

Fix typos in 'Devcontainer setup guide' page

---

packages/@ourworldindata/grapher/src/stackedCharts/StackedBarChart.tsx

Closes #1866.
This PR fixes the two problems mentioned in the issue.
1) Missing data has a 'fake' property, which comes from the function `withMissingValuesAsZeroes`. If fake, display "NA" instead of zero.
2) 
- I extended the tooltip to show when hovering over year labels as well. 
- Tooltip position maybe needs to be adjusted, but I'm not sure what would be a good way to determine it.
- Adding the label tooltip into the bar tooltip might make it a bit more confusing, maybe it could be moved into a separate component?.
Here are some screenshots:
Hovering over 'low income' bar:
Hovering over the year label:
I don't think I can access explorers from the devcontainer setup, so I tested in the admin page by creating a new chart and using the deaths_drought data variable.
Let me know what you …

Improve stacked bar tooltip to better handle missing data

---

adminSiteClient/Forms.tsx
adminSiteClient/TagBadge.tsx
adminSiteClient/admin.scss
db/migration/1675374345914-ChartTagIsKeyChartNonNull.ts
db/migration/1675374345914-ChartTagIsKeyNonNull.ts
db/model/Chart.ts
db/wpdb.ts
packages/@ourworldindata/utils/src/index.ts
packages/@ourworldindata/utils/src/owidTypes.ts
site/ChartListItemVariant.tsx
site/GrapherPage.jsdom.test.tsx
site/blocks/AllChartsListItem.tsx
site/blocks/RelatedCharts.jsdom.test.tsx
site/blocks/RelatedCharts.tsx

[As discussed on Slack](https://owid.slack.com/archives/CQQUA2C2U/p1675366222423609).
I tested that `/artificial-intelligence` displays the charts in the same order as before even after the ordering change, and adapted the `RelatedCharts.jsdom.test.tsx` test in such a way that it now also incorporates `isKey`, and checks for the correct order.

migrate(chart_tags): make isKey column non-null and rename to isKeyChart

---

db/migration/1675107812815-AutomatedCreatedUpdatedTimestamps.ts
db/model/Chart.ts
db/tests/basic.test.ts

This PR is part of the ongoing effort to drag our database out of the stone age. It adds automatic createdAt/updatedAt timestamps for almost all of our tables. Existing fields of such names are updated so that all these fields are updated automatically by mysql.
I also added a test based on the recent work to make the database test-able. Run `make dbtest` to run the tests (but they are also run as part of github actions now).
Let me know what you think, especially about the choice of tables that I did not add the automatic timestamps for as this was the area I was least sure about.

Automatic mysql timestamps

---

.vscode/launch.json
adminSiteServer/adminRouter.tsx
baker/postUpdatedHook.ts
db/migrateWpPostsToArchieMl.ts
db/migration/1675447441269-AddAuthorsToPosts.ts
db/migration/1675774335211-AddExcerptToPosts.ts
db/migration/1676470290267-AddCreatedAtInWordpressToPosts.ts
db/syncPostsToGrapher.ts
packages/@ourworldindata/utils/src/owidTypes.ts

This PR collects the authors from wordpress (all of them, with their order) and the excerpt (what is shown as the subtitle in both old and new style articles). The posts table in our mysql database is extended with two columns, the scripts to bulk fetch wordpress posts and the hook to update single posts on wordpress save are updated, and the information is used in backporting to create gdoc articles. This is part of issue #1870 
When rolling this out to prod:

Copy Wordpress authors and excerpt to posts, use in backporting

---

baker/algolia/configureAlgolia.ts
baker/algolia/indexChartsToAlgolia.ts
packages/@ourworldindata/utils/src/MarkdownTextWrap/MarkdownTextWrap.tsx
site/owid.scss
site/search/SearchResults.tsx
site/search/searchClient.ts
site/search/searchTypes.ts

Live on _tufte_, together with #1916.
Improving search, but this time for charts.
Includes:
- _Biggest change_: Ranking charts at the top when they are key charts for a tag, e.g. for "Artificial intelligence", "Chess ability of the best computers" is one of the first results, even if AI is nowhere to be found in its title & subtitle.
- some more style touchups, including ones that align it more with the "pages" results
- highlighting occurrences of the search term
- stripping out Markdown syntax and DoDs before indexing
- add some more synonyms

Search, part 2: better chart search

---

package.json
site/CookiePreferencesManager.tsx
site/search/SearchResults.tsx
site/search/searchClient.ts
site/search/searchTypes.ts
yarn.lock

Fixes #1877 | Live on _tufte_, together with #1915.
By communicating back click-through analytics to Algolia, they can provide us with insights like this one here:
As you can see, this is working fine already :)
One pretty big caveat right now is that for charts, we track click-throughs for all chart links, but don't track clicking on the interactive chart result, or interacting with it.

Search, part 3: add click-through analytics

---

baker/algolia/configureAlgolia.ts
baker/algolia/indexChartsToAlgolia.ts
baker/algolia/indexToAlgolia.ts
db/model/Pageview.ts
site/search/searchTypes.ts

Resolves #1878 | Live on [tufte](https://tufte-owid.netlify.app/)
This work matches up the data from the `pageviews` table with the actual posts and pages we have, and then adds that as an attribute to the Algolia records.
One important notion is that of a "score" - we don't rank by a single attribute any more, but combine them when we're creating the record already (since Algolia doesn't support computed/generated attributes, sadly).
In particular, the scores are calculated as follows:
- For charts, it's `score = numRelatedArticles * 500 + views_7d`
- (currently, `numRelatedArticles` is ranging between 0 and 19, for `life-expectancy`)
- For posts, it's `score = importance * 1000 + views_7d`
- (note that `importance` is one of 3, 1, 0, or -1)
These weighting factors are, of course, simply …

Search, part 4: add pageviews as a ranking criterion

---

adminSiteClient/NewsletterPage.tsx
adminSiteClient/PostsIndexPage.tsx
adminSiteServer/apiRouter.ts
baker/SiteBaker.tsx
db/migration/1676022628012-AddPostsWithGdocPublishStatusView.ts
db/model/Gdoc/archieToGdoc.ts
db/model/Gdoc/rawToArchie.ts
devTools/docker/vhosts.conf

This PR completes the workflow of converting selected wordpress posts into gdocs and then allowing publishing those. Before we did create gdocs documents but they were not registered in the posts_gdocs table and there was no way to publish them from there. This PR now adds that capability.
To test it, go to the posts table. You can view compare for all posts and then also hit "Create GDoc" (this needs the .env setting entry GDOCS_BACKPORTING_TARGET_FOLDER to be set). Once the GDoc is created, a link brings you to the preview page from where you can also go the the gdoc and edit it.

Complete backport publishing workflow

---

adminSiteClient/NewsletterPage.tsx
adminSiteClient/PostsIndexPage.tsx
adminSiteServer/apiRouter.ts
baker/postUpdatedHook.ts
baker/sitemap.ts
db/migrateWpPostsToArchieMl.ts
db/migration/1676042584151-AddUpdatedAtInWordpressToPosts.ts
db/syncPostsToGrapher.ts
packages/@ourworldindata/utils/src/owidTypes.ts

Because the posts table mirrors wordpress posts into our database, we use it to understand when the wordpress post was last modified. The [recent unification of automatic timestamps](https://github.com/owid/owid-grapher/pull/1888) interferes with this now - when running the archieml update for example that touches every post, the updated_at field is now automatically changed. This commit adds a new field so that we can separate the "wordpress changed" meaning from "the table was touched"

fix: Add updatedAtInWordpress field to posts table

---

db/migrateWpPostsToArchieMl.ts
db/model/Gdoc/gdocUtils.ts
db/model/Gdoc/htmlToEnriched.test.ts
db/model/Gdoc/htmlToEnriched.ts

This PR backports prominent links. Prominent links will need to fetch fallback titles (the title of the content they are pointing to) and thumbnails (of the content they are pointing to) - but this has to happen at bake time, not at backport time. This concern is thus tracked in #1921

Backport prominent links

---

db/migrateWpPostsToArchieMl.ts

This PR stops doing special handling for {ref}s which ironically makes them work in the full workflow :). To explain: initially I had put in the work to extract {ref} blocks in the html and replace them with superscript indexed numbers. This would have meant reconstructing the refs again when creating the ArchieML in Gdocs. Now we just leave them be.  This means that in the compare view they are visible as text (i.e. they don't show correctly in a tooltip), but once you create the gdoc they contain the {ref} blocks as before and are then rendered and previewed correctly. I think the fact that it looks a bit different now in the compare view is fine but curious to hear what you think.

Backport refs

---

db/model/Gdoc/archieToGdoc.ts
db/model/Gdoc/rawToArchie.ts

This PR fixes an issue with raw html blocks. They are used in backporting for things like HTML tables and thus quite important. The previous code had no special handling for html blocks. This meant that when we do our usual transformations like so:
```mermaid
flowchart LR
enriched --> raw
raw --> archieml[ArchieMl with inline HTML for styling]  
archieml --> cheerio[Cheerio nodes]
cheerio --> gdoc[GDoc DOM]
```
... then the problem is that the cheerio parsing step would parse the tables etc and we only want to use it to parse inline styles like `<a>`, `<em>` etc.
So this PR a) ensures that html properties are always written in the archieml multiline style with the `:end` token, and b) uses this information to skip cheerio parsing from the beginning of `html: ` until the :end token.

Backporting should retain html in html blocks

---

site/blocks/help.scss
site/blocks/index.ts

Nowadays not only used next to non-interactive charts but also next to interactive charts (explorers) and in other article contexts, making it overall more desirable to show them.

feat(help): bring help boxes back on mobile

---

baker/GrapherBaker.tsx
db/Variable.test.ts
db/model/Variable.ts

Rip out `data_values` table and fetch data from data JSON files instead. To make this work I had to refactor a few things:
1. Start using [nodejs-polars](https://github.com/pola-rs/nodejs-polars) to manipulate with dataframes
2. Only bake new variables for `country_latest_data` (country profiles) - this should be fine given that variables data never changes (we only do revisions), also we'll be replacing it by new country profiles soon
3. Simplify Makefile by removing SQL dump with data values
4. Raise an error when someone tries to use "Import CSV" tool (got replaced by Fast-track)
5. Remove DuckDB and option for reading Parquet
6. Remove option for fetching data from Data API
[nodejs-polars](https://github.com/pola-rs/nodejs-polars) is a cool Rust alternative to Pandas. It has a lot of …

refactor(baking): replace `data_values` table by fetching data JSON files

---

adminSiteClient/EditorScatterTab.tsx
packages/@ourworldindata/grapher/src/scatterCharts/ScatterPlotChart.tsx
packages/@ourworldindata/grapher/src/scatterCharts/ScatterPlotChartConstants.ts

Allows authors to manually select entities to be included in scatter plots. It mirrors the way Marimekko charts do this: The author can either specify an explicit start selection or exclude individual entities. 
closes #1912

feat(scatter): allow manual entity selection

---

adminSiteClient/EditorScatterTab.tsx
packages/@ourworldindata/grapher/src/core/Grapher.tsx
packages/@ourworldindata/grapher/src/core/GrapherInterface.ts
packages/@ourworldindata/grapher/src/scatterCharts/ScatterPlotChart.tsx
packages/@ourworldindata/grapher/src/scatterCharts/ScatterPlotChartConstants.ts
packages/@ourworldindata/grapher/src/scatterCharts/ScatterPointsWithLabels.tsx
packages/@ourworldindata/grapher/src/schema/grapher-schema.002.json
packages/@ourworldindata/grapher/src/schema/grapher-schema.002.yaml

Adds an option to hide entity names in scatter plots, as requested in #1550.
Issue #1550 states that this option should also work in explorers - that piece is missing atm. Daniel suggested to come back to this in a few days when I'm a bit more familiar with the codebase and focus on Grapher for now.

feat(grapher): add option to hide scatter labels

---

adminSiteServer/adminRouter.tsx
db/migrateWpPostsToArchieMl.ts
db/model/Gdoc/htmlToEnriched.ts
packages/@ourworldindata/utils/src/index.ts
packages/@ourworldindata/utils/src/owidTypes.ts

This is a very bare-bones way of surfacing the migration errors we collect for every post. This might be useful to alert users to inspect certain elements in more detail or just to show if the system sees anything wrong with the translation.

enhance: add primitive way to see list of migration errors

---

explorer/GrapherGrammar.ts

Turns out it doesn't do anything...
The harder part of this task however is to remove all uses of the `facet` column in the owid-content repo (and replace them with `selectedFacetStrategy`, if not already present).

cleanup(explorer): remove `facet` property from grammar

---

db/model/Variable.ts

We're now fetching data from S3 that goes through a worker with 1 hour Cloudflare cache. It can happen that when you import dataset that already exists, you'd still see an old version (it happened for [excess mortality](https://owid.slack.com/archives/C46U9LXRR/p1677579233857919)).
This PR skips the cache when fetching data from S3 (which applies to both admin and baking). There are alternative ways how to fix this:
1. Purge cache when data is uploaded to S3 - I couldn't find a way how to purge only a certain cache key for all workers. We could call `cache.delete` in worker, but that only applies to local cache of a single worker.
2. Lower cache from 1 hour to something much smaller - not sure about the implications, but something like 5 mins could perhaps work
3. Switch to R2 and turn …

fix(Variable): don't use cache when fetching data from S3

---

adminSiteServer/FunctionalRouter.ts
db/model/Variable.ts

We're getting errors all over admin that are hard to replicate (e.g. [this one](https://github.com/owid/owid-grapher/issues/1978)). They have probably something to do with fetching data from S3, but we're unable to pinpoint the root cause. We also ran into this error once [on this chart](https://owid.cloud/admin/charts/1471/edit).
They sometimes happen when we hit Cloudflare worker on https://catalog.ourworldindata.org/baked-variables/live_grapher/data/576162.json?nocache. I've done some load testing and we start running into problems for ~1000 parallel requests (we shouldn't be doing such number of requests anywhere from admin though). There might be rate limiting on Cloudflare when doing requests from single IP. Load testing S3 directly was ok.
We also ran into this error
``` …
```

enhance(Variable): retry variable fetching and start logging errors

---

packages/@ourworldindata/grapher/src/scatterCharts/ScatterPlotChart.tsx

Fixes the issue described in #1332 by respecting the author's domain extent setting for data sets with a single unique value along an axis.
What happens is that basically if there is only one (unique) value along an axis, the extent of the domain is set to a reasonable default that is (in case of linear scales) `[unique_value - 1, unique_value + 1]`.  The author's setting is then taken into account by _expanding_ (but never _shrinking_) the computed extent. In most cases, that's fine. But when the computed extent was set to `[unique_value - 1, unique_value + 1]`, and thus "overshoots" the actual data range to both sides, then this is not corrected for when taking into account the author's domain setting. Check out [this chart](https://ourworldindata.org/grapher/life-expectancy-vs-liberal-d …

fix(grapher): fix domain extent for scatter plots with few data points

---

adminSiteClient/PostsIndexPage.tsx
adminSiteServer/apiRouter.ts
db/model/Gdoc/archieToGdoc.ts
packages/@ourworldindata/utils/src/index.ts
packages/@ourworldindata/utils/src/owidTypes.ts

This was requested by Joe.  It happens that authors are working on converting an entry that is not supposed to be converted as one entity. In those cases it is useful if, after creating a gdoc and copying some fragments, the link to the doc can be cut again so as not to confuse
yourself or others in the future.

feat: add an unlink button - this keeps the gdoc but severs the link to posts/gdocs

---

db/model/Gdoc/htmlToEnriched.ts

Image backporting will have to switch to the new drive based image hosting in the future but for now this is better than not showing images at all

Fix: fix image paths being dropped in backport

---

db/Variable.test.ts
db/model/Variable.ts
packages/@ourworldindata/utils/src/index.ts

Previously we were baking data either from S3 if `dataPath` was defined on variable or from `data_values` table if `dataPath` was missing. In this PR we remove the branch that bakes from `data_values`.
In order to make this work, we have to make sure that `dataPath` always exists. This is currently done by running `datasync` service in ETL that synces data from `data_values` to S3. That means there's some latency (<30s). This is fine for JSON data, but would trickier for JSON metadata - if someone is editing variable metadata in admin, they wouldn't see their changes changed instantly. That is why we still fetch metadata from MySQL. Hopefully, once we separate ETL and admin, we could start fetching JSON metadata too.
This PR also refactors a few things to fix performance issues we're …

enhance(Variable): only load data from S3 and deprecate data_values

---

db/model/Variable.ts

`db.queryMysql` throws an error when parameter is an empty array

fix(Variable): fix case with no entities

---

packages/@ourworldindata/grapher/src/barCharts/DiscreteBarChart.tsx
packages/@ourworldindata/grapher/src/barCharts/DiscreteBarChartConstants.ts
packages/@ourworldindata/grapher/src/stackedCharts/AbstractStackedChart.tsx

fixes #1928
[As suggested by Marcel](https://owid.slack.com/archives/C5BDCB2R3/p1677880789986719?thread_ts=1677861957.213109&cid=C5BDCB2R3), we'll disallow splitting by product if that means we would be comparing different units along the same axis.
This PR does both:
- Fixes the particular issue in #1928 (if splitting by product were allowed)
- Disallows splitting by product when appropriate (such that the fix from above shouldn't be necessary)

Disallow splitting by product for charts with more than one unit

---

adminSiteServer/apiRouter.ts
db/model/Chart.ts

Fixes #1990 
In #1665, I changed two instances of `Table.findOne(id)` to `Table.findOneBy({ id })`, thinking they were entirely equivalent.
This is not the case, however, in the case where `id` is nullish - in that case we would be running `Table.findOneBy({})`, which is effectively returning the first row in the table.

fix: getBySlug method properly returns null

---

db/Variable.test.ts
db/model/Variable.ts
packages/@ourworldindata/utils/src/index.ts

Reverts #1981 and #1985, since their handling of mixed-type data is different than before, which is breaking charts. [See Slack.](https://owid.slack.com/archives/C46U9LXRR/p1678486016498279)

Revert "enhance(Variable): only load data from S3 and deprecate data_values"

---

packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.tsx
packages/@ourworldindata/grapher/src/core/grapher.scss
packages/@ourworldindata/grapher/src/header/Header.tsx
site/css/variables.scss

Fixes #1993.
This will be quite the SVG diff, but that's to be expected.

enhance: Add "Liberation" fonts as a fallback font, for Wikipedia

---

packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.tsx

Fixes [the svg issue I mentioned on Slack](https://owid.slack.com/archives/C46U9LXRR/p1678729334780529).
Also makes it so the white background is only present on exports, which should be okay I think

fix: use another method to achieve a solid white background in svgs

---

public/_headers

After identifying this [major cache issue on Slack](https://owid.slack.com/archives/CQQUA2C2U/p1678902021418709).
This is the cache config [as used by Netlify by default](https://www.netlify.com/blog/2017/02/23/better-living-through-caching/) (so I guess we could also just drop the header? but maybe good to be explicit about it).

fix: remove `s-maxage` header

---

packages/@ourworldindata/core-table/src/CoreTable.ts
packages/@ourworldindata/core-table/src/OwidTable.ts
packages/@ourworldindata/grapher/src/color/ColorScaleBin.ts

following up some breakages after #2016 
they didn't come up before because we're using `tsup` to build `packages/*`, which is currently still using TS 4.9

chore: fix type errors with TS 5.0

---

site/SiteNavigation.tsx
site/SiteNavigationTopics.scss
site/SiteNavigationTopics.tsx
site/SiteSearchNavigation.tsx

- fix: opening another menu after running a search now properly closes the search results. As side-effects:
- the search query is now kept while interacting with the nav
- the search remains active (overlay on) when deleting the whole query. The search can still be fully deactivated by pressing "esc", clicking on the cross, clicking on the overlay or interacting with another menu element.
https://user-images.githubusercontent.com/13406362/226956667-0d2f2a32-0e7a-4839-9807-c3ecac079e05.mov
_👆 the bug_
- feat: open first topic by default
- enhance(nav): ensure continuity of hover between bordering items

Fix nav issues

---

Makefile
devTools/docker/sync-s3-images.sh

We weren't sourcing `.env` when running `sync-s3-images` and there was also a small bug in checking env. With this PR I can run `make refresh` successfully (after setting `IMAGE_HOSTING_BUCKET_PATH` in `.env`)

fix(devtools): source .env when running sync s3 images

---

Makefile
site/README.md

At the moment, when you run `make up.full` for the first time, it copies an template `.env` file for you that should work out of the box, except one setting must be set manually, the image bucket path.
This change sets it to `owid-image-upload/dev-<user>`, where `user` is the unix username of the current user.

chore: use a sensible default for the image bucket path

---

db/model/Gdoc/rawToEnriched.ts
site/gdocs/ArticleBlock.tsx

see #1871 and companion PR for backported content #1953 
- Updates to existing source gdocs need to be done in parallel, manually.
- Authors need to be notified of the change: headings in content should now start at level 1 (and not 2, as historically done)

1871 lift content headings one level up

---

packages/@ourworldindata/grapher/src/mapCharts/MapChart.tsx

fixes #2054 
The "No data" annotation in tooltips doesn't show up in explorers, see #2054 for screenshots.
The reason "No data" shows up in charts but not in explorers is that the respective data column in charts is of type `NumberOrStringColumn` while the data column in explorers is of type `NumericColumn`. The `formatValueLong` function behaves differently for `NumberOrStringColumn` and `NumericColumn`. In case of `NumberOrStringColumn`, string values are passed through, in case of `NumericColumn` string values are silenced (returns `""`). That's why the "No data" label doesn't show in explorer maps.

fix(explorer): show "No data" annotation in map tooltips

---

adminSiteClient/EditorTextTab.tsx
adminSiteClient/GrapherConfigGridEditor.tsx
db/migration/1678783599815-SplitHideTitleAnnotationIntoMultipleFlags.ts
explorer/GrapherGrammar.ts
packages/@ourworldindata/grapher/src/core/Grapher.tsx
packages/@ourworldindata/grapher/src/core/GrapherConstants.ts
packages/@ourworldindata/grapher/src/core/GrapherInterface.ts
packages/@ourworldindata/grapher/src/schema/grapher-schema.003.json
packages/@ourworldindata/grapher/src/schema/grapher-schema.003.yaml

fixes #1094 
Splits the "Hide automatic time/entity" toggle into multiple controls, including:
- "Hide automatic entity (where possible)"
- "Hide automatic time (where possible)"
- "Don't prepend 'Change in' automatically (where possible)"
To do this, I have replaced `hideTitleAnnotation` with an object that holds three boolean properties, `entity`, `time` and `change`. I haven't changed the logic at all though. I've looked at some example charts and I couldn't find one where I thought updating the logic might be beneficial (doesn't mean these cases don't exist though).
Questionable:
- Wording
- Down migration (at the moment, if _any_ flag in the `hideTitleAnnotation` object is set to true, `hideTitleAnnotation` will be set to true)
- I created a new config schema and wrote a migration, …

feat(admin): split "Hide automatic time/entity" toggle into multiple controls

---

adminSiteClient/EditorMapTab.tsx
explorer/ColumnGrammar.ts
packages/@ourworldindata/core-table/src/CoreColumnDef.ts
packages/@ourworldindata/core-table/src/CoreTableColumns.ts
packages/@ourworldindata/core-table/src/CoreTableUtils.test.ts
packages/@ourworldindata/core-table/src/CoreTableUtils.ts
packages/@ourworldindata/core-table/src/OwidTable.ts
packages/@ourworldindata/grapher/src/mapCharts/MapChart.tsx
packages/@ourworldindata/grapher/src/mapCharts/MapConfig.ts
packages/@ourworldindata/grapher/src/schema/grapher-schema.002.json
packages/@ourworldindata/grapher/src/schema/grapher-schema.002.yaml
packages/@ourworldindata/grapher/src/schema/grapher-schema.003.json
packages/@ourworldindata/grapher/src/schema/grapher-schema.003.yaml
packages/@ourworldindata/utils/src/index.ts
packages/@ourworldindata/utils/src/owidTypes.ts

fixes #1182 
Grapher currently employs a `closest` strategy to fill missing data values that works in both directions, i.e. backwards and forwards in time. This is sometimes not appropriate and produces misleading charts, see #1182.
Add an option to the admin that allows to control whether the tolerance should be applied backwards in time, or forwards in time, or in both directions.
To do so, a new property `map.timeToleranceStrategy` is added to to chart config with three options:
- `closest` (default): Look for data values in both direction (current behaviour)
- `backwards`: Only look for data points in the past
- `forwards`: Only look for data points in the future
- Instead of specifying a strategy, we could also present two number fields to the author, "Backward tolerance" and …

feat(map): give authors more control over tolerance

---

baker/GrapherBaker.tsx
baker/worker.ts
db/model/Variable.ts

We're occasionally running into 429 errors caused by Cloudflare's rate limiting. This PR is more gentle and uses max 5 sockets to limit concurrency. It also drops `nocache` from URL - that's no longer an issue since TTL is now 5 min.
I've tested this against staging worker and didn't get 429 with this config. This wouldn't be necessary if we used S3 URLs directly, but it's safer to go one step at a time rather than rushing into them.

fix(Variable): limit concurrent requests to avoid 429 errors from rate limiting by Cloudflare

---

packages/@ourworldindata/grapher/src/barCharts/DiscreteBarChart.tsx
packages/@ourworldindata/grapher/src/chart/ChartInterface.ts
packages/@ourworldindata/grapher/src/core/Grapher.tsx

fixes #1542 
Entity name does not show up in chart titles for faceted single-entity StackedArea charts. This has been fixed for explorers a few days ago, but the issue persists in grapher charts.
- Explorer: https://ourworldindata.org/explorers/population-and-demography?Metric=Population+by+broad+age+group&Sex=Both+sexes&Age+group=Total&Projection+Scenario=None&country=~AFG (this works at the moment and shouldn't break again)
- Grapher chart: https://owid.cloud/admin/charts/298/edit – go to the "Data" tab, change selection to "User can add and remove data", notice that "Sweden" is not displayed in the title anymore (this is broken at the moment and should be fixed)
These are the offending lines:
https://github.com/owid/owid-grapher/blob/553d923e3b103621e18b332ba7c3f9e89441a510/packages/%40 …

fix(grapher): show entity in title for faceted single-entity charts

---

packages/@ourworldindata/grapher/src/scatterCharts/ScatterPlotChart.tsx

This PR offers a partial solution to issue #1167 by hiding the No Data label that appears in the legend for scatterplots when aggregates are part of the data set. It's unresolved whether anything should be done to hide the actual bubbles for regions (especially for the World dot which will typically dwarf all other country sizes).
The "No Data" item is being filtered out based on the `label` value of the legend's ColorScaleBin meaning this will break if it's ever renamed (e.g. to "Other" as proposed in #1306).

fix: hide No Data item in scatterplot legends

---

packages/@ourworldindata/core-table/src/OwidTable.ts
packages/@ourworldindata/grapher/src/core/LegacyToOwidTable.ts
packages/@ourworldindata/grapher/src/dataTable/DataTable.tsx

Variable-specific annotations are currently merged into the OwidTable using the naming convention `${id}-annotation`. There are also columns of the form `${id}-originalTime` that are currently omitted when displaying values in a table view, but perhaps there are others as well?
This PR adds the `-annotation` naming scheme to the list of columns to be omitted, but it might be better to come up with a consistent naming convention for programmatic columns so that we don't need to special case any future additions (or others that I've missed here).
One possibility would be renaming programmatic column slugs to something along the lines of `__${id}-${columnName}` and filtering based on the `/^__/`.
fixes #1275

Hide programmatic columns in tables

---

packages/@ourworldindata/grapher/src/dataTable/DataTable.scss

This PR uses flexbox rather than `float` to position the sort icon in the headers of data tables. I'd love to hear reports of regressions or unintended consequences on other pages.
Fixes https://github.com/owid/owid-grapher/issues/2047
https://ourworldindata.org/grapher/compare-sources-working-hours?tab=table&country=~ESP
https://ourworldindata.org/grapher/kaya-identity-co2?tab=table&time=earliest&country=~DZA

Fix table header icons

---

adminSiteServer/apiRouter.ts
db/model/Gdoc/Gdoc.ts
db/model/Image.ts

After migrating all 3200 WP images to Drive, a performance bottleneck in the current image syncing strategy was exposed due to GDrive's max pagesize of 1000.
Previous strategy: 
1. Extract image filenames from GDoc
2. Request **all images** from GDrive
3. Index them in memory
4. Validate the images that the GDoc references
5. Sync them to S3
New strategy is basically the same, except now we only request the _referenced images_ from GDrive.
Effectively:
```
OLD:
loadImages()
syncImages(filenames)
NEW:
loadImages(filenames)
syncImages()
```
I don't know why I didn't do it this way initially. I think I thought caching all the metadata in memory would work better for baking, but the baking method we went with made caching redundant, so 🤷

refactor(gdocs): only fetch the images we need

---

baker/buildLocalBake.ts

With the --steps feature, we can be more granular and might want to bake assets (from bakeWordpressPages) and charts

enhance(build): bakeAll during localBake

---

db/migration/1680614452457-HideTimelineForDiscreteBarCharts.ts
packages/@ourworldindata/grapher/src/core/Grapher.jsdom.test.ts
packages/@ourworldindata/grapher/src/core/Grapher.tsx

fixes #2060 
Adds the ability to show a timeline for discrete bar charts.
Tasks:

enhance: show timeline for DiscreteBar charts

---

Makefile
adminSiteClient/SuggestedChartRevision.ts
adminSiteClient/SuggestedChartRevisionApproverPage.tsx
adminSiteClient/admin.scss
adminSiteServer/apiRouter.ts
db/model/SuggestedChartRevision.ts

For the chart revision tool I am working on surfacing details on what is changing in the chart. To this end, I have added a new field `changesInDataSummary` to our database table `suggested_chart_revisions`.
Now we need to allocate some space on the grapher side to surface this.
This PR:
- Adds HTML field to surface the value of `suggested_chart_revisions`.
- Additionally, I am adding the option to have preview size `"Large"`, too.
- Change heading tags: `<h3>` → `<h1>` and `<h5>` → `<h2>`.
Parallel work on the ETL-side: https://github.com/owid/etl/pull/987

enhance(chart_revision): add summary text, large viz option

---

adminSiteClient/admin.scss
adminSiteServer/apiRouter.ts
adminSiteServer/app.tsx

Return the error to the client instead of crashing the server, so that parsing failures don't clog up the Slack error thread.

Handle error when archie parser fails

---

packages/@ourworldindata/utils/src/Util.ts
site/hooks.ts

It turns out that the way we imported lodash was causing a lot of requests in the vite dev server, and here we have reduced it down to... just one. This makes pageloads ~20% faster on the dev server.
The bundle size is bigger now, but the increase is negligible.

chore: change the way we import lodash

---

packages/@ourworldindata/grapher/src/footer/Footer.tsx
packages/@ourworldindata/grapher/src/footer/FooterManager.ts
packages/@ourworldindata/grapher/src/header/Header.tsx
packages/@ourworldindata/grapher/src/header/HeaderManager.ts

Pass an empty `detailsOrderedByReference` to `MarkdownTextWrap` when `shouldIncludeDetailsInStaticExport` is false.
This makes `MarkdownTextWrap.svgLines` follow its fallback behaviour which is to not append any new superscript tokens when it encounters DoD spans.
Staging example: 
https://ptolemy-owid.netlify.app/grapher/primary-energy-cons
https://ptolemy-owid.netlify.app/grapher/exports/primary-energy-cons.svg

Hide DoD superscript in static exports

---

adminSiteClient/GdocsPreviewPage.tsx
site/gdocs/OwidGdoc.tsx

I know nothing about how this works, but this has recently been renamed and is currently breaking hydration in prod...

fix(gdocs): use correct name for hydrated element

---

packages/@ourworldindata/grapher/src/stackedCharts/StackedBarChart.tsx
packages/@ourworldindata/grapher/src/stackedCharts/StackedUtils.test.ts
packages/@ourworldindata/grapher/src/stackedCharts/StackedUtils.ts
packages/@ourworldindata/utils/src/Util.test.ts
packages/@ourworldindata/utils/src/Util.ts
packages/@ourworldindata/utils/src/index.ts

fixes #1865
If observations are unevenly spaced, stacked bar charts end up with a non-linear x-axis.
To enforce uniform spacing along the axis, this PR implements [Marcel's suggestion](https://github.com/owid/owid-grapher/issues/1865#issue-1548859529) that involves computed the greatest common divisor. In Marcel's words, the gist of it is:
> ```
> given sortedYears = [1940, 1960, 1970, 1985]
> compute deltas = [20, 10, 15]
> compute gcd(deltas) = 5
> => the "minimum display interval" is 5 in this case
> => show 1940, 1945, 1950, 1955, 1960, 1965, ..., 1985 on the x axis
> ```
The SVG tester comes back with one problematic chart:
**Problem:** This chart shows monthly data but since we currently have no native way to represent monthly data, this data is treated as daily data where only the …

Ensure x-axis in stacked bar charts is linear

---

baker/GrapherBaker.tsx
site/DataPageContent.scss
site/DataPageContent.tsx
site/ExpandableAnimatedToggle.scss
site/ExpandableAnimatedToggle.tsx
site/FallbackFieldExplain.tsx
site/css/mixins.scss
site/gdocs/ArticleBlock.tsx
site/gdocs/Chart.tsx
site/gdocs/Image.tsx

Follow up to #2075, addressing #1947
- Test URL: https://exemplars.owid.cloud/admin/grapher/co-emissions-per-capita
- Test JSON: https://github.com/owid/owid-content/blob/staging/datapages/538918.json
Re-affirming the intention to "get pixels on the screen" so authors can start creating data pages and getting a sense for whether the editorial model works.
- Adding most of the remaining blocks
- Downgrading from "could potentially be published" to "will only work as a high-fidelity internal preview"
- Rendering sections of rich text from individual google docs, parsed and transformed through the new gdoc pipeline. This is rendered client-side only, using an admin route (so not suitable for production).
- Code quality is also sub-par, not too much time should be spent evaluating it as this …

1947 data page part2: google doc rendering and 90% section coverage

---

packages/@ourworldindata/grapher/src/color/CategoricalColorAssigner.ts
packages/@ourworldindata/grapher/src/stackedCharts/AbstractStackedChart.tsx

fixed #2097 | fixes #2098 | fixes #2107
**Problem:** Colours are used inconsisently across faceted StackedArea/StackedBar charts
**Proposed solution:** `seriesColorMap` defined in `FacetChart` is used to cache colours globally and the `CategoricalColorAssigner` is used to actually assign colours to entities/variables (keyed by their series name, i.e. their entity or variable name).
(**Aside:** I had to add another prop to `CategoricalColorAssigner` to have control over the number of colours that we pick from – otherwise lots of charts would come back with different colour schemes that looked worse.)

fix(stacked): make colour use consistent across faceted charts

---

packages/@ourworldindata/grapher/src/facetChart/FacetChart.tsx

fixes #2102 
When selecting a second entity in StackedArea charts, then entity colours would change for no good reason.
- The colour cache `seriesColorMap` exists in `Grapher` as well as `FacetChart`
- If viewing a single entity, faceting is turned off -> `seriesColorMap` in Grapher is used
- If faceting is then turned on (by selecting a second entity), previous colour assignments are thrown away as `seriesColorMap` is initialised again in `FacetChart`
--> take the "current" `seriesColorMap` into account when initialising it in `FacetChart`

fix inconsistent entity colours when switching faceting on or off

---

packages/@ourworldindata/grapher/src/stackedCharts/AbstractStackedChart.tsx

fixes #2110 
Chooses an appropriate shared domain in case of missing data for StackedArea charts. For entity without data, the domain is set to an empty range `[0, 0]`.

Choose an appropriate shared domain in case of missing data for StackedArea charts

---

packages/@ourworldindata/grapher/src/stackedCharts/StackedAreaChart.tsx
packages/@ourworldindata/grapher/src/stackedCharts/StackedConstants.ts

Fixes #2133.
In working on this I noticed a bunch more issues in this, so this ended up as a bit of a refactor.
It also got quite a bit more complex sadly, so if you see any way to simplify any of this (or add helpful comments at the very least) then please do let me know!
Before/afters (left/right):
⬆️ Here, the red incline on the left/right is misleading.
⬆️ Here, there's no data for Afghanistan for years <2000, but we're displaying it as if there was data.
The SVG tester comes back with many errors sadly, but these are only rounding errors as far as I can see.

fix(StackedArea): render the bottom series only within the domain of data availability

---

.github/scripts/buildkite_destroy_staging.py
.github/workflows/buildkite.yml

Github action that is triggered on pull request close and starts [grapher-destroy-staging-environment`](https://buildkite.com/our-world-in-data/grapher-destroy-staging-environment) pipeline on Buildkite through its API.
Closes issue https://github.com/owid/ops/issues/64

feature: github action to destroy staging by sending signal to buildkite API

---

adminSiteClient/EditorCustomizeTab.tsx
packages/@ourworldindata/grapher/src/core/Grapher.tsx

Faceting is turned on by default for the following chart types:
Things I did to make it work (see detailed descriptions below):
- Problem: When line charts include projections into the future, then these are plotted as separate entities
- Solution: Turn faceting off for charts with projections (it would be nice to plot history and projection into a single chart when faceting but I don't think Grapher knows which variables belong together)
<details>
<summary>Screenshot of a problematic chart</summary>
Link: https://ourworldindata.org/grapher/births-and-deaths-projected-to-2100?facet=metric&country=AND~AUS~AZE~BHS
</details>
- Problem: For many selected entities, individual sub-charts are extremely small and labels are not legible
- Solution: It's not a huge deal since by default the "All …

Turn faceting on by default for line charts and stacked charts

---

explorerAdminClient/ExplorerCreatePage.tsx
gitCms/GitCmsServer.ts

[Currently](Currently), when you modify explorers using the admin UI, it immediately writes and pushes these changes to production, regardless whether you are in a dev or staging environment.
This change fixes this for dev environments, by modifying the GitCmsServer to avoid doing Git operations (commit, push) if in a development environment.
Ideally we would do the same for staging. This would need us to be able to easily differentiate between prod and staging, which we can't easily do yet.

fix: do not push explorer changes in dev

---

serverUtils/slackLog.ts

This should make it way easier to debug #2148 hopefully.

feat(slackLog): always include stack trace

---

packages/@ourworldindata/grapher/src/facetChart/FacetChart.tsx

fixes #2152 
removes redundant legends for StackedDiscreteBar that are split by metric

fix: hide legend for StackedDiscreteBar charts that are split by metric

---

baker/GrapherBaker.tsx

If baker fails on a chart, it just logs the error with `console.error(err)` and continues. See what charts are failing like this and either keep them as errors or at least send them to Slack.

refactor(baker): remove silent failures

---

packages/@ourworldindata/grapher/src/core/Grapher.tsx

Don't turn on faceting by default for line charts with projections.
Because some have suboptimal colour assignments, others have confusing legends:

fix(facet): hide facet control for line charts with projections

---

packages/@ourworldindata/grapher/src/core/Grapher.tsx

fixes #2095 (again)
**Problem:** Faceting does not make sense for charts in relative mode when the resulting facets show a single metric or entity
**Solution:**
- Hide the relative toggle in such cases
- Switch to absolute mode for faceting when necessary

Prevent faceting in relative mode when facets would show a single entity or metric

---

baker/SiteBaker.tsx

Country profiles were never awaited. This was making debugging with `--steps countryProfiles` hard.

fix(baker): await country profiles

---

adminSiteServer/IndexPage.tsx
adminSiteServer/mockSiteRouter.tsx
devTools/vite/startVite.sh
package.json
settings/serverSettings.ts
site/Head.tsx
site/SiteFooter.tsx
site/viteUtils.tsx
vite.config.mts

By running `VITE_PREVIEW=true make up`, we'll now be running vite in production mode, meaning:
- Vite runs a proper production build (which will take some seconds!), which is not live-reloading
- It will then run off these assets
- Browser load times will be way faster, because we're only loading two or three files in this case
If `VITE_PREVIEW` is not specified, then everything runs just as it does currently, i.e. with a Vite HMR server.

feat(vite): allow running vite in preview mode

---

explorer/ExplorerGrammar.ts
explorer/GrapherGrammar.ts

fixes #2170
The `entityType` specified in the `ExplorerGrammar` of explorers didn't get passed through to Grapher because `entityType` wasn't specified in the `GrapherGrammar`. This has been fixed.
The example explorer mentioned in the issue is still not _really_ fixed because the dropdown is now labelled "Split by item" but this will be fixed once #2175 is merged.

Fix entity type in explorers

---

devTools/explorerTools/rewriteAllExplorers.ts
devTools/explorerTools/tsconfig.json
explorer/ExplorerProgram.ts
explorerAdminClient/ExplorerCreatePage.tsx
gridLang/GridProgram.test.ts
gridLang/GridProgram.ts
packages/@ourworldindata/core-table/src/CoreTable.ts
packages/@ourworldindata/core-table/src/index.ts

When looking at the explorer code, I found that ExplorerProgram/GridProgram acts on both one-dimensional arrays (`this.lines: string[]`) and two-dimensional arrays (both `this.matrix` and `this.asArray: string[][]`), but **the two could go out of sync** 😱 
That's because `this.matrix` is memoized, but `this.lines` can change (well, only in the Admin, really), and in that case `this.matrix` is not properly updated.
This is madness, and so I decided to fix this from the bottom, by using two-dimensional arrays all the way.
I sure hope our test coverage here is good 🙏🏻

refactor(explorer): always act on two-dimensional arrays

---

adminSiteClient/EditorTextTab.tsx

Requested by Fiona on [Slack](https://owid.slack.com/archives/C03NA1B2P1U/p1683105843805759?thread_ts=1682668766.796469&cid=C03NA1B2P1U)

fix(admin): allow to expand footer note field

---

db/migration/1676022628012-AddPostsWithGdocPublishStatusView.ts
db/migration/1683308571747-RecreatePostsWithGdocPublishStatusSaferWithCoalesce.ts

The view tried to join on the posts_gdocs table and then gave as the isGdocPublished field a nullable boolean. This is easy to use incorrectly so this fix adds COALESCE(false).
This fixes wordpress posts not showing up in the sitemap anymore.

fix: Fix wordpress posts missing in the sitemap by making the posts_with_gdoc_publish_status easier to use

---

packages/@ourworldindata/grapher/src/core/Grapher.tsx

Updates the chart title logic to prevent the entity annotation to be hidden when multiple entity selection mode is turned on.
I recently had a chat with Pablo A who noticed that manually hiding the entity annotation in a chart's title is not allowed for charts in 'change-country' mode but is allowed for charts in 'add-country' mode. That seemed inconsistent.
We have in fact [~30 stacked charts](https://owid-datasette-y43qr.ondigitalocean.app/owid?sql=select%0D%0A++id,%0D%0A++slug,%0D%0A++type%0D%0Afrom%0D%0A++charts%0D%0Awhere%0D%0A++(%0D%0A++++type+%3D+'StackedArea'%0D%0A++++or+type+%3D+'StackedBar'%0D%0A++)%0D%0A++AND+json_array_length(config,+%22$.data.availableEntities%22)+%3E+1%0D%0A++and+json_array_length(config,+%22$.dimensions%22)+%3E+1%0D%0A++and+(%0D%0A++++config+-%3E%3E+%22$.add …

Always show entity annotation in chart titles when in add-country mode

---

site/FrontPage.tsx

Now that we show featured work on the homepage, having the button read "See all of our latest work" implies that the content above it is a subset of our latest work, which isn't necessarily true. 
This is a tiny edit to change the button to read "See all of our work" which doesn't suffer from the same issue.

Homepage copy: clearer distinction with featured/latest work

---

packages/@ourworldindata/grapher/src/scatterCharts/ScatterPlotChart.tsx

Brought up by Matt on [Slack](https://owid.slack.com/archives/C04VBQ00HQR/p1684275787159579)

fix(scatter): hide arrow legend when not useful

---

packages/@ourworldindata/grapher/src/mapCharts/MapTooltip.tsx

As requested by Saloni on [Slack](https://owid.slack.com/archives/C46U9LXRR/p1684778544175229)
Render "Click to select" instead of "Click for change over time" when there is no time series data

fix(map): fix wording issue in map tooltips

---

adminSiteClient/SuggestedChartRevision.ts
adminSiteClient/SuggestedChartRevisionApproverPage.tsx
adminSiteServer/apiRouter.ts
db/model/SuggestedChartRevision.ts
owid-grapher-local.session.sql

This PR adds new functionality to the chart revision tool: Now, users can see - if available - improvement suggestions by chat GPT. At the moment, these improvements only concern the FASTT.
These suggestions are generated on the ETL side, currently manually by users by executing `etl-chartgpt` in the command line.
If the user likes one of the recommended improvements by chat GPT, they can choose to update the chart FASTT with it.
In the preview below, the first revision has some available suggestions by chat GPT; the second and third do not have any.
https://github.com/owid/owid-grapher/assets/18101289/f4f0c28d-77fc-4e45-b505-8bf30145b6d3
ChatGPT revisions are stored in column `experimental` from table `suggested_chart_revisions`.
related issue: https://github.com/owid/etl/pull/1128
cc. …

:tada: chatGPT-based chart revisions

---

packages/@ourworldindata/grapher/src/schema/grapher-schema.003.json
packages/@ourworldindata/grapher/src/schema/grapher-schema.003.yaml

I believe "custom" option is missing in `sortBy`. This raised an error on the chart revision side of things.

✨ schema: missing enum option

---

packages/@ourworldindata/grapher/src/schema/grapher-schema.001.json
packages/@ourworldindata/grapher/src/schema/grapher-schema.001.yaml
packages/@ourworldindata/grapher/src/schema/grapher-schema.002.json
packages/@ourworldindata/grapher/src/schema/grapher-schema.002.yaml
packages/@ourworldindata/grapher/src/schema/grapher-schema.003.json
packages/@ourworldindata/grapher/src/schema/grapher-schema.003.yaml

Add missing default values for `minTime` to chart config schema.
I also added linebreaks, which should make diffs easier to read in the future. Unsure if the previous styling was on purpose.

:sparkles: add default for `minTime` to chart config schema

---

packages/@ourworldindata/grapher/src/dataTable/DataTable.jsdom.test.tsx
packages/@ourworldindata/grapher/src/dataTable/DataTable.scss
packages/@ourworldindata/grapher/src/dataTable/DataTable.tsx
packages/@ourworldindata/utils/src/formatValue.ts
packages/@ourworldindata/utils/src/index.ts
packages/@ourworldindata/utils/src/regions.ts

Implements the proposal sketched in #1876 to group countries and aggregates into separate regions within the table. Countries are always listed first and their names are styled in bold. Aggregates are moved to the end of the table and their names are italicized. When the table is sorted by a column, the two groupings within the table are sorted independently.
To improve the readability of individual rows, the formatter now takes an option to use a no-break space to join the value and its unit, preventing awkward cases with unstable vertical baselines such as:
Vertically aligning cells to the bottom of the cell improves the chances that numerals will all be on the same line regardless of the presence of a data-not-available annotation:
A new formatting option that applies to …

Display aggregates separately in tables

---

.eslintrc.js
.github/workflows/ci.yml

Having the `@typescript-eslint/no-unused-vars` be an error is quite annoying in local development.
The comprise here is to make it into a warning again, but have the eslint action fail on warning already. This we can do because right now, our code has no linting errors and no warnings.
It's worth a try, can totally revert this if it turns out to be annoying.

🐝 actions: make eslint action fail on warnings

---

db/migration/1684922736595-CleanUpEntityTypes.ts
devTools/schemaProcessor/columns.json
explorer/ExplorerGrammar.ts
packages/@ourworldindata/grapher/src/controls/CollapsibleList/CollapsibleList.tsx
packages/@ourworldindata/grapher/src/controls/Controls.scss
packages/@ourworldindata/grapher/src/controls/Controls.tsx
packages/@ourworldindata/grapher/src/core/Grapher.tsx
packages/@ourworldindata/grapher/src/dataTable/DataTable.tsx
packages/@ourworldindata/grapher/src/schema/grapher-schema.003.json
packages/@ourworldindata/grapher/src/schema/grapher-schema.003.yaml
packages/@ourworldindata/grapher/src/selection/SelectionArray.ts

fixes #2159 | fixes #2173 | [Slack discussion](https://owid.slack.com/archives/C5BDCB2R3/p1682701879020779)
This PR solves two problems:
- Overwriting the default entity type "country" can lead to a confusing UI
- "Country" is a poor default since most of our charts contain countries and regions
See #2159 for a description of the problem
This PR implements the following design that was suggested by Matt:
- The height of the tooltip expands as necessary to make "Split by [...]" fit (used to be fixed height)
- The width of the dropdown control expands as necessary to make "Split by [...]" fit (used to be fixed width)
- Length constraint on `entityType` is dropped (I checked the [longest entity types currently in use](https://owid-datasette-y43qr.ondigitalocean.app/owid?sql=select%0D%0A++enti …

Adjust facet control design to accommodate entity types of arbitrary length

---

packages/@ourworldindata/grapher/src/controls/entityPicker/EntityPicker.tsx

fixes an issue mentioned on [Slack](https://owid.slack.com/archives/C46U9LXRR/p1685453357565159) and one more that I came across while looking into this
Fixes two small interaction issues of the entity picker:
- Clicking on an entity does not immediately select the checkbox. The checkbox is only checked after the mouse has left the input field (described by Pablo on [Slack](https://owid.slack.com/archives/C46U9LXRR/p1685453357565159))
- When navigating the "Sort by" dropdown using arrow keys, the entity picker beneath also reacts to pressing arrow keys

fix(explorer): fix small interaction issues when selecting an entity

---

packages/@ourworldindata/grapher/src/controls/entityPicker/EntityPicker.tsx

This reverts the "fix" from #2260. Removing `preventDefault` had some adverse effects...

revert: revert interaction fix for entity picker in explorers

---

site/gdocs/Chart.tsx

I think `d.height` is accidentally ignored at the moment.

fix: respect given height in gdoc charts

---

packages/@ourworldindata/grapher/src/core/LegacyToOwidTable.ts

This fixes a nasty bug that was [happening here](https://buildkite.com/our-world-in-data/grapher-automated-staging-environment/builds/442#01887733-fbba-431f-99ed-8b09650fff0a). The problem is that we take data from S3 and metadata from MySQL, this can cause discrepancy **on staging servers** and some entities on S3 might not be in `entities` table in MySQL.
This is a hotfix to make builds on staging work. It shouldn't affect production. Entity ids are so annoying, world would be much better without them.

:bug: return string id if entity is not in MySQL

---

settings/serverSettings.ts

refactor(env): remove slack webhooks env vars

---

explorer/ExplorerControls.scss

Brought up by Pablo A on [Slack](https://owid.slack.com/archives/C0149NKLZAM/p1685466231179289)
Would be nice to ship something that makes the inequality explorer look nicer before it launches later in June.
Improves the layout of explorer controls:
- Removes the "space-between" flex-layout (the "space-between" layout lead to one control on the left and another control on the right in case of two controls)
- Assigns equal space to each control and allows a control to fill its space (before, a max-width on the control lead to text being wrapped when it didn't need to)
<details>
<summary><b>Inequality explorer (the reason this came up)</b></summary>
Before:
After:
</details>
<details>
<summary><b>Migration explorer (three controls)</b></summary>
Before:
After:
</details>
<details> …

style(explorer): improve layout of explorer controls

---

packages/@ourworldindata/grapher/src/core/Grapher.tsx

fixes #2158
- We don't allow relative mode in some cases, in particular when faceting
- Grapher didn't restore relative mode correctly when switching from a faceted view (where absolute mode was enforced) to the normal view
- Fixed by removing hacky code that manipulated `stackMode` in the facetStrategy setter
`hasSingleMetricInFacets`, `hasSingleEntityInFacets` and `isStackedChartSplitByMetric` should ideally be using `facetControl` (not `selectedFacetControl`) but we can't because that would result in a cyclic dependency.

fix(facet): preserve relative mode after faceting

---

Makefile

This is to allow running "make up" and "make up.full" from non-standard shells like nushell. In nushell's case, it does not support the && operator, which makes tons of things break.
Since nushell can not be a default login shell, it will be nicely overridden here.

:honeybee: reinforce that tmux should run a normal shell

---

explorer/Explorer.tsx

fixes a bug described by Pablo on [Slack](https://owid.slack.com/archives/C46U9LXRR/p1685515462501279?thread_ts=1685453357.565159&cid=C46U9LXRR)
To reproduce:
- Go to https://ourworldindata.org/explorers/crop-yields
- Choose crop Cassava
- Unselect all default countries and select Vietnam
- Change to crop Almonds
- Note that Grapher shows default countries
- Change to crop Cassava
- Note that Grapher shows Vietnam
- Refresh page
- Change to crop Almonds
- Note that Grapher shows Vietnam
The reason for this behaviour is that Grapher remembers previous Grapher views. Some things are persisted across views like the time, for example. Persisting the country fixes this bug but not sure if this has any adverse effect?

fix(explorer): persist country selection between grapher views

---

packages/@ourworldindata/grapher/src/core/Grapher.tsx
packages/@ourworldindata/grapher/src/footer/Footer.tsx
packages/@ourworldindata/grapher/src/footer/FooterManager.ts
packages/@ourworldindata/grapher/src/header/Header.tsx
packages/@ourworldindata/grapher/src/header/HeaderManager.ts

It has been unused for five years (!) (dd6a541c6c4bd5dd2f41e57b8cce62984b61e7cc), and its implementation is quite broken anyway.

refactor: get rid of unused `isMediaCard` prop

---

adminSiteServer/apiRouter.ts

The bulk chart editor sometimes timed out inside a transaction which is pretty nasty - the reason is that we use the normal saveGrapher function
for each of the up to 50 charts that are submitted at one time. In saveGrapher we updated the latestCountryData which is a very expensive operation (hundreds of ms). This PR adds a flag that communicates if the referenced variables might change (the normal case in the chart editor) or not (the case in the bulk chart editor). This makes saving charts much faster, thus solving the timeout issues.

:bug: fix timeouts in bulk chart editor

---

adminSiteClient/GdocsSettingsForm.tsx
adminSiteClient/gdocsValidation.ts
db/model/Gdoc/Gdoc.ts
db/model/Gdoc/archieToEnriched.test.ts
db/model/Gdoc/archieToEnriched.ts
db/model/Gdoc/rawToEnriched.ts
packages/@ourworldindata/utils/src/index.ts
packages/@ourworldindata/utils/src/owidTypes.ts
site/gdocs/Footnotes.tsx
site/gdocs/OwidGdoc.tsx
site/gdocs/centered-article.scss
site/owid.scss

Resolves #2299
Changes refs to use a ID reference system instead of defining them inline.
Upsides:
- Multi-line refs in lists without messing up parsing. 
- Define a ref once and use it multiple times throughout an article.
We have three articles that are published with the old ref style. **Instead of writing a complex migration for them, I've opted to simply strip the refs out of the article during baking.** Once this PR is merged we can update the 3 source docs and republish them.
```
[.refs]
[.refs]
id: example_id
[.+content]
I am a ref
[]
id: multiline_id
[.+content]
I am a ref with [links](https://en.wikipedia.org/wiki/Wiki)
And multiple lines
And formatting
And
A list
whoa
[]
[]
[+.body]
If this works it’ll be great{ref}Some more inline stuff{/ref}
blah{ref}multiline_id{/ref}
blah …
```

🎉 Rich text in gdoc footnotes

---

adminSiteClient/EditorFeatures.tsx
adminSiteClient/EditorTextTab.tsx
adminSiteClient/Forms.tsx
packages/@ourworldindata/grapher/src/core/Grapher.tsx

resolves #2320 (not urgent)
Collection of small improvements around the annotation fields in chart titles:
- Add DiscreteBar, StackedDiscreteBar, and Marimekko charts to the list of chart types where hiding time is not allowed
- These chart types only refer to the current time in the timeline (for SVG exports without controls, the current time would be missing if not mentioned in the title)
- Hide the "Hide automatic time" and "Hide automatic entity" toggles in cases where Grapher ignores their state
- Add help text to better explain the behaviour
----
The SVG tester fails four charts that I think should in fact all mention the time in the title.

Improve chart title

---

packages/@ourworldindata/grapher/src/controls/Controls.scss

relates to #1339 
Fixes an issue where facet control labels were underlined when embedded in an article.

fix: remove underline from facet control options

---

packages/@ourworldindata/grapher/src/core/Grapher.tsx
packages/@ourworldindata/grapher/src/mapCharts/MapChart.tsx
packages/@ourworldindata/grapher/src/mapCharts/MapChartConstants.ts

fixes #2309
For collapsed line charts, clicking on a country in a map currently displays a discrete bar chart with a single bar. It makes more sense to show the full time range instead.

fix(grapher): reset timeline on map click for collapsed line charts

---

site/DataPage.tsx

Data page don't include the json config used by the multiEmbedder to render grapher charts. This PR adds it, similarly to how it is being done on grapher pages.
This affects all data page charts embedded on ourworldindata.org as well as other properties where `embedCharts.js` is used (e.g. sdg-tracker.org)

fix(datapage): add missing json config for multiembedder

---

baker/SiteBaker.tsx

Fixes https://github.com/owid/owid-grapher/issues/2346, maybe
Running two test bakes on Ptolemy:
Average gdoc bake time:
before: `3572ms`
after: `591ms`
We should update `explorerAdminServer` to use the DB, but until then, this will have to suffice.

🔨 use cached explorers during baking gdocs

---

db/migration/1686644029475-ChartsFixSchemaViolations.ts
packages/@ourworldindata/grapher/src/schema/grapher-schema.003.yaml

Because we don't have continuous schema checking, we accumulated a few violations to our current schema. This migration fixes the open issues that exist at the moment - they are all nonsensical fields or null values in places where they shouldn't exist.

:hammer: fix fields in grapher configs that should not exist

---

packages/@ourworldindata/utils/src/index.ts
packages/@ourworldindata/utils/src/owidTypes.ts
site/DataPage.tsx
site/DataPageContent.tsx

Follow up to #2350, which added the grapher config in the page for the multiEmbedder to consume - thus duplicating it with the grapher config passed within OWID_DATAPAGE_PROPS.
This PR unifies both sources and makes DataPageContent consume the same grapher config as Grapher components.

refactor(dp): deduplicate grapher config

---

baker/SiteBaker.tsx
db/model/Chart.ts
db/model/Gdoc/Gdoc.ts
packages/@ourworldindata/utils/src/owidTypes.ts
site/gdocs/ProminentLink.tsx
site/gdocs/utils.tsx

Found a pretty glaring oversight in the Gdoc baking process - we weren't including `linkedCharts`, which are needed to resolve any URLs / metadata to charts/explorers within a Gdoc.
It's a slightly more involved process because we need to resolve redirects first.
e.g. if a gdoc has a prominent link:
```
{.prominent-link}
url: https://ourworldindata.org/grapher/some-slug
{}
```
We use that slug to get the title and thumbnail for the prominent link.
If we update that slug, a redirect is created and we have to then resolve that redirect first before we can fetch the correct metadata.
An individual Gdoc already can already do this by calling `loadLinkedCharts`, but I didn't want to call that once per document so I fetch every single published chart & explorer and attach them instead. 
The …

🐛 pre-fetch linkedCharts before baking

---

packages/@ourworldindata/grapher/src/footer/Footer.tsx
packages/@ourworldindata/utils/src/MarkdownTextWrap/MarkdownTextWrap.tsx

Requested by Joe on [Slack](https://owid.slack.com/archives/C46U9LXRR/p1687335978710619)
Adds markdown support for the "Source" text in the footer. The main reason for doing this is to add support for Markdown links.
- No migration needed: Previously the text was "linkified" (links were detected and wrapped in an anchor tag). Markdown picks up plain text links as well, so existing charts should be fine
- We should consider inlining links in SVG exports (open issue: #2348)

feat(grapher): add markdown support for sources text

---

packages/@ourworldindata/utils/src/owidTypes.ts
site/DataPageContent.scss
site/DataPageContent.tsx
site/ExpandableToggle.scss
site/blocks/CodeSnippet.tsx
site/blocks/code-snippet.scss
site/blocks/index.ts

Some updates to the citation blocks on data pages, including updates to the CodeSnippet component.
- see [slack thread](https://owid.slack.com/archives/C05323F8S6S/p1687454673558549?thread_ts=1687452014.536169&cid=C05323F8S6S) for scope
- see https://www.figma.com/file/hGrJi0P2n2TLsUFO2ispxe/%5BProject%5D-Data-Pages?node-id=665%3A24602&mode=dev

feat(dp): citation updates

---

db/wpdb.ts

Removes duplicate charts in the all charts block on data pages by listing a chart only once, even if it is key chart on a topic, and non key chart on others.
Testing: search for "share in poverty relative to different poverty thresholds" in the all charts block on:
- [live](https://owid.cloud/admin/grapher/share-of-population-in-extreme-poverty): 2 identical charts ❌
- [staging](http://staging-site-datapages/admin/grapher/share-of-population-in-extreme-poverty): 1 single chart ✅
We could push this further by aggregating using SUM instead of MAX, thus promoting a chart which is key chart on multiple topics further up. However, this would require further changes in downstream code to change the type of isKeyChart to number (and rename accordingly, e.g. countKeyChart)

fix(dp): remove duplicate all charts

---

packages/@ourworldindata/grapher/src/core/Grapher.tsx

Discussion on [Slack](https://owid.slack.com/archives/C46U9LXRR/p1670855145129159)
Adds variable 597930 to the list of variable IDs whose source shouldn't be mentioned in the footer when used in Scatter plots and Marimekko charts.
I wasn't sure whether to add 597930 to the list or replace 597929 with 597930. 597929 seems to be still in use, so I opted for the former. And should we also replace 597929 with 597930 here? https://github.com/owid/owid-grapher/blob/a47c39ea877c26818882eb6926b0f46295e493c8/adminSiteClient/EditorBasicTab.tsx#L312
I want to merge this today, so the fix goes live. Can you have a quick look at this when you're back on Monday, @marcelgerber? Thank you!

chore(grapher): add population id

---

site/gdocs/KeyInsights.tsx

Minimal change to fix the anchor computed when selecting key insights on gdoc topic pages. 
Currently, the HTML structure doesn't match the WP block equivalent, leading the script to select the wrong element (and append the wrong anchor in the URL).
see [slack](https://owid.slack.com/archives/C46U9LXRR/p1688018400809499)
When WP is phased out, we might want to rethink and refactor the hydration strategy of this block and make it more react-friendly.

fix(key insight): anchor to correct element

---

adminSiteClient/GdocsPreviewPage.tsx
site/css/page.scss
site/css/topic-page.scss
site/gdocs/AllCharts.scss
site/gdocs/AllCharts.tsx
site/gdocs/ArticleBlock.tsx
site/gdocs/KeyInsights.tsx
site/gdocs/ResearchAndWriting.scss
site/gdocs/ResearchAndWriting.tsx
site/gdocs/centered-article.scss
site/gdocs/topic-page.scss

https://github.com/owid/owid-grapher/assets/11844404/5382fcb4-3ea2-4c83-81b4-536ee642cd7f

Some small Gdocs improvements

---

adminSiteClient/gdocsValidation.ts
db/model/Gdoc/Gdoc.ts
db/model/Gdoc/enrichedToRaw.ts
db/model/Gdoc/exampleEnrichedBlocks.ts
db/model/Gdoc/rawToArchie.ts
db/model/Gdoc/rawToEnriched.ts
packages/@ourworldindata/utils/src/Util.ts
packages/@ourworldindata/utils/src/index.ts
packages/@ourworldindata/utils/src/owidTypes.ts
site/gdocs/ArticleBlock.tsx
site/gdocs/centered-article.scss

As part of #2331.
This is my first ever gdocs block, so I'm putting it out for review already so I know more when working on future blocks.
Example ArchieML:
```
{.align}
alignment: center
[.+content]
Centered text
[]
{}
```
Test document that you can use: https://docs.google.com/document/d/1rR5dbQeINJJL3nsv-wchL8aqjhCjwU3Hp7nWG8l29wY/edit
- The block only sets `text-align`, which means that only text is affected, not chart blocks, images, etc.
The block can, however, contain these because I don't enforce block types that go into the block. Should I??

feat(gdocs): New block `align`

---

packages/@ourworldindata/utils/src/MarkdownTextWrap/parser.ts

See [Slack](https://owid.slack.com/archives/C46U9LXRR/p1688549094872669) | fixes #2402
Fixes an issue where tildes `~` in URLs break our markdown URL parser.

fix(markdown): fix broken url parser

---

explorer/ColumnGrammar.ts
explorer/Explorer.tsx
explorer/ExplorerProgram.ts
explorerAdminClient/ExplorerCreatePage.scss
explorerAdminClient/ExplorerCreatePage.tsx
packages/@ourworldindata/core-table/src/CoreColumnDef.ts
packages/@ourworldindata/core-table/src/CoreTable.ts
packages/@ourworldindata/core-table/src/CoreTableColumns.ts
packages/@ourworldindata/core-table/src/CoreTableConstants.ts
packages/@ourworldindata/core-table/src/OwidTableConstants.ts
packages/@ourworldindata/core-table/src/Transforms.test.ts
packages/@ourworldindata/core-table/src/Transforms.ts
packages/@ourworldindata/core-table/src/index.ts
packages/@ourworldindata/grapher/src/core/Grapher.tsx

relates to #2313
Allows indicator metadata in explorers to be overwritten. (Technically, column definitions are overwritten.) New columns that are derived from indicators can be added using the `transform` keyword.
- if a `columns` block is not linked to a table (i.e. the cell next to the `columns` keyword is empty), then the manually provided column definitions map to the indicators referenced in the `graphers` block to create charts
- mapping is done via a new column called `indicatorId` that is added to the `columns` grammar
- the manually provided column definition for an indicator is merged with the original column definition of that indicator
- add a new column that is derived from indicators by adding an entry to the `columns` block that has a `slug` and a `transform`
- the …

feat(explorer): allow indicator metadata to be overwritten

---

db/migration/1685091238139-UpdateGdocCalloutComponent.ts
db/migration/1685107184417-FixCalloutComponentMissingErrors.ts
db/migration/1685107433682-UpdateGdocRecircComponent.ts

Otherwise, they will fail once new properties are added onto the `Gdoc` object, as we talked about today.
I didn't run these, but I hope that `testdbcheck` will report if they go wrong?

fix(migration): use raw sql for gdocs db migrations

---

explorerAdminServer/ExplorerAdminServer.tsx

fixes #2401
Sorts explorers on https://ourworldindata.org/charts by their title:

enhance: sort explorers by title

---

site/gdocs/Chart.tsx

Sometimes narrative charts stopped reacting to changes made in the source gdoc, first described by Joe on [Slack](https://owid.slack.com/archives/C46U9LXRR/p1688466499021549).
- Add a chart with a custom title to a gdoc
- Note that all controls are hidden
- Configure the chart to show a particular control, e.g. the `entitySelector`
- Note that the entity selector is visible
- Edit the gdoc to hide the entity selector by removing the `entitySelector` keyword
- Note that the entity selector is still visible
- Note that the console logs a hydration diff:
- On the server: `hideEntityControls` is `false`
- On the client: `hideEntityControls` is `true`
- The `merge` function merges all objects into the first one
- `grapherInterfaceWithHiddenControlsOnly` was thus updated on each iteration, and …

Fixes bug where narrative charts stopped responding to gdoc changes

---

adminSiteClient/GdocsDiff.tsx
adminSiteClient/GdocsPreviewPage.tsx
adminSiteClient/GdocsSaveButtons.tsx
adminSiteClient/gdocsDeploy.ts
adminSiteClient/gdocsNotifications.tsx

Fixes #2393 
- There is now a "Save draft" button in the top toolbar, which is only shown when the document is currently unpublished.
- It is used to persist changes made to the slug (and some other properties), which before could only be applied by publishing.
- Saving as draft is possible even if there are document errors.

feat(gdocs-admin): allow saving gdocs as draft

---

adminSiteClient/GdocsBreadcrumbsInput.tsx
adminSiteClient/GdocsPreviewPage.tsx
adminSiteClient/GdocsSettingsForm.tsx
adminSiteClient/gdocsValidation.ts
db/migration/1687851686136-GdocsAddBreadcrumbsColumn.ts
db/model/Gdoc/Gdoc.ts
packages/@ourworldindata/utils/src/index.ts
packages/@ourworldindata/utils/src/owidTypes.ts
site/Breadcrumb/Breadcrumb.tsx
site/LongFormPage.tsx
site/gdocs/OwidGdoc.tsx
site/gdocs/OwidGdocHeader.tsx
site/gdocs/centered-article.scss
site/gdocs/utils.tsx

Part of #2331.
Breadcrumbs are specified on the new `posts_gdocs.breadcrumbs` column, which is a (nullable) JSON array and is of the form:
```json
[
{ "href": "/sdg", "label": "SDG Tracker" },
{ "label": "Goal 1: No poverty" }
]
```
We then automatically choose a color for the breadcrumbs out of `[white, blue]` depending on the `cover-color`, which is just a list of 17 constant colors at the moment.
TODOs:

feat(gdocs): breadcrumbs

---

adminSiteServer/apiRouter.ts

Fixes an issue we [encountered on Bugsnag](https://app.bugsnag.com/our-world-in-data/grapher-admin/errors/64aec7936152c900082923b7?event_id=64aec79300becbce03460000&i=sk&m=oc).

fix: don't throw upon saving grapher without dimensions

---

adminSiteClient/GdocsSlug.tsx
adminSiteClient/gdocsValidation.ts
adminSiteServer/mockSiteRouter.tsx
baker/SiteBaker.tsx
packages/@ourworldindata/utils/src/Util.test.ts
packages/@ourworldindata/utils/src/Util.ts

Resolves #2424
https://ptolemy-owid.netlify.app/sdgs/test
https://ptolemy-owid.netlify.app/sdgs/energy
~Noticed in the [mockSiteRouter](https://github.com/owid/owid-grapher/blob/f06f445a02368edd59e3a9c493c89d98adaaf249/adminSiteServer/mockSiteRouter.tsx#L249C20-L249C20) that we already had this behaviour, so I extended it to work for baked gdocs, too.~
There's no UNIQUE constraint on slugs at the moment, presumably because we didn't want to initiate the slug with the google ID (the only unique value that we're guaranteed to have when first saving the entry in the DB)
But it might be nice to add that in at some point.

🎉 Allow for slashes in gdoc slugs for SDG subdirectory

---

packages/@ourworldindata/utils/src/owidTypes.ts
site/css/colors.scss
site/gdocs/centered-article.scss
site/gdocs/utils.tsx

This changes the default color from a bright yellow to a more subtle blue. We would like to use this color for the SDG pages, and think it makes sense as the default generally for all articles, although we may revisit this at some point. 
See Marwa's comment on it in slack [here](https://owid.slack.com/archives/C040429G2SD/p1689233175622379).

Change default header background color for articles 

---

baker/SiteBaker.tsx
db/model/Gdoc/Gdoc.ts

A blindspot in the baking process was leading to _every_ grapher, published document, and image being embedded in every gdoc page.
After publishing the SDG pages, this finally ballooned the size of this data over ~4.5MB, which was when Twitter stopped previewing our pages to extract the `twitter:image` meta tag.
This PR adds three methods to the `Gdoc` class that return the identifiers of its attachments (linked document IDs, linked chart slugs, linked image filenames) and uses that to filter down the pre-fetched dictionaries we were previously attaching the entirety of.

🐛 Only attach referenced metadata to the window._OWID_GDOC_PROPS json

---

package.json
site/owid.entry.ts
yarn.lock

We have a free trial for bugsnag performance monitoring which looks very useful for our switch to serving data directly to the client from S3. This PR adds the required library and enables sending preformance data to Bugsnag

:tada: enable bugsnag performance monitoring

---

baker/GrapherBaker.tsx

Bakes indicators used in explorers.
Gets a list of indicators that are currently used in explorers from the `explorer_variables` table that is created in https://github.com/owid/owid-grapher/pull/2431 and populated in https://github.com/owid/automation/pull/8

fix: bake indicators used in explorers

---

baker/SiteBaker.tsx
db/migration/1689019238688-LinkQueryString.ts
db/model/Gdoc/Gdoc.ts
db/model/Link.ts
packages/@ourworldindata/utils/src/owidTypes.ts
site/gdocs/Chart.tsx
site/gdocs/ProminentLink.tsx
site/gdocs/utils.tsx

Our `posts_gdocs_links` table wasn't tracking query strings or hashes. 
This meant they would get stripped if you were using `useLinkedChart` (e.g. in `LinkedA` or `ProminentLink`)
This adds those two columns to the table and passes them through to the FE so that `useLinkedChart` works correctly.
It also updates `Chart.tsx` to use `useLinkedChart` so that referencing grapher URLs that have redirects will resolve to the correct URL.
[Document to test with](https://docs.google.com/document/d/1MfJkgmcH8-wM0Rd4AcksSrGaw6Hh4Uyrx2aouGge3gM/edit)

Track querystrings and hashes, fix grapher embeds with old slugs

---

db/migration/1689156258161-AddMissingSchemaURLsToConfigs.ts
packages/@ourworldindata/grapher/src/core/Grapher.jsdom.test.ts
packages/@ourworldindata/grapher/src/core/Grapher.tsx
packages/@ourworldindata/grapher/src/core/GrapherConstants.ts
packages/@ourworldindata/grapher/src/core/GrapherInterface.ts
packages/@ourworldindata/grapher/src/schema/README.md

We recently introduced the `$schema` field in Grapher configs that points to the json schema that the config is checked against. This PR makes Grapher aware that the schema field exists such that:
- New charts are being assigned a schema
- Updated charts keep their schema
The `$schema` property is special because we always want it to be present, even if it is the default. (Grapher doesn't usually include default values in configs.) This means that we loose the beauty of having an empty Grapher serialize to an empty object :(
Aside: I called the new Grapher property `$schema` (with `$`) to make it clear that this maps to the `$schema` config field but I can see how that might be controversial.

Add schema property to Grapher

---

packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.tsx
packages/@ourworldindata/grapher/src/core/Grapher.tsx
packages/@ourworldindata/grapher/src/dataTable/DataTable.tsx

Displays header and footer when on the Table tab
- Rendering the table is moved into the `CaptionedChart`
- The data table is rendered into the chart area, similar to a map or a chart

enhance(table): display header and footer

---

packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.tsx
packages/@ourworldindata/grapher/src/controls/Controls.tsx
packages/@ourworldindata/grapher/src/core/Grapher.jsdom.test.ts
packages/@ourworldindata/grapher/src/core/Grapher.tsx
packages/@ourworldindata/grapher/src/core/GrapherConstants.ts
packages/@ourworldindata/grapher/src/core/GrapherInterface.ts
packages/@ourworldindata/grapher/src/footer/FooterManager.ts
packages/@ourworldindata/grapher/src/mapCharts/MapChartConstants.ts
packages/@ourworldindata/utils/src/Util.ts
packages/@ourworldindata/utils/src/index.ts

Refactor that prepares for a rearrangement of the chart layout.
Two things have been done:
- "Normal" tabs (future content switchers, i.e. table/map/chart) are more clearly separated from overlay tabs (sources, download)
- The `FooterControls` component (including the tab panel and timeline) has been moved into `CaptionedChart`
The `CaptionedChart` component now renders everything inside the Grapher frame, from top to bottom:
[Chart title]
[Chart subtitle]
[Controls]
[Chart area]
[Sources & Notes]
[Timeline]
[Tabs]

refactor(grapher): prepare for rearranging the chart layout

---

site/gdocs/OwidGdocHeader.tsx
site/gdocs/centered-article.scss

As you already noticed, ike, there's some overflowing of the breadcrumbs into nothingness on small screens.
This adds a positioning logic that makes breadcrumbs take as much space as they need, while still maintaining the overall layout.
With one line: 
With two lines:

enhance: refine breadcrumb positioning logic

---

baker/algolia/indexChartsToAlgolia.ts
baker/algolia/indexToAlgolia.tsx

So, we have this chart https://owid.cloud/admin/charts/6061/edit which has lots and lots of `availableEntities` in the database, and which was causing our Algolia updates to fail because the max record size is 20,000 bytes.
I opted to just include an empty `availableEntities` array in this case for now to fix; `availableEntities` is the least important property anyway.

fix(algolia): fix chart indexing failure

---

db/migrateWpPostsToArchieMl.ts

This fixes the first part of #2487, namely the fact that WP->Gdoc migration queue stops if there is an exception. With this PR, if migrating a post leads to an exception, this exception is no longer immediately re-thrown but instead collected and the remaining items processed. In the end we print the exceptions and throw one exception to make the status code non-zero.

:bug: a single failing WP->Gdoc migration should not stop the entire queue

---

packages/@ourworldindata/grapher/src/lineCharts/LineChart.tsx
packages/@ourworldindata/grapher/src/mapCharts/MapTooltip.scss
packages/@ourworldindata/grapher/src/mapCharts/MapTooltip.tsx
packages/@ourworldindata/grapher/src/scatterCharts/ScatterPlotChart.tsx
packages/@ourworldindata/grapher/src/stackedCharts/MarimekkoChart.tsx
packages/@ourworldindata/grapher/src/stackedCharts/StackedDiscreteBarChart.tsx
packages/@ourworldindata/grapher/src/tooltip/Tooltip.scss
packages/@ourworldindata/grapher/src/tooltip/Tooltip.tsx
packages/@ourworldindata/grapher/src/tooltip/TooltipContents.tsx
packages/@ourworldindata/grapher/src/tooltip/TooltipProps.ts

The PR cleans up some lingering issues with the new tooltip component:
1. Improved specificity for dimming out parentheticals in entity names
- the previous regex would greedily include anything from the first `(` character to the `)` at the end of the line, even if the parenthetical was followed by non-parenthesized text <br><img width="323" alt="image" src="https://github.com/owid/owid-grapher/assets/469523/365767fa-20d2-450e-b1b7-f070aa00d0c2">
1. Scatterplots that plot a single indicator on both axes to compare different years now use the 'range'-style tooltip to show the change over time
- http://staging-site-tooltips-misc-bugfixes/grapher/homicide-rate-1990-vs-2019 <br> <img width="286" alt="image" src="https://github.com/owid/owid-grapher/assets/469523/ca17414a-e4ed-42a7-b722-c3997e …

Miscellaneous Tooltip Bugfixes

---

packages/@ourworldindata/grapher/src/tooltip/Tooltip.scss
packages/@ourworldindata/grapher/src/tooltip/Tooltip.tsx

The `notice` class used within the tooltip is getting caught up in a broad rule set in `content.scss` for `.article-content .notice`. This PR renames the tooltip's classes to avoid the collision.

:bug: (css): fix selector collision with site styles

---

packages/@ourworldindata/grapher/src/sourcesTab/SourcesTab.tsx

Fixes #2458
Simply remove the edit link for datasets if there is not a database dataset id to edit.

:bug: remove dataset edit link for explorers with FASTT in tsv

---

db/model/Gdoc/gdocToArchie.ts

The same fix as https://github.com/owid/owid-grapher/pull/2429 but for the other syntax that we're manually converting atm.
We'll need to keep this in mind when implementing https://github.com/owid/owid-grapher/issues/2468 as well.

🐛 fix lists breaking when following formatting tags

---

baker/algolia/configureAlgolia.ts
baker/algolia/indexToAlgolia.tsx
site/search/searchTypes.ts

Two things here:
- When Ike first wrote gdocs indexing to Algolia, there were only articles. Now there's also topic pages, so treat them as such.
The other two changes only affect the Algolia dashboard for now, and make it a bit easier to figure out what's going on from the dashboard:
- We now include a `documentType` field in the index, which can be one of "gdoc", "wordpress", "country-page".
- It is never surfaced anywhere, but I included it in facet-able attributes so we can filter by it in the Algolia dashboard.
- The other tiny change in here is adding a `afterDistinct` to facet-able attributes; this makes it so the result counts are reflecting reality (because we're now counting articles that match, not chunks that match)

enhance(algolia): index gdoc topic pages as such

---

site/Lightbox.tsx

The [recent fix for filenames with spaces in them](https://github.com/owid/owid-grapher/pull/2497/files) introduced a sneaky little bug to `runLightbox` causing [lightbox views not to work](https://ourworldindata.org/limits-personal-experience) in Gdocs.
Extracting the src for the image from `img.src` automatically URI encodes the output
So when we changed `<Image />` to automatically URIEncode whichever `imgSrc` was passed to it, we were _double_ encoding the string in the cases where it was coming from `img.src`
`getAttribute` doesn't automatically URI encode strings, so we still need to make sure those strings are encoded.
https://github.com/owid/owid-grapher/assets/11844404/b66b2c33-3600-45ac-810b-005a41a55943
To test this behaviour you can run the following in your browser's console …

🐛 fix double-URI-encoding of image src in lightbox

---

explorer/Explorer.tsx
packages/@ourworldindata/grapher/src/core/Grapher.tsx
packages/@ourworldindata/grapher/src/facetChart/FacetChart.tsx
site/multiembedder/MultiEmbedder.tsx

Fixes #1929 by using `ResizeObserver` to observe size changes of both graphers and explorers.
Similar to #2002 back in the day, this is changing a critical code path in the loading of graphers/explorers, but all went well back then so let's hope it does now, too 🙏🏻 
A cool benefit actually is that ResizeObservers fire only when necessary: If the window size changes but the size of the grapher component is unaffected, then the callback doesn't fire at all.
TODOs:
- Yes it is, and it has the added benefit that it resizes immediately upon orientation change on mobile
- Tested in Firefox 61 and Safari 12

✨ : use ResizeObserver to observe Grapher/Explorer container size

---

adminSiteClient/EditorFeatures.tsx

- Problem: The data missing section does not show up for [this draft chart](https://staging.owid.cloud/admin/charts/6457/edit)
- Reason: The chart has a single entity, but the data missing section only shows up for charts with multiple entities
- Solution:
- For line charts, discrete bar charts and stacked discrete bar charts, it makes sense to show the data missing section only if there are multiple entities
- But for stacked area and stacked bar charts this is too restrictive as the data missing strategy not only shows/hides entities but also has an effect on visible charts

Always show missing data section in the admin for stacked area/bar charts

---

.github/workflows/sync-grapher-schema-to-digital-ocean.yml
devTools/schema/generate-default-object-from-schema.ts
devTools/schema/tsconfig.json
packages/@ourworldindata/grapher/src/schema/grapher-schema.003.yaml
tsconfig.json

Discussion on [Slack](https://owid.slack.com/archives/C04VBQ00HQR/p1687879630078009)
This PR updates the GitHub action that syncs grapher schemas to DO. It creates an additional JSON file named `grapher-schema.default.{XXX,latest}.json` that is the default grapher config object derived from the current schema. The default grapher object is then available under `https://files.ourworldindata.org/schemas/grapher-schema.default.{XXX,latest}.json`.
I want to use the default grapher config object to create an additional column in the Datasette charts table, maybe named `configWithDefaults`, that fills in missing values with defaults from our schema. See: https://github.com/owid/owid-datasette/pull/19
- Arrays are ignored when creating the default object. For example, some properties of items in …

enhance(schema): sync default grapher config to digital ocean

---

db/wpdb.ts

🐛 fix duplicates in related charts on grapher pages, alphabetise

---

packages/@ourworldindata/utils/src/MarkdownTextWrap/parser.test.ts
packages/@ourworldindata/utils/src/MarkdownTextWrap/parser.ts

Fixes #2318.
Changes it so parens and brackets (`()[]`) are always consumed a single token at a time, and never as part of a word. This fixes the underlying issue.
The tokens we get out of that are now slightly different - as you can see in the one test case I had to adapt - but that shouldn't make any difference when rendered.

fix(md-parser): can parse a link inside parens

---

packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.scss
packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.tsx
packages/@ourworldindata/grapher/src/controls/ActionButtons.scss
packages/@ourworldindata/grapher/src/controls/ActionButtons.tsx
packages/@ourworldindata/grapher/src/controls/ContentSwitchers.scss
packages/@ourworldindata/grapher/src/controls/ShareMenu.scss
packages/@ourworldindata/grapher/src/core/grapher.scss
packages/@ourworldindata/grapher/src/footer/Footer.scss
packages/@ourworldindata/grapher/src/footer/Footer.tsx
packages/@ourworldindata/grapher/src/header/Header.scss

Updates the layout of the footer to match the new designs.
This PR also does a refactor:
- Component-specific CSS in CaptionedChart.scss is moved into individual files that are colocated with the corresponding components, e.g. `Header.scss`, `Footer.scss`, etc
- `renderStatic` has been removed in favour of a sub-class `StaticFooter` that extends Footer, since the interactive and the static version of the footer differ significantly (I kept the static footer as is for now)

enhance(footer): update footer layout

---

adminSiteClient/EditorMapTab.tsx
adminSiteClient/VariablesAnnotationPage.tsx
db/migration/1690810237148-RemoveMapVariableId.ts
packages/@ourworldindata/grapher/src/core/Grapher.jsdom.test.ts
packages/@ourworldindata/grapher/src/core/GrapherInterface.ts
packages/@ourworldindata/grapher/src/mapCharts/MapConfig.test.ts
packages/@ourworldindata/grapher/src/mapCharts/MapConfig.ts
packages/@ourworldindata/grapher/src/schema/grapher-schema.003.yaml

Gets rid of some legacy conversion code.
I went for `columnSlug` over `variableId` because it's more flexible in general, and can in theory be used in explorers, too.

migrate: get rid of `$.map.variableId` in favor of `$.map.columnSlug`

---

explorer/Explorer.tsx

- Explorers try to persist the current tab
- But if the current tab does not exist for the chart that the user switched to, then by default the first tab in `availableTabs` is shown
- This used to be `chart` but now it's `table`
- Hence the failing test

test(explorer): fix failing explorer test

---

baker/SiteBaker.tsx

This should hopefully fix the staging server baking issues we've had lately

:hammer: disable chunking of images as a band aid for baking issues

---

adminSiteClient/DatasetEditPage.tsx
adminSiteClient/Forms.tsx
adminSiteClient/VariableEditPage.tsx
adminSiteServer/apiRouter.ts

Disable all variable metadata fields. These fields should be only set in ETL / fast-track, otherwise we risk overwriting manual updates by automatic ETL run.
I didn't disable "Redistribution is prohibited" field for dataset. We don't have that setting in ETL (therefore we don't overwrite it) and I thought it could be useful? We could also move it to ETL and remove the `Update` button altogether.

:sparkles: Disable variable metadata fields in admin

---

packages/@ourworldindata/grapher/src/core/GrapherAnalytics.ts
settings/clientSettings.ts
site/CookieNotice.tsx
site/CookiePreferencesManager.tsx
site/Head.tsx
site/blocks/CookiePreferences.scss
site/blocks/CookiePreferences.tsx
site/css/cookie-notice.scss
site/owid.entry.ts
site/search/searchClient.ts

Resolves #2441.
[A detailed description of what changes is in Notion.](https://www.notion.so/owid/2023-07-26-Proposed-analytics-behaviour-f358d586378b48819665362293d9bb87?pvs=4)
TODOs:
- I think the current behavior there could be confusing, because the "Save preferences" button just disappears and it isn't clear that they are in fact persisted automatically. 
TODOs when deploying:

feat: change analytics flow to opt-in; use cookie-less tracking otherwise

---

baker/SiteBaker.tsx

Revert to using 2 workers for baking images and add retries. 
Performance:
1 worker: 275s
2 workers: 200s
3 workers: 183s

:bug: add retries to bakeDriveImages

---

baker/GrapherBaker.tsx
db/model/Variable.ts

Right before baking grapher charts we check the existence of about 7000 variables that we use in charts. That means firing 2 * 7000 requests to S3 to ensure they all exist. This can take some time (>1min) and sometimes lead to a connection error.
Since we haven't run into any non-existing variables, it's probably safe to skip this step. Bugsnag should cover us if there are client errors with missing data.
EDIT: This is becoming increasingly annoying as we get more Buildkite fails. Either we merge this, or we start chunking it (which might slow it down).

:hammer: remove existence validation of data & metadata files on S3

---

packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.tsx

Fixes an issue where the entire controls row (including content switchers) was not being rendered when on the map or table tab

fix(grapher): prevent content switchers from being hidden

---

site/NewsletterSubscription.tsx
site/SiteNavigation.scss
site/SiteTools.tsx
site/css/mixins.scss
site/css/newsletter-subscription.scss
site/owid.scss

- bring back subscribe button to site tools in the bottom right corner ([slack](https://owid.slack.com/archives/CLDM2AWCD/p1691577698885519))
- harmonize width of popups
- fix feedback popup height on shorter screens
- hide "Jobs" CTA

feat(newsletter): bring back subscribe button to site tools

---

baker/GrapherBakingUtils.ts
baker/GrapherImageBaker.tsx
baker/SiteBaker.tsx
baker/siteRenderers.tsx

Multiple optimisations in here:
- Explorers don't instantiate a `Grapher` object for each `grapherId` contained in it, which then requires downloading the data and metadata file for each of them [150s -> 30s]
- Rudimentarily parallelise `bakeEmbeds` some more by using `p-map` in a single thread [575s -> 412s on my local machine; mostly relevant for a first-time build]

perf: improve performance of baking

---

packages/@ourworldindata/grapher/src/core/Grapher.tsx
site/CookiePreferencesManager.tsx
site/owid.entry.ts

Fixes a [Bugsnag error](https://app.bugsnag.com/our-world-in-data/our-world-in-data-website/errors/64b67b9d62bfc7000803bd76).
If any OWID page is embedded within a sandboxed iframe without the `allow-same-origin` permission, then any attempt to access `document.cookie` will throw an exception that is currently unhandled.
Such a iframe snippet could look like this: `<iframe src="https://ourworldindata.org/poverty" sandbox="allow-scripts" />`
Demo CodeSandbox: https://codesandbox.io/s/owid-sandboxed-iframe-6vtmvf?file=/index.html

fix: check for cookie access before accessing them

---

baker/Deployer.ts
baker/SiteBaker.tsx

Attempt to fix error we get from deploy queue
```
0|live-deploy-queue  | 2023-08-10T08:53:49: RangeError: Invalid array length
0|live-deploy-queue  | 2023-08-10T08:53:49:     at ProgressBar.render (/home/owid/live/node_modules/progress/lib/node-progress.js:160:14)
0|live-deploy-queue  | 2023-08-10T08:53:49:     at ProgressBar.tick (/home/owid/live/node_modules/progress/lib/node-progress.js:97:8)
0|live-deploy-queue  | 2023-08-10T08:53:49:     at SiteBaker.flushCache (/home/owid/live/baker/SiteBaker.tsx:847:26)
0|live-deploy-queue  | 2023-08-10T08:53:49:     at SiteBaker.bakeAll (/home/owid/live/baker/SiteBaker.tsx:750:14)
0|live-deploy-queue  | 2023-08-10T08:53:49:     at bakeAndDeploy (/home/owid/live/baker/DeployUtils.ts:47:25)
0|live-deploy-queue  | 2023-08-10T08:53:49:     at …
```

:bug: hotfix progress bar issue

---

baker/SiteBaker.tsx

I often run `yarn buildLocalBake --steps charts` when debugging baking. The annoying thing is that it always runs `removeDeletedPosts` step.
Is it possible to make it optional? There's a comment saying `// There are 3 non-optional steps: flushCache, removeDeletedPosts, and flushCache (again)`, but I don't get why `removeDeletedPosts` is non-optional.

:sparkles: make step removeDeletedPosts optional

---

explorer/ExplorerProgram.ts
explorerAdminClient/ExplorerCreatePage.scss

resolves #2504
Adds a warning for mixed-content explorers that use Grapher IDs as well as CSV data files to create charts. We plan to drop support for mixed-content explorers soon-ish.

enhance(explorer): add warning for mixed-content explorers

---

explorer/Explorer.tsx
packages/@ourworldindata/core-table/src/CoreTable.test.ts
packages/@ourworldindata/core-table/src/CoreTable.ts
packages/@ourworldindata/core-table/src/Transforms.ts

Resolves #2514
- Adds a `duplicate` transform that is useful in explorers
- The duplicate transform is special: It operates on data values and touches column definitions
- For example, a column with transform `duplicate my-slug` inherits all metadata (and data) from the `my-slug` column

feat(explorer): add duplicate transform

---

baker/siteRenderers.tsx

The new grapherConfigETL on the variables table holds the grapher config that is written in the ETL (e.g. it is filled for the dummy indicator in this YAML file). This partial grapher config is not used yet in explorers. This PR adds this capability.

Use grapherConfigETL in explorers

---

packages/@ourworldindata/grapher/src/controls/ActionButtons.tsx
packages/@ourworldindata/grapher/src/core/Grapher.tsx
site/gdocs/Chart.tsx

- show "Explore the data" button when embedded in gdoc articles (customised or not)
- show "Explore the data" button in iframes
- hide full-screen button in iframes

Show "Explore the data" button when embedded

---

wordpress/web/app/plugins/owid/owid.php

Loads nvm's yarn before running the postUpdateHook.
https://github.com/owid/owid-grapher/assets/13406362/569f33f6-d030-422a-b108-fca66c6f2a93
Somehow, setting up NVM_DIR and running `~/.nvm/nvm.sh` didn't do the trick, hence the sourcing of .bashrc. There is a return for non-interactive shells right after NVM loads so running .bashrc is equivalent to loading NVM.
Note: staging still has a system version of node/yarn in /usr/bin which gives false positives if not looking carefully at which version is running.
Bug report: [slack](https://owid.slack.com/archives/CQQUA2C2U/p1691140007969139)

fix(wp): load nvm to run postUpdateHook

---

adminSiteServer/mockSiteRouter.tsx
baker/SiteBaker.tsx
baker/siteRenderers.tsx
db/wpdb.ts
packages/@ourworldindata/utils/src/owidTypes.ts

Problem: topic page announcements in the immediate newsletter are not sufficiently engaging.
Solution: remove them from the feed used by Mailchimp to send new issues of the immediate newsletter automatically. We still want to provide the full feed for RSS subscribers, so this PR creates an additional atom feed for Mailcihmp only, from which topic pages are excluded.
Staging feed URLs:
- http://staging-site-newsletter-no-topic-pages/atom-no-topic-pages.xml
- http://staging-site-newsletter-no-topic-pages/atom.xml

Remove topic page annoucements from automated immediate newsletter

---

site/gdocs/OwidGdoc.tsx

Fixes the issue where articles refer to themselves as topic pages (see: https://ourworldindata.org/optimism-and-pessimism#article-citation)

🐛 Make footer citation text change per OwidGdoc.content.type

---

adminSiteClient/admin.scss
adminSiteClient/styles/react-tag-autocomplete.scss
packages/@ourworldindata/grapher/src/controls/entityPicker/EntityPicker.scss
packages/@ourworldindata/grapher/src/core/grapher.scss
packages/@ourworldindata/grapher/src/lineLegend/LineLegend.tsx
site/PostCard/PostCard.scss
site/SiteFooter.tsx
site/css/footer.scss
site/owid.scss

Fixes a few spots where we had specified font weights that we didn't support that [now look wrong with the "correct" font weight.
](https://github.com/owid/owid-grapher/pull/2518)
e.g.

Font weight fixes

---

packages/@ourworldindata/grapher/src/controls/ActionButtons.scss
packages/@ourworldindata/grapher/src/controls/ActionButtons.tsx
packages/@ourworldindata/grapher/src/mapCharts/MapChart.tsx
packages/@ourworldindata/grapher/src/modal/DownloadModal.scss

- prevent grapher to overflow in admin
- add padding that was missing (visible after scroll)
- only label action buttons if there is enough space

Various bug fixes for Grapher redesign project

---

.eslintignore
baker/redirects.ts
packages/@ourworldindata/grapher/src/controls/globalEntitySelector/GlobalEntitySelector.tsx
packages/@ourworldindata/utils/src/Util.ts
packages/@ourworldindata/utils/src/index.ts
packages/@ourworldindata/utils/src/owidTypes.ts
packages/@ourworldindata/utils/src/regions.test.ts
packages/@ourworldindata/utils/src/regions.ts
public/detect-country.js

Try this out at https://staging-owid.netlify.app/covid-vaccinations#select-countries-to-show-in-all-charts.
Uses https://detect-country.owid.io for country detection, rather than the existing Netlify-based redirects.
This is mostly part of #2061 since we can't use country-based redirects any more with CF Pages, but I thought to frontload it already.
The worker returns a bit more information which could be useful in the future (incl. regions that the user is in).
We're putting a 301 redirect so we can still use the hardcoded, relative `/detect-country` URL rather than needing to pass a setting forward into utils, which would be hard to do.
I also deleted some very outdated redirects while I was at it.

enhance: use new detect-country worker to detect country

---

baker/GDriveImagesBaker.tsx
baker/SiteBaker.tsx

* DigitalOcean spaces return `etag` in the header
* Save this etag in a sidecar `image_filename.etag`
* When baking gdrive images, send this etag as `If-None-Match` and skip image baking if we get 304 back
* (DigitalOcean Spaces return etag with extra quotes, we need to strip them)
Can be tested with `yarn buildLocalBake --steps gdriveImages`.
I kept it in the `SiteBaker.tsx` file, but maybe it's time to move gdrive image baking code to its own file.

:sparkles: cache gdrive images etags to improve resizing speed

---

packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.tsx
packages/@ourworldindata/grapher/src/controls/ContentSwitchers.scss
packages/@ourworldindata/grapher/src/controls/ContentSwitchers.tsx
packages/@ourworldindata/grapher/src/core/Grapher.tsx
packages/@ourworldindata/grapher/src/core/GrapherConstants.ts
packages/@ourworldindata/grapher/src/core/grapher.scss
packages/@ourworldindata/grapher/src/footer/Footer.tsx
packages/@ourworldindata/grapher/src/fullScreen/FullScreen.scss
packages/@ourworldindata/grapher/src/fullScreen/FullScreen.tsx
packages/@ourworldindata/grapher/src/header/Header.tsx

- Doesn't take up all the space so that full-screen mode can be dismissed by clicking outside of the grapher component
- On smaller screens, full-screen mode uses all the space that is available
- If the screen is large, use ideal bounds rather than using up all space
- PR also includes a refactor of the `sizeVariant`

Grapher redesign: Improve full-screen mode

---

baker/SiteBaker.tsx

`bakeAssets` step is pruning all files from the bake folder. Exclude `images/published` so that they don't have to be downloaded again in case their etags match.

:bug: don't delete images folder when baking

---

adminSiteClient/TagEditPage.tsx
adminSiteServer/apiRouter.ts
db/migration/1692801236245-AddIsTopicToTag.ts

Add `isTopic` property to tags to be able to differentiate topic tags from non-topic tags.
This is useful for the [chart tagging effort](https://www.notion.so/owid/2023-08-22-Tagging-all-our-content-26b70903a88f4115bab88eb1c8d4b891?pvs=4#23834c1510bd4e73ba86a76a23fa5d13) where we need to identify charts that are not tagged with topic tags.

feat(admin): add isTopic as property of a tag

---

packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.tsx
packages/@ourworldindata/grapher/src/core/grapher.scss
packages/@ourworldindata/grapher/src/dataTable/DataTable.jsdom.test.tsx
packages/@ourworldindata/grapher/src/dataTable/DataTable.sample.ts
packages/@ourworldindata/grapher/src/dataTable/DataTable.scss
packages/@ourworldindata/grapher/src/dataTable/DataTable.tsx
packages/@ourworldindata/grapher/src/timeline/TimelineComponent.scss

Grapher redesign: Data table

---

packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.tsx
packages/@ourworldindata/grapher/src/core/Grapher.tsx
packages/@ourworldindata/grapher/src/fullScreen/FullScreen.scss
packages/@ourworldindata/grapher/src/fullScreen/FullScreen.tsx
packages/@ourworldindata/grapher/src/modal/EmbedModal.scss
packages/@ourworldindata/grapher/src/modal/EmbedModal.tsx
packages/@ourworldindata/grapher/src/modal/Modal.scss

- When in full-screen mode and a modal is open, dismiss the modal when clicked outside of Grapher instead of exiting full-screen mode
- In full-screen mode, if a modal is open, make the overlay cover the whole screen (not only Grapher itself)
- Add feedback when copying the code snippet was successful

Grapher redesign: Bug fixes

---

adminSiteServer/apiRouter.ts
db/model/Variable.ts
packages/@ourworldindata/utils/src/Util.test.ts
packages/@ourworldindata/utils/src/Util.ts

Data and metadata might get cached for 5 minutes by CF worker at the moment. This is typically not a problem, but it was annoying when I was fine-tuning the description in admin coming from ETL. This PR adds `nocache` header and ~switches to redirects for more transparency (we could even remove the admin variables endpoint and fetch directly from Data API, but I was afraid of side effects).~
Also adds exponential backoff to `retryPromise` which seems to have some effect [against 502 errors](https://github.com/owid/owid-grapher/issues/2585).

:hammer: use nocache when fetching variable data & metadata in admin

---

packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.scss
packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.tsx
packages/@ourworldindata/grapher/src/controls/ContentSwitchers.scss
packages/@ourworldindata/grapher/src/controls/ContentSwitchers.tsx
packages/@ourworldindata/grapher/src/core/Grapher.tsx
packages/@ourworldindata/grapher/src/core/GrapherConstants.ts
packages/@ourworldindata/grapher/src/dataTable/DataTable.tsx
packages/@ourworldindata/grapher/src/footer/Footer.tsx
packages/@ourworldindata/grapher/src/footer/FooterManager.ts
packages/@ourworldindata/grapher/src/header/Header.tsx
packages/@ourworldindata/grapher/src/header/HeaderManager.ts
packages/@ourworldindata/grapher/src/modal/DownloadModal.scss
packages/@ourworldindata/grapher/src/modal/DownloadModal.tsx
packages/@ourworldindata/grapher/src/modal/SourcesModal.scss
packages/@ourworldindata/utils/src/Util.ts
packages/@ourworldindata/utils/src/index.ts
site/css/chart.scss

Improves Grapher charts on mobile.
- hides chart/map/table label on mobile
- increases the minimum height from 480px to 540px
- makes control row a little smaller
- improves Download modal on smaller screens

Grapher redesign: Improve mobile view

---

packages/@ourworldindata/grapher/src/sourcesTab/SourcesTab.tsx

When updating the sources tab I wanted to drop undefined from an array but instead used the function that operates on objects - this tiny PR fixes this so that the sources tab shows citationProducer again

:bug: fix citationProducer missing in sources tab

---

explorerAdminClient/ExplorerCreatePage.tsx

Fixes an issue where the HotTable's context menu would disappear immediately after opening it, making it impossible to interact with it. (Video posted on [Slack](https://owid.slack.com/archives/C46U9LXRR/p1693396303506069))
What appears to be the reason is that `program. whyIsExplorerProgramInvalid` refreshes every few seconds (I don't know why), which causes the whole render function to re-run and `<HotTable />` to re-render. When `<HotTable />` is re-rendered, the context menu is closed.
For now, I simply commented out the piece of code that causes the problem. I'll look at it again when I have some more time.

hot fix(explorer): prevent HotTable context menu from disappearing

---

packages/@ourworldindata/grapher/src/controls/ContentSwitchers.scss
packages/@ourworldindata/grapher/src/controls/ContentSwitchers.tsx
packages/@ourworldindata/grapher/src/core/Grapher.tsx
packages/@ourworldindata/grapher/src/dataTable/DataTable.jsdom.test.tsx
packages/@ourworldindata/grapher/src/dataTable/DataTable.tsx
packages/@ourworldindata/grapher/src/footer/Footer.tsx
packages/@ourworldindata/grapher/src/timeline/TimelineComponent.scss

Collection of fixes and improvements
- remove line breaks from sources text
- underline "CC BY" link in static charts
- rename "Region" to "Other" in data tables (for non-country entities)
- expose grapher size as css classes
- hide separators between tabs on hover
- increase timeline height on hover

Grapher redesign: Papercuts

---

explorer/Explorer.tsx
packages/@ourworldindata/grapher/src/controls/entityPicker/EntityPicker.tsx
packages/@ourworldindata/grapher/src/controls/entityPicker/EntityPickerConstants.ts

Fixes an issue where clicking the entity picker's sort icon would also update the metric to its default value ("Relevance")

fix(explorer): prevent metric from being updated when entities are sorted

---

site/blocks/KeyInsights.scss
site/gdocs/AllCharts.scss
site/gdocs/Chart.scss
site/gdocs/Chart.tsx
site/gdocs/centered-article.scss
site/owid.scss

Sets the height of Grapher charts to the viewport height on smaller screens. Sometimes, the header and navigation are taken into account so that the full chart (and sometimes the navigation) are visible on the screen.
Updated components include:
- Stand-alone charts
- Charts in Key Insights block
- Charts in the All Charts block
- Charts in a Chart Story
Charts in the `Scroller />` component continue to have a fixed height.

Grapher redesign: Resize chart height based on the viewport in gdoc articles (on mobile)

---

adminSiteServer/app.tsx
site/viteUtils.tsx

Resolves #2112.
This is deployed on _staging_, and you can also have a look at https://64ef4a4cb5a812071aa03532--staging-owid.netlify.app/, which points to this specific Netlify deploy (incidentally, Cloudflare Pages has a similar concept for "URLs for past deploys").
All paths that we include in header and footer now - i.e. stylesheets, scripts, and preload directives - now use relative URLs of the form `/assets/admin.mjs`.
Cleverly, `/assets` is now also an endpoint in the admin server, such that we can easily serve these assets on the admin server, too. This actually has the added benefit that "breaking" changes to the admin can now go live immediately; before this, we were in a situation that the admin backend and frontend didn't match up for several minutes while deploying, which …

feat: load assets using relative urls

---

package.json
site/owid.entry.ts
yarn.lock

Disables #2447 again.
We can always re-enable it in the future if needed again, but for now I don't think we gain much from it.

chore: disable bugsnag network performance monitoring

---

package.json
packages/@ourworldindata/core-table/package.json
packages/@ourworldindata/core-table/src/CoreTable.test.ts
packages/@ourworldindata/core-table/src/CoreTable.ts
packages/@ourworldindata/core-table/src/CoreTableColumns.ts
packages/@ourworldindata/core-table/src/CoreTableUtils.test.ts
packages/@ourworldindata/core-table/src/CoreTableUtils.ts
packages/@ourworldindata/core-table/src/OwidTable.ts
packages/@ourworldindata/core-table/src/index.ts
yarn.lock

While working on Cloudflare Workers, I realized that `CoreTable.complete` takes up a non-trivial amount of time.
Seeing that we only ever call `complete` with exactly 2 columns, and that the current implementation was written in a way that supports an arbitrary number of cols (which makes everything trickier), I rewrote it to only ever support 2 columns, but in a way more performant way.
I benchmarked this on https://ourworldindata.org/grapher/life-expectancy-vs-gdp-per-capita:
The two invocations of `complete()` took **385ms** before; and now take **85ms**. And that's on a very fast M2 Max; I expect the difference to be similarly large on other machines too.
Here's also a (manual) timing output for localhost:
```
http://localhost:3030/grapher/life-expectancy-vs-gdp-per-capita …
```

perf: rewrite CoreTable.complete to be more performant

---

adminSiteClient/Forms.tsx
db/model/Chart.ts

I suggest giving "unlisted" precedence over public parent tags, so marking a chart "Unlisted" is predictable and guarantees exclusion from /charts and searches.
Currently, charts tagged with "unlisted" can still be visible in search and on the /charts page. 
This is due to "unlisted" having a lower priority than the presence of public parent tags, which currently take precedence in determining visibility.
E.g.:
- unlisted + core-econ = congruent because core-econ is not a public tag
- unlisted + homicides = incongruent because homicides is a topic tag, and will take precedence over "unlisted".
As part of proj-tagging, we've [made sure that no chart tagged with "unlisted" also had a public parent tag](https://www.notion.so/owid/2023-08-22-Tagging-all-our-content-26b70903a88f4115bab88eb1c8d4 …

enhance(tag): give unlisted precedence over public tags for charts

---

baker/siteRenderers.tsx

The homepage is using the metadata from the WP posts even when there's a Gdoc override. This is mostly an issue for topic pages, where for site nav reasons, we still need to keep the WP post published.

🐛 use correct metadata on homepage featured posts

---

site/search/Autocomplete.tsx

We were getting many warnings logged to Bugsnag for the oldschool React issue with browser translation (https://github.com/facebook/react/issues/11538), to do with the `<Highlight>` component.
Translating search is a bit weird anyhow, since the user needs to enter the search terms in English (which they might not realize; but there's not much we can do about that), and highlighting terms also is based on the English text.
The solution I came up with here is also not very consistent because it translates "Featured searches", then doesn't translate the autocomplete entries, but does translate the results on the "full" search page.
But anyhow, that also works reasonably well and the underlying errors are fixed now at least.

fix(search): search copes better with browser translation

---

site/gdocs/OwidGdoc.tsx
site/gdocs/centered-article.scss
site/owid.entry.ts

Adds two buttons to make it easier to update articles from the published page, like we have for WordPress pages.
`position: absolute` (instead of `fixed`) so that it doesn't obscure the nav in the rare case you're logged in on mobile.

🎉 Add gdoc quick edit buttons for logged-in admins

---

adminSiteClient/EditTags.tsx
adminSiteClient/admin.scss
adminSiteClient/styles/react-tag-autocomplete.scss
adminSiteServer/apiRouter.ts
package.json
packages/@ourworldindata/utils/package.json
packages/@ourworldindata/utils/src/owidTypes.ts
yarn.lock

see [demo](https://owid.slack.com/archives/C014SGT6W9X/p1694539715117499)
- reduce guessing by seeing all tags available
- autofocus for speeding up keyboard filtering
- validate selection by pressing "esc"
- improved styles

Upgrade tag autocomplete + UX

---

packages/@ourworldindata/grapher/src/sourcesTab/SourcesTab.tsx
packages/@ourworldindata/utils/src/GdocsUtils.ts
packages/@ourworldindata/utils/src/index.ts
site/DataPageV2Content.tsx

This PR switches the rendering of text from Source in the sources tab of Grapher from HTML to markdown. This is the companion PR for [this PR in the ETL](https://github.com/owid/etl/pull/1422) that converts legacy HTML to markdown in sources.
This PR implements #2520

Render source fields as markdown instead of HTML

---

explorer/Explorer.tsx
packages/@ourworldindata/grapher/src/core/Grapher.tsx

This fixes #2633 but does it in a crude way by turning off all intro animations in explorers

:bug: crude fix for map color animation resulting in wrong colors

---

packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.tsx
packages/@ourworldindata/grapher/src/controls/Controls.tsx
packages/@ourworldindata/grapher/src/core/Grapher.tsx
packages/@ourworldindata/grapher/src/dataTable/DataTable.scss
packages/@ourworldindata/grapher/src/dataTable/DataTable.tsx

This PR adds a UI for #2602 to the Settings menu, fixes an alignment problem in multi-line table headers, and removes the spacebar keyboard shortcut for toggling full-screen mode in the interest of accessibility (i.e., not interfering with the default space/shift-space shortcuts for page-down/page-up)

Data table enhancements & layout fixes

---

explorer/Explorer.tsx
packages/@ourworldindata/grapher/src/controls/entityPicker/EntityPicker.tsx

Makes it so there's always the option to sort by entity name, even if that's not explicitly specified in `pickerColumnSlugs`.

enhance(explorer): always show an explicit "sort by name" option in explorer entity picker

---

packages/@ourworldindata/grapher/src/dataTable/DataTable.scss
packages/@ourworldindata/grapher/src/dataTable/DataTable.tsx

Moves the data column closer to the entity column for tables that have a single data column only, see [Figma](https://www.figma.com/file/X5mOEX8zULS6qyHocUYdmh/%5BProject%5D-Grapher-Charts-V2?type=design&node-id=1728-6461&mode=dev) for a design.
- This is done by setting a minimum width on the column, and a maximum width on the content within that column
- To find an appropriate maximum width, I need to know the width of the content (if the maximum width is smaller than the content, then the values wouldn't be aligned on the right)
- Instead of measuring the width of all displayed data values, I only measure the width of the minimum and the maximum value
I'd prefer a css-only solution but I couldn't think of one. @samizdatco feel free to edit/merge/close as you please.

Grapher redesign: Move single data column closer to the entity column

---

packages/@ourworldindata/grapher/src/footer/Footer.scss

The license and origin url should never wrap. Since we're not using TextWrap to render the license and origin URL, the license – in rare cases – incorrectly breaks into a second line.

Grapher redesign: prevent license from wrapping

---

explorer/Explorer.tsx

Fixes a data loading issue that only happens for mixed-content explorers that use grapher IDs as well as csv data to create charts.
- for csv data charts, `grapher.manuallyProvidedData` is true
- when switching to a grapher id chart, `grapher.manuallyProvidedData` was persisted
- as a result, no data would be downloaded for the chart (since grapher thinks the data is manually provided)

fix(explorer): fix data loading issue in mixed-content explorers

---

packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.tsx
packages/@ourworldindata/grapher/src/controls/Controls.tsx

Additional bugfixes:
- show the Align Axes toggle even if there is only one choice for the current Faceting Mode (meaning the mode switcher is hidden)
- show the controls row if either the ContentSwitcher or ≥1 of the Control elements are visible

Grapher redesign updates

---

adminSiteServer/apiRouter.ts
db/migration/1695651135934-IndexUpdatedAt.ts

I was encountering issues where the [GdocsIndexPage](https://github.com/owid/owid-grapher/blob/64753e3738cf19033fda6dd5c651473717950807/adminSiteClient/GdocsIndexPage.tsx#L101) wasn't loading for me due to an MySQL sort_buffer overflow:
```json
{
"code": "ER_OUT_OF_SORTMEMORY",
"errno": 1038,
"sqlMessage": "Out of sort memory, consider increasing server sort buffer size",
"sqlState": "HY001",
"index": 0
}
```
```sql
SELECT `Gdoc`.`id`                     AS `Gdoc_id`,
`Gdoc`.`slug`                    AS `Gdoc_slug`,
`Gdoc`.`content`                 AS `Gdoc_content`,
`Gdoc`.`published`               AS `Gdoc_published`,
`Gdoc`.`publicationcontext`      AS `Gdoc_publicationContext`,
`Gdoc`.`createdat`               AS `Gdoc_createdAt`,
`Gdoc`.`publishedat`             AS …
```

✨ index posts_gdocs.updatedAt

---

site/gdocs/AllCharts.scss
site/gdocs/Footnotes.tsx
site/gdocs/centered-article.scss
site/gdocs/topic-page.scss

A few topic page changes requested by Marwa, and a bug I noticed with refs in the topic page intro.

Site touchups

---

site/gdocs/OwidGdoc.tsx
site/owid.entry.ts

These links aren't confidential, but we've seen a small surge of people asking for permission to view the documents since introducing these admin links. Hopefully removing the URLs directly from the source will help quell that.

🎉 obfuscate gdoc links in baked articles

---

site/gdocs/OwidGdoc.tsx
site/owid.entry.ts

Pages that were coming from gdocs recently got a new a link to edit them. This a link had the id #admin. Unfortunately, this means that window.admin in grapher all of a sudden resolves to true on these pages, but this is the [(admittedly poorly constructed) check](https://github.com/owid/owid-grapher/blob/5b26bb0c0e7255b3b4c377df440f71c94e100c65/packages/%40ourworldindata/grapher/src/core/Grapher.tsx#L749) that grapher does to figure out if data should be loaded via the admin or from the data url location.

:bug: fix broken data loading in prod

---

packages/@ourworldindata/grapher/src/core/Grapher.tsx
packages/@ourworldindata/grapher/src/dataTable/DataTable.tsx
packages/@ourworldindata/grapher/src/modal/EntitySelectorModal.scss
packages/@ourworldindata/grapher/src/modal/EntitySelectorModal.tsx
packages/@ourworldindata/utils/src/regions.ts

Add feedback message when no entities could be found on search in the entity selector modal.
- The message is: _Nothing turned up. You may want to try using different keywords or checking for typos."_
- A more specific message is displayed when the search input is an actual country (and the entities are country-like): _There is no data for the country, region or group you are looking for._

Grapher redesign: Add feedback for empty search result in entity selector

---

packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.scss
packages/@ourworldindata/grapher/src/controls/ActionButtons.tsx
packages/@ourworldindata/grapher/src/core/Grapher.tsx
packages/@ourworldindata/grapher/src/core/grapher.scss
packages/@ourworldindata/grapher/src/footer/Footer.tsx
packages/@ourworldindata/grapher/src/fullScreen/FullScreen.tsx
packages/@ourworldindata/utils/src/owidTypes.ts

- improve footer layout on smaller screens
- prevent full-screen mode to be exited when interacting with options in settings drawer ([Slack](https://owid.slack.com/archives/C05S2V4D2HZ/p1694698070089929))
- ensure grapher frame is visible at all times

Grapher redesign: Bug fixes and improvements

---

packages/@ourworldindata/utils/src/GdocsConstants.ts

This RegEx was catching a spreadsheet link Hannah had included in the [article on deforestation](https://ourworldindata.org/deforestation) and causing Gdoc validation to complain about linking to an article that hadn't been registered.
This PR updates the RegEx to require the `/document/` resource be specified, and uses a more specific non-capturing group to handle the optional google account information that may be contained in the link.
To test, I extracted all the docs.google.com URLs we have in prod and ran them on [regex101.com](https://regex101.com). The spreadsheet URL was the only one that didn't match.
And here is the link working correctly now:

🐛 tighten gdoc regex to not match on sheets links

---

packages/@ourworldindata/grapher/src/fullScreen/FullScreen.scss

There is [an issue in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1610093) where our `getRelativeMouse` doesn't properly work in fullscreen mode, because `getScreenCTM()` doesn't factor in any transforms on the element.
Using flexbox fixes this, and in my view it also makes the centering code easier to grasp.

enhance: use flexbox to center full screen content

---

adminSiteClient/GdocsDateline.tsx
adminSiteClient/GdocsPublicationContext.tsx

Interacting with the gdocs date picker changes the underlying time, in addition to the visible date. This change makes it all the way to the atom feed, which is then interpreted by Mailchimp RSS-to-Email feature as a new article to be sent.
This happens in two instances.
1. Interacting with the date picker calendar, e.g. going from Oct 11, to Oct 10 and back to Oct 11:
```
publishedAt Wed Oct 11 2023 00:59:53 GMT+0100 (British Summer Time)
publishedAt Tue Oct 10 2023 01:59:53 GMT+0100 (British Summer Time)
publishedAt Wed Oct 11 2023 02:59:53 GMT+0100 (British Summer Time)
```
Notice how that third time is now 02:59:53 vs 00:59:53 originally.
2. Pressing the "Today" button sets the time to the current time
This PR fixes 1 and removes the "Today" button so that the time remains unchanged …

fix(gdoc): unstable publication time triggers duplicate Mailchimp newsletter

---

packages/@ourworldindata/grapher/src/controls/Controls.scss
packages/@ourworldindata/grapher/src/core/Grapher.tsx
packages/@ourworldindata/grapher/src/lineCharts/LineChart.tsx

Two bugfixes:
1. add back delay before un-hovering a line chart legend label when rapidly moving between entity names
2. provide a class-based switch for the control row button label hiding to use in browsers that don't yet support container queries

Grapher redesign updates (iii)

---

db/model/Gdoc/archieToGdoc.ts
packages/@ourworldindata/utils/src/owidTypes.ts
site/gdocs/OwidGdoc.tsx
site/gdocs/OwidGdocHeader.tsx

It doesn't make sense for institutional writing to be cited. This PR adds a `hide-citation` frontmatter field to hide the citation information at the bottom of documents. It also hides the link to that block in the header of articles. 
I repurposed the `citation` field, which no longer seemed to be used.
see https://owid.slack.com/archives/C03G5HF66DD/p1696318369852199

feat(gdocs): add hide-citation Archie field

---

baker/BuildkiteTrigger.ts
ops/buildkite/README.md
ops/buildkite/build-code
ops/buildkite/deploy-content
settings/serverSettings.ts

Move scripts from [ops repo](https://github.com/owid/ops/tree/main/templates/owid-cloudflare-prod) here. This makes the workflow easier as buildkite fetches owid-grapher repo, and any script changes will be reflected immediately without needing to redeploy lxc container.
Scripts `build-code` and `deploy-content` have barely changed.
There are two buildkite jobs that run this. One deploys content and is [triggered by deploy queue](https://buildkite.com/our-world-in-data/grapher-deploy-content-master) and the [second one](https://buildkite.com/our-world-in-data/grapher-deploy-code-master) builds code and then deploys content.
⚠️ This PR currently deploys `cloudflare-pages` branch from grapher. We should change everything to master before merging.

:honeybee: Ops scripts for Cloudflare Pages

---

packages/@ourworldindata/grapher/src/controls/ChartIcons.tsx
packages/@ourworldindata/grapher/src/controls/Checkbox.scss
packages/@ourworldindata/grapher/src/controls/settings/FacetYDomainToggle.tsx
packages/@ourworldindata/grapher/src/controls/settings/ZoomToggle.tsx

Addresses @marcelgerber's review notes

Grapher redesign updates (iv)

---

package.json
packages/@ourworldindata/grapher/package.json
yarn.lock

Move a grapher-specific dependency (`indefinite`) into the grapher package rather than keeping it in the repo root.

Grapher redesign updates (v)

---

baker/redirects.ts

we had a /feed to /atom.xml redirect but were missing /feed/ to also redirect in that style. When looking at the CF 404 pages we noticed that this url is hit a noticeable number of times.

:hammer: we had  a /feed to /atom.xml redirect but were missing /feed/

---

db/migration/1696940352033-PostsGdocsLinksLongerTargetField.ts

We ran into this with this [document](https://docs.google.com/document/d/1vkvQehkmXKV_mS2hFw1COZCGQYxC1aadis1-9WbHN9I/edit) and link
```
https://books.google.co.uk/books?id=hWlZTVgLmAkC&pg=PT172&lpg=PT172&dq=%E2%80%9CI+expect+you%E2%80%99re+keen+to+hear+what+effect+it+had+on+my+health,+this+decision+of+mine+to+leave?+Well,+no+sooner+had+I+left+behind+the+oppressive+atmosphere+of+the+city+and+that+reek+of+smoking+cookers+which+pour+out,+along+with+a+cloud+of+ashes,+all+the+poisonous+fumes+they%E2%80%99ve+accumulated+in+their+interiors+whenever+they%E2%80%99re+started+up,+than+I+noticed+the+change+in+my+condition+at+once.+You+can+imagine+how+much+stronger+I+felt+after+reaching+my+vineyards!+I+fairly+waded+into+my+food+%E2%80%93+talk+about+animals+just+turned+out+on+to+spring+grass!+So+by+now …
```

:hammer: make posts_gdocs_links.target TEXT type instead of varchar(2047)

---

db/syncPostsToGrapher.ts

Our WP article "Loneliness and Social Connection" (id: 29766) was referring to a reusable block that doesn't exist ``
This surfaced a bug with the grapher sync code where this tag was getting resolved to the entire text, which then caused a recursion until the `recursionLevelsRemaining` condition tripped.
Now reusable block tags that have IDs that we can't resolve, simply get replaced with `""`

🐛 fix Grapher WP ReusableBlock resolver bug

---

package.json
packages/@ourworldindata/grapher/package.json
packages/@ourworldindata/grapher/src/controls/Checkbox.scss
packages/@ourworldindata/grapher/src/controls/EntitySelectionToggle.tsx
packages/@ourworldindata/grapher/src/controls/LabeledSwitch.scss
packages/@ourworldindata/grapher/src/controls/LabeledSwitch.tsx
packages/@ourworldindata/grapher/src/controls/SettingsMenu.scss
packages/@ourworldindata/grapher/src/controls/SettingsMenu.tsx
packages/@ourworldindata/grapher/src/controls/settings/AbsRelToggle.tsx
packages/@ourworldindata/grapher/src/controls/settings/AxisScaleToggle.tsx
packages/@ourworldindata/grapher/src/controls/settings/FacetStrategySelector.tsx
packages/@ourworldindata/grapher/src/controls/settings/FacetYDomainToggle.tsx
packages/@ourworldindata/grapher/src/controls/settings/NoDataAreaToggle.tsx
packages/@ourworldindata/grapher/src/controls/settings/TableFilterToggle.tsx
packages/@ourworldindata/grapher/src/controls/settings/ZoomToggle.tsx
packages/@ourworldindata/grapher/src/core/grapher.scss
yarn.lock

Misc. bugfixes:
- revert `indefinite` dependency location shift (it was breaking builds on staging servers for some reason)
- instrument the UI elements in the controls row and settings menu for analytics
- display the table filter switch in the controls row directly
- add a tooltip to the settings menu toggle button
- tweak checkbox appearance

Grapher redesign updates (vi)

---

packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.tsx
packages/@ourworldindata/grapher/src/controls/ShareMenu.tsx
packages/@ourworldindata/grapher/src/core/Grapher.tsx
packages/@ourworldindata/grapher/src/header/Header.tsx
packages/@ourworldindata/grapher/src/modal/Modal.scss
site/css/content.scss

Adds back an algorithm (for static charts only) that decreases the title's font size to keep the title on a single line.
And some more bug fixes...

Grapher redesign: Improve static charts

---

packages/@ourworldindata/grapher/src/controls/ActionButtons.tsx
packages/@ourworldindata/grapher/src/core/Grapher.tsx
packages/@ourworldindata/grapher/src/dataTable/DataTable.jsdom.test.tsx
packages/@ourworldindata/grapher/src/dataTable/DataTable.tsx
packages/@ourworldindata/grapher/src/header/Header.tsx
packages/@ourworldindata/grapher/src/header/HeaderManager.ts
packages/@ourworldindata/grapher/src/modal/DownloadModal.scss

A handful of very minor final changes

Grapher redesign: Final touchups

---

_routes.json
functions/grapher/[slug].ts

Always redirect incoming grapher URL requests that contain any uppercase letters to the lowercase version.
We do this even though we don't even know whether the page exists, so this might still end up in a 404.

fix(cf): redirect grapher to lowercase slug

---

functions/_common/grapherRenderer.ts
packages/@ourworldindata/grapher/src/core/Grapher.tsx
packages/@ourworldindata/grapher/src/footer/Footer.tsx
packages/@ourworldindata/grapher/src/footer/FooterManager.ts
packages/@ourworldindata/grapher/src/header/Header.tsx
packages/@ourworldindata/grapher/src/header/HeaderManager.ts

@sophiamersmann, if you could take a look at 0a312618ad9df3f802b74246580e2caec9e084da for a moment that would be great.
Basically, the rationale is that if a title spans two or more lines, then we benefit from the font size reduction even if that doesn't reduce the number of lines.
I also changed the font size reduction to a maximum of 20% rather than cap it at 2px. It's just another arbitrary number, so feel free to change.
In theory we could also make this behavior dependent on the `isGeneratingThumbnail` flag, so let me know what you think.
Here are some thumbnails rendered using the worker. The last three have a reduced title font size.

redesign: render thumbnails at a larger font size

---

packages/@ourworldindata/grapher/src/controls/ContentSwitchers.tsx

- Fixes a bug where the chart icon would unexpectedly change from a line chart icon into a bar chart icon when clicking on the map tab
- This happens because switching from a line chart to the map automatically sets the timeline to a single year, and the underlying chart switches to a discrete bar chart
- To prevent that, we hold onto the previous chart icon if we're not currently on the chart tab.

Grapher redesign: Prevent chart icon to unexpectedly change

---

packages/@ourworldindata/grapher/src/controls/SettingsMenu.tsx

Some final(?) tweaks:
- detect when the page is an embed rendering inside an iframe and use the pop-up settings menu
- use the `isEmbeddedInAnOwidPage` flag to detect entries in Related Charts blocks rather than walking the DOM
- add a shortcut to dismiss an open menu/drawer with the escape key

Grapher redesign updates (vii)

---

packages/@ourworldindata/utils/src/MarkdownTextWrap/parser.ts

- fixes https://github.com/owid/owid-grapher/issues/2661
- Allows ':' in the hostname to detect URLs like: http://web.archive.org/web/20230906141841/http://196.40.56.11/scij/Busqueda/Normativa/Normas/nrmtextocompleto.aspx?nValor1=1&nValor2=11967
- Allows ':' in the query string to detect URLs like: https://www.normattiva.it/uri-res/N2Ls?urn:nir:stato:legge:2022-08-04;127

fix(url-parser): allow ':' in urls

---

explorerAdminClient/ExplorerCreatePage.tsx

- resolves https://github.com/owid/owid-grapher/issues/2504
----
- I had disabled the warning for mixed content explorers as a hot fix for https://github.com/owid/owid-grapher/pull/2598
- Referencing `program.whyIsExplorerProgramInvalid` lead to the component being re-rendered every few seconds (probably some mobx issue...)
- Wrapping `whyIsExplorerProgramInvalid` in a computed property fixes the issue

chore(explorer): enable warning for mixed-content explorers
