- readme.md
I got it all working, but it required a bit of fiddling. Hopefully this will make it easier for others :)
> Update README with more detailed instructions

- app/Http/Controllers/ViewController.php
- public/js/app/Importer.jsx
Just added the country code column, which already was in the result set of database query, to the list of columns to be written to csv.
> Added Country code column for exported csv files

- grapher_admin/models.py
- grapher_admin/templates/admin.licenses.edit.html
- grapher_admin/views.py
Adding an atomic transaction in order to not mess up the db in case of
data import failure
> CSV importer bug fixes, making updated_at fields update properly

- .env.example
- .gitignore
> improve sample env

- js/charts/ChartData.ts
- js/charts/ControlsFooter.tsx
- js/charts/LabelledSlopes.tsx
- js/charts/ScatterColorLegend.tsx
- js/charts/SlopeChart.tsx
- js/charts/SlopeChartTransform.ts
On slope charts:
As requested in:
https://github.com/owid/owid-grapher/issues/50
https://github.com/owid/owid-grapher/issues/51
@mispy
> add features to slope charts

- js/admin/ChartList.tsx
- js/admin/EditorFeatures.tsx
- js/charts/ChartConfig.tsx
- js/charts/ChartTab.tsx
- js/charts/ChartType.ts
- js/charts/StackedBarChart.tsx
- js/charts/StackedBarTransform.ts
Add support for Stacked Bar Chart
1. Add legend (uses legend used by Scatter Plots)
2. Add tooltip on hover
3. No scale on X-Axis but still assumes X-Axis to be years
> add basic stacked bar chart

- js/admin/CountryStandardizerPage.tsx
I will try to explain the issue 😅 
Joe pointed out an interesting bug where:
`Micronesia, Fed. Sts` was getting matched to `Micronesia (region)` ...
when the data already has a map between `Micronesia, Fed. Sts.` (note the dot) -> `Micronesia (country)`
This is happening because the seed supplied to Fuzzy Set is only the polished (OWID) country names and there are only 2 candidates in OWID names (`Micronesia (country)` and `Micronesia (region)`). For some reason, fuzzy set likes to match the input with the latter.
My fix here is to change the seed given to FuzzySet - add both polished (OWID) names and the non-standard country names. This forces FuzzySet to use `Micronesia, Fed. Sts.` as its candidate match and that indirectly ties to `Micronesia (country)`.
> country tool - improve candidate matching by adding all input and output countries

- js/charts/DataSelector.tsx
- js/charts/IChartTransform.ts
- js/charts/ScatterTransform.ts
- js/charts/SlopeChartTransform.ts
Fix issue detailed in https://github.com/owid/owid-grapher/issues/79
> Selector bug fix

- js/admin/DatasetEditPage.tsx
- js/charts/ChartType.ts
Should fix #70. 
@mispy Let me know if there's anything you'd do differently, mainly to understand any nuances I might've missed. 
E.g. does the `else` branch need to switch back to a line chart?
> Show bar chart if variable only contains a single year

- site/client/SiteHeaderMenus.tsx
Will now close if clicked and has already been open for 500ms. Will also not open unless mouse has been over it for more than 100ms.
> Less annoying dropdown

- site/client/stripe.ts
- site/server/views/DonatePage.tsx
- site/server/views/Head.tsx
> Do not include Stripe on every page

- admin/client/ChartEditorPage.tsx
- charts/ChartConfig.tsx
- charts/ChartLayout.tsx
- charts/ChartTab.tsx
- charts/ChartView.tsx
- charts/ChartViewContext.ts
- charts/Controls.tsx
- charts/ControlsFooter.tsx
- charts/DataSelector.tsx
- charts/HTMLTimeline.tsx
- charts/Header.tsx
- charts/HeightedLegend.tsx
- charts/LineChart.tsx
- charts/MapTab.tsx
- charts/NoData.tsx
- charts/ScaleSelector.tsx
- charts/StackedArea.tsx
- charts/Tooltip.tsx
- charts/client/chart.scss
- site/client/css/general.scss
- site/client/owid.scss
And also:
- In DataSelector, the countries no longer disappear when selected
- Changed to Lato font by default (but not requesting the webfont from Google Fonts). This means that on OWID the charts will always use Lato, but on other sites, it's very likely they will default to Helvetica Neue or Arial, which feels reasonable?
- Small random fixes
> Move "add country" button to legend

- charts/ChartView.tsx
- charts/DataSelector.tsx
- charts/DownloadTab.tsx
- charts/PointsWithLabels.tsx
- charts/ScatterTransform.ts
- charts/client/chart.scss
...and make header sticky in DataSelector, and make the overlay "pop off" the chart
> Add "unselect all" button to DataSelector

- site/server/views/SiteFooter.tsx
Supporters link in the footer seems to be broken. This PR fixes it.
> Fix suppoerters link in footer

- charts/DataTable.tsx
- charts/ExploreView.tsx
- charts/__tests__/DataTable.test.tsx
- charts/client/chart.scss
Adds a very simple data table below the chart.
Needs tests but putting this out there for feedback.
> Add data table

- charts/__tests__/DataTable.test.tsx
- charts/__tests__/ExploreView.test.tsx
- charts/__tests__/Store.test.ts
- jest.config.js
- site/server/views/__tests__/ChartPage.test.tsx
- test/apiMock.ts
- test/fixtures/index.ts
* fixtures module to help read fixtures
* apiMock module to help mock XHR calls
> Add some test helper modules

- charts/ExploreView.tsx
Minor thing, just mirroring ChartView here
> Add error logging to ExploreView

- charts/DataTable.tsx
- charts/DataTableTransform.ts
- charts/__tests__/DataTable.test.tsx
Sort rows by value. This is so much more useful/interesting than always presenting them alphabetically by country name.
> Sort data table

- charts/DataTable.tsx
- charts/DataTableTransform.ts
- charts/ExploreView.tsx
- charts/MapData.ts
- charts/TickFormattingOptions.ts
- charts/Tippy.tsx
- charts/Util.ts
- charts/__tests__/DataTable.test.tsx
- charts/__tests__/Util.test.ts
- charts/client/chart.scss
- jest.config.js
- package.json
- test/styleMock.ts
- yarn.lock
Improvements:
- Number formatting in table (https://www.notion.so/owid/Data-table-value-formatting-polish-e9caef55a25049069bc09d254d09c8fd)
- Allowing users to change the sort order (https://www.notion.so/owid/Data-table-allow-user-to-change-sorting-9aae2b29db0541a8a4418914bab51730)
- Showing the currentYear value or the closest year within the tolerance (https://www.notion.so/owid/Data-table-current-year-tolerance-0bd50618b2ed4f259caf3856253052cb)
- Updated visuals
> Data Explorer table improvements

- charts/Util.ts
- site/client/Covid.tsx
- site/client/css/pages/covid.scss
- site/server/views/CovidPage.tsx
Various improvements. Just trying to push this out in a hurry...
> COVID Table v2

- charts/AxisBox.tsx
- charts/AxisTickMarks.tsx
- charts/DiscreteBarChart.tsx
- charts/HorizontalAxis.tsx
- charts/ScatterPlot.tsx
- charts/StackedBarChart.tsx
- charts/StandardAxisBoxView.tsx
- charts/TimeScatter.tsx
> Add tick marks to line charts and stacked bar charts.

- charts/ChartConfig.tsx
- charts/DataTab.tsx
I created a separate "Date" vs "Year" row header for the two different cases, but it may be ok to just use "Date" all the time. Lmk, I can change that.
> separate dayIsYearVar getter function, format years in csv download

- charts/Util.ts
- charts/__tests__/Util.test.ts
- site/client/covid/CovidBars.tsx
- site/client/covid/CovidConstants.ts
- site/client/covid/CovidDoublingTooltip.tsx
- site/client/covid/CovidFetch.ts
- site/client/covid/CovidTable.tsx
- site/client/covid/CovidTableColumns.tsx
- site/client/covid/CovidTableRow.tsx
- site/client/covid/CovidTypes.ts
- site/client/covid/CovidUtils.ts
- site/client/covid/index.tsx
- site/client/css/pages/covid.scss
- site/server/views/CovidPage.tsx
Leaving this here just as a log. 
I don't think we will be maintaining this in the long-term, so don't think we should review (let me know if you disagree)
> CovidTable: testing table demo + various improvements

- charts/ChartConfig.tsx
- charts/Controls.tsx
- charts/client/chart.scss
> Change control text from Search to Select Countries/Entities. Change color to controls color.

- charts/PointsWithLabels.tsx
> If a series is selected on a scatterplot only show labels for that series

- charts/PointsWithLabels.tsx
> Make subtle foreground lines a little less subtle

- site/client/css/content.scss
- site/server/formatting.tsx
Give "Add country" text (and variations) the appearance of "+ Add Country" chart control
> "Add country" styling

- charts/Bounds.ts
- charts/HorizontalAxis.tsx
> Fix leftmost horizontal tick label exceeding chart viewable area

- charts/ScaleSelector.tsx
> Ensure log-linear toggle does not exceed chart viewable area

- charts/covidDataExplorer/CovidCountryPicker.tsx
- charts/covidDataExplorer/CovidDataExplorer.tsx
- site/client/css/pages/covidDataExplorer.scss
- site/client/css/variables.scss
Notion issue: https://www.notion.so/owid/Turn-country-selector-into-a-dropdown-on-mobile-fe1bdf77ebfe464f8535953450f799f4
> Turn country select into searchable dropdown on mobile

- charts/covidDataExplorer/CovidDataExplorer.tsx
Think I should do anything more sophisticated?
> Customize metric ab test

- charts/covidDataExplorer/CovidDataExplorer.tsx
- charts/covidDataExplorer/CovidDataUtils.ts
> Change "daily" to "daily new" on CovidDataExplorer

- charts/ChartConfig.tsx
- charts/HorizontalAxis.tsx
- charts/LineChartTransform.ts
- charts/TickFormattingOptions.ts
@breck7 An alternative approach to #456 that doesn't pass `chart` down.
Was curious if it can be done, I might've missed some details!
> Use shorter date format on x tick marks for all but last tick (alternative approach)

- package.json
- scripts/configureAlgolia.ts
- scripts/indexChartsToAlgolia.ts
- scripts/indexToAlgolia.ts
- site/siteSearch.ts
- yarn.lock
- upgrade to algoliasearch v4
- upgrade to native Algolia functions for multi-index searches and atomic reindexing
(replaces https://github.com/owid/owid-grapher/pull/387)
> algoliasearch v4

- charts/covidDataExplorer/CovidDataUtils.ts
- charts/covidDataExplorer/CovidVariablePartials.ts
Also updated the cases & deaths annotations
> Derive test units from data

- charts/Controls.tsx
- charts/client/chart.scss
> remove lines above timeline and active tab

- charts/ChartDimensionWithOwidVariable.ts
- charts/Controls.tsx
- charts/DataTab.tsx
- charts/DataTable.tsx
- charts/DataTableTransform.ts
- charts/ScatterTransform.ts
- charts/Util.ts
- charts/client/chart.scss
- charts/covidDataExplorer/CovidDataExplorer.tsx
- charts/owidData/OwidVariable.ts
- site/client/css/components/datatable.scss
- site/client/owid.scss
All of the changes in DataTableTransform after line 194 are Prettier formatting auto-fixes -- ignore.
**Before:**
**After:**
> DataExplorer DataTable fixes

- charts/DataTable.tsx
- charts/DataTableTransform.ts
- charts/SortIcon.tsx
- charts/SortOrder.ts
- charts/TickFormattingOptions.ts
- charts/Util.ts
- charts/__tests__/CovidDataUtils.test.ts
- charts/covidDataExplorer/CovidChartUrl.ts
- charts/covidDataExplorer/CovidCountryPicker.tsx
- charts/covidDataExplorer/CovidCountryPickerMetric.ts
- charts/covidDataExplorer/CovidDataExplorer.tsx
- charts/covidDataExplorer/CovidDataUtils.ts
- charts/covidDataExplorer/CovidTypes.ts
- site/client/covid/CovidConstants.ts
- site/client/covid/CovidTable.tsx
- site/client/covid/CovidTableHeaderCell.tsx
- site/client/covid/CovidTableSortIcon.tsx
- site/client/covid/CovidTypes.ts
- site/client/covid/CovidUtils.ts
- site/client/covid/index.tsx
- site/client/css/pages/covidDataExplorer.scss
- Allows sorting by a selection of metrics
- Plots bars and values for each country
> CovidDataExplorer: custom sort in country selector

- charts/CSVGenerator.tsx
- charts/ChartDimensionWithOwidVariable.ts
Refactoring of CSVGenerator as promised. @breck7
> CSVGenerator Refactor

- charts/Controls.tsx
- charts/client/chart.scss
**Before:
After:
Before:
After:**
> Prominent/Responsive Download Button

- charts/owidData/OwidTable.ts
🕵️‍♂️ Bundle size detective is onto something again!
> import Util instead of lodash directly

- charts/MapTab.tsx
- charts/MapTooltip.tsx
- charts/Tooltip.tsx
w/ some minor refactoring
**Before:**
**After:**
**Before:**
**After:**
> Map tooltip location fix

- charts/ColorSchemes.ts
- charts/__tests__/CovidExplorerTable.test.ts
- charts/covidDataExplorer/CovidChartUrl.ts
- charts/covidDataExplorer/CovidColumnSpecs.ts
- charts/covidDataExplorer/CovidCountryPicker.tsx
- charts/covidDataExplorer/CovidDataExplorer.tsx
- charts/covidDataExplorer/CovidExplorerTable.ts
- charts/covidDataExplorer/CovidTypes.ts
> Add line colors to Cases + Tests scatters

- charts/ChartConfig.tsx
- charts/__tests__/CovidExplorerTable.test.ts
- charts/covidDataExplorer/CovidChartUrl.ts
- charts/covidDataExplorer/CovidConstants.ts
- charts/covidDataExplorer/CovidDataExplorer.tsx
- charts/covidDataExplorer/CovidExplorerTable.ts
- charts/owidData/OwidTable.ts
> Filter negative values from line and map charts and support more params in Explorer

- charts/ChartDimensionWithOwidVariable.ts
- charts/DataTable.tsx
- charts/DataTableTransform.ts
> DataTable: shortened dates

- charts/ChartConfig.tsx
- charts/Controls.tsx
- charts/__tests__/DataTable.test.tsx
> DataTable: option to hide small countries

- charts/__tests__/CovidDataExplorer.test.tsx
- charts/covidDataExplorer/CovidTypes.ts
- stories/covidDataExplorer.stories.tsx
This PR adds some Multimetric DataTable tests/stories. Will hopefully help with #520. I'll add more tests over the next couple days.
> Multimetric Tests v1

- admin/server/testPages.tsx
- charts/ChartData.ts
- charts/ChoroplethMap.tsx
- charts/MapData.ts
- charts/MapTab.tsx
- charts/MapTooltip.tsx
- charts/Util.ts
- charts/covidDataExplorer/CovidDataExplorer.tsx
Just an idea to allow shift-clicking to select/deselect countries on the map tab.
A design question is whether to show selection state of a country (my guess is not by default, as looking at existing charts on the map view many of them look worse with a few countries selected).
> New: shift click on map to select or deselect a country.

- admin/client/TestIndexPage.tsx
- admin/server/testPages.tsx
- charts/ColorLegend.ts
Notion: https://www.notion.so/owid/Increase-categorical-legend-font-size-bd341afe5d1d4869a1ac703ecd431834
> Increase categorical legend font size

- charts/ChartConfig.tsx
- charts/HTMLTimeline.tsx
- charts/client/chart.scss
**Live on [Nightingale](https://nightingale-owid.netlify.app/grapher/age-dependency-ratio-old?tab=chart&year=1983&time=1979..2010).** 
Also fixes Timeline grab glitch:
**Before:**
**After:**
> New Timeline Handles + Fixes

- scripts/exportChartData.ts
- scripts/exportChartDataNamespace.ts
> Fix exportChartData scripts following MySQL 5.7.31 update

- charts/controls/Controls.tsx
- charts/controls/Timeline.tsx
- charts/core/ChartConfig.tsx
> Timeline Overflow Fix

- explorer/client/SwitcherExplorer.tsx
- explorer/covidExplorer/CovidExplorer.tsx
- explorer/indicatorExplorer/ExploreUrl.ts
- grapher/controls/Controls.tsx
- grapher/core/Grapher.tsx
- grapher/core/GrapherConfig.test.ts
- grapher/core/GrapherConfig.ts
- grapher/core/GrapherUrl.jsdom.test.ts
- grapher/core/GrapherUrl.ts
- grapher/dataTable/DataTableTransform.ts
Currently GrapherUrl depends on Grapher and vice versa. Should get rid of that circular dependency which makes things harder to test. This is just some work toward that.
> Grapher url

- stripe/DonateForm.tsx
Just leaving here until the Netlify function is deployed and ready.
> Add GBP & EUR currencies to donate form

- grapher/core/Analytics.ts
- tsconfig.client.json
- types/simpleanalytics/index.d.ts
Adding trial support for Simple Analytics (https://simpleanalytics.com/).
> Add Simple Analytics (test)

- wordpress/web/app/plugins/owid/owid.php
> Remove edit link below tables in previews

- adminSite/server/testPageRouter.tsx
This would hide all charts tagged as "Private", unless the `includePrivate` query param is passed.
> Exclude charts tagged "Private" from test pages

- coreTable/OwidTable.test.ts
- coreTable/OwidTable.ts
- grapher/core/Grapher.tsx
- grapher/timeline/TimelineController.test.ts
- grapher/timeline/TimelineController.ts
- grapher/utils/TimeBounds.ts
A bunch of fixes for the timeline. The goal was to fix [Timeline plays backwards](https://www.notion.so/owid/Timeline-plays-backwards-9e69532e53394bdeb825a9d1f51e3a54).
> Timeline fixes

- grapher/core/Grapher.tsx
- grapher/sourcesTab/SourcesTab.tsx
Fixes: https://www.notion.so/owid/Fix-isAdmin-Grapher-flag-fa3cc7b0762c43c7be5f3f172d8299dd
There might be a better way to name these?
> Distinct admin context & admin user flags

- coreTable/OwidTable.ts
- grapher/barCharts/DiscreteBarChart.tsx
- grapher/chart/ChartInterface.ts
- grapher/chart/ChartManager.ts
- grapher/core/Grapher.jsdom.test.ts
- grapher/core/Grapher.tsx
- grapher/dataTable/DataTable.jsdom.test.tsx
- grapher/facetChart/FacetChart.tsx
- grapher/facetChart/FacetChartConstants.ts
- grapher/lineCharts/LineChart.tsx
- grapher/mapCharts/MapChart.tsx
- grapher/scatterCharts/ScatterPlotChart.tsx
- grapher/scatterCharts/ScatterPlotChartConstants.ts
- grapher/slopeCharts/SlopeChart.tsx
- grapher/stackedCharts/AbstractStackedChart.tsx
- grapher/stackedCharts/StackedAreaChart.tsx
Notion issue: https://www.notion.so/owid/Move-chart-transforms-to-Grapher-d53e023091e245c2914543b7fce0feac
> Move chart transforms to Grapher

- grapher/timeline/TimelineComponent.stories.tsx
- grapher/timeline/TimelineComponent.tsx
- grapher/timeline/TimelineController.test.ts
- grapher/timeline/TimelineController.ts
Fixes aforementioned embeds problems
> Restore DataTable Start Year Autoselection

- coreTable/CoreTableUtils.test.ts
- coreTable/CoreTableUtils.ts
- coreTable/InvalidCells.ts
- coreTable/LegacyToOwidTable.ts
- coreTable/OwidTable.test.ts
- coreTable/OwidTable.ts
- coreTable/OwidTableUtil.ts
- grapher/barCharts/DiscreteBarChart.tsx
- grapher/captionedChart/CaptionedChart.stories.tsx
- grapher/core/Grapher.tsx
- grapher/scatterCharts/ScatterPlotChart.stories.tsx
- grapher/utils/Util.test.ts
- grapher/utils/Util.ts
Working on applying them on charts on another branch.
> Implement tolerance fill transform on OwidTable

- coreTable/CoreTableColumns.ts
- coreTable/OwidTable.ts
- coreTable/OwidTableUtil.ts
- grapher/barCharts/DiscreteBarChart.test.ts
- grapher/barCharts/DiscreteBarChart.tsx
- grapher/barCharts/DiscreteBarChartConstants.ts
- grapher/core/Grapher.jsdom.test.ts
- grapher/core/Grapher.tsx
- grapher/facetChart/FacetChart.tsx
- grapher/mapCharts/MapChart.jsdom.test.tsx
- grapher/mapCharts/MapChart.tsx
- grapher/mapCharts/MapChartConstants.ts
- grapher/mapCharts/MapTooltip.tsx
- grapher/scatterCharts/ScatterPlotChart.tsx
- grapher/slopeCharts/SlopeChart.tsx
Still more to go. But I think these are good to merge?
> Tolerance-&-timeline-related fixes

- site/client/NewsletterSubscription.tsx
- site/client/SiteTools.tsx
- site/client/css/components/site-tools.scss
- site/client/css/mixins.scss
- site/client/hooks.ts
Buttons sometimes get in the way of the reading X. Solutions:
- smaller
- disappear / reappear on scroll
Context: https://owid.slack.com/archives/CLDM2AWCD/p1603375599054200
> Less prominent site tools

- adminSite/server/testPageRouter.tsx
- coreTable/CoreTable.ts
- coreTable/CoreTableColumns.ts
- coreTable/CoreTableUtils.test.ts
- coreTable/CoreTableUtils.ts
- coreTable/LegacyToOwidTable.test.ts
- coreTable/LegacyToOwidTable.ts
- coreTable/LegacyVariableCode.ts
- coreTable/OwidTable.test.ts
- coreTable/OwidTable.ts
- grapher/chart/ChartDimension.ts
- grapher/color/ColorScale.test.ts
- grapher/core/Grapher.tsx
- grapher/scatterCharts/ScatterPlotChart.tsx
- grapher/scatterCharts/ScatterPlotChartConstants.ts
Also adds more tests around this. Keeps all behaviour as it was before, haven't yet implemented mixed-time-type table joins...
> ScatterPlots: handle xOverrideTime and apply color scales

- wayback/readme.md
- wayback/wayback.ts
Idea is to have a fast way to bring up old versions of the site with the correct old assets.
Thoughts? Is it useful? Feel free to merge and update if you think it may be helpful.
> Dev: start owid wayback tool

- grapher/core/Grapher.jsdom.test.ts
- grapher/core/Grapher.tsx
Notion issue: https://www.notion.so/owid/Stacked-area-charts-are-broken-90e567a1e0334d3b9879b0f3237ee0ad
> Distinct timeline handles for map & chart

- grapher/core/Grapher.tsx
- site/server/bakeChartsToImages.tsx
As reported on Slack: https://owid.slack.com/archives/C46U9LXRR/p1604397643008400
> Fix: country param ignored in exports

- adminSite/client/EditorScatterTab.tsx
- coreTable/CoreTable.test.ts
- coreTable/CoreTable.ts
- coreTable/CoreTableColumns.ts
- coreTable/CoreTableUtils.test.ts
- coreTable/LegacyToOwidTable.test.ts
- coreTable/LegacyToOwidTable.ts
- coreTable/OwidTable.ts
- grapher/color/ColorScale.ts
- grapher/core/Grapher.tsx
- grapher/mapCharts/MapChart.tsx
- grapher/scatterCharts/ConnectedScatterLegend.tsx
- grapher/scatterCharts/ScatterPlotChart.test.ts
- grapher/scatterCharts/ScatterPlotChart.tsx
- grapher/scatterCharts/ScatterPlotChartConstants.ts
- grapher/slopeCharts/SlopeChart.tsx
- grapher/stackedCharts/StackedBarChart.test.ts
- grapher/stackedCharts/StackedBarChart.tsx
- grapher/utils/Util.ts
- grapher/verticalColorLegend/VerticalColorLegend.tsx
~~Based on `next-columnfilter-error-values` which should be merged first.~~
~~Missing tests, will add soon.~~ Added tests.
> ScatterPlot fixes

- explorer/client/Explorer.tsx
- explorer/client/ExplorerProgram.ts
- grapher/core/Grapher.tsx
> Better grapher error handling

- package.json
- site/client/blocks/index.ts
- site/client/covid/CovidLastUpdated.tsx
- site/client/runDataTokens.tsx
- site/server/DataToken.tsx
- site/server/formatting.tsx
- wordpress/web/app/plugins/owid/src/plugins.js
- yarn.lock
- fetched at runtime from https://covid.ourworldindata.org/data/owid-covid-data-last-updated-timestamp.txt
- initiating the transition away from Moment.js to (potentially) [Day.js](https://day.js.org/) as Moment is being sunset (https://momentjs.com/docs/#/-project-status/)
> Automated COVID data last updated date

- adminSite/server/testPageRouter.tsx
- explorer/admin/ExplorerBaker.tsx
- explorer/covidExplorer/CovidConstants.ts
- grapher/core/Grapher.tsx
> Switch CovidExplorer to JHU data

- coreTable/CoreColumnDef.ts
- coreTable/CoreTable.ts
- coreTable/CoreTableColumns.ts
This is good work. Merging it in.
> add QuarterColumn

- baker/Deployer.ts
It's still a little ugly how it writes scripts and then runs those on the server, perhaps just sending the SSH commands is the way to go. (Although I think ideally the way to go is just run the whole bake locally and then push to Netlify from your dev machine).
> Dev: refactor scripts into units. Now baking is a 21 step process

- grapher/color/ColorScale.test.ts
- grapher/color/ColorScale.ts
This adds test cases for my fixes on master from earlier today.
> test(colorScale): add test cases for color scale outlier detection

- adminSiteServer/adminRouter.tsx
- gitCms/GitCmsClient.ts
- gitCms/GitCmsServer.ts
Fixes some Explorer admin issues and cleans up some code. See 2 commits for longer explanations.
> Explorer editor fixes

- explorer/ExplorerGrammar.ts
- explorer/ExplorerProgram.ts
- explorer/GrapherGrammar.ts
- explorerAdmin/ExplorerCommands.ts
- explorerAdmin/ExplorerCreatePage.tsx
- explorerAdmin/ExplorersListPage.tsx
- gridLang/GridCell.test.ts
- gridLang/GridCell.ts
- gridLang/GridLangConstants.ts
- gridLang/GridProgram.ts
Same as https://github.com/owid/owid-grapher/pull/753 but this time against "next" instead of "master" (oops).
> Add support for lists to grid lang

- grapher/core/GrapherAnalytics.ts
- site/client/ExpandableInlineBlock/ExpandableInlineBlock.tsx
- site/client/SiteAnalytics.ts
- site/client/blocks/AdditionalInformation/AdditionalInformation.tsx
- add tracking to expandable blocks (glossary excerpts and "additional information")
- remove simple analytics tracking
> Miscellaneous analytics

- .gitignore
- explorer/covidExplorer/CovidConstants.ts
- explorer/covidExplorer/CovidExplorer.tsx
- explorer/covidExplorer/CovidExplorerTable.ts
- explorer/covidExplorer/CovidParams.ts
- site/server/SiteBaker.tsx
Waiting for authors to review this. Deploying to a staging server now, will appear here: https://playfair-owid.netlify.app/coronavirus-data-explorer
https://user-images.githubusercontent.com/1308115/103800391-44f77b80-5044-11eb-9ed9-1b842ab0c5b3.mp4
> Add Vaccinations to CovidExplorer

- adminSite/server/apiRouter.ts
- db/wpdb.ts
- grapher/utils/Util.ts
- package.json
- site/RelatedArticles/RelatedArticles.tsx
- site/server/contentGraph.test.ts
- site/server/contentGraph.ts
- site/server/grapherBaking.tsx
- site/server/views/GrapherPage.tsx
- yarn.lock
See https://www.notion.so/ba1c0a82e13f4a3d9c8467261975219e
> Related articles on grapher pages

- .rsync-ignore
- baker/Deployer.ts
- baker/SiteBaker.tsx
- baker/formatWordpressPost.tsx
- settings/serverSettings.ts
Notion: https://www.notion.so/owid/Deploy-next-to-staging-bf0185f104aa4b56b3f8fceda10aae8a
I tried deploying `next` to tufte; turns out it isn't this easy.
These are _some_ of the fixes needed to get this working, and there will be others coming next week. Nonetheless, this PR is ready to be reviewed & merged already, I'd rather work on the other fixes independently because they're mostly atomic.
> Fix (some) deploy issues on next

- baker/GrapherBaker.tsx
- baker/siteRenderers.tsx
- clientUtils/owidTypes.ts
- db/wpdb.ts
- wordpress/web/app/plugins/owid/src/authentication.php
See: https://www.notion.so/258acc2f93ec482e8d7352266cdace9d
> Prevents unauthenticated requests to REST and GraphQL APIs

- db/wpdb.ts
- wordpress/web/app/plugins/owid/owid.php
"wp_block" now needing custom post type handling to surface in GraphQL API
> Fix block content not showing on explorers

- wordpress/scripts/refresh-staging.sh
> fix(refresh): use master's exportMetadata

- explorer/Explorer.tsx
While reviewing https://github.com/owid/owid-grapher/pull/788, I realized some of the code in this method worked by accident and not design. This should partially fix that.
> Dev: refactor reactToUserSelection method

- site/server/views/SiteSubnavigation.tsx
Add subnavigation menu for Forests.
> Add subnavigation menu for forests

- site/server/views/LongFormPage.tsx
Part of experiment: https://www.notion.so/owid/Navigate-read-and-explore-fc770056bb8545e3a2ed6fea80e9d7ae#1e84d06c84fb443fbfef3aabd519cf4e
> Move subnavigation back above hero

- explorer/Explorer.tsx
This fixes [Changing explorer params dismisses the selected time range](https://www.notion.so/owid/Changing-explorer-params-dismisses-the-selected-time-range-8eeccfd91ba445c9a2e566e15dadf91a) and [CO2 explorer adds world and/or switches from line to map unexpectedly](https://www.notion.so/owid/CO2-explorer-adds-world-and-or-switches-from-line-to-map-unexpectedly-ae404eba49e0470bbceadb85bb2dea0c).
Basically, each grapher still gets its own query params, except the params are persisted by selected row instead of grapher ID, which works for both switcher explorers (which have a grapher ID) and non-switchers (which don't).
Certain params can be chosen to persist across explorer row changes -- currently, I'm only persisting the `time` param.
> Persist params by selected row instead of by grapher ID

- wordpress/web/app/plugins/owid/owid.php
By default, Wordpress uses not only the title but also the excerpt and the content when performing a search query in the admin. This leads to inaccurate results.
This PR limits the scope of the search to the posts titles only.
> Improve wordpress admin search accuracy

- site/client/Feedback.tsx
Deploy second, after https://github.com/owid/owid-feedback/pull/9
> Prevent sending empty feedback messages (companion PR)

- yarn.lock
Run `npx browserslist@latest --update-db`
https://github.com/browserslist/browserslist#browsers-data-updating
> Update browserlist db (caniuse-lite)

- baker/Deployer.ts
- db/readme.md
- ormconfig.js
- package.json
Notion: [Database migrations are not automatically run on deploy](https://www.notion.so/Database-migrations-are-not-automatically-run-on-deploy-48938a638d884cdd85efb9fd07c89c64)
> Run DB migrations on deploy

- explorer/Explorer.tsx
- grapher/core/Grapher.jsdom.test.ts
- grapher/core/Grapher.tsx
It has lead to too many problems. Latest one is: the CSV download is missing a time column.
> fix: do not drop "unnecessary" columns

- baker/formatWordpressPost.tsx
- site/LongFormPage.tsx
- site/css/page.scss
See [Condense page header (first steps)](https://www.notion.so/Condense-page-header-first-steps-afe225f2f1ae4e778459b79a0d2b89f9)
> Condense page header (first steps)

- site/Breadcrumb/Breadcrumb.scss
- site/Breadcrumb/Breadcrumb.test.ts
- site/Breadcrumb/Breadcrumb.tsx
- site/LongFormPage.tsx
- site/SiteSubnavigation.tsx
- site/owid.scss
See https://www.notion.so/owid/87c76bb6f68f45459a7ff6fa9fa3955a
> Add breadcrumb

- clientUtils/Util.ts
- grapher/controls/globalEntitySelector/GlobalEntitySelector.scss
- site/ChartsIndexPage.tsx
- site/EntriesByYearPage.tsx
- site/LongFormPage.tsx
- site/TableOfContents.tsx
- site/css/mixins.scss
- site/css/page.scss
- site/css/sidebar.scss
- site/css/site-tools.scss
- site/css/variables.scss
- site/owid.scss
see [Add a label to ToC toggle](https://www.notion.so/Add-a-label-to-ToC-toggle-b42d173607a1486c8482608fa5aabaed)
also: add hover states to "Subscribe" and "Feedback" buttons.
> Add a label to ToC toggle

- clientUtils/Util.ts
- grapher/selection/.eslintrc.yaml
- grapher/selection/SelectionArray.ts
This commit gets rid of a helper method to keep more precise type information
> style(grapher): Add return type annotations to selection

- adminSiteClient/VariableSelector.tsx
- clientUtils/Util.test.ts
- clientUtils/Util.ts
- coreTable/OwidTable.ts
- explorer/ExplorerControls.tsx
- grapher/color/ColorScale.ts
- grapher/lineLegend/LineLegend.tsx
- site/covid/CovidTable.tsx
Just some general cleanup I did:
* Removed unused lodash imports/exports
* got rid of `splitArrayIntoGroupsOfN` in favor of `_.chunk`
* added some stronger types here and there
* etc.
> General cleanup

- site/NewsletterSubscription.tsx
- make biweekly a default choice
- update biweekly label
> Minor newsletter subscription form updates

- grapher/core/schema.json
This is an initial base for a json schema for the grapher config. See this notion page for details: https://www.notion.so/owid/Grapher-json-schema-791109f371254a32999cd03b74d7056c
> enhance: Introduce grapher json schema

- adminSiteClient/Admin.tsx
- adminSiteClient/CountryStandardizerPage.tsx
- adminSiteClient/EditorReferencesTab.tsx
- adminSiteServer/adminRouter.tsx
- adminSiteServer/publicApiRouter.ts
- baker/GrapherBaker.tsx
- baker/pageOverrides.tsx
- clientUtils/Util.ts
- db/db.ts
- db/execWrapper.test.ts
- devTools/svgTester/utils.ts
- grapher/controls/VerticalScrollContainer.tsx
- grapher/downloadTab/DownloadTab.tsx
- package.json
- site/Feedback.tsx
- site/covid/CovidTable.tsx
- site/stripe/DonateForm.tsx
- yarn.lock
and adapt code to slightly stricter typedefs.
> chore: Upgrade to typescript 4.4

- baker/formatWordpressPost.tsx
- baker/formatting.tsx
- baker/siteRenderers.test.ts
- baker/siteRenderers.tsx
- clientUtils/Util.ts
- clientUtils/owidTypes.ts
- clientUtils/urls/Url.ts
- db/wpdb.ts
- settings/clientSettings.ts
- site/LongFormPage.tsx
- site/blocks/ProminentLink.tsx
- site/blocks/index.ts
- site/blocks/prominent-link.scss
- site/owid.entry.ts
- wordpress/web/app/plugins/owid/src/ProminentLink/prominent-link.php
see [Automatic prominent links](https://www.notion.so/Automatic-prominent-links-1eafcce85953483d912b6e5f20b928ec) (including technical rationale and current limitations)
> feat: automatic prominent links

- adminSiteClient/VariablesAnnotationPage.tsx
- adminSiteClient/VariablesAnnotationTypesAndUtils.tsx
- adminSiteClient/admin.scss
- adminSiteServer/apiRouter.ts
- clientUtils/AdminSessionTypes.ts
- clientUtils/SqlFilterSExpression.test.ts
- clientUtils/SqlFilterSExpression.ts
- clientUtils/schemaProcessing.ts
- grapher/schema/grapher-schema.001.json
- grapher/schema/grapher-schema.001.yaml
- package.json
- yarn.lock
> Bulk FASTT filtering

- site/formatting.test.ts
> Tests for splitting content into columns

- adminSiteServer/apiRouter.ts
- adminSiteServer/testPageRouter.tsx
- baker/GrapherImageBaker.tsx
- baker/siteRenderers.tsx
- db/model/Chart.ts
mysql 8 treats json extracted values on IS TRUE or IS FALSE differently from 5.7
This commit switches to the new ->> operatator that unquotes the json value to a string and compares that to false or true. See https://bugs.mysql.com/bug.php?id=99237
> SQL updates for MySQL 8 compatibility

- site/FrontPage.tsx
- site/SiteFooter.tsx
Attempt to solve issue #1283 "Add Instagram to social links". This is my first attempt at a Pull Request so I hope everything is in order. Also wasn't sure if "?" in the task list of the issue meant there might be other places where the instagram link should be added.
> Added Instagram link to the social media lists in homepage and in footer

- baker/GrapherBaker.tsx
> fix(baker): do not remove explorer redirects in `/grapher` dir

- devTools/droplet/setup-staging-environment.sh
Just a few small hitch-smoothers.
"OWID staff" as a way to navigate the private/public aspect of our dependencies.
> enhance(setup-staging-environment.sh) update comments

- README.md
- docs/docker-compose-mysql.md
- docs/full-wordpress-setup.md
- docs/local-database-setup.md
- docs/setup-options-overview.md
This advertises just one way to get started in the main readme and links to a separate document explaining all the different options
> Simplify readme

- baker/DeployTarget.ts
- wordpress/scripts/deploy.sh
Ptolemy is arguably not a central figure of data visualisation, but all the good ones were taken and I like the name.
> chore: add ptolemy staging environment

- wordpress/scripts/refresh-staging.sh
Fixing the database refresh script on staging that was broken for @ikesau and myself.
- Update server paths (live vs live-db)
- Use different database passwords for grapher and wordpress
- Simplify a little
> fix(staging): update refresh script for staging

- package.json
Removes an old holdover script that we don't use anymore.
> chore(package.json): remove startSiteBack

- wordpress/scripts/refresh-staging.sh
Just one more little sanity check until we improve this 😊 
Outputs:
```
Importing live Grapher metadata database (owid_metadata)
$GRAPHER_DB_NAME is set to ptolemy_grapher
$GRAPHER_DB_HOST is set to localhost
$GRAPHER_DB_USER is set to ptolemy_grapher
$GRAPHER_DB_PASSWORD is set to *******************
Downloading live Grapher chartdata database (owid_chartdata)
```
or 
```
Importing live Grapher metadata database (owid_metadata)
$GRAPHER_DB_NAME is unset
```
and exits the program.
> enhance(refresh-staging.sh): check env variables are defined

- .eslintrc.js
- adminSiteClient/BulkGrapherConfigEditor.tsx
- adminSiteClient/GrapherConfigGridEditor.tsx
- adminSiteClient/GrapherConfigGridEditorTypesAndUtils.tsx
- clientUtils/SqlFilterSExpression.ts
This implements persisting the filtering/paging state of bulk FASTT editory into the query params. Part of #1224
> Bulk fastt filters in querystring

- baker/formatWordpressPost.tsx
When a {{DataValue}} query doesn't resolve, an exception is thrown and halts baking / rendering. 
Originally, this behaviour was deemed [desirable as a way to prevent non-sensical sentences in the content](https://www.notion.so/owid/Exceptions-in-build-bake-should-prevent-deploy-161e34b212734dee944441bee742063a#f733c59bb2c9402ca8eda2f4ff05a6d5). It was also based on the assumption that an outdated value was probably better than no value at all. 
This more transparent approach challenges that, and make missing values visible, while waiting for a content fix after notifying authors. In a way, this is in line with our resolution to not hide missing data.
This also makes local development and baking-on-staging scenarios less cumbersome and less likely to fail when the `data_values` table has …
> More transparent, non-render blocking {{DataValue}} tags

- grapher/controls/EntitySelectorModal.tsx
Initial fix for issue #1399.
I moved the condition to check for "Escape" key to a separate function, and added it to `searchResults` div.
> Escape key to exit entity selector

- site/SiteTools.tsx
- site/css/site-tools.scss
Links to https://ourworldindata.org/jobs
> feat(tools): add jobs button

- adminSiteClient/AdminApp.tsx
- adminSiteClient/AdminSidebar.tsx
- adminSiteClient/DetailsOnDemand.tsx
- adminSiteClient/admin.scss
- adminSiteServer/apiRouter.ts
Resolves #1472 
A new table view in the grapher admin for DoD CRUD.
I didn't implement pagination but can if we think it's necessary.
https://user-images.githubusercontent.com/11844404/171907135-8f2d00dc-5f26-4875-8288-89510890d54b.mov
> Details on demand admin UI

- grapher/controls/Controls.tsx
- grapher/core/Grapher.tsx
> Hide related question when target is current page

- adminSiteServer/apiRouter.ts
- grapher/detailsOnDemand/detailsOnDemand.tsx
- grapher/text/MarkdownTextWrap.tsx
Thanks @marcelgerber for ID-ing this one. Constructor names were getting minified, so string matching was breaking. Switched to the better technique and validated on [staging](https://ptolemy-owid.netlify.app/grapher/annual-inflation-of-consumer-prices?country=Landlocked+developing+countries+%28LLDCs%29~Least+developed+countries+%28LDCs%29~Small+Island+Developing+States+%28SIDS%29) 👍
> DoD static exports superscript fix

- grapher/core/LegacyToOwidTable.test.ts
enhance: add passing unit test that documents the current weird day/year join behaviour
> Add test for weird day/year join behaviour

- site/LongFormPage.tsx
> remove stray zero

- clientUtils/Util.ts
- site/Feedback.tsx
Working towards #1458 | Live on _tufte_.
These are the last three uses of `XMLHttpRequest` in our code.
I tested all of them work fine on _tufte_.
> feat: use fetch in place of XMLHttpRequest

- site/Byline.tsx
- site/LongFormPage.tsx
- site/PostCard/PostCard.tsx
- site/formatting.test.ts
- site/formatting.tsx
> fix: format authors for bibtex

- adminSiteClient/SuggestedChartRevisionApproverPage.tsx
The current behaviour is not ideal, but as a minimal first step, document it more clearly.
See: #1626
> doc: improve help text for updating chart suggestions

- site/blocks/expandable-paragraph.scss
- wordpress/web/app/plugins/owid/src/ExpandableParagraph/ExpandableParagraph.js
Adding headings so that Joe can have larger sections of content hidden behind a "Continue reading" button
https://user-images.githubusercontent.com/11844404/187698489-96210fcf-7307-473d-af9c-1eb34e287ca6.mov
> Support headings in Expandable Paragraph

- adminSiteClient/GrapherConfigGridEditor.tsx
- devTools/schemaProcessor/columns.json
- grapher/schema/grapher-schema.002.json
- grapher/schema/grapher-schema.002.yaml
This PR adds the schema for details on demand and removes the now obsolete selectedData
> Schema update: removed selectedData, added details on demand

- Makefile
Add conventional Makefile commands that make deployment and staging simpler.
> chore: add "make deploy" and "make stage" helpers

- adminSiteClient/DimensionCard.tsx
- adminSiteClient/EditorBasicTab.tsx
> fix(admin): properly propagate dimension updates

- adminSiteClient/GrapherConfigGridEditorTypesAndUtils.tsx
- site/formatting.tsx
We had two lint warnings again, fixed those
> fix: fix minor lint issues

- adminSiteServer/apiRouter.ts
- adminSiteServer/authentication.tsx
- adminSiteServer/exportGitData.ts
- adminSiteServer/gitDataExport.ts
- db/dataSource.ts
- db/db.ts
- db/model/Chart.ts
- db/model/Dataset.ts
- package.json
- yarn.lock
Live on [tufte](https://tufte.owid.cloud/admin/charts).
There were [lots of breaking changes in the update to 0.3](https://github.com/typeorm/typeorm/blob/master/CHANGELOG.md#030-2022-03-17) - I've done my best to adapt to them, and everything seems to work fine.
> chore(deps): update typeorm to 0.3

- adminSiteClient/ColorSchemeDropdown.tsx
- adminSiteClient/EditorColorScaleSection.tsx
- adminSiteClient/EditorCustomizeTab.tsx
- adminSiteClient/EditorMapTab.tsx
- adminSiteClient/GrapherConfigGridEditor.tsx
- clientUtils/Util.ts
- grapher/color/ColorSchemes.ts
- grapher/color/CustomSchemes.ts
Reconfigures the order of color schemes to show a few preferred schemes first for every chart type in the admin
> Suggest good default color schemes

- site/blocks/BiographyCard.scss
Natasha noticed an overflow bug for biography cards on mobile. She has verified that this fixes it.
[Staging demo](https://ptolemy.owid.cloud/admin/posts/preview/22815)
https://user-images.githubusercontent.com/11844404/191531466-11edd381-51ca-43d7-bb2a-d7e528440375.mov
> Fix biography card breakpoints

- adminSiteServer/IndexPage.tsx
- site/Head.tsx
- site/blocks/KeyInsights.scss
- site/blocks/front-matter.scss
- site/blocks/research-and-writing.scss
- site/css/footer.scss
- site/css/page.scss
- site/css/topic-page.scss
- site/css/typography.scss
Another round of feedback from Marwa
[Staging demo](https://ptolemy.owid.cloud/admin/posts/preview/50414)
Changes:
- Various typography touchups, mostly switching to using the mixins where possible
- Adding Playfair 600 (semibold) to our webfonts
- Added support for an expandable paragraph in the Explorer section
> Topic page typography polish

- clientUtils/countries.ts
this is not really used AFAIK but it could lead to weird suprises later on and is an easy fix
> fix: fix some codes for country redirects missing

- adminSiteClient/DimensionCard.tsx
- adminSiteClient/EditorBasicTab.tsx
- adminSiteClient/EditorDataTab.tsx
- adminSiteClient/VariableSelector.tsx
- adminSiteClient/admin.scss
Live on [tufte](https://tufte.owid.cloud).
The drag-and-drop behaviour in our admin has been subpar at best, and thanks to @danyx23 we have a great library now with `react-beautiful-dnd`.
With this, we can get great and intuitive drag & drop, and can drop some pretty awful code at the same time 🙌🏻 
There are also some small style touchups to make it just that little bit more beautiful!
https://user-images.githubusercontent.com/2641501/191289283-9eb96261-27eb-428a-ae1f-4ff1b6169001.mp4
> refactor(admin): rework EditorBasicTab & EditorDataTab with react-beautiful-dnd

- devTools/cypress/integration/kitchenSink.js
- site/blocks/ProminentLink.tsx
- site/blocks/front-matter.scss
- site/blocks/prominent-link.scss
- site/blocks/research-and-writing.scss
- site/css/mixins.scss
A rewrite of the Prominent Link CSS to get it to play nice with our new columns.
[Staging demo](https://ptolemy.owid.cloud/admin/posts/preview/50492)
~@mlbrgl could you check these out for usecases I may have missed? I'm not sure what the lightbox interaction is, for example.~ Done.
> Prominent links with Grid

- site/LongFormPage.tsx
A slight improvement to the accuracy of our verbiage. 🙂
> "Cite our work" -> "Cite this work"

- grapher/mapCharts/MapChart.tsx
Hi there Owid gang!
_tl:dr: Moves European map viewport slightly eastwards so that Cyprus is visible in all screen sizes_
I was playing around with the grapher, kicking the proverbial tires, and figured I might take a stab at a small issue. So this is an attempt at a fix for #1428. 
In narrow viewports (such as on mobile phones) Cyprus was being cropped out of the European map as the viewport was centred too far westwards. The fix was small, nudging the center of the viewport for the European map 3 percentage points eastward. I found that was the happy medium to still have the westernmost part of Europe (Iceland) visible and this came out better than playing around with the projections for Europe. On larger screen sizes the change is barely noticible.
* Load a map chart
* Select Europe …
> fix: Move European map viewport slightly eastwards

- db/model/Variable.ts
- settings/serverSettings.ts
Fix for https://github.com/owid/owid-grapher/issues/1717
> fix(duckdb): fix random segfaults

- devTools/docker/refresh-grapher-data.sh
This commit creates a temp variable that is initialized with a default value instead
> fix: SKIP_CHARTDATA use collided with set -o nounset

- grapher/mapCharts/AnnotationGenerator.ts
- grapher/mapCharts/MapChart.tsx
- grapher/mapCharts/MapChartConstants.ts
- Code cleanup
- Algorithm tweak
- Comments
> feat(annotations): final changes

- packages/@ourworldindata/utils/src/owidTypes.ts
- site/css/colors.scss
- site/css/variables.scss
- site/gdocs/OwidArticle.tsx
- site/gdocs/centered-article.scss
> SDG: custom header color

- adminSiteClient/GdocsIndexPage.tsx
- adminSiteClient/GdocsPublicationContext.tsx
- adminSiteClient/GdocsSettingsForm.tsx
- baker/siteRenderers.tsx
- db/migration/1668613887314-AddPublicationContextColumn.ts
- db/model/Gdoc.ts
- db/wpdb.ts
- packages/@ourworldindata/utils/src/index.ts
- packages/@ourworldindata/utils/src/owidTypes.ts
> 1762-gdocs-publication-context

- packages/@ourworldindata/grapher/src/detailsOnDemand/detailsOnDemand.scss
> 1790 dod wrapping safari

- db/gdocBlockParsersRawToEnriched.ts
- db/gdocUtils.ts
- packages/@ourworldindata/utils/src/index.ts
- packages/@ourworldindata/utils/src/owidTypes.ts
- site/gdocs/ArticleBlock.tsx
- site/gdocs/MissingData.scss
- site/gdocs/MissingData.tsx
- site/owid.scss
> feat(gdocs): add missing data block

- Makefile
Make it easier to run SVG testing on your local machine with the "make svgtest" helper.
> chore: add "make svgtest" to run SVG tester locally

- adminSiteClient/DatasetEditPage.tsx
As was [democratically decided yesterday](https://owid.slack.com/archives/C3D58HF26/p1671485377899149), the dataset page is now way simpler and always shows a simple `VariableList`:
> feat(admin): always show variable list on dataset page

- README.md
- make "Quick start" section more prominent
- help scan through section with emoticons
> docs: reorganize README

- devTools/explorerTools/extractGrapherIds.ts
- devTools/explorerTools/extractSubtitlesAndNotes.ts
- devTools/explorerTools/tsconfig.json
- explorer/ExplorerDecisionMatrix.ts
- tsconfig.json
Creating a tool to extract subtitles and notes from existing explorers in order to check they are all parsed by the grammar.
> dev: create explorer extraction tool

- site/SiteSubnavigation.tsx
- site/countryProfileProjects.ts
see https://owid.slack.com/archives/C46U9LXRR/p1675358366635589
> refactor(country profiles): couple landing slug to subnav

- packages/@ourworldindata/grapher/src/captionedChart/readme.md
Assumed that the author meant "interactive" rather than "interfactive" in the readme.md
> Fixing a typo

- db/exportMetadata.ts
- db/migration/1676018297069-AddPageviewsTable.ts
Part of https://github.com/owid/analytics/pull/70
> enhance(mysql): exclude pageviews from export

- adminSiteClient/DatasetEditPage.tsx
- adminSiteServer/apiRouter.ts
Initial database query for `isArchived` field:
UI change:
Confirmation modal:
Operation result:
Fixes #1879
> Add archive dataset functionality on Admin panel

- adminSiteServer/testPageRouter.tsx
- db/model/Chart.ts
Just a small PR to get rid of another any type
> nit: properly type Chart config in typeorm Chart definition

- adminSiteClient/DatasetEditPage.tsx
> Add explanatory note about the archive button

- adminSiteClient/DatasetEditPage.tsx
- adminSiteClient/GdocsEditLink.tsx
- db/Variable.test.ts
- db/model/Gdoc/Gdoc.ts
- db/model/Gdoc/archieToGdoc.ts
- db/model/Gdoc/rawToArchie.ts
- db/tests/basic.test.ts
- packages/@ourworldindata/utils/src/DetailsOnDemand/detailsOnDemand.tsx
Was getting bored of seeing these pile up below every single PR.
> Fix various eslint warnings

- site/GrapherPage.tsx
> fix: convert subtitle to plaintext for social media cards

- .yarn/patches/react-codemirror2-npm-7.2.1-dcadbb9383.patch
- adminSiteClient/Admin.tsx
- adminSiteClient/admin.scss
- adminSiteServer/IndexPage.tsx
- package.json
- site/owid.scss
- yarn.lock
These are some small changes that we will need for Vite, and that we can safely apply already, so the effective diff is a bit smaller in the end.
> Some small vite preparations

- baker/postUpdatedHook.ts
- db/syncPostsToGrapher.ts
Also make the syncPostsToGrapher script more robust to deal with drafts that have no authors assigned yet.
> fix: fix sql query for postUpdateHook with no authors

- packages/@ourworldindata/grapher/src/captionedChart/Logos.tsx
- packages/@ourworldindata/grapher/src/footer/Footer.tsx
- packages/@ourworldindata/grapher/src/footer/FooterManager.ts
- Apparently, we were not showing the origin URL in external embeds??
- Similarly, the OWID logo was a link when embedded on our site, but not when it was external.
> fix: fix inverted linking logic

- packages/@ourworldindata/grapher/src/barCharts/DiscreteBarChart.test.ts
- packages/@ourworldindata/grapher/src/barCharts/DiscreteBarChart.tsx
> fix(DiscreteBar): fix country names overlapping with time label

- packages/@ourworldindata/grapher/src/sourcesTab/SourcesTab.scss
Simple enough, and fixes https://owid.slack.com/archives/C02706JNFC6/p1680185368251889
> fix(css): correctly display ul inside source description

- packages/@ourworldindata/grapher/src/timeline/TimelineComponent.tsx
- packages/@ourworldindata/utils/src/TimeBounds.ts
> fix: fix timeline displaying wrong year

- baker/ExplorerBaker.tsx
- baker/SiteBaker.tsx
> fix(baker): remove old explorers

- adminSiteClient/ChartEditor.ts
- adminSiteClient/ChartEditorPage.tsx
- adminSiteClient/EditorReferencesTab.tsx
- adminSiteServer/apiRouter.ts
- baker/algolia/indexToAlgolia.ts
- db/model/Pageview.ts
- packages/@ourworldindata/utils/src/index.ts
- packages/@ourworldindata/utils/src/owidTypes.ts
> feat(admin): display pageview numbers

- .github/scripts/buildkite_destroy_staging.py
- .github/workflows/buildkite.yml
Update python to get rid of warning and fix branch (it was target, now it is source branch).
> fix(github_actions): update python and fix target branch

- packages/@ourworldindata/grapher/src/core/Grapher.tsx
Relates to #2136
Turns off relative mode for faceted stacked area/bar charts that are split by metric as a hot fix for #2136. Can be reverted once #2136 is properly addressed.
Luckily we don't have existing charts that are split by metric and have relative mode enabled by default ([Datasette](https://owid-datasette-y43qr.ondigitalocean.app/owid?sql=select%0D%0A++facetStrategy,%0D%0A++count(*)+as+freq%0D%0Afrom%0D%0A++(%0D%0A++++select%0D%0A++++++id,%0D%0A++++++slug,%0D%0A++++++config+-%3E%3E+%22$.selectedFacetStrategy%22+as+facetStrategy%0D%0A++++from%0D%0A++++++charts%0D%0A++++where%0D%0A++++++(%0D%0A++++++++type+%3D+'StackedArea'%0D%0A++++++++or+type+%3D+'StackedBar'%0D%0A++++++)%0D%0A++++++and+(%0D%0A++++++++--+user+can+configure+relative+mode%0D%0A++++++++config+-%3E%3E+%22$.hideRelati …
> fix(facet): turn off relative mode for stacked charts split by metric

- baker/GrapherBaker.tsx
Fixes https://github.com/owid/owid-grapher/pull/2184
> fix(GrapherBaker): prevent race condition if someone edits chart variable during baking

- adminSiteServer/apiRouter.ts
- baker/GrapherImageBaker.tsx
- db/migration/1683577595565-ChartAddGeneratedColumns.ts
Related datasette PR: https://github.com/owid/owid-datasette/pull/12
> feat(migrate): add generated columns for chart slug and type

- package.json
- yarn.lock
Fixes https://owid.slack.com/archives/CQQUA2C2U/p1684485967941479
> 🔨 add @types/node-fetch as dev dependency

- adminSiteClient/DatasetList.tsx
- adminSiteClient/DatasetsIndexPage.tsx
- adminSiteServer/apiRouter.ts
Improves admin datasets table:
- renames "Dataspace" column to "Namespace"
- adds three columns:
- dataset short name
- version
- number of charts
> enhance(admin): add short name, version and number of charts to datasets table

- site/gdocs/centered-article.scss
Resolves  #2300
We'll need to make sure the HTML being used is valid as these classes make some assumptions about how it's structured. The tables in the Homicide data article had `<b>` tags that weren't closed properly. (I've added a font-weight rule so those tags aren't necessary anymore, but you get the point)
I've tested it with normal `<p>` tags as well and they look nice too 🙂 
```
html: <table class="html-table"><tr><td>WHO Mortality Database</td><td><p>Hello how’s it going. Aliquam gravida nunc et porta vestibulum. Duis tristique libero id eros pretium semper ut eget arcu</p><p>Duis id semper nunc. Suspendisse ultricies elit non diam viverra viverra.</p><ul><li>Use highly standardized definition of homicide</li><li>Exclude law enforcement and criminal justice data, because their …
```
> ✨ add .html-table class styles

- packages/@ourworldindata/grapher/src/barCharts/DiscreteBarChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedDiscreteBarChart.tsx
Reported on [Slack](https://owid.slack.com/archives/C5BDCB2R3/p1686592695700159)
> Fix label alignment in discrete bar charts

- adminSiteClient/gdocsDeploy.ts
- db/model/Gdoc/Gdoc.ts
- db/model/Gdoc/rawToEnriched.ts
- site/css/grid.scss
- site/gdocs/ArticleBlock.tsx
- site/gdocs/OwidGdoc.tsx
- site/gdocs/ResearchAndWriting.scss
- site/gdocs/topic-page.scss
A small handful of bugs exposed when recreating the Poverty topic page.
> Topic page fixes

- db/migration/1686637499720-ReplaceVariablesDataPath.ts
Point all data and metadata paths to the new Data API.
> :tada: fetch data and metadata from the new Data API

- packages/@ourworldindata/utils/src/owidTypes.ts
- site/DataPageContent.scss
- site/DataPageContent.tsx
> datapages misc fixes

- site/DataPage.tsx
- site/DataPageContent.scss
- site/DataPageContent.tsx
- site/ExpandableAnimatedToggle.scss
- site/ExpandableAnimatedToggle.tsx
- site/ExpandableToggle.scss
- site/ExpandableToggle.tsx
- site/blocks/StickyNav.scss
- site/blocks/expandable-paragraph.scss
- site/css/mixins.scss
- site/gdocs/centered-article.scss
- site/owid.scss
This PR contains minor - mostly visual - changes surfaced by the design QA. 
See the following threads for the exhaustive list of changes applied:
- https://owid.slack.com/archives/C04L4BHSFSB/p1686214859287869
- https://owid.slack.com/archives/C04L4BHSFSB/p1686241110227159
> datapages design QA

- baker/Deployer.ts
buildAndDeploySite would return a "0" error code, even if one of the remote SSH scripts would have returned a non-zero error code. 
This PR not only halts the deploy in case of an error but also makes buildAndDeploySite return a non-zero error code, thus making sure the parent caller - buildkite - recognizes something has gone wrong and doesn't systematically grant a green check mark when the script exits.
How I've tested this:
- add a failing script [here](https://github.com/owid/owid-grapher/blob/8f2e030342d692005f2cb0493ef34d8f40635451/baker/Deployer.ts#L227), e.g. `errorScript: "thisCommandDoesNotExist",`
- run `yarn buildAndDeploySite hans`
- check the exit code: `echo $?` -> 1
> fix(buildAndDeploy): return with non zero if ssh step fail

- adminSiteClient/GdocsPreviewPage.tsx
This fixes scroll persistence from #2328 on Chrome, possibly due to a race condition.
> refactor(gdoc preview): scroll iframe on page load

- adminSiteClient/GdocsPreviewPage.tsx
Just a little QOL thing
https://github.com/owid/owid-grapher/assets/11844404/3b3d11a4-2176-4b1f-ac1f-091ecb7fb1ea
> 🎉 preserve scrollY on gdoc refresh

- packages/@ourworldindata/grapher/src/footer/Footer.tsx
reported by Pablo A on [Slack](https://owid.slack.com/archives/C03NV9Z3YSV/p1687430849276629)
Likely introduced in #2339
> fix(grapher): remove underlines from license links

- site/blocks/ExpandableParagraph.tsx
- site/blocks/expandable-paragraph.scss
Another little QOL thing asked for by Marwa
https://github.com/owid/owid-grapher/assets/11844404/62bb6f39-8827-43e6-ad7d-0941610cc7a8
> 🎉 update scrollY when collapsing expandable-parapraph

- explorer/Explorer.tsx
- packages/@ourworldindata/grapher/src/chart/ChartManager.ts
- packages/@ourworldindata/grapher/src/chart/ChartUtils.tsx
- packages/@ourworldindata/grapher/src/controls/entityPicker/EntityPicker.tsx
- packages/@ourworldindata/grapher/src/controls/entityPicker/EntityPickerConstants.ts
- packages/@ourworldindata/grapher/src/selection/SelectionArray.ts
fixes #1008 
My third attempt to make embedded explorers respect the entity type.
> fix(explorer): respect entity type when explorer is embedded

- site/DataPageContent.tsx
- site/ExpandableToggle.scss
- site/ExpandableToggle.tsx
- see [slack](https://owid.slack.com/archives/C04L4BHSFSB/p1687537919389129)
- preview: http://staging-site-datapages/admin/grapher/banana-production
> feat(exp toggle): add teaser

- site/DataPageContent.scss
- site/DataPageContent.tsx
_Data pages_
- dark header
- full width separation after key information
> enhance(dp): dark header

- site/gdocs/ChartStory.tsx
- site/gdocs/centered-article.scss
As part of #2331.
Before and after:
> ✨ chart-story: visual touchups

- explorer/GrapherGrammar.ts
See [Slack](https://owid.slack.com/archives/C46U9LXRR/p1687880966985589)
> feat(explorer): allow to show/hide relative toggle

- site/DataPage.tsx
- site/GrapherFigureView.tsx
> fix(dp): bind chart to url

- adminSiteClient/GdocsPreviewPage.tsx
Fixes the issue that can be seen in https://github.com/owid/owid-grapher/issues/2393#issuecomment-1618532764.
This was happening because the `currentGdoc` variable was still holding the state from _before_ the fetch happened, and so if the slug was updated _while_ the fetch ran it would be reset to what it was before when the fetch finished.
I fixed this by rewriting it to use the ["updater function" version of the `setGdoc` call](https://react.dev/reference/react/useState#updating-state-based-on-the-previous-state).
---
Somewhat relatedly, but not necessarily something we need to address in this PR already: I was thinking that some things would probably be easier if we split the `originalGdoc` and `currentGdoc` states into two? I don't know the exact reason why they're one state right …
> fix(gdocs-admin): update gdocs state based on the latest state

- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/tooltip/Tooltip.tsx
Fixes two issues I spotted through Bugsnag:
- https://app.bugsnag.com/our-world-in-data/our-world-in-data-website/errors/64aedc36e43b1600081b1c1f
- https://app.bugsnag.com/our-world-in-data/our-world-in-data-website/errors/64183754fdbf9500085db2dd
> Fix Bugsnag bugs

- baker/SiteBaker.tsx
This should be optimized further to not rebake/resize every image on every bake, but because this is breaking deploys this is a temporary quick fix.
> 🔨 bake gdoc images in chunks

- site/gdocs/OwidGdocPage.tsx
I just noticed we were using the wrong value for our gdocs articles' `og:description` `<meta>` tag, which was why social media previews of the new [SDG index page](https://ourworldindata.org/sdgs) have "[Research and data to make progress against the world’s largest problems](https://github.com/owid/owid-grapher/blob/7b011c36454773b7506a2deb342ca190d342fce5/site/Head.tsx#L20)" as their description text.
[Datasette query](https://owid-datasette-y43qr.ondigitalocean.app/owid?sql=SELECT%0D%0A%09slug%2C%0D%0A%09content-%3E%3E%22%24.excerpt%22+AS+excerpt%2C%0D%0A%09content-%3E%3E%22%24.subtitle%22+AS+subtitle%0D%0AFROM+posts_gdocs+pg%0D%0AWHERE+published+%3D+true+AND+NOT%28content-%3E%3E%22%24.type%22+%3D+%22fragment%22%29)
```mysql
SELECT
slug,
content->>"$.excerpt" AS excerpt, …
```
> 🐛 use content.excerpt for gdocs social media previews

- adminSiteClient/ChartEditor.ts
- adminSiteClient/EditorReferencesTab.tsx
- adminSiteServer/apiRouter.ts
- db/migration/1689678362613-RemoveLegacySdgChartReferences.ts
> refactor: remove SDG reference tracking

- site/DataPage.tsx
- site/DataPageContent.tsx
> fix(embeds): don't bind embedded charts to window url by accident

- adminSiteServer/LoginPage.tsx
When authors use a staging server admin they are often puzzled about the user/password screen because normally we use cloudflare. This PR adds hints with the default password
> Add password hints

- db/migration/1690795517408-FixChartConfigDisplayShortUnitNull.ts
- packages/@ourworldindata/grapher/src/schema/grapher-schema.003.yaml
We want to remove this at some point but while we don't we should make the schema reflect reality
> Add .map.columnSlug to schema

- db/migration/1689688196662-OwidTeamDefaultGdocsAuthor.ts
- db/model/Gdoc/Gdoc.ts
[See slack thread](https://owid.slack.com/archives/C040429G2SD/p1689688002774359?thread_ts=1689686397.684999&cid=C040429G2SD)
> 🎉 Change default author to 'Our World in Data team'

- packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.scss
- packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.tsx
- packages/@ourworldindata/grapher/src/captionedChart/Logos.tsx
- packages/@ourworldindata/grapher/src/controls/ActionButtons.scss
- packages/@ourworldindata/grapher/src/controls/ActionButtons.tsx
- packages/@ourworldindata/grapher/src/controls/ContentSwitchers.scss
- packages/@ourworldindata/grapher/src/header/Header.tsx
- packages/@ourworldindata/grapher/src/timeline/TimelineComponent.scss
Collection of small style changes according to the designs
> Small styling adjustments

- packages/@ourworldindata/grapher/src/axis/Axis.ts
- packages/@ourworldindata/grapher/src/footer/Footer.scss
- packages/@ourworldindata/grapher/src/footer/Footer.tsx
Update footer layout according to the new designs:
- moves license and origin url to the bottom
- render sources on top and note next to action buttons
> Update footer layout

- packages/@ourworldindata/grapher/src/core/Grapher.tsx
hot fix for ongoing design review
> Don't scale up base font size

- packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.scss
- packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.tsx
- packages/@ourworldindata/grapher/src/controls/ActionButtons.scss
- packages/@ourworldindata/grapher/src/controls/ActionButtons.tsx
- packages/@ourworldindata/grapher/src/controls/ContentSwitchers.scss
- packages/@ourworldindata/grapher/src/controls/ContentSwitchers.tsx
- packages/@ourworldindata/grapher/src/controls/ShareMenu.scss
- packages/@ourworldindata/grapher/src/core/grapher.scss
- packages/@ourworldindata/grapher/src/footer/Footer.scss
- packages/@ourworldindata/grapher/src/footer/Footer.tsx
- packages/@ourworldindata/grapher/src/header/Header.tsx
- packages/@ourworldindata/grapher/src/timeline/TimelineComponent.scss
- packages/@ourworldindata/grapher/src/timeline/TimelineComponent.tsx
- site/gdocs/Chart.tsx
General improvements and various bug fixes
> Address design feedback

- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/footer/Footer.scss
- packages/@ourworldindata/grapher/src/modal/DownloadModal.scss
- packages/@ourworldindata/grapher/src/modal/DownloadModal.tsx
- packages/@ourworldindata/grapher/src/modal/EmbedModal.scss
- packages/@ourworldindata/grapher/src/modal/EmbedModal.tsx
- packages/@ourworldindata/grapher/src/modal/EntitySelectorModal.scss
- packages/@ourworldindata/grapher/src/modal/EntitySelectorModal.tsx
- packages/@ourworldindata/grapher/src/modal/Modal.scss
- packages/@ourworldindata/grapher/src/modal/Modal.tsx
- packages/@ourworldindata/grapher/src/modal/SourcesModal.scss
- packages/@ourworldindata/grapher/src/modal/SourcesModal.tsx
> Grapher Redesign: Modals

- packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.tsx
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/core/GrapherConstants.ts
- packages/@ourworldindata/grapher/src/footer/Footer.tsx
- Makes the font size smaller for static charts
- Update style of details rendered at the bottom of static charts
> Grapher redesign: Improve static charts

- packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.tsx
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/modal/EntitySelectorModal.scss
- packages/@ourworldindata/grapher/src/modal/EntitySelectorModal.tsx
- Update style according to the new designs
To do:
- Style checkboxes (will be done after Christian's code has been merged)
> Grapher redesign: Update style of the entity picker

- packages/@ourworldindata/grapher/src/axis/Axis.ts
- packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.tsx
- packages/@ourworldindata/grapher/src/controls/ActionButtons.scss
- packages/@ourworldindata/grapher/src/controls/ContentSwitchers.scss
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/slopeCharts/SlopeChart.tsx
- Use the default cursor for tabs
- Use pointers for buttons
- Prevent charts from overflowing
> Grapher redesign: Various bug fixes

- packages/@ourworldindata/grapher/src/footer/Footer.scss
- packages/@ourworldindata/grapher/src/footer/Footer.tsx
- support markdown in sources text
- counteract style leaks on wordpress pages
> Grapher redesign: Bug fixes

- packages/@ourworldindata/grapher/src/stackedCharts/StackedDiscreteBarChart.tsx
Fixes #2574.
Let's see what the svg checker has to say here 👀
> fix: StackedDiscreteBarChart can invert colors

- explorer/Explorer.tsx
- packages/@ourworldindata/grapher/src/controls/Checkbox.scss
- packages/@ourworldindata/grapher/src/controls/Checkbox.tsx
- packages/@ourworldindata/grapher/src/controls/ContentSwitchers.scss
- packages/@ourworldindata/grapher/src/core/grapher.scss
- packages/@ourworldindata/grapher/src/index.ts
- packages/@ourworldindata/grapher/src/modal/DownloadModal.scss
- packages/@ourworldindata/grapher/src/modal/DownloadModal.tsx
- packages/@ourworldindata/grapher/src/modal/EntitySelectorModal.scss
- packages/@ourworldindata/grapher/src/modal/EntitySelectorModal.tsx
Adds a `<Checkbox />` component that is used in various places:
- In the download tab
- In the embed tab (explorer only)
- In the entity selector tab
> Grapher redesign: Style checkboxes

- packages/@ourworldindata/utils/src/MarkdownTextWrap/parser.test.ts
- packages/@ourworldindata/utils/src/MarkdownTextWrap/parser.ts
> fix(md-parser): properly handle parens inside bold sequence

- site/blocks/research-and-writing.scss
- site/gdocs/ResearchAndWriting.scss
see https://owid.slack.com/archives/C05JT7FUVRS/p1694020733055229
> fix: r&w block typography and spacing

- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/utils/src/Util.ts
These are two changes we need to make for https://github.com/owid/cloudflare-workers/pull/12 to work well.
> enhance: small changes needed for thumbnails worker

- db/migration/1694549232436-IterableResearchAndWriting.ts
- db/model/Gdoc/enrichedToRaw.ts
- db/model/Gdoc/exampleEnrichedBlocks.ts
- db/model/Gdoc/gdocUtils.ts
- db/model/Gdoc/rawToArchie.ts
- db/model/Gdoc/rawToEnriched.ts
- packages/@ourworldindata/utils/src/owidTypes.ts
- site/gdocs/ResearchAndWriting.scss
- site/gdocs/ResearchAndWriting.tsx
Resolves https://github.com/owid/owid-grapher/issues/2630
Moves the grey box to another (now optional) text-only section below the other rows, and allows an arbitrary number of primary and secondary links.
This seems like the easiest way to make the R&W block more flexible without having to dramatically overhaul the component logic.
The gdocs with R&W blocks will need to be updated and republished by the authors if they want to rename the heading for the more section. (For example, the Poverty page currently has "More Key Articles on Poverty" as the heading for its grey box, and "More Articles on Poverty" as a row heading. This will be a noticeable repetition once they're placed next to one another)
Test archie:
```
{.research-and-writing}
[.primary]
title: Extreme poverty: how far have …
```
> Research and writing redesign

- baker/algolia/indexExplorersToAlgolia.ts
> fix(algolia): index explorers even if they're grapherId-powered

- explorer/Explorer.scss
- packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.tsx
- packages/@ourworldindata/grapher/src/controls/Checkbox.scss
Some more bug fixes.
- increase minimum height of grapher charts in explorers
- prevent long legends in scatter plots from overflowing
> Grapher redesign: Bug fixes & small improvements

- adminSiteClient/ChartEditor.ts
- adminSiteClient/VariableSelector.tsx
- adminSiteServer/apiRouter.ts
- db/migration/1696240121675-RecreateActiveDatasetsViewToIncludeNewColumns.ts
> feat(admin): display dataset version in variable picker

- packages/@ourworldindata/grapher/src/header/Header.tsx
Fixes a minor visual glitch in the new design
> fix(grapher): remove extra line below subtitle

- explorer/Explorer.tsx
Make sure explorers fetch data from the right Data API url.
> :bug: fix DATA_API_URL for explorers on staging

- adminSiteClient/ChartIndexPage.tsx
Small thing, big quality-of-life impact :)
Allows to search for `SlopeChart` or `Map`, for example.
> feat(admin): allow chart search by chart type

- package.json
- yarn.lock
We've recently had some issues with Lerna when it froze for no reason. I had to reinstall it to make it work. I'm bumping up its version to 6.0.x, hoping it would fix it. (>=6.1 wouldn't build)
> :honeybee: update lerna

- db/model/Chart.ts
> Add 1834 and 1835 to the list of public parent tags

- site/Feedback.tsx
Waiting on https://github.com/owid/cloudflare-workers/pull/16
> enhance: use new CF worker for sending feedback

- packages/@ourworldindata/grapher/src/dataTable/DataTable.scss
- packages/@ourworldindata/grapher/src/dataTable/DataTable.tsx
Solved this following issue by making minimal changes in the DataTable.scss. 
Issue No. #2767
> Fixed separator lines gap issue.

- packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.tsx
- packages/@ourworldindata/grapher/src/controls/Controls.scss
- packages/@ourworldindata/grapher/src/controls/LabeledSwitch.scss
- packages/@ourworldindata/grapher/src/controls/SettingsMenu.scss
fixes a style leak on the chart revision page, example: https://owid.cloud/admin/suggested-chart-revisions/review/35415
> fix(grapher): style leak on chart revision page

- packages/@ourworldindata/utils/src/index.ts
- packages/@ourworldindata/utils/src/string.ts
- site/DonatePage.tsx
- site/css/donate.scss
- site/css/forms.scss
- site/css/mixins.scss
- site/gdocs/topic-page.scss
- site/owid.scss
- site/stripe/DonateForm.tsx
closes #2737, #2890, #2744
- staging (see top of the stack)
This the [v1 of #proj-donor-page](https://owid.slack.com/archives/C060QED1YJV/p1698858247135849)
> we won't change the underlying infrastructure in this iteration
we won't change any of the flows or processes
adding names to /funding will still use the current semi-manual process
we won't change the thank-you page
we won't change the content or location (WP) of the /funding page
instead, we're going to focus on delivering the redesigned form and adding FAQs to /donate
> Donation form update

- db/migrateWpPostsToArchieMl.ts
- db/model/Gdoc/gdocUtils.ts
- db/model/Gdoc/htmlToEnriched.ts
- db/model/Gdoc/rawToEnriched.ts
- site/gdocs/centered-article.scss
Changes:
- Fixes small typo that was resulting in newlines not being migrated
- Automated a component conversion that was going to have to be done ~75 times.
Still TODO: See https://github.com/orgs/owid/projects/16/views/1?pane=issue&itemId=43280749
> Linear topic pages migration improvements

- site/ChartsIndexPage.tsx
- site/CountriesIndexPage.tsx
- site/CountryProfilePage.tsx
- site/ExplorerPage.tsx
- site/GrapherPage.tsx
- site/SiteFooter.tsx
- site/SiteHeader.tsx
- site/SiteNavigation.scss
- site/SiteNavigation.tsx
- site/runSiteFooterScripts.ts
- site/search/SearchPage.tsx
see [this conversation](https://owid.slack.com/archives/C060QED1YJV/p1700584909995919) for the reasoning behind:
- hide the flag on the mobile site
- hide the flag on problematic desktop pages (all charts, explorer pages)
> ✨ (donate) add navigation flag

- site/Feedback.tsx
> :hammer: make email optional in feedback form

- site/DonatePage.tsx
- site/css/donate.scss
https://owid.slack.com/archives/C060QED1YJV/p1700824298501669?thread_ts=1700764200.030039&cid=C060QED1YJV
> ✨ (donate) add faq button

- site/DataPageContent.scss
- site/css/chart.scss
Show the chart in a data page at full width
> Data pages: show chart as full width

- site/DataPageV2Content.tsx
Show a default thumbnail image for cases where no explicit thumbnail is available
> :hammer: show default thumbnail if none is available

- packages/@ourworldindata/utils/src/metadataHelpers.ts
- site/DataPageV2Content.tsx
Various minor tweaks to the citation block
> improve-citation-block

- Makefile
It now checks if you have installed the AWS CLI, and whether you have configured it, before letting you proceed.
> :honeybee: Add preflight check for "make sync-images"

- db/model/Gdoc/GdocBase.ts
- db/model/Gdoc/GdocDataInsight.ts
- db/model/Gdoc/GdocPost.ts
- packages/@ourworldindata/components/src/styles/mixins.scss
- packages/@ourworldindata/components/src/styles/typography.scss
- packages/@ourworldindata/utils/src/index.ts
- packages/@ourworldindata/utils/src/owidTypes.ts
- site/AnnotatingDataValue.scss
- site/gdocs/OwidGdoc.tsx
- site/gdocs/pages/DataInsight.scss
- site/gdocs/pages/DataInsight.tsx
- site/owid.scss
The view for a specific data insight (no baking yet)
testing data:
https://docs.google.com/document/d/1o8PtWZOUsdr_j31y6-kKI-mbSRVWqzWe5m1fsN6EPl0
https://docs.google.com/document/d/117Z5d_gF1ONg8UaOeAFjGxahv1oRxuVPM69S7lZWZKc
https://docs.google.com/document/d/1g8GiNLfo2p2nTuDzrJy96fFhfsi1FSQwS8PhweCfwvc
https://docs.google.com/document/d/1K3nc9c0WlrEjsJkJ770mVVKmbCOiZZmByDXcatl76VU
https://docs.google.com/document/d/1DdgUxo8mFC90EZ14wwOGABP90t4GTEQ_JrZXuW0Cpqc
> Data Insight Page

- adminSiteClient/SourceList.tsx
I made a dumb mistake of changing the original array.
> :bug: fix SourceList with more than max sources

- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/core/GrapherInterface.ts
> :sparkles: (grapher) reflect "Show selection only" toggle in the URL

- packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.tsx
> :bug: (data-table) wait for data to be loaded before rendering

- packages/@ourworldindata/grapher/src/schema/grapher-schema.003.yaml
Add missing defaults to Grapher schema:
- `stackMode` default is `absolute`
- `axis.facetDomain` default is `shared`
> :honeybee: (schema) add missing defaults

- packages/@ourworldindata/components/src/ExpandableToggle/ExpandableToggle.scss
- packages/@ourworldindata/components/src/IndicatorProcessing/IndicatorProcessing.scss
- packages/@ourworldindata/components/src/IndicatorSources/IndicatorSources.scss
- packages/@ourworldindata/grapher/src/modal/SourcesModal.scss
- packages/@ourworldindata/grapher/src/modal/SourcesModal.tsx
- site/blocks/KeyInsights.scss
- relates to #3008 
- fixes style leaks in gdoc articles and topic pages (but not Wordpress articles)
> :bug: (sources) fix style leaks for charts embedded in gdoc articles

- adminSiteClient/GdocsEditLink.tsx
- adminSiteClient/GdocsPreviewPage.tsx
[An ez 'n' small request from Natasha](https://owid.slack.com/archives/C03G5HF66DD/p1702250146342959)
> 🎉 add link to live article in admin preview for published gdocs

- baker/SiteBaker.tsx
- db/model/Chart.ts
This PR replaces the source of the `bakeEmbeds()` function with a DB content graph query.
It excludes embeds in gdocs posts since we don't do anything with them yet.
Some stats:
- previously: 1654 baked embeds
- now: 387
This is likely because this query now excludes embeds in Wordpress posts which slugs have been overridden by gdocs posts.
> refactor: bake embeds from DB content graph

- site/css/homepage.scss
- site/gdocs/OwidGdocPage.tsx
Some small fixes we noticed immediately after publishing the new homepage
> 🐛 Homepage fixes

- baker/SiteBaker.tsx
- packages/@ourworldindata/components/src/GdocsUtils.ts
- packages/@ourworldindata/components/src/index.ts
- site/gdocs/components/ResearchAndWriting.scss
- site/gdocs/components/ResearchAndWriting.tsx
demo: http://staging-site-fix-first-rw/co2-and-greenhouse-gas-emissions#research-writing
[slack](https://owid.slack.com/archives/C06KFK86HST/p1709724263614749)
> fix(r&w): tablet styles for first featured article

- packages/@ourworldindata/grapher/src/horizontalColorLegend/HorizontalColorLegends.tsx
Improves hover interaction for horizontal colour legends.
https://github.com/owid/owid-grapher/assets/12461810/32edee22-71ab-4edf-b166-3ec292818099
https://github.com/owid/owid-grapher/assets/12461810/bbc0a71c-6a08-43d1-a2d4-613ab80d3663
> ✨ (legend) improve hover interaction

- packages/@ourworldindata/grapher/src/slopeCharts/SlopeChart.tsx
- Follow up to #3321 
- Shows a list of selected entities that don't have data for the current time pair
- We only do this if we get "space for free", i.e. if there is a legend on the side with dead space below it
- Example chart: [Live](https://ourworldindata.org/grapher/child-mortality-1960-vs-latest-slope?country=~DEU) / [Staging](http://staging-site-slope-no-data/grapher/child-mortality-1960-vs-latest-slope?country=~DEU) (note that Germany is selected in both)
| <img width="730" alt="Screenshot 2024-03-21 at 14 58 54" src="https://github.com/owid/owid-grapher/assets/12461810/29858229-afa9-48a1-89e4-03d80c4e5597"> | <img width="730" alt="Screenshot 2024-03-21 at 14 58 32" src="https://github.com/owid/owid-grapher/assets/12461810/50557db1-734b-4e …
> ✨ (slope) list selected entities without data

- adminSiteServer/apiRouter.ts
- baker/GrapherBaker.tsx
- db/model/Post.ts
Cleanup of the code that accesses the posts table
> 🔨 clean up posts access via knex

- adminSiteServer/apiRouter.ts
There were a few more queries that probably typeorm allowed in this form but that knex seems to want as explicit parameters
> 🐛 fix more insert queries

- packages/@ourworldindata/grapher/src/core/Grapher.jsdom.test.ts
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/modal/EmbedModal.tsx
> Always add tab param to embed URL

- packages/@ourworldindata/utils/src/index.ts
- packages/@ourworldindata/utils/src/regions.test.ts
- packages/@ourworldindata/utils/src/regions.ts
- site/search/SearchUtils.tsx
Just some utils.
Not used yet, but will be used in the upstream PRs.
> enhance(search): Search utils

- adminSiteClient/gdocsValidation.ts
> 🔨 make excerpt mandatory again

- adminSiteClient/ChartEditor.ts
Show the chart preview in desktop mode by default
> 🐛 (admin) open chart in desktop preview mode by default

- site/gdocs/components/centered-article.scss
> Update prominent links design

- packages/@ourworldindata/components/src/Checkbox.scss
- packages/@ourworldindata/grapher/src/controls/RadioButton.scss
- packages/@ourworldindata/grapher/src/controls/RadioButton.tsx
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/core/GrapherConstants.ts
- packages/@ourworldindata/grapher/src/core/grapher.scss
- packages/@ourworldindata/grapher/src/core/typography.scss
- packages/@ourworldindata/grapher/src/entitySelector/EntitySelector.scss
- packages/@ourworldindata/grapher/src/entitySelector/EntitySelector.tsx
- packages/@ourworldindata/grapher/src/modal/EntitySelectorModal.tsx
- packages/@ourworldindata/grapher/src/modal/Modal.scss
- packages/@ourworldindata/grapher/src/modal/Modal.tsx
- packages/@ourworldindata/grapher/src/selection/SelectionArray.ts
- packages/@ourworldindata/grapher/src/sidePanel/SidePanel.scss
- packages/@ourworldindata/grapher/src/sidePanel/SidePanel.tsx
- packages/@ourworldindata/grapher/src/slideInDrawer/SlideInDrawer.scss
- packages/@ourworldindata/grapher/src/slideInDrawer/SlideInDrawer.tsx
- packages/@ourworldindata/grapher/src/slopeCharts/SlopeChart.tsx
- packages/@ourworldindata/grapher/src/timeline/TimelineComponent.scss
- packages/@ourworldindata/grapher/src/timeline/TimelineComponent.tsx
[Cycle 2024.2: Entity selector](https://github.com/owid/owid-grapher/issues/3349) | [Designs](https://www.figma.com/file/X5mOEX8zULS6qyHocUYdmh/Grapher-UI?type=design&node-id=2523%3A6266&mode=design&t=7edFp79OOjz6RENz-1)
Visual overhaul of Grapher's entity selector (but no bigger new features added).
I addressed most of the feedback that I got so far, but I am still figuring these two things out:
- There is a tiny gap above the search bar on mobile
- The animation sometimes feels too fast, esp. for entities that are at the very bottom of a long list
The SVG tester fails due to the changes in #3373
> ✨ (entity selector) redesign

- devTools/svgTester/create-compare-view.ts
Adds a '--url' param to the create-compare-view script. This is useful if the script is run from a staging container.
> 🐝 (svg tester) add url param to create-compare-view script

- devTools/svgTester/verify-graphs.ts
Set a maximum number of workers for the SVG tester.
> 🐝 (svg tester) set max number of workers

- packages/@ourworldindata/core-table/src/CoreTable.ts
- packages/@ourworldindata/core-table/src/ErrorValues.ts
- packages/@ourworldindata/grapher/src/stackedCharts/StackedDiscreteBarChart.tsx
fixes #3464 by dropping negative values (excluding zero) in `transformTable`
> 🐛 (stacked discrete bar) remove negative values

- packages/@ourworldindata/grapher/src/entitySelector/EntitySelector.tsx
> ✨ (entity selector) sort World to top

- explorer/GrapherGrammar.ts
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
Add `missingDatStrategy` for explorers (requested by Pablo R)
@marcelgerber is there anything else we need to do here?
> ✨ (explorer) add missing data strategy

- explorer/GrapherGrammar.ts
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
Adds `minTime` and `maxTime` to explorers (requested by Pablo R)
> 🎉 (explorer) add minTime and maxTime to grapher grammar

- packages/@ourworldindata/grapher/src/scatterCharts/ScatterPlotChart.tsx
> 🐛 (scatter) fix legend interaction on mobile

- site/gdocs/OwidGdocPage.tsx
> Don't add citation metadata on author page

- packages/@ourworldindata/grapher/src/mapCharts/MapChart.tsx
> 🐛 (map) fix overflow of Asia on mobile / TAS-533

- site/css/grid.scss
- site/gdocs/components/ArticleBlock.tsx
- site/gdocs/components/Image.tsx
> Fix heading spacing in left column of sticky-right block

- adminSiteClient/EditorHistoryTab.tsx
fixes https://github.com/owid/owid-grapher/issues/3643
> ✨ (admin) fix Restore button / TAS-536

- baker/DeployUtils.ts
> ✨ don't throw error when looking up etl@ourworldindata.org on slack

- db/migration/1720038601815-RemoveEntitiesDisplayName.ts
A light tidy up of https://github.com/owid/owid-grapher/pull/3717
> :honeybee: Remove `displayName` field on entities

- baker/SiteBaker.tsx
- db/db.ts
Fixes https://github.com/owid/owid-grapher/issues/3514
During baking, we prefetch gdoc attachments so that if, for example, multiple articles embed a grapher chart, we don't have to make multiple calls to the DB to fetch that chart's config.
For charts and linked indicators, this was done unparsimoniously: we prefetched resources that weren't being used anywhere.
Fortunately, on foundation, this has a negligible effect as you can see from the build step timings for charts and indicators:
```
6270 charts 9s
2239 indicators 0s
```
But locally, when each of these requests needs to be made over https, prefetching would take ~10 minutes, often timing out.
This PR makes it so that we only prefetch resources that are actually used somewhere, which makes local prefetching take about a minute.
As …
> Smarter gdocs attachment prefetching

- adminSiteClient/EditorFeatures.tsx
> enhance(admin): enable x axis label for stacked bar charts

- site/AboutThisData.scss
- site/AboutThisData.tsx
- site/DataPageContent.scss
- site/DataPageV2Content.tsx
- site/KeyDataTable.scss
- site/KeyDataTable.tsx
- site/MetadataSection.scss
- site/MetadataSection.tsx
- site/TopicTags.scss
- site/TopicTags.tsx
- site/owid.scss
I checked what is currently in staging and designs in Figma to get a sense of what is most useful to extract. For example, multidimensional data page doesn't have a related charts section, so I didn't extract it. Let me know what you think about the code structure and whether extracting something else would make sense.
> Extract data page components

- packages/@ourworldindata/utils/src/image.ts
- site/gdocs/components/Image.tsx
They have a hard limit of 20k.
> Fix too many files generated for CF pages

- packages/@ourworldindata/grapher/src/controls/SettingsMenu.tsx
- packages/@ourworldindata/grapher/src/core/GrapherConstants.ts
- packages/@ourworldindata/grapher/src/scatterCharts/ScatterPlotChart.tsx
- packages/@ourworldindata/grapher/src/slopeCharts/SlopeChart.tsx
- packages/@ourworldindata/grapher/src/utils.ts
fixes #3849 by removing click-anywhere-to-dismiss-selection for scatter plots for now
> 🐛 (scatter) zoom-to-selection toggle

- adminSiteClient/Link.tsx
- adminSiteClient/admin.scss
I thought it would be nice to make it easier for users to see where they are in the admin.
> Add active state to admin nav

- adminSiteClient/EditorExportTab.tsx
> 🐛 (admin) keep selection when exporting mobile version

- packages/@ourworldindata/grapher/src/barCharts/DiscreteBarChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedDiscreteBarChart.tsx
Removes vertical grid lines from (stacked) discrete bar charts.
> ✨ (discrete bar) remove vertical grid lines

- packages/@ourworldindata/grapher/src/lineLegend/LineLegend.tsx
https://owid.slack.com/archives/C04VBQ00HQR/p1727786398102909?thread_ts=1727781784.845229&cid=C04VBQ00HQR
> ✨ (grapher) increase padding between line label and annotation

- adminSiteClient/DimensionCard.tsx
- adminSiteClient/admin.scss
- packages/@ourworldindata/types/src/domainTypes/CoreTableTypes.ts
> feat(admin): surface catalog path in chart dimensions editor

- Makefile
> :honeybee: Bake images on `make refresh.full`

- packages/@ourworldindata/grapher/src/mapCharts/MapChart.tsx
- packages/@ourworldindata/grapher/src/mapCharts/MapChartConstants.ts
Use a thinner stroke for country outlines on mobile
> ✨ (static chart) use thinner stroke width on mobile

- packages/@ourworldindata/grapher/src/lineLegend/LineLegend.tsx
Adding a couple of missing react keys in the line legend component.
> 🔨 add missing react keys

- packages/@ourworldindata/grapher/src/stackedCharts/AbstractStackedChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedAreaChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedBarChart.tsx
Make stacked bar and area charts a bit nicer to work with in Figma
> ✨ (stacked bar/area) optimise static version for Figma

- packages/@ourworldindata/grapher/src/scatterCharts/ScatterPlotChart.tsx
Fix the size scale during an animation.
Example: http://staging-site-scatter-animation-size/grapher/life-expectancy-vs-gdp-per-capita
> ✨ (scatter) fix size scale during an animation

- adminSiteServer/mockSiteRouter.tsx
- baker/SiteBaker.tsx
- site/DataInsightsIndexPage.tsx
- site/SiteConstants.ts
- site/SiteFooter.tsx
- site/gdocs/OwidGdocPage.tsx
- site/gdocs/pages/Homepage.tsx
- site/gdocs/utils.tsx
Awaiting approval from Marwa re: size of the "Follow us" box on the homepage
> ✨ Update social media links, refactor to use constants through site codebase

- db/migration/1730367515116-AddCatalogPathToDatasets.ts
Migration for https://github.com/owid/etl/pull/3475
> ✨ Add catalogPath column to datasets table

- adminSiteServer/authentication.tsx
Handle the error with the same pattern as elsewhere in the file.
Fixes: https://app.bugsnag.com/our-world-in-data/grapher-admin/errors/672a37bfd1461623267d57d7
> Fix express middleware receiving a non-error

- adminSiteServer/adminRouter.tsx
- adminSiteServer/apiRouter.ts
- adminSiteServer/app.test.tsx
- adminSiteServer/chartConfigR2Helpers.ts
- adminSiteServer/mockSiteRouter.tsx
- adminSiteServer/multiDim.ts
- baker/MultiDimBaker.tsx
- baker/SiteBaker.tsx
- db/model/Gdoc/GdocBase.ts
- db/model/MultiDimDataPage.ts
- functions/_common/grapherRenderer.ts
- functions/_common/grapherTools.ts
- functions/multi-dim/[slug].json.ts
- functions/package.json
- functions/tsconfig.json
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/types/src/domainTypes/Various.ts
- packages/@ourworldindata/types/src/gdocTypes/Gdoc.ts
- packages/@ourworldindata/types/src/grapherTypes/GrapherTypes.ts
- packages/@ourworldindata/types/src/index.ts
- packages/@ourworldindata/types/src/siteTypes/MultiDimDataPage.ts
- settings/clientSettings.ts
- site/gdocs/components/Chart.tsx
- site/multiDim/MultiDimDataPage.tsx
- site/multiDim/MultiDimDataPageContent.tsx
- site/multiembedder/MultiEmbedder.tsx
* Fix itty-router types in pages functions
* Add new Cloudflare Pages function to serve mdim configs
* Add equivalent route to mockSiteRouter
* Add special handling for mdims to
* Gdocs admin
* SiteBaker
* MultiEmbedder
* Chart site component
> Support using mdims in gdocs

- functions/donation/thank-you.ts
- packages/@ourworldindata/utils/src/DonateUtils.ts
- site/DonateForm.tsx
As requested by Charlie and Hassan.
I tested the changes locally, following the instructions in the README.
Fixes #4133
> Donate updates

- site/gdocs/pages/Author.scss
> Remove mix-blend-mode from author's profile picture

- package.json
- packages/@ourworldindata/components/package.json
- packages/@ourworldindata/core-table/package.json
- packages/@ourworldindata/explorer/package.json
- packages/@ourworldindata/grapher/package.json
- packages/@ourworldindata/types/package.json
- packages/@ourworldindata/utils/package.json
- yarn.lock
https://devblogs.microsoft.com/typescript/announcing-typescript-5-7/
> chore(deps): update to typescript 5.7

- adminSiteClient/ImagesIndexPage.tsx
Improves the UX a bit. See [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/accept).
> Accept only images in images admin file input

- site/gdocs/components/LatestDataInsights.scss
I verified the fix works on my iPhone.
> Fix latest data insights styles

- packages/@ourworldindata/grapher/src/controls/EntitySelectionToggle.tsx
The icon currently in use is not the one from the designs
> ✨ update entity selector toggle icon

- packages/@ourworldindata/grapher/src/barCharts/DiscreteBarChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedDiscreteBarChart.tsx
> ✨ (discrete bar) add more whitespace between bars / TAS-771

- db/migration/1736188395813-UpdateHousekeepingSuggestedReviews.ts
Column was wrongly assigned CHAR type. Should be INTEGER.
> Update db table types

- site/gdocs/components/Person.scss
- site/gdocs/components/Person.tsx
- Add underline on hover to person's name
- Link also from the person's image
> Make links to author pages more discoverable

- adminSiteServer/adminRouter.tsx
- baker/GrapherBaker.tsx
- baker/MultiDimBaker.tsx
- baker/SiteBaker.tsx
- db/model/Image.ts
- db/model/Post.ts
- packages/@ourworldindata/types/src/siteTypes/MultiDimDataPage.ts
- site/DataPageResearchAndWriting.tsx
- site/DataPageV2Content.tsx
- site/dataPage.ts
- site/multiDim/MultiDimDataPage.tsx
- site/multiDim/MultiDimDataPageContent.tsx
> Add Related research and writing to multi-dim pages

- packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.tsx
- packages/@ourworldindata/grapher/src/core/GrapherConstants.ts
- packages/@ourworldindata/grapher/src/footer/Footer.tsx
- packages/@ourworldindata/grapher/src/header/Header.tsx
---
This is **part 2 of 3 in a stack** made with GitButler:
- <kbd>&nbsp;3&nbsp;</kbd> #4529 
- <kbd>&nbsp;2&nbsp;</kbd> #4522 👈 
- <kbd>&nbsp;1&nbsp;</kbd> #4427
> 🔨 extract section class names into constants

- adminSiteClient/ImagesIndexPage.tsx
Brought to you by Fixit Friday! Code adapted from `Image.tsx`.
Resolves #4339
> Add download button to images admin

- site/SiteMobileCategory.tsx
> Fix aria-label of category toggle in nav on mobile

- site/gdocs/components/OwidGdocHeader.tsx
- site/gdocs/components/centered-article.scss
Resolves https://github.com/owid/owid-grapher/issues/4399
[Figma](https://www.figma.com/design/AljmDG39W6hNDeeuR6tcWV/Article?node-id=107-2200&t=UsFMEe7QH9Irk33p-0)
|**Before**|**After**|
|---|---|
|  ![Screen Shot 2025-02-03 at 15 10 12](https://github.com/user-attachments/assets/f0ea33da-5798-4e9d-a283-c09810a654d8) |  ![Screen Shot 2025-02-03 at 15 10 10](https://github.com/user-attachments/assets/300b30bd-d555-45fc-9f83-e83c38faa997) |
> ✨ Improve article header typography on small screen widths

- site/SiteNavigation.scss
- site/SiteNavigation.tsx
- site/SiteResources.tsx
- site/search/Autocomplete.scss
- site/search/Autocomplete.tsx
Resolves https://github.com/owid/owid-grapher/issues/4414
Compare to [Figma](https://www.figma.com/design/1jhQuEZiaEUP5sNICOp8r9/Nav-Bar-and-Menu?node-id=2001-1282&p=f&t=h31yOfZhS0r8bMSZ-0)
Everything _just_ manages to fit at the smallest md breakpoint 😮‍💨 
https://github.com/user-attachments/assets/7b11bb56-277b-438c-835e-2c6840cfebdd
> ✨ Site Nav Updates

- adminSiteClient/CreateDataInsightModal.tsx
Update copy in the DI creation modal
> ✨ update copy

- packages/@ourworldindata/explorer/src/Explorer.tsx
This is a small regression in https://github.com/owid/owid-grapher/pull/4583/files#diff-971cc9fd921f240c7bcf62a8e6e647d58d7cab2afc5e58e752b5dabdd0bd09f9 in the explorer entity selection, and I believe the previous behaviour makes some sense.
You can see the previous behaviour in action over on [tufte](https://tufte-owid.netlify.app/explorers/coronavirus-data-explorer?facet=none&country=USA~BRA~JPN~DEU~OWID_AFR~ALB&Metric=Confirmed+deaths&Interval=Cumulative&Relative+to+Population=true&Color+by+test+positivity=false).
https://github.com/user-attachments/assets/c15083a2-2ee9-4c3f-9a96-bf2f293f0e76
In the video, you can see how, when switching to a different explorer view that has less entities available, the now-unavailable entities are supposed to be faded out / disabled.
But currently on …
> enhance(explorer): use append-only `availableEntityNames`

- baker/sitemap.ts
- packages/@ourworldindata/explorer/src/Explorer.tsx
- packages/@ourworldindata/explorer/src/ExplorerGrammar.ts
- packages/@ourworldindata/explorer/src/ExplorerProgram.ts
- site/ExplorerPage.tsx
- site/Head.tsx
Resolves #3147.
Essentially, this entirely reverts #1650 and #1661.
> cleanup(explorer): remove `indexViewsSeparately`

- package.json
- packages/@ourworldindata/explorer/package.json
- packages/@ourworldindata/grapher/package.json
- site/owid.scss
- vite.config-common.mts
- yarn.lock
Nothing much has changed, but good to modernize.
https://vite.dev/blog/announcing-vite6
> chore(deps): update to vite 6.2

- packages/@ourworldindata/grapher/src/entitySelector/EntitySelector.scss
- packages/@ourworldindata/grapher/src/entitySelector/EntitySelector.tsx
Resolves https://github.com/owid/owid-grapher/issues/4206
| <img width="1287" alt="Screenshot 2025-03-05 at 14 52 07" src="https://github.com/user-attachments/assets/750ccebb-acab-47ae-afc4-0fbd289017c8" /> | <img width="1287" alt="Screenshot 2025-03-05 at 14 52 39" src="https://github.com/user-attachments/assets/1829c142-c940-479f-af71-8f64c8be48f9" /> |
> ✨ (entity selector) reposition clear button

- site/multiDim/MultiDimDataPageContent.tsx
Use the format for additional context that `logGrapherView` expects.
> Fix multi-dim analytics

- functions/donation/thank-you.ts
> Link to Stripe customer portal in thank you email

- functions/donation/_utils/checkout.ts
- functions/donation/_utils/constants.ts
- functions/donation/thank-you.ts
- packages/@ourworldindata/types/src/DonationTypes.ts
- site/DonateForm.tsx
- site/css/donate.scss
Annual donation option was requested by Hassan and Valerie.
Resolves #4665
| Desktop | Mobile |
| <img width="544" alt="image" src="https://github.com/user-attachments/assets/dac5fd18-cd78-4fa6-87ad-fbab07f9c27b" /> | <img width="376" alt="image" src="https://github.com/user-attachments/assets/3b3fc44d-a0ad-439d-bfd7-424ba8ceecce" /> | 
Follow the docs in [the README](https://github.com/owid/owid-grapher/blob/add-annual-donation/functions/README.md#donationdonate).
Testing transactions I created:
* [Monthly subscription](https://dashboard.stripe.com/test/payments/pi_3R51H8G3kasqfjHR1eCtVQJN)
* [Annual subscription](https://dashboard.stripe.com/test/payments/pi_3R51JvG3kasqfjHR01MKGHJ0)
> Add annual donation option

- site/DonateForm.tsx
- site/css/donate.scss
Fix donate buttons sizes and variants
* Make sure they are the same height
* Make every.org button primary and Stripe button secondary for users
from the USA
Mention donor list inclusion in every.org section
> Donate page improvements

- baker/algolia/utils/explorerViews.ts
Fixes https://our-world-in-data.sentry.io/issues/34114463/?project=4508607592464464
https://github.com/owid/owid-content/commit/6f17c705d331a13380e9a52f3d319c9a51054625 added a novel method of configuring indicator-based explorers that leveraged the `duplicate` transform to create different views of the same indicator. This method doesn't specify each column's `yVariableIds` in the decision matrix, so the algolia indexing script was failing as it relies on these values for metadata wrangling purposes.
This PR fixes that by extracting the indicator IDs from the duplicate transforms and pushing them into the corresponding row's `yVariableIds` field, so that the indexing script can work on them as if they're regular indicator-based explorer rows.
1. Make sure your `owid-content` repo is on …
> 🐛 fix indexing explorers powered by duplicate transforms

- packages/@ourworldindata/grapher/src/mapCharts/ChoroplethMap.tsx
- packages/@ourworldindata/grapher/src/mapCharts/GeoFeatures.ts
- packages/@ourworldindata/grapher/src/mapCharts/MapChart.tsx
- packages/@ourworldindata/grapher/src/mapCharts/MapChartConstants.ts
Moves the Choropleth component to its own file.
---
This is **part 1 of 3 in a stack** made with GitButler:
- <kbd>&nbsp;3&nbsp;</kbd> #4708 
- <kbd>&nbsp;2&nbsp;</kbd> #4707 
- <kbd>&nbsp;1&nbsp;</kbd> #4706 👈
> 🔨 move ChoroplethMap to its own file

- site/gdocs/pages/GdocPost.tsx
Possibly fixes: https://github.com/owid/owid-grapher/issues/4701
> 🐛 fix deprecation notice full-width flashing

- baker/archival/ArchivalBaker.ts
- db/model/Chart.ts
Just polishing a bunch of things...
- **refactor(archive): refactor chart config fetching**
- **refactor(archive): split into baking method**
- **refactor(archive): factor more things out into own methods**
> refactor: archive baking

- package.json
- site/gdocs/components/Scroller.tsx
- yarn.lock
- **refactor(gdocs): implement scroller using `useIntersectionObserver`**
- **chore(deps): remove react-intersection-observer**
> refactor(gdocs): implement scroller using `useIntersectionObserver`

- packages/@ourworldindata/utils/src/Util.ts
Follow-up to #4729 
Before
After
---
This also makes `OwidGdodPageData` simpler, since the types coming from `extractGdocPageData` are now correct.
> feat: add typesafe pick

- adminSiteClient/imagesHelpers.ts
Fixes a small oversight in https://github.com/owid/owid-grapher/commit/7cdfffd9cb879948018244780ca5aa4a74b80693 that broke the data insight wizard's Figma integration
> 🐛 fix fileToBase64

- .clinerules
- CLAUDE.md
Add initial claude.md and .clinerules files
> Initial claude and clinerules versions

- .clinerules
- CLAUDE.md
- package.json
Add a typecheck command so that we can use `yarn typecheck` and have all files (including tests in the @packages subdirectories checked.
> 🐝 add a typecheck command that checks all TS files

- adminSiteClient/EditorCustomizeTab.tsx
- adminSiteClient/EditorFeatures.tsx
> ✨ (admin) allow setting y-min and max for stacked area and bar charts

- packages/@ourworldindata/explorer/src/Explorer.tsx
If a column is defined by duplicating an indicator via the `duplicate` transform, make sure the partial grapher config for that indicator is respected.
> 🐛 (explorer) respect partial grapher config of duplicated columns

- adminSiteClient/EditorColorScaleSection.tsx
- baker/GrapherBakingUtils.ts
- packages/@ourworldindata/components/src/MarkdownTextWrap/MarkdownTextWrap.tsx
- packages/@ourworldindata/components/src/TextWrap/TextWrap.tsx
- packages/@ourworldindata/core-table/src/CoreTableUtils.ts
- packages/@ourworldindata/grapher/src/axis/Axis.test.ts
- packages/@ourworldindata/grapher/src/axis/Axis.ts
- packages/@ourworldindata/grapher/src/color/BinningStrategies.ts
- packages/@ourworldindata/grapher/src/color/CategoricalColorAssigner.ts
- packages/@ourworldindata/grapher/src/color/ColorScale.ts
- packages/@ourworldindata/grapher/src/controls/entityPicker/EntityPicker.tsx
- packages/@ourworldindata/grapher/src/facetChart/FacetChart.tsx
- packages/@ourworldindata/grapher/src/horizontalColorLegend/HorizontalColorLegends.tsx
- packages/@ourworldindata/grapher/src/lineCharts/LineChart.tsx
- packages/@ourworldindata/grapher/src/lineLegend/LineLegendHelpers.ts
- packages/@ourworldindata/grapher/src/mapCharts/MapSparkline.tsx
- packages/@ourworldindata/grapher/src/scatterCharts/MultiColorPolyline.tsx
- packages/@ourworldindata/grapher/src/scatterCharts/ScatterPlotChart.tsx
- packages/@ourworldindata/grapher/src/scatterCharts/ScatterPoints.tsx
- packages/@ourworldindata/grapher/src/scatterCharts/ScatterPointsWithLabels.tsx
- packages/@ourworldindata/grapher/src/scatterCharts/ScatterSizeLegend.tsx
- packages/@ourworldindata/grapher/src/scatterCharts/ScatterUtils.ts
- packages/@ourworldindata/grapher/src/stackedCharts/MarimekkoChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedAreaChart.tsx
- packages/@ourworldindata/grapher/src/stackedCharts/StackedDiscreteBarChart.tsx
- packages/@ourworldindata/grapher/src/timeline/TimelineController.ts
- packages/@ourworldindata/utils/src/Util.ts
- packages/@ourworldindata/utils/src/index.ts
- packages/@ourworldindata/utils/src/metadataHelpers.ts
Switch usage of some of our custom functions to the alternatives provided by Remeda. I think we created the functions to get better type safety, which we now get from Remeda.
> Clean up utils

- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/modal/DownloadModal.tsx
> Fix mdim data download

- Makefile
- devTools/svgTester/export-graphs.ts
- devTools/svgTester/verify-graphs.ts
This is another step towards getting rid of `itsJustJavascript`. I tested all the changed commands to make sure they run.
> Switch to tsx in Makefile

- site/gdocs/components/KeyInsights.tsx
Fixes #4661. See the issue for reproduction steps.
> Fix error in key insights for certain URLs

- baker/DatapageHelpers.ts
- baker/GrapherBaker.tsx
- site/DataPageV2.tsx
- site/GrapherPage.tsx
- site/dataPage.ts
- site/multiDim/MultiDimDataPage.tsx
- site/multiDim/MultiDimDataPageContent.tsx
See Slack for [related discussion](https://owid.slack.com/archives/C071F90MD0X/p1745583603216919).
> Add meta title and description to mdim data page

- site/gdocs/OwidGdocPage.tsx
Adding [JSON-LD](https://developers.google.com/search/docs/appearance/structured-data/article) might help with our click-through rates ([as claimed by Google](https://developers.google.com/search/docs/appearance/structured-data/intro-structured-data)). It should make the Google search results prettier, with more context.
After we verify that it works and it is what we want, we can add more [types of JSON-LD](https://developers.google.com/search/docs/appearance/structured-data/search-gallery).
[Rich Results Test](https://search.google.com/test/rich-results/result/r%2Farticles?id=8ytCZbzmjvGVoU5OnemjXA). The crawl failure is unrelated. It happens because Cloudflare Pages previews set `X-Robots-Tag: noindex`.
> Add JSON-LD to gdoc posts

- adminSiteClient/EditorCustomizeTab.tsx
- adminSiteClient/EditorDataTab.tsx
> ✨ (admin) move the entity type section into the data tab

- adminSiteServer/apiRoutes/chartViews.ts
We must trigger a build if the updated narrative chart is used in an article.
[Slack discussion](https://owid.slack.com/archives/C46U9LXRR/p1745482169811779).
Check that a build is triggered when the narrative chart is used in an article.
> Fix narrative chart update lagging on prod

- .vscode/launch.json
- baker/algolia/utils/shared.ts
- package.json
- packages/@ourworldindata/grapher/src/core/FetchingGrapher.tsx
- packages/@ourworldindata/grapher/src/core/GrapherUseHelpers.tsx
- packages/@ourworldindata/types/src/index.ts
- packages/@ourworldindata/utils/src/index.ts
- site/GrapherWithFallback.tsx
- yarn.lock
feel free to merge this yourself, all commits are self-contained and atomic.
---
This is **part 2 of 2 in a stack** made with GitButler:
- <kbd>&nbsp;2&nbsp;</kbd> #4890 👈 
- <kbd>&nbsp;1&nbsp;</kbd> #4419
> Marcel's enhancements atop the grapher refactor

- adminSiteClient/DimensionCard.tsx
- adminSiteClient/EditorMapTab.tsx
Adds a note to both tolerance fields
> ✨ (admin) add help text for tolerance fields

- adminSiteClient/AdminSidebar.tsx
| <img width="155" alt="image" src="https://github.com/user-attachments/assets/954ccd01-d188-4049-9ae5-0fcc1fd2203d" /> | <img width="156" alt="image" src="https://github.com/user-attachments/assets/7f41cdc9-2f24-4193-b5af-3343204c2bca" /> |
> Align icons in admin sidebar

- package.json
- packages/@ourworldindata/grapher/src/controls/MapRegionDropdown.tsx
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/core/GrapherConstants.ts
- packages/@ourworldindata/grapher/src/mapCharts/ChoroplethGlobe.tsx
- packages/@ourworldindata/grapher/src/mapCharts/ChoroplethMap.tsx
- packages/@ourworldindata/grapher/src/mapCharts/GeoFeatures.ts
- packages/@ourworldindata/grapher/src/mapCharts/MapChart.tsx
- packages/@ourworldindata/grapher/src/mapCharts/MapChartConstants.ts
- packages/@ourworldindata/grapher/src/mapCharts/MapComponents.tsx
- packages/@ourworldindata/grapher/src/mapCharts/MapConfig.ts
- packages/@ourworldindata/grapher/src/mapCharts/MapHelpers.ts
- packages/@ourworldindata/grapher/src/mapCharts/MapTooltip.test.tsx
- packages/@ourworldindata/grapher/src/mapCharts/MapTooltip.tsx
- packages/@ourworldindata/grapher/src/tooltip/Tooltip.scss
- packages/@ourworldindata/utils/src/Util.ts
- packages/@ourworldindata/utils/src/index.ts
- yarn.lock
---
⧓ Review in [Butler Review `#9065aggVu`](https://gitbutler.com/sophiamersmann/owid-grapher/reviews/9065aggVu)
**🎉 add interactive globe**
16 commit series (version 61)
| Series | Commit Title | Status | Reviewers | 
| --- | --- | --- | --- |
| 16/16 | [🔨 fix rebase](https://gitbutler.com/sophiamersmann/owid-grapher/reviews/9065aggVu/commit/81575103-eade-4376-b224-10f3d3c08d69) | ⏳ |  |
| 15/16 | [🔨 minor refactor](https://gitbutler.com/sophiamersmann/owid-grapher/reviews/9065aggVu/commit/ded29674-d268-46e1-97db-c1dc525f4849) | ⏳ |  |
| 14/16 | [✨ add panning strategy for cursor outside of the globe](https://gitbutler.com/sophiamersmann/owid-grapher/reviews/9065aggVu/commit/02231f0d-ca59-4f08-afdf-f26cb0d7db5f) | ⏳ |  |
| 13/16 | [✨ improve globe …
> 🎉 add interactive globe / TAS-940

- _routes.json
- functions/multi-dim/[slug].json.ts
It worked fine with wrangler in both staging and local envs, but production is different...
> Fix mdims not working in gdocs in prod

- adminShared/validation.ts
- adminSiteClient/CreateNarrativeChartEditorPage.tsx
- adminSiteClient/EditorBasicTab.tsx
- adminSiteClient/NarrativeChartNameModal.tsx
- adminSiteClient/SaveButtons.tsx
- adminSiteServer/apiRoutes/narrativeCharts.ts
[Slack](https://owid.slack.com/archives/C071F90MD0X/p1748270599016159?thread_ts=1747993805.350349&cid=C071F90MD0X).
Please check that the validation works correctly.
> Add validation for narrative chart name

- adminSiteServer/apiRoutes/dods.ts
Fixes https://github.com/owid/owid-grapher/issues/4942
> 🐝 Standardize dod API response

- packages/@ourworldindata/grapher/src/controls/SearchField.tsx
- packages/@ourworldindata/grapher/src/entitySelector/EntitySelector.tsx
I dropped the event handler in a recent factor without noticing
> 🐛 fix selecting the first search result on enter

- site/gdocs/components/centered-article.scss
Part of https://github.com/owid/owid-grapher/issues/4851
| ![image](https://github.com/user-attachments/assets/b36350b9-eda3-46e4-b31a-866253712efb) | ![image](https://github.com/user-attachments/assets/e2e58862-8620-4cdb-88ff-001bc4cfc3b3) |
Check out the draft post "Two billion people don’t have safe drinking water"
> ✨ improve video alignment

- site/multiDim/MultiDimDataPageSettingsPanel.scss
- site/multiDim/MultiDimDataPageSettingsPanel.tsx
[Slack discussion](https://owid.slack.com/archives/C071F90MD0X/p1748420509861499).
Check that the dropdowns are fixed width on small screens. And that dropdowns row wraps under the heading when there isn't enough space.
> Mdim dropdowns layout improvements

- site/search/Search.scss
> fix(search): overflow long links

- packages/@ourworldindata/grapher/src/controls/Dropdown.scss
- packages/@ourworldindata/grapher/src/controls/Dropdown.tsx
- packages/@ourworldindata/grapher/src/controls/MapCountryDropdown.tsx
Adds continents to the mobile 'Zoom to...' dropdown.
Not sure why the first option is highlighted/focused when the dropdown is opened.
> 🎉 (map) add continents to mobile zoom dropdown

- site/multiDim/DimensionDropdown.scss
- site/multiDim/DimensionDropdown.tsx
- site/multiDim/MultiDimDropdowns.tsx
- site/multiDim/MultiDimEmbedSettingsPanel.scss
- site/multiDim/MultiDimEmbedSettingsPanel.tsx
Fixes missing background color and makes the calculation of collapsed count more robust.
> Fix mdim embed settings

- packages/@ourworldindata/grapher/src/controls/ActionButtons.scss
- packages/@ourworldindata/grapher/src/controls/ActionButtons.tsx
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
This new button is currently only ever shown in the archive.
See it in action: http://staging-site-action-button-donate:8789/latest/grapher/life-expectancy.html
[Slack discussion](https://owid.slack.com/archives/C04VBQ00HQR/p1749478367535579)
> feat(iframes): donate button

- adminSiteClient/MultiDimIndexPage.tsx
[Slack](https://owid.slack.com/archives/C071F90MD0X/p1750410987689389)
> Add link to example mdim and docs in admin

- site/multiDim/DimensionDropdown.scss
[Slack](https://owid.slack.com/archives/C071F90MD0X/p1750847557886759)
> Always show scrollbar when DimensionDropdown overflows

- site/search/DataCatalogRibbon.tsx
- site/search/SearchFilterPill.tsx
- site/search/TopicsRefinementList.tsx
Issue https://github.com/owid/owid-grapher/issues/4669. Standardization of tag names with "and" and "&" 
Step-by-step instructions on how to test this change
Go to https://ourworldindata.org/data and observe that ampersand (&) is used everywhere instead of the word "and".
> replace "and" with "&" in data labels

- packages/@ourworldindata/components/src/Checkbox.tsx
- packages/@ourworldindata/components/src/LabeledSwitch/LabeledSwitch.tsx
- packages/@ourworldindata/components/src/RadioButton.tsx
- packages/@ourworldindata/grapher/src/comparisonLine/ComparisonLine.tsx
- packages/@ourworldindata/grapher/src/scatterCharts/Triangle.tsx
- packages/@ourworldindata/grapher/src/sidePanel/SidePanel.tsx
- packages/@ourworldindata/grapher/src/tooltip/TooltipContents.tsx
To ease the mobx upgrade by a teeny tiny bit...
> refactor: turn some grapher components into functional components

- site/gdocs/components/centered-article.scss
| <img width="1265" height="386" alt="Screen Shot 2025-07-18 at 10 00 48" src="https://github.com/user-attachments/assets/7431e03e-aeb3-495f-85b8-7aef64372121" /> | <img width="1265" height="386" alt="Screen Shot 2025-07-18 at 10 01 07" src="https://github.com/user-attachments/assets/0f8fd25d-1447-4b1f-ac3e-32b23c0ae902" /> |
> ✨ fix video caption margin

- .gitignore
- db/tests/run-db-tests.sh
- devTools/docker/create-test-db.sh
- devTools/docker/wait-for-tests-mysql.sh
- vitest.db.config.ts
Reduce output of the dbtest suite 
I did this so tha it doesn't fill up the context of ai tools so much with meaningless log output
> make dbtest less noisy

- package.json
- packages/@ourworldindata/components/src/LabeledSwitch/LabeledSwitch.scss
- packages/@ourworldindata/components/src/styles/colors.scss
- packages/@ourworldindata/grapher/src/controls/CommandPalette.scss
- packages/@ourworldindata/grapher/src/core/grapher.scss
- site/css/footer.scss
- site/css/grid.scss
- site/gdocs/components/HomepageIntro.scss
- site/gdocs/components/centered-article.scss
- site/gdocs/components/topic-page.scss
- yarn.lock
- **chore(deps): update sass**
- **refactor: get rid of sass `color` warnings**
- **refactor: get rid of sass `map` warnings**
> refactor: update sass & get rid of some warnings

- package.json
- packages/@ourworldindata/components/package.json
- packages/@ourworldindata/core-table/package.json
- packages/@ourworldindata/explorer/package.json
- packages/@ourworldindata/grapher/package.json
- packages/@ourworldindata/types/package.json
- packages/@ourworldindata/utils/package.json
- yarn.lock
https://devblogs.microsoft.com/typescript/announcing-typescript-5-9/
> chore(deps): update typescript to 5.9

- packages/@ourworldindata/utils/src/regions.json
Automated update of regions data
TODOs:
> 🤖 Update regions [2025-08-06]

- packages/@ourworldindata/grapher/src/controls/ActionButtons.tsx
- packages/@ourworldindata/grapher/src/controls/ShareMenu.tsx
- packages/@ourworldindata/grapher/src/core/Grapher.tsx
- packages/@ourworldindata/grapher/src/core/GrapherConstants.ts
- packages/@ourworldindata/grapher/src/core/GrapherUrl.ts
- packages/@ourworldindata/grapher/src/footer/Footer.tsx
- packages/@ourworldindata/grapher/src/footer/FooterManager.ts
- packages/@ourworldindata/grapher/src/modal/DownloadModal.tsx
- packages/@ourworldindata/grapher/src/modal/EmbedModal.tsx
- packages/@ourworldindata/grapher/src/modal/SourcesModal.tsx
- packages/@ourworldindata/types/src/grapherTypes/GrapherTypes.ts
Adds `overlay=download-data` and `overlay=download-vis` to Grapher params
> 🎉 add query param for download overlay tab

- db/model/ExplorerViews.ts
Fixes poor performance of updating explorer views. The `refreshExplorerViewsForSlug` function now queries the existing view ids and then uses those to delete/update instead of using an inefficient where query.
Also adds an index on `explorer_views.explorerSlug` to make those queries not need a full table scan each time.
> Improve ExplorerViews performance with ID-based operations and index

- packages/@ourworldindata/explorer/src/Explorer.tsx
Alternative, improved implementation to #5332
Fixes csv based explorers not properly awaiting data loading, and also unifies our treatment of cancelling in-flight, outdated promises and applying the table transformations
Fixes #5331
> 🐛 fix broken csv based explorer

- packages/@ourworldindata/grapher/src/core/Grapher.tsx
Fixes the problem brought up here in Slack: https://owid.slack.com/archives/C46U9LXRR/p1756718367325909
> fix: disable `?overlay=embed` query param

- packages/@ourworldindata/utils/src/regions.json
Automated update of regions data
TODOs:
> 🤖 Update regions [2025-09-24]
